// The farmout capstone case files, generated by tools/course-waves/farmout/gen_course.py
// from the engine's own inputs (farmout_capstone.mjs --inputs). Only the capstone card
// imports this module: no panel preloads a case, and the graded answers are not
// stored anywhere in the app.
import ogbaku_case from './ogbaku_case.json?raw';
import umunze_case from './umunze_case.json?raw';
import akpugo_case from './akpugo_case.json?raw';

export const FARMOUT_CASE_FILES = {
  beginner: [
    { name: 'ogbaku_case.json', text: ogbaku_case },
  ],
  intermediate: [
    { name: 'umunze_case.json', text: umunze_case },
  ],
  advanced: [
    { name: 'akpugo_case.json', text: akpugo_case },
  ],
};
