-- ============================================================================
-- DR4 EXPERT DEEP SEED: Well Control, advanced tier.
--
-- Six modules, 26 lessons, 132 questions (15 per module bank plus a 42
-- question final exam). The structure row is GENERATED from the tier's
-- manifest.json rather than hand typed.
--
-- What this tier owns: the limit at the casing shoe. MAASP as the fracture
-- pressure there less the mud column above it, which makes it a ROCK limit at
-- a stated mud weight and means it FALLS as the mud weight rises. Kick
-- tolerance as two cases, shut in at the bottom and circulated to just below
-- the shoe with Boyle compression back to the entry volume, with the smaller
-- reported. Boyle on a single continuous bubble, conservative for a dispersed
-- influx and badly wrong for dissolved gas in oil-based mud, with the
-- isothermal and ideal assumptions erring in opposite directions and partly
-- cancelling. The sweep against mud weight, which sets the casing point.
--
-- THE FINDING THIS TIER IS BUILT ON, WHICH THE SWEEP PRODUCED RATHER THAN THE
-- PLAN. The slant well's kick tolerance falls nearly linearly from 7.814 m3 at
-- 1200 kg/m3 to zero at 1680. The horizontal well's is FLAT: 1.0776682353801654
-- at 1200 and 1.0792753276402405 at 1560, a RISE of two parts in a thousand
-- over 360 kg/m3 of mud weight. Its binding case is the circulated one, and
-- that case is limited by the 42.515647195 m of true vertical rise between its
-- bit and its shoe rather than by pressure. The distance does not move with
-- the mud weight, so neither does the tolerance. The usual well design lever
-- does not work on the well that needs it most, and module 4 says so.
--
-- FIVE THINGS TAUGHT IN m05 AND CERTIFIED NOWHERE: subsea and floating
-- operations, gas migration and volumetric control, dissolved gas in
-- oil-based mud, the casing pressure history, and multiphase influx
-- behaviour. 20260830_dr4_wellcontrol_go_live.sql asserts that no graded field
-- key names any of them.
--
-- Answer keys live only here and in academy_quiz_questions, which has no
-- client SELECT policy.
-- ============================================================================

insert into public.academy_course_structures
    (app_slug, tier, structure, content_version)
values ('wellcontrol', 'advanced', '{"modules":[{"key":"m01-maasp","title":"MAASP","lesson_keys":["l01-the-weakest-point","l02-the-definition","l03-it-changes-with-the-mud","l04-what-it-is-not","l05-reading-it-on-the-gauge"]},{"key":"m02-kick-tolerance","title":"Kick Tolerance","lesson_keys":["l01-the-question-it-answers","l02-the-shut-in-case","l03-the-circulated-case","l04-the-smaller-one-wins","l05-two-wells-two-answers"]},{"key":"m03-the-bubble","title":"The Bubble","lesson_keys":["l01-boyle-and-migration","l02-why-gas-is-worse","l03-the-single-bubble-assumption","l04-isothermal-and-ideal"]},{"key":"m04-planning-with-it","title":"Planning With It","lesson_keys":["l01-the-casing-point","l02-the-sweep-against-mud-weight","l03-what-a-zero-means","l04-the-numbers-that-go-in-a-programme"]},{"key":"m05-the-edges-of-the-model","title":"The Edges of the Model","lesson_keys":["l01-surface-bop-only","l02-vertical-hydrostatics","l03-no-friction-in-the-annulus","l04-no-time-and-no-migration-rate","l05-what-this-course-will-not-certify"]},{"key":"m06-the-expert-reading","title":"The Expert Reading","lesson_keys":["l01-the-story-so-far","l02-working-the-capstone","l03-onward"]}]}'::jsonb, 1)
on conflict (app_slug, tier) do update
  set structure = excluded.structure,
      content_version = excluded.content_version,
      active = true,
      updated_at = now();

delete from public.academy_quiz_questions
 where app_slug = 'wellcontrol' and tier = 'advanced';

insert into public.academy_quiz_questions
    (app_slug, tier, scope, module_key, ord, prompt, options, answer_index, explanation)
values
  ('wellcontrol', 'advanced', 'module', 'm01-maasp', 1, 'Which point in an open hole section is the weakest?', '["The bit, at the bottom of the hole.", "The casing shoe, because it is the shallowest exposed rock and therefore has the lowest fracture pressure.", "Whichever formation has the lowest compressive strength, identified from the logs run before the section was cased.", "The point of maximum dogleg, where the wellbore is most highly stressed by the geometry of the trajectory."]'::jsonb, 1, 'Shallowest exposed rock means least overburden and therefore the least resistance to fracturing.'),
  ('wellcontrol', 'advanced', 'module', 'm01-maasp', 2, 'Define MAASP.', '["The fracture pressure at the shoe less the hydrostatic pressure of the mud column above it.", "The pressure rating of the preventer stack.", "The highest pressure the casing string can withstand at its weakest connection, derated for wear and for temperature.", "The difference between the pore pressure and the fracture pressure at the shoe, expressed as a surface pressure."]'::jsonb, 0, 'It is the amount of surface pressure the shoe can take on top of the mud that is already there.'),
  ('wellcontrol', 'advanced', 'module', 'm01-maasp', 3, 'What happens to MAASP when the mud weight is raised?', '["It rises in proportion to the mud weight.", "It stays the same, since the fracture pressure at the shoe is a property of the rock and does not depend on the fluid.", "It falls, because more of the fracture pressure is being used by the mud column itself.", "It falls only until the mud weight reaches the pore pressure gradient, after which it becomes constant."]'::jsonb, 2, 'Making the well safer against taking a kick makes it less able to handle one it has already taken.'),
  ('wellcontrol', 'advanced', 'module', 'm01-maasp', 4, 'What kind of limit is MAASP?', '["A casing burst limit.", "A limit on the pressure rating of the annular preventer, which is the component that holds the annulus closed.", "An equipment limit set by the lowest rated component in the choke manifold and the surface pressure system.", "A rock limit at the shoe, valid only at the stated mud weight."]'::jsonb, 3, 'Casing and preventer ratings are separate limits, and the binding one is whichever is smallest.'),
  ('wellcontrol', 'advanced', 'module', 'm01-maasp', 5, 'Why must MAASP be recomputed after every mud weight change?', '["Because the mud column term in its definition changes, so the whole number changes with it.", "Because the fracture gradient changes too.", "Because the casing wear accumulates over time and the burst rating has to be derated at each recalculation.", "Because the shoe depth changes as the section is drilled deeper below the last casing point of the well."]'::jsonb, 0, 'It is not a fixed property of the well. It is a property of the well at a stated mud weight.'),
  ('wellcontrol', 'advanced', 'module', 'm01-maasp', 6, 'Where does the fracture pressure at the shoe come from?', '["A correlation with the pore pressure.", "A leak-off test performed after the casing was cemented and the shoe drilled out.", "The overburden gradient computed from the density log, reduced by a Poisson ratio taken from the sonic log data.", "The maximum pressure reached during the cement job, which establishes the strength of the formation below the shoe."]'::jsonb, 1, 'A prognosis is used before the test. The test replaces it as soon as it exists.'),
  ('wellcontrol', 'advanced', 'module', 'm01-maasp', 7, 'What does MAASP not tell you?', '["The mud weight currently in the hole.", "The maximum surface pressure the annular preventer can hold, which is a separate equipment limitation entirely.", "Whether the pressure at the shoe during circulation is safe, because it has no friction term in it.", "The pressure at which the formation below the shoe would begin to take fluid under a sustained injection."]'::jsonb, 2, 'It is a static limit and the Expert tier is explicit about what that costs during a circulation.'),
  ('wellcontrol', 'advanced', 'module', 'm01-maasp', 8, 'How is MAASP used during a kill?', '["As the target casing pressure.", "As the value the choke operator holds constant once the kill mud has arrived at the bit of the well.", "As the pressure at which the schedule begins, since the initial circulating pressure is derived from it.", "As a limit to compare the casing gauge against, rather than as a target to hold."]'::jsonb, 3, 'The drill pipe pressure is the target. The casing gauge is watched against the limit.'),
  ('wellcontrol', 'advanced', 'module', 'm01-maasp', 9, 'Why do operators apply a working margin below MAASP?', '["Because the calculated value carries known small errors and the consequence of exceeding it is severe.", "Because regulators require a fixed margin.", "Because the leak-off test overestimates the fracture pressure by an amount that depends on the cement quality.", "Because the mud weight is never known to better than a few kilograms per cubic metre in the active system."]'::jsonb, 0, 'The missing annulus friction term is one of the errors the margin absorbs.'),
  ('wellcontrol', 'advanced', 'module', 'm01-maasp', 10, 'What does it mean if the casing pressure exceeds MAASP during a kill?', '["The preventer will fail.", "The shoe is being fractured, and returns will be lost to the formation below it.", "The kill sheet was built with the wrong slow circulating rate pressure and the whole schedule is offset upward.", "The influx has reached the shoe and is passing into the cased section of the hole above it."]'::jsonb, 1, 'An underground blowout is the worst version of it, with the well flowing from one formation into another.'),
  ('wellcontrol', 'advanced', 'module', 'm01-maasp', 11, 'Which of these changes MAASP?', '["Changing the pump rate during a kill.", "Changing the choke setting, which alters the surface pressure and therefore the pressure being applied at the shoe.", "Changing the mud weight, which alters the column term in its definition.", "Changing the bit depth, since the shoe pressure depends on the length of open hole exposed below the casing."]'::jsonb, 2, 'The shoe depth and its fracture pressure are fixed. The mud weight is what moves.'),
  ('wellcontrol', 'advanced', 'module', 'm01-maasp', 12, 'Why is MAASP quoted alongside a mud weight rather than on its own?', '["Because it is only defined at a stated mud weight and is meaningless without one.", "Because the units require it.", "Because the mud weight determines which of the two casing shoes in a well is the binding constraint at that time.", "Because the fracture gradient at the shoe is expressed as an equivalent mud weight and the two must be consistent."]'::jsonb, 0, 'A MAASP with no mud weight beside it is an incomplete statement.'),
  ('wellcontrol', 'advanced', 'module', 'm01-maasp', 13, 'What is the relationship between MAASP and kick tolerance?', '["They are the same quantity.", "MAASP is the maximum surface pressure and kick tolerance is the maximum pit gain, and neither depends on the other.", "Kick tolerance sets the mud weight and MAASP is then computed from the mud weight that resulted from it.", "Kick tolerance asks how big an influx the MAASP headroom can absorb."]'::jsonb, 3, 'One is a pressure and the other is a volume, and the headroom at the shoe converts between them.'),
  ('wellcontrol', 'advanced', 'module', 'm01-maasp', 14, 'Which two numbers define MAASP completely?', '["The pore pressure and the mud weight.", "The fracture pressure at the shoe and the mud column above it.", "The shoe''s true vertical depth and its fracture equivalent mud weight, taken from the most recent leak-off test.", "The casing burst rating and the wear factor accumulated over the drilling of the section below it."]'::jsonb, 1, 'The second of those is itself a product of density, gravity and the shoe''s true vertical depth.'),
  ('wellcontrol', 'advanced', 'module', 'm01-maasp', 15, 'What does a low MAASP tell a well designer?', '["That the casing is under-rated.", "That the mud weight in use is below the pore pressure gradient and the well is at risk of taking a kick.", "That the section has little margin and that its casing point may need reconsidering.", "That the leak-off test was terminated early and should be repeated before the section is drilled any deeper."]'::jsonb, 2, 'The Expert tier turns exactly that observation into the casing point calculation.'),
  ('wellcontrol', 'advanced', 'module', 'm02-kick-tolerance', 1, 'What question does kick tolerance answer?', '["How large an influx the well can take and still be circulated out without fracturing the shoe.", "How long the well can be left shut in.", "What mud weight is required to balance the formation once the influx has been circulated out of the annulus.", "How much surface pressure the annular preventer can hold before it begins to leak past the closed element."]'::jsonb, 0, 'It is a volume, and it is the number a pit alarm setting should be compared against.'),
  ('wellcontrol', 'advanced', 'module', 'm02-kick-tolerance', 2, 'What does the shut-in case assume about the influx position?', '["That it has risen to just below the shoe.", "That it is distributed uniformly through the annulus from the bit up to the casing shoe of the section.", "That it sits at the bottom of the hole, where it entered.", "That it has been circulated to surface and its volume is measured in the trip tank at the choke manifold."]'::jsonb, 2, 'That is the moment the well is closed, before anything has been circulated.'),
  ('wellcontrol', 'advanced', 'module', 'm02-kick-tolerance', 3, 'What limits the influx height in the shut-in case?', '["The annulus capacity at the collars.", "The headroom at the shoe divided by the density difference between mud and influx.", "The distance between the bit and the casing shoe, since the influx cannot occupy more of the hole than exists.", "The pit gain recorded at the moment the well was closed, which fixes the volume and therefore the height."]'::jsonb, 1, 'It is a pressure divided by a gradient, and the result is a height that becomes a volume.'),
  ('wellcontrol', 'advanced', 'module', 'm02-kick-tolerance', 4, 'What does the circulated case assume?', '["That the influx stays at the bottom.", "That the influx has been partly dissolved into the mud and the residual volume is what reaches the casing shoe.", "That the influx has been circulated to surface and bled off through the choke without any expansion at all.", "That the influx has risen to just below the shoe and expanded on the way."]'::jsonb, 3, 'It is the moment the influx is at its most dangerous position relative to the shoe.'),
  ('wellcontrol', 'advanced', 'module', 'm02-kick-tolerance', 5, 'How is the circulated case converted back into an entry volume?', '["By Boyle compression from the pressure at the shoe back to the pressure at the bit where it entered.", "By dividing by the annulus capacity ratio.", "By subtracting the volume of mud displaced from the annulus during the circulation up to the casing shoe.", "By applying the pump efficiency correction, since the volume is measured in strokes rather than in cubic metres."]'::jsonb, 0, 'The graded answer is the volume at entry, which is what a pit gain would have shown.'),
  ('wellcontrol', 'advanced', 'module', 'm02-kick-tolerance', 6, 'Which of the two cases is reported as the kick tolerance?', '["The shut-in case, always.", "The smaller of the two, because the well has to survive both.", "The average of the two, weighted by the fraction of the operation spent in each of the two configurations.", "Whichever one corresponds to the kill method chosen, since the two methods place the influx differently."]'::jsonb, 1, 'Reporting the larger would certify a well against a condition it cannot actually survive.'),
  ('wellcontrol', 'advanced', 'module', 'm02-kick-tolerance', 7, 'On the slant well, which case binds?', '["The circulated case.", "Neither, since the two come out equal on that well by construction of the fixture used in the course.", "The shut-in case, because there is a large vertical gap between the shoe and the bit.", "It depends on the mud weight, with the circulated case binding below the pore pressure gradient."]'::jsonb, 2, 'A large gap means the influx can be tall at the bottom before the shoe notices, so the shut-in limit is generous.'),
  ('wellcontrol', 'advanced', 'module', 'm02-kick-tolerance', 8, 'And for the lateral, with its shoe barely above the bit?', '["The shut-in case, as on the slant well.", "Both equally, because the two cases converge whenever the wellbore is close to horizontal at the bottom.", "Neither, because a horizontal well cannot take a conventional influx and the calculation does not apply.", "The circulated case, because the shoe sits only a few tens of metres above the bit in true vertical depth."]'::jsonb, 3, 'The influx has almost nowhere to rise, so the geometry rather than the pressure sets the limit.'),
  ('wellcontrol', 'advanced', 'module', 'm02-kick-tolerance', 9, 'Why does the horizontal well''s tolerance barely change with mud weight?', '["Because its binding case is limited by geometry rather than by pressure, and the geometry does not move.", "Because its fracture gradient is higher.", "Because the annulus capacity in a lateral is larger, so a given volume of influx occupies a shorter length.", "Because the mud weight cancels out of the Boyle compression when the influx is close to the casing shoe."]'::jsonb, 0, 'The rise available is fixed, so the volume at the shoe is fixed, and only the compression correction moves.'),
  ('wellcontrol', 'advanced', 'module', 'm02-kick-tolerance', 10, 'What is the shoe headroom?', '["The difference between the two gauges.", "The fracture pressure at the shoe less the pressure the mud column already puts there.", "The volume of influx that can be accommodated below the shoe without the pressure there exceeding its limit.", "The vertical distance between the casing shoe and the bit, which is what the influx has available to rise through."]'::jsonb, 1, 'It is the same quantity as MAASP measured at the shoe rather than at surface.'),
  ('wellcontrol', 'advanced', 'module', 'm02-kick-tolerance', 11, 'What does a kick intensity of a given size represent?', '["The rate at which the influx enters.", "The severity of the kick expressed as a fraction of the maximum influx the well could tolerate at that mud weight.", "The pressure difference between the two shut-in gauge readings, converted into an equivalent mud weight.", "The amount by which the pore pressure exceeds the current mud weight, as a density."]'::jsonb, 3, 'It sets the underbalance that the tolerance calculation assumes, and it moves both cases.'),
  ('wellcontrol', 'advanced', 'module', 'm02-kick-tolerance', 12, 'Does the kick intensity affect MAASP?', '["Yes, in direct proportion.", "Yes, because a larger intensity implies a larger influx and therefore a lighter column in the annulus above it.", "No, because MAASP depends only on the fracture pressure and the mud column.", "Only in the circulated case, where the intensity determines how much the influx expands as it rises."]'::jsonb, 2, 'That is a useful check when working a capstone: some fields move with the intensity and some do not.'),
  ('wellcontrol', 'advanced', 'module', 'm02-kick-tolerance', 13, 'What is the influx density assumed in the tolerance calculation?', '["A default gas density, which the engine uses unless a different value is supplied.", "The density computed from the gauges.", "The density of the mud in the hole, reduced by the ratio of the pit gain to the total annulus volume of the well.", "Zero, which is the conservative assumption and gives the largest possible pressure deficit over the influx height."]'::jsonb, 0, 'Assuming gas is the conservative choice, because gas gives the largest deficit and the largest expansion.'),
  ('wellcontrol', 'advanced', 'module', 'm02-kick-tolerance', 14, 'Why is the single bubble assumption conservative for a dispersed influx?', '["Because dispersion reduces the volume.", "Because a dispersed influx is mixed with mud and provides more pressure than a continuous slug would.", "Because a dispersed influx cannot migrate, so it stays where it entered and never approaches the casing shoe.", "Because the engine reduces the influx density when the pit gain is small relative to the annulus volume."]'::jsonb, 1, 'Conservative in the useful direction: the model predicts a worse outcome than the real one.'),
  ('wellcontrol', 'advanced', 'module', 'm02-kick-tolerance', 15, 'What does a kick tolerance smaller than the pit alarm setting mean?', '["The alarm is set correctly.", "The kick tolerance calculation used the wrong annulus capacity and should be repeated with the collar value.", "The alarm would let the well take more than the standard procedure could handle.", "The well cannot be drilled any deeper without setting casing, regardless of what the pore pressure prognosis shows."]'::jsonb, 2, 'It is a two-number comparison that is rarely written down and directly links the design to the operation.'),
  ('wellcontrol', 'advanced', 'module', 'm03-the-bubble', 1, 'What does Boyle''s law say about a gas influx rising in the annulus?', '["Its volume stays constant as it rises.", "Its volume rises as the pressure around it falls, with the product of the two staying constant.", "Its pressure stays constant while its temperature falls, so the volume increases in proportion to the depth change.", "Its density falls in proportion to the distance travelled, which is why the expansion is largest near the surface."]'::jsonb, 1, 'Pressure times volume is constant, so most of the expansion happens in the last part of the rise.'),
  ('wellcontrol', 'advanced', 'module', 'm03-the-bubble', 2, 'Why does most of a gas influx''s expansion happen near surface?', '["Because the fractional change in pressure is largest there, and volume tracks the reciprocal of pressure.", "Because the annulus is widest near surface.", "Because the temperature falls as the gas rises, which reduces the pressure and allows the gas to expand further.", "Because the mud above the influx has already been displaced, so there is less resistance to the expansion."]'::jsonb, 0, 'Halving the pressure doubles the volume, and halving happens quickly at shallow depth.'),
  ('wellcontrol', 'advanced', 'module', 'm03-the-bubble', 3, 'What is gas migration?', '["The expansion of gas during a circulation.", "Movement of dissolved gas out of the base oil of an oil-based mud as the pressure falls during the circulation.", "Buoyant rise through static mud.", "The transfer of gas from the annulus into the drill string through a washout or a failed float valve."]'::jsonb, 2, 'It happens with the pumps off, which is exactly when nobody is watching a schedule.'),
  ('wellcontrol', 'advanced', 'module', 'm03-the-bubble', 4, 'What does migration do to the surface gauges in a shut-in well?', '["Lowers the casing pressure only.", "Leaves them unchanged, since the total weight of fluid in the annulus does not alter as the gas changes position.", "Raises the drill pipe gauge and lowers the casing gauge, because the gas displaces mud from one side to the other.", "Raises both of them, because the gas carries its pressure upward with it."]'::jsonb, 3, 'The gas keeps its original pressure while the mud that should be above it is now below it.'),
  ('wellcontrol', 'advanced', 'module', 'm03-the-bubble', 5, 'Why is gas worse than liquid at the moment of shut-in?', '["Its density is far below the mud''s, so the pressure it fails to provide over its height is much larger.", "It occupies more of the annulus.", "It dissolves into the mud, which raises the effective density of the column and disguises the size of the influx.", "It reaches the surface faster, so there is less time available to complete the calculations before it arrives."]'::jsonb, 0, 'One of two reasons gas is worse, and it applies before anything has been circulated at all.'),
  ('wellcontrol', 'advanced', 'module', 'm03-the-bubble', 6, 'Why is gas worse than liquid during the circulation?', '["It flows faster than liquid does.", "It expands as it rises, so its volume and its height both grow on the way up.", "It cools as it rises, which increases its density and causes it to fall back down through the mud column.", "It reacts with the mud additives, which changes the rheology and increases the annulus friction at the shoe."]'::jsonb, 1, 'A liquid influx does neither of those things to any comparable degree.'),
  ('wellcontrol', 'advanced', 'module', 'm03-the-bubble', 7, 'What is the single bubble assumption?', '["That the influx is made up entirely of gas.", "That the influx expands isothermally as it rises, following the ideal gas law with no departure from it.", "One continuous slug filling the annulus.", "That the influx remains at the bottom of the hole until the circulation reaches it and begins to move it upward."]'::jsonb, 2, 'Real influxes are dispersed, mixed with mud and concentrated on the high side of an inclined hole.'),
  ('wellcontrol', 'advanced', 'module', 'm03-the-bubble', 8, 'In which direction does the single bubble assumption err for a dispersed influx?', '["It is unsafe by a wide margin.", "It is exactly correct, since the total pressure deficit depends on the volume rather than on the distribution.", "It is unpredictable, because the direction depends on how much of the influx has mixed with the mud.", "It is conservative, because a dispersed influx provides more pressure than a slug does."]'::jsonb, 3, 'Conservative in the useful direction: the model predicts worse than reality.'),
  ('wellcontrol', 'advanced', 'module', 'm03-the-bubble', 9, 'For which influx is the single bubble assumption badly wrong?', '["Dissolved gas in an oil-based mud, which gives almost no pit gain and almost no casing pressure.", "A brine influx in a water-based mud.", "A large gas influx taken in a horizontal well, where the influx lies along the low side of the lateral section.", "Any influx taken while tripping, because the string is off bottom and the annulus geometry is different."]'::jsonb, 0, 'It comes out of solution suddenly and high in the annulus, which is the opposite of what the model expects.'),
  ('wellcontrol', 'advanced', 'module', 'm03-the-bubble', 10, 'What does the isothermal assumption do to the predicted expansion?', '["It understates the expansion.", "It overstates it, because a real gas cools as it expands and cooler gas occupies less volume.", "It has no effect, because the temperature of the annulus is set by the surrounding rock rather than by the gas.", "It makes the calculation indeterminate, since the gas law needs a temperature and none is supplied."]'::jsonb, 1, 'Isothermal means the surrounding fluid supplies whatever heat the expansion consumes, which is generous.'),
  ('wellcontrol', 'advanced', 'module', 'm03-the-bubble', 11, 'And treating the gas as ideal rather than real biases the answer how?', '["It overstates it at all pressures.", "It has no effect at the pressures encountered in well control, which are well within the ideal gas range.", "It understates it at high pressure, because a real gas is more compressible than an ideal one there.", "It makes the result depend on the gas composition, which is not known at the time of the calculation."]'::jsonb, 2, 'The compressibility factor departs from one at high pressure, and it departs downward.'),
  ('wellcontrol', 'advanced', 'module', 'm03-the-bubble', 12, 'What is the net effect of the two gas assumptions together?', '["They compound into a large error.", "They cancel exactly, which is why the simple form is used.", "They both err conservatively, so the result is safe.", "They partly cancel each other out, since one of the two overstates the expansion and the other understates it."]'::jsonb, 3, 'Partly, not exactly. The residual is small at the pressures this course works at.'),
  ('wellcontrol', 'advanced', 'module', 'm03-the-bubble', 13, 'Why is a full multiphase model not used here?', '["Because it needs data about the influx that nobody has at the time it would be used.", "Because it would be too slow to run.", "Because multiphase flow models are not accepted by the regulator for well control calculations of this type.", "Because the single bubble result is more accurate for the geometries this engine is designed to handle."]'::jsonb, 0, 'Composition, distribution and slip velocity are all unknown during an actual event.'),
  ('wellcontrol', 'advanced', 'module', 'm03-the-bubble', 14, 'What is the practical consequence of gas migration for a shut-in well?', '["Nothing, because the well is closed.", "The casing pressure rises with time and can eventually reach the MAASP with nothing being done.", "The influx volume increases, because the formation continues to flow as the gas rises away from the bottom.", "The kill mud weight requirement increases in proportion to the distance the gas has travelled upward."]'::jsonb, 1, 'Volumetric control is the wellsite procedure for managing it, and this engine has no time axis for it.'),
  ('wellcontrol', 'advanced', 'module', 'm03-the-bubble', 15, 'What does the course say about the casing pressure history?', '["It computes it stroke by stroke.", "It computes the peak value only, at the moment the influx passes the casing shoe, and reports it as the MAASP.", "It does not compute it, and kick tolerance is the closest available proxy.", "It derives it from the drill pipe schedule by subtracting the hydrostatic pressure of the annulus at each stroke."]'::jsonb, 2, 'Kick tolerance asks about the influx at the shoe, which is the peak of a history the model does not otherwise have.'),
  ('wellcontrol', 'advanced', 'module', 'm04-planning-with-it', 1, 'What is a casing point?', '["The depth at which the bit is changed.", "The depth at which a section must be cased off before the mud weight it needs costs too much tolerance.", "The depth at which the pore pressure gradient equals the fracture gradient, so no mud weight can be used safely.", "The point at which the hole size is reduced, which is set by the casing programme agreed before the well was spudded."]'::jsonb, 1, 'It is a well design decision and kick tolerance is the calculation that sets it.'),
  ('wellcontrol', 'advanced', 'module', 'm04-planning-with-it', 2, 'How does the tolerance sweep set the casing point?', '["Find the mud weight where the tolerance crosses the design kick size, convert it to a pore pressure and read the depth.", "By plotting tolerance against depth directly.", "By finding the mud weight at which the tolerance reaches zero and setting the shoe a fixed distance above it.", "By comparing the tolerance against the pit alarm setting and casing off wherever the two values become equal."]'::jsonb, 0, 'Four steps and one chart, and the prognosis supplies the last of them.'),
  ('wellcontrol', 'advanced', 'module', 'm04-planning-with-it', 3, 'What is a design kick size?', '["The largest kick ever recorded in the field.", "The volume at which the pit alarm is set, which is normally a fraction of the total active surface volume.", "The influx that the kill sheet was built for, which is the pit gain recorded at the moment of shut-in.", "The influx volume the well is designed to be able to circulate out safely."]'::jsonb, 3, 'It is a design choice rather than a measurement, and it is compared against the tolerance curve.'),
  ('wellcontrol', 'advanced', 'module', 'm04-planning-with-it', 4, 'What shape does the slant well''s tolerance curve have against mud weight?', '["A flat line until the fracture gradient.", "An exponential decay, because the Boyle compression term dominates the behaviour at every mud weight in the range.", "A nearly straight fall to zero, steepening slightly as it approaches.", "A rise followed by a fall, with the maximum occurring at the mud weight that balances the pore pressure exactly."]'::jsonb, 2, 'The headroom falls linearly with mud weight, and the shut-in case is proportional to the headroom.'),
  ('wellcontrol', 'advanced', 'module', 'm04-planning-with-it', 5, 'Now sweep the lateral over the same range. How does its curve run?', '["The same straight fall as the slant well.", "Almost flat over most of the range, then a fall as the mud approaches the fracture gradient.", "A steeper fall than the slant well, because a horizontal well has less true vertical depth to work with overall.", "A step change at the mud weight where the binding case switches from the shut-in one to the circulated one."]'::jsonb, 1, 'Its binding case is limited by the rise available rather than by the pressure, and the rise does not move.'),
  ('wellcontrol', 'advanced', 'module', 'm04-planning-with-it', 6, 'What does the flat horizontal curve mean for well design?', '["It means the well is safer than the slant one.", "It means the kick tolerance calculation does not apply to horizontal wells and a different method is required.", "It means the mud weight can be raised freely up to the fracture gradient without any consequence at all.", "Mud weight is not the lever on that well, so the shoe position has to be the answer instead."]'::jsonb, 3, 'The usual well design lever does not work on the well that needs it most, which is an uncomfortable finding.'),
  ('wellcontrol', 'advanced', 'module', 'm04-planning-with-it', 7, 'What does a kick tolerance of zero mean?', '["The well cannot be shut in on any influx at all without fracturing the shoe.", "The calculation has failed to converge.", "The well is perfectly balanced, so no influx can enter and no tolerance is required at that mud weight.", "The pit alarm should be set to zero, because any gain at all indicates that the shoe has already been fractured."]'::jsonb, 0, 'Not a large influx. Any influx, because the margin has already been spent on the mud.'),
  ('wellcontrol', 'advanced', 'module', 'm04-planning-with-it', 8, 'At what mud weight does the tolerance reach zero?', '["When the mud balances the pore pressure.", "When the mud weight reaches the point at which the two cases of the calculation give the same answer as each other.", "When the mud weight equals the fracture equivalent mud weight at the shoe.", "When the annulus capacity opposite the collars equals the capacity in the casing above the shoe of the section."]'::jsonb, 2, 'The hole full of mud is then already at the fracture pressure, with no influx present at all.'),
  ('wellcontrol', 'advanced', 'module', 'm04-planning-with-it', 9, 'Why does the engine clamp the tolerance at zero rather than returning a negative?', '["Because negative numbers break the panel.", "Because a negative volume has no physical meaning, even though the arithmetic would produce one.", "Because a negative tolerance would indicate that the influx density exceeded the mud density, which cannot happen.", "Because the engine switches to the other case whenever the first one would give a value below zero."]'::jsonb, 1, 'It is a defensible presentation choice and it does lose the information about how far past the limit the well is.'),
  ('wellcontrol', 'advanced', 'module', 'm04-planning-with-it', 10, 'What is the practical limit for a section, as opposed to the absolute limit?', '["Where the tolerance crosses zero.", "Where the mud weight equals the pore pressure gradient, since below that the well would be underbalanced.", "Where the equivalent circulating density at the drilling rate reaches the fracture gradient at the shoe.", "Where the tolerance crosses the design kick size, which comes earlier than the zero crossing."]'::jsonb, 3, 'The gap between the two is the design margin, and quoting both is more informative than quoting either.'),
  ('wellcontrol', 'advanced', 'module', 'm04-planning-with-it', 11, 'What check links the design calculation to the operation?', '["Comparing the pit alarm setting against the current kick tolerance.", "Comparing the mud weight against the prognosis.", "Comparing the slow circulating rate pressure against the value recorded at the previous shift''s measurement.", "Comparing the equivalent circulating density against the fracture gradient at the casing shoe of the section."]'::jsonb, 0, 'Two numbers and a comparison, and it is rarely written down anywhere.'),
  ('wellcontrol', 'advanced', 'module', 'm04-planning-with-it', 12, 'What does the section list in a drilling programme contain?', '["The completed kill sheet for the section.", "The pump output per stroke, the string and annulus volumes and the three stroke counts for the current depth.", "The shoe depth and its fracture equivalent, the MAASP, the tolerance and the section''s limiting mud weight.", "The casing burst and collapse ratings together with the wear factors expected over the life of the well."]'::jsonb, 2, 'Four numbers per hole section, and they change only when a string is run or a leak-off test is repeated.'),
  ('wellcontrol', 'advanced', 'module', 'm04-planning-with-it', 13, 'Which part of the programme goes stale fastest?', '["The MAASP for each section.", "The volumes, strokes and depths, because they change every stand.", "The fracture equivalent mud weight at the shoe, because the formation weakens as the section is exposed for longer.", "The design kick size, which is revised each time the pore pressure prognosis is updated during drilling."]'::jsonb, 1, 'That is the standing part of a kill sheet, and keeping it current is a routine duty.'),
  ('wellcontrol', 'advanced', 'module', 'm04-planning-with-it', 14, 'What does this course hand to casing design?', '["The burst and collapse loads.", "The maximum surface pressure that the wellhead will experience during a kill, which sets the equipment rating.", "The cement volume required to cover the shoe with sufficient height to achieve the required leak-off strength.", "The casing point, from the tolerance sweep against mud weight."]'::jsonb, 3, 'One number, and it is the output the whole Expert tier is built towards.'),
  ('wellcontrol', 'advanced', 'module', 'm04-planning-with-it', 15, 'Which two results arrive here from the previous drilling course?', '["The swab that causes the kick and the circulating density that has to be re-established afterwards.", "The slow circulating rate pressure.", "The annulus friction below the casing shoe, which is added to the MAASP comparison during the circulation.", "The transport ratio, which determines how quickly the influx can be carried up the annulus by the mud."]'::jsonb, 0, 'The slow circulating rate pressure is measured rather than computed, which is why it is not on that list.'),
  ('wellcontrol', 'advanced', 'module', 'm05-the-edges-of-the-model', 1, 'What does this engine assume about the blowout preventer''s position?', '["That it sits on the seabed.", "That it is close enough to surface for the choke line friction to be negligible at the rates used during a kill.", "That it sits at surface, with no riser and no choke line below it.", "That its position does not matter, because the calculation works from true vertical depths rather than from geometry."]'::jsonb, 2, 'Every number the engine produces is correct for a land or jack-up well and needs correcting on a floater.'),
  ('wellcontrol', 'advanced', 'module', 'm05-the-edges-of-the-model', 2, 'What does choke line friction do to the casing reading on a floater?', '["It adds to the observed reading, so the raw value overstates the pressure the annulus is actually holding.", "It has no effect on the reading.", "It reduces the reading in proportion to the length of the choke line and the density of the mud within it.", "It affects only the drill pipe side, because the choke line is in series with the string during a circulation."]'::jsonb, 0, 'On a deepwater well it is tens of bar, and forgetting it holds the bottom hole pressure too high.'),
  ('wellcontrol', 'advanced', 'module', 'm05-the-edges-of-the-model', 3, 'How is the choke line friction obtained?', '["By computing it from the line dimensions.", "By circulating through the choke line at the kill rate before it is needed and measuring it.", "By subtracting the shut-in casing pressure from the initial circulating pressure at the moment the kill begins.", "By comparing the two gauge readings once the influx has passed the subsea stack and entered the choke line."]'::jsonb, 1, 'It is a measured quantity, like the slow circulating rate pressure and for the same reason.'),
  ('wellcontrol', 'advanced', 'module', 'm05-the-edges-of-the-model', 4, 'What is a riser margin?', '["The volume of the riser above the seabed.", "The difference between the riser''s collapse rating and the pressure that seawater would exert at the seabed depth.", "The extra time available before a subsea well must be shut in, because of the riser volume above the stack.", "Extra mud weight that keeps the well overbalanced if the riser is disconnected."]'::jsonb, 3, 'On a deepwater well it is often not achievable, because it would fracture the shoe.'),
  ('wellcontrol', 'advanced', 'module', 'm05-the-edges-of-the-model', 5, 'Which calculations in this course are exactly right?', '["All of them, within numerical precision.", "The circulating ones, because the slow circulating rate pressure supplies the friction term that they require.", "The static ones, because a shut-in well genuinely is a column at rest.", "The volume calculations only, since they involve no assumptions about the fluid or about the flow at all."]'::jsonb, 2, 'Formation pressure, kill mud weight, MAASP and kick tolerance are all shut-in quantities.'),
  ('wellcontrol', 'advanced', 'module', 'm05-the-edges-of-the-model', 6, 'What does the vertical hydrostatic assumption leave out during circulation?', '["The annulus friction, which raises the pressure at the bottom above the static value while the pump runs.", "The compressibility of the mud.", "The temperature variation down the hole, which is the dominant departure from a simple density times depth product.", "The change in annulus capacity with depth, which alters how much fluid the column contains at each level."]'::jsonb, 0, 'The drill pipe side gets a friction term from the measurement. The annulus side gets none.'),
  ('wellcontrol', 'advanced', 'module', 'm05-the-edges-of-the-model', 7, 'Why does the annulus side of the kill sheet have no friction term?', '["Because annulus friction is always zero.", "Because the annulus contains mud, influx and expanding gas at positions that change continuously.", "Because the annulus friction is included in the slow circulating rate pressure, which covers the whole system.", "Because the choke operator measures it directly from the difference between the two gauges during the kill."]'::jsonb, 1, 'There is no fixed system to measure, unlike the string which stays the same throughout.'),
  ('wellcontrol', 'advanced', 'module', 'm05-the-edges-of-the-model', 8, 'In which direction does the missing annulus friction err?', '["Conservative, by a small margin.", "Neither, because the friction appears on both sides of the comparison and therefore cancels out entirely.", "It depends on the pump rate, being conservative at low rates and unsafe at the rates used while drilling.", "Unsafe, because the shoe is closer to its limit than the comparison suggests."]'::jsonb, 3, 'The pressure at the shoe while circulating exceeds the gauge plus the static column by the friction above it.'),
  ('wellcontrol', 'advanced', 'module', 'm05-the-edges-of-the-model', 9, 'Why is the missing annulus friction tolerated?', '["It is a few bar at kill rates, and the working margin applied to the MAASP absorbs it comfortably.", "It is not tolerated in modern practice.", "It is corrected automatically by the choke operator, who reads the casing gauge against the schedule continuously.", "It is included in the leak-off test result, which is measured with the pumps running at the same slow rate."]'::jsonb, 0, 'A known small error absorbed by a policy margin rather than by a correction, which is a common engineering pattern.'),
  ('wellcontrol', 'advanced', 'module', 'm05-the-edges-of-the-model', 10, 'When would the missing friction stop being tolerable?', '["When the influx is liquid rather than gas.", "When the well is horizontal, because the annulus friction in a lateral is much larger than in a vertical section.", "At a high circulating rate, in a tight annulus, or on a narrow margin well.", "When the kill mud density exceeds the original mud density by more than a small percentage of the original."]'::jsonb, 2, 'All three push the friction up relative to the MAASP, and all three argue for circulating more slowly.'),
  ('wellcontrol', 'advanced', 'module', 'm05-the-edges-of-the-model', 11, 'What axis does this model not have?', '["Depth below the casing shoe.", "Time, because every calculation is a state rather than a history.", "Temperature, which would be needed to compute the true hydrostatic pressure of a deep column of oil-based mud.", "Volume, since the calculations work in strokes and convert to volume only through the pump output."]'::jsonb, 1, 'The schedule is in strokes and the shut-in readings are read at one moment. Nothing is a function of elapsed time.'),
  ('wellcontrol', 'advanced', 'module', 'm05-the-edges-of-the-model', 12, 'Which time-dependent effect would the model most need?', '["Migration, because it changes the shut-in pressures while nothing at all is being done.", "Gelation of the mud at rest.", "Formation inflow, which continues for as long as the well remains underbalanced after the influx has entered.", "Dissolution of gas into an oil-based mud, which changes what the shut-in gauge readings actually mean."]'::jsonb, 0, 'A migration rate and a clock would say how long a well can be held before the casing pressure reaches the MAASP.'),
  ('wellcontrol', 'advanced', 'module', 'm05-the-edges-of-the-model', 13, 'What is volumetric control?', '["A method of measuring the pit gain.", "A technique for controlling the influx volume by adjusting the choke to hold the flow out equal to the flow in.", "The practice of recording the annulus volume at every casing point so that the standing part stays current.", "A wellsite procedure that bleeds mud in measured increments as the pressure rises."]'::jsonb, 3, 'It holds the bottom hole pressure constant while gas rises, and it is arithmetic on a sheet rather than in this engine.'),
  ('wellcontrol', 'advanced', 'module', 'm05-the-edges-of-the-model', 14, 'Which five things does the course say it will not certify?', '["The shut-in interpretation and the kill sheet.", "Kick tolerance, MAASP, the influx description, the two kill methods and the constant bottom hole pressure principle.", "Subsea operations, migration, dissolved gas in oil-based mud, the casing pressure history and multiphase behaviour.", "Any calculation involving a horizontal well, because the geometry falls outside the model''s stated range."]'::jsonb, 2, 'The go-live migration refuses to run if any graded field key names one of the five.'),
  ('wellcontrol', 'advanced', 'module', 'm05-the-edges-of-the-model', 15, 'What does the course certify?', '["Nothing, until field validation is complete.", "The static well control arithmetic on a surface preventer well, from volumes through to kick tolerance.", "The full kill operation including the casing pressure history and the behaviour of the influx as it rises.", "The volume and stroke calculations only, with the pressure work taught but explicitly left uncertified."]'::jsonb, 1, 'That is the industry-standard calculation, and stating its edges is what makes it usable by somebody else.'),
  ('wellcontrol', 'advanced', 'module', 'm06-the-expert-reading', 1, 'What is the Expert tier''s one sentence?', '["Kick tolerance is a geometry question dressed as a pressure question, and on a horizontal well the geometry wins.", "MAASP falls as the mud weight rises.", "The weakest point in any well is the casing shoe, and every calculation in the tier asks what it can stand.", "The smaller of the two kick tolerance cases is the one that has to be reported and designed against."]'::jsonb, 0, 'The others are all true and are parts of it. That one is what the tier discovered.'),
  ('wellcontrol', 'advanced', 'module', 'm06-the-expert-reading', 2, 'Which well does the Expert capstone grade?', '["The slant well only.", "The horizontal well only, since its geometry is the finding the tier is built around and the harder case to work.", "Both of them, with five fields on the slant well and one on the horizontal.", "Whichever well the learner selects in the tolerance explorer before beginning the capstone attempt for the tier."]'::jsonb, 2, 'Five tolerance and MAASP fields on one, and a kill sheet field on the other.'),
  ('wellcontrol', 'advanced', 'module', 'm06-the-expert-reading', 3, 'What fracture gradient does the Expert capstone use?', '["The same one the lessons use throughout.", "One the lessons never ran at, so no lesson prints any of the graded values.", "The value measured in the leak-off test recorded in the golden files, which the lessons quote in module 1.", "A value the learner chooses, since the capstone grades the method rather than any particular numerical result."]'::jsonb, 1, 'Same for the kick intensity. Both were changed deliberately.'),
  ('wellcontrol', 'advanced', 'module', 'm06-the-expert-reading', 4, 'Which capstone fields do not move when the kick intensity changes?', '["None of them, since all six depend on it.", "The kick tolerance and the headroom, because both are computed at the shoe rather than at the bit of the well.", "The kill mud density field, which depends only on the shut-in reading and the depth at which it is measured.", "The two MAASP fields, because MAASP does not depend on the formation pressure at all."]'::jsonb, 3, 'That is a useful self-check while working the capstone: some fields move and some do not.'),
  ('wellcontrol', 'advanced', 'module', 'm06-the-expert-reading', 5, 'On the slant well, which is larger, the tolerance or the circulated case?', '["The circulated case, because the shut-in case is the binding one on that well.", "The tolerance, by a small margin.", "They are equal, because the two cases converge whenever the shoe sits well above the bit in true vertical depth.", "It depends on the mud weight, with the circulated case larger only above the pore pressure gradient."]'::jsonb, 0, 'The tolerance is the smaller of the two, so if yours is the larger you have swapped the fields.'),
  ('wellcontrol', 'advanced', 'module', 'm06-the-expert-reading', 6, 'What is the trap in the capstone''s kill mud density field?', '["It uses a different shut-in reading.", "It is on the horizontal well while the same field in the previous tier was on the slant one.", "It requires the influx density to be computed first, because the kill mud must displace the influx from the annulus.", "It is graded at the shoe depth rather than at the bit, which changes the true vertical depth used in the division."]'::jsonb, 1, 'Same kick, different well, different answer. The previous tier''s value is a plausible wrong one.'),
  ('wellcontrol', 'advanced', 'module', 'm06-the-expert-reading', 7, 'Why is the headroom field graded as a pressure?', '["Because it is measured on a gauge.", "Because it is the difference between the two shut-in readings, which is a pressure by construction of the calculation.", "Because it is the fracture pressure at the shoe less what the mud column already puts there.", "Because the engine returns it in pascals and the capstone grades whatever unit the engine happens to use."]'::jsonb, 2, 'It is the same quantity as MAASP, read at the shoe rather than at surface.'),
  ('wellcontrol', 'advanced', 'module', 'm06-the-expert-reading', 8, 'What did module 1 establish about MAASP?', '["That it is a casing burst limit.", "That it is fixed for a hole section once the leak-off test has been performed and the shoe depth recorded.", "That it is the pressure the choke operator holds during the constant-pressure phase of the circulation.", "That it is a rock limit that falls as the mud weight rises."]'::jsonb, 3, 'Making the well safer against taking a kick makes it less able to handle one it has taken.'),
  ('wellcontrol', 'advanced', 'module', 'm06-the-expert-reading', 9, 'What did module 2 establish about the two wells?', '["That the slant well is bound by the shut-in case and the horizontal well by the circulated case.", "That both are bound by the same case.", "That the horizontal well has the larger tolerance because its lateral section provides more annulus volume.", "That the two cases give identical answers whenever the influx density is taken as the engine''s default."]'::jsonb, 0, 'The gap in true vertical depth between shoe and bit is what decides it, and the two gaps differ enormously.'),
  ('wellcontrol', 'advanced', 'module', 'm06-the-expert-reading', 10, 'What did module 3 establish about the single bubble?', '["That it is accurate for all influx types.", "That it overstates the expansion because the isothermal assumption supplies heat that a real annulus would not.", "That it is conservative for a dispersed influx and badly wrong for dissolved gas.", "That it is the only assumption available, since the composition of the influx is never known during the event."]'::jsonb, 2, 'Two directions, and the second one is the hazard that a course has to name explicitly.'),
  ('wellcontrol', 'advanced', 'module', 'm06-the-expert-reading', 11, 'How do the two tolerance curves compare when swept against mud weight?', '["That both curves fall at the same rate.", "That the slant curve falls nearly linearly while the horizontal one is almost flat.", "That the two curves cross at the mud weight where the binding case changes from one to the other on each well.", "That the horizontal curve falls faster, which is why horizontal wells need shallower casing points than slant ones."]'::jsonb, 1, 'The usual well design lever does not work on the well that needs it most.'),
  ('wellcontrol', 'advanced', 'module', 'm06-the-expert-reading', 12, 'What did module 5 establish about offshore work?', '["That the calculations are unchanged offshore.", "That a subsea stack raises the MAASP, because the seawater column above the seabed adds to the fracture margin.", "That the riser volume must be added to the annulus volume before the stroke counts are computed for the sheet.", "That the choke line friction must be measured and subtracted from every casing reading."]'::jsonb, 3, 'It is the correction that makes the difference between a right answer and one wrong by tens of bar.'),
  ('wellcontrol', 'advanced', 'module', 'm06-the-expert-reading', 13, 'Which three habits does the tier name?', '["Read MAASP at a stated mud weight, quote both tolerance cases, and correct for the choke line offshore.", "Shut in fast, read both gauges, record the gain.", "Recompute the volumes at every stand, measure the slow rate at every shift and rebuild the sheet at every casing point.", "Classify the influx, compute its height and compare the pit gain against the tolerance before circulating."]'::jsonb, 0, 'A tolerance bound circulated is a geometry problem and one bound shut in is a pressure problem, with different remedies.'),
  ('wellcontrol', 'advanced', 'module', 'm06-the-expert-reading', 14, 'What does this course take as given from geomechanics?', '["The mud rheology and the annulus friction.", "The casing shoe depth and the true vertical depth at the bit, both of which come from the directional survey.", "The fracture gradient and, implicitly, the pore pressure.", "The influx density, which is estimated from the reservoir fluid properties established before the well was drilled."]'::jsonb, 2, 'Every limit in the Expert tier is a comparison against the first of those.'),
  ('wellcontrol', 'advanced', 'module', 'm06-the-expert-reading', 15, 'What is the last thing the tier says a well is?', '["Safe once the kill mud is all the way round.", "Controlled when the bottom exceeds the pore pressure and the shoe does not exceed the fracture pressure.", "Under control whenever the blowout preventer is closed and the two surface gauges have both stabilised.", "Balanced when the mud weight equals the pore pressure gradient expressed as an equivalent density."]'::jsonb, 1, 'Two conditions held at once, and the whole course is the arithmetic of keeping both true.'),
  ('wellcontrol', 'advanced', 'final', null, 1, 'Something in the exposed hole will give way first. Where is it, and why there?', '["The casing shoe, being the shallowest exposed rock.", "The bit at the bottom of the hole.", "Whichever formation shows the lowest compressive strength on the logs run before the section was cased off.", "The point of maximum dogleg, where the wellbore is most highly stressed by the shape of the trajectory."]'::jsonb, 0, 'Least overburden means least resistance to fracturing.'),
  ('wellcontrol', 'advanced', 'final', null, 2, 'MAASP is defined as what?', '["The rating of the preventer stack.", "The highest pressure the casing can withstand at its weakest connection, derated for wear and for temperature.", "The fracture pressure at the shoe less the mud column above it.", "The difference between the pore pressure and the fracture pressure at the shoe of the current hole section."]'::jsonb, 2, 'It is the surface pressure the shoe can take on top of the mud that is already there.'),
  ('wellcontrol', 'advanced', 'final', null, 3, 'Raising the mud weight does what to MAASP?', '["Raises it proportionally.", "Lowers it, because the mud column uses more of the fracture pressure.", "Leaves it unchanged, since the fracture pressure is a property of the rock rather than of the fluid in the hole.", "Lowers it until the mud reaches the pore pressure gradient and holds it constant beyond that point."]'::jsonb, 1, 'Safer against taking a kick, less able to handle one already taken.'),
  ('wellcontrol', 'advanced', 'final', null, 4, 'Somebody quotes a MAASP without saying what it constrains. What is it a limit on?', '["A casing burst limit.", "A rating on the annular preventer, which is the component holding the annulus closed during the shut-in period.", "An equipment limit set by the lowest rated part of the choke manifold and surface pressure system.", "A rock limit at the shoe, valid at one stated mud weight."]'::jsonb, 3, 'Casing and preventer ratings are separate, and the binding limit is whichever is smallest.'),
  ('wellcontrol', 'advanced', 'final', null, 5, 'The circulation is under way and the annulus gauge is climbing. What role does MAASP play?', '["As the casing pressure to hold.", "As the value the operator holds constant once the kill mud has arrived at the bit and the schedule has ended.", "As a limit to compare the casing gauge against.", "As the starting point for the schedule, since the initial circulating pressure is derived from it directly."]'::jsonb, 2, 'The drill pipe pressure is the target. The casing gauge is watched against the limit.'),
  ('wellcontrol', 'advanced', 'final', null, 6, 'Kick tolerance answers which question?', '["How large an influx can be circulated out without fracturing the shoe.", "How long a well can be left shut in.", "What mud weight balances the formation once the influx has been circulated out of the annulus completely.", "How much surface pressure the annular preventer can hold before the element begins to leak past the pipe."]'::jsonb, 0, 'It is a volume, and it is what a pit alarm setting should be compared against.'),
  ('wellcontrol', 'advanced', 'final', null, 7, 'The shut-in case places the influx where?', '["Just below the casing shoe.", "Distributed evenly through the annulus from the bit up to the shoe of the current hole section being drilled.", "At surface, where its volume is measured in the trip tank before it is bled through the choke manifold.", "At the bottom of the hole, where it entered."]'::jsonb, 3, 'It is the moment the well is closed, before anything has been circulated at all.'),
  ('wellcontrol', 'advanced', 'final', null, 8, 'In that configuration, what caps how tall the influx can be?', '["The annulus capacity at the collars.", "The headroom at the shoe divided by the density difference.", "The vertical distance between the bit and the shoe, since the influx cannot occupy more hole than exists.", "The pit gain at the moment of closure, which fixes the volume and therefore the height directly."]'::jsonb, 1, 'A pressure divided by a gradient gives a height, which a capacity turns into a volume.'),
  ('wellcontrol', 'advanced', 'final', null, 9, 'Once it has been brought up the annulus, where does that second calculation put it?', '["At the bottom, as it entered.", "Just below the shoe, expanded on the way up.", "At the surface, having been circulated all the way round and bled off through the choke without expanding.", "Partly dissolved into the mud, with only the residual free volume reaching the casing shoe of the section."]'::jsonb, 1, 'It is the most dangerous position relative to the shoe.'),
  ('wellcontrol', 'advanced', 'final', null, 10, 'That second calculation gives a volume at the shoe. What step recovers the pit gain it came from?', '["By dividing by the capacity ratio.", "By subtracting the volume of mud displaced from the annulus during the rise up to the casing shoe.", "By applying the pump efficiency correction, since the volume is counted in strokes rather than in cubic metres.", "Boyle compression from the shoe pressure back to the pressure at the bit."]'::jsonb, 3, 'The graded answer is the entry volume, which is what a pit gain would have shown.'),
  ('wellcontrol', 'advanced', 'final', null, 11, 'Two numbers come out of the calculation. Which one goes on the report, and on what grounds?', '["The smaller, because the well has to survive both.", "The shut-in case, always.", "The average of the two, weighted by the fraction of the operation spent in each of the two configurations.", "Whichever matches the kill method chosen, since the two methods place the influx differently in the annulus."]'::jsonb, 0, 'Reporting the larger would certify the well against a condition it cannot survive.'),
  ('wellcontrol', 'advanced', 'final', null, 12, 'The slant well is bound by which case, and why?', '["The circulated case, because of expansion.", "Neither, since the two come out equal on that well by the way the course fixture was constructed.", "The shut-in case, because of the large vertical gap between its shoe and its bit.", "It varies with mud weight, the circulated case binding only below the pore pressure gradient."]'::jsonb, 2, 'A large gap lets the influx be tall at the bottom before the shoe notices.'),
  ('wellcontrol', 'advanced', 'final', null, 13, 'Take the lateral instead. Which case binds there?', '["The shut-in case, as on the slant well.", "Both equally, because the two cases converge whenever the wellbore approaches horizontal at its bottom.", "Neither, because a lateral cannot take a conventional influx and the calculation does not apply to it.", "The circulated case, because its shoe is only tens of metres above the bit in true vertical depth."]'::jsonb, 3, 'The influx has almost nowhere to rise, so geometry rather than pressure sets the limit.'),
  ('wellcontrol', 'advanced', 'final', null, 14, 'Why is the horizontal well''s tolerance almost flat against mud weight?', '["Because its fracture gradient is higher.", "Its binding case is limited by the rise available, and that distance does not change.", "Because the annulus in a lateral is larger, so a given volume occupies a shorter length of hole than elsewhere.", "Because the mud weight cancels out of the Boyle compression when the influx sits close to the casing shoe."]'::jsonb, 1, 'Only the compression correction moves, and it moves very little.'),
  ('wellcontrol', 'advanced', 'final', null, 15, 'One intermediate quantity in the tolerance run is a pressure. Say what it measures.', '["The difference between the two gauges.", "The volume of influx that can sit below the shoe without the pressure there exceeding its fracture limit.", "The fracture pressure at the shoe less what the mud column puts there.", "The vertical distance from the shoe to the bit, which is the height available for the influx to rise through."]'::jsonb, 2, 'The same quantity as MAASP, read at the shoe rather than at the surface.'),
  ('wellcontrol', 'advanced', 'final', null, 16, 'Raise the underbalance assumed in the calculation. Does the surface limit move with it?', '["No, because MAASP depends only on the fracture pressure and the mud column.", "Yes, in direct proportion to it.", "Yes, because a larger intensity means a larger influx and therefore a lighter column in the annulus above it.", "Only in the circulated case, where the intensity determines how far the influx expands on the way up."]'::jsonb, 0, 'A useful check when working a capstone: some fields move with it and some do not.'),
  ('wellcontrol', 'advanced', 'final', null, 17, 'A bubble climbs the annulus and the pressure round it falls. What does the gas law predict?', '["Volume rises as pressure falls, with their product constant.", "Volume stays constant as it rises.", "Pressure stays constant while temperature falls, so volume increases in proportion to the change in depth.", "Density falls in proportion to the distance travelled, which puts the largest expansion near the surface."]'::jsonb, 0, 'Most of the expansion happens in the last part of the rise.'),
  ('wellcontrol', 'advanced', 'final', null, 18, 'Name the process that moves gas up a closed well with the pumps off.', '["Expansion of gas during a circulation.", "Movement of dissolved gas out of the base oil of an oil-based mud as the pressure falls during the kill.", "Transfer of gas from the annulus into the string through a washout or a float valve that has failed to seat.", "Buoyant rise of gas through static mud with the pumps off."]'::jsonb, 3, 'It happens when nobody is watching a schedule, which is what makes it dangerous.'),
  ('wellcontrol', 'advanced', 'final', null, 19, 'Nobody is pumping and the readings are climbing anyway. Account for it.', '["Lowers the casing pressure only.", "Leaves them unchanged, since the total weight of fluid in the annulus is not altered by the gas changing position.", "Raises both, because the gas carries its pressure upward.", "Raises the string side and lowers the annulus side as the gas displaces mud from one to the other."]'::jsonb, 2, 'The gas keeps its original pressure while the mud that should be above it is now below it.'),
  ('wellcontrol', 'advanced', 'final', null, 20, 'Gas is worse than liquid at shut-in for what reason?', '["It occupies more of the annulus.", "Its density is far below the mud''s, so its pressure deficit over the same height is much larger.", "It dissolves into the mud, which raises the column density and disguises the true size of the influx.", "It reaches surface faster, leaving less time to complete the calculations before it arrives at the choke."]'::jsonb, 1, 'That is the first of two reasons, and it applies before anything is circulated.'),
  ('wellcontrol', 'advanced', 'final', null, 21, 'And once you start circulating, what makes it worse again?', '["It travels faster than a liquid would.", "It expands as it rises, so both its volume and its height grow.", "It cools as it rises, which raises its density and makes it fall back down through the mud column above.", "It reacts with the mud additives and changes the rheology, raising the annulus friction near the shoe."]'::jsonb, 1, 'A liquid influx does neither to any comparable degree.'),
  ('wellcontrol', 'advanced', 'final', null, 22, 'State the simplification the tolerance calculation makes about the shape of the influx.', '["One continuous slug filling the annulus cross section.", "That the influx is entirely gas.", "That the influx expands isothermally as it rises, following the ideal gas law with no departure from it.", "That the influx stays at the bottom until the circulation reaches it and begins to carry it upward."]'::jsonb, 0, 'Real influxes are dispersed, mixed and concentrated on the high side of an inclined hole.'),
  ('wellcontrol', 'advanced', 'final', null, 23, 'The real influx is mixed through the mud rather than continuous. Which way does the model err?', '["Unsafely, by a wide margin.", "Not at all, since the total pressure deficit depends on the volume rather than on how it is distributed.", "Unpredictably, because the direction depends on how much of the influx has already mixed with the mud.", "Conservatively, because a dispersed influx provides more pressure."]'::jsonb, 3, 'The model predicts worse than reality, which is the useful direction.'),
  ('wellcontrol', 'advanced', 'final', null, 24, 'Name the case where that simplification fails outright rather than merely erring safe.', '["A brine influx in water-based mud.", "A large gas influx in a horizontal well, where the influx lies along the low side of the lateral section.", "Dissolved gas in oil-based mud, which gives almost no pit gain and almost no casing pressure.", "Any influx taken while tripping, because the string is off bottom and the annulus geometry has changed."]'::jsonb, 2, 'It comes out of solution suddenly and high in the annulus, which is the opposite of the model''s picture.'),
  ('wellcontrol', 'advanced', 'final', null, 25, 'The isothermal assumption biases the expansion which way?', '["It understates the expansion.", "It has no effect, because the annulus temperature is set by the surrounding rock rather than by the gas itself.", "It overstates it, because a real gas cools as it expands.", "It makes the calculation indeterminate, because the gas law requires a temperature and none is supplied."]'::jsonb, 2, 'Isothermal means the surroundings supply whatever heat the expansion consumes, which is generous.'),
  ('wellcontrol', 'advanced', 'final', null, 26, 'Real gas departs from the simple law at depth. Which way does ignoring that push the result?', '["It overstates it at all pressures.", "It understates it at high pressure, where a real gas is more compressible.", "It has no effect at well control pressures, which lie comfortably within the ideal gas range for hydrocarbons.", "It makes the answer depend on the gas composition, which is not known at the time of the calculation."]'::jsonb, 1, 'The compressibility factor departs from one at high pressure, and it departs downward.'),
  ('wellcontrol', 'advanced', 'final', null, 27, 'Taken together, the two gas assumptions do what?', '["Partly cancel, since one overstates and the other understates.", "Compound into a large error.", "Cancel exactly, which is why the simple form of the calculation is used throughout the industry worldwide.", "Both err conservatively, so the combined result is safely on the high side of the true expansion."]'::jsonb, 0, 'Partly, not exactly, and the residual is small at the pressures this course works at.'),
  ('wellcontrol', 'advanced', 'final', null, 28, 'A programme fixes a depth for the next string. What determines that depth?', '["The depth at which the bit is changed.", "The depth where the pore pressure gradient equals the fracture gradient and no mud weight is safe at all.", "The point at which the hole size reduces, fixed by the casing programme agreed before the well was spudded.", "The depth at which a section must be cased off before its mud weight costs too much tolerance."]'::jsonb, 3, 'It is a design decision and kick tolerance is the calculation that sets it.'),
  ('wellcontrol', 'advanced', 'final', null, 29, 'You have a curve of tolerance against mud weight. Walk it through to a shoe depth.', '["Plot the tolerance against depth directly.", "Find the mud weight where the tolerance reaches zero and set the shoe a fixed distance above that point.", "Compare the tolerance against the pit alarm setting and case off wherever the two values become equal.", "Find the mud weight where tolerance meets the design kick, convert to a pore pressure, read the depth."]'::jsonb, 3, 'Four steps and one chart, with the prognosis supplying the last of them.'),
  ('wellcontrol', 'advanced', 'final', null, 30, 'The calculation returns nothing at all for the section. Spell out what that says about the well.', '["The calculation has not converged.", "The well is perfectly balanced, so no influx can enter and no tolerance is needed at that mud weight.", "The well cannot be shut in on any influx without fracturing the shoe.", "The pit alarm should be set to zero, because any gain means the shoe has already been fractured."]'::jsonb, 2, 'Not a large influx. Any influx, because the margin has been spent on the mud.'),
  ('wellcontrol', 'advanced', 'final', null, 31, 'The tolerance reaches zero at which mud weight?', '["When the mud balances the pore pressure.", "When the mud equals the fracture equivalent mud weight at the shoe.", "When the two cases of the calculation happen to give the same answer as one another for that geometry.", "When the collar annulus capacity equals the casing annulus capacity above the shoe of the section."]'::jsonb, 1, 'The hole full of mud is then already at the fracture pressure with no influx present.'),
  ('wellcontrol', 'advanced', 'final', null, 32, 'The arithmetic can go below zero but the output never does. Defend that choice.', '["Because a negative volume has no physical meaning, though the arithmetic would produce one.", "Because negative values break the panel.", "Because a negative would mean the influx was denser than the mud, which cannot physically occur in a well.", "Because the engine switches to the other case whenever the first would return a value below zero."]'::jsonb, 0, 'Defensible, and it loses the information about how far past the limit the well actually is.'),
  ('wellcontrol', 'advanced', 'final', null, 33, 'Name the one comparison that ties a desk calculation to a decision on the rig floor.', '["The pit alarm setting compared against the current kick tolerance.", "The mud weight against the prognosis.", "The slow circulating rate pressure compared against the value recorded during the previous shift''s measurement.", "The equivalent circulating density compared against the fracture gradient at the shoe of the current section."]'::jsonb, 0, 'Two numbers and a comparison, and it is rarely written down anywhere.'),
  ('wellcontrol', 'advanced', 'final', null, 34, 'This engine assumes the preventer is where?', '["On the seabed, as on a floater.", "At surface, with no riser and no choke line.", "Close enough to surface that the choke line friction is negligible at the rates used during a kill operation.", "Anywhere, because the calculation works from true vertical depths rather than from the physical geometry."]'::jsonb, 1, 'Every number is correct for a land or jack-up well and needs a correction on a floater.'),
  ('wellcontrol', 'advanced', 'final', null, 35, 'A floater circulates through a long line to the stack. What does that do to the gauge at the rig?', '["Has no effect on the reading.", "Reduces it in proportion to the length of the choke line and the density of the mud that is inside it.", "Affects the drill pipe side only, because the choke line is in series with the string during circulation.", "Adds to it, so the raw value overstates what the annulus holds."]'::jsonb, 3, 'Tens of bar on a deepwater well, and forgetting it holds the bottom hole pressure too high.'),
  ('wellcontrol', 'advanced', 'final', null, 36, 'Some results here carry no modelling error at all. Which ones, and why?', '["All of them, to numerical precision.", "The circulating ones, since the slow circulating rate pressure supplies the friction term that they need.", "The static ones, because a shut-in well genuinely is a column at rest.", "The volume calculations alone, because they make no assumption about the fluid or about the flow."]'::jsonb, 2, 'Formation pressure, kill mud weight, MAASP and kick tolerance are all shut-in quantities.'),
  ('wellcontrol', 'advanced', 'final', null, 37, 'The string side carries a measured friction term. Explain the absence on the other side.', '["Annulus friction is genuinely zero.", "The annulus friction is already inside the slow circulating rate pressure, which covers the whole system.", "The annulus contains mud, influx and gas at positions that change continuously.", "The operator measures it directly from the difference between the two gauges as the circulation proceeds."]'::jsonb, 2, 'There is no fixed system to measure, unlike the string which stays the same throughout.'),
  ('wellcontrol', 'advanced', 'final', null, 38, 'That omission is not neutral. Which way does it bias the shoe comparison?', '["Conservative, by a small margin.", "Neither, because the friction appears on both sides of the comparison and cancels out of it entirely.", "It depends on the rate, being conservative at low rates and unsafe at the rates used while drilling ahead.", "Unsafe, because the shoe is nearer its limit than the comparison shows."]'::jsonb, 3, 'The shoe pressure while circulating exceeds the gauge plus the static column by the friction above it.'),
  ('wellcontrol', 'advanced', 'final', null, 39, 'Why is that error tolerated?', '["It is a few bar at kill rates and the MAASP working margin absorbs it.", "It is not tolerated in modern practice.", "It is corrected by the operator, who reads the casing gauge against the schedule continuously through the kill.", "It is already inside the leak-off test result, which is measured with the pumps running at the same slow rate."]'::jsonb, 0, 'A known small error absorbed by a policy margin rather than by a correction.'),
  ('wellcontrol', 'advanced', 'final', null, 40, 'Which axis does this model lack?', '["Depth below the casing shoe.", "Time, because every calculation is a state rather than a history.", "Temperature, which the true hydrostatic pressure of a deep oil-based mud column would require.", "Volume, since the calculations work in strokes and reach volume only through the pump output per stroke."]'::jsonb, 1, 'Migration, dissolution, formation inflow and gelling all happen during the waiting rather than the pumping.'),
  ('wellcontrol', 'advanced', 'final', null, 41, 'Which five things does the course refuse to certify?', '["The shut-in interpretation and the kill sheet.", "Subsea work, migration, dissolved gas in oil-based mud, the casing pressure history and multiphase behaviour.", "Kick tolerance, MAASP, the influx description, the kill methods and the constant bottom hole pressure principle.", "Any calculation on a horizontal well, because that geometry falls outside the model''s stated valid range."]'::jsonb, 1, 'The go-live migration refuses to run if any graded field key names one of the five.'),
  ('wellcontrol', 'advanced', 'final', null, 42, 'Reduce this tier to a single claim worth carrying into a design review.', '["MAASP falls as the mud weight rises.", "The weakest point in a well is the casing shoe, and every calculation in the tier asks what it can stand.", "Kick tolerance is a geometry question dressed as a pressure question, and on a lateral the geometry wins.", "The smaller of the two kick tolerance cases is the one that must be reported and designed against."]'::jsonb, 2, 'The others are true and are parts of it. That one is what the tier discovered.');
