-- ============================================================================
-- PD5 ASSOCIATE DEEP SEED: Gas Well Performance, beginner tier.
--
-- Six modules, 26 lessons, 132 questions (15 per module bank plus a 42
-- question final exam). The structure row is GENERATED from the tier's
-- manifest.json rather than hand typed.
--
-- What this tier owns: THE DROPLET BALANCE AT ONE POINT, and that point is the
-- WELLHEAD, because that is the gauge an operator reads. A gas well loads up
-- when the gas can no longer carry the liquid it is producing, and the whole
-- of the classical treatment is a force balance on a single droplet: drag
-- against weight, a terminal velocity, a flow area, and one ratio that
-- decides. Every number in this tier comes out of a gas density, a terminal
-- velocity or a single-station loading check.
--
-- THE TIER ENDS ON A CONCLUSION THAT IS WRONG, AND THAT IS DELIBERATE. Read at
-- the wellhead the capstone well is comfortably unloaded, at a ratio of
-- 1.2552, and it still passes there under the stricter correlation. It is
-- nonetheless loading over the bottom third of its string. A learner who
-- finishes this tier can compute everything an operator reads off a surface
-- gauge and will reach the wrong verdict from it, which is the strongest
-- possible motivation for the tier above.
--
-- TWO THINGS THE TIER MUST NOT ASSUME, and both are ways of quietly importing
-- a number instead of computing one.
--
--   THE Z FACTOR IS NOT 0.9. The published fixture hands the loading module a
--   FLAT 0.9 at every pressure from 300 to 2,500 psia, which is fine for an
--   oracle checking droplet algebra and wrong for a well whose pressure
--   triples down the string. This course takes z from the package's own
--   natural gas correlation, and on the capstone well it runs 0.8436 to
--   0.8677. Since z sits in the denominator of both the gas density and the
--   actual velocity, assuming one instead of computing one moves most of the
--   tier's answers.
--
--   AND THE TWO MODULES IN THE CHAIN DO NOT SPEAK THE SAME UNITS. The loading
--   module takes degR and the properties module takes degF, so the conversion
--   has to happen at the DOOR, with the package's own converter, rather than
--   as a hand-typed 459.67 somewhere in the middle. They also carry two
--   different molecular weights of air, 28.9647 and 28.9625, against the same
--   gas constant, so one gas density computed two ways differs by 76 parts per
--   million. Neither is a defect. Both are seams, and a seam is where a course
--   has to say which side it is standing on.
--
-- A RESULT WORTH STATING BECAUSE INTUITION GETS IT BACKWARDS. The HEAVIER
-- liquid makes the FASTER droplet. Brine is harder to lift than condensate,
-- and its terminal velocity is higher, because the terminal velocity rises
-- with the density difference and the brine's extra weight more than pays for
-- its higher surface tension. A tier that leaves a learner thinking the
-- lighter liquid falls faster has taught the balance backwards.
--
-- The only numbers that travel from this tier to the next are the well's own
-- stated conditions. The tier above restates every one of them from scratch.
-- ============================================================================

insert into public.academy_course_structures
    (app_slug, tier, structure, content_version)
values ('gaswell', 'beginner', '{"modules":[{"key":"m01-a-well-that-drowns","title":"A Well That Drowns","lesson_keys":["l01-why-a-gas-well-loads-up","l02-what-this-engine-models","l03-what-it-refuses","l04-the-droplet-picture"]},{"key":"m02-gas-at-a-station","title":"Gas at a Station","lesson_keys":["l01-z-at-pressure-and-temperature","l02-gas-density","l03-what-density-decides","l04-reading-one-station","l05-what-one-station-cannot-tell-you"]},{"key":"m03-the-droplet-balance","title":"The Droplet Balance","lesson_keys":["l01-drag-against-weight","l02-terminal-velocity","l03-surface-tension-and-density","l04-brine-against-condensate","l05-what-the-balance-assumes"]},{"key":"m04-critical-velocity-and-rate","title":"Critical Velocity and Rate","lesson_keys":["l01-from-velocity-to-rate","l02-flow-area","l03-the-critical-rate","l04-the-actual-velocity","l05-the-ratio-that-decides"]},{"key":"m05-two-correlations","title":"Two Correlations","lesson_keys":["l01-turner-and-coleman","l02-the-twenty-percent","l03-which-one-and-where","l04-what-a-correlation-is-not"]},{"key":"m06-the-associate-reading","title":"The Associate Reading","lesson_keys":["l01-the-story-so-far","l02-working-the-capstone","l03-onward"]}]}'::jsonb, 1)
on conflict (app_slug, tier) do update
  set structure = excluded.structure,
      content_version = excluded.content_version,
      active = true,
      updated_at = now();

delete from public.academy_quiz_questions
 where app_slug = 'gaswell' and tier = 'beginner';

insert into public.academy_quiz_questions
    (app_slug, tier, scope, module_key, ord, prompt, options, answer_index, explanation)
values
  ('gaswell', 'beginner', 'module', 'm01-a-well-that-drowns', 1, 'What separates a droplet the gas carries to surface from one that falls back down the tubing?', '["The size of the droplet when it leaves the perforations.", "The volume of liquid the well makes each day.", "The gas velocity, measured against the one velocity at which upward drag exactly balances the droplet weight less the buoyancy of the gas around it.", "The total measured depth of the tubing string."]'::jsonb, 2, 'The module sorts a single droplet into carried or falling back, so the verdict is one droplet at its terminal velocity rather than a statement about a population.'),
  ('gaswell', 'beginner', 'module', 'm01-a-well-that-drowns', 2, 'Why does a gas well that has begun to load rarely settle at a slightly lower rate?', '["The liquid falling back adds back pressure, which lowers the rate, which lowers the velocity, so the arithmetic runs again the next day from a worse number.", "Reservoir pressure declines on its own schedule, and a liquid column standing in the tubing has no influence at all on the rate the well is able to deliver from one day to the next.", "The tubing corrodes once brine collects in it.", "The wellhead choke closes automatically at low rates."]'::jsonb, 0, 'The column of fallen liquid is something the reservoir now has to push against, so each day starts from a lower number than the day before it.'),
  ('gaswell', 'beginner', 'module', 'm01-a-well-that-drowns', 3, 'For published water at 540.0 degR, gas density rises from 1.0829385833 to 9.0244881938 lbm/ft3 between 300.0 and 2500.0 psia. What happens to the terminal velocity?', '["It climbs from 4.0737980096 to 12.1435923634 ft/s, because denser gas is harder for a droplet to move through on its way up to surface.", "It holds near 12.1435923634 ft/s throughout, because the interfacial tension and the liquid density did not change across the three pressures listed.", "It reaches zero at 2500.0 psia.", "It falls from 12.1435923634 to 4.0737980096 ft/s."]'::jsonb, 3, 'Denser gas both pushes harder on the droplet and reduces its submerged weight, so the two effects run the same way rather than opposing each other.'),
  ('gaswell', 'beginner', 'module', 'm01-a-well-that-drowns', 4, 'Why does the Turner critical rate climb from 892.895047041 to 2496.154595078 Mscf/d while the velocity requirement is falling?', '["The tubing inside diameter grows with pressure, so the flow area behind the rate is larger at 2500.0 psia than it is at 300.0 psia.", "A cubic foot of high pressure tubing holds far more standard gas.", "The rate is computed from reservoir deliverability, which improves at the higher pressures this table runs through.", "The Turner adjustment of 1.2000 applies only above the Coleman pressure limit of 1000.0 psia, so it lifts the upper rows and leaves the lower ones alone."]'::jsonb, 1, 'A rate and a velocity are one statement in two currencies, and the exchange between them is the flow area together with pressure over compressibility times temperature.'),
  ('gaswell', 'beginner', 'module', 'm01-a-well-that-drowns', 5, 'A study lists 892.895047041, 1614.343188395 and 2496.154595078 Mscf/d as though they described a well. What is the error?', '["They are one fluid in one string at three pressures, so nothing about any well changed between them.", "They were built on the Coleman adjustment of 1.0000 instead of the Turner adjustment of 1.2000, so every figure quoted sits twenty percent below the true requirement.", "They are measured rates rather than requirements.", "They use a tubing size no gas well runs."]'::jsonb, 0, 'A rate carries a verdict only once the pressure, the temperature, the compressibility factor and the diameter behind it are all fixed.'),
  ('gaswell', 'beginner', 'module', 'm01-a-well-that-drowns', 6, 'How many inputs stand behind a critical velocity, and what do they describe?', '["Three describe the gas, three describe the liquid and one describes the completion, with the compressibility factor worked out inside the module from the pressure and the temperature.", "Two describe the gas and five describe the reservoir, because the module needs an inflow relation before it can decide whether a droplet is carried.", "Four describe the gas, two describe the liquid and one describes the pipe.", "Two, a pressure and a rate."]'::jsonb, 2, 'The gas is a pressure in psia, a temperature in degR, a compressibility factor and a specific gravity, the liquid is an interfacial tension and a density, and the pipe is an inside diameter in inches.'),
  ('gaswell', 'beginner', 'module', 'm01-a-well-that-drowns', 7, 'Where does the tubing inside diameter enter this calculation?', '["In the drag coefficient, which is set from pipe wall roughness.", "At exactly one place, the flow area that turns a critical velocity into a critical rate, which is the reason a velocity string can change a verdict at all.", "In the gas density, through the volume of the string.", "In the interfacial tension of the liquid being carried."]'::jsonb, 1, 'Nothing inside the droplet balance itself knows the pipe, so the terminal velocity at a station is the same number in any string you care to run.'),
  ('gaswell', 'beginner', 'module', 'm01-a-well-that-drowns', 8, 'Turning a velocity through an area into Mscf/d costs one constant, 3054.38693878. What is that constant built from?', '["The drag coefficient of 0.4400 and the critical Weber number of 30.0000, combined through the droplet balance.", "A regression against the twelve published velocity rows, which is why it carries so many decimal places.", "The Turner adjustment of 1.2000 multiplied by the Coleman pressure limit of 1000.0 psia and then scaled to thousands.", "86400 seconds, 519.67 degR and 14.70 psia."]'::jsonb, 3, 'Divided by a thousand it reads 3.054387, which is the 3.06 the textbooks print for MMscf/d, and a constant you can rebuild from standard conditions is a constant you can audit.'),
  ('gaswell', 'beginner', 'module', 'm01-a-well-that-drowns', 9, 'All twelve published velocity rows carry z pinned at 0.90. What does that reveal about the module?', '["It computes the compressibility factor internally from Sutton pseudo-criticals and then prints the value it used alongside the velocity it returned.", "It restricts itself to gases whose compressibility factor sits near 0.90, and returns ok = false for any station where the real gas lies further away than that.", "It takes the compressibility factor as an input and never works it out.", "It ignores compressibility entirely."]'::jsonb, 2, 'The compressibility route lives in a different module, so a habitual 0.90 supplied at a pressure where the gas is nothing like that is a mistake this module cannot see.'),
  ('gaswell', 'beginner', 'module', 'm01-a-well-that-drowns', 10, 'Which input makes the module come back with ok = false and no velocity at all?', '["A gas gravity of 0.65 supplied with a compressibility factor of 0.90 at a pressure of 2500.0 psia.", "An interfacial tension of 0.0 dyne/cm.", "A misspelled fluid id.", "A tubing size of 2.441 in."]'::jsonb, 1, 'A liquid with no interfacial tension forms no droplet, so the Weber condition has nothing to size and the balance has no question left to answer.'),
  ('gaswell', 'beginner', 'module', 'm01-a-well-that-drowns', 11, 'What does a loading verdict from these modules assert about what a well will do next?', '["Nothing at all, because there is no inflow performance anywhere in them and the gas rate was supplied by whoever ran the check.", "It forecasts the day the well will die.", "It gives the rate the well will make next month.", "It predicts how much liquid reaches surface."]'::jsonb, 0, 'A flowing traverse is passed in as a list of stations carrying their own pressure, temperature, compressibility factor and diameter, so the stations you get out are the stations you put in.'),
  ('gaswell', 'beginner', 'module', 'm01-a-well-that-drowns', 12, 'What does recommendCorrelation do with the pressure it is handed?', '["It selects the correlation and then applies that choice to every station in the flowing traverse that follows.", "It rejects the value if it came from any station other than the wellhead where it belongs.", "It converts the value into a critical rate and compares that rate against the measured production.", "It returns guidance and switches nothing."]'::jsonb, 3, 'It also cannot see which station the pressure came from, and sizeTubingForRate is blind in the same way, sizing a string from any station handed to it.'),
  ('gaswell', 'beginner', 'module', 'm01-a-well-that-drowns', 13, 'A fluid id is misspelled on the way in. What comes back out?', '["A perfectly good brine answer at 60.0 dyne/cm and 67.0 lbm/ft3, reported under whatever name was asked for.", "An error object naming the fluid ids the module publishes, in the same way an unrecognised correlation name is refused before any velocity is computed.", "Condensate properties of 20.0 dyne/cm and 45.0 lbm/ft3.", "A velocity of zero carrying ok = false."]'::jsonb, 0, 'Water is the harsher of the two fluids the module publishes, so this failure flags healthy wells as loaded rather than the reverse, which is why it survives for years unnoticed.'),
  ('gaswell', 'beginner', 'module', 'm01-a-well-that-drowns', 14, 'The droplet has a size set by break-up, and then that size disappears from the answer. Why?', '["The module averages over a population of sizes, so no single value survives into the velocity it reports for the station.", "It is swapped for the tubing inside diameter, which is the only length the module carries anywhere among its inputs.", "The diameter appears in both the break-up condition and the force balance, so it cancels between them.", "It is fixed at one value by the Weber number."]'::jsonb, 2, 'What remains depends on three groups only, the interfacial tension to the quarter power, the density difference to the quarter power, and one over the square root of the gas density.'),
  ('gaswell', 'beginner', 'module', 'm01-a-well-that-drowns', 15, 'Which question does the one droplet picture refuse to answer?', '["Whether a droplet rises or falls at a station.", "How much liquid arrives at surface, because the picture never says how many droplets there are and sorts only one of them into carried or falling back.", "What the gas density is at a given pressure.", "What velocity a droplet needs in order to be carried."]'::jsonb, 1, 'Real tubing also moves liquid as a film running along the wall, a second transport mechanism this picture does not contain at all.'),
  ('gaswell', 'beginner', 'module', 'm02-gas-at-a-station', 1, 'The true compressibility factor at a station is 0.8522484090 and 0.90 was supplied in its place. Which way is the density wrong?', '["It came out too high, because a compressibility factor above the true one raises the density the module returns for that station.", "It came out too low, because the compressibility factor sits in the denominator.", "It is unaffected, because the compressibility factor cancels between the density and the terminal velocity that follows from it.", "It is wrong by 76 parts per million."]'::jsonb, 1, 'A gas whose real compressibility factor lies below the number supplied is denser than you calculated, and the error propagates silently into every velocity and rate that follows.'),
  ('gaswell', 'beginner', 'module', 'm02-gas-at-a-station', 2, 'Dranchuk and Abou-Kassem give 0.8522484090 at 1000.0 psia and 80.33 degF, and 0.9010583689 at the same pressure and 140.33 degF. What does that pair show?', '["Compressibility depends on pressure alone.", "Warming a gas always lowers its compressibility.", "Those two figures bracket the pinned 0.90 by design.", "Compressibility moves with temperature as well as with pressure, so one value carried unchanged down a producing string stops being right at the next station."]'::jsonb, 3, 'The step from 80.33 degF to 140.33 degF is smaller than the change a producing string sees between its shoe and its wellhead.'),
  ('gaswell', 'beginner', 'module', 'm02-gas-at-a-station', 3, 'Why do the published velocity goldens never exercise the compressibility route?', '["Every published row supplies z as an input.", "That route was written after the goldens were cut, and nobody has gone back to extend the published table so that it reaches the newer code.", "Sutton pseudo-criticals are only valid above 1000.0 psia, and most of the published rows sit below that limit and could not be checked.", "The route lives inside the same module, so exercising it would duplicate an assertion the engine gate already holds elsewhere."]'::jsonb, 0, 'Pinning the compressibility factor isolates the droplet balance from the equation of state, which is a clean way to publish a droplet table and leaves the Sutton plus Dranchuk and Abou-Kassem path untested.'),
  ('gaswell', 'beginner', 'module', 'm02-gas-at-a-station', 4, 'Which quantities does a gas density at a station need?', '["A pressure, a temperature, a tubing inside diameter and a flow rate, since density is what turns a rate at surface into a velocity downhole.", "A pressure and an interfacial tension.", "A pressure, a molecular weight, a compressibility factor, a gas constant and a temperature.", "A temperature and a liquid density."]'::jsonb, 2, 'It is p M over z R T, with R at 10.7316 psia ft3 per lbmol degR in both production modules, so the gas constant is never a source of disagreement between them.'),
  ('gaswell', 'beginner', 'module', 'm02-gas-at-a-station', 5, 'At 1000.0 psia, 600.0 degR, z 0.88 and gas gravity 0.65 the oracle publishes 3.3226524714 lbm/ft3 while the engine returns 3.3226453778 lbm/ft3. What does that establish?', '["The engine is in error by 7.0936e-6 lbm/ft3, and its gate has been loosened enough to let that difference through unchallenged.", "Both routes carry the same molecular weight of air, which is the reason they land so close together at this particular station.", "The compressibility factor of 0.88 is correct.", "Two implementations in different unit systems reach one density to six decimal places."]'::jsonb, 3, 'One implementation is in SI with no gc anywhere and the other in field units carrying gc explicitly, which is what makes the agreement worth something.'),
  ('gaswell', 'beginner', 'module', 'm02-gas-at-a-station', 6, 'How far apart are the molecular weights of air carried by gasWellLoading and by gasProperties?', '["0.002200 lbm/lbmol, which is wide enough that one of the two modules fails its own published golden case for density.", "0.002200 lbm/lbmol, which is 75.9603 parts per million.", "Nothing, both carry 28.9647.", "About one percent."]'::jsonb, 1, 'Both are defensible roundings of one physical constant and neither module is wrong on its own, which is exactly what makes a seam of this kind hard to see.'),
  ('gaswell', 'beginner', 'module', 'm02-gas-at-a-station', 7, 'At 2500.0 psia and 620.0 degR the two routes return 7.8600213238 and 7.8594243196 lbm/ft3. What accounts for the difference?', '["A different gas constant inside each module.", "A rounding in the conversion from psi/ft.", "The molecular weight of air and nothing else, because pressure, temperature, compressibility factor and gas gravity were identical on both routes.", "An adjustment applied on one route only."]'::jsonb, 2, 'The gap is 5.970042e-4 lbm/ft3, or 7.595452e-5 of the density, far below what any field pressure or temperature gauge could resolve.'),
  ('gaswell', 'beginner', 'module', 'm02-gas-at-a-station', 8, 'That density gap moves the Turner critical velocity by 4.050320e-5 of itself against 7.595452e-5 of the density. Why is the velocity fraction the smaller one?', '["Density enters as one over its square root.", "An adjustment of 1.2000 divides the fractional change before the velocity is reported at the station.", "The velocity is rounded to ten decimal places, and the change falls partly below the last figure retained.", "The flow area cancels part of the change when the velocity is converted through into a rate in Mscf/d."]'::jsonb, 0, 'The two fractions stand at 0.53325597, which is the one half from the inverse square root plus the buoyancy term inside the density difference.'),
  ('gaswell', 'beginner', 'module', 'm02-gas-at-a-station', 9, 'Beyond the molecular weight, how else do the two doors disagree?', '["One demands a compressibility factor while the other derives its own from Sutton pseudo-criticals before it returns anything at all.", "One takes temperature in degR and the other takes it in degF and converts internally.", "One returns a density and refuses a gradient.", "One uses gc and the other uses 6.852177e-5."]'::jsonb, 1, 'gasProperties hands back a gradient in psi/ft rather than a density, 0.0545793356 psi/ft at that station, and it takes 160.3300 degF to 620.0000 degR exactly, so the conversion is sound and only the labelling is missing.'),
  ('gaswell', 'beginner', 'module', 'm02-gas-at-a-station', 10, 'Why has the split between the two molecular weights cost nothing so far?', '["A gate compares the two routes at every published station and holds them to a tolerance wide enough to swallow the gap between them.", "The larger of the two values is used everywhere the answer matters, so the smaller one only ever reaches a diagnostic message.", "Nothing in the loading path calls both routes for one station.", "The gap falls below machine precision."]'::jsonb, 2, 'A critical velocity is built inside gasWellLoading on its own 28.9647 lbm/lbmol and a gradient inside gasProperties on its own 28.9625, so two forms of one constant stay free while nothing crosses between them.'),
  ('gaswell', 'beginner', 'module', 'm02-gas-at-a-station', 11, 'If something did one day cross that seam, what would the symptom look like?', '["Two answers for one station agreeing to four decimals and parting at the fifth, with no test in either module watching that place.", "An exception thrown at the module boundary.", "A verdict flipping from loaded to unloaded.", "A density coming back with ok = false."]'::jsonb, 0, 'It would never surface as an error, which is why a constant written two ways is worth knowing about even while both modules pass every test they carry.'),
  ('gaswell', 'beginner', 'module', 'm02-gas-at-a-station', 12, 'Of the three groups inside the droplet balance, which one does a station actually measure?', '["The interfacial tension, which is read from a sample of the produced liquid and then enters at a quarter power.", "The liquid density, at a quarter power.", "None of the three are measured.", "The gas density, and it carries the minus one half power."]'::jsonb, 3, 'The other two enter at a quarter power and neither is measured at all, which is why chasing precision in the liquid properties while accepting the station temperature as given is the wrong order of work.'),
  ('gaswell', 'beginner', 'module', 'm02-gas-at-a-station', 13, 'The published Turner critical rate at 2500.0 psia is 2496.154595078 Mscf/d at 540.0 degR and 2341.162863678 Mscf/d at 620.0 degR. Which way does a temperature guessed too high push a verdict?', '["Toward caution, since a warmer gas is denser and therefore demands a larger rate before a well can be declared free of liquid.", "Toward flattery, since the rate it demands is lower.", "Neither way, because the compressibility factor supplied alongside the temperature cancels the effect entirely at any pressure.", "Toward flattery below the Coleman pressure limit of 1000.0 psia and toward caution above it."]'::jsonb, 1, 'Pressure raises density and temperature lowers it, which is what p over z T says, and a wellhead temperature taken from a memory of last month is worth the whole of that difference.'),
  ('gaswell', 'beginner', 'module', 'm02-gas-at-a-station', 14, 'A report prints a Coleman critical velocity of 4.3868983237 ft/s beside a terminal droplet velocity of 4.3868983237 ft/s. What is happening?', '["Coleman applies an adjustment of 1.0000, so those two lines are a single result printed twice under two names.", "The report has rounded two different numbers alike.", "The station happens to sit at the Coleman limit.", "Turner has been applied to both by mistake."]'::jsonb, 0, 'Turner applies 1.2000 to the same number, and the goldens carry both names on every one of the twelve published rows so the identity is visible rather than assumed.'),
  ('gaswell', 'beginner', 'module', 'm02-gas-at-a-station', 15, 'Which sentence does a single station reading support?', '["The well needs 2341.162863678 Mscf/d, because the wellhead is where the gauge is read and that reading is exact.", "The well is not loading anywhere, because in a gas producer the controlling station always sits at the wellhead.", "Water through 2.441 in at 2500.0 psia and 620.0 degR needs 2341.162863678 Mscf/d.", "The well will load within the month."]'::jsonb, 2, 'The distance between a station claim and a well claim is every other point in the string, each with its own pressure, its own temperature and possibly its own diameter.'),
  ('gaswell', 'beginner', 'module', 'm03-the-droplet-balance', 1, 'What does the weight side of the droplet balance use, and where has buoyancy gone?', '["The droplet volume times the difference between the liquid and the gas density, which is where buoyancy already sits.", "The droplet volume times the liquid density alone, with buoyancy added afterwards as a separate correction once a terminal velocity has been found.", "The liquid density times gc, with no buoyancy anywhere.", "The mass of liquid the well makes each day."]'::jsonb, 0, 'That is why a heavier gas lifts a droplet more easily quite apart from the drag it applies, since the difference driving the weight shrinks as the gas gets denser.'),
  ('gaswell', 'beginner', 'module', 'm03-the-droplet-balance', 2, 'Which conversion constants does the field unit form of the balance carry that the checking implementation does not?', '["The Turner adjustment of 1.2000 and the Coleman adjustment of 1.0000, which are what separate a terminal velocity from a critical one.", "Standard conditions of 14.70 psia and 519.67 degR, which enter wherever a velocity is turned into a rate at surface conditions.", "gc at 32.1740 lbm ft per lbf s2, and 6.852177e-5 to take dyne/cm into lbf/ft.", "A drag coefficient and a Weber number."]'::jsonb, 2, 'Both are explicit in the engine and absent from the SI oracle that checks it, which is what makes the agreement between the two roads worth something.'),
  ('gaswell', 'beginner', 'module', 'm03-the-droplet-balance', 3, 'The oracle publishes 1.5935357894 and the engine reaches 1.5935346111. Why does the gate accept that?', '["Both figures round to the same four decimals.", "It is checking that the engine produces the constant through its own derivation rather than storing it, and a relative difference of 7.3947e-7 is what crossing unit systems costs.", "The published value is a book number nobody checks.", "The constant never reaches any answer the module returns."]'::jsonb, 1, 'Checking that a number is produced rather than remembered is the only way to tell a derivation from a coefficient somebody typed in.'),
  ('gaswell', 'beginner', 'module', 'm03-the-droplet-balance', 4, 'Moving the drag coefficient across the whole span from 0.22 to 1.10 changes the leading constant by how much?', '["By a factor of five, because the constant runs linearly with the drag coefficient and that span itself covers a factor of five.", "By nothing at all, because the drag coefficient cancels against the critical Weber number inside the balance.", "By a factor of twenty five, because the drag coefficient enters squared before the droplet diameter is eliminated.", "By less than a factor of two."]'::jsonb, 3, 'The relationship is a fourth root: 0.22 gives 1.8950426975 and 0.88 gives 1.3399975420, which is why the balance tolerates a coefficient nobody can defend to better than a factor of two.'),
  ('gaswell', 'beginner', 'module', 'm03-the-droplet-balance', 5, 'Sixteen times the interfacial tension does what to the terminal velocity?', '["Multiplies it by four, since the tension enters under a square root once the droplet diameter has been eliminated.", "Multiplies it by sixteen.", "Doubles it, a ratio of 2.0000000000.", "Leaves it unchanged."]'::jsonb, 2, 'Sigma 1.0 with a density difference of 60.0 gives 2.5605819862 ft/s and sigma 16.0 gives 5.1211639724 ft/s at a gas density of 3.0 lbm/ft3, which is the quarter power made visible.'),
  ('gaswell', 'beginner', 'module', 'm03-the-droplet-balance', 6, 'Raising the gas density fourfold takes the terminal velocity from 12.3434660205 to 6.1717330102 ft/s. Which exponent is on show?', '["Minus one half, so a fourfold rise halves it, a ratio of exactly 0.5000000000.", "Minus one, a plain inverse.", "Minus a quarter, as on the liquid terms.", "Minus two, a square law."]'::jsonb, 0, 'Gas density is the only one of the three groups a station measures rather than assumes, which is why loading is a pressure and temperature story and not a fluid chemistry one.'),
  ('gaswell', 'beginner', 'module', 'm03-the-droplet-balance', 7, 'A sigma of 1.0 dyne/cm with a density difference of 60.0, and a sigma of 60.0 with a difference of 1.0, both return 2.5605819862 ft/s. Why?', '["The module clamps the interfacial tension to the liquid density whenever either one falls below 5.0 dyne/cm, so those rows run on identical inputs.", "Both rows sit at a gas density of 3.0 lbm/ft3, and gas density is the only term that survives once the droplet diameter has been eliminated.", "It is a coincidence of the rounding.", "Both groups enter at the same power, so exchanging their values exchanges nothing."]'::jsonb, 3, 'Each of the two enters at a quarter power, so a factor of sixteen in either one is worth a factor of two in the velocity and no more.'),
  ('gaswell', 'beginner', 'module', 'm03-the-droplet-balance', 8, 'At 1000.0 psia and 540.0 degR the terminal velocity is 6.5866393859 ft/s. What is the Coleman critical velocity at that station?', '["7.9039672631 ft/s, because Coleman applies the adjustment of 1.2000 that separates the two published correlations.", "6.5866393859 ft/s, because Coleman applies 1.0000.", "It cannot be found without the tubing size.", "Lower, since Coleman is the gentler test."]'::jsonb, 1, 'Turner applies 1.2000 to the same number and reads 7.9039672631 ft/s there, and the published table carries both names on every row so the identity cannot be mistaken for an agreement between two methods.'),
  ('gaswell', 'beginner', 'module', 'm03-the-droplet-balance', 9, 'Sweeping interfacial tension from 5.0 to 80.0 dyne/cm at one published station moves the terminal velocity how far?', '["By a factor of sixteen, which is why a tension read off a chart is the largest single error on a real gas well.", "By nothing measurable, because the module clamps the tension to 60.0 dyne/cm whenever water is the selected fluid.", "From 3.7989369177 to 7.5978738354 ft/s.", "From 4.5587243012 to 9.1174486024 ft/s, which is what the same sweep publishes at that station."]'::jsonb, 2, 'Neither 5.0 nor 80.0 dyne/cm is a liquid a gas well produces, so everything a real well makes sits inside a span worth less than a factor of two.'),
  ('gaswell', 'beginner', 'module', 'm03-the-droplet-balance', 10, 'Holding sigma at 60.0 dyne/cm, the liquid density span from 40.0 to 75.0 lbm/ft3 is worth how much in terminal velocity?', '["About a foot per second, from 6.1628840484 to 7.2823697925 ft/s.", "Nearly a factor of two, running from 6.1628840484 ft/s at the light end up to 7.2823697925 ft/s at the heavy end of that span.", "Nothing, because the balance uses the difference between the liquid and the gas density and that difference is fixed at any one station.", "Around five feet per second."]'::jsonb, 0, 'That range covers everything from a light condensate to a heavy brine, and it passes 6.5440748684 ft/s at 50.0 and 6.8683281812 ft/s at 60.0 lbm/ft3 on the way.'),
  ('gaswell', 'beginner', 'module', 'm03-the-droplet-balance', 11, 'Which of the two fluids the module publishes loads a well at the lower rate, and why?', '["Water, because a well makes more of it.", "Condensate, at 20.0 dyne/cm and 45.0 lbm/ft3, because about a third the tension together with a lower density both make its droplets easier for the gas to carry.", "Condensate, because it evaporates in the tubing.", "Water, at 60.0 dyne/cm and 67.0 lbm/ft3."]'::jsonb, 1, 'Published water at 1000.0 psia and 620.0 degR needs 1509.356272243 Mscf/d through 2.441 in tubing while condensate needs 1031.930477998 Mscf/d, and a condensate well between those two figures is unloaded.'),
  ('gaswell', 'beginner', 'module', 'm03-the-droplet-balance', 12, 'A note records the water terminal velocity over the condensate terminal velocity as 1.4626530609. What has to be recorded alongside it?', '["The tubing inside diameter of 2.441 in, because the flow area does not cancel between a velocity ratio and a rate ratio.", "The drag coefficient of 0.4400.", "The station it belongs to, 1000.0 psia and 620.0 degR.", "Nothing, it is a property of the two fluids."]'::jsonb, 2, 'At a real station the gas density appears twice, once on its own under the square root and once inside the density difference, so that figure does not hold at 300.0 or at 2500.0 psia.'),
  ('gaswell', 'beginner', 'module', 'm03-the-droplet-balance', 13, 'Why does the water over condensate rate ratio come out at the same 1.4626530609 as the velocity ratio?', '["Because both fluids are evaluated at one gas density, and gas density is the only term the conversion from a velocity to a rate touches.", "Because the adjustment of 1.2000 is applied to the rate and not to the velocity, and the two effects happen to offset at this station.", "It is a coincidence at that station.", "The flow area and the standard conditions cancel between the two."]'::jsonb, 3, 'Those two being one number is not a station property, since the cancellation holds anywhere, which is the opposite of what is true of the ratio itself.'),
  ('gaswell', 'beginner', 'module', 'm03-the-droplet-balance', 14, 'An unrecognised fluid id and an unknown correlation name are both typing mistakes. How does the module treat each of them?', '["Both are refused with an error object naming the values the module publishes, so neither one can reach a velocity calculation.", "The fluid id falls back to water while the correlation is refused with an error.", "The correlation falls back to Turner while the fluid id is refused with ok = false and no velocity returned for that station.", "Both fall back to a published default, water for the fluid and Coleman for the correlation, and each returns a valid velocity under the name that was asked for."]'::jsonb, 1, 'Water is the harsher of the two fluids, so the fallback flags healthy wells as loaded rather than the reverse, and a failure running in the conservative direction is exactly the kind that survives review.'),
  ('gaswell', 'beginner', 'module', 'm03-the-droplet-balance', 15, 'Which chosen number inside the balance moves the answer furthest, and where does it show up in the output?', '["The critical Weber number of 30.0000, and it shows up nowhere in what the module returns, which is why nobody argues about it.", "The interfacial tension, and it is printed with every result.", "The liquid density, and it is printed with the fluid name.", "The drag coefficient, and it is returned beside the velocity."]'::jsonb, 0, 'Moving it from 20.0 to 60.0 takes the leading constant from 1.4399210674 to 1.8950426975, a larger swing than the entire span of liquid properties a gas well produces.'),
  ('gaswell', 'beginner', 'module', 'm04-critical-velocity-and-rate', 1, 'What does the rate constant 3054.38693878 Mscf/d per (ft/s x ft2 x psia / degR) encode?', '["The drag coefficient of 0.4400 carried into field units.", "The Turner adjustment of 1.200000 folded into the last step.", "Nothing but the carriage to standard conditions, since it rebuilds by hand as 86400 x 519.67 / (14.70 x 1000) from a standard pressure of 14.70 psia and a standard temperature of 519.67 degR.", "A property of the gas, fixed by the gravity of 0.65."]'::jsonb, 2, 'Divided by 1000 it reads 3.054387, which is the 3.06 the textbooks print for MMscf/d.'),
  ('gaswell', 'beginner', 'module', 'm04-critical-velocity-and-rate', 2, 'A velocity of 12.0 ft/s through a 2.441 in string at 900.0 psia, 580.0 degR and z 0.9 converts to 2053.715375332 Mscf/d, and that rate is then converted back at the same station. What comes back?', '["12.000000000000 ft/s, a round trip closure of -1.7764e-15 ft/s.", "A figure slightly below 12.0 ft/s, because the forward step multiplies by the Turner adjustment of 1.200000 and the reverse step has no way to remove it again.", "Something near 12.0 ft/s but not equal to it, because the carriage to standard conditions of 14.70 psia and 519.67 degR is not a reversible operation.", "Nothing, since a rate cannot be run backwards."]'::jsonb, 0, 'The two conversions are the same three multiplications run in opposite directions, so the closure is limited only by floating point.'),
  ('gaswell', 'beginner', 'module', 'm04-critical-velocity-and-rate', 3, 'Two published stations share water at 60.0 dyne/cm and 67.0 lbm/ft3, a pressure of 1000.0 psia and a 2.441 in string, and differ only in temperature. The hotter one demands 8.4847482463 ft/s against 7.9039672631 ft/s, yet its critical rate reads 1509.356272243 Mscf/d against 1614.343188395 Mscf/d. Why?', '["The flow area contracts as the tubing warms.", "The published figure was quoted through a narrower string.", "The hotter station switches correlation, since Coleman applies at the lower temperature and Turner takes over once the gas has warmed past the published limit.", "The same standard volume occupies more space at 620.0 degR, so the faster gas carries the smaller rate."]'::jsonb, 3, 'Temperature alone moved the requirement by about a hundred Mscf/d with nothing about the well changed.'),
  ('gaswell', 'beginner', 'module', 'm04-critical-velocity-and-rate', 4, 'Two candidate strings have flow areas of 0.0659002292 ft2 and 0.0324984725 ft2. Read at one station, what does moving from the first to the second do to the two velocities?', '["It raises both by that ratio, since a critical velocity is a critical rate divided by the same flow area that the actual velocity is built from.", "It leaves the critical velocity exactly where it was and raises the actual velocity by the ratio of the areas.", "It raises the critical velocity by the square root of that ratio, because a narrower bore supports a larger stable droplet through the critical Weber number of 30.0000.", "It leaves both velocities where they were and moves only the critical rate, which is the field a sizing compares against the well."]'::jsonb, 1, 'The droplet balance carries a surface tension, two densities and a Weber number and no diameter at all, so a bore reaches the verdict only through the area: those two strings share one critical velocity and differ in what the gas is doing.'),
  ('gaswell', 'beginner', 'module', 'm04-critical-velocity-and-rate', 5, 'A 2.441 in string carries 0.0324984725 ft2. What area does a 1.610 in string carry?', '["0.0141377124 ft2, since the area is the circle of the inside diameter.", "0.0217076689 ft2, the catalogue value against 1.995 in, because the two sizes settle on one area.", "0.0227202653 ft2, because area follows the diameter directly and 1.610 in sits close to 2.041 in.", "2.03583058 ft2, read straight off the catalogue."]'::jsonb, 0, 'The catalogue prints 2.03583058 in2 for that same string, and the engine carries the area in ft2 throughout.'),
  ('gaswell', 'beginner', 'module', 'm04-critical-velocity-and-rate', 6, 'Doubling an inside diameter from 2.441 in to 4.882 in multiplies the flow area by 4.0000000000. At a fixed critical velocity, what becomes of the critical rate?', '["It doubles, following the diameter rather than the area.", "It is unchanged, since the balance never sees a diameter.", "It rises by that same factor of four, because the critical rate is proportional to the flow area once the station and the critical velocity are both held.", "It falls by four, because wider tubing slows the gas."]'::jsonb, 2, 'The same well can read healthy or loaded on one day depending on what string is hanging in it.'),
  ('gaswell', 'beginner', 'module', 'm04-critical-velocity-and-rate', 7, 'One published station is walked across a contiguous production sweep from 400.0 to 2600.0 Mscf/d. What does the critical rate read at each point of it?', '["It falls away as production falls, because a well making less gas needs less gas to lift the droplet it is still making at that station.", "1614.343766935 Mscf/d everywhere, because no production number enters it.", "It climbs with the sweep, from 400.0 to 2600.0 Mscf/d.", "It reads 1614.343766935 Mscf/d only at the crossing."]'::jsonb, 1, 'Its inputs are station properties and fluid properties, and none of them knows what the well is flowing today.'),
  ('gaswell', 'beginner', 'module', 'm04-critical-velocity-and-rate', 8, 'What kind of number is a critical rate?', '["A forecast of the rate the well will settle at once the liquid it can no longer carry has finished collecting in the bottom of the string.", "A measurement of the gas velocity in the tubing, carried to standard conditions of 14.70 psia and 519.67 degR.", "A property of the well rather than of a station.", "A rate the string requires there, not a rate the well can supply."]'::jsonb, 3, 'There is no inflow performance anywhere in these modules, so whether the well can deliver it is a question they never ask.'),
  ('gaswell', 'beginner', 'module', 'm04-critical-velocity-and-rate', 9, 'At one published station 400.0 Mscf/d gives an actual velocity of 1.9584354355 ft/s. What does 800.0 Mscf/d give?', '["3.9168708710 ft/s.", "5.8753063066 ft/s, because doubling the rate more than doubles the velocity once the gas is given room to expand.", "6.8545240243 ft/s, since the station pressure falls as the well is opened up and the same gas then occupies more space.", "1.9584354355 ft/s, unchanged, because an actual velocity belongs to the station in the way a critical rate does."]'::jsonb, 0, 'The relation is linear because the area, the pressure, the temperature and z are all held at the station.'),
  ('gaswell', 'beginner', 'module', 'm04-critical-velocity-and-rate', 10, 'Which quantity in a loading check comes from the well rather than from a station property, a fluid table or a tubing catalogue?', '["The interfacial tension, since the balance reads it from the liquid the well is actually making at the hour of the survey.", "The production rate, which arrives as a rate and is divided down to a velocity.", "The compressibility factor z.", "The critical velocity of the droplet."]'::jsonb, 1, 'Nothing here measures a velocity, so even the actual velocity is a supplied rate divided by a typed geometry.'),
  ('gaswell', 'beginner', 'module', 'm04-critical-velocity-and-rate', 11, 'Why is a velocity ratio identical to a rate ratio at one station, to a difference of 0.0000e+0?', '["The Turner adjustment of 1.200000 divides out of both.", "Standard conditions are common to both sides of it.", "Both sides of the comparison are evaluated at the same station on the same area, so the conversion between a velocity and a rate cancels out of the fraction entirely.", "It holds only above the crossing, where the flag reads false."]'::jsonb, 2, 'That is why the ratio is the figure to carry: it is unitless and says the same thing in either currency.'),
  ('gaswell', 'beginner', 'module', 'm04-critical-velocity-and-rate', 12, 'A station reports a ratio of 0.9997870547 at a gas rate of 1614.0 Mscf/d. What is the verdict?', '["Loaded, because the comparison is strict and anything below one is a loading verdict.", "Unloaded, since a ratio inside three parts in ten thousand of one falls within the tolerance the balance carries on its own droplet constant.", "Marginal, and a third flag is returned for the band immediately beneath one so that a reader is not forced to choose.", "Unloaded, since 1614.0 clears the critical rate."]'::jsonb, 0, 'Nothing in the balance says how far under one is close enough, so the engine has no way to be less pedantic.'),
  ('gaswell', 'beginner', 'module', 'm04-critical-velocity-and-rate', 13, 'Rounding a ratio of 0.9997870547 to two decimals before it is read does what?', '["It leaves the verdict intact, because the flag is computed from the unrounded figure and travels beside the rounded one in the same returned object.", "It shifts the crossing down to 1600.0 Mscf/d.", "It changes the critical rate but not the flag.", "It turns a loading verdict into a passing one, since 1.00 reads as clearing the threshold."]'::jsonb, 3, 'Everything at or below the critical rate is a well that cannot lift its droplets there, and the ratio says by how little rather than whether.'),
  ('gaswell', 'beginner', 'module', 'm04-critical-velocity-and-rate', 14, 'What happens when the conversion from a rate to a velocity is handed a flow area of zero?', '["It returns a velocity of zero.", "It substitutes the 2.441 in area.", "It returns nothing at all rather than an infinite velocity, and that is the only geometric case it guards.", "It returns a large finite velocity."]'::jsonb, 2, 'A gas density at a temperature of zero is refused in the same spirit rather than dividing through.'),
  ('gaswell', 'beginner', 'module', 'm04-critical-velocity-and-rate', 15, 'An engineer carries a critical rate from one station to another because the fluid and the tubing did not change. What is wrong with that?', '["Nothing, provided both stations sit in the same string, since a critical rate depends on the fluid properties and the flow area alone.", "The pressure, the temperature and z changed, and those three set the rate.", "The recommendation would have to be taken again, and that recommendation is the only part of the calculation which moves between stations.", "The droplet constant of 1.5935346111 is derived per station, so it has to be rebuilt before any rate can be carried elsewhere."]'::jsonb, 1, 'Two published stations on one fluid and one string still read 1614.343188395 and 1509.356272243 Mscf/d on temperature alone.'),
  ('gaswell', 'beginner', 'module', 'm05-two-correlations', 1, 'What separates a Turner critical velocity from a Coleman critical velocity at one station?', '["A different drag coefficient, since Turner treats the droplet as a rigid sphere at 0.4400 while Coleman lets it deform on the way up.", "One multiplier, 1.200000 against 1.000000, applied after the balance has finished.", "A different critical Weber number, so each of the two sizes a different largest stable droplet before either one solves a force balance.", "A different interfacial tension for the liquid."]'::jsonb, 1, 'At 1200.0 psia, 600.0 degR and z 0.9 both routes return a terminal velocity of 6.3307682001 ft/s, a difference of 0.0000e+0 ft/s.'),
  ('gaswell', 'beginner', 'module', 'm05-two-correlations', 2, 'Why does the Coleman critical velocity equal the terminal velocity on all twelve published rows?', '["The published rows were all cut below 1000.0 psia.", "The goldens round both columns to ten places.", "Coleman was fitted on the wells Turner used.", "Coleman applies an adjustment of 1.000000, so its critical velocity is the unmodified output of the droplet balance under another name."]'::jsonb, 3, 'The goldens carry both names against one station so that the identity is visible rather than assumed.'),
  ('gaswell', 'beginner', 'module', 'm05-two-correlations', 3, 'On one published row the two correlations stand 416.025765846 Mscf/d apart. What is that gap?', '["Twenty percent of the Coleman rate, which is what the choice is worth on that station.", "The spread between water and condensate properties there, since each correlation publishes its own starting tension.", "The uncertainty carried on the droplet constant.", "A rounding between two implementations."]'::jsonb, 0, 'The figure is 20.00000000 percent on every published row, so the bigger the well, the bigger the gap in Mscf/d.'),
  ('gaswell', 'beginner', 'module', 'm05-two-correlations', 4, 'Is the adjustment of 1.200000 a safety factor a study may tune?', '["Yes, and it is usually raised on wells with a history of loading so the critical rate carries a margin the operator can defend.", "Yes, since it already varies with the fluid, reading 1.200000 on water and something lower on condensate at one station.", "No, it is a stored constant that nothing derives or checks.", "Only downward, because dropping it toward 1.000000 recovers the unadjusted balance and that is the exact answer."]'::jsonb, 2, 'It reads 1.200000 at 300.0 psia and at 2500.0 psia, on water and on condensate alike.'),
  ('gaswell', 'beginner', 'module', 'm05-two-correlations', 5, 'What did Turner and his co-authors actually fit?', '["The drag coefficient of 0.4400.", "The critical Weber number of 30.0000.", "The interfacial tension of water.", "One multiplier, after finding their field data sat about twenty percent above the theoretical velocity."]'::jsonb, 3, 'Coleman and his co-authors, working on low-pressure wells, found the unadjusted equation fitted better and left it at 1.000000.'),
  ('gaswell', 'beginner', 'module', 'm05-two-correlations', 6, 'An engineer picks Turner as a matter of prudence because it flags more wells as loaded. What has been chosen?', '["A wider tolerance band on one answer, which is what a safety factor is for and which the returned object records beside the rate.", "A physical claim about which dataset this well resembles, made for a commercial reason.", "The more accurate of the two, since Turner was fitted on a larger set of wells and covers a wider pressure range than Coleman.", "Nothing at all, because the two agree at the wellhead."]'::jsonb, 1, 'The report will not record that the choice was made for margin rather than for fit.'),
  ('gaswell', 'beginner', 'module', 'm05-two-correlations', 7, 'What does the module return when it is asked for a correlation named guess?', '["The Turner answer, since 1.200000 is the shipped default whenever a requested name cannot be matched against the two on offer.", "The Coleman answer, on the principle that an unadjusted balance is the safer thing to hand back when the caller was not understood.", "ok = false, with an error naming turner and coleman.", "A valid velocity under whatever name was asked for, the way an unrecognised fluid id is handled."]'::jsonb, 2, 'The fluid id is where it does fall back silently, quietly selecting 60.0 dyne/cm and 67.0 lbm/ft3.'),
  ('gaswell', 'beginner', 'module', 'm05-two-correlations', 8, 'The Coleman pressure limit is 1000.0 psia. What does the branch return at exactly 1000.00 psia?', '["turner, because the test is strictly below the limit for coleman.", "coleman, since the limit is the top of the range Coleman''s data covered and a well sitting on it is still inside that range.", "Neither, and it returns ok = false.", "Whatever the station above it returned."]'::jsonb, 0, 'At 999.96 psia, four hundredths of a psi under it, the same branch returns coleman.'),
  ('gaswell', 'beginner', 'module', 'm05-two-correlations', 9, 'Why did the reason string once print a pressure of 999.88 psia as 1000?', '["The branch itself compared rounded pressures.", "It rounded the pressure it had branched on to a whole number, so a well below the limit printed as the limit under a branch that never fires there.", "The gauge reading was rounded before the call.", "The limit was stored as 999.88 psia at the time."]'::jsonb, 1, 'The same sentence also hardcoded the word wellhead for whatever station it was handed, and that label is supplied by the caller now.'),
  ('gaswell', 'beginner', 'module', 'm05-two-correlations', 10, 'Printing that pressure to one decimal does what to the collision?', '["It removes the collision, because a pressure carried to one decimal can no longer render as a limit it does not equal at that precision.", "It moves the collision across the limit, so the sentence now misreads wells above 1000.0 psia instead of wells beneath it.", "It narrows the class of wells that can print a contradictory sentence by ten.", "It leaves the collision exactly as wide."]'::jsonb, 2, 'Anything inside 0.05 psi of the limit still renders as the limit, and 999.96 psia is one such well.'),
  ('gaswell', 'beginner', 'module', 'm05-two-correlations', 11, 'What does the recommendation itself amount to?', '["Guidance, since it does not switch the correlation for anybody.", "A decision, and the critical rate handed back downstream has already been built under the correlation it selected for the caller.", "A critical velocity under both names.", "The station the pressure was read at."]'::jsonb, 0, 'Which pressure to give it is not a question it can answer, and that is the one worth carrying forward.'),
  ('gaswell', 'beginner', 'module', 'm05-two-correlations', 12, 'Where does the droplet constant of 1.5935346111 come from?', '["A regression on the same field data that produced the twenty percent adjustment, which is why both correlations carry the identical value.", "The ratio of the standard conditions, 519.67 degR over 14.70 psia, carried in through the rate constant.", "A measurement of droplet size in producing gas wells, reported beside the interfacial tension of water at 60.0 dyne/cm.", "A drag coefficient of 0.4400 and a critical Weber number of 30.0000."]'::jsonb, 3, 'Neither of those two numbers was measured on any well, and a real droplet deforms rather than staying a rigid sphere.'),
  ('gaswell', 'beginner', 'module', 'm05-two-correlations', 13, 'Moving the drag coefficient from 0.22 to 1.10 takes the droplet constant from 1.8950426975 to 1.2672914315. How does that spread compare with the gap between the two correlations?', '["It is narrower, at well under twenty percent.", "It is wider than the twenty percent that separates them, and nobody argues about it because it does not have a name on it.", "It is the same twenty percent, by construction.", "The two cannot be compared at all."]'::jsonb, 1, 'The critical Weber number does the same, running from 1.2108244638 at 10.0 to 2.2535982591 at 120.0.'),
  ('gaswell', 'beginner', 'module', 'm05-two-correlations', 14, 'Water is published at 60.0 dyne/cm and 67.0 lbm/ft3 and condensate at 20.0 dyne/cm and 45.0 lbm/ft3. What are those four figures?', '["Labelled starting points, typed in rather than derived from anything these modules know.", "Correlations in their own right, evaluated at the station pressure and temperature before the droplet balance is entered.", "Measurements of the liquid the well produces.", "Outputs of whichever correlation was chosen."]'::jsonb, 0, 'An unrecognised fluid id falls back to water rather than refusing, so the larger answer comes back with no warning attached.'),
  ('gaswell', 'beginner', 'module', 'm05-two-correlations', 15, 'Which of these lies outside the droplet balance entirely?', '["The buoyancy of the gas on the droplet, which is why the balance uses a liquid density alone rather than a difference of two.", "The largest droplet that survives the gas going past it, which has to be supplied alongside the interfacial tension.", "Liquid running as a film on the tubing wall.", "The weight of the droplet."]'::jsonb, 2, 'Film flow is the other way a gas well carries liquid, and coalescence and break-up in transit are outside the picture with it.'),
  ('gaswell', 'beginner', 'module', 'm06-the-associate-reading', 1, 'In the nine step reading, what has to be fixed before any arithmetic is done at all?', '["The correlation, because the adjustment of 1.200000 or 1.000000 decides which fluid properties the balance then reaches for.", "The tubing catalogue entry.", "The production for the day.", "The station, as a pressure, a temperature, a z and a gas gravity written down together."]'::jsonb, 3, 'Every number after that belongs to those four and to no other station.'),
  ('gaswell', 'beginner', 'module', 'm06-the-associate-reading', 2, 'One published row carries a Turner critical rate of 1614.343766935 Mscf/d from the engine and 1614.343188395 Mscf/d from the oracle. What is the rule for using them?', '["Take the mean of the two, since neither implementation has a claim on being the reference and the gap is far below anything a field gauge could resolve.", "Quote either, label the road it came from, and never mix the two inside one claim.", "Quote the engine figure alone, because the oracle works in SI with no gc anywhere and its answer has to be converted before it can be read in Mscf/d.", "Quote neither until the disagreement is closed."]'::jsonb, 1, 'The same fork runs through the gas densities, where one road publishes 3.3226524714 lbm/ft3 and the other returns 3.3226453778 lbm/ft3.'),
  ('gaswell', 'beginner', 'module', 'm06-the-associate-reading', 3, 'A published station is written out as eleven quantities, from the pressure through to the critical rate. How many of the eleven came off a gauge?', '["Four, the whole station description.", "Six, everything except the computed values.", "Two, the pressure and the temperature, with two more supplied for the gas, two chosen with the fluid and five computed from all of them.", "Eleven, since the goldens are measured."]'::jsonb, 2, 'The five computed values inherit everything that was assumed and print with the same run of decimals as the pressure that was actually read.'),
  ('gaswell', 'beginner', 'module', 'm06-the-associate-reading', 4, 'Which single output of the Associate chain carries a verdict?', '["The unitless ratio.", "The critical rate in Mscf/d, since that is the figure a report prints beside the measured rate and the one a decision is taken on.", "The terminal droplet velocity, because it is the output of the force balance and everything after it is only a change of units.", "The gas density in lbm/ft3, which is the first thing a station gives and the term the balance is most sensitive to."]'::jsonb, 0, 'Everything before it is bookkeeping, and the comparison against one is strict rather than banded.'),
  ('gaswell', 'beginner', 'module', 'm06-the-associate-reading', 5, 'Water gives 7.0706235386 ft/s and condensate 4.8341084620 ft/s at 1000.0 psia and 620.0 degR, a ratio of 1.4626530609. How should that ratio be quoted?', '["As a fluid constant, since the two liquids differ only in tension and in density and neither of those moves with pressure in these modules.", "With its station, because the gas density sits inside the density difference as well.", "As a property of the 2.441 in string.", "Only once both have been converted to rates."]'::jsonb, 1, 'The velocity ratio and the rate ratio agree at 1.4626530609 because the area and the standard conditions cancel between them.'),
  ('gaswell', 'beginner', 'module', 'm06-the-associate-reading', 6, 'A condensate well flows between 1031.930477998 and 1509.356272243 Mscf/d and is assessed on water properties out of habit. What follows?', '["It is reported as unloaded when it is loading.", "The module refuses, since the fluid is wrong.", "Nothing, the two fluids agree there.", "It is reported as loading when it is not, and a velocity string or a plunger is recommended for a well that needs neither."]'::jsonb, 3, 'Water is the harsher fluid of the two the module publishes, so the error runs in the direction that survives review.'),
  ('gaswell', 'beginner', 'module', 'm06-the-associate-reading', 7, 'Which chosen number inside the balance moves the answer most, and never appears in anything the module returns?', '["The critical Weber number of 30.0000.", "The interfacial tension of 60.0 dyne/cm, which is the one term nobody has measured on the well in front of them.", "The omission of film flow on the tubing wall, which is the assumption that sounds worst of the ones on offer.", "The gas gravity of 0.65."]'::jsonb, 0, 'Moving it from 20.0 to 60.0 takes the droplet constant from 1.4399210674 to 1.8950426975, a wider swing than any liquid a gas well produces.'),
  ('gaswell', 'beginner', 'module', 'm06-the-associate-reading', 8, 'Converting 12.0 ft/s to 2053.715375332 Mscf/d and straight back returns 12.000000000000 ft/s. What is that check worth?', '["It confirms the droplet balance, since a closure of -1.7764e-15 ft/s is far tighter than the 7.3947e-7 that separates the two droplet constants.", "It confirms the correlation was chosen correctly.", "It confirms the area, the pressure, the temperature and z were the same on both passes.", "It proves the tubing size was in the catalogue."]'::jsonb, 2, 'The two conversions are one set of multiplications run in opposite directions, so the closure tests the inputs rather than the physics.'),
  ('gaswell', 'beginner', 'module', 'm06-the-associate-reading', 9, 'In what unit does the loading module take a temperature at its door?', '["degF, and it converts internally before dividing, which is why a station is normally written down in degF alongside its pressure in psia.", "degR.", "Either one, since the module inspects the magnitude and treats anything above 400 as an absolute temperature already.", "degR for the density and degF for the rate step, because standard temperature is published as 519.67 degR."]'::jsonb, 1, 'The other production module takes degF at its door and converts internally, so what goes unlabelled is the convention a number was born in.'),
  ('gaswell', 'beginner', 'module', 'm06-the-associate-reading', 10, 'An engineer can spend a day sampling the produced liquid for a tension or a day establishing which station a pressure came from. Which moves the answer more?', '["The station, since the tension enters at a quarter power.", "The tension, because it is the only term in the balance that nobody has measured and it enters at the same power as the gas density.", "Neither, because both feed one terminal velocity and the balance is equally sensitive to every one of its three groups.", "The tension, at a factor of two."]'::jsonb, 0, 'A factor of two in the tension is far less than a factor of two in the velocity, and it is smaller than reading the temperature at the wrong hour.'),
  ('gaswell', 'beginner', 'module', 'm06-the-associate-reading', 11, 'A returned velocity is printed to ten decimal places. What does that establish?', '["That the inputs were checked.", "That the oracle agreed with the engine.", "That the arithmetic is exact, and it is exact about a tension read from a table and a station somebody chose.", "That the station was measured."]'::jsonb, 2, 'The refusals cover physical impossibilities nobody types by accident, so the realistic error comes back as a number with the full run of decimals on it.'),
  ('gaswell', 'beginner', 'module', 'm06-the-associate-reading', 12, 'What question does the Associate tier leave open?', '["Whether the droplet balance is the right physics, since the alternative to a force balance is a full multiphase model of the whole string.", "Which fluid the well makes.", "What a gas density is.", "Where in the well the liquid is losing."]'::jsonb, 3, 'Every number in the tier belongs to one station, at a rate somebody supplied, through an area somebody typed.'),
  ('gaswell', 'beginner', 'module', 'm06-the-associate-reading', 13, 'A Turner critical velocity of 5.2642779885 ft/s is quoted as the velocity in the tubing. What is wrong with that?', '["It is a requirement rather than an observation.", "It was built under one correlation, so the velocity in the tubing would have to be quoted as 4.3868983237 ft/s under the other.", "It belongs to a 2.441 in string, so it has to be rescaled by the flow area before it describes a velocity anywhere at all.", "It is quoted to too many places."]'::jsonb, 0, 'Nothing here measures a velocity, and the actual velocity is a separate calculation that needs the flow rate.'),
  ('gaswell', 'beginner', 'module', 'm06-the-associate-reading', 14, 'How can one well be called healthy and loaded on the same day, on the same gauge reading, the same tubing and the same water?', '["Its z was read at two temperatures.", "Its rate sits between the two published critical rates, which stand twenty percent apart on every row.", "Two gauges disagreed at the wellhead.", "The flow area was typed twice."]'::jsonb, 1, 'The difference is a fixed fraction of a number that grows, so the bigger the well, the bigger the gap in Mscf/d.'),
  ('gaswell', 'beginner', 'module', 'm06-the-associate-reading', 15, 'Across the published stations the Turner requirement runs from 833.741395355 to 2496.154595078 Mscf/d on one fluid, one gravity, one compressibility factor and one string. What moved it?', '["The production those wells were making, since the requirement is evaluated at whatever rate was flowing at the hour of the reading.", "The correlation, because the rows below 1000.0 psia were cut under Coleman and the rows above it under Turner.", "The pressure and the temperature.", "The liquid, since water and condensate carry different tensions and different densities across the published rows."]'::jsonb, 2, 'Nothing about the reservoir, the completion or the liquid rate entered anywhere, so the span is a statement about where the gauge was.'),
  ('gaswell', 'beginner', 'final', null, 1, 'Liquid falls back, the column builds, the rate drops and the velocity drops with it. What does that loop rule out?', '["A verdict at the wellhead, since the loop runs from the bottom of the string upward and the gauge is the last place it arrives.", "A well that unloads itself, because a falling rate lowers the wellhead pressure and a lower pressure lowers the critical rate with it.", "A loading well settling quietly at a slightly lower rate.", "A critical rate that moves, which is what makes the loop a loop rather than a single step down to a new operating point."]'::jsonb, 2, 'The added back pressure lowers the rate, the lower rate lowers the velocity, and the arithmetic runs again the next day from a worse number.'),
  ('gaswell', 'beginner', 'final', null, 2, 'A monthly report prints a metered gas rate and a critical rate of 2496.154595078 Mscf/d in one column. What has been put beside what?', '["A rate the well delivered and a rate one station requires, and the second is not a production figure at all.", "Two production figures, converted at one pressure and temperature.", "A measurement and its tolerance, since a critical rate is the band a metered rate has to be read against.", "Two thresholds, one from the gas and one from the liquid."]'::jsonb, 0, 'There is no inflow performance anywhere in these modules, so a critical rate is what the string requires at that station and never what the reservoir will send.'),
  ('gaswell', 'beginner', 'final', null, 3, 'A station arrives as a pressure, a temperature, a z and a gas gravity. Which of the four came off an instrument?', '["All four, since a gas gravity is read from the separator sample and z from the pressure and temperature the same gauge reported.", "The pressure alone, because a temperature at the door is converted from degF and is therefore a derived figure by the time the module sees it.", "The pressure, the temperature and z, with only the gravity chosen.", "The pressure and the temperature."]'::jsonb, 3, 'In all twelve published velocity rows z is pinned at 0.90 as an input, supplied alongside the pressure and the temperature.'),
  ('gaswell', 'beginner', 'final', null, 4, 'The true compressibility factor at a station is 0.8522484090 and 0.90 was supplied instead. What happens to the velocity a droplet is said to need?', '["It is understated, since a larger z divides a larger density out of the same pressure and a denser gas asks a faster velocity.", "It is overstated, because the density comes out too low and the velocity carries a minus one half power of it.", "It is unchanged, z cancelling out at one station.", "It is overstated by exactly the ratio of the two compressibility factors."]'::jsonb, 1, 'A gas whose real z is below the number supplied is denser than was calculated, and a denser gas lifts a droplet at a lower velocity.'),
  ('gaswell', 'beginner', 'final', null, 5, 'Twelve published velocity rows carry six gas densities between them. Why only six?', '["The condensate rows reuse the water densities to keep the table comparable, which is a convention of the published set rather than a property of the gas.", "Six of the twelve rows were cut at duplicate stations, so the table carries each density twice under a different fluid label.", "Two fluids share every station, and a density knows nothing about the liquid it is asked to carry.", "Density is rounded to six figures, and the twelve values collapse onto six at that precision."]'::jsonb, 2, 'A density is built from the pressure, the temperature, the compressibility factor and the gas gravity, and three pressures crossed with two temperatures give six.'),
  ('gaswell', 'beginner', 'final', null, 6, 'Why does the same brine get harder for a well to lift as the well depletes, when nothing about the brine changes?', '["The gas thins, so the density difference grows while the drag available falls.", "The interfacial tension rises as the pressure falls.", "The droplet grows, because a lower dynamic pressure across it raises the size at which the Weber condition breaks it up, and a bigger droplet is heavier.", "The flow area effectively shrinks as liquid holds up in the string, so the same rate has to be carried through less of the bore than the diameter says."]'::jsonb, 0, 'At 300.0 psia and 540.0 degR published water needs 12.1435923634 ft/s against 4.0737980096 ft/s at 2500.0 psia, so the requirement rises as the well runs down.'),
  ('gaswell', 'beginner', 'final', null, 7, 'A liquid density below the gas density and an interfacial tension of 0.0 dyne/cm both return ok = false. What is being distinguished?', '["A physical impossibility from a typing mistake, which is why a misspelled fluid id is refused in the same way as a tension of zero.", "An input outside the published range from an input inside it, since both of those sit beyond the fluids the module carries.", "A refusal from a warning, the second of which returns a velocity and attaches a flag to it for the caller to read.", "A case with no answer from a case with a bad answer."]'::jsonb, 3, 'With no submerged weight there is nothing for drag to balance, and with no tension there is no droplet for the Weber condition to size.'),
  ('gaswell', 'beginner', 'final', null, 8, 'The critical Weber number runs from 1.4399210674 at 20.0 to 1.8950426975 at 60.0 in the leading constant. How does that compare with the gap between the two correlations?', '["It is the narrower of the two, since 1.200000 against 1.000000 is a twenty percent move and the Weber span is smaller than that.", "It is the wider of the two, and it is the one that never appears in any output.", "The two cannot be compared, because a Weber number scales a velocity while a correlation adjustment scales a rate after the area has entered.", "They are the same size, both being break-up corrections."]'::jsonb, 1, 'The adjustment of 1.200000 has a name on it and gets argued about, while 30.0000 is chosen, never reported, and moves the answer further.'),
  ('gaswell', 'beginner', 'final', null, 9, 'Every published critical rate is quoted through one string. Which, and what happens to those figures on a different one?', '["3.548 in at 0.0686585475 ft2, and the rates scale with the diameter rather than with the area, so a change of string is a linear correction.", "2.441 in at 0.0324984725 ft2, and the rates hold, because a critical rate belongs to the station and the tubing enters only the actual velocity.", "2.441 in at 0.0324984725 ft2, and none of them survives the change.", "1.610 in at 0.0141377124 ft2, the narrowest candidate, which is why the published rates are the conservative end of the range."]'::jsonb, 2, 'The tubing enters the whole calculation once, as an area, so a rate through 2.441 in is a statement about a 2.441 in string and nothing else.'),
  ('gaswell', 'beginner', 'final', null, 10, 'At one published station the ratio reads 1.1150041502 whether it is taken from the velocities or from the rates. Why does the conversion drop out?', '["Both sides are evaluated at the same station on the same area.", "The rate constant of 3054.38693878 is dimensionless once the area is in ft2, so it leaves any ratio it appears in unchanged.", "The velocity ratio and the rate ratio agree only above one, which is where the sweep was read, and they part company below it.", "The standard conditions cancel against the station."]'::jsonb, 0, 'That is why the ratio is the number to carry: it is unitless and it says the same thing whichever currency the report happens to use.'),
  ('gaswell', 'beginner', 'final', null, 11, 'recommendCorrelation used to print the word wellhead for whatever station it was given. What is that word now?', '["A fixed label, since the function is only ever called with a wellhead pressure and the limit of 1000.0 psia was fitted at surface.", "An argument the caller supplies, which is an admission that the pressure need not be a wellhead one.", "A field on the returned object rather than a word in the sentence, so a reader can compare it against the station the pressure was read at.", "Removed, because the sentence no longer names a station at all."]'::jsonb, 1, 'The function takes one pressure and cannot see where it came from, so which station to hand it is the question it cannot answer.'),
  ('gaswell', 'beginner', 'final', null, 12, 'Which output field records how much of a critical rate came from the droplet balance and how much from the adjustment?', '["The adjustment field, which carries 1.2000 or 1.0000 beside the rate so the two contributions can be separated by a reader who wants them.", "The correlation field, which names turner or coleman and therefore states the multiplier that was applied to that row.", "The constant field, which holds 1.5935346111 for the balance and the adjustment separately alongside it.", "There is none."]'::jsonb, 3, 'The twenty percent is invisible downstream, so 1614.343188395 Mscf/d and 1345.285990329 Mscf/d look equally like measurements by the time they reach a report.'),
  ('gaswell', 'beginner', 'final', null, 13, 'The published plunger case sums 120.0000000000, 88.3320000000, 16.2440440692, 1.2821115429 and 0.0000000000 psi. Which of those does a wrong slug length move?', '["The 120.0000000000 psi line pressure, since a longer slug arrives at the surface against a higher pressure than a shorter one.", "The 1.2821115429 psi plunger weight, spread over the slug.", "The 88.3320000000 psi hydrostatic, and the gas column standing above the slug with it.", "Only the hydrostatic, because the gas column is carried at the line pressure and the line pressure is an input."]'::jsonb, 2, 'The five terms sum to 225.8581556122 psia, and the column of gas runs from the line down to the top of the slug, so its length moves when the slug does.'),
  ('gaswell', 'beginner', 'final', null, 14, 'An empty traverse and an unknown correlation name are the only two calls loadingProfile refuses. What does that say about everything else it accepts?', '["It scores whatever stations it is handed, having no way to check that they belong to one well on one day.", "It validates the traverse against the diameter carried on each station and refuses a list whose bores disagree with one another.", "It accepts them because those two are the only inputs that could be typed wrongly, the rest being computed inside the module.", "It treats a short traverse as a warning and a bad name as an error."]'::jsonb, 0, 'The pressures come from somewhere else, so the answer is only as good as they are, and the stations you get out are the stations you put in.'),
  ('gaswell', 'beginner', 'final', null, 15, 'Coleman applies an adjustment of 1.0000. What follows for the number it returns?', '["Coleman returns the terminal velocity of a smaller droplet, since its dataset was cut on low pressure wells where break-up happens sooner.", "The Coleman critical velocity is the terminal velocity of the droplet balance under another name.", "Coleman returns a velocity with no adjustment and therefore no correlation, which is why the goldens publish it as the theoretical column.", "Coleman and the balance agree only below the limit of 1000.0 psia."]'::jsonb, 1, 'It holds on every one of the twelve published rows, so a report showing a Coleman velocity and a terminal velocity as two results is printing one result twice.'),
  ('gaswell', 'beginner', 'final', null, 16, 'A report quotes 5.2642779885 ft/s as the velocity in the tubing at a published station. What is it actually?', '["The velocity of the gas at that station, which is what the balance solves for once the droplet diameter has cancelled out of it.", "The velocity of the droplet, which rises at the difference between the gas velocity and the terminal velocity of the balance.", "An average velocity across the flow area, against which the centreline value would read higher.", "A requirement, and nothing is travelling at it."]'::jsonb, 3, 'It is the velocity the gas would have to reach for a droplet to stop falling, and the actual velocity is a separate calculation needing the flow rate.'),
  ('gaswell', 'beginner', 'final', null, 17, 'What does a station reading know about depth?', '["The depth arrives with the traverse, which is why a station carries a pressure and a temperature that could only occur at one place in a string.", "It knows the depth through the pressure and a gradient.", "Nothing, since there is no length and no gradient anywhere in it.", "It knows only whether the station is above or below the point where the correlation limit of 1000.0 psia is crossed."]'::jsonb, 2, 'The answer is exact and it is exact about one point in a pipe, so the sentence a reading supports names the station and not the well.'),
  ('gaswell', 'beginner', 'final', null, 18, 'A misspelled fluid id reaches the module. What does it return, and which way does the error run?', '["A valid brine answer at 60.0 dyne/cm and 67.0 lbm/ft3, in the direction that calls healthy wells loaded.", "An error, since the fluid id is checked against the two published fluids in the same way as a correlation name.", "A condensate answer at 20.0 dyne/cm and 45.0 lbm/ft3, which is the safer of the two defaults and the reason the fallback survives.", "A velocity with ok = false attached to the fluid it could not place."]'::jsonb, 0, 'Water is the harsher of the two fluids the module publishes, so the failure flags healthy wells as loaded rather than the reverse, which is why it can survive for years.'),
  ('gaswell', 'beginner', 'final', null, 19, 'A condensate well flows at 1200.0 Mscf/d and its critical rate is worked out from water properties by habit. What follows?', '["Nothing, because the two fluids differ in the terminal velocity and the verdict is taken on the rate.", "It is called loaded when it is not, since condensate at that station needs 1031.930477998 Mscf/d and water needs 1509.356272243 Mscf/d.", "It is called healthy when it is not, since water is the lighter droplet of the two and therefore the easier requirement to clear.", "The verdict holds, since the ratio of 1.4626530609 between the two fluids is a constant that cancels out of a comparison."]'::jsonb, 1, 'A work order for a velocity string or a plunger follows on a well that does not need one, and the reading that produced it looks entirely sound.'),
  ('gaswell', 'beginner', 'final', null, 20, 'Sixteen times the interfacial tension doubles the terminal velocity and four times the gas density halves it. Which of the two is worth a day''s work?', '["The tension, because it is the one property that can be improved by treating the well and the density cannot be changed at all.", "Neither, since both enter through the same droplet constant of 1.5935346111 and the constant is what the answer is sensitive to.", "The tension, since a factor of sixteen is available in it across the fluids a well produces while a fourfold density change is not.", "The station that supplied the gas density."]'::jsonb, 3, 'A quarter power is a flat thing and no gas well produces a liquid that varies by anything close to sixteen, while the gas density carries the minus one half and is measured.'),
  ('gaswell', 'beginner', 'final', null, 21, 'Both 2.5605819862 ft/s rows in the published sweep carry different inputs. What are they showing?', '["That the tension and the density difference enter at the same power, so a sixty against one swap between them changes nothing.", "That the balance is insensitive to both groups over that range, which is why the two ends of the sweep return one velocity.", "That a density difference of 1.0 lbm/ft3 is below the resolution of the solve and is clamped to the tension term.", "That the two rows share a gas density of 3.0 lbm/ft3, which is the only term that matters."]'::jsonb, 0, 'Sigma 1.0 with a difference of 60.0 and sigma 60.0 with a difference of 1.0 both return 2.5605819862 ft/s, and both groups carry a quarter power.'),
  ('gaswell', 'beginner', 'final', null, 22, 'Turner reads 7.9039672631 ft/s where the balance itself returned 6.5866393859 ft/s. At which point in the chain did those two figures part?', '["In the droplet size, Turner breaking it up at a smaller diameter.", "In the density difference, where Turner carries the buoyancy term and Coleman drops it as negligible at low pressure.", "In the last step, after the drag coefficient, the Weber number, the tension, both densities and the constant had all agreed.", "In the gas density, which Turner evaluates at the station and Coleman at standard conditions."]'::jsonb, 2, 'A lesson that says the two correlations model different droplets, or different break-up, or different drag, is wrong: one of them multiplies.'),
  ('gaswell', 'beginner', 'final', null, 23, 'Which figure would you have to defend if a well were shut in on the strength of it?', '["The droplet constant of 1.5935346111, which the engine derives rather than storing and which the gate checks it produces.", "The 416.025765846 Mscf/d that separates the two published answers at one station.", "The rate constant of 3054.38693878, since it is the number that turns a velocity into the rate the shut-in decision is read against.", "The gas density, which is the only term in the balance a station measures."]'::jsonb, 1, 'A well flowing between the two answers is healthy under one published correlation and loaded under the other, on the same day and the same gauge reading.'),
  ('gaswell', 'beginner', 'final', null, 24, 'Nine steps run from fixing the station to taking the ratio. What is the value of working them in that order?', '["A graded answer that is wrong is wrong at a step you can name.", "The order is what makes the arithmetic reproducible, since the module evaluates its own terms in that sequence internally.", "It keeps the correlation out of the calculation until the pressure is known, which is the only ordering constraint the chain carries.", "It puts the two refusals before the rate."]'::jsonb, 0, 'Every step is checkable on its own, and a disagreement with the panel is at a step rather than in the answer.'),
  ('gaswell', 'beginner', 'final', null, 25, 'A ratio of 0.9997870547 is rounded to two decimals before anybody reads it. What has been lost?', '["The margin, since two decimals still carry the flag and only the distance from one has gone, which is what the loaded field was for.", "Nothing important, because a ratio that close to one is inside the resolution of the pressure and temperature it was built from anyway.", "The comparison against the critical rate of 1614.343766935 Mscf/d, which cannot be reconstructed from a rounded ratio.", "The verdict, which is strict and reads loaded there."]'::jsonb, 3, 'Everything at or below the critical rate is a well that cannot lift its droplets at that station, and nothing in the balance says how far under one is close enough.'),
  ('gaswell', 'beginner', 'final', null, 26, 'An actual velocity of 7.9022869823 ft/s is written into a report. What is that figure made of?', '["A measured velocity, since the panel reads it from the flowing well at the station the pressure and the temperature came from.", "A velocity the droplet balance solved for, which is why it can be set against the critical velocity of the same station at all.", "A rate somebody supplied, divided by a geometry somebody typed, at a station somebody chose.", "The gas velocity at standard conditions."]'::jsonb, 2, 'Nothing here measures a velocity, and the same area and the same p over z T carried the critical velocity the other way.'),
  ('gaswell', 'beginner', 'final', null, 27, 'A constant of 3054.38693878 turns a velocity through an area into a daily standard volume. Which gas property is inside it?', '["The gas gravity of 0.65 and a compressibility of 0.90, which is why the published rows all share one gravity and one z.", "Nothing, since it rebuilds as 86400 times 519.67 over 14.70 times 1000.", "The molecular weight of air at 28.9647 lbm/lbmol, which is the only gas property standard conditions need.", "The gas constant of 10.7316 psia ft3 per lbmol degR."]'::jsonb, 1, 'It is standard conditions and seconds in a day, which is why divided by 1000 it reads 3.054387, the 3.06 the texts print for MMscf/d.'),
  ('gaswell', 'beginner', 'final', null, 28, '12.0 ft/s through 2.441 in at 900.0 psia, 580.0 degR and z 0.9 gives 2053.715375332 Mscf/d, and that rate gives back 12.000000000000 ft/s. What has been established?', '["That a rate and a velocity are one statement in two currencies, provided both conversions use the same p, z and T.", "That the conversion is exact for that station and approximate elsewhere, the closure of -1.7764e-15 ft/s being the error at 900.0 psia.", "That the critical velocity and the actual velocity share one route.", "That the flow area of 0.0324984725 ft2 was entered correctly, since a wrong area would not close."]'::jsonb, 0, 'The round trip closes to -1.7764e-15 ft/s, and the condition on it is the whole point: a surface rate and a downhole velocity are not that pair.'),
  ('gaswell', 'beginner', 'final', null, 29, 'A surface gas rate is divided by a downhole area at downhole conditions to get an actual velocity. What has been produced?', '["A conservative reading, because a surface rate is smaller than the rate at depth and the velocity is therefore understated.", "A valid velocity, since a rate at standard conditions is the same standard volume wherever the conversion is performed on it.", "An error the module reports, having checked the pressure the rate was metered at against the one it was converted at.", "A comparison between two different wells."]'::jsonb, 3, 'The arithmetic runs, no warning appears, and the actual velocity has to be computed where the critical velocity was computed for the ratio to mean anything.'),
  ('gaswell', 'beginner', 'final', null, 30, 'What does the drag coefficient of 0.4400 describe?', '["A droplet fitted to the data behind the 1.200000.", "A deforming droplet at the critical Weber number of 30.0000, which is why the two constants are quoted together.", "A rigid sphere in the Newton regime, which is a different object from a droplet.", "A sphere at low Reynolds number, where the drag is linear in the velocity."]'::jsonb, 2, 'A real droplet deforms, flattens and sheds, and nothing here knows that, so the value is describing a different object rather than being wrong.'),
  ('gaswell', 'beginner', 'final', null, 31, 'Why does the leading constant move so little across drag coefficients from 0.22 to 1.10?', '["The constant is dominated by the Weber number of 30.0000, and the drag coefficient enters only through the frontal area of the droplet.", "The relationship is a fourth root, so the whole span moves it from 1.8950426975 to 1.2672914315.", "The engine clamps the coefficient to the shipped 0.44.", "Drag appears on both sides of the balance and largely cancels."]'::jsonb, 1, 'That is why the balance tolerates a drag coefficient nobody can defend to better than a factor of two, and why the argument about it is not where the money is.'),
  ('gaswell', 'beginner', 'final', null, 32, 'Reading 2500.0 psia and 620.0 degR, eleven quantities are written out down to the critical rate. How many of them were measured?', '["Two, with two more supplied for the gas, two chosen with the fluid and five computed.", "Six, the station numbers and the fluid properties.", "Four, since the pressure, the temperature, z and the gas gravity all describe the gas at the station the gauge sits on.", "Eleven, because a computed value inherits the standing of the numbers behind it."]'::jsonb, 0, 'The five computed values inherit everything that was assumed and print with the same run of decimals as the pressure that was actually read.'),
  ('gaswell', 'beginner', 'final', null, 33, 'gasWellLoading carries 28.9647 lbm/lbmol and gasProperties carries 28.9625. What is the size of that seam at a published station?', '["0.002200 lbm/ft3, which is the difference between the two molecular weights carried straight through into the density.", "75.9603 lbm/ft3, the two constants being 75.9603 parts per million apart and the density scaling linearly with them.", "Nothing measurable, since the two modules use the same gas constant of 10.7316 psia ft3 per lbmol degR.", "5.970042e-4 lbm/ft3, or 7.595452e-5 of the density."]'::jsonb, 3, 'At 2500.0 psia and 620.0 degR the two routes return 7.8600213238 and 7.8594243196 lbm/ft3, and the velocity moves by 4.050320e-5 of itself.'),
  ('gaswell', 'beginner', 'final', null, 34, 'Why does that density gap move the Turner velocity by a smaller fraction than it moves the density?', '["The velocity is adjusted by 1.200000 afterwards, which divides the fractional change by the same factor.", "The two routes agree on the density difference itself.", "The velocity carries the inverse square root, so a little over half the fractional density change reaches it.", "The velocity is rounded to ten decimal places, which absorbs a change of 5.970042e-4 lbm/ft3."]'::jsonb, 2, 'The ratio of the two fractions is 0.53325597, which is the one half from the inverse square root plus the buoyancy term inside the density difference.'),
  ('gaswell', 'beginner', 'final', null, 35, 'A well is called healthy on Monday and loaded on Tuesday from the same gauge reading, the same tubing and the same water. What could have changed?', '["The z that was supplied, which cannot move a verdict because it divides out between the density and the conversion to standard conditions.", "The correlation the report was run under, which multiplies every critical rate by 1.200000 or by 1.000000.", "The rate constant, at 3054.38693878 Mscf/d against 3.06.", "The gas gravity, which is a property of the gas and not of the report."]'::jsonb, 1, 'A well flowing between the two published answers at one station sits on either side of the verdict depending on which name was filed.'),
  ('gaswell', 'beginner', 'final', null, 36, 'The wellhead pressure of a well reads 999.96 psia and the printed reason names 1000.0 psia. Which correlation did the branch return?', '["coleman, because the comparison is strict and 999.96 psia is below the limit even though it renders as it.", "turner, since the pressure printed at the limit is the pressure the branch compared, and at 1000.0 psia the answer is turner.", "coleman, the limit being a soft threshold at a rounding.", "Neither, since a pressure inside the print resolution of the limit is returned as indeterminate."]'::jsonb, 0, 'Anything inside 0.05 psi of the limit still renders as the limit, so the sentence cannot be verified from itself: 999.96 psia is 0.0400 psi away.'),
  ('gaswell', 'beginner', 'final', null, 37, 'Which functions take a pressure from any station at all and answer without comment?', '["Only recommendCorrelation, since the sizing checks the pressure it was handed against the traverse that produced its candidate list.", "Neither of them, because both refuse a station they were given no depth for, in the same way an empty traverse is refused outright.", "Only the sizing, since the recommendation names the wellhead in its own sentence and rejects a pressure from anywhere else.", "recommendCorrelation and sizeTubingForRate."]'::jsonb, 3, 'One returns guidance and cannot see which station the pressure came from, and the other has no opinion about which station supplied its pressure, temperature and z.'),
  ('gaswell', 'beginner', 'final', null, 38, 'What would it take to turn this station reads 2341.162863678 Mscf/d into the well needs 2341.162863678 Mscf/d?', '["An inflow relation, which these modules would then run at the station to see whether the well can supply that rate.", "Every other point in the string, each with its own pressure, temperature and diameter.", "A measured liquid rate, since a critical rate is a threshold for the liquid the well makes rather than for the gas.", "Nothing, because the shoe and the wellhead of one well share a fluid and a string."]'::jsonb, 1, 'Each of those points would return a different number from the same code, and a single station has no mechanism by which it could know what any other one reads.'),
  ('gaswell', 'beginner', 'final', null, 39, 'A study spends a day refining an interfacial tension of 60.0 dyne/cm. What would the same day have bought spent on the station?', '["The same, since the tension and the gas density both enter the terminal velocity and neither is more fundamental than the other.", "Less, a tension belonging to the liquid the well makes.", "More, because the gas density carries the minus one half and it is the only term of the three that is measured.", "Nothing either way, since both are inputs and neither is a function of anything these modules know."]'::jsonb, 2, 'An error of a factor of two in tension is an error of far less than that in velocity, and it is smaller than reading the temperature at the wrong hour.'),
  ('gaswell', 'beginner', 'final', null, 40, 'A critical rate is recomputed after a well''s production falls and comes back lower than last month. What has happened?', '["The critical rate followed the well down, which is the behaviour that makes it a useful trending figure on a declining string.", "The gas thinned as the wellhead pressure fell, so the critical velocity fell with it and carried the rate down.", "The rate sweep was rerun at the new production figure, and the critical rate is evaluated at whatever rate it is handed.", "A station number moved."]'::jsonb, 3, 'Walked across a sweep from 400.0 to 2600.0 Mscf/d one station reads 1614.343766935 Mscf/d at every point, so a critical rate cannot follow a well down out of politeness.'),
  ('gaswell', 'beginner', 'final', null, 41, 'The engine derives 1.5935346111 where the oracle publishes 1.5935357894. Why does the gate accept it?', '["The two agree at the precision the goldens are cut to.", "The relative difference is 7.3947e-7, and what is being checked is that the engine produces the number rather than storing it.", "The gate loosens that assertion for the slug hydrostatic.", "The oracle value is the reference and the engine value is a fitted approximation to it within a stated tolerance."]'::jsonb, 1, 'One implementation is in SI with no gc anywhere and the other in field units carrying gc and 6.852177e-5 explicitly, and agreement across that is what the check is worth.'),
  ('gaswell', 'beginner', 'final', null, 42, 'Which single output of the Associate chain would you put in front of a decision, and what are the others?', '["The critical rate, since it is the figure a production report can be read against directly and the ratio is derived from it.", "The loaded flag, a decision needing a verdict rather than a number.", "The ratio, with the density, the velocities, the area and the rates as the supporting work behind it.", "The terminal velocity, which is the one quantity the balance itself produces and the rest are conversions of it."]'::jsonb, 2, 'A rate carries no verdict and a velocity carries no verdict, and the ratio is unitless and strict: 0.9997870547 reads loaded.');
