-- ============================================================================
-- DR6 EXPERT DEEP SEED: Casing & Tubing Design, advanced tier.
--
-- Six modules, 26 lessons, 132 questions (15 per module bank plus a 42
-- question final exam). The structure row is GENERATED from the tier's
-- manifest.json rather than hand typed.
--
-- What this tier owns: the tubing string, which is a casing string that is
-- ALLOWED TO MOVE. It is not cemented, so it can change length, load its
-- packer and buckle, and a cemented string can do none of those. Only three
-- things change over the life of a completion, and every force here is a
-- CHANGE in one of them from the packer setting condition. The Lubinski and
-- Hammerlindl planning forms give piston, ballooning and thermal; three length
-- terms; a stroke verdict; and the Dawson-Paslay buckling limits.
--
-- THE FINDING, AND m05 IS BUILT ON IT. The three published operating cases
-- each hit a DIFFERENT limit. Production heating buckles HELICALLY and is
-- comfortably inside its stroke, and it has the BEST packer safety factor of
-- the three at 5.416989018921467. Injection cooling does not buckle at all and
-- strokes out. Stimulation has the WORST packer safety factor at
-- 1.448941812184961 and does not buckle either. There is no design case,
-- because buckling responds to the SIGN of the force through a maximum against
-- zero while the packer and stroke checks respond to its MAGNITUDE, and only
-- one of the three cases is in compression. That is the same shape as the
-- Professional tier's result, where a case named after burst was governed by
-- the triaxial check.
--
-- TWO EXACT RESULTS THE TIER TURNS ON. The helical buckling limit is
-- 1.8284271247461903 times the sinusoidal one, which is two root two less one,
-- on every string in every hole at every inclination, because both limits are
-- the same square root times a different pure constant. And the STROKE WINDOW
-- is exactly twice the stroke over the expansion coefficient times the length,
-- which is 100 degrees on this completion, whatever the pressures do: the
-- total length is a straight line in temperature whose slope contains no
-- pressure, so the pressures slide the window and never widen it. The engine's
-- bisected edges at minus 34.82534863819683 and 65.17465136180317 agree with
-- the closed form to a part in ten million.
--
-- A THIRD RESULT, IN m04. Neither the thermal FORCE nor either buckling limit
-- contains a length. A 500 m string and a 5000 m string give the same thermal
-- force for the same mean temperature change, and the same buckling limits in
-- the same hole. The thermal LENGTH change does contain the length, and
-- holding that pair together is the point of the module.
--
-- WHAT THIS TIER TEACHES AND CERTIFIES NOWHERE: the buckling length term, the
-- annular pressure buildup coupling, seal and buckled-string friction, the
-- erosional velocity limit as a design criterion, connection sealing, casing
-- wear and fatigue. 20260830_dr6_casingtubing_go_live.sql asserts it.
--
-- Numeric sweep and tier-leakage sweep as for the tiers below: 0 unresolved
-- literals, 0 downward leaks, 0 same-tier answer prints.
--
-- Answer keys live only here and in academy_quiz_questions, which has no
-- client SELECT policy.
-- ============================================================================

insert into public.academy_course_structures
    (app_slug, tier, structure, content_version)
values ('casingtubing', 'advanced', '{"modules":[{"key":"m01-tubing-is-a-different-problem","title":"Tubing Is a Different Problem","lesson_keys":["l01-cemented-and-not-cemented","l02-three-areas","l03-what-changes-and-from-what","l04-the-sign-convention"]},{"key":"m02-the-three-forces","title":"The Three Forces","lesson_keys":["l01-piston","l02-ballooning","l03-thermal","l04-why-thermal-usually-wins","l05-adding-them-up-at-the-packer"]},{"key":"m03-length-and-what-holds-it","title":"Length, and What Holds It","lesson_keys":["l01-force-and-length-are-two-answers","l02-the-three-length-terms","l03-the-stroke-window-is-a-constant","l04-free-anchored-and-limited-motion","l05-reading-a-stroke-verdict"]},{"key":"m04-buckling","title":"Buckling","lesson_keys":["l01-a-string-in-compression-in-a-hole","l02-sinusoidal-and-helical","l03-the-radial-clearance","l04-where-this-string-starts-to-buckle","l05-what-buckling-costs"]},{"key":"m05-the-envelope-and-its-edges","title":"The Envelope, and Its Edges","lesson_keys":["l01-three-cases-three-limits","l02-the-erosional-velocity-limit","l03-what-the-planning-forms-leave-out","l04-what-this-course-will-not-certify"]},{"key":"m06-the-expert-reading","title":"The Expert Reading","lesson_keys":["l01-the-story-so-far","l02-working-the-capstone","l03-onward"]}]}'::jsonb, 1)
on conflict (app_slug, tier) do update
  set structure = excluded.structure,
      content_version = excluded.content_version,
      active = true,
      updated_at = now();

delete from public.academy_quiz_questions
 where app_slug = 'casingtubing' and tier = 'advanced';

insert into public.academy_quiz_questions
    (app_slug, tier, scope, module_key, ord, prompt, options, answer_index, explanation)
values
  ('casingtubing', 'advanced', 'module', 'm01-tubing-is-a-different-problem', 1, 'What is the one structural fact that separates tubing from casing?', '["Tubing is smaller and therefore has a lower rating.", "Tubing is not cemented, so it can change length, load its packer and buckle, and cemented pipe can do none of those.", "Tubing carries produced fluid rather than drilling fluid, so its internal pressure is set by the reservoir rather than the pump.", "Tubing is run after the well is completed, so every load it sees is a production load rather than a drilling or test one."]'::jsonb, 1, 'Everything different about the tubing problem follows from that one permission.'),
  ('casingtubing', 'advanced', 'module', 'm01-tubing-is-a-different-problem', 2, 'Which three inputs change over the life of a completion?', '["The mud weight, the hole angle and the packer setting.", "The bore pressure, the flow rate and the produced water cut, all of which act on the tubing through the fluid it carries.", "The pressure inside the tubing, the pressure in the annulus outside it, and the temperature the string is operating at.", "The pressure in the bore, the pressure in the annulus and the temperature of the steel."]'::jsonb, 3, 'Every force in the tier is a change in one of those three from the state at which the packer was set.'),
  ('casingtubing', 'advanced', 'module', 'm01-tubing-is-a-different-problem', 3, 'Why does the tubing routine take pressure changes rather than pressures?', '["Because the forces are all measured from the packer setting condition, at which every one of them is zero by definition.", "Because absolute pressures would require a depth reference.", "Because the piston and ballooning terms are linear, so the absolute values cancel and only the differences survive the algebra.", "Because the annulus pressure is not known absolutely, only as a change read at surface from the moment of setting."]'::jsonb, 0, 'A string that has never been produced has zero force from all three mechanisms whatever the absolute pressures are.'),
  ('casingtubing', 'advanced', 'module', 'm01-tubing-is-a-different-problem', 4, 'Which four areas does the tubing calculation use?', '["The bore, the outside and the annular flow area.", "The bore area, the outside area and the two annular differences between each of them and the packer seal bore area.", "The bore area, the outside area, the packer seal bore area and the steel cross-section.", "The steel area, the seal bore area and the two projected areas of the couplings at the top and bottom of the string."]'::jsonb, 2, 'The pressures never act on the steel section, and the thermal force uses nothing else.'),
  ('casingtubing', 'advanced', 'module', 'm01-tubing-is-a-different-problem', 5, 'Why is the seal bore area the largest of the three pressure areas?', '["Because it includes the coupling outside diameter.", "Because the packer bore is larger than the tubing that seals into it, so the seals sit on a mandrel passing through it.", "Because the seal bore is measured on the outside of the seal assembly, which is thicker than the tubing body above it.", "Because the packer is set in casing rather than in tubing, so its bore is scaled to the casing size rather than the tubing one."]'::jsonb, 1, 'That ordering decides the sign of the piston force, and reversing it reverses the force.'),
  ('casingtubing', 'advanced', 'module', 'm01-tubing-is-a-different-problem', 6, 'What does the difference between the seal bore area and the bore area represent?', '["The area over which the bore pressure acts upward, trying to push the tubing out of the packer.", "The annular flow area between tubing and casing.", "The area of steel at the bottom of the tubing that transmits the bore pressure directly into the body of the packer itself.", "The area over which the annulus pressure acts, since the annulus is bounded by the seal bore on the inside of the packer."]'::jsonb, 0, 'On this string it is 0.0035712418834005005 square metres, nearly twice the annulus one.'),
  ('casingtubing', 'advanced', 'module', 'm01-tubing-is-a-different-problem', 7, 'The seal bore is a property of what?', '["The tubing, since the seals are run on the tubing string.", "The casing, since the packer is set in casing and its seal bore is sized to a fixed fraction of the casing inside diameter.", "The packer rather than the tubing, which makes a smaller seal bore one of the few free design levers in a completion.", "The packer, not the tubing, so changing the packer changes every piston force with the tubing untouched."]'::jsonb, 3, 'A smaller seal bore reduces the piston force at no cost in tubing.'),
  ('casingtubing', 'advanced', 'module', 'm01-tubing-is-a-different-problem', 8, 'How does the engine get the mean temperature change when none is supplied?', '["It uses the bottomhole temperature change directly.", "It solves a transient conduction problem along the string and integrates the resulting profile over the length of the tubing.", "It takes the temperature gradient times the length, divided by two, which is the mean of a linear profile change.", "It takes the surface temperature and the gradient and evaluates the profile at the packer, which is the deepest point."]'::jsonb, 2, 'The mean is exact for the LENGTH given a linear profile, because the integral of a linear function is its length times its mean.'),
  ('casingtubing', 'advanced', 'module', 'm01-tubing-is-a-different-problem', 9, 'Which of the three published cases has the largest bore pressure change?', '["Production heating, at 10000000 Pa on the bore.", "Stimulation, at 45000000 Pa, with 5000000 Pa held on the annulus at the same time.", "Injection cooling, at 20000000 Pa, since injection requires more pump pressure than any other routine operation on a well.", "They are equal, because all three are run at the same treating pressure and differ only in the temperature change applied."]'::jsonb, 1, 'It is also the case with the largest temperature change, at minus 50 degrees.'),
  ('casingtubing', 'advanced', 'module', 'm01-tubing-is-a-different-problem', 10, 'Why does injection cool the string while production heats it?', '["Because the injected water arrives cold from surface and the produced fluid arrives hot from the reservoir.", "Because injection is performed at a higher rate.", "Because the injected fluid expands as it is pumped down and the Joule Thomson effect cools the steel around it accordingly.", "Because the annulus fluid is displaced upward during injection, carrying heat away from the tubing at a higher rate."]'::jsonb, 0, 'The sign of the temperature change is the difference between the two cases, and it is the term that dominates.'),
  ('casingtubing', 'advanced', 'module', 'm01-tubing-is-a-different-problem', 11, 'What is the sign convention for the total force at the packer?', '["Positive is compression, matching the buckling check.", "Positive is upward, which coincides with tension for the piston term and with compression for the thermal one.", "Positive is tension added to the packer, so a positive number means the string is pulling up and a negative one that it pushes.", "Positive is tension and negative is compression, and the engine says so in one line."]'::jsonb, 3, 'Everything downstream depends on it, and getting it wrong inverts every conclusion in the tier.'),
  ('casingtubing', 'advanced', 'module', 'm01-tubing-is-a-different-problem', 12, 'Which of the three forces carries an explicit minus sign in its formula?', '["The piston one, because the bore pressure pushes upward.", "The ballooning one, because internal pressure swells the pipe and a swollen pipe is shorter than the one it started as.", "The thermal one, because heating a restrained string puts it into compression.", "None of them, because the sign is applied when the three are summed rather than being carried in the individual formulas."]'::jsonb, 2, 'It is minus E times A times alpha times the temperature change.'),
  ('casingtubing', 'advanced', 'module', 'm01-tubing-is-a-different-problem', 13, 'Heating a tubing string does what to the packer?', '["Pulls on it, because hot steel is stronger in tension.", "Pushes on it, because the string wants to grow and the packer will not let it.", "Neither, because a free string simply lengthens and the packer sees no force at all until the seal assembly reaches its stop.", "Pushes on it at the top of the string and pulls at the bottom, because the temperature change is not uniform along it."]'::jsonb, 1, 'It is backwards from the instinct that hot things push harder on everything.'),
  ('casingtubing', 'advanced', 'module', 'm01-tubing-is-a-different-problem', 14, 'Of the three published cases, which is the only one that ends in compression?', '["Production heating, and it is the only one with a positive temperature change.", "Stimulation, which has the largest forces overall.", "Injection cooling, because the cold string contracts and drives the seal assembly down into the packer bore against its stop.", "None of them, since all three apply a bore pressure and the pressure terms are always positive on this geometry."]'::jsonb, 0, 'The other two are cooling cases and both end in tension.'),
  ('casingtubing', 'advanced', 'module', 'm01-tubing-is-a-different-problem', 15, 'Why do the force and the length change carry opposite signs for one case?', '["Because the length change is reported as an absolute value.", "Because the length changes are computed from the pressure terms only, while the force also includes the thermal contribution.", "Because a compressive force at the packer goes with an elongation that was prevented.", "Because the length is measured from the packer upward and the force is measured from the wellhead downward."]'::jsonb, 2, 'Reading the two columns and expecting them to agree in sign is the commonest error in the tier.'),
  ('casingtubing', 'advanced', 'module', 'm02-the-three-forces', 1, 'The piston force is which combination?', '["The bore pressure change times the steel cross-section.", "The bore pressure change on the seal bore less bore area, less the annulus change on the seal bore less outside area.", "The difference of the two pressure changes, acting on the seal bore area, since that is the only area the packer presents.", "The bore pressure change on the bore area less the annulus pressure change on the outside area, both taken at the packer."]'::jsonb, 1, 'Two terms, opposite signs, each a pressure change times an area difference.'),
  ('casingtubing', 'advanced', 'module', 'm02-the-three-forces', 2, 'Why does neither pressure act on the seal bore area itself?', '["Because the seal bore is filled with the same fluid.", "Because the seal bore area is the sum of the other two, so its contributions cancel identically in the force balance.", "Because the seals transmit it to the packer body, so the tubing only feels the pressure acting on the projected annular areas.", "Because the seals transmit that part of the load into the packer rather than into the tubing above them."]'::jsonb, 3, 'The control volume is drawn around the bottom of the tubing where it enters the packer.'),
  ('casingtubing', 'advanced', 'module', 'm02-the-three-forces', 3, 'On this geometry, a pascal of bore pressure is worth how much against a pascal of annulus pressure in the piston term?', '["About 1.879 times as much, because the bore area difference is that much larger than the annulus one.", "Exactly the same, since the two act on the same bore.", "About half as much, because the annulus area difference is the larger of the two on a normal packer seal bore geometry.", "It depends on the temperature, because the areas change with the thermal strain in the steel at operating conditions."]'::jsonb, 0, 'And they act in opposite directions, so annulus pressure cancels part of the bore pressure''s effect.'),
  ('casingtubing', 'advanced', 'module', 'm02-the-three-forces', 4, 'Holding 5000000 Pa on the annulus during a stimulation removes how much piston force?', '["Nothing, since the annulus is outside the seal bore.", "About 18000 N, since the annulus pressure acts on the full outside area of the tubing rather than on a difference of areas.", "9500.765233078084 N, which is the annulus area difference times that pressure.", "The same amount the bore pressure adds, because the two areas are equal and the effect is a balanced pressure test."]'::jsonb, 2, 'It also reduces the ballooning term and supports the tubing against burst, which is why it is a deliberate tool.'),
  ('casingtubing', 'advanced', 'module', 'm02-the-three-forces', 5, 'Which quantity does the piston force NOT depend on?', '["The seal bore diameter of the packer.", "The length of the string, because it is an end effect at the packer.", "The inside diameter of the tubing, since the piston term is computed from the seal bore and the outside diameter alone.", "The pressure change in the annulus, which enters only the ballooning term through the outside area of the tubing."]'::jsonb, 1, 'It would be the same on a 500 m string, which is not true of any of the length changes.'),
  ('casingtubing', 'advanced', 'module', 'm02-the-three-forces', 6, 'Ballooning is which effect?', '["The Poisson effect: internal pressure swells the pipe radially, and a swollen pipe pays for it with some of its length.", "Thermal expansion of the fluid inside the tubing.", "The pressure acting on the projected area of the couplings, which are larger in diameter than the pipe body between them.", "The radial growth of the annulus fluid, which presses on the outside of the tubing and shortens it by the same mechanism."]'::jsonb, 0, 'Steel conserves volume as it deforms elastically, near enough.'),
  ('casingtubing', 'advanced', 'module', 'm02-the-three-forces', 7, 'What is the 0.6 in the ballooning formula?', '["The fraction of the bore area that is effective.", "An empirical calibration factor from Lubinski''s original measurements on tubing strings in producing wells in the 1960s.", "Twice the Poisson ratio, taken as 0.3 for steel, which makes the ballooning term half again the size of a pure Poisson strain.", "Twice the Poisson ratio of steel at 0.3, and the engine names it as a constant rather than burying it."]'::jsonb, 3, 'It appears in the length change formula as two times 0.3 as well, which is the same number written differently.'),
  ('casingtubing', 'advanced', 'module', 'm02-the-three-forces', 8, 'Why is annulus pressure more effective against ballooning than against piston?', '["Because the ballooning term has no seal bore in it.", "Because the Poisson ratio applies only to the internal pressure, so the annulus term enters the ballooning force undamped.", "Because it acts on the full outside area there rather than on the difference between the outside and the seal bore.", "Because the outside area exceeds the bore area, and the ballooning term is the difference between the two acting together."]'::jsonb, 2, 'The cancellation ratios are 0.7307807346938777 for ballooning against 0.5320706657949223 for piston.'),
  ('casingtubing', 'advanced', 'module', 'm02-the-three-forces', 9, 'The thermal force is minus E times A times alpha times the temperature change. What is missing from it?', '["The Poisson ratio, which the other two terms carry.", "The length, so a 500 m string and a 5000 m string give the same force for the same mean change.", "The pressure, since the thermal term is independent of the pressures acting inside and outside the string at the time.", "The seal bore area, since the thermal force acts on the steel section rather than on any of the pressure areas."]'::jsonb, 1, 'The thermal LENGTH change does contain the length, and that is the pair worth holding together.'),
  ('casingtubing', 'advanced', 'module', 'm02-the-three-forces', 10, 'On the published string, how much thermal force does one degree produce?', '["4146.974057365369 N, which is E times the steel area times the expansion coefficient.", "About 41 kN, which is why the term dominates.", "It depends on the length, since a longer string develops more thermal strain and therefore more force at the packer.", "About 2.48 MPa, which is the product of the modulus and the expansion coefficient before the area is applied."]'::jsonb, 0, 'Multiply by 45 and you get the production heating case''s 186613.83258144156 N of compression.'),
  ('casingtubing', 'advanced', 'module', 'm02-the-three-forces', 11, 'Why does the temperature term usually dominate?', '["Because temperature changes are larger than pressure ones.", "Because the steel area is larger than the bore area, so the same stress produces a larger force through the thermal route.", "Because the pressure terms partly cancel each other while the thermal term has nothing acting against it in the sum.", "Because the pressures act on large areas but are only tens of megapascals, while the thermal term is multiplied by the modulus."]'::jsonb, 3, 'The product of the modulus and the expansion coefficient is 2481600 Pa per degree of axial stress.'),
  ('casingtubing', 'advanced', 'module', 'm02-the-three-forces', 12, 'On the published string, one degree is worth how much bore pressure change?', '["About 6.6 MPa, so a 45 degree swing is unbeatable.", "658993.7232542605 Pa, which is about two thirds of a megapascal.", "About 66 kPa, since the thermal force per degree is small compared with the pressure force per pascal on these areas.", "It cannot be expressed that way, because the two act through different areas and are not commensurable quantities."]'::jsonb, 1, 'The 45 degree warm-up in the production case is therefore worth 29.654717546441724 MPa of bore pressure.'),
  ('casingtubing', 'advanced', 'module', 'm02-the-three-forces', 13, 'Name a completion in which the pressures carry more of the packer load than the heat does.', '["Never, on any tubing string of realistic dimensions.", "On a short string, because the thermal force scales with the length while the pressure terms are end effects at the packer.", "On a well produced continuously with no shut-ins, or during a large annulus pressure event with nothing on the bore.", "On a thick walled tubing, because the steel area grows faster than the bore area as the wall thickness is increased."]'::jsonb, 2, 'The delta is what matters, and a string that never changes temperature has no thermal term at all.'),
  ('casingtubing', 'advanced', 'module', 'm02-the-three-forces', 14, 'The three forces are combined how?', '["By straight addition, with no weighting and no interaction term, because all three act on the same body in the same direction.", "By taking the largest of the three in absolute value.", "By root sum of squares, since the three mechanisms are independent and their uncertainties therefore combine in quadrature.", "By adding the two pressure terms and subtracting the thermal one, which is where the minus sign in the formula is applied."]'::jsonb, 0, 'The sign convention does the rest.'),
  ('casingtubing', 'advanced', 'module', 'm02-the-three-forces', 15, 'Which two comparisons is the total force put through?', '["The pipe body yield and the connection efficiency.", "The packer rating and the stroke, since a force that exceeds the rating will also drive the seal assembly out of its bore.", "The packer rating, using its absolute value, and the buckling limits, using only the compressive part.", "The buckling limits and the erosional velocity, which together define the operating envelope for the completion."]'::jsonb, 2, 'The absolute value is deliberate: a packer has to resist both directions and a rating is usually one number for both.'),
  ('casingtubing', 'advanced', 'module', 'm03-length-and-what-holds-it', 1, 'Why does the engine report a force set and a length set rather than one answer?', '["Because some packers are rated in force and some in stroke.", "Because they answer two different questions under two different restraint conditions, and neither follows from the other.", "Because the force is needed for the packer check and the length for the buckling check, which use different sign conventions.", "Because the length is a planning approximation while the force is exact, so reporting both lets the reader judge the error."]'::jsonb, 1, 'One assumes nothing moves and the other assumes everything does.'),
  ('casingtubing', 'advanced', 'module', 'm03-length-and-what-holds-it', 2, 'What does an anchored packer do to a length change?', '["Allows it, up to the length of the polished bore.", "Halves it, because the tubing and the packer share the restraint according to their relative axial stiffnesses at the seal.", "Prevents it, which is why the reported force column is the anchored answer and the length column is the free one.", "Prevents it entirely, so the whole of it appears as a force at the packer instead."]'::jsonb, 3, 'A seal assembly in a polished bore is the opposite case and transmits essentially no axial force.'),
  ('casingtubing', 'advanced', 'module', 'm03-length-and-what-holds-it', 3, 'Why can you not derive the reported length from the reported force?', '["Because they are not two views of one restraint condition, they are two different ones.", "Because the stiffness of the string is not reported.", "Because the length changes include a buckling term that the force set omits, so the two are computed from different mechanisms.", "Because the force is measured at the packer and the length is integrated over the whole string, so the two have different bases."]'::jsonb, 0, 'A real limited motion packer lies between them and needs a seal stiffness and a friction the model does not carry.'),
  ('casingtubing', 'advanced', 'module', 'm03-length-and-what-holds-it', 4, 'Which of the three length terms contains no area and no modulus?', '["The piston one, which is Hooke''s law on a bar.", "The ballooning one, since the Poisson strain is a pure ratio and the areas cancel between the numerator and the denominator.", "The thermal one, which is the expansion coefficient times the length times the temperature change.", "None of them, because all three are elastic deformations and every elastic deformation is a stress over a modulus."]'::jsonb, 2, 'It is the only one that is exactly what a first course would give.'),
  ('casingtubing', 'advanced', 'module', 'm03-length-and-what-holds-it', 5, 'Why does the piston length change carry a sign flip against the piston force?', '["Because the length is measured from the packer upward.", "Because a piston force that pulls up on the tubing shortens the part of it below.", "Because the length changes are computed for the free string and the forces for the anchored one, which reverses every sign.", "Because Hooke''s law relates stress to strain with a negative constant when the load is applied at the lower end of a bar."]'::jsonb, 1, 'A positive piston force therefore gives a negative length change.'),
  ('casingtubing', 'advanced', 'module', 'm03-length-and-what-holds-it', 6, 'Which length term is missing from this engine?', '["The shortening due to helical buckling, because a wrapped string is shorter end to end than a straight one.", "The ballooning term, which is reported as a force only.", "The thermal term, which the engine reports as a force and derives the length from separately using the mean temperature change.", "The piston term, since an end load produces no distributed strain and therefore no length change along the string body."]'::jsonb, 0, 'It matters on exactly the one case that buckles, where the true length change is smaller than reported.'),
  ('casingtubing', 'advanced', 'module', 'm03-length-and-what-holds-it', 7, 'On a bore pressure event, which way do the two pressure length terms act?', '["They oppose each other and nearly cancel.", "Both lengthen it, because a pressurised pipe swells and a swollen pipe accommodates the extra volume by growing longer.", "Piston shortens it and ballooning lengthens it, which is why the two are reported separately rather than as a single term.", "Both shorten the string, because both piston and ballooning are positive forces on this geometry."]'::jsonb, 3, 'So pressure alone always makes the string shorter and temperature decides everything else.'),
  ('casingtubing', 'advanced', 'module', 'm03-length-and-what-holds-it', 8, 'The stroke window on this string is exactly 100 degrees wide. Where does that come from?', '["The difference between the two published temperature cases.", "The temperature range over which the packer seals are qualified, which the manufacturer specifies as a hundred degree band.", "Twice the stroke divided by the expansion coefficient times the length, which is 3 over 0.03 metres per degree.", "The bisection tolerance, since the engine searches a hundred degree bracket and reports its width when neither end is reached."]'::jsonb, 2, 'The bisected answer agrees with the closed form to a part in ten million.'),
  ('casingtubing', 'advanced', 'module', 'm03-length-and-what-holds-it', 9, 'Why can the pressures not widen the stroke window?', '["Because the pressure terms are small compared with thermal.", "Because the total length is a straight line in temperature whose slope contains no pressure, so they only move the offset.", "Because the stroke condition uses an absolute value, which is symmetric and therefore cancels any offset the pressures apply.", "Because the piston and ballooning length terms have opposite signs, so their net contribution to the total is always zero."]'::jsonb, 1, 'They slide the window along the axis and they never change its width.'),
  ('casingtubing', 'advanced', 'module', 'm03-length-and-what-holds-it', 10, 'How much stroke does a 2500 m string need to cover an 80 degree operating swing?', '["About 1.2 m, which is the expansion coefficient times the length times the swing, halved.", "Two metres, which is the industry standard length.", "About 2.4 m, since the string must be able to move the full thermal length change in whichever direction the swing takes it.", "It depends on the pressure changes, since those determine where in the seal bore the string sits at the start of the event."]'::jsonb, 0, 'This packer has 1.5 m and would cover a 100 degree swing.'),
  ('casingtubing', 'advanced', 'module', 'm03-length-and-what-holds-it', 11, 'Which architecture transmits essentially no axial force to the packer?', '["Anchored, where the tubing is latched to the packer.", "Limited motion, because the stops are sprung and absorb the load rather than transmitting it into the packer body itself.", "Free motion, provided the string stays within the length of the bore, which is the condition the stroke verdict tests for.", "Free motion, where the tubing ends in a seal assembly sliding in a polished bore."]'::jsonb, 3, 'It is common for exactly that reason, and it costs almost nothing.'),
  ('casingtubing', 'advanced', 'module', 'm03-length-and-what-holds-it', 12, 'For a case whose free length change is well inside the stroke, what is the reported force?', '["Correct, because the packer resists the movement anyway.", "An understatement, because a string that has not reached its stop is still developing force as the temperature continues to rise.", "An overstatement, because the string never reaches its stop and the anchored answer does not apply to it.", "Meaningless, because the engine skips the force calculation whenever the free length change is inside the specified stroke."]'::jsonb, 2, 'The production heating case is that situation: 0.8947604591459051 m against 1.5 m of stroke.'),
  ('casingtubing', 'advanced', 'module', 'm03-length-and-what-holds-it', 13, 'What are the three possible values of the stroke verdict?', '["True and false, since it is a simple comparison.", "True, false, and null when no stroke was specified at all.", "True, false and a numeric margin giving how much of the stroke remains, so the reader can see how close the case came.", "Ok, exceeded and marginal, the last being the state in which the length change is within ten percent of the available stroke."]'::jsonb, 1, 'Any code that treats the null as truthy has converted a missing input into a pass.'),
  ('casingtubing', 'advanced', 'module', 'm03-length-and-what-holds-it', 14, 'Why does the stroke check use an absolute value?', '["Because a string that shortens out of the bottom of the bore has lost its seal exactly as one that lengthens out of the top has.", "Because the sign of the length change is not reliable.", "Because the seal assembly is symmetric, so the same stroke is available in each direction and the sign carries no information.", "Because the packer rating is quoted as a single number for both directions, and the stroke check follows the same convention."]'::jsonb, 0, 'Both are a lost seal, and the consequence is annulus communication rather than a broken string.'),
  ('casingtubing', 'advanced', 'module', 'm03-length-and-what-holds-it', 15, 'Two of the three published cases stroke this completion out. What is the right fix?', '["A heavier tubing, which moves less for the same load.", "A lower operating temperature swing, achieved by insulating the tubing so that the mean change over the string is reduced.", "A longer seal assembly or a different packer, since the tubing is not the problem.", "An anchored packer, since a latched string cannot stroke out of its bore and the force it develops is within the rating."]'::jsonb, 2, 'The instinct on seeing two failures is to change the tubing, and the tubing is not what failed.'),
  ('casingtubing', 'advanced', 'module', 'm04-buckling', 1, 'Euler''s buckling load for this 2500 m tubing is about half a newton. Why does that not end the discussion?', '["Because Euler applies only to bars in compression.", "Because the string is not free to move sideways: it lies in a hole with a radial clearance around it.", "Because the tubing is supported by the fluid it is immersed in, which raises the effective critical load by the buoyancy factor.", "Because Euler assumes pinned ends and the tubing is fixed at the packer, which quadruples the critical load for that case."]'::jsonb, 1, 'To buckle it has to lift itself off the low side, which is a completely different problem.'),
  ('casingtubing', 'advanced', 'module', 'm04-buckling', 2, 'Which three quantities does the buckling limit depend on?', '["The length, the diameter and the compressive force.", "The steel area, the modulus and the length, which together give the slenderness ratio the classical solutions are written in.", "The bending stiffness, the buoyed weight per metre and the clearance, and the sine of the inclination multiplies the weight.", "The bending stiffness, the buoyed weight per unit length and the radial clearance, with the hole angle scaling the weight."]'::jsonb, 3, 'Not the length, which is the second time in the tier a length has dropped out of something that should contain it.'),
  ('casingtubing', 'advanced', 'module', 'm04-buckling', 3, 'Why does the sine of the inclination appear in the buckling limit?', '["Because the restoring force is the component of weight pressing the string against the low side of the hole.", "Because the axial load resolves along the hole axis.", "Because the radial clearance is measured perpendicular to the hole, so it must be projected onto the vertical when weight acts.", "Because the buoyed weight is a vertical force and only its component along the string contributes to the axial compression."]'::jsonb, 0, 'In a vertical hole that sine is zero and there is no restoring force at all.'),
  ('casingtubing', 'advanced', 'module', 'm04-buckling', 4, 'The engine passes an inclination of 90 degrees for the packer region. What kind of choice is that?', '["The most conservative, since sine is largest there.", "A neutral choice, because the sine of ninety degrees is one and the term therefore drops out of the calculation entirely.", "The most stable orientation and therefore the least conservative one, since a lower angle gives a lower limit.", "An arbitrary one, because the buckling limit is insensitive to the hole angle over the range a completion packer is set in."]'::jsonb, 2, 'A vertical hole would give a limit of zero, and the truth for a real completion is between the two.'),
  ('casingtubing', 'advanced', 'module', 'm04-buckling', 5, 'The helical limit is what multiple of the sinusoidal one?', '["The square root of two, about 1.4142135623730951.", "Two root two less one, which is 1.8284271247461903 on every string in every hole at every inclination.", "It depends on the radial clearance, since the helix has to fit inside the annulus while the sinusoidal shape does not.", "Two, because the helical mode has twice the curvature of the sinusoidal one and therefore takes twice the load to reach."]'::jsonb, 1, 'It is a pure number falling out of the two mode shapes, with no geometry in it.'),
  ('casingtubing', 'advanced', 'module', 'm04-buckling', 6, 'What is the difference between the two buckling shapes?', '["Sinusoidal snakes from side to side in a plane along the low side, while helical wraps around the inside of the casing.", "Sinusoidal is elastic and helical is plastic.", "Sinusoidal occurs in a vertical hole and helical in a deviated one, because the restoring weight acts differently in each.", "Sinusoidal is a static shape and helical is a dynamic one that develops only while the string is being moved in the hole."]'::jsonb, 0, 'Sinusoidal comes first, and at a higher load the string snaps into a helix.'),
  ('casingtubing', 'advanced', 'module', 'm04-buckling', 7, 'The published production heating case sits above the helical limit by about seven percent. What does that make the finding?', '["Robust, since seven percent is a wide margin.", "Wrong, because a seven percent exceedance is inside the uncertainty of any planning-level buckling limit and cannot be relied on.", "True and robust, because the buckling state is a discrete outcome and a seven percent exceedance is unambiguous.", "True and marginal, since a slightly cooler production temperature would leave the string sinusoidal instead."]'::jsonb, 3, 'The exceedance is 7811.9781603483425 N out of a helical limit of 115872.96889413144.'),
  ('casingtubing', 'advanced', 'module', 'm04-buckling', 8, 'What is the radial clearance for this completion?', '["Half an inch, as with most tubing in seven inch casing.", "0.06817360000000002 m, which is the full difference between the casing inside diameter and the tubing outside diameter.", "0.03408680000000001 m, being half the difference between the casing bore and the tubing outside diameter.", "It varies along the string, since the casing is tapered and the tubing passes through more than one nominal size."]'::jsonb, 2, 'Three and a half inch tubing inside seven inch 29 lb/ft casing gives thirty four millimetres each side.'),
  ('casingtubing', 'advanced', 'module', 'm04-buckling', 9, 'Which way does a tighter hole move the buckling limit?', '["Down, because a tight annulus concentrates the contact force.", "Up, because a string that has nowhere to go cannot develop a buckling wave.", "It does not move, because the clearance enters both the sinusoidal and the helical expressions and cancels between them.", "Down at low compression and up at high compression, because the mode shape changes once the string contacts the wall."]'::jsonb, 1, 'The limits go as one over the square root of the clearance, so halving it raises them by root two.'),
  ('casingtubing', 'advanced', 'module', 'm04-buckling', 10, 'The engine defaults to a clearance of 0.02 m when no casing size is given. What is the risk?', '["A completion run without a casing size still gets an answer, computed on a clearance that may be nothing like the real one.", "The calculation throws and the run is aborted.", "The answer is always conservative, since twenty millimetres is smaller than any real annulus and a tighter hole gives a lower limit.", "The buckling state is reported as unknown, which any downstream reader will correctly interpret as a missing input."]'::jsonb, 0, 'Twenty against thirty four is a factor of 1.7 in clearance and 1.3 in the limit, enough to change the reported state.'),
  ('casingtubing', 'advanced', 'module', 'm04-buckling', 11, 'Why does the engine floor the clearance at a millimetre?', '["To avoid a division by zero in the square root.", "Because a millimetre is the smallest annulus in which a tubing string can physically be run, so it is a physical rather than a numerical floor.", "Because a zero or negative clearance would give an infinite limit, and the floor converts that into a large but finite one instead.", "To turn a silent absurdity from a typo in a casing size into a very large finite number a reader will question."]'::jsonb, 3, 'A negative clearance is not nonsense: it is what a mistyped casing size produces.'),
  ('casingtubing', 'advanced', 'module', 'm04-buckling', 12, 'At a bore pressure change of 10 MPa, when does this string first buckle?', '["Immediately, since the pressure terms put it in compression.", "At 30.45640382594624 degrees of mean temperature change, and it goes helical at 43.11622208089929.", "At 45 degrees, which is the production heating case, and it goes helical at about 65 where the stroke also runs out.", "It never does at that pressure, because the piston and ballooning terms keep the string in tension at every temperature."]'::jsonb, 1, 'Both are above zero because at zero temperature change the pressure terms alone put the string in tension.'),
  ('casingtubing', 'advanced', 'module', 'm04-buckling', 13, 'Why bisect for the buckling onset rather than read it off a sweep?', '["Because a threshold that is going to be quoted should be a number somebody else can check, not an interval.", "Because a sweep would take too long to compute.", "Because the buckling state is a discrete function of temperature and a sweep would miss the crossing entirely if the step were coarse.", "Because the relationship between temperature and force is nonlinear, so interpolating between sweep points would be inaccurate."]'::jsonb, 0, 'A five degree sweep would place the onset between 30 and 35 and stop there.'),
  ('casingtubing', 'advanced', 'module', 'm04-buckling', 14, 'The gap between the two onsets is 12.659818254953054 degrees. What is it made of?', '["The bisection tolerance on the two searches.", "The difference between the sinusoidal and helical mode wavelengths, expressed as an equivalent temperature through the expansion coefficient.", "The gap between the two force limits, converted to temperature through the thermal coefficient.", "The width of the transition between the two shapes, over which the string is partly sinusoidal and partly helical along its length."]'::jsonb, 2, 'It is the difference of the limits divided by 4146.974057365369 N per degree.'),
  ('casingtubing', 'advanced', 'module', 'm04-buckling', 15, 'The buckling state is reported and never used. What is it for?', '["To feed the length change calculation on the next iteration.", "To select the design factor applied to the packer force, since a buckled string transmits less load into the packer body.", "To say that the planning numbers have stopped being adequate, which is a legitimate thing for a screening tool to do.", "To warn that the compression has exceeded the pipe body yield, which is the point at which the string permanently deforms."]'::jsonb, 2, 'A completion reporting helical on any case needs a proper buckling analysis before anybody relies on the length change.'),
  ('casingtubing', 'advanced', 'module', 'm05-the-envelope-and-its-edges', 1, 'Read by packer force alone, which of the three published cases is worst?', '["Production heating, which is the only one in compression.", "Stimulation, at a safety factor of 1.448941812184961, which is the lowest of the three by a wide margin.", "Injection cooling, because its total force of 250266.9927748846 N is developed against the smallest available stroke.", "They are comparable, because all three totals fall within about a factor of two of each other on this packer rating."]'::jsonb, 1, 'Production heating is the best of the three on that measure, at 5.416989018921467.'),
  ('casingtubing', 'advanced', 'module', 'm05-the-envelope-and-its-edges', 2, 'Read by buckling alone, which operation is the one to worry about here?', '["Production heating, which is also the one with the best packer safety factor of the three.", "Stimulation, which has the largest total force.", "Injection cooling, because a cooling string contracts and the contraction drives it into compression against the packer stop.", "All three, because every one of them develops a total force larger than the sinusoidal limit for this geometry."]'::jsonb, 0, 'The other two are in tension, and buckling responds only to compression.'),
  ('casingtubing', 'advanced', 'module', 'm05-the-envelope-and-its-edges', 3, 'Why is there no single design case for this completion?', '["Because the three cases are equally severe.", "Because the packer rating and the stroke are quoted by different manufacturers and are therefore not directly comparable.", "Because the limits respond to different functions of the same force, so the worst case for one is not the worst for another.", "Because buckling responds to the sign of the force while the packer and stroke checks respond to its magnitude."]'::jsonb, 3, 'Only one of the three cases is in compression, and compression is what the other two limits are indifferent to.'),
  ('casingtubing', 'advanced', 'module', 'm05-the-envelope-and-its-edges', 4, 'Sizing this completion for stimulation alone would tell you nothing about what?', '["The packer rating, which stimulation governs.", "The stroke, since stimulation strokes out by more than twice the available travel and therefore bounds that limit as well.", "Buckling, because stimulation is a cooling event and a cooling string does not buckle.", "The erosional velocity, which depends on the produced rate rather than on the treatment rate the stimulation is pumped at."]'::jsonb, 2, 'The temptation is to size for the severest operation and move on.'),
  ('casingtubing', 'advanced', 'module', 'm05-the-envelope-and-its-edges', 5, 'The same shape of result appeared in the Professional tier. Where?', '["A collapse case that produced a burst differential.", "A case named after burst that was governed by the triaxial check instead.", "A section whose governing depth for burst was at the wellhead rather than at the shoe, which is where every other case governed.", "A pair of evacuation cases that gave byte-identical numbers on the upper section and very different ones on the lower."]'::jsonb, 1, 'Same mechanism, different module: the limit that binds is not the one the name suggests.'),
  ('casingtubing', 'advanced', 'module', 'm05-the-envelope-and-its-edges', 6, 'The erosional velocity formula is a constant over the square root of what?', '["The mixture density, expressed in pounds per cubic foot in the original field-unit form.", "The tubing inside diameter, in inches.", "The gas to liquid ratio, which is what determines how abrasive a multiphase stream is at a given superficial velocity.", "The product of the density and the viscosity, which together set the momentum flux the correlation is really a proxy for."]'::jsonb, 0, 'Light fluids can go fast and heavy fluids cannot.'),
  ('casingtubing', 'advanced', 'module', 'm05-the-envelope-and-its-edges', 7, 'What is the conventional C factor for continuous service?', '["Fifty, doubled to a hundred for corrosion resistant alloys.", "One hundred and twenty five for continuous service, reduced to a hundred where sand is expected in the produced stream.", "One hundred for continuous service and 125 for intermittent, both of which are the values the original document recommends.", "One hundred, with 125 used for intermittent service in the original recommended practice."]'::jsonb, 3, 'The engine''s golden case uses a C of 100 at 700 kg/m3, giving 4.610800842784442 m/s.'),
  ('casingtubing', 'advanced', 'module', 'm05-the-envelope-and-its-edges', 8, 'What is the most serious thing missing from the erosional velocity correlation?', '["A temperature term for the produced fluid.", "A velocity profile, since the correlation uses a bulk average while the erosion happens at the wall where the shear is highest.", "A sand term, since a trace of produced sand changes the erosion rate by orders of magnitude.", "A pressure term, because the same mass rate at a lower pressure gives a much higher velocity through the same tubing bore."]'::jsonb, 2, 'The formula does not know sand exists.'),
  ('casingtubing', 'advanced', 'module', 'm05-the-envelope-and-its-edges', 9, 'Why does this engine keep a correlation it describes as poor?', '["Because no better model exists for erosional velocity.", "Because it is the industry''s common screening number and a tubing size that fails it will be questioned.", "Because it is conservative, so a tubing sized against it will always be larger than an erosion rate model would require.", "Because the recommended practice mandates it, and a design that departs from a published standard has to justify itself."]'::jsonb, 1, 'The engine''s own comment calls it the one honest flow fragment kept.'),
  ('casingtubing', 'advanced', 'module', 'm05-the-envelope-and-its-edges', 10, 'The tubing calculations in this tier are described as what, by the engine''s own header?', '["Lubinski planning forms, which is a real category of closed-form approximation designed to be computed by hand.", "Exact solutions of the tubing movement problem.", "Finite element results tabulated for the common tubing sizes, interpolated at run time for the geometry actually supplied.", "Empirical correlations fitted to measured tubing movement on producing wells, in the manner of the collapse formulas."]'::jsonb, 0, 'They are still used, still taught and still approximate.'),
  ('casingtubing', 'advanced', 'module', 'm05-the-envelope-and-its-edges', 11, 'Which loop does the engine deliberately not close?', '["The thermal one, between temperature and length.", "The pressure one, since the bore pressure change affects the length which affects the volume which affects the pressure again.", "The buckling one, because a buckled string carries part of its load as wall contact, which changes the force at the packer.", "The buckling one: the state is computed from the force and then not fed back into it."]'::jsonb, 3, 'Closing it needs an axial force profile along the string and a friction coefficient.'),
  ('casingtubing', 'advanced', 'module', 'm05-the-envelope-and-its-edges', 12, 'Annular pressure buildup is named as a missing coupling. What is it?', '["The pressure the packer applies to the casing wall.", "The pressure that accumulates in the annulus from a leaking tubing connection, which the seal rating is meant to prevent.", "Heating a sealed annulus raises its pressure, sometimes by tens of megapascals, and nothing here computes that.", "The rise in annulus pressure as the tubing balloons outward and reduces the volume the annulus fluid has available to it."]'::jsonb, 2, 'A case with 45 degrees of heating and no annulus pressure change describes an annulus that somehow did not warm up.'),
  ('casingtubing', 'advanced', 'module', 'm05-the-envelope-and-its-edges', 13, 'Why is friction absent from every number in this tier?', '["Because friction is small for a string in tension.", "Because the planning forms assume the string transmits load perfectly along its whole length.", "Because the friction coefficient between steel and the packer seals is not published, so the engine omits it rather than guess.", "Because friction acts only during movement, and every case here is a comparison between two static equilibrium conditions."]'::jsonb, 1, 'The seal assembly has friction and so does a buckled string against the casing.'),
  ('casingtubing', 'advanced', 'module', 'm05-the-envelope-and-its-edges', 14, 'Which of the topics taught in this tier is graded nowhere?', '["Erosional velocity, buckling length change, annular pressure buildup, connection sealing, wear and fatigue.", "The total force at the packer, which is a screening number.", "The helical buckling limit, since it depends on a default clearance and an assumed hole angle rather than on measured inputs.", "The three length terms, since the fourth one is missing and a total that omits a term cannot be certified as correct."]'::jsonb, 0, 'For each of them, either the engine cannot produce the answer or it produces a screening version.'),
  ('casingtubing', 'advanced', 'module', 'm05-the-envelope-and-its-edges', 15, 'What does the go-live migration for this course refuse to run against?', '["A capstone with fewer than six fields per tier.", "A capstone field whose expected value falls within tolerance of a number the published goldens carry, which would make it a lookup.", "A capstone field whose name matches buckling length, annular buildup, erosion, wear, fatigue, sealing or temperature derating.", "A course structure whose lesson count differs from the manifest, since the two would then disagree about what was taught."]'::jsonb, 2, 'It is a scope decision written as a check, so a later edit that added an erosion field is stopped rather than reviewed.'),
  ('casingtubing', 'advanced', 'module', 'm06-the-expert-reading', 1, 'Summarising the Expert tier: what is a tubing string, in one phrase?', '["A smaller casing string with a lower pressure rating.", "A casing string that is allowed to move, and everything different about it follows from that permission.", "A conduit sized for flow rather than for pressure, which is why the erosional velocity limit is the one that usually governs it.", "A pressure vessel sealed at both ends, so that the internal pressure produces an axial load the casing strings never see."]'::jsonb, 1, 'It can change length, load its packer and buckle, and a cemented string can do none of those.'),
  ('casingtubing', 'advanced', 'module', 'm06-the-expert-reading', 2, 'Which two quantities in this tier surprisingly contain no length?', '["The thermal force and the two buckling limits, both of which are the same for a short string and a long one.", "The piston force and the ballooning force.", "The three length changes, since each is a strain and a strain is dimensionless before it is multiplied by anything at all.", "The packer safety factor and the stroke verdict, both of which are ratios and therefore independent of the string dimensions."]'::jsonb, 0, 'The thermal LENGTH change does contain the length, and holding that pair together is the point.'),
  ('casingtubing', 'advanced', 'module', 'm06-the-expert-reading', 3, 'Which two constants in this tier are exact pure numbers?', '["The expansion coefficient and Young''s modulus.", "The stroke window width and the buckling onset temperature, both of which are computed to the machine''s own precision.", "The helical ratio of 1.8284271247461903 and the stroke window of 100 degrees, neither of which depends on the geometry.", "The helical to sinusoidal ratio of two root two less one, and the ballooning factor of twice the Poisson ratio."]'::jsonb, 3, 'The stroke window width is exact for this string and it does depend on the stroke and the length.'),
  ('casingtubing', 'advanced', 'module', 'm06-the-expert-reading', 4, 'A capstone runs a different tubing inside the same casing. What has changed about the buckling calculation?', '["Nothing, since the casing is unchanged.", "Only the bending stiffness, since the clearance is a property of the casing and the tubing size does not enter it directly.", "The radial clearance, because it is half the difference between the casing bore and the tubing outside diameter.", "The inclination, because a larger tubing lies differently in the same casing and its contact angle with the low side changes."]'::jsonb, 2, 'A bigger tubing in the same casing means a tighter annulus and therefore a higher limit.'),
  ('casingtubing', 'advanced', 'module', 'm06-the-expert-reading', 5, 'A capstone thermal force comes out positive at a positive temperature change. What went wrong?', '["Nothing, since heating always produces tension.", "The minus sign in front of the formula was dropped, which also flips the total and every conclusion after it.", "The temperature change was entered as a bottomhole value rather than a mean, which doubles it and reverses the reported sign.", "The steel area was computed from the bore rather than the annulus, which makes the term small enough to be swamped by the others."]'::jsonb, 1, 'It is also the largest of the three, so getting its sign wrong is the most expensive single error available.'),
  ('casingtubing', 'advanced', 'module', 'm06-the-expert-reading', 6, 'A capstone total force must exceed a buckling limit in absolute value. What does that tell you before you compute anything?', '["That the completion buckles, and that a positive total would therefore mean an error rather than a passing string.", "That the packer rating has been exceeded as well.", "That the stroke will also be exceeded, since a buckled string has wrapped and its end to end length has shortened accordingly.", "That the temperature change must be negative, since only a cooling string can develop enough force to reach the helical limit."]'::jsonb, 0, 'Two of the free checks on a capstone say the completion fails, and that is the correct answer.'),
  ('casingtubing', 'advanced', 'module', 'm06-the-expert-reading', 7, 'Why compute the sinusoidal limit even when only the helical one is graded?', '["Because the state cannot be read without both.", "Because the sinusoidal limit is the one compared against the compression, and the helical one is reported for information only.", "Because dividing the helical limit by the exact ratio recovers the sinusoidal one, which then checks the clearance and the weight.", "Because their ratio must be 1.8284271247461903, which is a free check on the whole buckling calculation."]'::jsonb, 3, 'A reported pair that does not have that ratio is a bug.'),
  ('casingtubing', 'advanced', 'module', 'm06-the-expert-reading', 8, 'A capstone applies a pressure change to the annulus as well as the bore. What does that affect?', '["The piston force only, at the seal bore.", "The ballooning force only, since the piston term uses the seal bore area which is inside the packer rather than in the annulus.", "Both the piston force and the ballooning force, and by different amounts because they act on different areas.", "Neither, since the two pressure changes are measured from the same setting condition and their effects cancel in the sum."]'::jsonb, 2, 'Dropping it gives two wrong answers rather than one.'),
  ('casingtubing', 'advanced', 'module', 'm06-the-expert-reading', 9, 'Which arithmetic check catches a sign error in exactly one of the three forces?', '["That the total exceeds the largest of the three.", "That the three add to the total, which fails for one error and can pass for two.", "That the packer safety factor equals the rating divided by the total, which is the only relation between the reported numbers.", "That the ratio of the piston force to the ballooning force equals the ratio of the two areas they act on, at any pressure."]'::jsonb, 1, 'It is the arithmetic check rather than a physical one, and it is worth doing first.'),
  ('casingtubing', 'advanced', 'module', 'm06-the-expert-reading', 10, 'A capstone total length change must exceed the stroke. Which term is responsible?', '["The thermal one, because at a large temperature change over a long string it beats both pressure terms together.", "The piston one, which is the largest of the three.", "The ballooning one, since the Poisson strain acts over the whole length while the piston term is an end effect at the packer.", "None individually, since the two pressure terms shorten the string and only their sum with the thermal term exceeds the stroke."]'::jsonb, 0, 'The pressure terms always shorten and the temperature term decides everything else.'),
  ('casingtubing', 'advanced', 'module', 'm06-the-expert-reading', 11, 'Both limits are violated on the capstone completion. What would you change first?', '["The tubing, to a heavier wall in the same size.", "The operating temperature, by insulating the string so that the mean change over its length falls below the buckling onset.", "The seal assembly length, which fixes the stroke, and then the annulus fluid density, which changes the buoyed weight and the limit.", "The seal assembly, or the packer, since the tubing is not what failed either check."]'::jsonb, 3, 'A longer seal assembly converts a force problem into a non-problem and costs almost nothing.'),
  ('casingtubing', 'advanced', 'module', 'm06-the-expert-reading', 12, 'What does an Expert in this course sign their name to?', '["Designing a completion from the reservoir up.", "Running a full tubing movement analysis with a thermal model, including the buckling feedback and the annular pressure buildup.", "Producing the Lubinski force set, the length change and the two limits for a completion, and saying which one binds.", "Selecting a packer and a seal assembly for a given well, given the operating envelope and the manufacturer''s rating data."]'::jsonb, 2, 'The tier below supplied the casing check and the one below that the ratings.'),
  ('casingtubing', 'advanced', 'module', 'm06-the-expert-reading', 13, 'What is the one thing every number in this course is about?', '["Pressure, which every load case is built from.", "Steel, because nothing here decided where a shoe should go or what the well will produce.", "The reservoir, since the fluid it delivers sets the temperature and the pressure that drive every force in the Expert tier.", "The trajectory, since every true vertical depth and every dogleg in the course comes from the well path directly."]'::jsonb, 1, 'Casing design is a downstream activity that turns a casing scheme and a set of pressures into a purchase order.'),
  ('casingtubing', 'advanced', 'module', 'm06-the-expert-reading', 14, 'Which three habits does the course close on?', '["Ask which regime, scan the profile, and compute the gap.", "Check the units, check the signs, and check the areas.", "Establish the load case, apply the design factor, and report the verdict per section rather than for the string as a whole.", "Derive every constant, recompute every rating on the worn wall, and verify each screening number against a data sheet."]'::jsonb, 0, 'All three are the same habit: the answer is only as strong as the thing that would have to change to make it different.'),
  ('casingtubing', 'advanced', 'module', 'm06-the-expert-reading', 15, 'Which later course takes all of this and asks whether the barriers are still there twenty years on?', '["Well Cost and Time, which takes the purchase order.", "Completion Design, which builds the rest of the completion around the production casing and the tubing this course sized.", "Well Integrity and P and A, which inherits the string, the cement and the completion together.", "Torque, Drag and Casing Wear, which predicts the wall loss that determines whether the original ratings still apply at all."]'::jsonb, 2, 'It is the last of the twelve, and it reads everything the other eleven produced.'),
  ('casingtubing', 'advanced', 'final', null, 1, 'You are given a completion and asked whether the packer is big enough. What do you need first?', '["The absolute pressures at the packer depth.", "The pressure changes and the temperature change from the setting condition, since every force is a delta.", "The tubing grade, since the packer force is limited by whichever of the tubing and the packer yields at the lower load.", "The reservoir pressure and the flowing tubing head pressure, from which the bore pressure change can then be worked out."]'::jsonb, 1, 'A string that has never been produced has zero force from all three mechanisms.'),
  ('casingtubing', 'advanced', 'final', null, 2, 'A completion is landed and never operated. What is the packer force from these three mechanisms?', '["Zero, because all three are measured from the setting condition and nothing has changed since.", "The buoyed weight of the tubing below the wellhead.", "The piston force from the packer fluid column, which acts on the seal bore area from the moment the packer is set onward.", "It cannot be determined without the absolute pressures, since the piston term depends on the pressure and not on its change."]'::jsonb, 0, 'Whatever the absolute pressures are.'),
  ('casingtubing', 'advanced', 'final', null, 3, 'The baseline for every delta is which moment?', '["The moment the tubing was made up at surface.", "The moment the well was first put on production, since that is the first operation the completion is designed to survive.", "The moment the packer was set, which is why a packer set after circulating cold has a different zero from one set warm.", "The moment the packer was set, with whatever fluids and temperature the well had then."]'::jsonb, 3, 'It is also the input that most often goes wrong, and the three deltas can all be right about a wrong baseline.'),
  ('casingtubing', 'advanced', 'final', null, 4, 'On this geometry, which of the three pressure areas is largest?', '["The tubing outside area, at 0.006207166618944346.", "The tubing bore area, since the fluid inside acts on it over the whole length while the others act only at the packer.", "The packer seal bore area, because the bore is larger than the tubing that seals into it.", "They are comparable, because a seal bore is sized to the tubing and the three differ by only a few percent in practice."]'::jsonb, 2, 'That ordering decides the sign of the piston force.'),
  ('casingtubing', 'advanced', 'final', null, 5, 'A packer with a smaller seal bore is fitted, tubing unchanged. What happens to the piston force?', '["It rises, because the seals are more highly loaded.", "It falls, because the area difference the bore pressure acts on has shrunk.", "It is unchanged, since the piston force depends on the tubing dimensions and the seal bore only sets where the seals sit.", "It reverses sign, because a seal bore smaller than the tubing bore makes the first area difference negative in the formula."]'::jsonb, 1, 'It is one of the few free levers in a completion.'),
  ('casingtubing', 'advanced', 'final', null, 6, 'Which sign convention does the tubing routine use?', '["Positive is tension added at the packer, so a negative total means the string is pushing down on it.", "Positive is compression, matching the buckling test.", "Positive is downward, so a heating string gives a positive total because it is trying to grow toward the bottom of the hole.", "There is none, because the routine reports the three components separately and leaves the reader to combine them."]'::jsonb, 0, 'Everything downstream depends on it, including the buckling test which uses only the compressive part.'),
  ('casingtubing', 'advanced', 'final', null, 7, 'Which mechanism puts a heated string into compression?', '["Thermal softening of the steel at temperature.", "The rise in annulus pressure that accompanies heating, which acts downward on the area between the seal bore and the outside.", "Restraint at the packer, which prevents the elongation the temperature rise would otherwise produce and returns it as a force.", "Restraint: the string wants to grow, the packer will not let it, and the reaction is compressive."]'::jsonb, 3, 'It is the reverse of the instinct that hot things push harder on everything.'),
  ('casingtubing', 'advanced', 'final', null, 8, 'A case reports a negative force and a positive length change. Is that consistent?', '["No, since force and length must agree in sign.", "Only if the pressure terms and the thermal term have opposite signs, which is what allows the two totals to differ in direction.", "Yes, because a prevented elongation is a compression, and the two columns are opposite by construction.", "Yes, but only for a free motion packer, where the length is realised and the force therefore never develops at all."]'::jsonb, 2, 'It is the commonest misreading in the tier.'),
  ('casingtubing', 'advanced', 'final', null, 9, 'The piston force on this string is 0.0035712418834005005 N per pascal of bore pressure. What is that number?', '["The steel cross-section of the tubing.", "The seal bore area less the tubing bore area, in square metres.", "The seal bore area less the tubing outside area, which is the annular area the annulus pressure acts downward on at the packer.", "The tubing bore area, since the bore pressure acts on the full internal cross-section where the tubing enters the packer."]'::jsonb, 1, 'Multiply by ten million and you get the production heating case''s piston force exactly.'),
  ('casingtubing', 'advanced', 'final', null, 10, 'Why does an annulus pressure reduce the piston force?', '["Because it acts downward on the area between the seal bore and the tubing outside, opposing the bore pressure.", "Because it compresses the tubing radially.", "Because it raises the external hydrostatic at the packer, which reduces the net differential the seals have to hold against.", "Because it acts on the same area as the bore pressure but from the other side, so the two cancel exactly at equal pressures."]'::jsonb, 0, 'The two areas are different, so equal pressures do not cancel.'),
  ('casingtubing', 'advanced', 'final', null, 11, 'Ballooning is 0.6 times which combination?', '["The difference of the two pressure changes.", "The bore pressure change on the seal bore area less the annulus change on the same area, which is what the seals separate.", "The bore pressure change times the bore area, less the annulus pressure change times the outside area of the tubing body.", "The bore pressure change on the bore area less the annulus change on the outside area."]'::jsonb, 3, 'The 0.6 is twice the Poisson ratio of steel at 0.3.'),
  ('casingtubing', 'advanced', 'final', null, 12, 'A balanced pressure test puts equal pressure on bore and annulus. Is the ballooning force zero?', '["Yes, because the two terms cancel identically.", "Yes, because the Poisson effect responds to the differential pressure across the wall rather than to either pressure alone.", "No, because the two act on different areas and the outside area is the larger of the two.", "No, because the annulus pressure enters with a coefficient of one and the bore pressure with the ballooning factor of 0.6."]'::jsonb, 2, 'It comes out negative, which means a balanced test pushes on the packer rather than pulling.'),
  ('casingtubing', 'advanced', 'final', null, 13, 'The thermal force per degree on this string is 4146.974057365369 N. What are its three factors?', '["The modulus, the length and the expansion coefficient.", "Young''s modulus, the steel cross-section and the thermal expansion coefficient.", "The modulus, the steel area and the length, with the expansion coefficient entering only the length change rather than the force.", "The steel area, the expansion coefficient and the mean temperature change, with the modulus applied when the force is summed."]'::jsonb, 1, 'Multiply by the temperature change and put a minus sign in front.'),
  ('casingtubing', 'advanced', 'final', null, 14, 'One degree of temperature is worth 658993.7232542605 Pa of bore pressure on this string. What is that ratio made of?', '["The thermal force per degree divided by the sum of the piston and ballooning coefficients per pascal.", "The modulus divided by the bulk modulus of the fluid.", "The product of the modulus and the expansion coefficient, divided by the bore pressure that produces the same axial stress.", "The temperature change that produces one megapascal of axial stress, inverted and converted through the steel cross-section."]'::jsonb, 0, 'It is why a 45 degree warm-up is worth 29.654717546441724 MPa of bore pressure.'),
  ('casingtubing', 'advanced', 'final', null, 15, 'The three forces are summed with no interaction term. Why is that legitimate?', '["Because the three mechanisms are independent.", "Because each is small enough that second order coupling between them falls below the precision the planning forms are quoted to.", "Because they act on the same body along the same axis, so superposition applies exactly for a linear elastic material.", "Because all three act on the same body in the same direction, so they add like any three collinear forces."]'::jsonb, 3, 'The sign convention does the rest of the work.'),
  ('casingtubing', 'advanced', 'final', null, 16, 'The packer safety factor uses the absolute value of the total. Why?', '["Because the sign is not reliably computed.", "Because a packer has to resist both directions and a rating is usually one number for both.", "Because the rating is quoted as a tensile capacity, and a compressive load is converted into an equivalent tension for comparison.", "Because the buckling check already uses the sign, so using it twice would double count the direction of the load."]'::jsonb, 1, 'The buckling check is the one that reads the sign, through a maximum against zero.'),
  ('casingtubing', 'advanced', 'final', null, 17, 'Which case has the lowest packer safety factor of the published three, and why?', '["Production heating, because it is in compression.", "Injection cooling, because its temperature change and its bore pressure change both act to put the string into tension at once.", "Stimulation, because all three of its terms are large and all three point the same way.", "They are equal, since the packer rating is a single number and all three cases are run against the same one."]'::jsonb, 2, 'It reaches 1.448941812184961 against a rating of 670000 N.'),
  ('casingtubing', 'advanced', 'final', null, 18, 'Which case can buckle, of the published three?', '["Only production heating, because it is the only one whose total force is negative.", "All three, at sufficiently large pressure changes.", "Production heating and stimulation, since both develop total forces larger in magnitude than the sinusoidal limit for this string.", "None, because the buckling limits are computed at ninety degrees of inclination which no completion packer is actually set at."]'::jsonb, 0, 'The other two give a compression of exactly zero through the maximum against zero.'),
  ('casingtubing', 'advanced', 'final', null, 19, 'The force column assumes what, and the length column assumes what?', '["Both assume a free motion seal assembly.", "That the string is anchored, and that it is anchored but with the buckling length change added back in to the reported total.", "That the string is fully restrained, and that it is fully free, so neither is the answer for a limited motion packer.", "That nothing moves, and that everything does, which are the two ends of a range a real packer sits inside."]'::jsonb, 3, 'Reconciling them needs a seal stiffness and a friction the model does not carry.'),
  ('casingtubing', 'advanced', 'final', null, 20, 'A seal assembly never bottoms out during an event. How should you read the packer number?', '["Correct, since the packer resists the movement anyway.", "Non-conservative, because a string that has not stroked out is still free to develop further force as conditions continue to change.", "Conservative, because the string never reaches its stop and the anchored answer overstates what reaches the packer.", "Irrelevant, because the packer only sees a force once the seal assembly has bottomed out against one end of its travel."]'::jsonb, 2, 'Production heating is that situation, at 0.8947604591459051 m against 1.5 m.'),
  ('casingtubing', 'advanced', 'final', null, 21, 'The stroke window on this string is 100 degrees. What formula gives it?', '["The difference between the two published cases.", "Twice the stroke divided by the expansion coefficient times the length.", "The stroke divided by the thermal length change per degree, which is the expansion coefficient times the length of the string.", "Twice the stroke divided by the sum of the thermal and pressure length coefficients, both taken per degree of temperature."]'::jsonb, 1, 'The bisected answer agrees with it to a part in ten million.'),
  ('casingtubing', 'advanced', 'final', null, 22, 'Raising the bore pressure change moves both stroke limits. Which way and why?', '["Both up, because the pressure terms shorten the string so it takes more heating to stroke out at the hot end.", "Both down, because pressure adds to the total length.", "The cold limit up and the hot one down, since the pressure terms reduce the length available in each direction symmetrically.", "Neither, because the stroke condition uses an absolute value which is insensitive to a constant offset in the length."]'::jsonb, 0, 'The window slides and its width stays at 100.'),
  ('casingtubing', 'advanced', 'final', null, 23, 'A 4000 m string with 2 m of stroke has what window width?', '["100 degrees, the same as any completion.", "About 83.3 degrees, since the stroke is larger and the length is longer and the two effects partly compensate for each other.", "It cannot be said without the pressure changes, since those determine where the string sits in the bore at the start.", "About 41.7 degrees, since twice the stroke over the expansion coefficient times the length falls with the length."]'::jsonb, 3, 'A longer string needs more stroke for the same operating swing, in direct proportion.'),
  ('casingtubing', 'advanced', 'final', null, 24, 'What does a null stroke verdict mean?', '["That the length change came out exactly at the limit.", "That the packer is anchored, so the stroke concept does not apply and the force column is the only relevant answer.", "That no stroke was specified, so the engine will not guess whether the string is inside one.", "That the calculation could not converge, which happens when the pressure and thermal terms are of similar magnitude."]'::jsonb, 2, 'Any code that treats it as truthy has converted a missing input into a pass.'),
  ('casingtubing', 'advanced', 'final', null, 25, 'Which of the three published cases passes the stroke check?', '["Injection cooling, at 1.81 m of contraction.", "Production heating alone, at 0.8947604591459051 m against 1.5 m.", "Stimulation, because its large pressure terms shorten the string and partly offset its fifty degrees of cooling.", "All three, since the seal assembly is sized to the largest length change any of the operating cases produces."]'::jsonb, 1, 'The other two contract past the bore, which is a lost seal at the other end.'),
  ('casingtubing', 'advanced', 'final', null, 26, 'Euler''s critical load is irrelevant for a tubing string in a hole. What replaces it?', '["The Dawson-Paslay limits, which depend on stiffness, buoyed weight, hole angle and radial clearance.", "A modified Euler load with an effective length factor.", "The pipe body yield in compression, since a string that cannot move sideways will simply yield axially before it buckles at all.", "The helical buckling limit alone, since a string lying in a hole cannot form a sinusoidal wave without first lifting off it."]'::jsonb, 0, 'None of them contains a length, which is what makes them different from Euler in kind rather than in degree.'),
  ('casingtubing', 'advanced', 'final', null, 27, 'Why does the buckling limit contain no length?', '["Because the wavelength of the buckle is short.", "Because the length cancels between the bending energy and the gravitational work in the derivation of the critical load.", "Because it is a local lift-off condition rather than a global slenderness one, so no overall length of string appears in it.", "Because the string has to lift itself off the low side to buckle, and that is a local condition rather than a global one."]'::jsonb, 3, 'It is the second time in the tier that a length has dropped out of something that intuitively should contain it.'),
  ('casingtubing', 'advanced', 'final', null, 28, 'In a vertical hole the sinusoidal limit collapses to zero. Why?', '["Because the clearance is undefined in a vertical hole.", "Because a vertical string carries no side load and therefore no contact force, so the classical solution divides by zero there.", "Because the restoring force is the component of weight pressing the string against the wall, and it vanishes.", "Because a vertical hole has no low side, so the string is already free to buckle in any direction at any compressive load."]'::jsonb, 2, 'The classical treatment of vertical tubing buckling is a different formula for that reason.'),
  ('casingtubing', 'advanced', 'final', null, 29, 'Setting the hole angle to ninety in the buckling limit does what to the answer?', '["The most conservative, since sine is largest there.", "The most stable orientation and therefore the least conservative choice available.", "A neutral one, because the sine of ninety is unity and the inclination therefore drops out of the calculation altogether.", "A realistic one, since a completion packer is almost always set in the tangent section of a deviated production well."]'::jsonb, 1, 'A vertical hole would give a limit of zero, and the truth is between the two.'),
  ('casingtubing', 'advanced', 'final', null, 30, 'Halving the radial clearance does what to the buckling limits?', '["Raises them by a factor of the square root of two, since the clearance sits under a square root in the denominator.", "Halves them, since the clearance enters linearly.", "Doubles them, because the string has half as far to move before it contacts the wall and the contact restores it sooner.", "Leaves them unchanged, since the clearance enters both the numerator and the denominator of the Dawson-Paslay expression."]'::jsonb, 0, 'Tighter is better, for buckling specifically.'),
  ('casingtubing', 'advanced', 'final', null, 31, 'A completion is run without a casing size. What does the engine assume?', '["It refuses to compute a buckling state at all.", "The clearance corresponding to the nearest standard casing size for the tubing supplied, taken from the tubular catalog.", "A radial clearance of twenty millimetres, which is a defensible default and a silent one that can change the reported state.", "A radial clearance of 0.02 m, which may be nothing like the real one."]'::jsonb, 3, 'Against this completion''s thirty four millimetres that is a factor of 1.3 in the limit.'),
  ('casingtubing', 'advanced', 'final', null, 32, 'The helical limit divided by the sinusoidal one comes out at 1.9 in a report. What does that mean?', '["A tight annulus, which raises the helical limit more.", "A high inclination, since the two limits respond differently to the sine of the hole angle and the ratio therefore varies.", "A bug, because the ratio is exactly two root two less one on every string in every hole.", "Nothing, because the ratio depends on the mode shapes which in turn depend on the ratio of the clearance to the diameter."]'::jsonb, 2, 'It is a pure number with no geometry in it, and it is worth using as a check.'),
  ('casingtubing', 'advanced', 'final', null, 33, 'This string first buckles at 30.45640382594624 degrees and goes helical at 43.11622208089929. What separates the two?', '["The width of the transition between the two shapes.", "12.659818254953054 degrees, which is the gap between the two force limits over the thermal coefficient.", "The temperature at which the pressure terms stop dominating and the thermal term takes over, which is a property of the case.", "The bisection bracket, since the two searches are run over different ranges and the difference reflects their convergence."]'::jsonb, 1, 'The production case at 45 degrees is helical by 1.88 degrees.'),
  ('casingtubing', 'advanced', 'final', null, 34, 'Buckling costs four things. Which of them does the engine compute?', '["The length change, which is fed back into the stroke.", "The contact force against the casing, which is what drives the wear a permanently buckled string inflicts on both tubulars.", "None, because each of the four needs an axial force profile along the string and a friction coefficient the model lacks.", "None of them: it reports the state and adjusts nothing."]'::jsonb, 3, 'The flag is there to say that the planning numbers have stopped being adequate.'),
  ('casingtubing', 'advanced', 'final', null, 35, 'A completion reports helical on one case and none on the others. What follows?', '["Nothing, since one case out of three is normal.", "The other two cases must be rerun at the same conditions, since a string that buckles once will carry residual curvature afterward.", "The planning numbers on that case cannot be relied on, and a proper buckling analysis is needed before they are.", "The length change on the buckled case is overstated, so the stroke verdict on it is conservative and can be accepted as it stands."]'::jsonb, 2, 'It is a legitimate thing for a screening tool to do: know where its own answer stops being good.'),
  ('casingtubing', 'advanced', 'final', null, 36, 'Read three ways, the three published cases give three different worst cases. What is the general condition for that?', '["That the three cases are of comparable severity.", "That the limits respond to different functions of the same variable, an absolute value here and a one-sided maximum there.", "That the three mechanisms have different signs, so that the sum can be positive for some cases and negative for others.", "That the packer rating and the stroke are set by different manufacturers and are therefore not on a comparable scale."]'::jsonb, 1, 'The same shape appeared in the Professional tier, where a case named after burst was governed by triaxial.'),
  ('casingtubing', 'advanced', 'final', null, 37, 'The erosional velocity at 700 kg/m3 and a C of 100 is 4.610800842784442 m/s. What is that number for?', '["Sizing a tubing for rate: exceed it and the tubing is too small for the flow it is being asked to carry.", "Certifying that the tubing will not erode in service.", "Setting the maximum drawdown, since the velocity at the perforations is what determines whether sand will be produced at all.", "Checking the packer, since the momentum of the flowing stream applies an axial load at every change of section in the string."]'::jsonb, 0, 'It decides tubing size on a great many wells and it certifies nothing.'),
  ('casingtubing', 'advanced', 'final', null, 38, 'Which is the strongest objection to the erosional velocity correlation?', '["That it uses field units rather than SI internally.", "That the square root of density is the wrong functional form, since erosion depends on the momentum flux rather than the velocity.", "That it was fitted in the 1980s, and modern tubulars are made to tighter tolerances than the pipe in the original test population.", "That the C factor is treated as a constant when it depends on material, corrosivity, sand and continuity of service."]'::jsonb, 3, 'A single number cannot carry four dependencies, and the recommended practice itself says so in later editions.'),
  ('casingtubing', 'advanced', 'final', null, 39, 'Which of the seven named omissions would matter most on a deep subsea gas well?', '["The missing buckling length change term.", "The single mean temperature, since a gas well warms nearly uniformly and the mean is therefore an excellent approximation.", "Annular pressure buildup, because a sealed subsea annulus that warms up has nowhere to put the pressure.", "The absence of friction, since a subsea completion has a long tubing string and the seal friction accumulates over its length."]'::jsonb, 2, 'It is a live safety issue rather than a modelling nicety.'),
  ('casingtubing', 'advanced', 'final', null, 40, 'Why does the go-live migration assert the scope decision rather than leaving it to review?', '["So that a later edit which quietly added an erosion field is stopped rather than reviewed.", "Because migrations are the only place assertions can run.", "Because a reviewer cannot be expected to remember which topics were deliberately excluded from a course written months earlier.", "Because the scope decision is part of the certificate''s meaning, and a certificate cannot be revoked once it has been issued."]'::jsonb, 0, 'It is a scope decision written as a check.'),
  ('casingtubing', 'advanced', 'final', null, 41, 'Which six quantities does the Expert tier grade, and what do they have in common?', '["Six safety factors, all of them ratios.", "The three forces, the packer safety factor, the buckling state and the stroke verdict, which together summarise the completion.", "Three forces, the total, the length change and the erosional velocity, since all six are computed by a single engine call.", "Three forces, their total, the helical limit and the total length change, all of them exact closed forms."]'::jsonb, 3, 'None of them is a screening correlation, which is why each earns its place.'),
  ('casingtubing', 'advanced', 'final', null, 42, 'What does the course close on, as the single transferable habit?', '["That every constant should be derived rather than typed.", "That a screening tool should always be verified against a full analysis before any of its numbers are used in a design decision.", "That an answer is only as strong as the thing that would have to change to make it different.", "That the four collapse regimes decide everything, since the regime is what determines how a shortfall should be corrected."]'::jsonb, 2, 'Ask which regime, scan the profile, compute the gap: three versions of the same habit.');
