-- ============================================================================
-- DR7 PROFESSIONAL DEEP SEED: Cementing, intermediate tier.
--
-- Six modules, 26 lessons, 132 questions (15 per module bank plus a 42
-- question final exam). The structure row is GENERATED from the tier's
-- manifest.json rather than hand typed.
--
-- What this tier owns: placement. The flow path is parametrised by PUMPED
-- VOLUME rather than by depth, because depth is not single valued on a U, and
-- pumping one cubic metre advances every front by exactly one cubic metre of
-- path coordinate wherever it is. The fronts partition the path into intervals
-- whose lengths always sum to the path length. Two maps convert volume back to
-- measured depth, the annulus one running BACKWARDS from the shoe. And the
-- whole pressure calculation is one line: the maximum of zero and the annulus
-- head plus friction less the inside head, with the heads on the exact
-- minimum-curvature true vertical depths and the friction imported from the
-- hydraulics loss kernel rather than reimplemented here.
--
-- THE FINDING THE TIER IS BUILT ON. The pump rate is a straight TRADE. Faster
-- adds friction, which supports the annular column and cures free fall, and
-- the same friction raises the equivalent circulating density at the
-- shallowest exposed formation. One knob, two constraints, opposite senses.
-- Both edges are BISECTED rather than swept, because a sweep gives an interval
-- and the answer is going to be quoted. On the HORIZONTAL well with a NEAT
-- single slurry, at a previous-shoe limit of 1700 kg/m3, the window is CLOSED:
-- the slowest rate with no free fall is 0.02059793163869393 and the fastest
-- under the limit is 0.017832442077937685, a width of
-- -0.0027654895607562464. Every rate slow enough to protect the shoe free
-- falls and every rate fast enough to prevent free fall fractures it.
--
-- AND THE LEAD SLURRY OPENS IT. The same well with a lighter lead across the
-- cased annulus gives 0.019340962816243038 and 0.024740241221207958, a width
-- of 0.00539927840496492. One change to the programme moved BOTH edges in the
-- helpful direction: the free-fall edge down because the annular column is
-- heavier, and the ECD edge up because the head at the previous shoe is lower.
-- Which is the whole argument for a lead slurry, and it is not the cost one.
--
-- A SECOND FINDING, IN m03. The equivalent circulating density at the CASING
-- shoe on the horizontal well is 1837.9218199066345 kg/m3 before anything has
-- been pumped, against 1646.773401667299 on the slant well, because it divides
-- the friction of a 1600 m lateral by 1214.859173174059 m of true vertical
-- depth. ECD divides a quantity generated along the hole by one measured
-- vertically, and the two stop being proportional the moment the hole turns.
--
-- A THIRD, IN m05, AND IT IS ABOUT THE GRID. The horizontal well's neat
-- programme free falls at exactly ONE of the 61 default steps. Refined to 600
-- the dip spans sixteen samples over about two cubic metres and the worst
-- deficit is -110300.25230836123 Pa rather than -104394.27505085245. The
-- finding survives and one of its digits does not, and neither is visible from
-- a single run.
--
-- Numeric sweep and tier-leakage sweep as for the Associate tier: 0
-- unresolved literals, 0 downward leaks, 0 same-tier answer prints.
--
-- Answer keys live only here and in academy_quiz_questions, which has no
-- client SELECT policy.
-- ============================================================================

insert into public.academy_course_structures
    (app_slug, tier, structure, content_version)
values ('cementing', 'intermediate', '{"modules":[{"key":"m01-the-flow-path","title":"The Flow Path","lesson_keys":["l01-plug-flow-and-what-it-assumes","l02-the-volume-coordinate","l03-fronts-and-intervals","l04-from-volume-to-measured-depth"]},{"key":"m02-the-u-tube","title":"The U-tube","lesson_keys":["l01-three-terms-and-a-maximum","l02-head-on-the-exact-tvd","l03-friction-from-the-loss-kernel","l04-free-fall","l05-the-one-pascal-deadband"]},{"key":"m03-the-job-over-time","title":"The Job Over Time","lesson_keys":["l01-reading-a-pump-pressure-curve","l02-it-falls-before-it-rises","l03-ecd-at-the-previous-shoe","l04-ecd-at-the-shoe","l05-the-end-of-the-job"]},{"key":"m04-two-programmes-one-well","title":"Two Programmes, One Well","lesson_keys":["l01-neat-and-lead-and-tail","l02-what-the-lead-slurry-buys","l03-the-rate-is-a-trade","l04-when-the-window-closes","l05-choosing-a-programme"]},{"key":"m05-reading-a-placement-result","title":"Reading a Placement Result","lesson_keys":["l01-achieved-toc","l02-the-warnings-one-at-a-time","l03-what-the-simulation-cannot-see","l04-sixty-steps"]},{"key":"m06-the-professional-reading","title":"The Professional Reading","lesson_keys":["l01-the-story-so-far","l02-working-the-capstone","l03-onward"]}]}'::jsonb, 1)
on conflict (app_slug, tier) do update
  set structure = excluded.structure,
      content_version = excluded.content_version,
      active = true,
      updated_at = now();

delete from public.academy_quiz_questions
 where app_slug = 'cementing' and tier = 'intermediate';

insert into public.academy_quiz_questions
    (app_slug, tier, scope, module_key, ord, prompt, options, answer_index, explanation)
values
  ('cementing', 'intermediate', 'module', 'm01-the-flow-path', 1, 'What does the plug flow assumption say about the interfaces between fluids?', '["That each spans about thirty metres of annulus.", "That each is a sharp face with no mixing across it, in the order the fluids were pumped.", "That mixing occurs but is symmetric, so the average density across the interface equals the average of the two fluids.", "That the spacer volume is what sets the interface length, which is why a spacer is required between mud and cement."]'::jsonb, 1, 'The engine''s own header calls it plug flow volume bookkeeping, no intermixing.'),
  ('cementing', 'intermediate', 'module', 'm01-the-flow-path', 2, 'What does plug flow buy?', '["A more realistic interface than a mixing model gives.", "The ability to model contamination, since the volume of each fluid is tracked separately along the whole of the flow path.", "Exactness and speed, which is what makes eighty runs of a whole job affordable inside a single bisection.", "Exactness, reproducibility and speed, because every front position is arithmetic rather than a solution."]'::jsonb, 3, 'No time stepping, no numerical diffusion, no convergence.'),
  ('cementing', 'intermediate', 'module', 'm01-the-flow-path', 3, 'What does plug flow cost, most importantly?', '["The spacer''s whole purpose, because a spacer exists to control mixing and this model has no mixing.", "Accuracy in the hydrostatic head at the interfaces.", "The ability to compute the achieved top of cement, since a mixed interface has no single depth at which the cement stops.", "Speed, since the intervals have to be rebuilt from scratch at each of the sixty one steps rather than advanced."]'::jsonb, 0, 'In this model the spacer is a block of fluid of a given density and rheology, and nothing else.'),
  ('cementing', 'intermediate', 'module', 'm01-the-flow-path', 4, 'Why is the flow path parametrised by volume rather than by depth?', '["Because the annulus capacity varies with depth.", "Because the pumps deliver volume, and converting a delivered volume into a depth would need the capacity at every point.", "Because depth is not single valued on a U: at 1000 m you can be inside the casing or in the annulus.", "Because the true vertical depth is what the hydrostatic head needs, and measured depth would have to be converted anyway."]'::jsonb, 2, 'And because pumping one cubic metre advances every front by exactly one cubic metre of path coordinate.'),
  ('cementing', 'intermediate', 'module', 'm01-the-flow-path', 5, 'The slant well''s path is 98.50861256939106 cubic metres and the job pumps 86.48058691428402. What does that mean?', '["The job is under-displaced by 12 cubic metres.", "The last of the original mud is still in the annulus at surface when the job ends.", "The cement has not yet reached the annulus, since the pumped volume is smaller than the path length of the whole circuit.", "The engine will report a warning, because a job that does not fill the path cannot reach its target top of cement."]'::jsonb, 1, 'A job pumping a full path volume would bring cement back to surface.'),
  ('cementing', 'intermediate', 'module', 'm01-the-flow-path', 6, 'Where does a fluid''s front sit at pumped volume V?', '["At V less the total volume of the fluids pumped ahead of it, clamped between zero and the path length.", "At V times the fraction of the job that fluid represents.", "At V less the volume of the fluid itself, since the front is the leading face and the volume trails behind it along the path.", "At the path length less V, because the fronts advance from the far end of the annulus back toward the pumps at surface."]'::jsonb, 0, 'The clamp holds a front at zero before it has entered and at the path end once it has left.'),
  ('cementing', 'intermediate', 'module', 'm01-the-flow-path', 7, 'What lies above the first front, from it to the end of the path?', '["The displacement fluid, which entered most recently.", "Nothing, because the first front is by definition the leading face and there is no fluid ahead of the first one pumped.", "The mud that was in the hole before the job, which is why the mud interval shrinks as the first front advances.", "The original mud that was in the hole before the job started."]'::jsonb, 3, 'And below the last front is whatever entered most recently, which is the displacement.'),
  ('cementing', 'intermediate', 'module', 'm01-the-flow-path', 8, 'What must the interval lengths always sum to?', '["The total pumped volume so far.", "The path length less the volume still in the pumps, which is why the sum falls as the job proceeds toward the plug bump.", "The path length, at every pumped volume, by construction.", "The sum of the fluid volumes, since each fluid occupies an interval whose length is exactly the volume pumped of it."]'::jsonb, 2, 'The engine''s test asserts it at several pumped volumes, which is the cheapest possible check on the bookkeeping.'),
  ('cementing', 'intermediate', 'module', 'm01-the-flow-path', 9, 'How does the inside leg convert volume to measured depth?', '["By walking the annulus rows from the shoe upward.", "Dividing by the inside capacity, because the inside has one capacity for the whole string.", "By interpolating the minimum-curvature trajectory, since the volume coordinate is measured along the hole rather than vertically.", "By subtracting the annulus volume first, since the inside leg occupies the second half of the volume coordinate."]'::jsonb, 1, 'The annulus leg needs the row walk because its capacity changes at the section boundary.'),
  ('cementing', 'intermediate', 'module', 'm01-the-flow-path', 10, 'Why does the annulus map subtract rather than add?', '["Because volume increases going UP the annulus, so a larger volume coordinate is a shallower depth.", "Because the annular capacity is negative by convention.", "Because the annulus is walked from surface downward while the volume is accumulated from the shoe upward, so the two oppose.", "Because the true vertical depth decreases upward and the map returns a true vertical depth rather than a measured one."]'::jsonb, 0, 'So the two ends of an interval swap: the smaller volume is the deeper depth.'),
  ('cementing', 'intermediate', 'module', 'm01-the-flow-path', 11, 'What does an annulus segment carry that an inside segment does not?', '["The true vertical depths of its two ends.", "The fluid density, since the inside segments are all the same fluid while the annulus holds several at once during the job.", "The bore and the capacity of the row it falls in, which the inside does not need because the inside is one size throughout.", "The effective bore and the capacity of its row, because the friction term needs both and they differ per row."]'::jsonb, 3, 'An inside segment needs neither, because the inside is one size.'),
  ('cementing', 'intermediate', 'module', 'm01-the-flow-path', 12, 'The engine rebuilds the intervals and both maps at every step. What does that buy?', '["Speed, since a rebuild is cheaper than an advance.", "The ability to change the pump rate between steps, which a state-carrying advance could not represent without restarting.", "No accumulation of rounding error, because nothing accumulates from one step to the next.", "Consistency with the volume sheet, since both are recomputed from the same geometry rather than from a cached result."]'::jsonb, 2, 'It is slower than advancing a state and it is correct by construction.'),
  ('cementing', 'intermediate', 'module', 'm01-the-flow-path', 13, 'At the last step the annulus segments are what?', '["The state just before the top plug is dropped.", "The finished cement column, which the engine reports as the annulus end state.", "The state at the moment the first cement front reaches the shoe, which is when the annular column starts to build up.", "An interpolation between the last two sampled volumes, since the exact end of the job falls between two grid points."]'::jsonb, 1, 'On the slant well that is mud to 900.5245622082865 m, spacer to 1200, lead to 1400 and tail to 3000.'),
  ('cementing', 'intermediate', 'module', 'm01-the-flow-path', 14, 'The top of the lead on the slant well is exactly 1200 m. What is that?', '["The target top of cement, which is the programme working as designed.", "The previous casing shoe, where the split was placed.", "The depth at which the spacer front happened to stop when the last of the displacement was pumped in behind it.", "An artefact of the sixty one step grid, since the exact top falls between two samples and is reported at the nearer one."]'::jsonb, 0, 'And the top of the tail is exactly the previous shoe at 1400, because that is where the split was put.'),
  ('cementing', 'intermediate', 'module', 'm01-the-flow-path', 15, 'Where would plug flow be a poor model?', '["On a long annulus, where the errors accumulate.", "On a job with more than two slurries, since each additional interface adds a mixing zone the model does not represent.", "On a short interval, where a thirty metre mixing zone is a large fraction of the column.", "On a horizontal well, since the interfaces in a lateral are much longer on the low side than on the high side of the hole."]'::jsonb, 2, 'This course''s jobs have 1600 m of open hole annulus, so the interface error is well under a percent.'),
  ('cementing', 'intermediate', 'module', 'm02-the-u-tube', 1, 'Write down the placement pressure calculation.', '["The annulus head less the inside head, plus friction.", "The maximum of zero and the annulus head plus friction less the inside head.", "The sum of the annulus head, the friction and the inside head, since all three oppose the pumps during a displacement.", "The friction alone, since the two hydrostatic columns cancel once the same fluid is on both sides of the flow path."]'::jsonb, 1, 'Three terms and a floor at zero, and everything in the module is what each term is made of.'),
  ('cementing', 'intermediate', 'module', 'm02-the-u-tube', 2, 'Which of the three terms HELPS the pumps?', '["The inside head, because a dense column on the pump side of a U is a siphon.", "The friction, which is recovered at the outlet.", "The annulus head, since the fluid standing in the annulus is what pushes the returns out at surface without pump assistance.", "None of them, since all three are resistances that the pumps have to overcome during every phase of the job."]'::jsonb, 0, 'Every pascal of it is a pascal the pumps do not have to supply.'),
  ('cementing', 'intermediate', 'module', 'm02-the-u-tube', 3, 'Why is cementing different from ordinary circulation in this respect?', '["Because circulation is at a much higher rate.", "Because the annulus is open to the atmosphere during a cement job, and closed during circulation through the choke manifold.", "In circulation the same fluid is on both sides so the heads cancel, and a cement job is designed to make them differ.", "In circulation the two columns are the same density and their heads cancel exactly; in cementing they deliberately are not."]'::jsonb, 3, 'That is the whole content of the word U-tube.'),
  ('cementing', 'intermediate', 'module', 'm02-the-u-tube', 4, 'What does the engine keep alongside the floored pump pressure?', '["The friction term, reported separately per leg.", "The two hydrostatic heads separately, so a reader can see which of the two moved between one step and the next.", "The raw U-tube value, which is negative where the column falls on its own.", "The rate at which the column falls during a free-fall period, computed from the friction of the falling fluid."]'::jsonb, 2, 'Where the raw value is positive the two are the same number.'),
  ('cementing', 'intermediate', 'module', 'm02-the-u-tube', 5, 'The slant well''s job starts at 5517762.999844827 Pa with mud on both sides. What is that number?', '["The hydrostatic head of the annular column.", "The friction of circulating the whole path at the pump rate, because the two heads cancel exactly.", "The difference between the annular and inside heads at the start, since the annulus runs only to the shoe and the inside runs deeper.", "The pressure needed to burst the bottom plug at the float collar, which is the first event of the job."]'::jsonb, 1, 'Both columns are the same fluid at the same true vertical depths, so the heads are equal.'),
  ('cementing', 'intermediate', 'module', 'm02-the-u-tube', 6, 'How does the engine compute a hydrostatic head?', '["Summing, over the segments, the density times gravity times the difference of the true vertical depths of the two ends.", "Density times gravity times the measured depth.", "The average density of the whole column times gravity times the true vertical depth of the deepest point of that leg.", "By integrating the density along the trajectory, using the minimum-curvature dogleg at each station to weight the interval."]'::jsonb, 0, 'It calls the trajectory interpolation for each segment end rather than using an average inclination.'),
  ('cementing', 'intermediate', 'module', 'm02-the-u-tube', 7, 'The horizontal well''s true vertical depth is the same at 2000 m and 2800 m of measured depth. What follows?', '["Its annular volume over that interval is also zero.", "The cement in that interval exerts no pressure on the formation, so the equivalent circulating density there cannot be computed.", "Eight hundred metres of cement column weighing nothing, which is why its float differential is a tenth of the slant well''s.", "The last 800 m of that well contributes exactly zero hydrostatic head, on either side of the U."]'::jsonb, 3, 'A cement column 800 m long, weighing nothing.'),
  ('cementing', 'intermediate', 'module', 'm02-the-u-tube', 8, 'Where does the friction term come from?', '["A Herschel-Bulkley model implemented in this engine.", "A single Fanning friction factor applied to the whole path, computed from the average velocity and the average density.", "The loss kernel of the Drilling Fluids and Hydraulics engine, called once per segment.", "A published correlation for cement slurries, which differs from the drilling fluid one because slurries are more shear thinning."]'::jsonb, 2, 'A cementing engine that reimplemented pipe friction would be a second place for the same physics to be slightly different.'),
  ('cementing', 'intermediate', 'module', 'm02-the-u-tube', 9, 'What does the friction term do with a fluid that has no rheology?', '["Assumes water and computes a Newtonian loss.", "Nothing. It contributes zero friction, which the vertical fixture uses deliberately.", "Throws, because a fluid without a rheological model cannot be placed and the caller has to supply one for each of them.", "Uses the rheology of the fluid ahead of it, on the argument that the two are in contact and will have partly mixed."]'::jsonb, 1, 'It is also a silent trap on a real run: forget the rheology on one fluid and its friction quietly disappears.'),
  ('cementing', 'intermediate', 'module', 'm02-the-u-tube', 10, 'What velocity does the friction term use in an annulus segment?', '["The pump rate divided by that ROW''s capacity, so it changes at the section boundary.", "The pump rate divided by the inside capacity.", "The pump rate divided by the average of the two annular capacities, weighted by the length of each of the two rows.", "The volumetric rate divided by the effective bore area, which is the annulus plus the casing cross-section together."]'::jsonb, 0, 'On this well that is 1.4973771889585683 m/s cased and 1.476222714457212 in the washed-out open hole.'),
  ('cementing', 'intermediate', 'module', 'm02-the-u-tube', 11, 'A bigger excess makes the annular friction what?', '["Larger, because the annulus is longer.", "Unchanged, since the excess affects the volume calculation and the friction is computed on the nominal bore of the hole.", "Smaller, because a wider annulus means a lower velocity at the same rate and a larger hydraulic gap as well.", "Smaller, because it inflates the capacity and therefore lowers the velocity."]'::jsonb, 3, 'Which is why the washed-out open hole on this well is the slower of its two annuli.'),
  ('cementing', 'intermediate', 'module', 'm02-the-u-tube', 12, 'What is the free-fall condition?', '["The pump pressure reaching zero at the surface gauge.", "The annular velocity falling below the minimum needed to keep the fluid interfaces stable against gravity segregation.", "The raw U-tube value going negative, which means the inside column outweighs everything on the other side.", "The cement front reaching the shoe before the displacement has entered, which leaves the casing partly empty above it."]'::jsonb, 2, 'Nothing at surface is holding it up and it falls under its own weight.'),
  ('cementing', 'intermediate', 'module', 'm02-the-u-tube', 13, 'Which of these does free fall NOT cause?', '["A loss of control over the pump rate.", "A change in the total volume that has to be pumped to bump the plug.", "A divergence between the pumped and returned volumes, which looks exactly like losing circulation to the formation.", "A spike in the annular velocity, at exactly the moment nobody was watching for a high circulating density."]'::jsonb, 1, 'The displacement volume is a geometric quantity and free fall does not change it.'),
  ('cementing', 'intermediate', 'module', 'm02-the-u-tube', 14, 'Why is the free-fall threshold minus one pascal rather than zero?', '["Because the difference of two ten megapascal sums in double precision is not exactly zero when the columns balance.", "Because a one pascal deficit is not worth reporting.", "Because the float equipment holds about one pascal of residue, which the engine treats as a floor on the balance calculation.", "Because the engine''s segment ordering is not deterministic, so a strict comparison would give different answers on each run."]'::jsonb, 0, 'Half the time the rounding is negative, and a strict comparison would report free fall at random steps.'),
  ('cementing', 'intermediate', 'module', 'm02-the-u-tube', 15, 'The deadband is one pascal and the worst real deficit is minus 104394.27505085245. What is the margin?', '["About one order of magnitude, which is tight.", "About two orders of magnitude, which is enough to distinguish a real event but not enough to be sure about a marginal one.", "About five orders of magnitude of daylight on the physical side, and nine on the rounding side.", "There is no margin, since the deadband was chosen to sit just below the smallest deficit the two wells actually produce."]'::jsonb, 2, 'The threshold cannot mask a real event and cannot admit a spurious one.'),
  ('cementing', 'intermediate', 'module', 'm03-the-job-over-time', 1, 'What does each row of the placement series carry?', '["A time, a pressure and a top of cement.", "A pumped volume, a pump pressure, the raw U-tube value, a free-fall flag and two circulating densities.", "A pumped volume and the positions of every fluid front, from which the pressures can be recomputed by the caller if needed.", "A pumped volume, the annulus head, the inside head and the friction, reported separately so their sum can be checked."]'::jsonb, 1, 'Sixty one rows, evenly spaced in pumped volume from zero to the total.'),
  ('cementing', 'intermediate', 'module', 'm03-the-job-over-time', 2, 'The slant well''s pressure goes 5.52 MPa, down to 0.59, up to 13.71. What are the three phases?', '["Cement down the inside, cement turning the corner at the shoe, and displacement pushing it up the annulus.", "Mixing, pumping and bumping the plug.", "Spacer, lead and tail, since each fluid has a different density and the pressure steps as each of them enters the annulus.", "Circulation, displacement and the pressure test that follows the plug bump once the floats have been confirmed to hold."]'::jsonb, 0, 'Down by a factor of nine and then up by a factor of twenty three.'),
  ('cementing', 'intermediate', 'module', 'm03-the-job-over-time', 3, 'Why must the pressure fall before it rises?', '["Because the pump rate is reduced at the start.", "Because the spacer is lighter than the cement behind it, so the column entering the well is initially lighter than the mud.", "Because the first cement into the casing increases the inside head and the annulus is untouched, so the balance falls.", "Because cement going into the casing raises the inside head, which subtracts, before any of it reaches the annulus."]'::jsonb, 3, 'It is a property of the geometry rather than of these numbers.'),
  ('cementing', 'intermediate', 'module', 'm03-the-job-over-time', 4, 'A cement job''s surface pressure does NOT fall in the first third. What does that suggest?', '["That the cement is heavier than designed.", "That the annulus is taking fluid, so the annular column is not building and the U-tube stays at its starting value.", "A stuck plug, a mixing failure, or a geometry that is not what you thought.", "That the pump rate has been increased, which raises the friction term enough to mask the fall in the hydrostatic balance."]'::jsonb, 2, 'The fall is not optional, which is what makes it a good diagnostic.'),
  ('cementing', 'intermediate', 'module', 'm03-the-job-over-time', 5, 'The minimum on the slant well is at 28.826862304761338 cubic metres. Where is the cement then?', '["Just reaching the shoe, which is why the pressure turns.", "Still going down the inside, because the inside volume alone is 58.13230334930856 cubic metres.", "Already 300 m up the annulus, which is where the marginal effect of the next cubic metre changes sign for the whole column.", "At the float collar, since the bottom plug bursts there and the pressure minimum coincides with that event."]'::jsonb, 1, 'The turn is where the marginal effect of the next cubic metre changes sign, not where a front reaches the shoe.'),
  ('cementing', 'intermediate', 'module', 'm03-the-job-over-time', 6, 'How is the ECD at the previous shoe computed?', '["The head plus friction of the annulus ABOVE that shoe, divided by gravity times its true vertical depth.", "The whole annular head divided by the shoe TVD.", "The pump pressure plus the annular head at that depth, converted to a density by dividing by the measured depth of the shoe.", "The head of the annulus below the shoe, since that is the column standing on the formation at the shoe depth."]'::jsonb, 0, 'Only the part above the shoe is counted, because that is what loads the formation there.'),
  ('cementing', 'intermediate', 'module', 'm03-the-job-over-time', 7, 'Why is the ECD at the previous shoe flat for two thirds of the job?', '["Because the engine only recomputes it at the end.", "Because the friction is constant at constant rate, and the head above the shoe is the same mud column throughout the job.", "Because the annulus above the previous shoe holds only mud until cement or spacer crosses it on the way up.", "Because nothing above that shoe has changed: the annulus there is still full of the original mud."]'::jsonb, 3, 'It moves only when a different fluid crosses the previous shoe depth.'),
  ('cementing', 'intermediate', 'module', 'm03-the-job-over-time', 8, 'When does the peak ECD at the previous shoe occur?', '["At the pressure minimum, a third of the way through.", "When the first cement front reaches the previous shoe, since that is the largest single density step the annulus ever sees.", "At the last step, on all four of this course''s runs.", "At the start, when the whole annulus is still full of the heaviest fluid the well contained before the job began."]'::jsonb, 2, 'The most dangerous moment of a cement job for the shoe above is the moment the plug bumps.'),
  ('cementing', 'intermediate', 'module', 'm03-the-job-over-time', 9, 'The horizontal well''s ECD at the CASING shoe starts at 1837.9218199066345 kg/m3. Why so high?', '["Because the cement is heavier on that well.", "Because it divides the friction of a 1600 m lateral by only 1214.859173174059 m of true vertical depth.", "Because the annulus is narrower on a horizontal well, so the same rate gives a higher velocity and much more friction.", "Because the previous shoe is shallower, so the same annular head converts to a higher equivalent density at that depth."]'::jsonb, 1, 'The friction is generated over the lateral and the vertical depth is not.'),
  ('cementing', 'intermediate', 'module', 'm03-the-job-over-time', 10, 'What does that tell you about ECD as a unit on a horizontal well?', '["It divides a quantity generated along the hole by a quantity measured vertically, and the two stop being proportional.", "That it should be quoted at the previous shoe instead.", "That it is a poor unit for cement and a good one for drilling, since drilling circulates a single fluid at a constant density.", "That it must be recomputed at each survey station rather than at the shoe, to account for the changing inclination."]'::jsonb, 0, 'The intuition attached to ECD comes from vertical wells.'),
  ('cementing', 'intermediate', 'module', 'm03-the-job-over-time', 11, 'Which of the two circulating densities is a limit and which a diagnostic?', '["The casing shoe one is the limit, being the deepest.", "Both are limits, and a job has to satisfy the fracture gradient at every exposed formation along the whole open hole.", "The one at the previous shoe is the limit, and the one at the casing shoe is reported so that a reader can compare them.", "The previous shoe one is the limit, because that is where the exposed formation is weakest."]'::jsonb, 3, 'The formation at the casing shoe is about to be cased off.'),
  ('cementing', 'intermediate', 'module', 'm03-the-job-over-time', 12, 'The float differential is computed at which step and with what in it?', '["At the first step, before any cement has moved.", "At the step where the annular head is greatest, which is the last one, including the friction at the design pump rate.", "At the last step, with no friction, because the pumps have stopped.", "At every step, and the reported value is the largest of the sixty one, which is what the floats have to hold at worst."]'::jsonb, 2, 'It is the annulus head less the inside head at the end of the job.'),
  ('cementing', 'intermediate', 'module', 'm03-the-job-over-time', 13, 'The slant well''s float differential is ten times the horizontal well''s. Why?', '["The slant well has more cement in the annulus.", "True vertical depth: 2507.9196993011733 m against 1214.859173174059, on the same measured column.", "The slant well''s displacement fluid is lighter, so the inside head at the end of the job is smaller and the difference larger.", "The horizontal well''s floats are rated lower, so the engine reports a differential capped at what they can hold."]'::jsonb, 1, 'Less vertical height means less head on both sides, and the difference shrinks with it.'),
  ('cementing', 'intermediate', 'module', 'm03-the-job-over-time', 14, 'What does a NEGATIVE float differential mean?', '["The inside is heavier than the annulus, so the floats have to hold a reverse U-tube.", "The annulus is heavier and the floats hold normally.", "The cement has not reached the annulus, so there is no annular column to compare against the fluid inside the casing.", "The job is under-displaced, since a negative differential can only arise if cement is still inside the casing at the end."]'::jsonb, 0, 'A one-way valve designed to hold flow in one direction is being asked to hold it in the other.'),
  ('cementing', 'intermediate', 'module', 'm03-the-job-over-time', 15, 'On the slant well the end pump pressure is 13712451.13169735 and the float differential 5714040.2699640095. What is the rest?', '["The annular head, which is not in the differential.", "The inside head, which the float differential subtracts and the pump pressure adds, so it appears in one and not the other.", "Friction at the last step, which is why the bump pressure falls when the rate is reduced for the final few cubic metres.", "Friction at the last step, 7998410.86173334 Pa, which is more than half the plug bump pressure."]'::jsonb, 3, 'The vertical fixture has no rheology at all, so its two numbers are equal exactly.'),
  ('cementing', 'intermediate', 'module', 'm04-two-programmes-one-well', 1, 'What do the neat and the two-slurry programmes have in common?', '["The same number of fluids pumped.", "The same total slurry volume, the same target and the same achieved top of cement.", "The same density profile in the annulus, since both place the same mass of cement between the same two depths in the hole.", "The same pump pressure history, since the pressures depend on the total slurry rather than on how it is split up."]'::jsonb, 1, 'Both reach 1200 m on the slant well and 1000 on the horizontal one, to a rounding error.'),
  ('cementing', 'intermediate', 'module', 'm04-two-programmes-one-well', 2, 'What differs between them?', '["The density profile of the column, and therefore every pressure in the job.", "The total volume that has to be pumped.", "The achieved top of cement, since the neat programme has no spacer and therefore no buffer above the cement column.", "The job time, since the neat programme pumps one fewer fluid and therefore takes fewer changeovers at surface."]'::jsonb, 0, 'The neat programme is worse on every measure on both wells.'),
  ('cementing', 'intermediate', 'module', 'm04-two-programmes-one-well', 3, 'Where does the difference between the two programmes physically sit?', '["In the shoe track, which the neat job fills with tail.", "In the whole annular column, since the neat programme places 1900 kg/m3 cement everywhere the two-slurry one places two densities.", "In 200 m of annulus above the previous shoe, where the two-slurry job has lead at 1560 and the neat job has tail at 1900.", "In 200 m of annulus between the top of cement and the previous shoe, plus the spacer above it."]'::jsonb, 3, 'Which is 340 kg/m3 over 200 m of measured depth, plus the spacer''s contribution.'),
  ('cementing', 'intermediate', 'module', 'm04-two-programmes-one-well', 4, 'What does the lead slurry buy on the horizontal well, most importantly?', '["About eleven percent of the cement cost.", "A lower achieved top of cement, since the lighter lead occupies more annulus per unit mass than the tail slurry would.", "The difference between free falling and not, on the same volumes at the same rate.", "A higher float differential, which means the floats have more to hold and are therefore more thoroughly proved by the job."]'::jsonb, 2, 'It also buys 62 kg/m3 of peak circulating density at the previous shoe.'),
  ('cementing', 'intermediate', 'module', 'm04-two-programmes-one-well', 5, 'The lead is in the ANNULUS at the moment that matters, and it makes the annulus heavier. How does that help?', '["It does not; the help comes from the inside column.", "By adding to the side of the U that was losing, rather than subtracting from the side that was winning.", "By reducing the friction, since a lighter slurry has a lower yield stress and therefore a smaller annular pressure loss.", "By raising the achieved top of cement, so the annular column is taller and its head is larger at the moment of the worst balance."]'::jsonb, 1, 'A lead heavier than the mud but lighter than the tail does both jobs at once.'),
  ('cementing', 'intermediate', 'module', 'm04-two-programmes-one-well', 6, 'What does the engine''s density hierarchy check skip, and why?', '["The displacement, because it is deliberately the lightest fluid in the job and flagging it would be noise on every run.", "The spacer, which is a buffer rather than a slurry.", "The mud in the hole, since it is not a pumped fluid and therefore has nothing ahead of it in the chain to be compared against.", "The lead, since the whole point of a lead slurry is to be lighter than the tail behind it in the pumping sequence."]'::jsonb, 0, 'On this course''s programmes the chain 1440, 1500, 1560, 1900 is monotone and the check never fires.'),
  ('cementing', 'intermediate', 'module', 'm04-two-programmes-one-well', 7, 'Why does pumping FASTER cure free fall?', '["Because a faster job gives the cement less time to fall.", "Because the pump delivers more volume per unit time than the column can fall through, so the interface cannot separate.", "Because friction rises with rate and appears on the annulus side of the U-tube balance, supporting the column.", "Because friction rises with the rate and friction is what holds the annular column up."]'::jsonb, 3, 'And the same friction raises the circulating density at the shoe above.'),
  ('cementing', 'intermediate', 'module', 'm04-two-programmes-one-well', 8, 'The two rate constraints act on the same knob. In which directions?', '["Both want the rate low, and mud removal wants it high.", "Free fall wants it low, since a slower job gives the column time to settle, and the fracture limit wants it high.", "Free fall wants the rate high and the fracture limit at the previous shoe wants it low.", "Both want it high, and the only thing wanting it low is the mixing rate at surface, which this engine does not model."]'::jsonb, 2, 'The same friction term appears in both, with opposite signs on what it does for you.'),
  ('cementing', 'intermediate', 'module', 'm04-two-programmes-one-well', 9, 'Why bisect for the rate edges rather than sweep?', '["Because a sweep would take too long to compute.", "Because the answer is going to be quoted, and a sweep gives an interval whose width is the step size.", "Because the relationship between rate and circulating density is nonlinear, so interpolating between sweep points is inaccurate.", "Because the free-fall flag is discrete, so a sweep would miss the transition entirely unless the step happened to straddle it."]'::jsonb, 1, 'Only a bisected answer can be checked by somebody else or compared against another programme.'),
  ('cementing', 'intermediate', 'module', 'm04-two-programmes-one-well', 10, 'On the slant well''s neat programme the window at 1700 is 0.0001944956449708296 wide. What does that mean?', '["It is open and useless: a fifth of a percent of the rate is not a band anybody can hold a pump inside.", "It is closed, since a positive width means no rate works.", "It is comfortably open, since any width above zero means there exists a rate satisfying both constraints simultaneously.", "It cannot be interpreted, because a window narrower than the bisection tolerance is inside the numerical noise of the search."]'::jsonb, 0, 'A window that is open but narrow is a warning in itself.'),
  ('cementing', 'intermediate', 'module', 'm04-two-programmes-one-well', 11, 'A window comes out negative. How should that be read?', '["That the calculation failed and returned a null edge.", "That the job free falls at every rate, so the ECD edge is meaningless and only the free-fall edge should be reported.", "That the two constraints cross, so no pump rate satisfies both, and the programme rather than the rate has to change.", "Every rate slow enough to protect the shoe free falls, and every rate fast enough to prevent free fall fractures it."]'::jsonb, 3, 'Switch to a lead and tail and the window opens to 0.00539927840496492.'),
  ('cementing', 'intermediate', 'module', 'm04-two-programmes-one-well', 12, 'Adding a lead slurry moved BOTH rate edges. Which way, and why?', '["Both up, since the annular column is heavier throughout.", "The free-fall edge up and the ECD edge down, since a lighter column needs more friction to hold it and generates more of it.", "The free-fall edge down and the ECD edge up, because the annulus is heavier and the head at the previous shoe is lower.", "Only the ECD edge moved, since the free-fall condition depends on the inside column and the lead is in the annulus."]'::jsonb, 2, 'One change to the programme, two edges, both improved.'),
  ('cementing', 'intermediate', 'module', 'm04-two-programmes-one-well', 13, 'The window closure depends on three things. Which?', '["The well, the pump rate and the excess factor.", "The well, the fluid programme and the assumed leak-off value at the previous shoe.", "The fluid programme, the pump rate and the number of steps in the placement grid, which decides whether a dip is sampled.", "The well, the mud weight and the total depth, since those three set the hydrostatic balance at the moment of the worst step."]'::jsonb, 1, 'Quote it without all three and it is not reproducible.'),
  ('cementing', 'intermediate', 'module', 'm04-two-programmes-one-well', 14, 'What are the four remedies for a closed rate window?', '["A lighter or longer lead, a lower top of cement, a staged job, or accepting the free fall and managing it.", "A faster pump, a slower pump, a bigger pump or a smaller one.", "A heavier spacer, a lighter displacement fluid, a deeper float collar or a longer shoe track to reduce the annular column.", "A different excess assumption, a different slurry yield, a different casing size or a different previous shoe depth."]'::jsonb, 0, 'Raising the rate is not one of them, because the window closed means no rate works.'),
  ('cementing', 'intermediate', 'module', 'm04-two-programmes-one-well', 15, 'In what order should a cement programme be decided?', '["Rate first, then volumes, then the density profile.", "The rate first, since it is what the pumping equipment constrains, and then the programme is designed to fit inside that rate.", "The top of cement, then the fluid programme, then the rate window, and the rate last of the four rather than first.", "Where the cement must reach, then the density profile, then whether a window exists, then the rate."]'::jsonb, 3, 'The rate is the last of the four, and the density profile is where free fall is actually decided.'),
  ('cementing', 'intermediate', 'module', 'm05-reading-a-placement-result', 1, 'How does the engine find the achieved top of cement?', '["The depth the volume sheet computed it should reach.", "The shallowest depth reached by any annulus segment whose fluid kind is lead or tail, at the last step.", "The shallowest annulus segment that is not the original mud, which includes the spacer sitting on top of the cement column.", "The depth at which the density of the annular column first exceeds the mud density, walking upward from the shoe."]'::jsonb, 1, 'The spacer is deliberately not counted: a top that included it would be a lie of exactly the spacer''s length.'),
  ('cementing', 'intermediate', 'module', 'm05-reading-a-placement-result', 2, 'Both wells and both programmes hit their target exactly. What does that prove?', '["That the code is self-consistent, since the volumes were computed from the same geometry the placement runs in.", "That the volume sheet has been validated against reality.", "That the excess factor was chosen correctly, since a wrong excess would have shown up as a missed top of cement.", "That plug flow is a good model, since a mixing model would have smeared the top of cement over tens of metres."]'::jsonb, 0, 'It is a consistency check on the code, not on the world.'),
  ('cementing', 'intermediate', 'module', 'm05-reading-a-placement-result', 3, 'What is the achieved-top warning tolerance, and what is notable about it?', '["Five percent of the annular slurry volume.", "One annulus row, so the warning fires when the cement top lands in a different row from the one the target was in.", "Thirty metres, which is roughly the length of a mixing zone, so a smaller disagreement is inside the model''s own resolution.", "Thirty metres, hard coded with no comment, which is about the length of a real mixing zone."]'::jsonb, 3, 'It is a judgement, it is reasonable, and it is the kind of hard-coded number worth noticing in an engine you rely on.'),
  ('cementing', 'intermediate', 'module', 'm05-reading-a-placement-result', 4, 'In the FIELD, what makes the achieved and target tops disagree most often?', '["A volume error in the displacement calculation.", "Intermixing at the interfaces, which spreads the top of cement over tens of metres and makes the reported single depth meaningless.", "An excess mismatch: ordered at 15 percent into a hole that washed out to 30.", "The plug failing to bump, which leaves the displacement short and the whole column lower than the design intended."]'::jsonb, 2, 'Inside the model the two cannot disagree, because both read the same excess.'),
  ('cementing', 'intermediate', 'module', 'm05-reading-a-placement-result', 5, 'When is the achieved top of cement reported as null?', '["When the target was not supplied by the caller.", "When no cement reached the annulus at all, which the engine warns about separately.", "When the cement is still inside the casing at the last step, which happens if the displacement volume was under-specified.", "When two annulus segments carry cement at different depths, so there is no single shallowest cement depth to report."]'::jsonb, 1, 'It happens if the slurry volume is smaller than the shoe track plus the casing bore.'),
  ('cementing', 'intermediate', 'module', 'm05-reading-a-placement-result', 6, 'Which warning is only raised if an extra input is supplied?', '["The fracture one, which needs an equivalent mud weight at the previous shoe to compare against.", "The free-fall one, which needs a rate.", "The achieved top of cement one, which needs a target top and is silent if the caller only asks for a placement.", "The density hierarchy one, which needs the mud in the hole to be supplied alongside the pumped fluid sequence."]'::jsonb, 0, 'No limit, no warning, and the peak is still reported for the reader to compare.'),
  ('cementing', 'intermediate', 'module', 'm05-reading-a-placement-result', 7, 'What do all six warnings have in common?', '["Each carries a severity level and a colour.", "Each is raised at a specific step in the series, so the reader can see at what pumped volume the condition first occurred.", "Each names the numbers involved rather than reporting a code, which is why they are sentences rather than flags.", "Each names the quantity that triggered it and, where two numbers are compared, both of them."]'::jsonb, 3, 'None of them is a severity, a score or a colour.'),
  ('cementing', 'intermediate', 'module', 'm05-reading-a-placement-result', 8, 'What does the absence of any warning mean?', '["That the job will place cement as designed.", "That the volumes reconcile and the top of cement was reached, which are the two things the warnings actually test for.", "That none of six specific conditions occurred, and nothing at all about whether the job is good.", "That every check the engine can make has passed, so the remaining risk is in the chemistry rather than the placement."]'::jsonb, 2, 'There is no warning for a bad excess, a slurry that will not set, a mud channel, contamination or a plug that does not bump.'),
  ('cementing', 'intermediate', 'module', 'm05-reading-a-placement-result', 9, 'How many warnings do the four runs in this course produce?', '["None, since all four runs place cement as designed.", "One, the free-fall warning on the horizontal well''s neat programme.", "Two, the free-fall warning on the horizontal neat run and the fracture warning on both of the neat runs at the design limit.", "Four, one per run, since each of the four exceeds at least one of the six conditions the engine checks for."]'::jsonb, 1, 'The slant well produces none on either programme.'),
  ('cementing', 'intermediate', 'module', 'm05-reading-a-placement-result', 10, 'Which two omissions from the simulation are the biggest levers a cementer has?', '["Mixing, which the spacer exists to control, and casing movement.", "Temperature and losses to the formation.", "The transient free-fall rate and the float equipment pressure drop, which together determine what the crew actually see.", "Gas migration after placement and the thickening time, which are the two things that decide whether the cement sets at all."]'::jsonb, 0, 'A job simulated here is a job with the casing sitting still and sharp interfaces.'),
  ('cementing', 'intermediate', 'module', 'm05-reading-a-placement-result', 11, 'What is unknown about a job during a free-fall period?', '["Only the surface pressure, which reads zero.", "Nothing beyond the surface pressure, since the volumes are still being pumped and the fronts still advance with them.", "The rate is unknown, and every quantity computed from it is unknown with it, so that stretch of the job has no numbers.", "The rate, and therefore the friction, the circulating density and the annular velocity as well."]'::jsonb, 3, 'The engine reports the deficit and refuses to compute the fall rate.'),
  ('cementing', 'intermediate', 'module', 'm05-reading-a-placement-result', 12, 'The placement grid is 61 points, evenly spaced in what?', '["Time, from the start of the job to the plug bump.", "Measured depth of the leading front, so that the resolution is finer where the annular capacity is smaller and the fronts move faster.", "Pumped volume, not time, which are the same thing only at a constant rate.", "Pumped volume, and also refined near the section boundaries where the capacity changes and the fronts change speed."]'::jsonb, 2, 'At a varying rate the two would not be the same.'),
  ('cementing', 'intermediate', 'module', 'm05-reading-a-placement-result', 13, 'The horizontal well''s neat programme free falls at ONE of 61 steps. What should you do about that?', '["Discard the finding as a sampling artefact.", "Rerun at a finer grid, which is one line and eighty milliseconds.", "Accept it, since a single step in free fall is inside the resolution of the grid and therefore not worth acting on.", "Report it as a free-fall period of one sixty-first of the job, which is the resolution the default grid provides."]'::jsonb, 1, 'At 600 steps the dip spans sixteen samples and the deficit is six percent deeper than the coarse grid found.'),
  ('cementing', 'intermediate', 'module', 'm05-reading-a-placement-result', 14, 'What did the finer grid change about the free-fall finding?', '["Nothing about whether it happens, and six percent about how deep the deficit is.", "It showed the dip was a sampling artefact.", "It moved the dip to a different pumped volume, which means the coarse grid had located it in the wrong part of the job.", "It found two dips rather than one, since the coarse grid had merged two separate free-fall periods into a single sample."]'::jsonb, 0, 'The finding survives and one of its digits does not, and neither is visible from a single run.'),
  ('cementing', 'intermediate', 'module', 'm05-reading-a-placement-result', 15, 'Which three outputs are NOT sampled quantities?', '["The two circulating densities and the free-fall flag.", "The achieved top of cement, the peak circulating density and the free-fall flag, since all three scan the whole series.", "The end pump pressure, the float differential and the annulus end state, all from the final evaluation.", "The pump pressure, the U-tube value and the annular velocity, which are computed once and held constant through the job."]'::jsonb, 2, 'The final evaluation is at exactly the full pumped volume, which is the end of the job.'),
  ('cementing', 'intermediate', 'module', 'm06-the-professional-reading', 1, 'Summarising the Professional tier: what kind of calculation is placement?', '["A transient two-phase flow simulation along the wellbore.", "Volume bookkeeping on a single coordinate, producing three terms and a floor at zero.", "A time-stepped displacement calculation, advancing the fluid fronts by the pumped rate at each of the sixty one intervals.", "A pressure balance at the shoe, computed once at the end of the job and compared against the fracture gradient."]'::jsonb, 1, 'The whole pressure calculation is one line.'),
  ('cementing', 'intermediate', 'module', 'm06-the-professional-reading', 2, 'A capstone changes the casing, the hole, the fluids and the rheologies. What stays the same?', '["The method: fronts on a volume coordinate, three terms, and two bisected edges.", "The two circulating densities, being properties of the well.", "The free-fall behaviour, since it depends on the density hierarchy and every capstone keeps the mud, spacer, lead, tail order.", "The friction, since the loss kernel is the same one and the rheologies only change the fluid densities it is applied to."]'::jsonb, 0, 'Nothing about the procedure depends on the numbers it is given.'),
  ('cementing', 'intermediate', 'module', 'm06-the-professional-reading', 3, 'A capstone asks for the ECD at the previous shoe. Which shoe is that on a job cased to 350 m?', '["The casing shoe, being the deepest point of the string.", "Whichever of the two has the lower fracture gradient, which the engine determines from the leak-off values supplied to it.", "The 350 m shoe, since that is the deepest CASED section boundary and it is the shallowest exposed formation in the hole.", "The 350 m one, not the casing shoe the job is cementing to."]'::jsonb, 3, 'The two are very different numbers and the engine reports both.'),
  ('cementing', 'intermediate', 'module', 'm06-the-professional-reading', 4, 'A capstone rate window comes out positive when the design says it should be negative. What is likely wrong?', '["The ECD edge, which needs the fracture limit.", "The order of subtraction, since the window is the free-fall edge less the ECD one rather than the other way round.", "The free-fall edge, which is a bisection and is easy to get wrong by using the wrong bracket or the wrong predicate.", "The pump rate, since the window is computed at the design rate and a different rate gives a different window entirely."]'::jsonb, 2, 'The ECD edge is usually the easier of the two, because the design rate is normally inside that constraint.'),
  ('cementing', 'intermediate', 'module', 'm06-the-professional-reading', 5, 'A capstone free-fall edge is five times the design rate. Is that an error?', '["Yes, since a free-fall edge above the design rate is impossible.", "No. Large-diameter casing in a wide annulus free falls at every rate anybody could actually pump.", "Yes, because the bisection bracket must have been set too high, and the true edge is always within a factor of two of the design rate.", "No, but it means the ECD edge is meaningless, since a job that free falls has no well-defined circulating density at all."]'::jsonb, 1, 'It is what wide annuli do, and the honest reading is that the job free falls and has to be managed rather than avoided.'),
  ('cementing', 'intermediate', 'module', 'm06-the-professional-reading', 6, 'Which free check catches a sign error in a capstone rate window?', '["The ECD edge less the free-fall edge must equal the reported width, exactly.", "The window must be positive.", "The peak circulating density at the design rate must lie between the two edges, since both are rates and it is a density.", "The free-fall edge must be smaller than the ECD edge, which is what having an open window means in the first place."]'::jsonb, 0, 'And on a job whose design rate is inside the ECD constraint, the ECD edge must exceed the design rate.'),
  ('cementing', 'intermediate', 'module', 'm06-the-professional-reading', 7, 'Four different Fann sets feed a capstone. What do they change?', '["The densities of the four fluids.", "The hydrostatic heads, since the Herschel-Bulkley yield stress contributes a static pressure the density alone does not carry.", "The friction term, and therefore both edges of the rate window, so reusing the lessons'' rheologies moves both of them.", "The friction, which is what both rate edges are made of."]'::jsonb, 3, 'Reusing the lessons'' rheologies would move both edges.'),
  ('cementing', 'intermediate', 'module', 'm06-the-professional-reading', 8, 'The end pump pressure must exceed the float differential. Why?', '["Because the annulus is always heavier at the end.", "Because the pump pressure is floored at zero and the float differential is not, so the pump pressure is the larger of the two.", "Because the difference between them is the friction at the last step, which is positive.", "Because the end pump pressure includes the plug bump spike, which the float differential is measured before."]'::jsonb, 2, 'On the vertical fixture, which has no rheology, the two are equal exactly.'),
  ('cementing', 'intermediate', 'module', 'm06-the-professional-reading', 9, 'You halve a capstone''s pump rate. Which reported number does NOT move?', '["The peak circulating density at the previous shoe.", "The float differential, because it is computed with the pumps stopped.", "The achieved top of cement, since the volumes are unchanged and the fronts end in the same places whatever the rate was.", "The end pump pressure, since it is dominated by the hydrostatic imbalance rather than by the friction at the last step."]'::jsonb, 1, 'The achieved top of cement also does not move, and neither does the volume sheet.'),
  ('cementing', 'intermediate', 'module', 'm06-the-professional-reading', 10, 'In one sentence, what is the Professional tier''s central result?', '["One knob, two constraints pulling opposite ways, and whether a window exists is a property of the programme.", "That the pump pressure falls before it rises on every job.", "That the equivalent circulating density at the previous shoe peaks at the plug bump, which is the most dangerous moment.", "That a lead slurry saves about eleven percent of the cement cost on a job of this length and geometry."]'::jsonb, 0, 'Not of the driller.'),
  ('cementing', 'intermediate', 'module', 'm06-the-professional-reading', 11, 'A Professional certificate in this course stands for what?', '["Designing a cement job from the reservoir up.", "Predicting the top of cement to within thirty metres on a well with a known caliper log over the open hole section.", "Producing a placement result and a standoff profile, which together decide whether the job will isolate the reservoir.", "Producing a placement history, a circulating density and a rate window, and saying whether the window exists."]'::jsonb, 3, 'Whether the mud got out of the way is the Expert tier and three things outside the course.'),
  ('cementing', 'intermediate', 'module', 'm06-the-professional-reading', 12, 'Every case in this tier is a placement. What does it never say?', '["Whether the volumes were ordered correctly.", "Whether the slurry will still be pumpable when it arrives, which needs a thickening time and a bottomhole temperature.", "Whether the cement isolated anything, because it has no term for where the casing is in the hole.", "Whether the plug bumped, since that is a field observation rather than something a simulation can predict in advance."]'::jsonb, 2, 'The whole tier would give identical numbers for a perfectly centred casing and one lying flat on the low side.'),
  ('cementing', 'intermediate', 'module', 'm06-the-professional-reading', 13, 'Which course supplies the loss kernel this tier imports?', '["Casing and Tubing Design, through the triaxial check.", "Drilling Fluids and Hydraulics, along with the rheology fits that feed it.", "Geomechanics, which computes the fracture gradient and therefore also the friction the circulating density is compared with.", "Torque, Drag and Casing Wear, which owns the string properties function the annular geometry is derived from."]'::jsonb, 1, 'A cementing engine that reimplemented pipe friction would be a second place for the same physics to be slightly different.'),
  ('cementing', 'intermediate', 'module', 'm06-the-professional-reading', 14, 'What is the transferable habit from the rate window result?', '["Bisect the edge and quote the number, because an interval cannot be checked by anybody else.", "Always pump at the lowest rate the window allows.", "Compute the window at three different fracture limits, so that the sensitivity to the leak-off assumption is visible.", "Report the free-fall edge only, since the circulating density edge depends on an assumption the engine cannot verify."]'::jsonb, 0, 'Eighty runs of a millisecond calculation, against a result nobody can reproduce.'),
  ('cementing', 'intermediate', 'module', 'm06-the-professional-reading', 15, 'What does the Expert tier add that this one has no term for?', '["The chemistry of the cement slurry.", "The transient rate during a free-fall period, which is the one stretch of the job this tier''s numbers do not cover.", "Where the casing is in the hole, which is what decides whether the mud on the narrow side is displaced.", "The intermixing at the fluid interfaces, which plug flow assumes away and which the standoff calculation restores."]'::jsonb, 2, 'It is the single biggest thing the placement cannot see.'),
  ('cementing', 'intermediate', 'final', null, 1, 'You are given a volume sheet and asked whether the job can be pumped. What else do you need?', '["The trajectory and the casing dimensions only.", "The fluid densities and rheologies, the mud in the hole, a pump rate and a fracture limit at the previous shoe.", "The slurry yield and the thickening time, since a job that cannot stay liquid for the duration cannot be pumped at all.", "Nothing further, since the volume sheet already contains the geometry and the placement follows from it directly."]'::jsonb, 1, 'The volume sheet has no densities in it and no rate.'),
  ('cementing', 'intermediate', 'final', null, 2, 'Why can a depth not parametrise the cementing flow path?', '["Because it is not single valued: at 1000 m you can be inside the casing or in the annulus.", "Because the annular capacity changes with depth.", "Because the true vertical depth is what the pressures need, and measured depth would have to be converted at every step.", "Because the fronts move at different speeds inside and outside, so a single depth coordinate could not track both at once."]'::jsonb, 0, 'Volume distinguishes them, and pumping one cubic metre advances every front by one.'),
  ('cementing', 'intermediate', 'final', null, 3, 'Pumping one cubic metre advances every fluid front by how much?', '["One cubic metre divided by the local capacity, in metres.", "One cubic metre of path coordinate for the leading front and less for the ones behind it, since some volume is compressed.", "Exactly one cubic metre of path coordinate, which is why the bookkeeping is exact and needs no time stepping at all.", "Exactly one cubic metre of path coordinate, wherever it is and whatever the local capacity."]'::jsonb, 3, 'That is the whole reason the calculation is arithmetic rather than a solve.'),
  ('cementing', 'intermediate', 'final', null, 4, 'What must be true of the interval lengths at every pumped volume?', '["They sum to the total pumped volume.", "They sum to the path length less the volume still inside the pumps, which shrinks as the job proceeds to the plug bump.", "They sum to the path length, always, by construction.", "Each is at most the volume of its own fluid, since a fluid cannot occupy more of the path than was pumped of it."]'::jsonb, 2, 'If that sum ever failed to close, a fluid would have been created or destroyed.'),
  ('cementing', 'intermediate', 'final', null, 5, 'Which leg of the flow path needs a row walk to convert volume to depth?', '["The inside, because it runs from surface downward.", "The annulus, because its capacity changes at the section boundary.", "Both, since each leg has its own capacity structure and the conversion is a different function on each of the two legs.", "Neither, since the conversion is a single division by the total path capacity divided by the total path length."]'::jsonb, 1, 'The inside is one capacity, so its conversion is a division.'),
  ('cementing', 'intermediate', 'final', null, 6, 'A colleague asks what the pumps actually have to supply. What do you tell them?', '["The maximum of zero and the annulus head plus friction less the inside head.", "The annulus head plus the inside head plus friction.", "The friction plus the difference between the annulus and inside heads, without a floor, since a negative pressure is meaningful.", "The annulus head less the inside head, floored at zero, with the friction reported separately as a second quantity."]'::jsonb, 0, 'The floor at zero is what separates the reported pump pressure from the raw U-tube value.'),
  ('cementing', 'intermediate', 'final', null, 7, 'One of the three terms carries a minus sign in front of it. Which, and why?', '["The friction, which is recovered at the annulus outlet.", "The annulus head, since a heavier annulus means the returns leave the well under their own pressure rather than being pushed.", "The inside head, since the two ends of the flow path are both at surface and a heavy column on one side siphons the other.", "The inside head, because the flow path is a U and a dense column on the pump side is a siphon."]'::jsonb, 3, 'Every pascal of it is a pascal the pumps do not have to supply.'),
  ('cementing', 'intermediate', 'final', null, 8, 'At the first step of a job with mud on both sides, what is the pump pressure?', '["Zero, since the two columns balance.", "The hydrostatic head of the annular column, since the inside column has not yet been displaced by any of the cement slurry.", "The friction of circulating the whole path, because the two heads cancel exactly.", "The difference between the annular and inside heads, which is non-zero because the two legs have different capacities."]'::jsonb, 2, 'On the slant well that is 5517762.999844827 Pa.'),
  ('cementing', 'intermediate', 'final', null, 9, 'How are the hydrostatic heads computed?', '["From the average density and the shoe true vertical depth.", "Segment by segment, on the exact minimum-curvature true vertical depths of each segment''s two ends.", "From the average inclination over each segment, multiplied by the segment length to give an equivalent vertical height.", "From the measured depth, since the fluid column follows the hole and its weight acts along the hole rather than vertically."]'::jsonb, 1, 'It calls the trajectory interpolation rather than using an average angle.'),
  ('cementing', 'intermediate', 'final', null, 10, 'The horizontal well has 800 m of hole with no change in true vertical depth. What does it contribute?', '["Exactly zero hydrostatic head, on either side of the U.", "A head proportional to its measured length.", "A head equal to the fluid density times gravity times the length, since the fluid still weighs the same however the hole turns.", "A head that depends on the inclination, which is ninety degrees there and gives a sine of one and a full contribution."]'::jsonb, 0, 'A cement column 800 m long, weighing nothing.'),
  ('cementing', 'intermediate', 'final', null, 11, 'This engine has no friction model of its own. Where does the loss come from?', '["From a cement-specific correlation in this engine.", "From a Fanning friction factor computed here, since a cement slurry is more shear thinning than a drilling fluid and needs one.", "From the hydraulics engine, since that engine already has the Herschel-Bulkley fits the Fann dial readings are turned into.", "From the hydraulics loss kernel, because a second implementation would be a second place for the same physics to differ."]'::jsonb, 3, 'It is called once per segment, at the velocity that segment''s capacity gives.'),
  ('cementing', 'intermediate', 'final', null, 12, 'A fluid supplied without a rheology contributes what friction?', '["A Newtonian friction at the water viscosity.", "An error, since a fluid cannot be placed without a rheological model and the engine refuses the input by name for that reason.", "None, which the vertical fixture uses deliberately and which is a silent trap on a real run.", "The friction of the fluid ahead of it, on the argument that the two are in contact and have partly mixed at the interface."]'::jsonb, 2, 'Its three fluids carry no rheology, so its friction is identically zero and its closed forms are checkable by hand.'),
  ('cementing', 'intermediate', 'final', null, 13, 'Free fall means what, in terms of the three-term balance?', '["The pump pressure has been floored at zero.", "The raw value has gone negative: the inside column outweighs the annulus head plus the friction.", "The annular velocity has dropped below the rate at which the column can be supported, so the interface separates from the fluid.", "The friction has exceeded the hydrostatic imbalance, so the pumps are having to push against a column that wants to rise."]'::jsonb, 1, 'Nothing at surface is holding it up.'),
  ('cementing', 'intermediate', 'final', null, 14, 'Which of these does the engine deliberately NOT compute during a free fall?', '["The rate at which the column falls, which would need a transient two-phase model.", "Whether it is happening, which it reports as a flag.", "The pump pressure, which it reports as zero over those steps rather than as the negative value the balance actually produces.", "The deficit, which it reports as a raw U-tube value alongside the floored pump pressure at every step of the series."]'::jsonb, 0, 'It can say when it happens and by how much, and not how fast.'),
  ('cementing', 'intermediate', 'final', null, 15, 'Why is the free-fall test written against minus one pascal?', '["Because one pascal is the resolution of a surface gauge.", "Because the float equipment leaves about a pascal of residue on the collar, which the deadband is sized to accommodate.", "Because the rounding in the segment sums is about a pascal, and a strict comparison would report free fall at random steps.", "Because the difference of two ten megapascal sums is not exactly zero in double precision when the columns balance."]'::jsonb, 3, 'The rounding is around a nanopascal and the real deficits are around a hundred kilopascals.'),
  ('cementing', 'intermediate', 'final', null, 16, 'The pump pressure falls and then rises on every cement job. Why must it?', '["Because the rate is reduced and then increased.", "Because the friction falls as the heavier slurry replaces the mud, and then rises again as the annulus fills with slurry.", "Cement into the casing raises the inside head, which subtracts, and cement into the annulus raises the annulus head, which adds.", "Because the spacer is lighter than the mud ahead of it, so the balance falls until the spacer has left the casing entirely."]'::jsonb, 2, 'The minimum is where the two effects balance.'),
  ('cementing', 'intermediate', 'final', null, 17, 'Nothing happens to the gauge for the first twenty cubic metres. What are you looking for?', '["The excess was underestimated.", "The bottom plug did not burst at the float collar, so the cement is not going down the casing.", "The annulus is taking fluid, so the returns are short and the annular column is not building at the expected rate.", "The pump rate is too high, so the friction term dominates the hydrostatic fall and masks it on the surface gauge."]'::jsonb, 1, 'A mixing failure at surface and a geometry that is not what you thought are the other two.'),
  ('cementing', 'intermediate', 'final', null, 18, 'The ECD at the previous shoe uses which part of the annulus?', '["Only the part above that shoe, because that is what loads the formation there.", "The whole annulus, divided by the shoe TVD.", "The part below the shoe, since that is the column standing on the formation at the depth of the previous casing seat.", "The whole annulus above the casing shoe, which includes the open hole section as well as the cased one above it."]'::jsonb, 0, 'The engine finds the deepest cased section whose bottom is at or above the casing shoe.'),
  ('cementing', 'intermediate', 'final', null, 19, 'Why is that number flat for two thirds of a cement job?', '["Because the engine only recomputes it at the end.", "Because the friction above the shoe is constant at a constant rate, and the head there is fixed by the mud density.", "Because nothing above that shoe has changed until cement or spacer crosses it on the way up the annulus.", "Because the annulus above the previous shoe is still full of the original mud until late in the job."]'::jsonb, 3, 'On the slant well it sits at 1631.9010099539694 kg/m3 for the first half of the series.'),
  ('cementing', 'intermediate', 'final', null, 20, 'At which moment of a cement job is the shallowest exposed formation worst loaded?', '["When the cement front first reaches that shoe.", "At the pressure minimum, since that is where the annular column is building fastest and the friction is at its highest.", "At the last step, on every run in this course.", "At the start, when the annulus is full of the heaviest fluid the well contained before the job was pumped."]'::jsonb, 2, 'The most dangerous moment for the shoe above is the plug bump.'),
  ('cementing', 'intermediate', 'final', null, 21, 'The horizontal well''s ECD at the CASING shoe is 1837.9218199066345 kg/m3 before anything is pumped. Why?', '["Its mud is heavier than the slant well''s.", "It divides the friction of a 1600 m lateral by 1214.859173174059 m of true vertical depth.", "Its annulus is narrower, so the same pump rate produces a much higher velocity and therefore much more friction per metre.", "Its previous shoe is shallower, so the head above it converts to a higher equivalent density at the reference depth."]'::jsonb, 1, 'The friction is generated along the hole and the depth is measured vertically.'),
  ('cementing', 'intermediate', 'final', null, 22, 'The report gives two equivalent densities. Which one do you compare against a leak-off?', '["The one at the previous shoe, because that is where the exposed formation is weakest.", "The one at the casing shoe, being the deepest.", "Whichever is larger, since the job has to satisfy the fracture gradient wherever the annulus is in contact with open rock.", "Neither, since both are diagnostics and the real limit is the pump pressure against the surface equipment rating."]'::jsonb, 0, 'The formation at the casing shoe is about to be cased off.'),
  ('cementing', 'intermediate', 'final', null, 23, 'The float differential is computed how?', '["The end pump pressure less the annular head.", "The maximum over the whole series of the difference between the two heads, since that is what the floats have to hold at worst.", "The annulus head less the inside head at the last step, computed with the pumps stopped so the friction term is excluded.", "Annulus head less inside head at the last step, with no friction, because the pumps have stopped."]'::jsonb, 3, 'A negative one means the floats are holding a reverse U-tube.'),
  ('cementing', 'intermediate', 'final', null, 24, 'The slant and horizontal wells'' float differentials differ by a factor of ten. Why?', '["The slant well places more cement in the annulus.", "The horizontal well''s displacement fluid is heavier, so its inside head at the end of the job is larger and the difference smaller.", "Their shoe true vertical depths are 2507.9196993011733 and 1214.859173174059 m on the same measured column.", "The slant well''s floats are rated higher, so the engine reports a larger differential against a larger rating on that well."]'::jsonb, 2, 'Less vertical height means less head on both sides and the difference shrinks with it.'),
  ('cementing', 'intermediate', 'final', null, 25, 'What is the end pump pressure less the float differential?', '["The annular head at the last step.", "The friction at the last step, which on the slant well is 7998410.86173334 Pa.", "The inside head at the last step, which the differential subtracts and the pump pressure adds, so it appears in both.", "The plug bump spike, which is the pressure rise as the top plug seats on the float collar and the flow path closes."]'::jsonb, 1, 'It is more than half the bump pressure, which is why reducing the rate at the end reduces the bump.'),
  ('cementing', 'intermediate', 'final', null, 26, 'The vertical fixture''s end pump pressure equals its float differential exactly. Why?', '["None of its three fluids carries a rheology, so its friction is identically zero.", "Its two columns have the same density.", "It is a vertical well, so the measured and true vertical depths coincide and the two head calculations give the same answer.", "It has no shoe track, so the plug lands at the shoe and the last step is computed with the pumps already stopped."]'::jsonb, 0, 'It is the cleanest possible demonstration of what the two numbers are.'),
  ('cementing', 'intermediate', 'final', null, 27, 'Two programmes place the same slurry to the same top. What differs?', '["The volume of displacement fluid required.", "The achieved top of cement, since the neat programme has no spacer and its cement column therefore reaches higher.", "The density profile of the annular column, and with it the pump pressure, the float differential and the circulating density.", "The density profile of the column, and therefore every pressure in the job."]'::jsonb, 3, 'The neat programme is worse on every measure, on both wells.'),
  ('cementing', 'intermediate', 'final', null, 28, 'A two-slurry design is defended on cost grounds. What is the better argument?', '["About eleven percent of the cement cost.", "A lower achieved top of cement, since a lighter slurry occupies more annulus per unit mass than the heavier tail does.", "The difference between free falling and not, at the same rate on the same volumes.", "A shorter job, since the lead is mixed faster than the tail and the total pumping time falls with it accordingly."]'::jsonb, 2, 'It also buys 62 kg/m3 of peak circulating density at the previous shoe.'),
  ('cementing', 'intermediate', 'final', null, 29, 'The lead makes the annulus HEAVIER, and it prevents free fall. How?', '["It does not; the effect is on the inside column.", "By adding to the side of the U that was losing rather than subtracting from the side that was winning.", "By reducing the friction, since a lighter slurry has a lower annular pressure loss and therefore supports the column less.", "By raising the achieved top of cement, so the annular column is taller and its head is greater at the moment that matters."]'::jsonb, 1, 'A lead heavier than the mud but lighter than the tail does both jobs at once.'),
  ('cementing', 'intermediate', 'final', null, 30, 'Pumping faster does what to the two rate constraints?', '["Cures free fall and raises the circulating density, because the same friction term appears in both with opposite senses.", "Helps both, since friction supports the annular column.", "Worsens both, since a faster job generates more friction and the friction appears on the wrong side of both balances.", "Helps free fall and does nothing to the circulating density, which is set by the hydrostatic column rather than the rate."]'::jsonb, 0, 'One knob, two constraints, pulling in opposite directions.'),
  ('cementing', 'intermediate', 'final', null, 31, 'A sweep at 0.005 steps would have been quicker to write. What is wrong with it?', '["Because the free-fall flag is discrete.", "Because a sweep would take eighty times as long, and the bisection converges in the same number of runs to full precision.", "Because only a bisected number can be checked by somebody else or compared against another programme''s edge.", "Because a sweep gives an interval whose width is the step size, and the answer is going to be quoted."]'::jsonb, 3, 'The bisection costs eighty runs of a millisecond calculation.'),
  ('cementing', 'intermediate', 'final', null, 32, 'A rate window of 0.0001944956449708296 cubic metres a second. What does that mean?', '["Closed, since the width is smaller than the tolerance.", "Comfortably open, since any positive width means a rate exists that satisfies both constraints at the stated limit.", "Open and useless: a fifth of a percent of the rate is not a band anybody can hold a pump inside.", "Meaningless, since a window narrower than the resolution of the placement grid is inside the numerical noise of the search."]'::jsonb, 2, 'A window that is open but narrow is a warning in itself.'),
  ('cementing', 'intermediate', 'final', null, 33, 'A rate window comes out negative. What has to change?', '["The pump rate, to somewhere inside the window.", "The programme, because no rate satisfies both constraints and the rate is the only thing a rate change moves.", "The fracture limit, since a negative window means the assumed leak-off value was too conservative for the well in question.", "The placement grid, since a negative window usually means the free-fall dip was sampled at the wrong resolution."]'::jsonb, 1, 'The four remedies are a lighter lead, a lower top of cement, a staged job, or accepting the free fall.'),
  ('cementing', 'intermediate', 'final', null, 34, 'Adding a lead slurry moves both rate edges. In which directions?', '["The free-fall edge down and the circulating density edge up, so the window opens from both sides.", "Both up, since the annular column is heavier.", "Both down, since a lighter overall column needs less friction to hold and generates less at any given rate.", "Only the free-fall edge moves, since the circulating density depends on the total slurry rather than on how it is split."]'::jsonb, 0, 'One change to the programme, two edges, both improved.'),
  ('cementing', 'intermediate', 'final', null, 35, 'You are handed a blank cement programme sheet. What do you fill in first?', '["Rate, volumes, densities, top of cement.", "Volumes first, since the sheet has to be produced before anything can be simulated, and then the rate and the fluid programme.", "The top of cement, then the fluid programme, then the rate window, with the rate last rather than first of the four.", "Where the cement must reach, the density profile, whether a window exists, and then the rate."]'::jsonb, 3, 'The rate is the last of the four, and the density profile is where free fall is actually decided.'),
  ('cementing', 'intermediate', 'final', null, 36, 'A spacer sits above the cement in the annulus. Is it part of the reported top?', '["The depth the volume sheet said it should reach.", "The shallowest annulus segment that is not the original mud, which includes the spacer sitting above the cement column.", "The shallowest lead or tail segment in the annulus at the last step, excluding the spacer.", "The depth at which the annular density first exceeds the mud density, found by walking the column upward from the shoe."]'::jsonb, 2, 'A top of cement that counted the spacer would be a lie of exactly the spacer''s length.'),
  ('cementing', 'intermediate', 'final', null, 37, 'How far can the placed cement miss its target before anything is said about it?', '["Five percent of the annular slurry volume.", "Thirty metres, hard coded, which is about the length of a real mixing zone.", "One annulus row, so the warning fires when the achieved top lands in a different capacity row from the target.", "Ten metres, which is the resolution the sixty one step grid gives on a job of this total pumped volume."]'::jsonb, 1, 'It is a judgement, it is reasonable, and it has no comment next to it.'),
  ('cementing', 'intermediate', 'final', null, 38, 'Name the two most powerful things a cementer can do that this engine cannot represent.', '["Intermixing, which the spacer exists to control, and casing movement during the job.", "Temperature and losses to the formation.", "The transient free-fall rate and the float equipment pressure drop, which together set what the crew see at surface.", "Gas migration after placement and the slurry thickening time, both of which decide whether the cement sets at all."]'::jsonb, 0, 'A job simulated here has sharp interfaces and a stationary casing.'),
  ('cementing', 'intermediate', 'final', null, 39, 'The placement grid found a free-fall dip at exactly one of 61 steps. What did the finer grid show?', '["That the dip was a sampling artefact.", "That there were two dips rather than one, which the coarse grid had merged into a single sample near the middle of them.", "That the dip is real and about two cubic metres wide, and that the coarse grid found its depth correctly at the first attempt.", "The dip is real and spans about two cubic metres, and the coarse grid understated its depth by six percent."]'::jsonb, 3, 'The finding survives and one of its digits does not.'),
  ('cementing', 'intermediate', 'final', null, 40, 'Refining the grid cannot change three of the reported numbers. Which three?', '["The two circulating densities and the free-fall flag.", "The achieved top of cement, the peak circulating density and the warnings, since all three are derived from the whole series.", "The end pump pressure, the float differential and the annulus end state.", "The pump pressure, the U-tube value and the annular velocity, which are constant through a job at a constant rate."]'::jsonb, 2, 'All three come from the final evaluation at exactly the full pumped volume.'),
  ('cementing', 'intermediate', 'final', null, 41, 'What has the Professional tier said nothing about?', '["How much of each fluid to order.", "Whether the cement isolated anything, because there is no term for where the casing sits in the hole.", "Whether the formation at the previous shoe will fracture, which is exactly what the circulating density is computed for.", "Whether the plug will bump at the calculated displacement, which is the only real-time check the field has on the job."]'::jsonb, 1, 'Every number in this tier is identical for a perfectly centred casing and one lying flat on the low side.'),
  ('cementing', 'intermediate', 'final', null, 42, 'The engine rebuilds the fluid intervals from scratch at each of the 61 steps. What does that buy?', '["No accumulation of rounding, because there is no state carried from one step to the next.", "Speed, since a rebuild is cheaper than an advance.", "The ability to vary the pump rate between steps, which a state-carrying scheme could not represent without restarting the job.", "Consistency with the volume sheet, since both are recomputed from the same geometry rather than from a cached intermediate."]'::jsonb, 0, 'It is slower than advancing a state, and it is correct by construction.');
