-- ============================================================================
-- HELD DECISIONS (HD): 20261030f_hd_fluid_quiz.
--
-- Owner 2026-09-22: fix the labTune Bo fallback in the engine (engines #235);
-- lead decision 2026-09-22, Option A: the fluid course follows the fixed
-- engine. Its Bo fallback had returned a null Bo at random during the Good
-- Oil regression, so the regression met its penalty residual and the tuned
-- figures the advanced tier teaches were artefacts of that. These served
-- questions print the old figures or a claim the fixed engine no longer
-- supports; each is retired and re-inserted at its slot with the same
-- answer_index and every figure rendered from the vendored engine.
--
-- Spec: docs/graded-field-audit/hd/quiz/fluid.json; every figure from
-- docs/graded-field-audit/hd/fluid/figures.mjs (the vendored engine).
-- Generated by docs/graded-field-audit/hd_quiz.py. Applies AFTER the whole
-- W2-W6 batch.
--
-- SLOTS (retire the published row, insert the re-cut at the same slot and
-- answer_index):
--   advanced m03-tuning ord 9: replaces d23e85389b960ccff4df5b505129a23a
--   advanced m03-tuning ord 10: replaces 4468517815dfdb07285bd127a5404619
--   advanced m04-what-tuning-costs ord 3: replaces 64fcba2c213ca65f57bfbdb5625ee6af
--   advanced m04-what-tuning-costs ord 8: replaces 11f60ba8b1f433c0907ac173a822b95e
--   advanced m06-the-expert-reading ord 9: replaces 4416fa3d8c68b46e55f219c5627b9591
--   advanced m06-the-expert-reading ord 12: replaces ef4d724c1ec181e1ef6b29935f477331
--   advanced final ord 22: replaces 419e142f7b4cdd6111f50c4995758857
--
-- REPLACEMENT. Each slot holds ONE active row. When that row carries its
-- published content hash, md5(prompt | options | answer_index | explanation),
-- it is RETIRED (active = false, text untouched) and the re-cut question is
-- inserted at the same slot. A retired row keeps its id, so every stored
-- attempt, open or submitted, still grades and reviews against the question
-- it was served. Stored scores are never recomputed. When the active row
-- already IS the re-cut question and the published row sits retired beside
-- it, the slot is left alone. ANYTHING ELSE RAISES and the transaction rolls
-- back (drift). Every touched quiz keeps its active count. SAFE TO RE-RUN.
-- No capstone is touched.
-- ============================================================================

do $$
declare
  v_n        integer;
  v_pub      integer;
  v_new      integer;
  v_written  integer := 0;
  v_total    integer;
  v_counts   jsonb := '{}'::jsonb;
begin
  select count(*) into v_total from public.academy_quiz_questions where app_slug = 'fluid' and tier = 'advanced' and scope = 'final' and module_key is null and active;
  v_counts := v_counts || jsonb_build_object('advanced/final/None', v_total);
  select count(*) into v_total from public.academy_quiz_questions where app_slug = 'fluid' and tier = 'advanced' and scope = 'module' and module_key = 'm03-tuning' and active;
  v_counts := v_counts || jsonb_build_object('advanced/module/m03-tuning', v_total);
  select count(*) into v_total from public.academy_quiz_questions where app_slug = 'fluid' and tier = 'advanced' and scope = 'module' and module_key = 'm04-what-tuning-costs' and active;
  v_counts := v_counts || jsonb_build_object('advanced/module/m04-what-tuning-costs', v_total);
  select count(*) into v_total from public.academy_quiz_questions where app_slug = 'fluid' and tier = 'advanced' and scope = 'module' and module_key = 'm06-the-expert-reading' and active;
  v_counts := v_counts || jsonb_build_object('advanced/module/m06-the-expert-reading', v_total);

  -- advanced m03-tuning ord 9: replaces d23e85389b960ccff4df5b505129a23a
  select count(*) filter (where active), count(*) filter (where active and md5(prompt || chr(31) || options::text || chr(31) || answer_index::text || chr(31) || coalesce(explanation, '')) = 'd23e85389b960ccff4df5b505129a23a'),
         count(*) filter (where active and prompt = 'Why are two knobs multipliers and two absolute?' and options = '["Because a multiplier keeps a positive quantity positive, and the other two may legitimately be negative.", "Because the criticals enter the equation non-linearly and the other two enter linearly, so the scaling differs.", "Because the form encodes how much the starting value is worth: the Kesler-Lee criticals are meaningful starting points and the other two starting values are guesses.", "Because the engine''s bounds are relative for the criticals and absolute for the other two, and the knob form has to match."]'::jsonb and answer_index = 2 and explanation = 'A multiplier of 0.971 says the correlation was within three percent, which is a statement a reader can evaluate. For a barely-constrained interaction parameter the starting value is a guess and the tuned value is the answer.')
    into v_n, v_pub, v_new
    from public.academy_quiz_questions where app_slug = 'fluid' and tier = 'advanced' and scope = 'module' and module_key = 'm03-tuning' and ord = 9;
  if v_n <> 1 then raise exception 'hd fluid quiz refused: advanced m03-tuning ord 9 holds % active rows, expected 1', v_n; end if;
  if v_pub = 1 then
    update public.academy_quiz_questions set active = false where app_slug = 'fluid' and tier = 'advanced' and scope = 'module' and module_key = 'm03-tuning' and ord = 9 and active and md5(prompt || chr(31) || options::text || chr(31) || answer_index::text || chr(31) || coalesce(explanation, '')) = 'd23e85389b960ccff4df5b505129a23a';
    insert into public.academy_quiz_questions (app_slug, tier, scope, module_key, ord, prompt, options, answer_index, explanation, active)
    values ('fluid', 'advanced', 'module', 'm03-tuning', 9, 'Why are two knobs multipliers and two absolute?',
            '["Because a multiplier keeps a positive quantity positive, and the other two may legitimately be negative.", "Because the criticals enter the equation non-linearly and the other two enter linearly, so the scaling differs.", "Because the form encodes how much the starting value is worth: the Kesler-Lee criticals are meaningful starting points and the other two starting values are guesses.", "Because the engine''s bounds are relative for the criticals and absolute for the other two, and the knob form has to match."]'::jsonb, 2, 'A multiplier of 0.971 says the correlation was within three percent, which is a statement a reader can evaluate. For a barely-constrained interaction parameter the starting value is a guess and the tuned value is the answer.', true);
    v_written := v_written + 1;
  elsif v_new = 1 then
    if not exists (select 1 from public.academy_quiz_questions where app_slug = 'fluid' and tier = 'advanced' and scope = 'module' and module_key = 'm03-tuning' and ord = 9 and not active and md5(prompt || chr(31) || options::text || chr(31) || answer_index::text || chr(31) || coalesce(explanation, '')) = 'd23e85389b960ccff4df5b505129a23a') then
      raise exception 'hd fluid quiz refused: advanced m03-tuning ord 9 carries the re-cut question but its published row is not retired beside it';
    end if;
  else
    raise exception 'hd fluid quiz refused: advanced m03-tuning ord 9 matches neither its published content hash nor its re-cut form (drift)';
  end if;

  -- advanced m03-tuning ord 10: replaces 4468517815dfdb07285bd127a5404619
  select count(*) filter (where active), count(*) filter (where active and md5(prompt || chr(31) || options::text || chr(31) || answer_index::text || chr(31) || coalesce(explanation, '')) = '4468517815dfdb07285bd127a5404619'),
         count(*) filter (where active and prompt = 'The tuned criticals move by about three percent and the volume shift moves by about a quarter. What does that say?' and options = '["That the Kesler-Lee characterization was close and the Jhaveri-Youngren volume shift correlation was not.", "That the regression is under-determined in the criticals, so the prior pull held them near their starting values.", "That the criticals hit their bounds early and the solver spent its remaining freedom on the volume shift.", "That the saturation pressure target was satisfied first, leaving the other three to be fitted by the shift alone."]'::jsonb and answer_index = 0 and explanation = 'That is exactly what the Professional tier predicted from the mechanisms, and seeing the regression confirm it independently is worth more than either statement alone. No knob hits a bound.')
    into v_n, v_pub, v_new
    from public.academy_quiz_questions where app_slug = 'fluid' and tier = 'advanced' and scope = 'module' and module_key = 'm03-tuning' and ord = 10;
  if v_n <> 1 then raise exception 'hd fluid quiz refused: advanced m03-tuning ord 10 holds % active rows, expected 1', v_n; end if;
  if v_pub = 1 then
    update public.academy_quiz_questions set active = false where app_slug = 'fluid' and tier = 'advanced' and scope = 'module' and module_key = 'm03-tuning' and ord = 10 and active and md5(prompt || chr(31) || options::text || chr(31) || answer_index::text || chr(31) || coalesce(explanation, '')) = '4468517815dfdb07285bd127a5404619';
    insert into public.academy_quiz_questions (app_slug, tier, scope, module_key, ord, prompt, options, answer_index, explanation, active)
    values ('fluid', 'advanced', 'module', 'm03-tuning', 10, 'The tuned criticals move by about three percent and the volume shift moves by about a quarter. What does that say?',
            '["That the Kesler-Lee characterization was close and the Jhaveri-Youngren volume shift correlation was not.", "That the regression is under-determined in the criticals, so the prior pull held them near their starting values.", "That the criticals hit their bounds early and the solver spent its remaining freedom on the volume shift.", "That the saturation pressure target was satisfied first, leaving the other three to be fitted by the shift alone."]'::jsonb, 0, 'That is exactly what the Professional tier predicted from the mechanisms, and seeing the regression confirm it independently is worth more than either statement alone. No knob hits a bound.', true);
    v_written := v_written + 1;
  elsif v_new = 1 then
    if not exists (select 1 from public.academy_quiz_questions where app_slug = 'fluid' and tier = 'advanced' and scope = 'module' and module_key = 'm03-tuning' and ord = 10 and not active and md5(prompt || chr(31) || options::text || chr(31) || answer_index::text || chr(31) || coalesce(explanation, '')) = '4468517815dfdb07285bd127a5404619') then
      raise exception 'hd fluid quiz refused: advanced m03-tuning ord 10 carries the re-cut question but its published row is not retired beside it';
    end if;
  else
    raise exception 'hd fluid quiz refused: advanced m03-tuning ord 10 matches neither its published content hash nor its re-cut form (drift)';
  end if;

  -- advanced m04-what-tuning-costs ord 3: replaces 64fcba2c213ca65f57bfbdb5625ee6af
  select count(*) filter (where active), count(*) filter (where active and md5(prompt || chr(31) || options::text || chr(31) || answer_index::text || chr(31) || coalesce(explanation, '')) = '64fcba2c213ca65f57bfbdb5625ee6af'),
         count(*) filter (where active and prompt = 'Which target got worse under tuning?' and options = '["The total gas-oil ratio, from plus 3.4 percent to minus 0.97, since the sign flipped across zero.", "The stock tank gravity, since a 1.9 API residual is still outside the engine''s stated tolerance.", "None of them; all four improved, which is what a factor of twenty seven in the residual means.", "The formation volume factor, from minus 0.31 percent to minus 0.60."]'::jsonb and answer_index = 3 and explanation = 'It was the best-matched target before tuning, the only one an untuned model got right to within half a percent, and the regression gave it up to improve the other three.')
    into v_n, v_pub, v_new
    from public.academy_quiz_questions where app_slug = 'fluid' and tier = 'advanced' and scope = 'module' and module_key = 'm04-what-tuning-costs' and ord = 3;
  if v_n <> 1 then raise exception 'hd fluid quiz refused: advanced m04-what-tuning-costs ord 3 holds % active rows, expected 1', v_n; end if;
  if v_pub = 1 then
    update public.academy_quiz_questions set active = false where app_slug = 'fluid' and tier = 'advanced' and scope = 'module' and module_key = 'm04-what-tuning-costs' and ord = 3 and active and md5(prompt || chr(31) || options::text || chr(31) || answer_index::text || chr(31) || coalesce(explanation, '')) = '64fcba2c213ca65f57bfbdb5625ee6af';
    insert into public.academy_quiz_questions (app_slug, tier, scope, module_key, ord, prompt, options, answer_index, explanation, active)
    values ('fluid', 'advanced', 'module', 'm04-what-tuning-costs', 3, 'Which target got worse under tuning?',
            '["The total gas-oil ratio, from plus 3.4 percent to minus 0.97, since the sign flipped across zero.", "The stock tank gravity, since a 1.9 API residual is still outside the engine''s stated tolerance.", "None of them; all four improved, which is what a factor of twenty seven in the residual means.", "The formation volume factor, from minus 0.31 percent to minus 0.60."]'::jsonb, 3, 'It was the best-matched target before tuning, the only one an untuned model got right to within half a percent, and the regression gave it up to improve the other three.', true);
    v_written := v_written + 1;
  elsif v_new = 1 then
    if not exists (select 1 from public.academy_quiz_questions where app_slug = 'fluid' and tier = 'advanced' and scope = 'module' and module_key = 'm04-what-tuning-costs' and ord = 3 and not active and md5(prompt || chr(31) || options::text || chr(31) || answer_index::text || chr(31) || coalesce(explanation, '')) = '64fcba2c213ca65f57bfbdb5625ee6af') then
      raise exception 'hd fluid quiz refused: advanced m04-what-tuning-costs ord 3 carries the re-cut question but its published row is not retired beside it';
    end if;
  else
    raise exception 'hd fluid quiz refused: advanced m04-what-tuning-costs ord 3 matches neither its published content hash nor its re-cut form (drift)';
  end if;

  -- advanced m04-what-tuning-costs ord 8: replaces 11f60ba8b1f433c0907ac173a822b95e
  select count(*) filter (where active), count(*) filter (where active and md5(prompt || chr(31) || options::text || chr(31) || answer_index::text || chr(31) || coalesce(explanation, '')) = '11f60ba8b1f433c0907ac173a822b95e'),
         count(*) filter (where active and prompt = 'The residual falls by a factor of 27.01832736401665. What does that number mean?' and options = '["The model is that many times more accurate, averaged across the four targets it was fitted to.", "The uncertainty in every predicted quantity has fallen by the square root of that factor.", "The sum of squared relative errors is that many times smaller, which is dominated by the two targets that started worst.", "The tuned model reproduces the study to within roughly a twenty-seventh of the untuned model''s error on each of the targets."]'::jsonb and answer_index = 2 and explanation = 'A single aggregate hides that one target degraded, which is why the ledger is per target and the aggregate is a footnote.')
    into v_n, v_pub, v_new
    from public.academy_quiz_questions where app_slug = 'fluid' and tier = 'advanced' and scope = 'module' and module_key = 'm04-what-tuning-costs' and ord = 8;
  if v_n <> 1 then raise exception 'hd fluid quiz refused: advanced m04-what-tuning-costs ord 8 holds % active rows, expected 1', v_n; end if;
  if v_pub = 1 then
    update public.academy_quiz_questions set active = false where app_slug = 'fluid' and tier = 'advanced' and scope = 'module' and module_key = 'm04-what-tuning-costs' and ord = 8 and active and md5(prompt || chr(31) || options::text || chr(31) || answer_index::text || chr(31) || coalesce(explanation, '')) = '11f60ba8b1f433c0907ac173a822b95e';
    insert into public.academy_quiz_questions (app_slug, tier, scope, module_key, ord, prompt, options, answer_index, explanation, active)
    values ('fluid', 'advanced', 'module', 'm04-what-tuning-costs', 8, 'The residual falls by a factor of 27.01832736401665. What does that number mean?',
            '["The model is that many times more accurate, averaged across the four targets it was fitted to.", "The uncertainty in every predicted quantity has fallen by the square root of that factor.", "The sum of squared relative errors is that many times smaller, which is dominated by the two targets that started worst.", "The tuned model reproduces the study to within roughly a twenty-seventh of the untuned model''s error on each of the targets."]'::jsonb, 2, 'A single aggregate hides that one target degraded, which is why the ledger is per target and the aggregate is a footnote.', true);
    v_written := v_written + 1;
  elsif v_new = 1 then
    if not exists (select 1 from public.academy_quiz_questions where app_slug = 'fluid' and tier = 'advanced' and scope = 'module' and module_key = 'm04-what-tuning-costs' and ord = 8 and not active and md5(prompt || chr(31) || options::text || chr(31) || answer_index::text || chr(31) || coalesce(explanation, '')) = '11f60ba8b1f433c0907ac173a822b95e') then
      raise exception 'hd fluid quiz refused: advanced m04-what-tuning-costs ord 8 carries the re-cut question but its published row is not retired beside it';
    end if;
  else
    raise exception 'hd fluid quiz refused: advanced m04-what-tuning-costs ord 8 matches neither its published content hash nor its re-cut form (drift)';
  end if;

  -- advanced m06-the-expert-reading ord 9: replaces 4416fa3d8c68b46e55f219c5627b9591
  select count(*) filter (where active), count(*) filter (where active and md5(prompt || chr(31) || options::text || chr(31) || answer_index::text || chr(31) || coalesce(explanation, '')) = '4416fa3d8c68b46e55f219c5627b9591'),
         count(*) filter (where active and prompt = 'What did the tuned criticals and the tuned volume shift each say about the characterization?' and options = '["That both were close, since no knob hit a bound and the prior pull held them all near their starting values.", "That both were wrong, since a factor of twenty seven in the residual implies large corrections throughout.", "That the Kesler-Lee criticals were close and the Jhaveri-Youngren volume shift correlation was not.", "That the criticals were wrong and the shift was close, which is why the equilibrium targets improved most."]'::jsonb and answer_index = 2 and explanation = 'The multipliers move by about three percent and the shift moves by about a quarter. That is exactly what the Professional tier predicted from the mechanisms, confirmed independently by the regression.')
    into v_n, v_pub, v_new
    from public.academy_quiz_questions where app_slug = 'fluid' and tier = 'advanced' and scope = 'module' and module_key = 'm06-the-expert-reading' and ord = 9;
  if v_n <> 1 then raise exception 'hd fluid quiz refused: advanced m06-the-expert-reading ord 9 holds % active rows, expected 1', v_n; end if;
  if v_pub = 1 then
    update public.academy_quiz_questions set active = false where app_slug = 'fluid' and tier = 'advanced' and scope = 'module' and module_key = 'm06-the-expert-reading' and ord = 9 and active and md5(prompt || chr(31) || options::text || chr(31) || answer_index::text || chr(31) || coalesce(explanation, '')) = '4416fa3d8c68b46e55f219c5627b9591';
    insert into public.academy_quiz_questions (app_slug, tier, scope, module_key, ord, prompt, options, answer_index, explanation, active)
    values ('fluid', 'advanced', 'module', 'm06-the-expert-reading', 9, 'What did the tuned criticals and the tuned volume shift each say about the characterization?',
            '["That both were close, since no knob hit a bound and the prior pull held them all near their starting values.", "That both were wrong, since a factor of twenty seven in the residual implies large corrections throughout.", "That the Kesler-Lee criticals were close and the Jhaveri-Youngren volume shift correlation was not.", "That the criticals were wrong and the shift was close, which is why the equilibrium targets improved most."]'::jsonb, 2, 'The multipliers move by about three percent and the shift moves by about a quarter. That is exactly what the Professional tier predicted from the mechanisms, confirmed independently by the regression.', true);
    v_written := v_written + 1;
  elsif v_new = 1 then
    if not exists (select 1 from public.academy_quiz_questions where app_slug = 'fluid' and tier = 'advanced' and scope = 'module' and module_key = 'm06-the-expert-reading' and ord = 9 and not active and md5(prompt || chr(31) || options::text || chr(31) || answer_index::text || chr(31) || coalesce(explanation, '')) = '4416fa3d8c68b46e55f219c5627b9591') then
      raise exception 'hd fluid quiz refused: advanced m06-the-expert-reading ord 9 carries the re-cut question but its published row is not retired beside it';
    end if;
  else
    raise exception 'hd fluid quiz refused: advanced m06-the-expert-reading ord 9 matches neither its published content hash nor its re-cut form (drift)';
  end if;

  -- advanced m06-the-expert-reading ord 12: replaces ef4d724c1ec181e1ef6b29935f477331
  select count(*) filter (where active), count(*) filter (where active and md5(prompt || chr(31) || options::text || chr(31) || answer_index::text || chr(31) || coalesce(explanation, '')) = 'ef4d724c1ec181e1ef6b29935f477331'),
         count(*) filter (where active and prompt = 'Which target did the joint fit give up, and why could it not be avoided?' and options = '["The stock tank gravity, because the volume shift is bounded and could not reach the measured value.", "The total gas-oil ratio, because the stock tank stage releases gas the model cannot partition correctly.", "The formation volume factor, because total gas-oil ratio, stock tank gravity and formation volume factor all divide by the same stock-tank volume.", "None was given up; all four improved, which is what a twenty-seven-fold residual reduction means."]'::jsonb and answer_index = 2 and explanation = 'It was the best-matched target before tuning. One knob sets how dense the stock tank liquid is, and making it lighter necessarily changes its volume, which two other targets divide by.')
    into v_n, v_pub, v_new
    from public.academy_quiz_questions where app_slug = 'fluid' and tier = 'advanced' and scope = 'module' and module_key = 'm06-the-expert-reading' and ord = 12;
  if v_n <> 1 then raise exception 'hd fluid quiz refused: advanced m06-the-expert-reading ord 12 holds % active rows, expected 1', v_n; end if;
  if v_pub = 1 then
    update public.academy_quiz_questions set active = false where app_slug = 'fluid' and tier = 'advanced' and scope = 'module' and module_key = 'm06-the-expert-reading' and ord = 12 and active and md5(prompt || chr(31) || options::text || chr(31) || answer_index::text || chr(31) || coalesce(explanation, '')) = 'ef4d724c1ec181e1ef6b29935f477331';
    insert into public.academy_quiz_questions (app_slug, tier, scope, module_key, ord, prompt, options, answer_index, explanation, active)
    values ('fluid', 'advanced', 'module', 'm06-the-expert-reading', 12, 'Which target did the joint fit give up, and why could it not be avoided?',
            '["The stock tank gravity, because the volume shift is bounded and could not reach the measured value.", "The total gas-oil ratio, because the stock tank stage releases gas the model cannot partition correctly.", "The formation volume factor, because total gas-oil ratio, stock tank gravity and formation volume factor all divide by the same stock-tank volume.", "None was given up; all four improved, which is what a twenty-seven-fold residual reduction means."]'::jsonb, 2, 'It was the best-matched target before tuning. One knob sets how dense the stock tank liquid is, and making it lighter necessarily changes its volume, which two other targets divide by.', true);
    v_written := v_written + 1;
  elsif v_new = 1 then
    if not exists (select 1 from public.academy_quiz_questions where app_slug = 'fluid' and tier = 'advanced' and scope = 'module' and module_key = 'm06-the-expert-reading' and ord = 12 and not active and md5(prompt || chr(31) || options::text || chr(31) || answer_index::text || chr(31) || coalesce(explanation, '')) = 'ef4d724c1ec181e1ef6b29935f477331') then
      raise exception 'hd fluid quiz refused: advanced m06-the-expert-reading ord 12 carries the re-cut question but its published row is not retired beside it';
    end if;
  else
    raise exception 'hd fluid quiz refused: advanced m06-the-expert-reading ord 12 matches neither its published content hash nor its re-cut form (drift)';
  end if;

  -- advanced final ord 22: replaces 419e142f7b4cdd6111f50c4995758857
  select count(*) filter (where active), count(*) filter (where active and md5(prompt || chr(31) || options::text || chr(31) || answer_index::text || chr(31) || coalesce(explanation, '')) = '419e142f7b4cdd6111f50c4995758857'),
         count(*) filter (where active and prompt = 'One of the four laboratory targets is worse after the fit than before it. Which?' and options = '["The total gas-oil ratio, since its sign flipped from plus 3.4 percent to minus 0.97.", "The stock tank gravity, since 1.9 API is still outside the engine''s stated tolerance.", "None; all four improved, which is what a twenty-seven-fold residual reduction means.", "The formation volume factor, from minus 0.31 percent to minus 0.60."]'::jsonb and answer_index = 3 and explanation = 'It was the best-matched target before tuning, the only one an untuned model got right to within half a percent, and the regression gave it up to improve the other three.')
    into v_n, v_pub, v_new
    from public.academy_quiz_questions where app_slug = 'fluid' and tier = 'advanced' and scope = 'final' and module_key is null and ord = 22;
  if v_n <> 1 then raise exception 'hd fluid quiz refused: advanced final ord 22 holds % active rows, expected 1', v_n; end if;
  if v_pub = 1 then
    update public.academy_quiz_questions set active = false where app_slug = 'fluid' and tier = 'advanced' and scope = 'final' and module_key is null and ord = 22 and active and md5(prompt || chr(31) || options::text || chr(31) || answer_index::text || chr(31) || coalesce(explanation, '')) = '419e142f7b4cdd6111f50c4995758857';
    insert into public.academy_quiz_questions (app_slug, tier, scope, module_key, ord, prompt, options, answer_index, explanation, active)
    values ('fluid', 'advanced', 'final', null, 22, 'One of the four laboratory targets is worse after the fit than before it. Which?',
            '["The total gas-oil ratio, since its sign flipped from plus 3.4 percent to minus 0.97.", "The stock tank gravity, since 1.9 API is still outside the engine''s stated tolerance.", "None; all four improved, which is what a twenty-seven-fold residual reduction means.", "The formation volume factor, from minus 0.31 percent to minus 0.60."]'::jsonb, 3, 'It was the best-matched target before tuning, the only one an untuned model got right to within half a percent, and the regression gave it up to improve the other three.', true);
    v_written := v_written + 1;
  elsif v_new = 1 then
    if not exists (select 1 from public.academy_quiz_questions where app_slug = 'fluid' and tier = 'advanced' and scope = 'final' and module_key is null and ord = 22 and not active and md5(prompt || chr(31) || options::text || chr(31) || answer_index::text || chr(31) || coalesce(explanation, '')) = '419e142f7b4cdd6111f50c4995758857') then
      raise exception 'hd fluid quiz refused: advanced final ord 22 carries the re-cut question but its published row is not retired beside it';
    end if;
  else
    raise exception 'hd fluid quiz refused: advanced final ord 22 matches neither its published content hash nor its re-cut form (drift)';
  end if;

  select count(*) into v_total from public.academy_quiz_questions where app_slug = 'fluid' and tier = 'advanced' and scope = 'final' and module_key is null and active;
  if v_total <> (v_counts->>'advanced/final/None')::integer then raise exception 'hd fluid quiz refused: advanced/final/None changed its active count to %', v_total; end if;
  select count(*) into v_total from public.academy_quiz_questions where app_slug = 'fluid' and tier = 'advanced' and scope = 'module' and module_key = 'm03-tuning' and active;
  if v_total <> (v_counts->>'advanced/module/m03-tuning')::integer then raise exception 'hd fluid quiz refused: advanced/module/m03-tuning changed its active count to %', v_total; end if;
  select count(*) into v_total from public.academy_quiz_questions where app_slug = 'fluid' and tier = 'advanced' and scope = 'module' and module_key = 'm04-what-tuning-costs' and active;
  if v_total <> (v_counts->>'advanced/module/m04-what-tuning-costs')::integer then raise exception 'hd fluid quiz refused: advanced/module/m04-what-tuning-costs changed its active count to %', v_total; end if;
  select count(*) into v_total from public.academy_quiz_questions where app_slug = 'fluid' and tier = 'advanced' and scope = 'module' and module_key = 'm06-the-expert-reading' and active;
  if v_total <> (v_counts->>'advanced/module/m06-the-expert-reading')::integer then raise exception 'hd fluid quiz refused: advanced/module/m06-the-expert-reading changed its active count to %', v_total; end if;
  raise notice 'hd fluid quiz: % of 7 slots written, the rest already carried the re-cut question', v_written;
end $$;
