-- ============================================================================
-- DC27 - Pore Pressure EXPERT (advanced tier) goes deep.
--
-- Flips (porepressure, advanced) onto the DC1 deep path by inserting its
-- ACTIVE academy_course_structures row, generated from the repo manifest
-- src/content/courses/porepressure/advanced/manifest.json (emitted by a
-- generator, not hand-typed), and seeding the six module quiz banks plus the
-- final exam. Answer keys live only here and in the table.
--
-- Six modules, 27 lessons: from pressure to mud, the window, the exponent
-- lever, Bowers loading, unloading and the cross-check, and the window
-- workflow. COMPLETES THE PORE PRESSURE LADDER at all three tiers.
--
-- Every numeric item traces to the porepressure engines through
-- src/lib/porepressureTeaching.js (computeWindowExplorer / computeBowersFacts
-- and the untouched computeMudWindow capstone driver) and reproduces the live
-- NG9 Expert capstone answer key: floor 1179.1048116553065 kg/m3, ceiling
-- 1903.9238599165737, window 724.8190482612672 (all EMW referenced to sea
-- level over the z+100 m column), Bowers loading velocity at 5 MPa
-- 1949.944709834568 m/s, unloading inversion exactly 10 MPa from
-- 3125.808993287662 m/s (sigma_max 50 MPa, U 3), and pore pressure at TD
-- under n 1.2 of 43.901549937778526 MPa. windowLab.test.js pins the panel
-- math to those same values.
--
-- Tier positioning: EMW itself and the TD bracket 1029.878049 / 2266.333384
-- kg/m3 belong to the Associate tier; the prognosis and fracture ceiling to
-- the Professional. This tier owns the WINDOW as an object (widest 750.28 at
-- the ramp top and narrowing below at n 3; the shape FLIPS to widening at
-- n 1.2), the calibration price (floor throw 87.22378125499152 kg/m3 at TD,
-- window +58.15, detected onset 2540), the Bowers pair in both directions
-- (published ft/s-psi domain, mudline 1524 m/s exactly; loading reads
-- 29.240177382128643 MPa from the velocity unloading reads 10 from, a 2.9x
-- mechanism gap; curves rejoin at sigma_max exactly), and the cross-check
-- (Bowers loading agrees with Eaton at TD to 0.03790437848802725 MPa, traced
-- to the 1.408 m/s fit residual through the 0.0269 MPa per m/s inversion
-- gain; mid-ramp drift 1.509 MPa at 3000 m is fit geometry, not geology).
--
-- Bank standard: measured on the length RANK of the correct option and checked
-- for cyclic key sequences, answer-index skew, within-pool near-duplicates and
-- same-claim option pairs before seeding. Across the 132 questions the correct
-- option is longest in 9 pct and shortest in 1 pct.
--
-- Enrollment grandfathering: enforced_from defaults to now() on first insert;
-- the ON CONFLICT update deliberately leaves enforced_from unchanged on
-- re-seeds.
--
-- Ladder note: an ADVANCED enrollment needs an unrevoked PROFESSIONAL
-- certification on the SAME app, so the dry-run probes back-stop a porepressure
-- professional cert in-transaction, and P3b checks prove BOTH tiers below are
-- left undisturbed at 132 questions each.
--
-- New pp-window-explorer panel. NO DDL. Data only.
-- ============================================================================

insert into public.academy_course_structures
    (app_slug, tier, structure, content_version)
values ('porepressure', 'advanced', '{"modules":[{"key":"m01-from-pressure-to-mud","title":"From Pressure to Mud","lesson_keys":["l01-what-this-tier-adds","l02-the-drillers-question","l03-emw-revisited","l04-the-window-panel-map"]},{"key":"m02-the-window","title":"The Window","lesson_keys":["l01-the-floor","l02-the-ceiling","l03-the-window-at-td","l04-the-window-down-the-well","l05-what-a-wide-window-buys"]},{"key":"m03-the-exponent-lever","title":"The Exponent Lever","lesson_keys":["l01-the-lever","l02-n-one-point-two","l03-the-window-under-n12","l04-which-n-is-right"]},{"key":"m04-bowers-loading","title":"Bowers: The Loading Curve","lesson_keys":["l01-a-second-method","l02-the-loading-curve","l03-the-published-domain","l04-worked-v-at-5-mpa","l05-inverting-the-curve"]},{"key":"m05-unloading-and-the-crosscheck","title":"Unloading and the Cross-Check","lesson_keys":["l01-the-unloading-curve","l02-the-graded-inversion","l03-same-velocity-two-stresses","l04-the-rejoin-and-the-limits","l05-the-crosscheck-on-this-well"]},{"key":"m06-the-window-workflow","title":"The Window Workflow","lesson_keys":["l01-the-workflow-end-to-end","l02-quality-control","l03-the-capstone-walkthrough","l04-onward"]}]}'::jsonb, 1)
on conflict (app_slug, tier) do update
  set structure = excluded.structure,
      content_version = excluded.content_version,
      active = true,
      updated_at = now();

delete from public.academy_quiz_questions
 where app_slug = 'porepressure' and tier = 'advanced';

insert into public.academy_quiz_questions
    (app_slug, tier, scope, module_key, ord, prompt, options, answer_index, explanation)
values
  ('porepressure', 'advanced', 'module', 'm01-from-pressure-to-mud', 1, 'What does the Expert tier add to the Professional tier''s prognosis?', '["The driller''s units, the window between the walls, and an independent cross-check of the floor.", "The Eaton inversion that converts the sonic''s departure into pressure at every sample of the well.", "The hydrostatic and overburden reference frame that all later pressure statements stand on.", "The exact least-squares fit of the compaction trend through the twelve shale picks."]'::jsonb, 0, 'The frame was the Associate tier and the prognosis the Professional. This tier translates, assembles the window, prices the calibration and runs Bowers.'),
  ('porepressure', 'advanced', 'module', 'm01-from-pressure-to-mud', 2, 'Why does a prognosis in MPa fail to answer the driller''s question directly?', '["Because megapascals are too coarse a unit to specify a mud density to the rig''s mixing tolerance.", "Because mud contributes pressure in proportion to depth, so the comparison must be a density.", "Because drillers are trained only on imperial units.", "Because drilling crews are trained on gradients rather than absolute pressures at depth."]'::jsonb, 1, 'One mud column must satisfy two constraints at every exposed depth. Dividing by column height collapses 401 pairs of constraints into one density interval.'),
  ('porepressure', 'advanced', 'module', 'm01-from-pressure-to-mud', 3, 'What is the equivalent mud weight of pressure P at depth z below mudline on this well?', '["P divided by g times z.", "P divided by g times the water depth.", "P divided by g times (z + 100).", "P times g times (z + 100)."]'::jsonb, 2, 'The column runs from sea level: water depth plus depth below mudline. Dividing by z alone is the classic trap, 29.48 kg/m3 heavy at TD.'),
  ('porepressure', 'advanced', 'module', 'm01-from-pressure-to-mud', 4, 'Convert the TD pore pressure, 47.408579625 MPa, to EMW.', '["1208.5824319466892 kg/m3.", "1179.1048116553065 kg/m3.", "1171.9587218876989 kg/m3.", "1029.878048780488 kg/m3."]'::jsonb, 1, 'Divide by 40207.265. The 1208.58 value is the missing-water-column trap, 1171.96 the 25 m rig-floor datum, and 1029.88 the hydrostatic''s EMW.'),
  ('porepressure', 'advanced', 'module', 'm01-from-pressure-to-mud', 5, 'Why does the hydrostatic EMW vary with depth, 1029.55 at 1000 m to 1029.88 at TD, when the pore fluid never changes?', '["Numerical noise accumulated by the engine''s repeated division across the sample loop.", "Compaction raises the pore fluid''s density slightly with every kilometre of additional burial.", "The gravity constant is depth-dependent in the engine.", "The seawater fraction of the column shrinks with depth, pulling the average toward 1030."]'::jsonb, 3, 'EMW is a property of a pressure AT a depth, not of a fluid. Even a perfectly hydrostatic well has a floor that creeps.'),
  ('porepressure', 'advanced', 'module', 'm01-from-pressure-to-mud', 6, 'One MPa of pressure is worth how much EMW at 1000 m versus at 4000 m?', '["92.7 versus 24.9 kg/m3: mud units compress at depth.", "24.9 versus 92.7 kg/m3: the deeper column spreads the same megapascal across more density units.", "The same at both depths, since EMW was constructed to be depth-invariant.", "10.1 versus 14.1 kg/m3, the two gradient values."]'::jsonb, 0, 'The divisor grows with the column. The same megapascal buys 3.7 times fewer density units at TD, which is why shallow hazards dominate in mud units.'),
  ('porepressure', 'advanced', 'module', 'm01-from-pressure-to-mud', 7, 'A rig floor sits 25 m above sea level. What does referencing the TD floor to it do?', '["Nothing: the datum term cancels when floor and ceiling are subtracted to form the window.", "Raises the floor by exactly 25 kg/m3.", "Lowers it to 1171.9587218876989 kg/m3, fourteen tolerances of shift.", "Lowers it by 0.5 kg/m3, one tolerance."]'::jsonb, 2, 'The same pressure over a 4125 m column needs less density. An EMW without its stated datum is not yet a number.'),
  ('porepressure', 'advanced', 'module', 'm01-from-pressure-to-mud', 8, 'The static window this tier computes is bounded by which two quantities?', '["Hydrostatic below and overburden above.", "Pore pressure below and fracture pressure above.", "Kick margin below and ECD above.", "Mud weight below and casing rating above."]'::jsonb, 1, 'The frame pair is the outer bracket and the margins are refinements inside. The static window is the honest first object: pore to fracture, mud at rest.'),
  ('porepressure', 'advanced', 'module', 'm01-from-pressure-to-mud', 9, 'What does the Associate bracket, 1029.878 to 2266.333 kg/m3 at TD, do for this tier?', '["It is the window itself, already refined, and needs no further margin bookkeeping.", "It sets the capstone tolerances.", "It replaces the fracture pressure as the ceiling wherever no leak-off test has been taken.", "Everything this tier computes must land strictly inside it."]'::jsonb, 3, 'Floor 1179.1 and ceiling 1903.9 sit inside the bracket. A converted value outside it is an arithmetic error with no physical reading.'),
  ('porepressure', 'advanced', 'module', 'm01-from-pressure-to-mud', 10, 'Which two graded fields are pure conversions of Professional-tier pressures?', '["The Bowers loading velocity and the unloading stress.", "The floor and ceiling EMWs at TD.", "The n 1.2 pore pressure and the window.", "The onset and the trend value."]'::jsonb, 1, '1179.10 and 1903.92 are this tier''s own pressures divided by the TD column. The window is their subtraction; Bowers and the n 1.2 chain are new machinery.'),
  ('porepressure', 'advanced', 'module', 'm01-from-pressure-to-mud', 11, 'Why do the Bowers tiles on the panel refuse to move when the exponent control flips?', '["Bowers contains no Eaton exponent: that absence is the independence.", "A caching defect in the panel''s implementation of the exponent selector control.", "The tiles are static images of the graded values.", "The exponent only reshapes the prognosis above the detected onset, which the tiles do not sample."]'::jsonb, 0, 'Watching tiles NOT move is information: the second method is computed from its own curves, untouched by the Eaton calibration.'),
  ('porepressure', 'advanced', 'module', 'm01-from-pressure-to-mud', 12, 'What is the operational window for a section, as opposed to the window at one depth?', '["The band''s width averaged over every sample of the exposed open hole below the casing shoe.", "The window at the section''s midpoint depth.", "Max of floor over the hole against min of ceiling: floor-at-bottom, ceiling-at-shoe.", "The narrower of the windows at top and bottom of the section."]'::jsonb, 2, 'One mud must satisfy every exposed depth at once, so the binding constraints are the worst of each wall, which for monotonic walls sit at opposite ends.'),
  ('porepressure', 'advanced', 'module', 'm01-from-pressure-to-mud', 13, 'A 1200 kg/m3 mud stands to TD. What pressure does it exert there, and is the well balanced?', '["48.248718 MPa over the 4100 m column: balanced, inside both walls.", "49.03 MPa over the 4167 m column: balanced with a wide margin.", "46.9 MPa over the 4000 m column: underbalanced by half a megapascal.", "48.2 MPa, but balance cannot be judged until the kick margin and ECD allowances are attached."]'::jsonb, 0, '1200 times 9.80665 times 4100. The mud pressure comparison at a depth is exactly the window test at that depth, run in pressure units.'),
  ('porepressure', 'advanced', 'module', 'm01-from-pressure-to-mud', 14, 'Which quantity is graded in MPa rather than kg/m3 in this tier''s capstone?', '["The window at TD.", "The pore pressure at TD with n 1.2.", "The fracture pressure at TD.", "The floor at TD."]'::jsonb, 1, 'Five fields are mud-unit or velocity values; the exponent probe is graded in its native pressure units, 43.901549937778526 MPa, tolerance 0.01.'),
  ('porepressure', 'advanced', 'module', 'm01-from-pressure-to-mud', 15, 'Why is EMW interpolation between depths unreliable even when pressure interpolation works?', '["EMW values inherently carry fewer significant figures than the pressures they derive from.", "The divisor changes with depth, so equal pressure steps make unequal EMW steps.", "Interpolation between sample depths is disallowed by the capstone''s grading rules.", "EMW is only defined at sample depths."]'::jsonb, 1, 'Mud-unit compression bends the EMW curve even where pressure is linear. Run the machinery at the target depth, or interpolate the residual and reconvert.'),
  ('porepressure', 'advanced', 'module', 'm02-the-window', 1, 'What are the three graded window values at TD?', '["Floor 1179.1048116553065, ceiling 1903.9238599165737, window 724.8190482612672 kg/m3.", "Floor 1029.878048780488, ceiling 2266.333384047207, window 1236.455335266719 kg/m3, the frame''s own bracket rendered as a window.", "Floor 1091.881030400315, ceiling 1874.84926616491, window 782.968235764595 kg/m3.", "Floor 1179.10, ceiling 1780.09, window 600.99 kg/m3."]'::jsonb, 0, 'The second option is the frame bracket, the third is the n 1.2 set, and the fourth pairs the TD floor with the SHOE ceiling, the operational interval rather than the TD window.'),
  ('porepressure', 'advanced', 'module', 'm02-the-window', 2, 'Split the TD floor into its two parts by source of confidence.', '["1030 of pore fluid density plus 149.1 of seawater-fraction correction accumulated down the column.", "1029.878 of frame arithmetic plus 149.227 of interpretation.", "589.55 of water column plus 589.55 of sediment column, the two halves of the divisor.", "1179.1 of measurement with no split available."]'::jsonb, 1, 'The hydrostatic part is near-certain; the 6 MPa of overpressure, 149.23 kg/m3, carries every trend, exponent and screening uncertainty. Error bars belong to the 149.'),
  ('porepressure', 'advanced', 'module', 'm02-the-window', 3, 'Why does the floor''s climb DECELERATE in mud units, 65.8 then 47.5 then 35.9 kg/m3 per 500 m, while the overpressure grows linearly?', '["The ramp itself flattens with depth below 3000 m.", "The ceiling absorbs a progressively larger share of the climb through the mixture as depth increases.", "The deepening column divides the constant 4 kPa per metre by a growing height.", "Floating-point precision loss at the deep samples."]'::jsonb, 2, 'Mud-unit compression: the same pressure increment is worth fewer density units deeper. The MPa picture stays linear; the kg/m3 picture bends.'),
  ('porepressure', 'advanced', 'module', 'm02-the-window', 4, 'Where does the binding ceiling of a section sit, and why?', '["At total depth, where the accumulated overburden makes the rock strongest against tensile failure.", "At the last casing shoe: a rising ceiling''s minimum over the hole is at the top.", "At the depth of the window''s maximum.", "At the mudline, where the fracture pressure''s absolute value is at its smallest anywhere."]'::jsonb, 1, 'The mud may not exceed the ceiling at ANY exposed depth. For a rising curve the worst case is the shallowest exposure: the shoe sets the ceiling, which is why shoes are where leak-offs are taken.'),
  ('porepressure', 'advanced', 'module', 'm02-the-window', 5, 'The mixture identity FP-EMW = two thirds overburden-EMW plus one third floor survives the unit conversion. Why?', '["Because the coefficient K is dimensionless and therefore identical in every unit system.", "Because the engine enforces the identity numerically as a correction step after converting each wall.", "Because EMW is linear in depth.", "Because all three quantities at one depth divide by the same column."]'::jsonb, 3, 'Division by a shared constant preserves weighted averages. Every audit trick from the Professional tier works unmodified in mud units.'),
  ('porepressure', 'advanced', 'module', 'm02-the-window', 6, 'What is the operational window from the 2500 m shoe to TD?', '["1179.10 to 1780.09 kg/m3: TD floor against shoe ceiling, about 601 wide.", "1179.10 to 1903.92, the TD window.", "1029.81 to 1780.09, the shoe''s own bracket.", "1229.10 to 1680.09 kg/m3, the interval left over once the standard operating margins are applied."]'::jsonb, 0, 'Floor-at-bottom against ceiling-at-shoe. The 1229-to-1680 interval is what remains AFTER the worked margins, not the static operational window.'),
  ('porepressure', 'advanced', 'module', 'm02-the-window', 7, 'The window is widest at 2500 m, 750.28 kg/m3, and narrows below. What race sets this shape?', '["The ceiling''s climb against the floor''s: below the onset the floor wins, and the band loses the difference.", "The stress budget against the compaction trend: the trend decays toward matrix faster than the budget grows.", "The hydrostatic against the overburden: they converge below the onset.", "The kick margin against the ECD: both grow with depth."]'::jsonb, 0, 'From 2500 to 3000 m the floor climbs 65.82 and the ceiling 50.68 kg/m3: the band loses exactly the difference, 15.14.'),
  ('porepressure', 'advanced', 'module', 'm02-the-window', 8, 'In PRESSURE units the window WIDENS below the onset, 19.13 to 29.14 MPa, while the mud window narrows. Which statement is honest?', '["The pressure-unit trend is the correct one; the mud picture is an artefact.", "The mud trend is correct; pressure windows are obsolete.", "Both are wrong; the window is constant.", "Both answer different questions; the driller''s is the density one, so the well is gently tightening."]'::jsonb, 3, 'Effective stress grows while density room shrinks. Quoting the MPa trend to claim increasing comfort is a units error dressed as insight.'),
  ('porepressure', 'advanced', 'module', 'm02-the-window', 9, 'Suppose the 4 kPa per metre ramp continued indefinitely below TD. Could it ever close the operational window against the 1780.09 shoe ceiling?', '["Yes, near 5900 m, where extrapolating the current floor slope linearly reaches the shoe ceiling.", "No: the ramp''s EMW contribution asymptotes near 408 kg/m3, saturating the floor near 1438.", "Yes, at exactly twice the current TD.", "No, because the fracture-pressure ceiling always rises to meet the overburden before any closure."]'::jsonb, 1, 'The overpressure EMW is 4000(z-2500)/(9.80665(z+100)), which asymptotes. Knowing when the answer is never is also window arithmetic.'),
  ('porepressure', 'advanced', 'module', 'm02-the-window', 10, 'Which margins spend the window from the floor side?', '["Equivalent circulating density and surge.", "Kick margin and trip margin.", "Datum shift and column error.", "K uncertainty and trend spread."]'::jsonb, 1, 'Kick and trip margins raise the practical minimum mud above the floor; ECD and surge lower the practical maximum below the ceiling. Uncertainties are priced separately.'),
  ('porepressure', 'advanced', 'module', 'm02-the-window', 11, 'With 50 kg/m3 of floor-side margin and 100 of ceiling-side allowances, what is the practical interval for the deep section?', '["1229.10 to 1680.09 kg/m3, about 451 wide.", "1179.10 to 1780.09, unchanged by margins.", "1129.10 to 1880.09 kg/m3: margins act outward and widen the interval available to the mud program.", "1229.10 to 1780.09, only the floor moves."]'::jsonb, 0, 'Minimum practical mud is floor plus margins; maximum is shoe ceiling minus dynamic allowances. The interval that remains is what a mud program actually chooses inside.'),
  ('porepressure', 'advanced', 'module', 'm02-the-window', 12, 'Why can a wide window be dangerous in a different way than a narrow one?', '["Wide windows invite higher pump rates, whose equivalent circulating density then fractures the shoe.", "Wide windows make the leak-off test at the shoe impossible to interpret against the prognosis.", "Crews drift toward the floor for penetration rate, and the margin quietly becomes the plan.", "Regulators require narrower windows for reporting."]'::jsonb, 2, '724 kg/m3 of ceiling room does not change what happens if the mud slips under the floor. Comfort erodes discipline; the floor still marks a real pressure.'),
  ('porepressure', 'advanced', 'module', 'm02-the-window', 13, 'Which failures does the pressure window say NOTHING about?', '["Kicks from underbalance at the bit.", "Losses from exceeding the fracture pressure at the shoe.", "Differential sticking, hole cleaning, and shale-mud chemistry.", "Influx during a trip with the pumps off."]'::jsonb, 2, 'The window is a static hydraulic statement, necessary and never sufficient. Maximum overbalance because the ceiling allows it is how differential sticking happens.'),
  ('porepressure', 'advanced', 'module', 'm02-the-window', 14, 'Moving the shoe from 2500 to 3000 m changes the deep section''s operational window how?', '["Narrows it: setting the shoe deeper exposes progressively weaker rock at the top of the new section.", "Widens it to 651.67 kg/m3: the binding ceiling rises to 1830.77.", "Leaves it unchanged, since the total-depth floor still binds the section from below.", "Eliminates it: no window exists below 3000 m."]'::jsonb, 1, 'Casing deeper raises the binding ceiling on a well whose ceiling rises with depth. The cost is drilling 2500 to 3000 m on the previous section''s program, which this well''s floor permits.'),
  ('porepressure', 'advanced', 'module', 'm02-the-window', 15, 'What does the floor deficit of a mud 25 kg/m3 under the floor at TD convert to in pressure?', '["About 0.1 MPa of underbalance.", "About 10 MPa of underbalance.", "About 1 MPa: the deficit times the 40207.265 column factor.", "Zero effective underbalance until the deficit has consumed the kick margin carried above the floor."]'::jsonb, 2, '25 times 40207.265 Pa is 1.005 MPa: the drive pushing formation fluid in. The conversion runs both directions, and reading deficits in both units is a working habit.'),
  ('porepressure', 'advanced', 'module', 'm03-the-exponent-lever', 1, 'Compute the graded pore pressure at TD under n 1.2.', '["43.901549937778526 MPa.", "47.408579625 MPa.", "43.808579625 MPa.", "41.408579625 MPa."]'::jsonb, 0, 'Budget times (1 minus the ratio to the 1.2), plus hydrostatic. The 43.81 value is the linearised 40-percent shortcut, outside tolerance by ten times.'),
  ('porepressure', 'advanced', 'module', 'm03-the-exponent-lever', 2, 'What is the TD ratio raised to the 1.2 power?', '["0.8793108342707514.", "0.9498542487938293.", "0.9580337483265022.", "0.9436991025399956."]'::jsonb, 1, 'Via logarithms: e to the 1.2 times ln(0.9580337483265022). The others are the cube, the raw ratio, and the 3000 m cube.'),
  ('porepressure', 'advanced', 'module', 'm03-the-exponent-lever', 3, 'Why is 1.2 the capstone''s chosen alternative exponent?', '["It is the smallest value the engine accepts.", "It is the classic low calibration, tied to seismic-velocity work and gentler basins.", "It makes the TD overpressure land at exactly 40 percent of the n 3 value, by design of the fixture.", "It is the value the exact least-squares routine returns when fitted to this well''s twelve shale picks."]'::jsonb, 1, 'The pair 3 and 1.2 spans the practical range. On this well 3 is right by construction; on a real well the pair brackets until data discriminates.'),
  ('porepressure', 'advanced', 'module', 'm03-the-exponent-lever', 4, 'What is the exponent''s throw on the TD mud floor?', '["87.22378125499152 kg/m3, floor 1179.10 down to 1091.88.", "29.07 kg/m3, the ceiling''s move.", "58.15 kg/m3, the amount by which the mud window itself widens under the lower calibration.", "3.507 kg/m3, the pressure difference."]'::jsonb, 0, 'Choosing the exponent IS choosing a mud floor 87 kg/m3 apart. The ceiling moves a third of that and the window two thirds; 3.507 is in MPa, not mud units.'),
  ('porepressure', 'advanced', 'module', 'm03-the-exponent-lever', 5, 'Under n 1.2 the window at TD becomes 782.968235764595 kg/m3. Verify it in one line.', '["Two thirds of (2266.333384047207 minus 1091.881030400315).", "The n 3 window plus the floor throw.", "Two thirds of (2266.333384047207 minus 1179.1048116553065).", "1874.84926616491 minus 1091.881030400315, less the kick, trip, circulating and surge allowances."]'::jsonb, 0, 'The K-algebra route: two thirds of the overburden-EMW-minus-floor gap. Adding the full throw to the old window over-counts; the window gains only two thirds of it.'),
  ('porepressure', 'advanced', 'module', 'm03-the-exponent-lever', 6, 'Where do the two calibrations agree exactly, and why?', '["At total depth, where the capstone anchors both calibrations to the same graded pressure value.", "Nowhere: they differ at every sample.", "Everywhere at and above the ramp top, where the ratio is 1.", "Only at the detected onset depth itself, where both calibrations first clear the threshold."]'::jsonb, 2, 'Evidence discriminates only where the anomaly exists. The disagreement grows from zero at 2500 m to its maximum at the deepest, most expensive hole.'),
  ('porepressure', 'advanced', 'module', 'm03-the-exponent-lever', 7, 'What happens to the detected onset under n 1.2?', '["It stays at 2520 m, because onset detection reads the ratio, which does not contain the exponent.", "2540 m: the quieter anomaly needs more ramp to clear 0.05 MPa.", "It moves to 2510 m, since lower exponents sharpen the detector''s response to the ramp.", "It becomes undefined below 1 exactly."]'::jsonb, 1, 'Same rule, quieter anomaly: 0.016 MPa at 2510 under n 1.2, first clearing the bar at 2540. The mechanism still starts at 2500.'),
  ('porepressure', 'advanced', 'module', 'm03-the-exponent-lever', 8, 'What does the window''s SHAPE do when the calibration drops to 1.2?', '["It keeps narrowing below the onset exactly as at n 3, but starting from a higher value at the ramp top.", "It becomes exactly flat below the onset.", "It narrows twice as fast, since the floor is lower.", "It flips: the window widens with depth below the onset, 750.28 to 782.97."]'::jsonb, 3, 'At n 1.2 the floor''s ramp climb, 62.07 kg/m3, no longer outruns the ceiling. Window shape is calibration-conditional and must be re-read after any refit.'),
  ('porepressure', 'advanced', 'module', 'm03-the-exponent-lever', 9, 'When does the exponent choice become a feasibility question rather than an optimisation?', '["When the throw is comparable to the slack left after margins.", "Whenever the window exceeds 700 kg/m3.", "Only when the compaction trend is simultaneously in dispute, since the two levers multiply together.", "When the two calibrations disagree about the onset by more than one sample."]'::jsonb, 0, 'On this well both calibrations drill comfortably; squeeze the interval and 87 kg/m3 of floor disagreement decides whether the section is drillable as designed.'),
  ('porepressure', 'advanced', 'module', 'm03-the-exponent-lever', 10, 'Rank the evidence that settles an exponent argument, strongest first.', '["Mechanism reasoning, offset calibration, drilling events, direct measurements, in that descending order.", "Measurements, drilling events, offset calibration, mechanism reasoning.", "Offset-well calibration, direct measurements, mechanism, drilling events.", "Drilling events, mechanism, direct measurements, offsets."]'::jsonb, 1, 'One good wireline point in the anomalous section outranks every argument; a shut-in pressure is a measurement paid for the hard way; offsets import assumptions; mechanism is weakest but not empty.'),
  ('porepressure', 'advanced', 'module', 'm03-the-exponent-lever', 11, 'An RFT at 2400 m reads exactly hydrostatic. What does it contribute to the exponent argument?', '["It endorses n 3, whose curve passes through the hydrostatic at that depth within the instrument accuracy.", "It endorses n 1.2, since the low calibration is nearer hydrostatic.", "It splits the difference, supporting a refit near 2.", "Nothing: above the onset every exponent predicts the same hydrostatic."]'::jsonb, 3, 'It confirms the normal section and the trend''s quietness, valuable for the trend defence, silent on n. Evidence discriminates only where the calibrations disagree.'),
  ('porepressure', 'advanced', 'module', 'm03-the-exponent-lever', 12, 'A measured 42.0 MPa at 3800 m lands between the calibrations'' predictions, 44.588 and 41.542. What is standard practice?', '["Snap the program to n 1.2, since the measurement lands measurably nearer the low preset''s curve.", "Fit the exponent to the point, near 1.46, and rerun everything downstream.", "Average the two prognoses depth by depth and carry the mean curve into the program.", "Discard the point as inconsistent with both."]'::jsonb, 1, 'Presets bracket, data interpolates: solve 1 minus r to the n for the observed handover fraction. That is what calibration means.'),
  ('porepressure', 'advanced', 'module', 'm03-the-exponent-lever', 13, 'How should a plan behave while the exponent is still undiscriminated?', '["Publish the labelled band, design each decision to its conservative wall, name the discriminator.", "Adopt n 3 everywhere as the conservative option, since higher pressure predictions are always safer.", "Choose n 1.2 everywhere, to avoid overstating pressure.", "Defer all drilling until a measurement exists."]'::jsonb, 0, 'A single calibration cannot be conservative for both walls at once: high n is safe for mud, low n for ceiling commitments. The band plus a named trigger is the honest object.'),
  ('porepressure', 'advanced', 'module', 'm03-the-exponent-lever', 14, 'Why is averaging the two floors, 1179.10 and 1091.88, the wrong resolution?', '["Averages of prognoses must be weighted by each depth''s stress budget before they become meaningful.", "The average describes NO calibration; mud is pumped at one density.", "The average would violate the frame bracket at the deepest section of the well.", "Averaging is acceptable and standard."]'::jsonb, 1, 'A compromise line drills no well. Design to the conservative wall per decision and let measurement collapse the band.'),
  ('porepressure', 'advanced', 'module', 'm03-the-exponent-lever', 15, 'The kick at 3900 m implies 46.8 MPa against the n 3 curve''s 45.998 there. What does the refit do?', '["Pins n slightly above 3, following the sign of the miss.", "Pins n at exactly 3, within tolerance.", "Pins n near 1.46, as with the 3800 m point.", "Rejects the kick data, since shut-in readings are systematically biased low by gas migration effects."]'::jsonb, 0, 'The observed overpressure exceeds the n 3 prediction''s, so the fitted exponent lands a little over 3. Refit direction follows the sign of the miss.'),
  ('porepressure', 'advanced', 'module', 'm04-bowers-loading', 1, 'Write the Bowers loading relation.', '["V = Vml + A sigma^B, stress in psi, velocity in ft/s.", "V = Vml times sigma to the B, in SI units throughout.", "V = A times (sigma minus Vml) to the B.", "dt = dtma + (dtml - dtma) e to the minus cz, evaluated on the well''s own header parameters."]'::jsonb, 0, 'Velocity is mudline velocity plus a power law in effective stress, in the published domain. The last option is the compaction trend, the equation Bowers exists to be independent of.'),
  ('porepressure', 'advanced', 'module', 'm04-bowers-loading', 2, 'What makes Bowers a genuinely second method beside Eaton?', '["It consumes the density log rather than the sonic, so the two methods share no wireline input at all.", "No depth trend, no Eaton exponent, its own failure modes; only the frame is shared.", "It requires no basin calibration at all, since A and B are universal constants of shale physics.", "It measures pressure directly rather than inferring it."]'::jsonb, 1, 'Different mathematics on the same log. Agreement defends against trend, exponent and implementation error; the shared sonic and frame are what it cannot defend.'),
  ('porepressure', 'advanced', 'module', 'm04-bowers-loading', 3, 'What velocity does the loading curve assign to rock at zero effective stress?', '["Zero.", "1524 m/s: 5000 ft/s converted.", "1500 m/s, the seawater velocity.", "The matrix velocity of about 4545 m/s, one million over the 220 us/m matrix transit time."]'::jsonb, 1, 'A sediment carrying no grain load is as slow as mudline ooze whatever its depth: the equation asserting that velocity tracks stress, not burial.'),
  ('porepressure', 'advanced', 'module', 'm04-bowers-loading', 4, 'Compute the graded loading velocity at 5 MPa.', '["1949.944709834568 m/s.", "2240.3507591923435 m/s.", "6397.4563970950385 m/s.", "1425.944709834568 m/s."]'::jsonb, 0, '725.1886886510462 psi, to the 0.75, times 10, plus 5000, times 0.3048. The 6397 figure is the ft/s value before conversion; 2240.35 is the 10 MPa point.'),
  ('porepressure', 'advanced', 'module', 'm04-bowers-loading', 5, 'Why does the engine keep A and B in the published ft/s and psi domain instead of converting them once to SI?', '["Because imperial units remain the contractual convention for reporting on most offshore drilling projects.", "Because B cannot be converted at all.", "A''s conversion depends on B, so pre-converted tables invite mismatched pairs; edge conversion is error-proofing.", "Because SI conversion loses precision at the fourth decimal."]'::jsonb, 2, 'A multiplies sigma to the B, so its units involve psi to the 0.75. Converting it correctly per-B is fragile; converting at the edges is safe and matches the oracle.'),
  ('porepressure', 'advanced', 'module', 'm04-bowers-loading', 6, 'What is the inversion of the loading curve?', '["sigma = ((V_fts - 5000)/A)^(1/B), converted at the edges.", "sigma = A times (V minus Vml) to the B, with the coefficient and power applied in the forward order.", "sigma equals the natural log of V over Vml, divided by the coefficient B.", "sigma equals (V over A) to the B minus Vml."]'::jsonb, 0, 'Undo the offset, the coefficient, then the power: the outer exponent becomes 4/3, above one, which is where the error amplification lives.'),
  ('porepressure', 'advanced', 'module', 'm04-bowers-loading', 7, 'At the TD point, a 10 m/s velocity error becomes how much effective stress error?', '["About 0.027 MPa.", "About 0.27 MPa.", "About 2.7 MPa.", "About 0.94 MPa, the equivalent-mud-weight cost of the cross-check gap converted back into stress."]'::jsonb, 1, 'The engine''s perturbation: 43.75 to 44.02 MPa for plus 10 m/s. Thirty-seven m/s of sonic bias is a full megapascal of pressure; 0.94 is the EMW cost in kg/m3 of 0.038 MPa.'),
  ('porepressure', 'advanced', 'module', 'm04-bowers-loading', 8, 'Why is the inversion structurally fragile just above 1524 m/s?', '["The engine refuses to invert any velocity below 2000 m/s as a guard against exactly this fragility.", "V minus Vml is tiny there, its relative error huge, and the 4/3 power amplifies it.", "The psi conversion overflows double precision at stresses below about one megapascal of effective load.", "Slow rock violates the loading assumption."]'::jsonb, 1, 'Shallow, slow sediment gives fragile Bowers stresses, which is why shallow-hazard work leans on the frame and analogues rather than velocity inversion.'),
  ('porepressure', 'advanced', 'module', 'm04-bowers-loading', 9, 'A cemented streak inverts to an effective stress above the overburden. What is the honest reading?', '["The pore pressure there is genuinely negative.", "The overburden must be recomputed upward.", "sigma_max has been exceeded and unloading has begun.", "Off-model rock: lithology read as compaction, the Bowers cousin of Eaton''s fast-side trap."]'::jsonb, 3, 'Fast rock that is not compaction-fast implies impossible stress. The screening discipline is shared between the methods because the failure is.'),
  ('porepressure', 'advanced', 'module', 'm04-bowers-loading', 10, 'What does the FORWARD direction of the loading curve certify in practice?', '["The calibration: evaluate at known-pressure depths and compare with the log.", "The onset depth of overpressure.", "The fracture pressure at the shoe.", "Nothing: professional practice runs only the inversion, and the forward form exists for teaching alone."]'::jsonb, 0, 'Forward residuals at measured-pressure points are the evidence A and B fit the basin, the same epistemology as calibrating Eaton''s n.'),
  ('porepressure', 'advanced', 'module', 'm04-bowers-loading', 11, 'On this well the forward evaluation at the TD''s known stress gives 3689.682402180745 m/s against a log of 3691.0906301457703. What is that 1.408 m/s?', '["The fit residual of A and B: the whole source of the 0.038 MPa gap.", "Residual instrument error deliberately mixed into the synthetic sonic to imitate a real wireline tool.", "The unloading correction at TD, which the loading fit absorbs into its residual by construction.", "Float32 truncation in the goldens file."]'::jsonb, 0, 'The well was built through Eaton, and the two-parameter Bowers curve describes it imperfectly. Tracing a residual to its source is part of running a cross-check.'),
  ('porepressure', 'advanced', 'module', 'm04-bowers-loading', 12, 'Which assumption gives the LOADING curve its name?', '["The rig loads the formation during drilling.", "Effective stress only ever increased: velocity and stress walked up together.", "The sonic tool loads the borehole wall.", "Sediment loading is the only overpressure mechanism the two-curve Bowers system is able to describe."]'::jsonb, 1, 'Undercompaction respects it: stress stalls but never retreats. Stress REDUCTION after burial breaks it, and that rock follows the flatter unloading path.'),
  ('porepressure', 'advanced', 'module', 'm04-bowers-loading', 13, 'Compute the loading velocity at 20 MPa by the five-step chain.', '["2728.7535709382373 m/s.", "2801.16 m/s, the value obtained when the psi conversion is taken at 20 MPa but the power at 25.", "8952.6 m/s.", "2240.3507591923435 m/s."]'::jsonb, 0, '2900.7547546041847 psi, to the 0.75 is 395.2603579193691, times 10 plus 5000 is 8952.6 ft/s, times 0.3048. The ft/s figure before conversion is the classic slip.'),
  ('porepressure', 'advanced', 'module', 'm04-bowers-loading', 14, 'The curve rises 426 m/s over the first 5 MPa but only 228 over the 6.2 MPa from 43.8 to 50. Why?', '["The mudline offset''s share saturates once stress dominates.", "The psi conversion is nonlinear.", "B below 1 flattens the curve: each megapascal stiffens less than the last.", "Velocity approaches the seawater ceiling."]'::jsonb, 2, 'A power 0.75 decelerates. Read backward, the flat deep curve becomes a steep inversion, which is the error-gain story.'),
  ('porepressure', 'advanced', 'module', 'm04-bowers-loading', 15, 'For a Bowers pore pressure good to 0.5 MPa at TD, the velocity must be good to roughly what?', '["About 1.9 m/s.", "About 190 m/s, since the tolerance divides by the 0.0269 gain and then scales by ten for safety.", "About 18.6 m/s, half of one percent of the reading.", "About 0.5 m/s, exactly matching the graded tolerance of the field."]'::jsonb, 2, 'At 0.0269 MPa per m/s, 0.5 MPa needs about 18.6 m/s. Comparable in relative terms to what Eaton demands of its trend: neither method is the cheap one.'),
  ('porepressure', 'advanced', 'module', 'm05-unloading-and-the-crosscheck', 1, 'Why does an unloaded rock''s velocity not walk back down the loading curve?', '["Because the sonic tool measures the fastest path, which never registers a stiffness decrease in situ.", "Compaction is largely irreversible: lost porosity stays lost, only elastic stiffness relaxes.", "Because pore pressure locks the velocity at its maximum.", "Because the loading curve is only defined for increasing depth."]'::jsonb, 1, 'The rock keeps most of the stiffness its maximum stress built, so unloading follows a much flatter velocity-stress path.'),
  ('porepressure', 'advanced', 'module', 'm05-unloading-and-the-crosscheck', 2, 'Which two parameters does the unloading form add?', '["The mudline velocity and the matrix velocity.", "A second coefficient and power, A2 and B2, fitted independently to the unloaded section''s samples.", "sigma_max, the maximum stress ever carried, and U, the irreversibility exponent.", "The onset depth and the detection threshold, imported from the Eaton half of the tier."]'::jsonb, 2, 'The golden fixture uses 50 MPa and 3. Neither is readable from a single log: sigma_max is history, U is calibrated where measured pressures exist in unloaded sections.'),
  ('porepressure', 'advanced', 'module', 'm05-unloading-and-the-crosscheck', 3, 'What does U = 1 do to the unloading curve?', '["Collapses it onto the loading curve exactly: no irreversibility.", "Makes it perfectly flat at the sigma_max velocity, which is the limit of total irreversibility instead.", "Makes the inversion undefined.", "Doubles the mudline velocity."]'::jsonb, 0, 'The inner bracket becomes sigma itself. Large U is the flat, irreversible limit; U = 1 is no memory at all.'),
  ('porepressure', 'advanced', 'module', 'm05-unloading-and-the-crosscheck', 4, 'Where do the loading and unloading curves meet, exactly?', '["At the mudline velocity, 1524 m/s, which both forms share as their zero-stress intercept by construction.", "At sigma_max: vUnloading(50 of 50) equals vLoading(50) as identical doubles.", "At 10 MPa, the graded point.", "They never meet at any stress: permanent separation is what makes them two distinct curves."]'::jsonb, 1, 'The unloading path begins where stress starts falling, at which moment the rock is a loading rock at sigma_max. The rejoin anchors the high end to the loading calibration.'),
  ('porepressure', 'advanced', 'module', 'm05-unloading-and-the-crosscheck', 5, 'Run the graded inversion: what effective stress does the unloading form read from 3125.808993287662 m/s with sigma_max 50 MPa and U 3?', '["29.240177382128643 MPa.", "10 MPa, to fourteen decimals.", "15.625 MPa.", "3.42 MPa."]'::jsonb, 1, 'Loading-equivalent 29.24, over 50, cubed, times 50. The 29.24 is where the LOADING inversion stops; 15.625 is the sigma_max 40 variant and 3.42 the U 5 variant.'),
  ('porepressure', 'advanced', 'module', 'm05-unloading-and-the-crosscheck', 6, 'Why is the graded answer exactly 10?', '["Because 10 MPa is the effective stress at the ramp top, which the fixture placed there deliberately.", "Because U 3 always produces round numbers.", "Because psi and MPa happen to align at that stress.", "Because the fixture computed 3125.808993287662 m/s AS the unloading velocity at 10 MPa."]'::jsonb, 3, 'Known answer, exact recovery, machinery certified: the Bowers version of the Eaton ramp. The roundness certifies arithmetic, not the parameters it stands on.'),
  ('porepressure', 'advanced', 'module', 'm05-unloading-and-the-crosscheck', 7, 'The same 3125.8 m/s read on the LOADING curve gives what, and what does the pair teach?', '["10 MPa: below sigma_max the two curves agree, so the reading is independent of the assumed history.", "29.240177382128643 MPa: same measurement, 2.9x apart by assumed history.", "50 MPa exactly, since the loading curve saturates at the maximum stress parameter.", "1524 m/s: the question is ill-posed."]'::jsonb, 1, '19.24 MPa of stress gap passes straight into pore pressure with opposite sign. Choosing the wrong curve is the largest error available in the module.'),
  ('porepressure', 'advanced', 'module', 'm05-unloading-and-the-crosscheck', 8, 'Reading an UNLOADED rock with the LOADING curve errs in which direction?', '["Under-reads pore pressure: the dangerous, kick-side direction.", "Over-reads pore pressure, which wastes mud weight but keeps the well safe from influx at all times.", "No error: the curves agree below sigma_max.", "Errs randomly per sample."]'::jsonb, 0, 'Loading misattributes remembered stiffness to present stress, so effective stress reads high and pore pressure low, by 19.24 MPa on the graded pair.'),
  ('porepressure', 'advanced', 'module', 'm05-unloading-and-the-crosscheck', 9, 'Which observed pair is the classic unloading fingerprint?', '["Sonic slowing with density falling together, the pair moving in proportion to the porosity increase.", "Sonic slowing while density stays flat.", "Both sonic and density rising with depth.", "Density falling while sonic is flat."]'::jsonb, 1, 'Unloaded rock kept its compaction, so it stays dense while the elastic stiffness relaxes. Slow AND light is undercompaction instead; the pair separates the mechanisms.'),
  ('porepressure', 'advanced', 'module', 'm05-unloading-and-the-crosscheck', 10, 'What are the three discriminators for choosing the unloading curve, in practice?', '["Water depth, mud weight and bit size.", "The exponent, the threshold and the trend.", "An unloading mechanism, a velocity reversal, and the sonic-density split.", "Leak-off pressure at the shoe, the kick history of the offsets, and the rate of penetration trend."]'::jsonb, 2, 'Mechanism first: asserting history needs evidence. This well shows none of the three, which is why the loading reading stands.'),
  ('porepressure', 'advanced', 'module', 'm05-unloading-and-the-crosscheck', 11, 'Assuming sigma_max 25 MPa for this well''s TD velocity produces 134 MPa of claimed stress and negative pore pressure. What went wrong?', '["The engine''s power function overflowed on the cubed ratio and returned a garbage stress value.", "The velocity was converted from metres to feet twice in sequence before the inversion.", "The overburden is too small at TD.", "Inconsistent history: the loading-equivalent 43.75 exceeds the claimed maximum of 25."]'::jsonb, 3, 'A rock cannot sit above the curve it departed from. The absurd output traces to the impossible assumption, which is the system working.'),
  ('porepressure', 'advanced', 'module', 'm05-unloading-and-the-crosscheck', 12, 'The Eaton and Bowers pore pressures at TD are 47.408579625 and 47.37067524651197 MPa. What does the 0.038 MPa agreement certify?', '["The mechanism is undercompaction on the loading curve, confirmed without assuming it.", "That n = 3 is correct in every basin.", "That the sonic log is error-free.", "That the unloading parameters sigma_max 50 and U 3 are correctly calibrated for this particular basin."]'::jsonb, 0, 'Two routes sharing no trend or exponent converge; the residual traces to the loading fit. It does not certify the shared inputs, sonic and frame.'),
  ('porepressure', 'advanced', 'module', 'm05-unloading-and-the-crosscheck', 13, 'Why do the methods drift apart mid-ramp, 1.509 MPa at 3000 m, while nearly agreeing at TD?', '["The encoded ramp is deliberately nonlinear between the two graded depths, and the methods read it differently.", "A two-parameter power law cannot hug the encoding at every stress: the drift is fit geometry.", "Eaton loses its accuracy away from the single depth at which its exponent was originally calibrated for this well.", "The overburden is uncertain at 3000 m."]'::jsonb, 1, 'Trust cross-checks most at calibration anchors and read mid-span disagreement as fit quality first, screening second, mechanism third.'),
  ('porepressure', 'advanced', 'module', 'm05-unloading-and-the-crosscheck', 14, 'What would a 3 MPa Bowers-below-Eaton disagreement at TD, with clean fits and screens, suggest?', '["The detection threshold is set too low.", "The exponent should be raised to 4.", "The rock has begun to unload: loading mis-reads remembered stiffness.", "The water depth is wrong by roughly 300 m, shifting the hydrostatic that both methods reference."]'::jsonb, 2, 'Bowers-below-Eaton with clean fit is the loading curve under-reading pressure, the unloading signature. The check order is fit, screening, mechanism.'),
  ('porepressure', 'advanced', 'module', 'm05-unloading-and-the-crosscheck', 15, 'What is the sharpest limit on what Eaton-Bowers agreement can prove?', '["Both share the sonic and frame, so a biased input moves them together, invisibly.", "Agreement between any two methods is coincidence at some depth of every well, by continuity.", "The two methods share the exponent n through the shared frame arithmetic they both consume.", "Bowers cannot run below 2500 m."]'::jsonb, 0, 'Independent mathematics, shared data. A truly independent check needs different DATA: measured pressures, drilling response, resistivity methods.'),
  ('porepressure', 'advanced', 'module', 'm06-the-window-workflow', 1, 'Which four new steps does the Expert workflow add to the Professional seven?', '["Convert on a stated datum; assemble the window; price the calibration; cross-check the mechanism.", "Fit the trend; screen; invert; detect the onset.", "Run the frame; check orderings; close the loop; write the report.", "Kick drill, casing pressure test, cement bond log, and the section handover meeting, in rig order."]'::jsonb, 0, 'Plus the report, which consumes everything. The middle distractor is the Professional core; the workflow is a dependency chain either way.'),
  ('porepressure', 'advanced', 'module', 'm06-the-window-workflow', 2, 'Where must every converted EMW value land, as a standing sanity check?', '["Within 0.5 kg/m3 of one of the six graded capstone fields, the stated tolerance of the exam form.", "Strictly inside the frame''s own EMW curves at that depth.", "Between 1000 and 2266 kg/m3, the physically admissible density range for any drilling fluid.", "Below the previous section''s mud weight."]'::jsonb, 1, 'Floor and ceiling live inside the hydrostatic-to-overburden bracket everywhere. A wall outside it is arithmetic error with no physical reading.'),
  ('porepressure', 'advanced', 'module', 'm06-the-window-workflow', 3, 'The hydrostatic EMW converting to a value a hair BELOW the pore fluid density is which check passing?', '["The commutation check, which verifies the conversion agrees along the subtract-first and convert-first routes.", "The bracket check.", "The datum check: the seawater-fraction signature confirms the column.", "The shape re-read."]'::jsonb, 2, '1029.878 against 1030 at TD. A result of exactly 1030 means the water column was dropped from pressure and height together.'),
  ('porepressure', 'advanced', 'module', 'm06-the-window-workflow', 4, 'What does the commutation check verify?', '["That the panel and the engine agree.", "That windows agree along every route: subtract-convert, convert-subtract, K-algebra.", "That the exponent choice commutes with the trend choice everywhere in the finished, converted window.", "That the equivalent mud weight of each wall rises monotonically with depth over the exposed section."]'::jsonb, 1, 'Worst disagreement in the thirteenth digit on this well. It catches transcription between tables computed at different times, and hidden re-rounding.'),
  ('porepressure', 'advanced', 'module', 'm06-the-window-workflow', 5, 'Why must window shape be RE-READ after any recalibration?', '["Because the engine caches the previous calibration''s shape until the panel control is toggled twice.", "Shape is calibration-conditional: n 3 narrows below the onset, n 1.2 widens, moving any pinch.", "Because moving the shoe depth during planning invalidates the calibration the shape was read under.", "Because tolerance fields depend on the shape."]'::jsonb, 1, 'Stale section logic is the failure: a shoe planned against a pinch the refit moved. The narrowest depth is an output, not an assumption.'),
  ('porepressure', 'advanced', 'module', 'm06-the-window-workflow', 6, 'A contractor''s window shows floor 1208.6 and ceiling 1951.5 at TD, internally consistent, inside the bracket. Which check fires?', '["The bracket check, since a floor of 1208.6 kg/m3 falls outside the frame''s own EMW envelope at TD.", "The commutation check.", "The shape re-read.", "The datum check: both are divide-by-4000 values, the water column dropped twice."]'::jsonb, 3, 'The width, 742.9, is nearly right because the error partially cancels in subtraction. Walls first, width second: a width-only review would have approved it.'),
  ('porepressure', 'advanced', 'module', 'm06-the-window-workflow', 7, 'A window of 812.04 kg/m3 is quoted with floor 1091.88 and ceiling 1903.92. What happened?', '["Mixed provenance: an n 1.2 floor beside an n 3 ceiling, exposed by the K-algebra.", "Nothing: the width is inside both calibrations'' range.", "A datum slip of 25 m applied to the ceiling alone, leaving the floor on sea level.", "The kick margin was mistakenly added to the static window before the walls were written down."]'::jsonb, 0, 'Each wall is individually plausible and the pair is impossible. Widths and walls must reconcile through the algebra.'),
  ('porepressure', 'advanced', 'module', 'm06-the-window-workflow', 8, 'What is the six-line summary''s calibration line for this well?', '["n 1.2 rejected outright: the closed loop and the Bowers cross-check both independently select 3 on this well.", "n fixed at 3 by industry convention; no alternative computed.", "n 1.2 floor 1091.88, throw 87.22, inside slack; discriminator named; refit protocol stated.", "Exponent immaterial on wide windows."]'::jsonb, 2, 'The line carries the alternative, its price, the verdict that it fits, and the trigger that would change it. On THIS well the loop does select 3, but the plan line documents the band.'),
  ('porepressure', 'advanced', 'module', 'm06-the-window-workflow', 9, 'The margins ledger exists to catch which failure?', '["Leak-off tests taken at the wrong casing shoe and carried into the ceiling at the wrong depth.", "Excessive conservatism in kick margins.", "Rig crews quietly ignoring the mud program''s stated margins during connections and long trips.", "The double-spend: the same room counted against two margins by two documents."]'::jsonb, 3, 'Every margin named, sized and subtracted in the open, so the discovery happens on the list rather than on the rig.'),
  ('porepressure', 'advanced', 'module', 'm06-the-window-workflow', 10, 'Which graded field is the only full re-run of the Professional chain?', '["The window at TD, which requires re-running both walls from their pressure forms at full precision.", "The pore pressure at TD under n 1.2.", "The Bowers unloading stress, whose inversion re-runs the full loading chain plus the remapping layer.", "The floor at TD."]'::jsonb, 1, 'The conversions are one division each and Bowers is curve evaluation; the n 1.2 field re-runs ratio, power, budget and sum with a non-integer exponent.'),
  ('porepressure', 'advanced', 'module', 'm06-the-window-workflow', 11, 'The floor field''s classic slip divides by 4000 m instead of 4100. How wrong is it, in tolerances?', '["About one tolerance, which is why the field is considered forgiving of column mistakes.", "About six tolerances.", "About sixty: 29.48 kg/m3 against a 0.5 tolerance.", "It passes, since the bracket absorbs it."]'::jsonb, 2, '1208.58 against 1179.10. The bracket check alone does NOT catch it, which is why the column is checked at the input.'),
  ('porepressure', 'advanced', 'module', 'm06-the-window-workflow', 12, 'Which protection catches confusing the unloading inversion''s answer with its loading-equivalent intermediate?', '["Unwinding the formula from the outside in, so 29.24 is visibly a middle line.", "The bracket check.", "The datum declaration.", "Rounding each layer to the 0.01 MPa tolerance as it is computed, so errors cannot accumulate silently."]'::jsonb, 0, 'Stopping at 29.240177382128643 answers the wrong history. The staged layout makes the final over-50-cubed-times-50 step impossible to skip silently.'),
  ('porepressure', 'advanced', 'module', 'm06-the-window-workflow', 13, 'What does the linearised 40-percent shortcut give for the n 1.2 field, and why does it fail?', '["43.808579625 MPa: outside tolerance ten times over, because the fraction is not linear in n.", "43.901549937778526 MPa: the shortcut lands within the stated tolerance and is accepted practice.", "41.408579625 MPa: it collapses to hydrostatic.", "44.6 MPa: the shortcut overshoots because linearisation always overstates a concave function''s value."]'::jsonb, 0, 'Hydrostatic plus 0.4 times 6. The true fraction ratio is 0.4155, not 0.4000; the shortcut degrades exactly when pressures matter.'),
  ('porepressure', 'advanced', 'module', 'm06-the-window-workflow', 14, 'Time allocation for the capstone sitting should weight what most heavily?', '["The three EMW conversions, which carry the loosest tolerances and therefore reward extra checking time.", "Transcribing all sixteen digits of each expected value into the form without a single character slip.", "The Bowers unit edges and the n 1.2 chain, then the protections.", "The window subtraction."]'::jsonb, 2, 'Conversions are two minutes. The chain and the unit crossings carry the risk, and the remaining time belongs to the checks that separate a submission from an attempt.'),
  ('porepressure', 'advanced', 'module', 'm06-the-window-workflow', 15, 'After this tier, which two ladders does the course point to next, and why?', '["Rock Physics, for the other reading of velocity, and Basin, for burial histories.", "Mapping and ReservoirCalc, whose volumetrics chain consumes the mud window as its starting surface.", "Well Data and Petrophysics, which remain formal prerequisites for the certification chain itself.", "Seismolord alone, for the wavelet."]'::jsonb, 0, 'A velocity anomaly reads as fluid and frame in one course and as effective stress in this one; telling gas from overpressure uses both. Basin''s decompaction supplies unloading''s history.'),
  ('porepressure', 'advanced', 'final', null, 1, 'What is the equivalent mud weight of the TD fracture pressure?', '["1951.5219564144882 kg/m3, over the sediment column alone.", "1903.9238599165737 kg/m3.", "2266.333384047207 kg/m3, the frame''s ceiling.", "1780.090931942938 kg/m3, the value at the shoe."]'::jsonb, 1, '76551571.17548856 over 40207.265. The distractors are the missing-water trap, the overburden, and the 2500 m ceiling.'),
  ('porepressure', 'advanced', 'final', null, 2, 'State the mud-weight window at TD and its tolerance.', '["29.14299155048856 MPa, tolerance 0.01, as the tier below reported it.", "600.99 kg/m3, tolerance 0.5.", "600.99 kg/m3, tolerance 0.5, the shoe-to-TD operational interval.", "724.8190482612672 kg/m3, tolerance 0.5."]'::jsonb, 3, 'Ceiling minus floor at TD. The MPa value is the same gap in pressure units; 600.99 is the operational shoe-to-TD interval; 782.97 is the n 1.2 window.'),
  ('porepressure', 'advanced', 'final', null, 3, 'Why is the column height at TD 4100 m rather than 4000?', '["The EMW reference is sea level, so the 100 m of water joins the column.", "The kelly bushing adds 100 m.", "The engine pads the column by 2.5 percent.", "It is really 4000, and the 4100 is a display convention inherited from the reporting software."]'::jsonb, 0, 'Every EMW in the course divides by g times (z plus 100). Dropping the water is a sixty-tolerance error on the floor field.'),
  ('porepressure', 'advanced', 'final', null, 4, 'Which value differs between a sea-level and a rig-floor datum 25 m higher, and by how much at the TD floor?', '["Nothing differs, because the datum term cancels identically when the walls are subtracted to form windows.", "The floor reads 7.15 kg/m3 lighter on the rig-floor datum.", "The floor reads 25 kg/m3 heavier, one for one with the air gap''s height.", "Only the ceiling shifts."]'::jsonb, 1, 'Same pressure, taller column, less density: 1171.96 against 1179.10. Fourteen tolerances from 25 m of air; the datum line is not boilerplate.'),
  ('porepressure', 'advanced', 'final', null, 5, 'The floor at TD splits into 1029.878 plus 149.227 kg/m3. What is the second part?', '["The seawater-fraction correction accumulated from sea level down to total depth.", "The kick margin.", "The 6 MPa of overpressure divided by the column factor.", "The combined trend and exponent uncertainty, converted at the TD column factor."]'::jsonb, 2, '6000000 over 40207.265. The interpretation-laden part of the floor, where the error bars belong; the hydrostatic part is frame arithmetic.'),
  ('porepressure', 'advanced', 'final', null, 6, 'Where is the mud window WIDEST on capstone settings, and how wide?', '["At 2500 m, the ramp top: 750.2832396352455 kg/m3.", "At TD, where it reads 724.8190482612672 kg/m3.", "At 1000 m: 617.6616824116697 kg/m3.", "At 3000 m: 735.1476808049017 kg/m3."]'::jsonb, 0, 'The band grows to the onset and narrows below it: maximum room exactly where the trouble begins.'),
  ('porepressure', 'advanced', 'final', null, 7, 'In pressure units the window WIDENS below the onset while in mud units it narrows. Which reading answers the driller''s question?', '["The pressure-unit reading, because effective stress is the quantity that actually fractures rock at the wall.", "Both readings equally, since the two unit systems are algebraically interchangeable.", "Neither: only the operational interval matters.", "The mud-unit reading: mud is a density, so the well tightens gently below 2500 m."]'::jsonb, 3, 'Quoting the MPa trend to argue increasing comfort is a units error dressed as insight. The two pictures answer different questions.'),
  ('porepressure', 'advanced', 'final', null, 8, 'What sets the ceiling of the deep section once casing is set at 2500 m?', '["The fracture EMW at TD, 1903.92, since the deepest exposure controls the whole section''s design.", "The fracture EMW at the shoe, 1780.09: a rising ceiling binds at the top.", "The overburden EMW at the shoe.", "The leak-off value at the previous shoe."]'::jsonb, 1, 'The mud may not exceed the ceiling at ANY exposed depth; for a monotonic ceiling that is the shoe. This is also why leak-offs are taken there.'),
  ('porepressure', 'advanced', 'final', null, 9, 'Compute the operational window for the 2500 m shoe to TD.', '["1780.09 minus 1179.10: about 600.99 kg/m3.", "1903.92 minus 1179.10, the full 724.82 kg/m3 at TD.", "1780.09 minus 1029.81, the 750.28 kg/m3 window at the shoe depth itself.", "1830.77 minus 1179.10: 651.67 kg/m3."]'::jsonb, 0, 'Floor-at-bottom against ceiling-at-shoe. The 651.67 value is the answer for a 3000 m shoe; 750.28 is the TD-free window at the shoe depth itself.'),
  ('porepressure', 'advanced', 'final', null, 10, 'Which spending list belongs to the CEILING side of the window?', '["Kick margin and trip margin, carried above the floor while pipe is moving through the hole.", "Equivalent circulating density and surge allowance.", "Trend spread and exponent throw.", "Datum shift and column error, the two conversion traps of module one."]'::jsonb, 1, 'Dynamic effects raise the mud''s effective weight downhole, spending ceiling room. Kick and trip margins spend from the floor side; uncertainties are priced separately.'),
  ('porepressure', 'advanced', 'final', null, 11, 'What is the graded pore pressure at TD under n 1.2, and its overpressure?', '["47.408579625 MPa with the full 6 MPa of overpressure, unchanged by the calibration choice.", "43.901549937778526 MPa; 2.492970312778525 MPa over hydrostatic.", "41.408579625 MPa with zero overpressure, since low exponents silence the method.", "43.808579625 MPa; 2.4 MPa."]'::jsonb, 1, 'The low calibration reads the same four percent slowness at two fifths the volume. The 43.81 pair is the linearised shortcut, outside tolerance.'),
  ('porepressure', 'advanced', 'final', null, 12, 'What is the exponent''s throw on the TD mud floor, and on the window?', '["87.22 kg/m3 down on the floor, 58.15 up on the window.", "87.22 down on both.", "29.07 down, 87.22 up.", "3.51 down and 2.34 up, both stated in the megapascals the conversion started from."]'::jsonb, 0, 'The ceiling follows the floor by one third through the mixture, so the window moves by the remaining two thirds, with opposite sign.'),
  ('porepressure', 'advanced', 'final', null, 13, 'Under n 1.2 the detected onset moves to 2540 m. Why?', '["The rule''s threshold scales with the exponent, so the flag needs proportionally more overpressure.", "The ramp top moves under recalibration.", "The quieter anomaly needs two more samples to clear the fixed bar.", "The grid coarsens to 20 m."]'::jsonb, 2, '0.016 MPa at 2510 under the low calibration; the fixed rule fires where the scaled anomaly crosses it. The mechanism still starts at 2500 m.'),
  ('porepressure', 'advanced', 'final', null, 14, 'What does the window''s shape do under the n 1.2 calibration?', '["Narrows below the onset exactly as at n 3, from the same 750.28 maximum.", "Widens with depth below the onset: 750.28, 761.16, 782.97.", "Becomes exactly flat.", "Inverts outright, with the floor crossing above the ceiling at the deepest samples of the well."]'::jsonb, 1, 'The quiet floor no longer outruns the ceiling. Shape is calibration-conditional; re-read it after any refit, since it moves where sections pinch.'),
  ('porepressure', 'advanced', 'final', null, 15, 'When is the exponent argument an optimisation and when a feasibility question?', '["Optimisation when the throw fits inside the post-margin slack; feasibility when it does not.", "Always an optimisation on offshore wells, where windows are wide by the geometry of deep water.", "Feasibility whenever windows narrow with depth.", "Optimisation only if the trend is defended."]'::jsonb, 0, 'On this well 87 kg/m3 fits inside hundreds of slack. Squeeze the interval and the same 87 decides whether the section is drillable as designed.'),
  ('porepressure', 'advanced', 'final', null, 16, 'A wireline pressure point at 3800 m reads 42.0 MPa. The calibrations predicted 44.588 and 41.542. What is the professional response?', '["Adopt n 1.2 program-wide, since it is the preset whose curve passes nearest the measurement.", "Average the presets and carry 43.07.", "Fit n to the point, about 1.46, and rerun everything downstream.", "Hold the program unchanged until a second confirming point exists at a different depth."]'::jsonb, 2, 'Presets bracket, data interpolates. The fitted exponent, not the nearest label, carries the measurement''s information into the program.'),
  ('porepressure', 'advanced', 'final', null, 17, 'Which single statement about conservatism and the exponent is correct?', '["High n is conservative for every purpose.", "Low n is conservative for every purpose.", "Conservatism is directional per wall: high n for the floor, low for the ceiling; no single n serves both.", "Conservatism is a property of the stated tolerances rather than of the calibration that produced the curve."]'::jsonb, 2, 'n 1.2 authorises lighter mud, anti-conservative on the floor; its lower ceiling is the conservative reading for losses. Hence the two-floor band, not a chosen line.'),
  ('porepressure', 'advanced', 'final', null, 18, 'Compute the Bowers loading velocity at 5 MPa from its chain.', '["1949.944709834568 m/s, from psi 725.1886886510462 through the 0.75 power.", "1949.94 m/s, by taking 5 MPa directly to the 0.75 power in SI and skipping both unit crossings entirely.", "6397.46 m/s: the chain without the final conversion.", "2240.35 m/s: the chain at 10 MPa."]'::jsonb, 0, 'Two unit crossings, four operations. The tolerance is 0.5 m/s, cleared with fifteen digits to spare.'),
  ('porepressure', 'advanced', 'final', null, 19, 'What is the mudline velocity in SI, and what does it bound?', '["1500 m/s; the seawater velocity floor.", "1524 m/s exactly; the inversion''s hard domain edge.", "1030 m/s, the pore fluid''s acoustic velocity at reservoir conditions.", "1524 m/s, the deepest velocity this well''s sonic reaches at its total depth sample."]'::jsonb, 1, '5000 ft/s times 0.3048. A velocity at or below it claims zero grain load, and the honest output is an exception, not a pressure.'),
  ('porepressure', 'advanced', 'final', null, 20, 'Why does the inversion amplify velocity error?', '["The outer exponent 1/B is 4/3: where the forward curve is flat, the inverse is steep.", "The psi conversion multiplies any velocity error by the full 6894.757293168361 factor.", "The mudline subtraction doubles relative error.", "It does not: inversion is exact."]'::jsonb, 0, 'About 0.27 MPa per 10 m/s at the TD point. Sensitivity to signal and to error are the same number, as with Eaton''s exponent.'),
  ('porepressure', 'advanced', 'final', null, 21, 'What is the loading curve''s stress read of this well''s TD velocity, 3691.0906301457703 m/s?', '["43.714487325732826 MPa, the Eaton effective stress.", "29.240177382128643 MPa.", "43.752391704220855 MPa.", "50 MPa, the sigma_max."]'::jsonb, 2, 'The inversion of the golden loading curve. Eaton''s 43.714 is what the prognosis implies; the 0.038 MPa gap between them is the cross-check.'),
  ('porepressure', 'advanced', 'final', null, 22, 'Assemble the Bowers pore pressure at TD.', '["91.12306695073282 minus 43.752391704220855: 47.37067524651197 MPa.", "91.12306695073282 minus 43.714487325732826, which reproduces the Eaton value of 47.408579625 MPa.", "43.752391704220855 minus 41.408579625, the stress above hydrostatic at TD.", "47.408579625 minus 0.038: 47.37 MPa by definition."]'::jsonb, 0, 'Overburden minus the Bowers stress. Subtracting the EATON stress instead reproduces 47.408579625; restating the gap is not a derivation.'),
  ('porepressure', 'advanced', 'final', null, 23, 'The graded unloading inversion reads exactly 10 MPa from 3125.808993287662 m/s. What certifies, and what does not?', '["It certifies that sigma_max 50 MPa and U 3 are the correct history parameters for this well''s basin.", "It certifies your arithmetic: the fixture encoded the velocity AT 10 MPa.", "It certifies the rock is unloading.", "It certifies U is between 3 and 8."]'::jsonb, 1, 'Known answer, exact recovery, machinery certified, the Bowers version of the closed loop. The 10 is only as real as the 50 and the 3.'),
  ('porepressure', 'advanced', 'final', null, 24, 'With sigma_max 50 and the same velocity, what does U = 5 read instead of 10 MPa?', '["17.099759466766944 MPa.", "3.4199518933533817 MPa.", "15.625 MPa.", "29.240177382128643 MPa."]'::jsonb, 1, 'The inner ratio to the fifth power. U 2 gives 17.10; sigma_max 40 at U 3 gives 15.625; the loading-equivalent is 29.24. The parameter spread IS the lesson.'),
  ('porepressure', 'advanced', 'final', null, 25, 'What is the velocity-stress signature that separates undercompaction from unloading?', '["Undercompacted rock is slow and light; unloaded rock is slow but dense.", "Undercompacted rock is fast and dense; unloaded rock is fast and light.", "Both are slow and light; only mechanism arguments separate them.", "Undercompacted rock shows a velocity reversal; unloaded rock never does."]'::jsonb, 0, 'Unloading locked its compaction in and relaxed only elastically. The velocity reversal belongs to unloading, not undercompaction, so the claim pairing the reversal with undercompaction is doubly wrong.'),
  ('porepressure', 'advanced', 'final', null, 26, 'Why does the loading curve read 29.24 MPa from a velocity the unloading curve reads as 10?', '["A units mismatch between the two forms, since only the loading branch converts through the psi domain.", "Velocity records maximum stress; loading assumes the maximum is the present, unloading discounts it.", "The loading curve being miscalibrated at every stress above about 20 MPa.", "Rounding of PA_PER_PSI in the loading branch."]'::jsonb, 1, 'The ambiguity is a fact about rocks, not a defect: any honest method must surface it, and Bowers puts it on the label as two explicit curves.'),
  ('porepressure', 'advanced', 'final', null, 27, 'Reading an unloaded rock with the loading curve at the graded pair''s depth-equivalent would misstate pore pressure by how much, and in which direction?', '["19.24 MPa too high: the safe direction.", "0.038 MPa too low: negligible.", "19.24 MPa too low: the kick direction.", "2.9 MPa too low: one tolerance."]'::jsonb, 2, 'Effective stress high by 19.24 means pore pressure low by the same. The factor 2.9x is the stress ratio, not the pressure error.'),
  ('porepressure', 'advanced', 'final', null, 28, 'At what stress do the loading and unloading curves rejoin, and what anchors does that provide?', '["At sigma_max: loading anchors every unloading path''s start, so only U needs unloading data.", "At the mudline velocity of 1524 m/s, which both forms share as their zero-stress intercept by definition.", "At 10 MPa, the graded point.", "They never rejoin below infinite stress."]'::jsonb, 0, 'vUnloading(50 of 50) equals vLoading(50) exactly, 3919.263125861896 m/s. Shared parameters where sharing is physical: two extra numbers, not a second calibration.'),
  ('porepressure', 'advanced', 'final', null, 29, 'Feed the TD velocity to an unloading inversion with sigma_max 25 MPa. The output is 134 MPa. What is the diagnosis?', '["The engine''s cubing step overflowed and returned a value outside its representable range of stresses.", "The rock is deeper than the model allows.", "U must be raised until the output is physical.", "The loading-equivalent 43.75 exceeds the assumed maximum 25: inconsistent history, flagged by absurdity."]'::jsonb, 3, 'A rock cannot sit above the curve it departed from. Impossible outputs trace to impossible assumptions, which is the system working.'),
  ('porepressure', 'advanced', 'final', null, 30, 'On this well, which three unloading indicators are absent?', '["A candidate mechanism, a velocity reversal, and a sonic-density split.", "An encoded ramp, a detected onset, and a closed recovery loop over all samples.", "A shoe, a leak-off, and a kick.", "A trend, an exponent, and a threshold."]'::jsonb, 0, 'No uplift or late charge, transit time falls monotonically, and density continues its compaction rise to 2505.27 kg/m3 at TD. Hence the loading reading stands.'),
  ('porepressure', 'advanced', 'final', null, 31, 'The cross-check''s 0.038 MPa residual traces to what?', '["The 1.408 m/s loading-fit residual, through the 0.0269 MPa per m/s gain.", "Float32 storage of the goldens file, which truncates every velocity to about seven significant digits.", "The difference between n 3 and n 1.2.", "The 10 m sample grid."]'::jsonb, 0, 'An explained residual is what distinguishes a run cross-check from a lucky agreement. The product of the two named numbers is almost exactly 0.038.'),
  ('porepressure', 'advanced', 'final', null, 32, 'Why does the Eaton-Bowers gap grow to 1.509 MPa at 3000 m while being 0.038 at TD?', '["The encoded ramp steepens measurably at 3000 m, and the two methods respond to the steepening differently.", "A two-parameter law strays between its anchors: the drift is fit geometry, read before geology.", "Eaton is wrong mid-ramp.", "The overburden is uncertain mid-well."]'::jsonb, 1, 'Trust cross-checks most at calibration anchors. Mid-span disagreement means fit first, screening second, mechanism third.'),
  ('porepressure', 'advanced', 'final', null, 33, 'What can Eaton-Bowers agreement NOT defend against?', '["Trend bias in the Eaton branch.", "Exponent miscalibration.", "A biased sonic or overburden, which both methods consume identically.", "Implementation error in either engine, since the two codebases share no numerical routines at all."]'::jsonb, 2, 'Different mathematics, shared data. Truly independent checking needs different data: measured pressures, drilling response, resistivity.'),
  ('porepressure', 'advanced', 'final', null, 34, 'Which check catches a floor of 1208.58 kg/m3 at TD that sits comfortably inside the frame bracket?', '["The bracket check itself, since 1208.58 kg/m3 falls outside the frame''s envelope at total depth.", "The commutation check.", "The input-side column check: was the divisor g times 4100?", "The shape re-read, which would notice the floor moving between calibrations."]'::jsonb, 2, 'The missing-water value passes the generous bracket, which is why the column is checked at the input, never inferred from the output.'),
  ('porepressure', 'advanced', 'final', null, 35, 'A window quoted as 812.04 kg/m3 with walls 1091.88 and 1903.92 fails which reconciliation?', '["The K-algebra: that floor predicts a 782.97 window, exposing mixed calibrations.", "The datum check, since mixed datums are the only mechanism that can move a quoted width that far.", "The bracket check.", "The margins ledger."]'::jsonb, 0, 'Each wall is plausible; the pair is impossible. Widths and walls must reconcile through the algebra at one calibration.'),
  ('porepressure', 'advanced', 'final', null, 36, 'What belongs in the four-clause sentence for a key depth?', '["Value with provenance; cross-check with size; mechanism with evidence; units with datum.", "Depth, pressure, tolerance and signature, in the order the capstone submission form requests them.", "Floor, ceiling, window and margin, the four columns of the ledger.", "Trend, exponent, K, sigma_max."]'::jsonb, 0, 'Every clause auditable back to a lesson. The window trio is the plot''s content; the sentence is the report''s unit of account.'),
  ('porepressure', 'advanced', 'final', null, 37, 'What does the margins ledger for the deep section conclude on this well, with 50 floor-side and 100 ceiling-side?', '["The section is marginal: 10 kg/m3 of room.", "The section is marginal, with roughly 10 kg/m3 of usable room once every allowance is subtracted.", "1229.10 to 1680.09, about 451 kg/m3: any sensible mud fits easily.", "Margins cannot be assessed without leak-off data."]'::jsonb, 2, 'A benign well: the ledger''s value is the habit, and the honest note that this well must not calibrate your sense of danger.'),
  ('porepressure', 'advanced', 'final', null, 38, 'Why is carrying maximum overbalance, because the ceiling allows it, still bad practice?', '["It voids the leak-off test at the shoe by exceeding the pressure the test was interpreted at.", "The window is silent on sticking, hole cleaning and chemistry: necessary, never sufficient.", "It shifts the effective datum of every EMW quoted for the section.", "It reduces kick tolerance."]'::jsonb, 1, 'A mud can sit beautifully inside the pressure window and fail the well by other physics; high overbalance against permeable beds is the classic sticking recipe.'),
  ('porepressure', 'advanced', 'final', null, 39, 'Which capstone field would a 12.5 m/s sonic bias at TD endanger first?', '["The floor EMW, through the prognosis.", "The window, through the ceiling.", "The unloading stress field, whose graded input velocity would shift by the full bias.", "Nothing graded: the capstone fixes the Bowers inputs; on a real well it is about 0.34 MPa of pressure."]'::jsonb, 3, 'The capstone''s Bowers inputs are specified constants, so the bias hits nothing graded; the lesson is for the field, where 0.0269 MPa per m/s prices sonic quality.'),
  ('porepressure', 'advanced', 'final', null, 40, 'The six-line summary''s cross-check line reads: Bowers loading agrees to 0.038 MPa at TD; no unloading indicators; mechanism undercompaction. Which clause makes it auditable rather than assertive?', '["The 0.038, because a sized residual can be traced and challenged.", "The word loading, which commits the line to one of the two Bowers curves and can be checked against the screens.", "The word undercompaction, which names the mechanism the line commits to.", "The TD reference."]'::jsonb, 0, 'A sized, traceable residual invites audit; an unsized claim of agreement is decoration. The mechanism words stand on the three named screens.'),
  ('porepressure', 'advanced', 'final', null, 41, 'What is the deepest transferable habit this ladder installs?', '["Preferring transit time to velocity in every derivation, since the log itself is recorded in transit time.", "Setting thresholds at round numbers.", "Derived, defended, priced, and closed at whatever strength the data affords.", "Quoting sixteen digits wherever possible."]'::jsonb, 2, 'The machinery changes per course; the standard travels. Derived, defended, priced, closed is the whole doctrine in four words.'),
  ('porepressure', 'advanced', 'final', null, 42, 'Which statement correctly relates the three window routes at a single depth?', '["They agree only at total depth, where the capstone anchors them.", "Subtract-then-convert, convert-then-subtract and the K-algebra agree to floating point, because all quantities share one column.", "They differ by the kick margin, which only the operational route includes.", "They agree only if the exponent is an integer."]'::jsonb, 1, 'Division by a shared constant commutes with subtraction and preserves weighted averages. Three routes, one number, and any disagreement is a transcription hunt.');
