-- ============================================================================
-- DR8 ASSOCIATE DEEP SEED: Completion Design, beginner tier.
--
-- Six modules, 26 lessons, 132 questions (15 per module bank plus a 42
-- question final exam). The structure row is GENERATED from the tier's
-- manifest.json rather than hand typed, so the seeded structure and the
-- shipped lesson files cannot disagree.
--
-- What this tier owns: what a completion is made of, what an API 5CT drift is,
-- how a stack up is built and what it refuses, which equipment items are wide
-- and why, and the two volumes that come from the string alone. Fourteen
-- equipment types over 49 catalog rows, every one flagged approximate. The
-- published string is 13 components and 2606.25 m, of which four runs of plain
-- tubing carry almost all the length and nine pieces of equipment carry a
-- little over thirteen metres between them.
--
-- THE FINDING THE MODULE IS BUILT ON, AND IT IS ABOUT TWO NUMBERS. Every
-- component carries an outside diameter and an inside diameter, and the two
-- answer completely different questions: the outside decides what gets DOWN
-- and appears in no volume at all, the inside decides what gets THROUGH and
-- how much the component holds. The pair does not correlate. The safety valve
-- is the widest body above the packer at 5.75 in and its bore of 2.75 in is
-- NARROWER than the plain tubing at 2.992; the perforated joint is the
-- narrowest body in the kit at 3.5 in and its bore is the full tubing bore.
-- Almost every mistake in the subject is one of those two numbers being used
-- for the other one's question.
--
-- A SECOND FINDING, IN m02. The drift deduction is a lookup on the OUTSIDE
-- diameter and on nothing else, because the mandrel sizes are standardised by
-- pipe size and a physical mandrel knows neither weight nor grade. Every
-- 9-5/8 in row in the 28 row catalog gives up the same 5/32 in, so their
-- drifts differ ONLY because their nominal bores do, which is why a drift is
-- never quoted without the weight beside it. The four classes split the
-- catalog 3 / 9 / 10 / 6, and the two casing class boundaries at 8-5/8 and
-- 13-3/8 in are INCLUSIVE at the top: no row in any real catalog sits on
-- either of them, so a classification error there survives every test written
-- from the catalog and shows up the first time somebody runs a genuine
-- boundary size.
--
-- Every number in the lessons is derived by running the vendored
-- engines/drilling completionDesign module against completion_cases.json and
-- tubular_cases.json, and the teaching lab the panels and this course share is
-- pinned by completionLab.test.js across 42 cases. A numeric sweep over the
-- lessons resolved every literal carrying seven or more significant figures to
-- an engine-derived value; a tier-leakage sweep over the lessons and the banks
-- reports zero downward leaks and zero same-tier answer prints against all
-- eighteen graded fields.
--
-- Answer keys live only here and in academy_quiz_questions, which has no
-- client SELECT policy.
-- ============================================================================

insert into public.academy_course_structures
    (app_slug, tier, structure, content_version)
values ('completion', 'beginner', '{"modules":[{"key":"m01-what-a-completion-is","title":"What a Completion Is","lesson_keys":["l01-the-last-string-in-the-well","l02-what-the-components-do","l03-two-diameters-per-component","l04-what-this-engine-models"]},{"key":"m02-api-drift","title":"API Drift","lesson_keys":["l01-an-id-is-not-what-fits","l02-the-drift-mandrel","l03-three-deduction-classes","l04-the-class-boundary","l05-drift-is-a-guarantee"]},{"key":"m03-the-stack-up","title":"The Stack-Up","lesson_keys":["l01-a-tally-is-a-telescoping-sum","l02-top-down-from-the-hanger","l03-where-the-packer-lands","l04-what-the-tally-refuses","l05-reading-a-tally"]},{"key":"m04-the-equipment","title":"The Equipment","lesson_keys":["l01-what-each-piece-is-for","l02-the-body-od-is-the-coupling-od","l03-landing-nipples-and-seat-bores","l04-the-big-body-items","l05-the-catalog-says-approx"]},{"key":"m05-volumes-and-what-a-tally-hides","title":"Volumes, and What a Tally Hides","lesson_keys":["l01-capacity-and-displacement","l02-the-steel-between-them","l03-measured-depth-not-vertical","l04-what-a-tally-cannot-tell-you"]},{"key":"m06-the-associate-reading","title":"The Associate Reading","lesson_keys":["l01-the-story-so-far","l02-working-the-capstone","l03-onward"]}]}'::jsonb, 1)
on conflict (app_slug, tier) do update
  set structure = excluded.structure,
      content_version = excluded.content_version,
      active = true,
      updated_at = now();

delete from public.academy_quiz_questions
 where app_slug = 'completion' and tier = 'beginner';

insert into public.academy_quiz_questions
    (app_slug, tier, scope, module_key, ord, prompt, options, answer_index, explanation)
values
  ('completion', 'beginner', 'module', 'm01-what-a-completion-is', 1, 'What is a completion, in one sentence?', '["Any string of pipe run below the casing shoe.", "The string of tubing and equipment that stays in the well for its producing life.", "The final phase of well construction, covering everything done between the end of drilling and the handover of the well to production.", "The set of perforations and sand control hardware placed across the reservoir interval at the bottom of the hole."]'::jsonb, 1, 'Everything else that goes in the hole comes back out. The completion is what is there when the well is handed over.'),
  ('completion', 'beginner', 'module', 'm01-what-a-completion-is', 2, 'Which of these is NOT one of the four things a completion has to do?', '["Carry produced fluid to surface in a conduit of known size.", "Isolate the annulus above the reservoir so that pressure is contained by the tubing rather than by the casing.", "Allow tools to be run inside it later without having to dress the well over first.", "Support the weight of the casing strings above the reservoir."]'::jsonb, 3, 'The casing carries its own weight and is cemented. The completion hangs inside it and supports nothing.'),
  ('completion', 'beginner', 'module', 'm01-what-a-completion-is', 3, 'Why is completion design treated as a geometry problem before anything else?', '["Because a conduit, a seal, tool access and recovery are all questions about diameters and depths.", "Because reservoir inflow cannot be predicted reliably.", "Because geometric calculations are cheaper to run than the mechanical and thermal ones that follow them later.", "Because the equipment vendors publish dimensions but do not publish the ratings needed for any other calculation."]'::jsonb, 0, 'Read the four requirements again and each one reduces to a diameter against another diameter.'),
  ('completion', 'beginner', 'module', 'm01-what-a-completion-is', 4, 'Who decides the casing bores the completion has to work inside?', '["The completion engineer, at the same time as the tubing size.", "The reservoir engineer, based on the expected production rate and the tubing performance curve for the well.", "The casing design, made before the completion, on pressure and stability grounds.", "The drilling contractor, based on what bit sizes are available for the sections being drilled."]'::jsonb, 2, 'That inheritance is the tension in the subject. Every fit question is about somebody else''s earlier decision.'),
  ('completion', 'beginner', 'module', 'm01-what-a-completion-is', 5, 'How many equipment types does the catalog in this course carry?', '["Six, one for each module of the tier.", "Fourteen.", "Twenty eight, matching the number of casing and tubing rows in the tubular catalog used for the drift table.", "Forty nine, which is the number of catalog rows across all four tubing sizes."]'::jsonb, 1, 'Forty nine is the number of rows, because each type appears at several tubing sizes.'),
  ('completion', 'beginner', 'module', 'm01-what-a-completion-is', 6, 'What does a flow coupling do?', '["It puts a thick wall where turbulence downstream of a restriction would otherwise erode the pipe.", "It couples two tubing sizes together in a tapered string.", "It provides a machined internal profile that a lock mandrel can latch into, so a plug can be set at a known depth.", "It allows flow between the tubing and the annulus when shifted by a wireline tool run from surface."]'::jsonb, 0, 'It is sacrificial by design and it goes above and below anything that disturbs the flow.'),
  ('completion', 'beginner', 'module', 'm01-what-a-completion-is', 7, 'What is the operating principle of a surface controlled subsurface safety valve?', '["It closes when flow through it exceeds a set velocity.", "It is held closed by spring force and opened by the differential pressure that produced fluid develops across it.", "Hydraulic pressure from surface holds it open, so losing that pressure closes it.", "It is opened and closed by a wireline shifting tool run from surface whenever the well needs to be isolated."]'::jsonb, 2, 'Fail safe means the failure of the control system produces the safe state, which is shut.'),
  ('completion', 'beginner', 'module', 'm01-what-a-completion-is', 8, 'Why does a side pocket mandrel have its valve in a pocket beside the bore?', '["To reduce the pressure drop across the mandrel.", "Because the valve would otherwise obstruct the tubing bore completely and prevent any wireline access below it.", "To keep the gas injection point away from the produced fluid stream so the two do not mix inside the mandrel.", "So that the valve can be pulled and replaced without pulling the tubing string."]'::jsonb, 3, 'The offset pocket is why the mandrel is eccentric, which is what makes it one of the widest items in the kit.'),
  ('completion', 'beginner', 'module', 'm01-what-a-completion-is', 9, 'Two diameters are carried for every component. What does the outside diameter decide?', '["How much fluid the component holds inside it.", "Whether the component can be got down the hole past the casing above it.", "The pressure rating of the component, since a larger body carries more wall thickness at the same bore.", "The smallest tool that can be run through the finished string once the completion is in the hole."]'::jsonb, 1, 'It is the only thing the outside diameter is used for in this course, and it appears in no volume.'),
  ('completion', 'beginner', 'module', 'm01-what-a-completion-is', 10, 'The inside diameter answers two questions rather than one. Which two?', '["What can be got through the component afterwards, and how much fluid it holds.", "Its weight per unit length and its collapse rating.", "How far it can be run into the well, and how much clearance it has against the casing that surrounds it.", "Whether it can pass the casing above it, and how much annular volume it displaces on the way down."]'::jsonb, 0, 'One is a minimum over the string and one is a sum over it, and a component can dominate one and not the other.'),
  ('completion', 'beginner', 'module', 'm01-what-a-completion-is', 11, 'In the published string, which is true of the safety valve?', '["It is the narrowest body and has the widest bore.", "Its outside and inside diameters are both close to those of the plain tubing that runs above and below it.", "It is one of the widest bodies and its bore is narrower than the tubing above it.", "It is wide on the outside and its bore is the full tubing bore, because a valve of that size cannot restrict flow."]'::jsonb, 2, 'Two of the hardest things to run are also two of the hardest to get through, and the pair does not correlate.'),
  ('completion', 'beginner', 'module', 'm01-what-a-completion-is', 12, 'Which of these does the completion engine in this course compute?', '["A production rate from a reservoir inflow model.", "The axial force in the tubing string arising from thermal and pressure loads over the producing life of the well.", "The hook load required to push the completion to depth in a deviated hole with a stated friction factor.", "A through bore as a running minimum of the component inside diameters."]'::jsonb, 3, 'Inflow, tubing stress and running loads all belong to other courses, each with the inputs this one lacks.'),
  ('completion', 'beginner', 'module', 'm01-what-a-completion-is', 13, 'The engine refuses six kinds of input. Which of these is one of them?', '["A component that is wider than the casing above it.", "A component whose inside diameter is not smaller than its outside diameter.", "A packer set at a depth where the exposed casing bore changes from one string to another within a metre.", "A completion string whose total length exceeds the total depth of the well by any amount at all."]'::jsonb, 1, 'A component wider than the casing is a real design that fails, and it is computed and reported rather than refused.'),
  ('completion', 'beginner', 'module', 'm01-what-a-completion-is', 14, 'What does the engine do when the casing program does not cover an interval it is integrating?', '["It skips the interval and returns a warning naming the depths it could not cover.", "It refuses the whole calculation.", "It uses the bore of the nearest casing section above the gap, on the grounds that this is the best available estimate.", "It returns zero for that interval, which is conservative because it understates the volume rather than overstating it."]'::jsonb, 0, 'The number that comes back is real and incomplete, and the warning is the only thing that says so.'),
  ('completion', 'beginner', 'module', 'm01-what-a-completion-is', 15, 'Why is the scope of this engine drawn where it is?', '["Because the excluded calculations are too slow to run.", "Because the excluded items are covered by regulation rather than by engineering analysis in most jurisdictions.", "Because everything excluded would need an input the model does not carry.", "Because the vendors who supply the equipment will not release the data needed to compute anything beyond dimensions."]'::jsonb, 2, 'A tool that answered them from the inputs it has would be answering them by assumption.'),
  ('completion', 'beginner', 'module', 'm02-api-drift', 1, 'Why is the nominal bore of a joint of casing not the size of the largest thing that will pass?', '["Because the nominal bore is quoted in inches and tools are quoted in millimetres.", "Because the nominal bore is measured at the coupling, which is always wider than the pipe body it joins together.", "Because wall tolerance, ovality and straightness all make the effective bore smaller.", "Because casing is always run with a wall thickness greater than nominal, as a safety measure against internal corrosion."]'::jsonb, 2, 'None of the three can be measured on every joint, which is why a guaranteed number is quoted instead.'),
  ('completion', 'beginner', 'module', 'm02-api-drift', 2, 'What is a drift, physically?', '["The diameter of the largest standard mandrel that passed through the joint at the mill.", "The average inside diameter measured along the joint.", "The nominal inside diameter reduced by a fixed percentage that depends on the grade and the connection type.", "The smallest inside diameter found anywhere in the joint when it is calipered along its full length after manufacture."]'::jsonb, 0, 'There is no calculation in the definition. It is the result of a physical test on that particular joint.'),
  ('completion', 'beginner', 'module', 'm02-api-drift', 3, 'Why does the drift mandrel have a specified length as well as a diameter?', '["To make the mandrel heavy enough to fall under its own weight.", "So that the test says something about straightness and not only about bore.", "Because the specification has to define a volume for the mandrel so that its displacement can be accounted for in the mill records.", "Because a longer mandrel wears more slowly, which keeps the test consistent across the many thousands of joints a mill produces."]'::jsonb, 1, 'A short mandrel would pass through a bent joint that a long one would jam in.'),
  ('completion', 'beginner', 'module', 'm02-api-drift', 4, 'Why is the tubing drift mandrel longer than the casing one?', '["Because tubing has a thinner wall than casing does.", "Because tubing is normally run into deviated sections where the doglegs are more severe than in the cased sections above.", "Because tubing connections are upset, which makes the internal geometry vary more along the joint than a casing connection does.", "Because tubing is run in longer unsupported strings and the tools that go through it are longer."]'::jsonb, 3, 'Forty two inches for tubing against twelve for most casing sizes.'),
  ('completion', 'beginner', 'module', 'm02-api-drift', 5, 'Why does the drift deduction depend on the outside diameter alone?', '["Because the mandrel sizes are standardised by pipe size, and the mandrel knows nothing else.", "Because the outside diameter is the only dimension that is measured.", "Because the deduction is derived from the wall thickness, which is itself a function of the outside diameter and nothing more.", "Because heavier pipe drifts the same as lighter pipe of the same size, so the deduction has to be independent of both."]'::jsonb, 0, 'It does not depend on weight or grade, because neither of those is visible to a physical mandrel test.'),
  ('completion', 'beginner', 'module', 'm02-api-drift', 6, 'Two nine and five eighths inch casing rows of different weight are compared. What differs between their drifts?', '["Both the nominal bore and the deduction differ.", "Neither differs, because the drift of a size is a single published value that applies to every weight in that size.", "Only the nominal bore, because both rows give up the same deduction.", "Only the deduction differs, because the heavier row has more wall and therefore takes a larger deduction than the lighter one."]'::jsonb, 2, 'That is why a drift is never quoted without the weight beside it.'),
  ('completion', 'beginner', 'module', 'm02-api-drift', 7, 'What deduction does tubing take?', '["One eighth of an inch, the same as small casing.", "Three thirty seconds of an inch.", "Five thirty seconds of an inch, which is the value that applies to casing in the middle of the size range.", "Three sixteenths of an inch, which is the largest of the four deduction values in the specification."]'::jsonb, 1, 'It is the smallest of the four, even though tubing is the smallest pipe, because the mandrel programme is separate.'),
  ('completion', 'beginner', 'module', 'm02-api-drift', 8, 'Casing at exactly eight and five eighths inches outside diameter takes which deduction?', '["Three thirty seconds of an inch.", "Five thirty seconds of an inch, because eight and five eighths is the point at which the larger deduction begins to apply.", "It depends on the weight, because the class boundary is defined on the nominal bore rather than the outside diameter.", "One eighth of an inch."]'::jsonb, 3, 'The ranges are inclusive at the top, so the size named at the boundary stays in the lower class.'),
  ('completion', 'beginner', 'module', 'm02-api-drift', 9, 'How do the twenty eight tubulars in this course divide between the four deduction values?', '["Three in the largest class, nine in the next, ten in the smallest casing class and six tubing rows.", "Seven in each of the four classes.", "Ten in the largest class, nine in the next, three in the smallest casing class and six tubing rows.", "Six in the largest class, ten in the next, nine in the smallest casing class and three tubing rows."]'::jsonb, 0, 'Most of a casing catalog sits in the two middle classes, which is where the common strings are.'),
  ('completion', 'beginner', 'module', 'm02-api-drift', 10, 'Why is a class boundary test worth writing when no real catalog row sits on a boundary?', '["Because the specification requires a test at each boundary.", "Because catalog rows change over time and a size that is not on a boundary today may be added at one in a future revision.", "Because a classification error at the boundary would survive every test written from the catalog.", "Because the boundary values are the ones most often quoted in field conversations, so they need to be right for that reason."]'::jsonb, 2, 'It would then show up the first time somebody put a genuine boundary size in a well.'),
  ('completion', 'beginner', 'module', 'm02-api-drift', 11, 'A joint has been drifted at the mill. What may you rely on as a result?', '["That the joint has no internal defects of any kind.", "That a rigid cylinder of that diameter and the mandrel length will pass that joint.", "That any tool of that diameter can be run to the bottom of the string in which the joint is installed at any time.", "That the inside diameter of the joint is at least the drift diameter everywhere along its length, including in the coupling."]'::jsonb, 1, 'It is a statement about new pipe in the rack and about a mandrel of a particular length.'),
  ('completion', 'beginner', 'module', 'm02-api-drift', 12, 'Which of these does the drift guarantee NOT cover?', '["The bore of the same casing three years later, after scale and corrosion.", "A twelve inch mandrel passing through a new joint.", "The dimensional acceptability of the joint against the manufacturing tolerance stated in the specification for that size.", "A rigid cylinder of the drift diameter and the mandrel length passing through the joint at the mill on the day it was tested."]'::jsonb, 0, 'The catalog value says what to expect and a drift run says what is actually there.'),
  ('completion', 'beginner', 'module', 'm02-api-drift', 13, 'How much smaller is the drift than the nominal bore for nine and five eighths inch casing?', '["About an inch and a half.", "About a hundredth of an inch, which is within the measurement uncertainty of a caliper run in most field conditions.", "It varies with the weight, and can be anything between a tenth of an inch and half an inch depending on the row chosen.", "About a fifth of an inch, or a few millimetres."]'::jsonb, 3, 'A few millimetres is the whole margin on the tightest row in the published completion.'),
  ('completion', 'beginner', 'module', 'm02-api-drift', 14, 'Why is a drift run performed before a workover?', '["Because the specification requires it before any intervention.", "Because the drift of a string changes with the pressure and temperature it has been exposed to during its producing life.", "Because the catalog value describes new pipe and the well is not new pipe.", "Because the original mill drift records are rarely available once a well has been handed over from construction to production."]'::jsonb, 2, 'A physical mandrel or gauge ring through the actual well is the only way to know what is there.'),
  ('completion', 'beginner', 'module', 'm02-api-drift', 15, 'How should a clearance computed against a catalog drift be read?', '["As the exact gap the component will see when it is run.", "As a clearance against the best case, with less than that available in a used well.", "As a conservative lower bound, because the drift is smaller than the bore that the component will actually encounter.", "As a nominal figure with no physical meaning, since the real bore is unknown until a drift run has been performed."]'::jsonb, 1, 'Zero clearance against a guarantee is not zero clearance in a well, which is the argument for a warn margin.'),
  ('completion', 'beginner', 'module', 'm03-the-stack-up', 1, 'State the whole rule that builds a completion tally.', '["Each component is placed at its own design depth independently.", "Each component starts at the depth where the one above it stopped.", "Components are placed from the bottom of the well upward, so that the packer and the perforations land where the design wants them.", "Each component is placed at the depth given in the equipment schedule, and the lengths are then adjusted to make the sum come out right."]'::jsonb, 1, 'Top of the first is the hanger, bottom is top plus length, and the next top is that bottom.'),
  ('completion', 'beginner', 'module', 'm03-the-stack-up', 2, 'Why is the sum called telescoping?', '["Because every intermediate depth appears once as a bottom and once as a top and cancels.", "Because the string can be shortened by removing joints.", "Because the components are nested inside one another in the same way that the sections of a telescope are nested together.", "Because the calculation is performed at several scales at once, from the whole string down to the individual component."]'::jsonb, 0, 'What survives is the hanger depth plus the sum of the lengths, which is the bottom depth.'),
  ('completion', 'beginner', 'module', 'm03-the-stack-up', 3, 'What check does the telescoping identity give you for free?', '["The number of components must be odd.", "The sum of the component outside diameters must be less than the inside diameter of the casing they are run inside.", "The last bottom depth must equal the hanger depth plus the sum of the lengths.", "The average component length must lie between the shortest and the longest component in the string, which it always does."]'::jsonb, 2, 'If it does not close, the tally has been built wrong and the depths below the error are all wrong.'),
  ('completion', 'beginner', 'module', 'm03-the-stack-up', 4, 'How many components does the published string carry, and how long is it?', '["Fourteen components and about two thousand nine hundred metres.", "Thirteen components and about three thousand metres, which is the total depth of the well the string is run into.", "Nine components and about two thousand four hundred metres, which is the depth at which the liner top is set in that well.", "Thirteen components and a little over two thousand six hundred metres."]'::jsonb, 3, 'Four of the thirteen are plain tubing and account for almost all of the length.'),
  ('completion', 'beginner', 'module', 'm03-the-stack-up', 5, 'What is the hanger depth in the published string, and what does that mean?', '["Two thousand four hundred metres, at the liner top.", "Zero, so the string is hung at surface and depths share the casing datum.", "It is not specified, because a completion run from surface does not need a hanger depth in order for the tally to be built.", "It is set equal to the packer depth, because the packer is what actually supports the weight of the string once it is set."]'::jsonb, 1, 'A hanger above zero happens on a string run on a work string or hung off a liner top.'),
  ('completion', 'beginner', 'module', 'm03-the-stack-up', 6, 'Why does the engine refuse a negative hanger depth?', '["Because a hanger above the datum is not a configuration, it is a sign error.", "Because negative numbers cannot be stored in the depth field.", "Because a hanger above the datum would put the top of the string above the rotary table, which no rig can physically accommodate.", "Because the depths of everything below would then be negative too, and the volume integrals would come out with the wrong sign."]'::jsonb, 0, 'It is the same kind of refusal as a component with no length: an input that describes nothing.'),
  ('completion', 'beginner', 'module', 'm03-the-stack-up', 7, 'Why is the tally built downward from the hanger rather than upward from total depth?', '["Because measured depth increases downward by convention.", "Because the packer depth is the only depth in the well that is known accurately enough to build a tally from.", "Because the length of the string is known before it goes in and the bottom depth is not.", "Because building upward would require the total depth to be measured after the completion is landed, which is not possible."]'::jsonb, 2, 'Building upward would assume the answer and back calculate the tally from it.'),
  ('completion', 'beginner', 'module', 'm03-the-stack-up', 8, 'Four calculations read the packer depth. Which of these is NOT one of them?', '["The clearance check, which needs to know which bore the packer passes.", "The annulus volume above the packer, which is integrated from the hanger down to the packer depth and no further.", "The through bore at the packer, which is what a tool has to pass in order to reach anything below the packer at all.", "The drift of the liner the packer has to pass through."]'::jsonb, 3, 'The liner drift is a property of the liner and does not change with where the packer is set.'),
  ('completion', 'beginner', 'module', 'm03-the-stack-up', 9, 'In the published string, how many components sit below the packer?', '["None, because the packer is the last component.", "Four, in a little under six metres.", "Nine, which is the number of pieces of equipment in the string as distinct from the four runs of plain tubing.", "Two, a perforated joint and a wireline entry guide, with nothing between them and nothing below the guide."]'::jsonb, 1, 'Two metres of tubing, a no go nipple, a perforated joint and an entry guide.'),
  ('completion', 'beginner', 'module', 'm03-the-stack-up', 10, 'If the packer in the published well were moved two hundred metres shallower, what would happen to its clearance?', '["It would rise by more than an order of magnitude, because it would no longer pass the liner.", "It would be unchanged, because the packer body is unchanged.", "It would fall, because the casing bore is smaller higher in the well than it is at the liner top and below it.", "It would rise by a few percent, reflecting the small difference between the two casing weights in the production string."]'::jsonb, 0, 'Nothing about the packer changed. The geometry above it changed, and the constraint follows the geometry.'),
  ('completion', 'beginner', 'module', 'm03-the-stack-up', 11, 'Why can the packer in the published well not simply be moved above the liner top?', '["Because the liner top is above the total depth of the well.", "Because a packer set in casing rather than in a liner requires a completely different setting mechanism and sealing element.", "Because it has to sit above the perforations and below the liner top, which puts it inside the liner.", "Because moving it would change the volume above the packer, and the packer fluid has already been ordered against that volume."]'::jsonb, 2, 'The tight clearance follows from a reservoir depth and a casing program that were both fixed first.'),
  ('completion', 'beginner', 'module', 'm03-the-stack-up', 12, 'Why is a zero length component particularly dangerous if it is not refused?', '["Because it would divide by zero in the volume calculation.", "Because it contributes nothing and the sum still comes out consistent for everything else.", "Because a component with no length cannot be assigned an outside diameter, so the clearance check would have nothing to compare.", "Because it would appear at the top of the string, where the tally is normally checked most carefully by the crew making it up."]'::jsonb, 1, 'It is usually a row that was added to the tally and never filled in, and it is invisible in the arithmetic.'),
  ('completion', 'beginner', 'module', 'm03-the-stack-up', 13, 'A component row has its two diameters swapped. Why does that matter so much?', '["Because both consequences point the same way and make the string look more runnable than it is.", "Because the volume would come out negative and stop the run.", "Because the two numbers are in different units, so the error changes the magnitude of the result by a factor of about forty.", "Because the swapped row would be placed at the wrong depth in the tally, which shifts everything below it by its own length."]'::jsonb, 0, 'A smaller body clears easily and a larger bore improves the through bore. Both errors flatter the design.'),
  ('completion', 'beginner', 'module', 'm03-the-stack-up', 14, 'What is the difference between an input the engine refuses and a design it reports as failing?', '["A refusal stops the program and a failure does not.", "A refusal is issued for anything outside the catalog, and a failure is issued for anything inside it that does not fit.", "A refusal comes from the stack up and a failure comes from the clearance check, so the two never arise in the same calculation.", "A refused input describes no physical object; a failing design describes one that will not work."]'::jsonb, 3, 'A component wider than the casing is a legitimate input with a legitimate answer, and the answer is a failure.'),
  ('completion', 'beginner', 'module', 'm03-the-stack-up', 15, 'What three scans should you run over a tally before running any check?', '["The weights, the grades and the connection types.", "The component names, the vendor part numbers and the setting depths, so that the tally can be checked against the purchase order.", "The length distribution, the extreme diameters in both columns, and the order.", "The total length, the total capacity and the total displacement, since between them those three summarise the whole string."]'::jsonb, 2, 'Three predictions from three scans take a minute and tell you when a check says something surprising.'),
  ('completion', 'beginner', 'module', 'm04-the-equipment', 1, 'What is a blast joint for?', '["It puts a sacrificial thick wall opposite perforations where produced fluid jets sideways.", "It absorbs the length change of the string.", "It provides a place for a wireline tool to be parked while other operations are carried out inside the tubing above it.", "It breaks up slugs of liquid in a gas well so that the flow arriving at surface is steadier than it would otherwise be."]'::jsonb, 0, 'Same principle as a flow coupling against a different attack.'),
  ('completion', 'beginner', 'module', 'm04-the-equipment', 2, 'What distinguishes an X profile from an XN profile?', '["The X is run in tubing and the XN in casing.", "The X profile seals against pressure from above only, and the XN profile seals against pressure arriving from either direction.", "The XN has a no go shoulder below its seat, so a tool of the wrong size stops there.", "The X is machined into the tubing wall directly and the XN is a separate component made up into the string as its own joint."]'::jsonb, 2, 'Selective means tools can pass a shallower one to reach a deeper one of the same size.'),
  ('completion', 'beginner', 'module', 'm04-the-equipment', 3, 'Why is the no go nipple normally the deepest nipple in a string?', '["Because it is the heaviest component in the string.", "Because it stops tools, and placing it higher would deny access to everything below it.", "Because the pressure differential across a plug is greatest at the bottom of the well, where the no go is best able to carry it.", "Because it has to sit below the packer in order to isolate the reservoir when a plug is set in it during a workover."]'::jsonb, 1, 'The trade is access gained at a depth against access lost below it, in its strongest form.'),
  ('completion', 'beginner', 'module', 'm04-the-equipment', 4, 'What is a wireline entry guide?', '["A surface device that guides wireline into the wellhead.", "A machined internal profile at the top of the string that centralises a tool string as it is run in from surface.", "A short length of enlarged bore below the packer that gives a tool room to turn around before being pulled back up.", "A bell mouth at the bottom that guides a tool coming up from below back into the bore."]'::jsonb, 3, 'It is at the very bottom of the published string, below the perforated joint.'),
  ('completion', 'beginner', 'module', 'm04-the-equipment', 5, 'Why is a perforated joint run below a packer?', '["Because the bottom of the string is plugged and fluid has to enter somewhere.", "Because it centralises the tail of the completion.", "Because it provides the pressure drop needed to keep the flow from the reservoir stable across the producing interval.", "Because it allows the annulus below the packer to be circulated out before the packer is set and the well is put on production."]'::jsonb, 0, 'It is a plain pipe body with holes in it and no upset, which makes it the narrowest body in the kit.'),
  ('completion', 'beginner', 'module', 'm04-the-equipment', 6, 'What is the default rule about the outside diameter of completion equipment?', '["Most items are the same outside diameter as the tubing body.", "Most items are sized to the casing they will be run into rather than to the tubing they are made up into, as a packer is.", "Most items are machined to the same outside diameter as the tubing coupling.", "Most items are sized so that the annular area around them is equal to the flow area inside the tubing above and below."]'::jsonb, 2, 'The coupling has to go down anyway, so matching it costs nothing in runability and buys wall thickness.'),
  ('completion', 'beginner', 'module', 'm04-the-equipment', 7, 'For three and a half inch external upset tubing, what is the coupling outside diameter?', '["Three and a half inches, the same as the pipe body.", "Four and a half inches.", "Five and three quarter inches, which is also the outside diameter of the safety valve and the side pocket mandrel.", "Five and seven eighths inches, which is the outside diameter of the production packer used in the published string."]'::jsonb, 1, 'So a nipple at the coupling diameter is a full inch wider than the pipe it is made up into.'),
  ('completion', 'beginner', 'module', 'm04-the-equipment', 8, 'Which four items in the three and a half inch kit are wider than the coupling?', '["The two flow couplings, the blast joint and the entry guide.", "The two landing nipples, the perforated joint and the wireline entry guide, all of which carry machined internal profiles.", "The tubing, the flow coupling and the blast joint, which are the three items that carry the heaviest wall in the whole kit.", "The safety valve, the side pocket mandrel, the sliding sleeve and the expansion joint."]'::jsonb, 3, 'Each has a physical reason: a flapper and piston, an offset pocket, an outer sleeve, and one tube inside another.'),
  ('completion', 'beginner', 'module', 'm04-the-equipment', 9, 'One type in the kit sits below the coupling diameter. Name it and say why.', '["The perforated joint, which is a plain pipe body with holes in it.", "The safety valve, which is machined down to save weight.", "The wireline entry guide, whose bell mouth is machined from the inside so that the outside stays at the pipe body diameter.", "The XN no go nipple, because its bore is the smallest in the string and the wall is thinned to compensate for that."]'::jsonb, 0, 'No upset at all, which makes it the easiest thing in the string to run.'),
  ('completion', 'beginner', 'module', 'm04-the-equipment', 10, 'The three and a half inch kit is put into five and a half inch casing at twenty pounds per foot. What happens?', '["Everything fails, because the tubing itself will not go.", "Nothing fails, because five and a half inch casing at that weight has a drift larger than the widest item in the kit.", "Three items fail: the side pocket mandrel, the safety valve and the expansion joint.", "Only the packer fails, because it is sized to seven inch casing and cannot be run into anything smaller than that."]'::jsonb, 2, 'The pipe fits comfortably, which is exactly the trap.'),
  ('completion', 'beginner', 'module', 'm04-the-equipment', 11, 'Why does a size discussion that starts from the tubing get the wrong answer?', '["Because tubing sizes are quoted as nominal rather than actual.", "Because the widest item in a completion is never the pipe, and the pipe fits when the kit does not.", "Because the tubing is the only item whose outside diameter is not published by the vendor in a form that can be compared.", "Because the tubing is run first and the equipment is made up afterwards, so the two are never checked against the same bore."]'::jsonb, 1, 'Three and a half inch tubing has a coupling of four and a half, and the widest item is nearly two inches larger than the body.'),
  ('completion', 'beginner', 'module', 'm04-the-equipment', 12, 'Which of these is a real remedy when a big body item will not fit the casing?', '["Use a slimline version, usually at the cost of a reduced rating or a higher price.", "Run the item at a shallower depth in the same string.", "Ream the casing at the depths where the item will sit, so that the local bore is enlarged enough to accept it as designed.", "Accept the negative clearance, since the drift is a conservative figure and the actual bore is normally larger than it."]'::jsonb, 0, 'The three remedies are a smaller tubing size, a slimline component, or leaving the component out.'),
  ('completion', 'beginner', 'module', 'm04-the-equipment', 13, 'Every equipment row in the catalog carries an approximate flag. What is it for?', '["It marks the rows whose dimensions have not yet been verified.", "It indicates that the dimensions were converted from imperial units and therefore carry a rounding error in the last digit.", "It shows that the row is an average across several vendors, so the true value for any one vendor is within a few percent.", "It is an instruction that the numbers are representative and must not be used to order equipment."]'::jsonb, 3, 'The flag separates the part that transfers, which is the structure, from the part that does not, which is the digits.'),
  ('completion', 'beginner', 'module', 'm04-the-equipment', 14, 'If every catalog row were replaced with real vendor data, what would change?', '["Nothing at all, because the rows are already accurate.", "Every conclusion in the course would need to be rechecked, because the results depend on the specific numbers used.", "The magnitudes would move and the ordering would not.", "Only the through bore results would change, because those depend on internal dimensions that vary most between vendors."]'::jsonb, 2, 'Big bodies stay bigger than pipe and nipple bores stay smaller than tubing bores, whoever makes them.'),
  ('completion', 'beginner', 'module', 'm04-the-equipment', 15, 'Which of these would be a misuse of this course''s equipment catalog?', '["Using it to learn which item types are widest.", "Quoting one of its outside diameters in a design document.", "Working through the size matrix to see which family of components decides the tubing size that a well can carry.", "Substituting a vendor''s real dimensions into the same calculations and comparing the answers against the ones taught here."]'::jsonb, 1, 'The flag is on every row precisely so that this cannot happen by accident.'),
  ('completion', 'beginner', 'module', 'm05-volumes-and-what-a-tally-hides', 1, 'Define the capacity of a completion string.', '["The volume of steel the string contains.", "The volume of the annulus between the string and the casing, integrated from the hanger down to the packer depth.", "The sum over components of the inside area times the length.", "The volume the string would hold if every component had the bore of the plain tubing that makes up most of its length."]'::jsonb, 2, 'It is what you pump to fill the tubing from empty, and what has to come out when it is displaced.'),
  ('completion', 'beginner', 'module', 'm05-volumes-and-what-a-tally-hides', 2, 'Which sum gives the volume the running string pushes out of the well?', '["The sum over components of the outside area times the length.", "The volume of fluid the string holds inside it.", "The difference between the volume of the casing bore and the volume the string occupies, taken over the length of the string.", "The volume of fluid that has to be pumped to displace the tubing contents to the packer once the string is landed and set."]'::jsonb, 0, 'It is the volume of the outside envelope of the string.'),
  ('completion', 'beginner', 'module', 'm05-volumes-and-what-a-tally-hides', 3, 'Why is the displacement of a string always larger than its capacity?', '["Because the displacement includes the couplings and the capacity does not.", "Because the outside diameter exceeds the inside diameter for every component.", "Because the displacement is measured with the string full of fluid and the capacity is measured with the string empty of it.", "Because the displacement is integrated over the whole well and the capacity only over the part of the string above the packer."]'::jsonb, 1, 'The difference between them is the volume of steel in the string.'),
  ('completion', 'beginner', 'module', 'm05-volumes-and-what-a-tally-hides', 4, 'For the published string, roughly what is the ratio of displacement to capacity?', '["About one point one.", "About five, which is also the ratio between the annulus volume above the packer and the capacity of the string itself.", "It cannot be stated as a single number, because the ratio varies from component to component along the string.", "A little over two."]'::jsonb, 3, 'Capacity is about eleven point eight cubic metres and displacement about twenty six point eight.'),
  ('completion', 'beginner', 'module', 'm05-volumes-and-what-a-tally-hides', 5, 'Which of these do the capacity and displacement calculations NOT read?', '["The casing program.", "The inside diameter of each component.", "The length of each component, which is the same length the stack up uses to place it at its depth in the well.", "The outside diameter of each component, which is also what the run in clearance check compares against the casing."]'::jsonb, 0, 'Both are properties of the string alone and neither would change in a different well.'),
  ('completion', 'beginner', 'module', 'm05-volumes-and-what-a-tally-hides', 6, 'What physical object is the difference between the two string volumes?', '["The annular space around the string.", "The fluid displaced from the well while the string is being run in with the bottom of it open to the wellbore.", "The steel in the string, which can be weighed once a density is applied.", "The volume of the couplings, which is the part of the string that neither the bore nor the pipe body accounts for."]'::jsonb, 2, 'Multiply it by the density of steel and you have the weight of the string in air.'),
  ('completion', 'beginner', 'module', 'm05-volumes-and-what-a-tally-hides', 7, 'Why is the steel volume a useful check on a tally?', '["Because it must equal the capacity for a correctly built string.", "Because it must be positive for every component, so a swapped diameter pair shows up immediately.", "Because it is the only one of the three volumes that can be measured directly on the rig before the string goes in the hole.", "Because it does not depend on the component lengths, so an error in a length cannot affect it and the check is independent."]'::jsonb, 1, 'It is a second line of defence behind the input refusal, and it confirms the refusal did its job.'),
  ('completion', 'beginner', 'module', 'm05-volumes-and-what-a-tally-hides', 8, 'Which of these does the steel volume NOT tell you?', '["The weight of the string in air, once a density is applied.", "Whether any component in the tally has had its inside and outside diameters entered the wrong way round.", "How much of the string cross section is metal rather than fluid, expressed per metre of string if you divide by the length.", "The weight of the string in the well."]'::jsonb, 3, 'Weight in the well is weight in air less buoyancy, and buoyancy depends on the fluid the string is run in.'),
  ('completion', 'beginner', 'module', 'm05-volumes-and-what-a-tally-hides', 9, 'Every depth in this course is which kind of depth?', '["Measured depth, along the hole from the datum.", "True vertical depth below the datum.", "Measured depth for the string and true vertical depth for the casing program, since the two are recorded differently.", "Subsea depth, referenced to mean sea level rather than to the rotary table or any other rig floor elevation."]'::jsonb, 0, 'Every quantity in this course is a length along the hole or an area across it.'),
  ('completion', 'beginner', 'module', 'm05-volumes-and-what-a-tally-hides', 10, 'Why does a volume calculation correctly use measured depth?', '["Because measured depth is always the larger of the two.", "Because the casing program is recorded in measured depth, and converting it would require a survey the model does not carry.", "Because the fluid fills the annulus along its path and not along a vertical line.", "Because the difference between the two depths is negligible in the cased section, where every volume in this course is computed."]'::jsonb, 2, 'A volume is an area times a length along the hole, which is exactly what the integration does.'),
  ('completion', 'beginner', 'module', 'm05-volumes-and-what-a-tally-hides', 11, 'Which quantity would require true vertical depth rather than measured depth?', '["The capacity of the string.", "A hydrostatic pressure at the packer.", "The clearance of a component against the casing bore that sits above it at the depth where the component lands.", "The through bore of the string, which is a running minimum of the component inside diameters taken from the top down."]'::jsonb, 1, 'Pressure accumulates with height, and so does temperature, and neither accumulates with distance travelled.'),
  ('completion', 'beginner', 'module', 'm05-volumes-and-what-a-tally-hides', 12, 'What error would substituting vertical depths into a volume calculation produce in a deviated well?', '["It would understate the volume, by the ratio between the two depths.", "It would overstate the volume by the same ratio.", "It would leave the volume unchanged, because the areas are unaffected by the inclination of the hole at any depth.", "It would change the volume only in the sections where the inclination exceeds about thirty degrees from the vertical."]'::jsonb, 0, 'The error would still look plausible, which is what makes it dangerous.'),
  ('completion', 'beginner', 'module', 'm05-volumes-and-what-a-tally-hides', 13, 'What can the beginner tier NOT yet tell you about a completion?', '["How long the string is.", "How much fluid the string holds inside it, and how much it displaces when it is run into the well with the bottom open.", "What the drift of every casing and tubing size in the catalog is, including the sizes that sit on a class boundary.", "Whether the string will go in the hole."]'::jsonb, 3, 'That needs the clearance check, which compares each component against the casing above it.'),
  ('completion', 'beginner', 'module', 'm05-volumes-and-what-a-tally-hides', 14, 'What can a tally never tell you, at any tier?', '["The bottom depth of the string.", "The bore of the smallest component in the string, which is what sets the through bore once the string is in the hole.", "Whether the string can actually be run in a deviated well.", "How much annular volume there is above the packer, given a casing program to integrate the string against."]'::jsonb, 2, 'Geometry says it fits; mechanics says whether it goes, and there is no survey and no friction model here.'),
  ('completion', 'beginner', 'module', 'm05-volumes-and-what-a-tally-hides', 15, 'What claim does a completed tally support?', '["That the completion will produce at the design rate.", "That the completion is geometrically possible, and nothing about whether it is a good one.", "That the equipment in the string is correctly rated for the pressure, temperature and fluid composition of the well.", "That the string can be run to depth in the well it was designed for, given the trajectory that well was drilled on."]'::jsonb, 1, 'Geometric possibility is a hard constraint that binds before anything else, and it is often found late.'),
  ('completion', 'beginner', 'module', 'm06-the-associate-reading', 1, 'A colleague asks what the Associate tier of this course qualifies you to do. What is the honest answer?', '["Design a completion for any well from first principles.", "Read a tally, compute a drift correctly, build and check a stack up, and find the two string volumes.", "Decide whether a proposed completion will go into a given casing program, and what tools will pass through it afterwards.", "Select the tubing size for a well, given the casing program and a production forecast for the reservoir it will produce from."]'::jsonb, 1, 'Not yet whether the string goes in the hole. That is the next tier.'),
  ('completion', 'beginner', 'module', 'm06-the-associate-reading', 2, 'One observation ties the whole tier together. Which is it?', '["Each component carries two diameters and the two answer different questions.", "A completion is the last string in the well.", "The drift deduction depends on the outside diameter of the pipe and never on its weight, its grade or its connection.", "Every depth in this course is a measured depth, so no calculation in it needs a survey or a true vertical depth conversion."]'::jsonb, 0, 'Almost every mistake in the subject is one of those two numbers being used for the other one''s question.'),
  ('completion', 'beginner', 'module', 'm06-the-associate-reading', 3, 'A tally arrives with fifteen rows. Which three scans do you run before touching a calculator?', '["The weights, the grades and the connection types.", "The total length, the sum of the outside diameters and the sum of the inside diameters, compared against the casing bore.", "The length distribution, the extremes in each diameter column, and the order of the rows.", "The vendor part numbers, the setting depths and the purchase order, so that the tally can be reconciled with what was ordered."]'::jsonb, 2, 'Three predictions in a minute, so that you know when a check says something surprising.'),
  ('completion', 'beginner', 'module', 'm06-the-associate-reading', 4, 'A tally lists a component with a length of zero. What should happen and why?', '["It should be ignored, since it adds no length.", "It should be accepted and flagged, because a zero length component may legitimately represent a profile machined into a joint.", "It should be replaced with the catalog length for that component type, which is the value the tally was intended to carry.", "It should be refused, because it contributes nothing and disappears into a consistent looking sum."]'::jsonb, 3, 'A row added and never filled in is invisible in the arithmetic, which is why the input has to catch it.'),
  ('completion', 'beginner', 'module', 'm06-the-associate-reading', 5, 'You are handed a drift of eight point three eight inches with no other information. What is missing?', '["The weight, because the deduction came off a nominal bore that the weight fixed.", "The grade of the pipe.", "The connection type, since an upset connection has a different internal geometry from a plain end one at the same weight.", "The mandrel length used for the test, without which the guarantee cannot be interpreted for a tool of any particular length."]'::jsonb, 0, 'Every row at a size gives up the same deduction, so the drift alone does not identify the row.'),
  ('completion', 'beginner', 'module', 'm06-the-associate-reading', 6, 'A junior engineer says the completion is three and a half inch so it will fit five and a half inch casing. What is wrong?', '["Nothing is wrong; the statement is correct as given.", "The size named is the pipe, and the pipe is never the widest thing in a completion.", "The casing weight has not been stated, and without it the drift cannot be found, so the comparison cannot be made at all.", "Five and a half inch casing is never used as a production string, so the comparison is not one that would arise on a real well."]'::jsonb, 1, 'Three items in that kit will not enter that casing, and the pipe is not one of them.'),
  ('completion', 'beginner', 'module', 'm06-the-associate-reading', 7, 'Which pair of numbers would you scan for first to predict which component sets the through bore?', '["The largest values in the outside diameter column.", "The shortest components in the string, since a short component is more likely to carry a machined internal restriction.", "The smallest values in the inside diameter column.", "The components placed below the packer, because those are the ones that a tool has to reach last and therefore last limit."]'::jsonb, 2, 'The largest outside diameters predict the clearance check instead, which is the other scan.'),
  ('completion', 'beginner', 'module', 'm06-the-associate-reading', 8, 'A tally closes: the last bottom depth equals the hanger plus the sum of the lengths. What has that proved?', '["That the tally is correct in every respect.", "That no component has had its inside and outside diameters entered the wrong way round anywhere in the string.", "That the string will reach the intended packer setting depth once it has been run into the well and landed at surface.", "That the depths follow from the lengths, and nothing about whether the lengths are right."]'::jsonb, 3, 'A wrong length gives a wrong sum, a wrong bottom and a perfectly consistent tally.'),
  ('completion', 'beginner', 'module', 'm06-the-associate-reading', 9, 'Somebody proposes filling a gap in the casing program with the bore of the section above it. Why is that wrong?', '["Because it substitutes a guess for missing data and produces a complete looking answer.", "Because the section above is always wider than the missing one.", "Because the resulting profile would fail to merge correctly with the sections below the gap, which changes the row count.", "Because a gap in the program means the well was drilled open hole there, so no casing bore of any kind should be assumed."]'::jsonb, 0, 'The engine returns nothing for a clearance and a warning for a volume, and neither invents a bore.'),
  ('completion', 'beginner', 'module', 'm06-the-associate-reading', 10, 'A vendor quotes a safety valve at five and a quarter inches outside diameter. How does that compare with this catalog?', '["It contradicts the catalog and one of the two must be wrong.", "It is narrower than the representative value, which is the sort of difference a real data sheet produces.", "It is impossible, because a safety valve cannot be machined narrower than the coupling of the tubing it is made up into.", "It is irrelevant, because the catalog values are the ones the calculations in this course are validated against and must use."]'::jsonb, 1, 'The magnitudes move with a real catalog and the ordering does not.'),
  ('completion', 'beginner', 'module', 'm06-the-associate-reading', 11, 'Which single number would you want before agreeing that a completion is runnable?', '["The total length of the string.", "The ratio between the displacement and the capacity, which describes how much steel there is per unit of flow area.", "The tightest clearance in the string, with the component it belongs to named.", "The drift of the shallowest casing string, since that is the first restriction anything run into the well has to pass."]'::jsonb, 2, 'The tightest row is the design. Everything else on the sheet is passing comfortably.'),
  ('completion', 'beginner', 'module', 'm06-the-associate-reading', 12, 'You are asked for the pit gain expected while running a completion with the bottom open. Which volume do you use?', '["The capacity of the string.", "The displacement of the string, which is the volume of its outside envelope taken over the whole of its length.", "The annulus volume above the packer, since that is the space the string is being run into and therefore what it fills.", "The steel volume, which is the displacement less the capacity."]'::jsonb, 3, 'Run open ended and the string fills as it goes, so only the steel actually displaces fluid from the well.'),
  ('completion', 'beginner', 'module', 'm06-the-associate-reading', 13, 'Why does the engine name which depth is out of range when the packer and total depth conflict?', '["Because the two errors come from different places and the reader should not have to check both.", "Because the specification requires named errors.", "Because the packer depth and the total depth are entered by different people, so naming one assigns responsibility for it.", "Because the calculation can continue if only one of the two is wrong, and naming it tells the caller which one to correct."]'::jsonb, 0, 'A mistyped packer depth and a mistyped total depth are different mistakes with the same symptom.'),
  ('completion', 'beginner', 'module', 'm06-the-associate-reading', 14, 'What would you need before quoting any number from this course in a design document?', '["A signed copy of the API specification.", "Real vendor dimensions, because every equipment row here is flagged as representative.", "A second engineer to check the arithmetic, since the calculations in this course have not been independently verified.", "The measured lengths of the actual joints, without which no depth in the tally can be relied upon for a real string."]'::jsonb, 1, 'The method transfers exactly and the numbers do not transfer at all.'),
  ('completion', 'beginner', 'module', 'm06-the-associate-reading', 15, 'Where does this course sit in relation to Casing and Tubing Design?', '["The two courses cover the same material at different depths.", "This course computes the loads on the tubing, and that course checks whether the tubing selected can survive them.", "That course sizes the casing this one has to fit a string through.", "That course is a prerequisite, and its Expert certificate is required before this one can be attempted at any tier."]'::jsonb, 2, 'There is no hard prerequisite inside the Drilling and Completions module, and the two are natural companions.'),
  ('completion', 'beginner', 'final', null, 1, 'A new graduate is told the completion is the last string in the well and asks what came out before it. What is the right answer?', '["Nothing; the completion is run before the casing.", "The drill string, the work string and the running tools, all of which are temporary.", "The casing, which is pulled once the cement has set and the well has been handed over from drilling to production.", "Only the drilling bottom hole assembly, since every other string run into a well is left in place for the life of it."]'::jsonb, 1, 'The completion is the only thing in the hole when the well is handed over.'),
  ('completion', 'beginner', 'final', null, 2, 'A completion has to allow tools to be run later. Which diameter does that requirement depend on?', '["The inside diameters of the components, taken as a minimum from the top.", "The outside diameters of the components.", "The casing inside diameter, since a tool run on wireline travels in the annulus between the tubing and the casing wall.", "The tubing outside diameter, because the coupling of the tubing is the widest part of the string that a tool has to pass."]'::jsonb, 0, 'Getting a tool through is inside diameters against each other, not outside diameters against a bore.'),
  ('completion', 'beginner', 'final', null, 3, 'You are shown a component five and three quarter inches outside with a bore of two and three quarter inches. What is it likely to be?', '["A perforated joint.", "A plain joint of three and a half inch tubing, whose coupling reaches that outside diameter while the bore stays full.", "A safety valve, whose body houses a flapper and a hydraulic piston around a restricted bore.", "A wireline entry guide, whose bell mouth widens the body while narrowing the bore that a tool passes through it."]'::jsonb, 2, 'Wide outside and narrow inside is the signature of a valve, and it is one of the widest items in the kit.'),
  ('completion', 'beginner', 'final', null, 4, 'A designer asks the engine for a production rate. What happens?', '["It returns a rate based on the through bore.", "It returns a rate estimated from the string capacity and the expected drawdown across the perforated interval at the bottom.", "It refuses the request and names the missing input, which is the permeability of the formation the well is completed in.", "Nothing; the engine has no reservoir model and computes no rate at all."]'::jsonb, 3, 'Inflow, tubing stress and running loads all belong to other courses with the inputs this one lacks.'),
  ('completion', 'beginner', 'final', null, 5, 'A joint of casing has a published bore of eight point five three five inches. A tool of that diameter is proposed. What do you say?', '["That the guaranteed size is the drift, which is smaller, and the tool should be checked against that.", "That the tool will pass, since it equals the bore.", "That the tool will pass provided it is shorter than the drift mandrel used to test that joint at the mill when it was made.", "That the bore quoted is a minimum rather than a nominal figure, so any tool at or below it is guaranteed to go through."]'::jsonb, 0, 'Wall tolerance, ovality and straightness all make the effective bore smaller than nominal.'),
  ('completion', 'beginner', 'final', null, 6, 'Two joints of nine and five eighths inch casing at different weights are on the rack. What do their drifts have in common?', '["Nothing; the drift depends on the weight alone.", "The same deduction was taken off each, because both are the same outside diameter.", "The same drift value, because the specification publishes one drift per casing size regardless of the wall thickness.", "The same ratio of drift to nominal bore, since the deduction is defined as a fixed percentage of the published inside diameter."]'::jsonb, 1, 'Their drifts differ only because their nominal bores differ.'),
  ('completion', 'beginner', 'final', null, 7, 'A reimplementation reports a drift for eight and five eighths inch casing that is smaller than the published one by a thirty second of an inch. What is the likely cause?', '["It applied the tubing deduction by mistake.", "It used the outside diameter in place of the nominal bore before subtracting the deduction, which shifts every result equally.", "It placed the boundary size in the class above, treating the top of the range as exclusive.", "It converted the deduction from inches to millimetres twice, which reduces every drift in the table by the same proportion."]'::jsonb, 2, 'The ranges are inclusive at the top, and getting that wrong is worth three quarters of a millimetre on a common size.'),
  ('completion', 'beginner', 'final', null, 8, 'A tally has fourteen rows and its last bottom depth does not equal the sum of the lengths. What do you conclude?', '["The hanger depth is not zero.", "One of the components has been entered with its diameters swapped, which is the only error that breaks the identity.", "The tally is correct but the sum has been taken over the wrong column, which is the usual cause of this discrepancy.", "The tally has been built wrong, and every depth below the error is wrong with it."]'::jsonb, 3, 'The telescoping identity holds for any hanger depth, so a failure to close is an error in the tally.'),
  ('completion', 'beginner', 'final', null, 9, 'A packer is moved from two thousand six hundred metres to two thousand three hundred in a well with a liner top at twenty four hundred. What changes?', '["Its clearance rises sharply, because it is now checked against the casing rather than the liner.", "Nothing, because the packer body is unchanged.", "Its clearance falls, because the casing higher in the well is heavier and therefore has a smaller bore than the liner does.", "Only the volumes change, since the clearance check reads the component diameters and not the depth at which it is placed."]'::jsonb, 0, 'Nothing about the packer changed. The geometry above it changed.'),
  ('completion', 'beginner', 'final', null, 10, 'You are asked why the packer cannot simply be moved above the liner top on a real well. What is the constraint?', '["Packers cannot be set in casing, only in liners.", "It has to sit above the perforations and below the liner top, which leaves it inside the liner.", "The volume above the packer would change, and the packer fluid has already been ordered against the original figure.", "The setting tool cannot reach above the liner top once the string has been made up with the tail below the packer in place."]'::jsonb, 1, 'The tight clearance follows from a reservoir depth and a casing program that were both fixed first.'),
  ('completion', 'beginner', 'final', null, 11, 'A row in a tally has an inside diameter larger than its outside diameter. What should the tool do?', '["Swap them silently and continue.", "Accept it and report a negative steel volume for that component, which alerts the reader without stopping the calculation.", "Refuse the input, naming both diameters, because the row describes no physical object.", "Accept it and flag it as a warning, since the same pattern legitimately describes a component with an eccentric internal bore."]'::jsonb, 2, 'Both consequences of a swap flatter the design, which is why it has to be caught at the input.'),
  ('completion', 'beginner', 'final', null, 12, 'Somebody argues that a component wider than the casing should be refused as an invalid input. Why is that wrong?', '["Because the casing bore is not known at input time.", "Because the engine has no way of comparing a component diameter against a casing bore until the profile has been built.", "Because a component wider than the casing can still be run if it is placed above the depth at which that casing begins.", "Because it describes a real design with a real answer, and the answer is a failed clearance check."]'::jsonb, 3, 'An input that cannot describe any object is refused; a design that will not work is computed and reported.'),
  ('completion', 'beginner', 'final', null, 13, 'A nipple is proposed at the coupling diameter of the tubing it is made up into. What does that cost in runability?', '["Nothing, because the coupling has to pass the casing anyway.", "A significant loss, since it is wider than the pipe body.", "It depends on the depth at which it is placed, because the governing bore changes with depth and so does the cost of the width.", "A small loss that is offset by the wall thickness gained, which is what allows the internal profile to be machined at all."]'::jsonb, 0, 'Matching the coupling costs nothing and buys wall thickness for the profile.'),
  ('completion', 'beginner', 'final', null, 14, 'A well can take five and a half inch casing at twenty pounds per foot. A three and a half inch completion is proposed. What is your first question?', '["Whether the tubing coupling will pass, which it will not.", "Which of the big body items are in the kit, because three of them will not go.", "What grade of tubing is being proposed, since the wall thickness at that grade decides whether the pipe body itself will fit.", "Whether the casing has been drifted since it was run, because the published drift is the only figure available otherwise."]'::jsonb, 1, 'The side pocket mandrel, the safety valve and the expansion joint are the three that fail.'),
  ('completion', 'beginner', 'final', null, 15, 'A client needs gas lift in a well whose casing will not take the side pocket mandrel. What are the real options?', '["Ream the casing to accept the mandrel.", "Run the mandrel above the point where the casing tightens, which puts the injection point higher than the design intended.", "Drop a tubing size, use a slimline mandrel, or do without gas lift in this well.", "Accept the negative clearance, on the grounds that the published drift is conservative and the real bore will be larger."]'::jsonb, 2, 'None of the three is free, and the choice is made once and lived with for the life of the well.'),
  ('completion', 'beginner', 'final', null, 16, 'You need to know how much fluid to pump to fill an empty completion string. Which volume is that?', '["The displacement of the string.", "The steel volume, which is the difference between the displacement and the capacity of the same string over its length.", "The annulus volume above the packer, since that is the space the fluid occupies once the string has been run and landed.", "The capacity, which is the inside area of each component times its length, summed."]'::jsonb, 3, 'It is also what has to come out when the tubing is displaced.'),
  ('completion', 'beginner', 'final', null, 17, 'A string has a capacity of about eleven point eight cubic metres and a displacement of about twenty six point eight. What is the steel volume?', '["About fifteen cubic metres, which is the difference between the two.", "About thirty nine cubic metres, the sum of the two.", "It cannot be found from those two numbers alone, because the steel volume also depends on the couplings and the upsets.", "About two and a quarter, which is the ratio of the two and therefore the fraction of the cross section that is metal."]'::jsonb, 0, 'Multiply it by the density of steel and you have the weight of the string in air.'),
  ('completion', 'beginner', 'final', null, 18, 'A colleague uses true vertical depths in a volume calculation on a well with a long tangent. What is the effect?', '["The volume comes out too large by the same ratio.", "The volume comes out too small, by the ratio between the two depths.", "The volume is unaffected, because the areas involved do not depend on the inclination of the hole at any depth.", "The volume is only affected below the kick off point, and the error there is proportional to the square of the inclination."]'::jsonb, 1, 'The number would still look plausible, which is what makes it dangerous.'),
  ('completion', 'beginner', 'final', null, 19, 'The engine reports a volume together with a warning naming a depth interval. How should that be read?', '["As a failed calculation that must be discarded.", "As a complete volume with a note that the casing program in that interval was entered from a different source than the rest.", "As a real number that is definitely low, by an amount the named interval bounds.", "As a volume computed with the bore of the nearest section above the gap, which the warning identifies for the reader."]'::jsonb, 2, 'A partial volume with a named hole is useful; a partial one presented as complete is not.'),
  ('completion', 'beginner', 'final', null, 20, 'You are told a completion is geometrically possible. What has actually been established?', '["That it will produce at the design rate.", "That it can be run to depth in the well it was designed for, on the trajectory that well was actually drilled on.", "That every component in it is rated for the pressure and temperature the well will see over its producing life.", "That it fits, and nothing about whether it can be run, will produce, or is correctly rated."]'::jsonb, 3, 'Geometric possibility is a hard constraint that binds before anything else.'),
  ('completion', 'beginner', 'final', null, 21, 'A tally shows four rows carrying almost all the length and nine short rows. What does that distribution tell you?', '["That anything unusual is nearly always in the short rows, which set the fit and not the depths.", "That the tally has probably been entered incorrectly.", "That the string is unusually equipment heavy, since nine pieces of equipment in thirteen rows is well above the normal number.", "That the four long rows are the ones to check first, because an error in them changes the fit of everything below."]'::jsonb, 0, 'A tubing length changes the depths below it; an equipment length changes almost nothing about them.'),
  ('completion', 'beginner', 'final', null, 22, 'A drift run is proposed before a workover on a five year old well. What is the argument for it?', '["The specification requires one before any intervention.", "The catalog drift describes new pipe, and what is in the hole now is a different object.", "The drift of a casing string changes with the pressure and temperature history it has seen while the well was producing.", "The original mill records are unavailable, so the drift of the string is unknown and has to be established afresh."]'::jsonb, 1, 'Scale, wax, corrosion product and a deformed section are all possible and none is in the catalog.'),
  ('completion', 'beginner', 'final', null, 23, 'A summary reports the worst clearance in a passing string as over a hundred millimetres. What would you check first?', '["Whether the casing program was entered correctly.", "Whether the units are consistent, since a hundred millimetres is a plausible figure if the value has been reported in the wrong one.", "Which row it selected, against the list of rows sorted by clearance.", "Whether the warn margin was set high enough, because a margin that is too low makes every row report as passing comfortably."]'::jsonb, 2, 'When a tool reports a single worst case out of many, check it against the list once by hand.'),
  ('completion', 'beginner', 'final', null, 24, 'The tubing bore is two point nine nine two inches and a nipple bore is two point six three five. Which limits a wireline tool?', '["The tubing, because it makes up most of the string.", "Whichever is shallower in the string, since a tool encounters that one first and is stopped by it before reaching the other.", "Neither on its own; the limit is the average of the two weighted by the length over which each of them applies.", "The nipple, because access is limited by the smallest bore above the target depth."]'::jsonb, 3, 'That is the through bore question, and it is a minimum rather than an average.'),
  ('completion', 'beginner', 'final', null, 25, 'You want to know the weight of a completion string in air. What do you need beyond the tally?', '["A steel density, applied to the steel volume the tally gives you.", "A survey of the well the string will be run into.", "The buoyancy factor for the fluid the string will be run in, which converts the volume of steel into a weight in the well.", "The grade of each component, since the weight per unit length depends on the grade as well as on the wall thickness."]'::jsonb, 0, 'Weight in the well needs buoyancy as well, and that belongs to another course.'),
  ('completion', 'beginner', 'final', null, 26, 'A component is described as eccentric. Which item is it likely to be, and why?', '["A flow coupling, because its wall is thicker on one side.", "A side pocket mandrel, because it carries a valve in a pocket beside the bore.", "An expansion joint, because one tube slides inside another and the two are not concentric while the joint is stroking.", "A sliding sleeve, because the ports are machined on one side of the body so that they can be shifted by a wireline tool."]'::jsonb, 1, 'The offset pocket is what makes it one of the widest items in the kit.'),
  ('completion', 'beginner', 'final', null, 27, 'Which single fact explains why a flow coupling exists?', '["It couples two different tubing sizes together.", "It provides a place to land a plug at a known depth, which is why one is placed above and below every restriction.", "Turbulence downstream of a restriction erodes the pipe, so a thick wall is put where it will happen.", "It stiffens the string across the depth interval where the largest bending loads occur during running and pulling."]'::jsonb, 2, 'It is sacrificial by design.'),
  ('completion', 'beginner', 'final', null, 28, 'A well needs a plug set at a known depth. Which component makes that possible?', '["The wireline entry guide at the bottom.", "The sliding sleeve, which can be shifted closed by the same tool that would otherwise be used to set the plug in place.", "The packer, whose bore is the smallest in the string and therefore the natural place for a plug to be set and to seal.", "A landing nipple, whose machined seat a lock mandrel latches into."]'::jsonb, 3, 'The nipple gives both a known depth and a seal bore for the plug.'),
  ('completion', 'beginner', 'final', null, 29, 'You are given only a drift value and asked whether a five and seven eighths inch packer will pass. What else do you need?', '["Nothing else; subtract the packer diameter from the drift and read the sign.", "The weight and grade of the casing.", "The depth at which the packer will be set, because the drift quoted may not be the governing one for that particular depth.", "The length of the packer, since a long component needs more clearance than a short one of the same outside diameter."]'::jsonb, 0, 'At this tier the comparison is a subtraction. The governing drift question comes in the next tier.'),
  ('completion', 'beginner', 'final', null, 30, 'Somebody proposes a fixed percentage drift deduction instead of the API step function. What would that do to heavy pipe?', '["It would deduct more from heavy pipe than at present.", "It would deduct less from heavy pipe, because its bore is smaller, weakening the guarantee where it is tightest.", "It would leave the guarantee unchanged, since a percentage of a smaller bore and a fixed value are equivalent at the boundary.", "It would make no practical difference, because the wall thickness of casing varies by only a few percent within any one size."]'::jsonb, 1, 'The deduction protects against absolute effects, so an absolute deduction is the right shape.'),
  ('completion', 'beginner', 'final', null, 31, 'A tally is measured twice on the rig floor by two people. What error is that guarding against?', '["A swapped pair of diameters in one of the rows.", "A component omitted from the tally entirely, which would be caught by the count and not by measuring the lengths again.", "A wrong length, which shifts every depth below it and leaves the arithmetic perfectly consistent.", "A component placed in the wrong order, which changes the through bore without changing the total length of the string."]'::jsonb, 2, 'Nothing in the arithmetic can detect a wrong length, which is why the measured lengths are what get recorded.'),
  ('completion', 'beginner', 'final', null, 32, 'A completion is advertised as a two point six three five inch bore string. What has not been said?', '["Which casing the string is run inside.", "Whether the figure is a nominal bore or a drift, which for a machined nipple profile are two quite different numbers.", "What the tubing size is, since a bore figure alone does not identify the pipe the completion is made up from.", "How much of the string that restriction actually governs, which may be a few metres."]'::jsonb, 3, 'An extreme value summary is correct and can be badly misleading about how typical it is.'),
  ('completion', 'beginner', 'final', null, 33, 'The volume below a packer is reported using the full casing bore rather than an annular area. Why?', '["Because the tail is open and perforated, so the fluid inside it and around it are the same body.", "Because the tail of the string is very short.", "Because the annular area below a packer cannot be computed without knowing the outside diameter of the perforated joint.", "Because the volume below the packer is used only for ordering fluid, where a gross figure is the conservative choice."]'::jsonb, 0, 'Treating it as an annulus would exclude a volume that nothing physical excludes.'),
  ('completion', 'beginner', 'final', null, 34, 'An engineer wants to add inflow performance to this engine. What has to arrive first?', '["A survey of the well.", "A reservoir model, with a permeability, a skin and a drawdown.", "A temperature and pressure history for the string, from which the flowing conditions at each depth could then be derived.", "A friction factor and a hook load model, without which the flow inside the tubing cannot be related to the pressure drop."]'::jsonb, 1, 'Every excluded item needs an input the model does not carry, which is where the scope line is drawn.'),
  ('completion', 'beginner', 'final', null, 35, 'You are told the through bore of a string is set by its no go nipple. Is that a design problem?', '["Yes; the nipple should be replaced with a larger bore.", "Yes, unless the nipple is the deepest component in the string, in which case the restriction affects nothing below it.", "No; stopping a tool of the wrong size is exactly what a no go nipple is for.", "It depends on the tubing size, because a no go bore below the tubing bore is acceptable only in the larger sizes."]'::jsonb, 2, 'A course that treated the smallest bore as a problem would have missed the point of the component causing it.'),
  ('completion', 'beginner', 'final', null, 36, 'A component list arrives with no hanger depth given. What does the engine assume?', '["It refuses the input until a hanger depth is supplied.", "It sets the hanger at the depth of the shallowest casing section, which is where a string run from surface would be hung.", "It infers the hanger depth from the packer depth and the lengths below the packer, working upward from the reservoir.", "Nothing is assumed; the hanger depth defaults to the surface datum and is added to every depth."]'::jsonb, 3, 'A hanger above zero happens on a string run on a work string or hung off a liner top.'),
  ('completion', 'beginner', 'final', null, 37, 'Which statement about the four deduction values is correct?', '["Tubing takes the smallest of the four, even though it is the smallest pipe in the well.", "Tubing takes the largest of the four.", "The four values increase with pipe size in equal steps, so that the deduction is proportional to the outside diameter.", "The tubing value falls between the two largest casing values, which is why tubing drifts are close to small casing drifts."]'::jsonb, 0, 'The reason is the mandrel programme, not the pipe, and it is a coincidence worth not relying on.'),
  ('completion', 'beginner', 'final', null, 38, 'Which scan on a tally predicts the run in clearance result before it is computed?', '["The smallest values in the inside diameter column.", "The largest values in the outside diameter column, read together with their depths.", "The longest components in the string, since a longer component needs more clearance to pass a bend than a short one does.", "The total of the outside diameters, compared against the smallest casing bore anywhere in the program above the packer."]'::jsonb, 1, 'The smallest inside diameters predict the through bore instead.'),
  ('completion', 'beginner', 'final', null, 39, 'A completion tally lists a component twice at different depths. Is that an error?', '["Yes, every component may appear only once.", "Yes, unless the two entries have different lengths, in which case they represent two separately measured joints of the same type.", "Not necessarily; four runs of plain tubing appear in the published string at four different depths.", "It depends on the component type, since equipment may be repeated and tubing may not be entered more than once per string."]'::jsonb, 2, 'A tally is a list of what is in the string in order, and repetition is normal.'),
  ('completion', 'beginner', 'final', null, 40, 'You want to compare two completion designs for a well. Which single number is most informative?', '["The total length of each string.", "The ratio of displacement to capacity in each, which describes how much steel each design carries per unit of flow area.", "The number of components in each, since a simpler string carries fewer restrictions and fewer opportunities for a fit problem.", "The tightest clearance in each, with the component named."]'::jsonb, 3, 'The tightest row is the design; everything else on the sheet is passing comfortably.'),
  ('completion', 'beginner', 'final', null, 41, 'A tool reports the through bore and nothing else. What would you ask for next?', '["The extent, meaning how much of the string that restriction governs.", "The outside diameter of the same component.", "The depth at which the restriction occurs, which together with the bore is enough to describe the access the string offers.", "The next smallest bore in the string, so that the consequence of removing the controlling component can be evaluated."]'::jsonb, 0, 'When a summary is a minimum or a maximum, ask over how much.'),
  ('completion', 'beginner', 'final', null, 42, 'Which of these is the correct order of work when a completion tally arrives?', '["Run every check first, then read the tally.", "Scan it, predict what the checks will say, then run them and compare.", "Compute the volumes first, since they validate the tally arithmetic before any fit question is asked of the same numbers.", "Check the equipment against the vendor data sheets first, so that the catalog values used are correct before anything is run."]'::jsonb, 1, 'When a prediction disagrees with a check you have found either an error or something interesting.');
