-- ============================================================================
-- DR3 PROFESSIONAL DEEP SEED: Drilling Hydraulics, intermediate tier.
--
-- Six modules, 26 lessons, 132 questions (15 per module bank plus a 42
-- question final exam). The structure row is GENERATED from the tier's
-- manifest.json.
--
-- What this tier owns: the annulus, which is carrying cuttings and pressing on
-- the formation at the same time. Only the annulus loss reaches the rock,
-- because the pipe and the bit are inside the string; the equivalent
-- circulating density divides by TRUE VERTICAL depth, which is why a lateral
-- raises it so sharply and why using measured depth is an error in the unsafe
-- direction; it is a PROFILE and the formation that fractures is not always
-- the deepest one; and cuttings are worth about 11.6 kg/m3 of bulk density per
-- percent by volume in this mud and are absent from the pressure calculation.
-- Annular velocity is flow rate over area, so the slowest place is the WIDEST
-- annulus, which is the shallowest; slip velocity is a falling particle solved
-- with Schiller-Naumann drag and it RISES where the annulus is tight because
-- the mud is sheared thinner there. Cleaning wants more flow and the formation
-- wants less, and on this well the PUMP binds first.
--
-- THE LIMITATION THIS TIER IS BUILT AROUND. The transport model has no
-- inclination term at all, and the engine's own output proves it: the
-- horizontal well and the slant well return identical transport ratios at
-- every flow rate. Cuttings beds above about 30 degrees are the dominant real
-- hole cleaning mechanism, they are moved by rotation first and flow rate
-- second, and neither rotation nor a bed exists in this model. The computed
-- transport ratio is an UPPER BOUND on a deviated well and the tier says so
-- rather than inventing an inclination correction with no oracle behind it.
--
-- Numeric sweep 200 literals / 0 unresolved over the lessons; tier-leakage 0
-- downward leaks and 0 same-tier answer prints over the lessons and the banks.
--
-- Answer keys live only here and in academy_quiz_questions.
-- ============================================================================

insert into public.academy_course_structures
    (app_slug, tier, structure, content_version)
values ('hydraulics', 'intermediate', '{"modules":[{"key":"m01-equivalent-circulating-density","title":"Equivalent Circulating Density","lesson_keys":["l01-only-the-annulus-reaches-the-rock","l02-the-definition","l03-the-profile-not-the-number","l04-what-raises-it","l05-cuttings-in-the-annulus"]},{"key":"m02-carrying-the-cuttings","title":"Carrying the Cuttings","lesson_keys":["l01-annular-velocity","l02-slip-velocity","l03-the-transport-ratio","l04-cuttings-concentration","l05-the-worst-section"]},{"key":"m03-cleaning-at-angle","title":"Cleaning at Angle","lesson_keys":["l01-why-inclination-changes-everything","l02-beds-and-what-moves-them","l03-what-this-model-does-not-see","l04-the-hole-cleaning-toolkit"]},{"key":"m04-the-flow-rate-decision","title":"The Flow Rate Decision","lesson_keys":["l01-two-constraints-one-number","l02-solving-for-the-minimum","l03-what-it-costs-at-the-pump","l04-when-there-is-no-answer","l05-the-nozzle-lever"]},{"key":"m05-against-the-oracle","title":"Against the Oracle","lesson_keys":["l01-what-the-goldens-are","l02-the-method-spec","l03-what-agreement-proves","l04-and-what-it-does-not"]},{"key":"m06-the-professional-reading","title":"The Professional Reading","lesson_keys":["l01-the-story-so-far","l02-working-the-capstone","l03-onward"]}]}'::jsonb, 1)
on conflict (app_slug, tier) do update
  set structure = excluded.structure,
      content_version = excluded.content_version,
      active = true,
      updated_at = now();

delete from public.academy_quiz_questions
 where app_slug = 'hydraulics' and tier = 'intermediate';

insert into public.academy_quiz_questions
    (app_slug, tier, scope, module_key, ord, prompt, options, answer_index, explanation)
values
  ('hydraulics', 'intermediate', 'module', 'm01-equivalent-circulating-density', 1, 'Why does the formation see only the annulus loss?', '["Because the pipe and the bit are inside the string and the steel contains them.", "Because the annulus loss is the largest.", "Because the annulus is where the mud is slowest, so it is the only place the pressure has time to reach the rock.", "Because the pipe and bit losses are recovered as the mud leaves the nozzles, so they never reach the annulus."]'::jsonb, 0, 'The annulus loss is the SMALLEST of the three on this system, and it is the only one the rock feels.'),
  ('hydraulics', 'intermediate', 'module', 'm01-equivalent-circulating-density', 2, 'What is the equivalent circulating density?', '["The pump pressure over the depth.", "The mud weight plus the total pressure loss over the measured depth, which is what a driller reads on the gauge.", "The mud weight plus the annulus loss below the point, over gravity times the true vertical depth.", "The bulk density of the mud and cuttings mixture in the annulus while circulating at the drilling rate."]'::jsonb, 2, 'The cuttings contribution is real and it is not in this expression. The divisor is TRUE VERTICAL depth, which matters on a deviated well.'),
  ('hydraulics', 'intermediate', 'module', 'm01-equivalent-circulating-density', 3, 'Why is the divisor true vertical depth rather than measured depth?', '["Because measured depth is not known.", "Because a static pressure comes from vertical height, so an equivalent density has to divide by it.", "Because the annulus loss accumulates along the measured depth, so dividing by it would double count the length.", "Because a deviated well has a longer measured depth and the convention is to normalise it away."]'::jsonb, 1, 'Using measured depth understates the equivalent circulating density on every deviated well, which is the unsafe direction.'),
  ('hydraulics', 'intermediate', 'module', 'm01-equivalent-circulating-density', 4, 'Why is the horizontal well''s ECD uplift larger than the slant well''s, on a smaller annulus loss?', '["Because its annulus is tighter.", "Because its lateral has a higher annular velocity, which raises the friction per metre through the whole section.", "Because it is shallower in measured depth, so the same loss is spread over a shorter flow path.", "Because its true vertical depth is smaller, and the loss is divided by it."]'::jsonb, 3, 'Every metre of lateral adds friction to the numerator and nothing to the denominator, which is what makes long laterals a pressure problem.'),
  ('hydraulics', 'intermediate', 'module', 'm01-equivalent-circulating-density', 5, 'Where in a well is the equivalent circulating density usually largest?', '["At surface.", "At the casing shoe, which is where the annulus changes size and the velocity steps up.", "At total depth, because the friction contribution accumulates downward.", "In the middle of the open hole, where the annular velocity is highest and the friction per metre peaks."]'::jsonb, 2, 'It starts at the mud weight at surface, because there is no annulus above surface, and it grows downward.'),
  ('hydraulics', 'intermediate', 'module', 'm01-equivalent-circulating-density', 6, 'Why is the whole ECD profile needed rather than the value at total depth?', '["Because the formation that fractures is not always the deepest one.", "Because the profile is smoother.", "Because the value at total depth is the least reliable, being the end of the longest accumulation of friction.", "Because the profile is what the pressure-while-drilling tool measures, and comparing needs both to be profiles."]'::jsonb, 0, 'A weak shallow shale sees a lower ECD than total depth and it may still be the one that breaks, because its fracture gradient is lower.'),
  ('hydraulics', 'intermediate', 'module', 'm01-equivalent-circulating-density', 7, 'Of the numbers that add up to a circulating density, which dominates?', '["The annulus friction.", "The static mud weight, by a wide margin.", "The cuttings contribution, which on a fast-drilling well exceeds the friction uplift at ordinary flow rates.", "The true vertical depth, which appears in the denominator and therefore dominates the arithmetic."]'::jsonb, 1, 'On this well the uplift is under 60 kg/m3 against a mud weight of 1440, so the friction is under five percent of the answer.'),
  ('hydraulics', 'intermediate', 'module', 'm01-equivalent-circulating-density', 8, 'What is the flow rate''s exponent on the annulus loss, and what follows?', '["About 2, so it doubles it fourfold.", "About 1, so the ECD uplift is directly proportional to the flow rate and is easy to extrapolate.", "It varies with the mud, so no general statement can be made about how a rate change moves the ECD.", "About 0.75, so doubling the rate raises the ECD by much less than double."]'::jsonb, 3, 'It inherits the mud''s flow behaviour index directly, because the annulus is laminar and the fluid is shear thinning.'),
  ('hydraulics', 'intermediate', 'module', 'm01-equivalent-circulating-density', 9, 'Comparing the two muds at the same rate, how much of the ECD difference is rheology?', '["None: the difference is all density.", "About 5 percent, since the two muds'' flow behaviour indices differ by under a tenth and the effect is proportional.", "About 23 percent of the annulus loss, on top of the density difference.", "It cannot be separated, because the density and the rheology both enter the friction factor calculation."]'::jsonb, 2, 'The density enters linearly and the rheology enters through the friction factor. Both move together between these two muds.'),
  ('hydraulics', 'intermediate', 'module', 'm01-equivalent-circulating-density', 10, 'Which change LOWERS the equivalent circulating density?', '["A washout that enlarges the annulus.", "A tighter annulus.", "A higher rate of penetration, since the cuttings displace mud from the annulus and reduce its effective density.", "A deeper well, since the loss is divided by the true vertical depth and a deeper well has more of it."]'::jsonb, 0, 'It is one of the few things a washout is good for, and it comes with worse hole cleaning as the price.'),
  ('hydraulics', 'intermediate', 'module', 'm01-equivalent-circulating-density', 11, 'How much does one percent of cuttings by volume raise the annulus bulk density?', '["About 26 kg/m3.", "About 11.6 kg/m3 for this mud, from the difference between the cuttings and the mud.", "About 1.4 kg/m3, which is one percent of the mud''s own density and is negligible against the friction uplift.", "It depends on the flow rate, because a faster annulus carries the cuttings for a shorter time."]'::jsonb, 1, 'It is one percent of the difference between 2600 and the mud''s density, and at low flow rate it is comparable to the friction uplift.'),
  ('hydraulics', 'intermediate', 'module', 'm01-equivalent-circulating-density', 12, 'Which way does the missing cuttings term bias the computed ECD?', '["It overstates it.", "It has no bias, because the cuttings displace an equal volume of mud and the bulk density is unchanged.", "It UNDERSTATES it, and most at low flow rate.", "It understates it at high flow rate and overstates it at low rate, since the concentration falls with rate."]'::jsonb, 2, 'The concentration falls as the rate rises, so the two effects partly cancel and the true ECD is flatter against rate than the friction alone.'),
  ('hydraulics', 'intermediate', 'module', 'm01-equivalent-circulating-density', 13, 'Why does the engine not couple the cuttings into the pressure calculation?', '["Because cuttings are negligible.", "Because the cuttings concentration is computed after the pressure loss, so the information is not available in time.", "Because the goldens do not include a coupled case, so the engine would have nothing to be checked against.", "Because doing it consistently is a coupled problem and doing it approximately is left to the reader."]'::jsonb, 3, 'It computes both quantities and leaves the coupling explicit, which is a defensible choice as long as it is stated.'),
  ('hydraulics', 'intermediate', 'module', 'm01-equivalent-circulating-density', 14, 'What is the practical correction for cuttings?', '["Take the worst concentration, compute the bulk density, and re-read the ECD with that as the mud weight.", "Add ten percent to the ECD.", "Multiply the annulus loss by one plus the concentration, since the friction scales with the fluid''s density.", "Nothing can be done, because the concentration varies along the annulus and a single correction is meaningless."]'::jsonb, 0, 'It ignores the depth distribution of the cuttings and it is much better than ignoring them entirely.'),
  ('hydraulics', 'intermediate', 'module', 'm01-equivalent-circulating-density', 15, 'What does the ECD profile do through a horizontal lateral?', '["It stays flat.", "It rises steeply against depth, because the lateral adds friction and no true vertical depth.", "It falls, because the annular velocity in the lateral is lower than in the build section above it.", "It rises linearly with measured depth, exactly as it does in the vertical section above the build."]'::jsonb, 1, 'Plotted against true vertical depth it rises vertically, which is the clearest way to see why a lateral is a pressure problem.'),
  ('hydraulics', 'intermediate', 'module', 'm02-carrying-the-cuttings', 1, 'What is the annular velocity?', '["The mud''s speed at the pump.", "The cuttings'' speed up the annulus, which is what the transport calculation is trying to determine.", "The flow rate divided by the open area between the hole and the pipe.", "The flow rate divided by the hole''s cross-sectional area, ignoring the pipe that occupies part of it."]'::jsonb, 2, 'Nothing else enters it: not the mud, not the depth, not the rheology. It is pure geometry and flow rate.'),
  ('hydraulics', 'intermediate', 'module', 'm02-carrying-the-cuttings', 2, 'Where is the annular velocity lowest in this course''s wells?', '["In the shallowest cased section, which is the widest annulus.", "Around the collars at total depth.", "In the middle of the open hole, where the drill pipe is smallest relative to the hole it is running in.", "It is uniform, because the flow rate is constant and the annulus is a single continuous path to surface."]'::jsonb, 0, 'The tight annulus around the collars is nearly twice as fast, which is why the worst cleaning is at the top and the worst loss is at the bottom.'),
  ('hydraulics', 'intermediate', 'module', 'm02-carrying-the-cuttings', 3, 'How fast does a cutting fall through mud that is standing still?', '["The speed the mud slips past the wall.", "The terminal speed a cutting falls at through stationary mud.", "The difference between the annular velocity and the cuttings'' velocity, which is what the transport ratio measures.", "The velocity at which a cutting starts to move, below which it stays on the low side of the hole."]'::jsonb, 1, 'It is a force balance: weight less buoyancy against drag, with the drag coefficient from the Schiller-Naumann correlation.'),
  ('hydraulics', 'intermediate', 'module', 'm02-carrying-the-cuttings', 4, 'What makes the slip velocity calculation circular?', '["Nothing, it is a closed form.", "The cutting''s size changes as it travels, so the diameter used in the balance depends on how far it has come.", "The mud''s density in the buoyancy term depends on the cuttings concentration, which depends on the slip.", "The drag coefficient depends on the Reynolds number, which depends on the velocity being solved for."]'::jsonb, 3, 'The engine iterates. Schiller-Naumann is standard, published, and valid from creeping flow up to a Reynolds number of a few hundred.'),
  ('hydraulics', 'intermediate', 'module', 'm02-carrying-the-cuttings', 5, 'Which annulus section makes a cutting fall fastest, and why?', '["In the wide annulus at the top.", "It is the same everywhere, because the cuttings'' size and density do not change along the annulus.", "In the tight annulus at the bottom, because the mud is sheared thinner there.", "At the shoe, where the annulus changes size abruptly and the flow is neither fully developed nor uniform."]'::jsonb, 2, 'The apparent viscosity FALLS where the annulus is tight, and a thinner mud offers less resistance to a falling chip.'),
  ('hydraulics', 'intermediate', 'module', 'm02-carrying-the-cuttings', 6, 'What is the transport ratio?', '["One less the slip velocity over the annular velocity.", "The annular velocity over the slip.", "The fraction of the cuttings that reach surface, as against those that settle out on the way up.", "The ratio of the cuttings'' volume to the mud''s volume in the annulus at any moment."]'::jsonb, 0, 'It is the fraction of the mud''s speed the cuttings actually travel at, so 0.83 means they are moving at 83 percent of the mud.'),
  ('hydraulics', 'intermediate', 'module', 'm02-carrying-the-cuttings', 7, 'Which mud in this course cleans better, and why?', '["The light one, being easier to pump.", "The heavy one, through both buoyancy and viscosity.", "The heavy one, but only through buoyancy: the two muds'' viscosities are similar at annular shear rates.", "They clean identically, since the transport ratio depends on the annular velocity and both are pumped at the same rate."]'::jsonb, 1, 'Buoyancy reduces the driving term in the slip velocity and viscosity resists the fall. Both help and both point the same way.'),
  ('hydraulics', 'intermediate', 'module', 'm02-carrying-the-cuttings', 8, 'What is a typical target for a transport ratio?', '["Above 0.99 always.", "Exactly 1.0, since anything less means cuttings are accumulating in the annulus faster than they are removed.", "Below 0.5, since a high ratio means the flow rate is unnecessarily high and the ECD is being wasted.", "Between about 0.5 and 0.9, depending on the hole angle and the tolerance."]'::jsonb, 3, 'Below 0.5 the cuttings are moving at less than half the mud''s speed. Above 0.9 the ratio is no longer the constraint.'),
  ('hydraulics', 'intermediate', 'module', 'm02-carrying-the-cuttings', 9, 'What does the transport ratio NOT tell you?', '["How fast the cuttings are moving.", "How the cleaning varies between the annulus sections, which requires reading the per-interval table instead.", "Whether the hole is clean, which depends on the rate of penetration as well.", "How much flow rate would be needed to improve it, which requires the minimum-flow solver."]'::jsonb, 2, 'A hole can have a good transport ratio and still be full of cuttings if the bit is making them fast enough.'),
  ('hydraulics', 'intermediate', 'module', 'm02-carrying-the-cuttings', 10, 'What is the cuttings feed rate?', '["The rate of penetration times the bit''s cross-sectional area.", "The flow rate times the concentration.", "The volume of cuttings arriving at the shakers per unit time, which is what a mud logger measures directly.", "The mass of rock the bit removes per unit time, divided by the cuttings'' density of 2600 kg/m3."]'::jsonb, 0, 'At the engine''s default of 0.005 m/s of penetration it is about 0.18 litres per second against 25 of mud.'),
  ('hydraulics', 'intermediate', 'module', 'm02-carrying-the-cuttings', 11, 'Why does the cuttings concentration fall faster than the transport ratio rises?', '["Because the feed rate falls with flow rate.", "Because the annular velocity appears in the denominator twice, directly and through the transport ratio.", "Because the slip velocity falls as the flow rate rises, which raises the cuttings'' speed more than proportionally.", "Because a faster annulus is turbulent, and turbulent flow suspends cuttings far more effectively than laminar."]'::jsonb, 1, 'That is why raising the rate is such an effective response to a dirty hole: it more than halves the concentration for a doubling.'),
  ('hydraulics', 'intermediate', 'module', 'm02-carrying-the-cuttings', 12, 'What concentration is usually regarded as a problem?', '["Above one percent.", "Above 0.5 percent, since above that the annulus''s bulk density has risen enough to affect the equivalent circulating density.", "There is no threshold: the concentration is a continuous quantity and any value can be managed with enough rotation.", "Above about four or five percent by volume."]'::jsonb, 3, 'The annulus starts to behave differently, the ECD rises and the risk of packing off around the assembly grows.'),
  ('hydraulics', 'intermediate', 'module', 'm02-carrying-the-cuttings', 13, 'Where are the worst transport ratio and the worst concentration?', '["The ratio at the top, the concentration at the bottom.", "Both at the bottom, around the collars, where the annulus is tightest and the cuttings have furthest to travel.", "Both in the shallowest, widest annulus interval.", "The ratio is uniform and the concentration is worst at the top, because that is where the cuttings accumulate."]'::jsonb, 2, 'Cuttings accumulate where they travel slowest, exactly as traffic does, and the slowest place is the widest annulus.'),
  ('hydraulics', 'intermediate', 'module', 'm02-carrying-the-cuttings', 14, 'Which two numbers together describe the annulus''s state?', '["The transport ratio and the cuttings concentration.", "The annular velocity and the slip.", "The equivalent circulating density and the pump pressure, which between them describe the whole circulating system.", "The apparent viscosity and the Reynolds number, which determine the flow regime in each annulus section."]'::jsonb, 0, 'One says how well the annulus is working and the other says how much is in it, and the concentration is the one that predicts a pack-off.'),
  ('hydraulics', 'intermediate', 'module', 'm02-carrying-the-cuttings', 15, 'Why does a big hole section need such a large flow rate?', '["Because the cuttings are bigger.", "Because velocity is flow rate over area and the area is large.", "Because the rate of penetration is higher in a soft shallow formation, so the cuttings feed rate is greater.", "Because the mud is thinner in the shallow section, where it has not yet been contaminated with drilled solids."]'::jsonb, 1, 'The rate of penetration point contributes too. The dominant effect is geometric, and it is why the pump limits the big sections.'),
  ('hydraulics', 'intermediate', 'module', 'm03-cleaning-at-angle', 1, 'In an inclined hole, what happens to a cutting?', '["It stays suspended in the mud.", "It falls across the annulus and lands on the low side almost immediately.", "It falls along the hole rather than across it, so the transport calculation applies with the gravity term reduced.", "It is carried by the turbulent eddies, which are stronger at angle because the flow is no longer axisymmetric."]'::jsonb, 1, 'The distance it has to fall is the annular gap, which is centimetres. Once it lands it is part of a bed rather than a particle in a fluid.'),
  ('hydraulics', 'intermediate', 'module', 'm03-cleaning-at-angle', 2, 'What is different about moving a bed rather than a suspended cutting?', '["It needs a different mechanism: scouring, rolling or lifting it back into suspension.", "Nothing, it is the same physics.", "It needs a higher flow rate, which is the same mechanism applied more strongly rather than a different one.", "It needs a denser mud, since buoyancy is what determines whether a bed can be lifted off the low side."]'::jsonb, 0, 'None of the three mechanisms is a falling-particle force balance, and none of them is in this model.'),
  ('hydraulics', 'intermediate', 'module', 'm03-cleaning-at-angle', 3, 'How does the engine''s output demonstrate the missing inclination term?', '["It prints a warning.", "The transport ratio falls with inclination in the per-interval table, but the summary reports only the worst value.", "The slip velocity rises with inclination, which is visible in the table but is not carried into the ratio.", "The horizontal well and the slant well return identical transport ratios at every flow rate."]'::jsonb, 3, 'The two wells have identical annulus geometry and identical flow rates, and the model has no other input that could distinguish them.'),
  ('hydraulics', 'intermediate', 'module', 'm03-cleaning-at-angle', 4, 'What are the three inclination regimes real experience finds?', '["Laminar, transitional and turbulent.", "Suspension below 45 degrees and beds above it, with no intermediate regime worth distinguishing.", "Suspension below about 30 degrees, sliding beds from 30 to 60, stable beds above 60.", "Vertical, deviated and horizontal, corresponding to 0, 45 and 90 degrees of inclination respectively."]'::jsonb, 2, 'The middle one is the difficult regime, because a bed can slide back down the hole under its own weight, and a build section passes through it.'),
  ('hydraulics', 'intermediate', 'module', 'm03-cleaning-at-angle', 5, 'What is the most effective bed removal mechanism in a deviated hole?', '["Rotating the drill string, which stirs the bed mechanically.", "Raising the flow rate.", "Pumping a high-viscosity sweep, which lifts the cuttings in suspension and carries them out as a slug.", "Reciprocating the string, which drags the assembly through the bed and mobilises it along its length."]'::jsonb, 0, 'All four are used. Rotation is first, and it is entirely absent from every model in this course.'),
  ('hydraulics', 'intermediate', 'module', 'm03-cleaning-at-angle', 6, 'Why is rotation absent from the model?', '["Because it has no effect on cleaning.", "Because the annulus is assumed concentric with a stationary inner pipe.", "Because the rotary speed is not one of the inputs the goldens supply, so there is nothing to check a model against.", "Because rotation affects the pressure loss rather than the cleaning, and this module is about cleaning."]'::jsonb, 1, 'Rotation affects both, and it changes the pressure loss in either direction depending on the regime.'),
  ('hydraulics', 'intermediate', 'module', 'm03-cleaning-at-angle', 7, 'Why do a high-viscosity sweep and a low-viscosity sweep both work?', '["Only one of them works.", "Both raise the annular velocity, since a sweep is pumped at a higher rate than the normal circulating rate.", "They work by opposite mechanisms: one lifts in suspension, the other scours the bed.", "Both raise the equivalent circulating density briefly, which lifts the bed off the low side by buoyancy."]'::jsonb, 2, 'Which one to use depends on the angle, which is exactly the variable this model does not have.'),
  ('hydraulics', 'intermediate', 'module', 'm03-cleaning-at-angle', 8, 'What does eccentricity do to the cleaning?', '["Improves it, by raising the velocity.", "Leaves it unchanged, since the total flow area is the same whether the pipe is centred or lying on the low side.", "Improves it in a vertical hole and worsens it in a horizontal one, since the pipe only lies down at angle.", "Makes it much worse: the flow takes the wide side and the cuttings are on the narrow one."]'::jsonb, 3, 'It also LOWERS the pressure loss, so eccentricity is conservative for the pressure and dangerously optimistic for the cleaning.'),
  ('hydraulics', 'intermediate', 'module', 'm03-cleaning-at-angle', 9, 'Which two of the six omissions matter most on a 3000 m horizontal well?', '["Inclination and rotation.", "Particle size and time.", "Eccentricity and cuttings interaction, both of which are geometric effects that grow with the hole''s length.", "Time and particle size distribution, since a long lateral takes many hours to clean and the fines behave differently."]'::jsonb, 0, 'All six matter. The first two are the ones that change the answer by a factor rather than a fraction.'),
  ('hydraulics', 'intermediate', 'module', 'm03-cleaning-at-angle', 10, 'What status does a computed transport ratio have on a deviated well?', '["An exact answer.", "An upper bound: the real cleaning is worse and by an amount that is not an input.", "A lower bound, since the model omits rotation and pipe movement, both of which improve the cleaning.", "A ranking only: it can compare two flow rates and cannot be interpreted as a fraction at all."]'::jsonb, 1, 'Rotation does improve it, and the model also omits eccentricity and beds, which more than offset that.'),
  ('hydraulics', 'intermediate', 'module', 'm03-cleaning-at-angle', 11, 'Which hole cleaning tools can this model price?', '["All of them.", "The flow rate and the rotation, since both enter the annular velocity through the shear rate at the wall.", "The flow rate, and partly the mud rheology.", "None of them, since every mechanism that actually moves a bed is outside the model''s scope."]'::jsonb, 2, 'It computes what a thicker mud does to the slip and to the annulus loss, and it does not compute what a thicker mud does to a bed.'),
  ('hydraulics', 'intermediate', 'module', 'm03-cleaning-at-angle', 12, 'What is the closest thing to a direct measurement of hole cleaning?', '["The cuttings volume at the shakers.", "The transport ratio, computed from a survey and a flow rate, which is what this course produces.", "The torque and drag, which rises with a dirty hole and is measured at surface on every connection.", "Downhole equivalent circulating density from a pressure-while-drilling tool."]'::jsonb, 3, 'The shakers and the torque are both real indicators and both are indirect. A measured ECD above the computed one says the annulus holds more than assumed.'),
  ('hydraulics', 'intermediate', 'module', 'm03-cleaning-at-angle', 13, 'What connects this course''s largest omission to the torque and drag course''s?', '["They are the same missing mechanism: a cuttings bed, seen from two sides.", "Nothing connects them.", "Both courses omit pipe rotation, which affects the friction factor in one and the annular flow in the other.", "Both courses omit temperature, which changes the mud''s rheology and therefore both the drag and the pressure loss."]'::jsonb, 0, 'A bed is the largest single thing a fitted friction factor absorbs, and the way to see it is to watch both models drift at once.'),
  ('hydraulics', 'intermediate', 'module', 'm03-cleaning-at-angle', 14, 'Two mechanisms clean the hole and raise the equivalent circulating density at the same time. Which?', '["Rotation and pipe movement.", "Raising the flow rate and thickening the mud.", "Reciprocating the string and pumping a sweep, both of which add a displaced volume on top of the circulating rate.", "Rotation and raising the flow rate, since rotation adds a tangential velocity that raises the total shear rate."]'::jsonb, 1, 'That conflict is real: two of the four cleaning levers make the pressure problem worse, and the other two do not.'),
  ('hydraulics', 'intermediate', 'module', 'm03-cleaning-at-angle', 15, 'What is the honest description of this model''s transport calculation?', '["A general hole cleaning model.", "Valid for any inclination, since the slip velocity is a property of the particle and the fluid rather than of the geometry.", "Valid for a near-vertical hole at moderate concentration with a stationary concentric string.", "Valid only for the two wells in the fixture set, since the goldens contain no other geometry to check it against."]'::jsonb, 2, 'That is a real and useful calculation. It is not a hole cleaning model for a deviated well, and the difference matters most where cleaning is hardest.'),
  ('hydraulics', 'intermediate', 'module', 'm04-the-flow-rate-decision', 1, 'What are the two constraints on the flow rate?', '["Cleaning wants more and the formation wants less.", "The pump and the mud pumps'' liners.", "The bit''s hydraulic power wants more and the annular velocity wants less, since a fast annulus erodes the hole.", "The equivalent circulating density wants more and the surge pressure wants less, and both scale with the rate."]'::jsonb, 0, 'The pump is a third constraint and on many rigs it is the one that binds first.'),
  ('hydraulics', 'intermediate', 'module', 'm04-the-flow-rate-decision', 2, 'What shape does the transport ratio take against flow rate?', '["It rises linearly.", "It rises to a maximum and then falls, because at high rate the flow becomes turbulent and the slip velocity rises.", "It rises steeply at low rate and flattens, so the benefit has diminishing returns.", "It is a step: below a threshold rate the cuttings do not move at all and above it they move with the mud."]'::jsonb, 2, 'Meanwhile the pressure cost has slightly accelerating returns, so there is a rate beyond which you pay more and get less.'),
  ('hydraulics', 'intermediate', 'module', 'm04-the-flow-rate-decision', 3, 'How does the engine solve for a minimum flow rate?', '["A closed-form inversion.", "Bisection over the flow rate on the transport ratio, sixty halvings.", "Newton iteration on the derivative of the transport ratio with respect to the flow rate, which has a closed form.", "A sweep at fixed increments, returning the first rate whose transport ratio exceeds the target."]'::jsonb, 1, 'Bisection needs monotonicity, and the transport ratio is monotone in the flow rate by construction.'),
  ('hydraulics', 'intermediate', 'module', 'm04-the-flow-rate-decision', 4, 'What does the solver return when the target is unreachable?', '["The maximum rate in its bracket.", "The rate that gets closest to the target, with a warning that the target itself could not be reached.", "Zero, since no rate satisfies the condition and zero is the conventional answer for an empty set.", "Null, rather than a number."]'::jsonb, 3, 'That is a real outcome: a target of 0.99 on a wide annulus may simply not be achievable, and returning null is honest.'),
  ('hydraulics', 'intermediate', 'module', 'm04-the-flow-rate-decision', 5, 'How much more flow does the light mud need to reach the same transport ratio?', '["Forty to fifty percent more, at every target.", "About the same.", "Roughly double, which is why a light mud is never used in a section where hole cleaning is a concern.", "It depends on the target: at 0.5 the two muds are equal and the gap opens only above about 0.9."]'::jsonb, 0, 'That is a very large penalty and it is why mud rheology is a hole cleaning decision rather than only a pressure one.'),
  ('hydraulics', 'intermediate', 'module', 'm04-the-flow-rate-decision', 6, 'Going from a transport ratio of 0.9 to 0.95, what happens to the required flow rate?', '["It rises by about ten percent.", "It rises by about half, since the transport ratio approaches one asymptotically and the last increments are dear.", "It more than doubles.", "It falls, because the higher rate makes the annulus turbulent and turbulent flow transports cuttings more efficiently."]'::jsonb, 2, 'The last five percentage points of transport cost more than the first ninety, which is the diminishing return in its starkest form.'),
  ('hydraulics', 'intermediate', 'module', 'm04-the-flow-rate-decision', 7, 'What three numbers should a flow rate recommendation carry?', '["Only the flow rate itself.", "The transport ratio it achieves, the pump pressure it needs, and the ECD it produces.", "The flow rate, the mud weight and the rate of penetration, which are the three inputs the calculation depends on.", "The minimum, the maximum and the recommended value, so that the reader can see how much room there is."]'::jsonb, 1, 'One of the three on its own has not made a decision, and the whole trade is between the second and the third.'),
  ('hydraulics', 'intermediate', 'module', 'm04-the-flow-rate-decision', 8, 'Which constraint usually binds first on this course''s well?', '["The fracture gradient.", "The cleaning, since the annulus is wide in the cased section and the transport ratio is low at ordinary rates.", "The bit''s hydraulic power, which falls below any useful level once the nozzles are opened up enough to reach the rate.", "The pump, by a wide margin."]'::jsonb, 3, 'At 0.040 m3/s this well needs over 26 MPa and at 0.050 nearly 40, both beyond a normal rig, while the ECD has barely moved.'),
  ('hydraulics', 'intermediate', 'module', 'm04-the-flow-rate-decision', 9, 'Why is the pump usually the binding constraint rather than the formation?', '["Because the pump pressure more than doubles over a range where the ECD rises by under three percent.", "Because pumps are undersized.", "Because the formation''s fracture gradient is usually far above the mud weight, while the pump''s rating is close to its working pressure.", "Because the ECD is computed with a margin already built in, so it appears more comfortable than it is."]'::jsonb, 0, 'The asymmetry between the two exponents, about 1.72 for the pipe and 0.75 for the annulus, is the whole reason.'),
  ('hydraulics', 'intermediate', 'module', 'm04-the-flow-rate-decision', 10, 'What are the three ways the flow rate problem has no solution?', '["Only the pump case exists.", "The mud is too thin, the annulus too wide or the rate of penetration too high for any rate to keep up.", "The target is unreachable, the pump cannot supply it, or the formation cannot take it.", "The bit balls up, the hole packs off, or the string sticks, which are the three failure modes of a dirty hole."]'::jsonb, 2, 'The first two are engineering problems with equipment answers. The third is a rock problem and you cannot buy a higher fracture gradient.'),
  ('hydraulics', 'intermediate', 'module', 'm04-the-flow-rate-decision', 11, 'What is the one lever that relieves the pump constraint alone?', '["The mud weight.", "The nozzle total flow area.", "The flow rate, since reducing it lowers the pump pressure faster than it lowers the equivalent circulating density.", "The rate of penetration, since drilling more slowly reduces the cuttings load and therefore the annular pressure."]'::jsonb, 1, 'It leaves the pipe loss, the annulus loss, the ECD and the cleaning all exactly unchanged.'),
  ('hydraulics', 'intermediate', 'module', 'm04-the-flow-rate-decision', 12, 'What does opening the nozzles cost?', '["The equivalent circulating density.", "The hole cleaning, since a slower jet clears the bottom less well and the cuttings are recut before they leave.", "Nothing at all, which is why it should always be the first lever tried on any well.", "Bit hydraulics: the jet velocity and the power at the bit both fall."]'::jsonb, 3, 'Recutting is a real cost and it is a bottom-hole cleaning effect rather than an annular one. Whether it matters depends on the formation.'),
  ('hydraulics', 'intermediate', 'module', 'm04-the-flow-rate-decision', 13, 'What is the right order to try levers in when the pump is the constraint?', '["Nozzles, then the string''s bore, then the mud, then the flow rate.", "Flow rate first, always.", "The mud first, since it is the input most easily changed at the rig and it affects both constraints at once.", "The string''s bore first, since it is the largest lever on pump pressure by a considerable margin."]'::jsonb, 0, 'The bore IS the largest lever and it needs a different assembly. Nozzles are free and are changed at the rig floor.'),
  ('hydraulics', 'intermediate', 'module', 'm04-the-flow-rate-decision', 14, 'What is the trap in optimising nozzles first?', '["There is no trap.", "The nozzle area affects the equivalent circulating density, so it has to be fixed before the ECD check can be made.", "The flow rate is set by the annulus, so choosing nozzles before the rate gets it backwards.", "The nozzle area affects the cleaning through the jet velocity, so the two decisions cannot be separated at all."]'::jsonb, 2, 'It is how a bit hydraulics optimisation produces a well that cannot be cleaned.'),
  ('hydraulics', 'intermediate', 'module', 'm04-the-flow-rate-decision', 15, 'A well needs a flow rate the pump cannot supply. Which response does NOT help?', '["A larger bore in the assembly.", "Raising the mud weight.", "Larger nozzles, which cut the bit''s share of the pump pressure without changing the flow rate or the annulus.", "A thinner mud, which lowers the pipe loss and the annulus loss together at the cost of worse cleaning."]'::jsonb, 1, 'A heavier mud raises every one of the three losses, so it makes the pump constraint worse rather than better.'),
  ('hydraulics', 'intermediate', 'module', 'm05-against-the-oracle', 1, 'What is in the goldens for each case?', '["A single pump pressure.", "Three rheology fits, three flow rates of hydraulics, four surge and swab results, and one cleaning result.", "The engine''s own output recorded once, so that any later change to the code shows as a regression.", "Field measurements from four real wells, against which the model''s predictions have been validated."]'::jsonb, 1, 'More than a hundred values in all, and they came from a separate program rather than from this engine.'),
  ('hydraulics', 'intermediate', 'module', 'm05-against-the-oracle', 2, 'Why is an independent implementation the check rather than a hand calculation?', '["Because a hydraulics run on a real string is dozens of elements and nothing about it is checkable by hand.", "Because hand calculations are slow.", "Because the method specification is proprietary, so no published worked example exists to compare against.", "Because the goldens have to cover four cases and three flow rates, which is too many to do by hand."]'::jsonb, 0, 'Each element needs a local power law and a friction factor from a correlation, and there is no closed form for the total.'),
  ('hydraulics', 'intermediate', 'module', 'm05-against-the-oracle', 3, 'How many points does the method specification name, and how many are conventions?', '["Three, all of them derived.", "Seven, of which one is a convention, the blend width, and the other six are either derived or measured.", "Seven, of which four are conventions rather than derivations.", "Twelve, matching the twelve inputs the calculation takes, with each one specified to avoid ambiguity."]'::jsonb, 2, 'Derived: the 16 and the 24. Correlations: Bourgoyne and Schiller-Naumann. Conventions: the local power law, the Reynolds definition, the blend and the clinging constant.'),
  ('hydraulics', 'intermediate', 'module', 'm05-against-the-oracle', 4, 'Which two points of the specification are exact derivations?', '["The Bourgoyne turbulent correlation.", "The Schiller-Naumann drag correlation and the Burkhardt clinging constant, both of which are published results.", "The generalised Reynolds number and the local power law, both of which follow from the Herschel-Bulkley model.", "The laminar friction factors of 16 over Re in a pipe and 24 over Re in an annulus."]'::jsonb, 3, 'They fall out of solving the flow exactly in the two geometries. Everything else is a fit or a choice.'),
  ('hydraulics', 'intermediate', 'module', 'm05-against-the-oracle', 5, 'What tolerance do the goldens ask for, and does the engine meet it?', '["Better than one part in a million, and it does everywhere.", "One percent, and it does.", "One part in a hundred million, which the engine meets on the rheology fits and misses on the pump pressures.", "No tolerance is stated: the goldens are a regression baseline rather than an independent check."]'::jsonb, 0, 'The rheology agrees to about 1e-10, surge and swab to about 1e-16, and the pump pressures to about 1e-7.'),
  ('hydraulics', 'intermediate', 'module', 'm05-against-the-oracle', 6, 'Why do the surge and swab pressures agree at machine precision?', '["Because they are read from a table.", "Because they involve no rheology, since the clinging constant replaces the friction factor in that calculation.", "Because the calculation is short and both implementations do it identically.", "Because the goldens were generated by this engine for that subsystem and by numpy for the others."]'::jsonb, 2, 'Short chains agree at machine precision and long chains accumulate rounding. That is a clean comparison rather than a suspicious one.'),
  ('hydraulics', 'intermediate', 'module', 'm05-against-the-oracle', 7, 'Why is the pump pressure the largest disagreement?', '["Because it is the largest number.", "Because it is the longest chain: a fit, a local power law per element, a Reynolds number, a friction factor, a sum.", "Because the two implementations use different blend widths, and the pipe elements sit inside the transition band.", "Because it includes the surface loss, which one implementation sets to zero and the other omits entirely."]'::jsonb, 1, 'About 1e-7 over that chain is what a long floating-point calculation looks like, and it is a function of the length rather than of a choice.'),
  ('hydraulics', 'intermediate', 'module', 'm05-against-the-oracle', 8, 'What does agreement between the two implementations prove?', '["That the specification is correct.", "That the friction factor correlations are valid within their stated ranges, since both reproduce them exactly.", "That the mud rheology models describe a real drilling fluid, since both fit the same four dial readings.", "That two people reading the same specification wrote code producing the same numbers."]'::jsonb, 3, 'It eliminates transcription, sign, unit and misread-formula errors, which between them are most of the defects that occur.'),
  ('hydraulics', 'intermediate', 'module', 'm05-against-the-oracle', 9, 'What does it NOT eliminate?', '["Sign errors.", "Unit errors, which would show only if the two implementations used different unit systems internally.", "A shared misreading of the specification, and anything about the specification itself.", "Discretisation error, since both implementations discretise the flow path into the same elements."]'::jsonb, 2, 'There is no discretisation: the elements come from the string and the geometry. The four conventions are shared by construction.'),
  ('hydraulics', 'intermediate', 'module', 'm05-against-the-oracle', 10, 'How does this comparison differ from the torque and drag course''s?', '["That one had a real disagreement to explain and a closed form to settle it; this one has neither.", "It is identical in structure.", "That one agreed at machine precision throughout and this one has a residual at 1e-7 in the longest chain.", "That one compared against field measurements and this one against an independent implementation."]'::jsonb, 0, 'The disagreement is the more instructive of the two, because it forces the question of which implementation is closer.'),
  ('hydraulics', 'intermediate', 'module', 'm05-against-the-oracle', 11, 'What does field validation of drilling hydraulics look like?', '["A laboratory flow loop.", "A pressure-while-drilling tool measuring the annulus pressure, compared against the computed ECD.", "A comparison of the measured standpipe pressure against the computed pump pressure, which is available on every rig.", "A leak-off test at the shoe, which establishes the fracture gradient the computed ECD is compared against."]'::jsonb, 1, 'The standpipe comparison is genuinely useful and it validates the pipe and bit terms rather than the annulus one.'),
  ('hydraulics', 'intermediate', 'module', 'm05-against-the-oracle', 12, 'How close do published field comparisons come?', '["Within one part in a million.", "Within one percent, which is why a computed equivalent circulating density can be compared directly against a fracture gradient.", "They do not agree at all, which is why downhole measurement replaced calculation on every well that can afford it.", "Within five to fifteen percent of the circulating uplift, which is far worse than 1e-6."]'::jsonb, 3, 'That is the number that actually matters, and it is why a computed ECD within 10 kg/m3 of a fracture gradient is not a safe answer.'),
  ('hydraulics', 'intermediate', 'module', 'm05-against-the-oracle', 13, 'Which omissions account for the field gap, and which way does each go?', '["All of them raise it.", "All of them lower it, which is why a concentric non-rotating calculation is systematically conservative.", "Cuttings raise the real pressure; eccentricity and temperature lower it; rotation does either.", "Only cuttings matter, and they raise it by about 11.6 kg/m3 per percent by volume in this mud."]'::jsonb, 2, 'Because they do not all point one way, the field comparisons come out within tens of percent rather than wrong by a factor.'),
  ('hydraulics', 'intermediate', 'module', 'm05-against-the-oracle', 14, 'How should a computed equivalent circulating density be used?', '["Comparatively with confidence, absolutely with a margin, and against a downhole measurement where one exists.", "Absolutely, to two decimal places.", "Only comparatively, since the absolute value carries an uncertainty of tens of percent and is therefore meaningless.", "Only against a downhole measurement, since without one the calculation has no reference at all."]'::jsonb, 0, 'The differences between cases are much better determined than the absolute values, which is true of almost every model in this series.'),
  ('hydraulics', 'intermediate', 'module', 'm05-against-the-oracle', 15, 'What four statements should accompany a computed ECD?', '["The flow rate and the mud weight.", "It excludes cuttings, assumes concentric geometry, assumes no rotation, and uses surface-temperature rheology.", "The method specification, the software version, the date and the engineer, which is what a fitted parameter needs.", "The pore pressure, the fracture pressure, the mud weight and the flow rate, which are the four numbers it is compared against."]'::jsonb, 1, 'Four sentences, and they are the difference between a number and a number somebody can use.'),
  ('hydraulics', 'intermediate', 'module', 'm06-the-professional-reading', 1, 'Having finished the Professional modules, which skill have you earned?', '["Computing a pump pressure.", "Saying how fast the string may be tripped without fracturing the formation or bringing in a kick.", "Saying what the rock feels while the pumps run, and how well the annulus is carrying.", "Designing a mud whose rheology satisfies both the cleaning and the pressure constraints simultaneously."]'::jsonb, 2, 'The first is the Associate tier and the second is the Expert tier. Mud design is an application rather than the certified skill.'),
  ('hydraulics', 'intermediate', 'module', 'm06-the-professional-reading', 2, 'If the Professional tier had one line, what would it be?', '["The annulus carries cuttings and presses on the formation at once, and the rate that helps one hurts the other.", "Only the annulus loss reaches the rock.", "The transport ratio is one less the slip velocity over the annular velocity, and the worst is where the annulus is widest.", "The equivalent circulating density divides by true vertical depth, which is why a lateral raises it so sharply."]'::jsonb, 0, 'All three are true statements from this tier. The claim is the conflict that holds them together.'),
  ('hydraulics', 'intermediate', 'module', 'm06-the-professional-reading', 3, 'Which depth does the equivalent circulating density divide by, and why does it matter?', '["Measured depth, being the flow path.", "True vertical depth, and it is why a lateral raises the ECD so much.", "True vertical depth, and it matters only on wells above about 60 degrees where the two diverge substantially.", "The bit depth in measured units, converted to vertical at the end using the survey''s average inclination."]'::jsonb, 1, 'Every metre of lateral adds friction to the numerator and nothing to the denominator, exactly as it adds contact length and no TVD in torque and drag.'),
  ('hydraulics', 'intermediate', 'module', 'm06-the-professional-reading', 4, 'Where is the hole cleaning worst, and why does that surprise people?', '["At total depth, as expected.", "Around the collars, where the annulus is tightest and the cuttings have the furthest still to travel.", "At the casing shoe, where the annulus changes size and the flow is neither fully developed nor uniform.", "In the shallowest, widest annulus, because velocity is flow rate over area."]'::jsonb, 3, 'It is also the opposite of where the annular pressure loss concentrates, which is the tight annulus around the collars.'),
  ('hydraulics', 'intermediate', 'module', 'm06-the-professional-reading', 5, 'What is the clearest evidence of the model''s missing inclination term?', '["The model prints a warning.", "The slip velocity is independent of the annular velocity, which cannot be true for a particle in a moving fluid.", "The horizontal well and the slant well return identical transport ratios at every rate.", "The transport ratio exceeds one at high flow rates, which is physically impossible for a settling particle."]'::jsonb, 2, 'A 40 degree hole and a 90 degree hole cannot clean the same. The model says they do, because it has no angle input.'),
  ('hydraulics', 'intermediate', 'module', 'm06-the-professional-reading', 6, 'A percent of rock is in the annulus. What does that do to what the formation feels?', '["About 11.6 kg/m3, from the difference between the cuttings and the mud.", "About 26 kg/m3.", "About 1.4 kg/m3, which is one percent of the mud''s own density and is negligible beside the friction uplift.", "It depends on the transport ratio, because slower cuttings spend longer in the annulus and accumulate more."]'::jsonb, 0, 'The concentration DOES depend on the transport ratio; the density effect per percent does not. At low rate it is comparable to the friction uplift.'),
  ('hydraulics', 'intermediate', 'module', 'm06-the-professional-reading', 7, 'The last five percentage points of transport. What do they cost?', '["It rises by about a tenth.", "It more than doubles.", "It falls, because a higher rate makes the annulus turbulent and turbulent flow carries cuttings far better.", "It rises by about half, since the transport ratio approaches one asymptotically as the slip becomes negligible."]'::jsonb, 1, 'The last five percentage points cost more than the first ninety, which is why a target above about 0.9 is rarely worth setting.'),
  ('hydraulics', 'intermediate', 'module', 'm06-the-professional-reading', 8, 'How much extra flow does the light mud need for the same cleaning?', '["About the same.", "About ten percent more, since the two muds differ mainly in density and buoyancy is a small term in the slip velocity.", "Roughly triple, since the light mud''s apparent viscosity at annular shear rates is a third of the heavy mud''s.", "Forty to fifty percent more, at every target."]'::jsonb, 3, 'That is why mud rheology is a hole cleaning decision rather than only a pressure one.'),
  ('hydraulics', 'intermediate', 'module', 'm06-the-professional-reading', 9, 'Cleaning, the formation and the equipment all bound the rate. Which stops you first here?', '["The fracture gradient.", "The cleaning, since the transport ratio at ordinary rates is below the usual target of 0.9 on both muds.", "The pump.", "The bit''s hydraulic power, which cannot reach a classical optimum on this string at any achievable pressure."]'::jsonb, 2, 'The pump pressure more than doubles over a range where the ECD rises by under three percent, which is the asymmetry between the two exponents.'),
  ('hydraulics', 'intermediate', 'module', 'm06-the-professional-reading', 10, 'What does the capstone ask you for?', '["Two circulating densities, an annular velocity, a transport ratio, a concentration and a solved flow rate.", "Six pressures from one well.", "The three rheology fits and the four pressures the circulating system is made of, on the new mud.", "The surge and swab pressures at a stated trip speed, and the trip speed a stated window allows."]'::jsonb, 0, 'The first of the wrong answers is the Associate capstone and the second is the Expert one, over the same fixtures.'),
  ('hydraulics', 'intermediate', 'module', 'm06-the-professional-reading', 11, 'Which capstone field does not depend on the mud at all?', '["The transport ratio.", "The worst annular velocity, which is flow rate over area.", "The equivalent circulating density, since the mud weight is added back and the friction uplift is a small correction.", "The minimum flow rate, since the target transport ratio is stated and the solver hits it whatever the mud."]'::jsonb, 1, 'It is a free check: if it moves when you change the mud, something in the setup is wrong.'),
  ('hydraulics', 'intermediate', 'module', 'm06-the-professional-reading', 12, 'Which two capstone fields will be identical between the two wells?', '["The two circulating densities.", "The cuttings concentration and the minimum flow rate, both of which depend only on the annulus geometry.", "None of them: the two wells differ in survey, so every output differs between them.", "The transport ratio and the annular velocity."]'::jsonb, 3, 'The concentration and the minimum flow rate would also be identical, for the same reason: the model has no inclination term.'),
  ('hydraulics', 'intermediate', 'module', 'm06-the-professional-reading', 13, 'Which single idea is the frame the Expert tier puts everything else into?', '["That cuttings are not in the ECD.", "That the transport model has no inclination term, which is the largest single limitation in the whole course.", "That the four pressures in a well all live in one window, and this tier computed two of them.", "That the pump binds before the formation does on most wells, which is why the ECD is rarely the constraint."]'::jsonb, 2, 'All three are worth carrying. The first is the frame the Expert tier puts the other two into.'),
  ('hydraulics', 'intermediate', 'module', 'm06-the-professional-reading', 14, 'What does the Expert tier add?', '["Pressure from moving the string, with no pumps running at all.", "A better rheology model.", "The geomechanics that produce the pore pressure and the fracture gradient this tier compared against.", "The transient effects the steady-state model omits, including the pressure to accelerate the mud column."]'::jsonb, 0, 'The transients are named there and graded nowhere, and the geomechanics is a separate course in the module.'),
  ('hydraulics', 'intermediate', 'module', 'm06-the-professional-reading', 15, 'Which two habits does this tier ask you to carry?', '["Always use the highest flow rate.", "Name the pressure you mean, and state the scope with the answer.", "Always compute the ECD at total depth, and always compare it against the fracture gradient at the same depth.", "Always use the Herschel-Bulkley fit, and always refine the element list until the answer stops moving."]'::jsonb, 1, 'There is no element list to refine: the elements come from the string and the geometry rather than from a grid.'),
  ('hydraulics', 'intermediate', 'final', null, 1, 'A report gives an ECD at total depth and nothing else. What do you ask for?', '["The pump pressure at the same rate.", "The profile, because the formation that fractures is not always the deepest one.", "The mud weight it was computed from, since the ECD is the mud weight plus a small friction uplift.", "The flow rate, which is the only input that moves it and is often omitted from a summary."]'::jsonb, 1, 'The flow rate matters and is secondary. A weak shallow shale sees less ECD than total depth and may still be the one that breaks.'),
  ('hydraulics', 'intermediate', 'final', null, 2, 'An engineer computes an ECD on a horizontal well using measured depth. What happens?', '["The uplift comes out much too small, and on a lateral the error is large.", "Nothing, the two are close.", "The uplift comes out too large, since measured depth exceeds true vertical depth and the friction is spread over more of it.", "The profile shape is wrong but the value at total depth is right, since the two depths converge at the bit."]'::jsonb, 0, 'Dividing by a larger number gives a smaller uplift, and understating the ECD is the unsafe direction.'),
  ('hydraulics', 'intermediate', 'final', null, 3, 'Two wells have the same annulus loss and different true vertical depths. Which has the higher ECD uplift?', '["The deeper one.", "They are the same, because the ECD is defined so that the depth cancels between the friction and the hydrostatic terms.", "The shallower one, because the loss is divided by the smaller depth.", "It cannot be said without the mud weight, which enters the uplift through the density in the friction expression."]'::jsonb, 2, 'That is the mechanism that makes a long lateral a pressure problem: annulus length with no vertical depth to divide by.'),
  ('hydraulics', 'intermediate', 'final', null, 4, 'The cuttings concentration at a low flow rate is 1.65 percent. What does that do to the real ECD?', '["Nothing, cuttings are included.", "Lowers it, since the cuttings displace mud from the annulus and rock is less compressible than drilling fluid.", "Raises it by about 1.65 kg/m3, which is the concentration applied to the mud''s own density.", "Raises it by about 19 kg/m3 above the computed value on this mud."]'::jsonb, 3, 'It is the concentration times the difference between the cuttings and the mud, which for this mud is about 11.6 kg/m3 per percent.'),
  ('hydraulics', 'intermediate', 'final', null, 5, 'Raising the flow rate raises the friction uplift and lowers the cuttings uplift. What follows?', '["The two cancel exactly.", "The true ECD falls with flow rate, since the cuttings term is the larger of the two at ordinary drilling rates.", "The true ECD is flatter against flow rate than the friction calculation alone suggests.", "The friction calculation is useless, since it omits the term that dominates the answer at every rate."]'::jsonb, 2, 'It is a partial cancellation rather than an exact one, and it is a real and useful result for a narrow-window well.'),
  ('hydraulics', 'intermediate', 'final', null, 6, 'Where would you expect the worst annular velocity on a well with a 17 and a half inch section above a 12 and a quarter?', '["In the 12 and a quarter section.", "In the 17 and a half inch section, whose annulus is far wider.", "At the crossover between them, where the flow accelerates and the velocity profile is not fully developed.", "At total depth, where the annulus has the most cuttings in it and the effective area is smallest."]'::jsonb, 1, 'That is why the flow rate for a hole section is set by its top rather than its bottom, and why big sections need large pumps.'),
  ('hydraulics', 'intermediate', 'final', null, 7, 'A cutting''s slip velocity is higher in the tight annulus than in the wide one. Why?', '["The mud is sheared harder there, so its apparent viscosity is lower.", "The cutting is larger there.", "The annular velocity is higher, and the slip velocity is proportional to the velocity of the surrounding fluid.", "The pressure is higher at depth, which compresses the mud and reduces the drag on a falling particle."]'::jsonb, 0, 'It partly offsets the higher annular velocity in the same section, and the velocity term wins, so the transport ratio is still better there.'),
  ('hydraulics', 'intermediate', 'final', null, 8, 'A transport ratio of 0.83 means what?', '["83 percent of them reach surface.", "The annulus is 83 percent efficient at removing cuttings, so 17 percent of them settle out on the way up.", "The slip velocity is 83 percent of the annular velocity, so the cuttings are barely moving upward at all.", "The cuttings are travelling at 83 percent of the mud''s speed."]'::jsonb, 3, 'A slip of 83 percent of the annular velocity would be a transport ratio of 0.17, which is a very dirty hole.'),
  ('hydraulics', 'intermediate', 'final', null, 9, 'You double the flow rate. What happens to the cuttings concentration?', '["It halves exactly.", "It falls by less than half, because the transport ratio improves and the cuttings spend less time in the annulus.", "It falls by more than half, because the velocity appears in the denominator twice.", "It stays the same, since the feed rate is unchanged and the annulus volume is unchanged."]'::jsonb, 2, 'Once directly and once through the transport ratio, which is why raising the rate is such an effective response to a dirty hole.'),
  ('hydraulics', 'intermediate', 'final', null, 10, 'A model returns identical transport ratios for a 40 degree and a 90 degree well. What is your conclusion?', '["The two wells clean the same.", "It has no inclination term, so its answer on a deviated well is an upper bound.", "The two wells have different annulus geometries and the coincidence is worth investigating as a possible defect.", "The transport ratio is a property of the mud rather than the well, so identical muds give identical answers."]'::jsonb, 1, 'They have the SAME annulus geometry in this fixture set, which is why the model has nothing that could distinguish them.'),
  ('hydraulics', 'intermediate', 'final', null, 11, 'What is the most effective way to move a cuttings bed?', '["Rotate the string.", "Raise the flow rate.", "Pump a high-viscosity sweep, which lifts the bed into suspension and carries it out as a slug.", "Reciprocate the string, which drags the assembly through the bed and mobilises it mechanically."]'::jsonb, 0, 'All four are used and rotation is first. It is also entirely absent from every model in this course.'),
  ('hydraulics', 'intermediate', 'final', null, 12, 'Why is eccentricity conservative for the pressure and dangerous for the cleaning?', '["It is dangerous for both.", "It raises the pressure loss and improves the cleaning, since the narrow side has a higher local velocity.", "It has no effect on either, since the total flow area is unchanged when the pipe moves off centre.", "The flow takes the wide side, which lowers the loss and starves the low side where the cuttings are."]'::jsonb, 3, 'So a concentric non-rotating model overstates the ECD a little and overstates the hole cleaning a lot.'),
  ('hydraulics', 'intermediate', 'final', null, 13, 'Which two courses in this module are looking at the same missing mechanism?', '["This one and well design.", "This one and casing design, since both depend on the annulus geometry and neither models a bed within it.", "This one and torque and drag: a cuttings bed, from two sides.", "None of them: cuttings beds are a hole cleaning problem and appear in no other course in the module."]'::jsonb, 2, 'A bed is the largest single thing a fitted friction factor absorbs, and watching both models drift at once is how you see it.'),
  ('hydraulics', 'intermediate', 'final', null, 14, 'A rising fitted friction factor and a rising measured ECD, with no input change. What is it?', '["The mud has been weighted up.", "The hole is loading up with cuttings.", "The pipe has washed out, which raises the drag through the larger contact area and the ECD through the tighter annulus.", "The temperature downhole has risen, which thins the mud and would raise both quantities together."]'::jsonb, 1, 'A thinner mud LOWERS both. The pair of rising indicators is the clearest hole cleaning signal there is.'),
  ('hydraulics', 'intermediate', 'final', null, 15, 'What does the minimum flow solver return when the target cannot be reached?', '["Null, rather than a number.", "The maximum rate it searched.", "The rate that comes closest, so that the user can see how far short the annulus geometry falls.", "An error, which stops the calculation and requires the target to be lowered before it can proceed."]'::jsonb, 0, 'That is a real outcome and returning null is more honest than returning a rate that does not achieve the target.'),
  ('hydraulics', 'intermediate', 'final', null, 16, 'Which of the three constraints on flow rate cannot be bought your way out of?', '["The pump.", "The cleaning, since no equipment change raises the transport ratio at a fixed rate and mud.", "The formation, because you cannot buy a higher fracture gradient.", "All three can be bought: a bigger pump, a thicker mud and a larger hole solve them respectively."]'::jsonb, 2, 'A thicker mud does improve the cleaning, and a larger hole makes it worse. The rock is the one with no equipment answer.'),
  ('hydraulics', 'intermediate', 'final', null, 17, 'You are handed a recommended rate on its own. What is missing from it?', '["The rate alone is enough.", "The rate, the mud weight and the rate of penetration, which are the three inputs the cleaning calculation needs.", "The minimum, the recommended and the maximum, so a reader can see the room available either side.", "The transport ratio, the pump pressure and the equivalent circulating density."]'::jsonb, 3, 'One of the three on its own has not made a decision, and the trade is between the second and the third.'),
  ('hydraulics', 'intermediate', 'final', null, 18, 'The pump pressure more than doubles while the ECD rises three percent. What causes that asymmetry?', '["The bit''s square law alone.", "The two exponents: about 1.72 for the pipe and about 0.75 for the annulus.", "The mud''s shear thinning, which lowers the annulus loss and raises the pipe loss as the rate increases.", "The hydrostatic head, which is the largest term in the ECD and does not change with flow rate."]'::jsonb, 1, 'The hydrostatic head does dominate the ECD and that is a separate reason the percentage is small. The exponents drive the pump.'),
  ('hydraulics', 'intermediate', 'final', null, 19, 'Which lever relieves the pump constraint without touching the other two?', '["A thinner mud.", "A lower flow rate, which reduces the pump pressure faster than it reduces the equivalent circulating density.", "Larger nozzles.", "A shallower bit depth, which shortens both the pipe and the annulus and reduces all three losses together."]'::jsonb, 2, 'A thinner mud lowers the pump pressure and the ECD and worsens the cleaning, so it touches all three.'),
  ('hydraulics', 'intermediate', 'final', null, 20, 'A bigger total flow area relieves the pump. What is paid for that?', '["Jet velocity and hydraulic power at the bit both fall.", "The equivalent circulating density rises.", "The hole cleaning worsens, since a slower jet fails to clear cuttings from under the bit and they are recut.", "Nothing, which is why it is always the first lever to try when the pump is the constraint."]'::jsonb, 0, 'Recutting is a real consequence of the lower jet velocity and it is a bottom-hole effect rather than an annular one.'),
  ('hydraulics', 'intermediate', 'final', null, 21, 'What is the correct order of decisions: nozzles or flow rate?', '["Nozzles first, then the rate.", "They are independent and can be decided in either order, since the nozzle does not affect the annulus at all.", "Both at once, by solving for the pair that maximises hydraulic power at the bit subject to the pump''s limit.", "Flow rate first, from the annulus, then nozzles to make it achievable."]'::jsonb, 3, 'Choosing nozzles first is how a bit hydraulics optimisation produces a well that cannot be cleaned.'),
  ('hydraulics', 'intermediate', 'final', null, 22, 'How many values does the oracle comparison check, and what is the worst disagreement?', '["Eighteen, at about one percent.", "Over a hundred, and better than one part in a million everywhere.", "Four, one per case, and they agree at machine precision because the calculation is deterministic arithmetic.", "Over a hundred, and the worst is about seven percent on the horizontal well''s transport ratio."]'::jsonb, 1, 'Surge and swab agree at about 1e-16, rheology at about 1e-10, and the pump pressures at about 1e-7.'),
  ('hydraulics', 'intermediate', 'final', null, 23, 'Why does the pump pressure carry the largest residual in the comparison?', '["It is computed differently in the two codes.", "It includes the surface loss, which one implementation sets to zero and the other omits from its output entirely.", "It is the longest chain of arithmetic in the calculation.", "It depends on the blend width, and the two implementations use slightly different transition bands."]'::jsonb, 2, 'Both use the same 800-wide band by specification. The residual is a function of the calculation''s length rather than of any choice.'),
  ('hydraulics', 'intermediate', 'final', null, 24, 'What would a disagreement at 1e-3 have meant that this result does not?', '["That one of the two had a defect, or that they had read the specification differently.", "That the physics was wrong.", "That the discretisation was too coarse in one of them, which a finer element list would fix.", "That the goldens were generated on a different fixture set from the one the engine is being run on."]'::jsonb, 0, 'There is no discretisation to refine. A gap that size would be a code difference or a specification reading.'),
  ('hydraulics', 'intermediate', 'final', null, 25, 'How close do field measurements of ECD come to computed values?', '["Within one part in a million.", "Within one percent, which is why a computed ECD can be compared directly against a fracture gradient.", "They do not correlate at all, since the model omits cuttings, eccentricity, rotation and temperature.", "Within five to fifteen percent of the circulating uplift."]'::jsonb, 3, 'They correlate well and imprecisely, which is why the differences between cases are more trustworthy than the absolute values.'),
  ('hydraulics', 'intermediate', 'final', null, 26, 'Which omissions raise the real ECD and which lower it?', '["All of them raise it.", "Cuttings raise it; eccentricity and temperature lower it; rotation does either.", "Cuttings and rotation raise it, and eccentricity and temperature lower it, so the four cancel to within a percent.", "All of them lower it, which is why the concentric non-rotating calculation is always conservative."]'::jsonb, 1, 'Because they do not all point one way, the field comparisons land within tens of percent rather than being wrong by a factor.'),
  ('hydraulics', 'intermediate', 'final', null, 27, 'What is the honest way to use a computed ECD near a fracture gradient?', '["Use it to two decimal places.", "Add ten percent to it as a safety factor, which covers the omissions and makes the comparison direct.", "Treat a margin smaller than the model''s own uncertainty as no margin at all.", "Compare only the differences between cases, since the absolute value is not meaningful at all."]'::jsonb, 2, 'The differences ARE more trustworthy, and refusing to use the absolute value at all would make the model useless.'),
  ('hydraulics', 'intermediate', 'final', null, 28, 'A circulating density is handed over with no caveats. Which four are owed?', '["It excludes cuttings, assumes concentric geometry, assumes no rotation, and uses surface-temperature rheology.", "The flow rate and the depth.", "The method specification, the software, the date and the engineer, which is what a fitted parameter needs.", "The mud weight, the pore pressure, the fracture pressure and the flow rate it was computed at."]'::jsonb, 0, 'They are the difference between a number and a number somebody who was not in the room can use.'),
  ('hydraulics', 'intermediate', 'final', null, 29, 'A well''s ECD uplift is 58 kg/m3 and its window is 60 kg/m3 wide. What is the finding?', '["There is comfortable margin.", "The mud weight should be lowered by 58 kg/m3 so that the ECD sits at the middle of the window.", "The flow rate should be doubled, since the ECD''s exponent is below one and the uplift would rise by less than double.", "Circulating at all takes the well essentially to the fracture gradient."]'::jsonb, 3, 'Lowering the mud weight by that much would take the static weight below the pore pressure. This is a narrow-margin well.'),
  ('hydraulics', 'intermediate', 'final', null, 30, 'What does a pressure-while-drilling tool measure that this course computes?', '["The pump pressure at the standpipe.", "The cuttings concentration in the annulus, from the density difference between the mud going in and coming out.", "The annulus pressure downhole, which is the equivalent circulating density directly.", "The transport ratio, by timing how long cuttings take to reach surface after a marker is added."]'::jsonb, 2, 'It converts the model from a prediction into an interpolation between measurements, which is a much stronger position.'),
  ('hydraulics', 'intermediate', 'final', null, 31, 'Why does a bed in an inclined hole not clear itself as flow rate rises?', '["Because the flow rate has no effect.", "Because the bed reduces the flow area, which raises the velocity over it until scour balances arrival.", "Because the cuttings on the low side are shielded from the flow by the pipe lying on top of them.", "Because a bed is denser than the mud and cannot be lifted without a density change in the fluid."]'::jsonb, 1, 'It reaches an equilibrium thickness rather than disappearing, and raising the rate lowers that equilibrium rather than removing it.'),
  ('hydraulics', 'intermediate', 'final', null, 32, 'What does the model''s cuttings feed rate depend on?', '["The rate of penetration and the bit''s cross-sectional area.", "The flow rate.", "The transport ratio, since the cuttings that fail to reach surface return to the bottom and are recut.", "The mud''s density, since the buoyancy determines how much of the cut rock is actually carried away."]'::jsonb, 0, 'At the engine''s default of 0.005 m/s it is about 0.18 litres per second against 25 of mud, which is under one percent by volume.'),
  ('hydraulics', 'intermediate', 'final', null, 33, 'One number says how well the annulus works. What is the other half?', '["The velocity and the slip.", "The equivalent circulating density and the pump pressure, which between them describe the whole circulating system.", "The Reynolds number and the apparent viscosity, which determine the flow regime in every annulus section.", "The transport ratio and the cuttings concentration."]'::jsonb, 3, 'One says how well the annulus is working and the other says how much is in it. The concentration is what predicts a pack-off.'),
  ('hydraulics', 'intermediate', 'final', null, 34, 'A colleague reports a hole is clean because the transport ratio is 0.9. What is missing?', '["Nothing, that is a good ratio.", "The inclination, since a transport ratio above 0.9 is achievable in a vertical hole and never in a horizontal one.", "The concentration, which depends on the rate of penetration as well.", "The flow rate, since a transport ratio without the rate it was computed at cannot be reproduced."]'::jsonb, 2, 'A hole can have a good ratio and be full of cuttings if the bit is making them fast enough.'),
  ('hydraulics', 'intermediate', 'final', null, 35, 'What happens to the annulus share of the pump pressure as the rate rises?', '["It rises.", "It falls, because its exponent is the gentlest of the three.", "It stays constant, since all three losses are proportional to the flow rate through the same friction factor.", "It rises to a peak around 0.025 m3/s and then falls once the annulus becomes turbulent."]'::jsonb, 1, 'From about a fifth at 0.015 m3/s to under a tenth at 0.035, even though its value is rising throughout.'),
  ('hydraulics', 'intermediate', 'final', null, 36, 'Which of the seven specification points is a pure convention with no physics in it?', '["The blend width of 800 Reynolds numbers.", "The 16 over Re laminar pipe factor.", "The Schiller-Naumann drag correlation, which is a fit to experiment and therefore has no theoretical basis.", "The generalised Reynolds number, which is derived from the definition of the local power law."]'::jsonb, 0, 'A correlation is a fit with a stated range. A convention is a choice, and the blend width is the clearest example.'),
  ('hydraulics', 'intermediate', 'final', null, 37, 'A convention with no physics in it sits where the annulus runs. Why does that bite?', '["Because it changes the pipe loss most.", "Because a wider band would slow the calculation, since both friction factors have to be computed in it.", "Because the goldens'' tolerance cannot be met unless both implementations use exactly the same width.", "Because the annulus often sits inside the transition band, and the annulus sets the ECD."]'::jsonb, 3, 'So the part of the calculation with the most modelling convention in it produces the number the formation feels.'),
  ('hydraulics', 'intermediate', 'final', null, 38, 'What is the free arithmetic check on a hole cleaning run?', '["The concentration equals the feed rate.", "The transport ratio times the annular velocity should equal the slip velocity in every interval.", "The transport ratio and the concentration should move in opposite directions with flow rate.", "The worst transport ratio should be in the same interval as the worst annular velocity, always."]'::jsonb, 2, 'The last is true on these fixtures and is not general, because the slip velocity also varies between intervals.'),
  ('hydraulics', 'intermediate', 'final', null, 39, 'Which mud property is a hole cleaning decision as well as a pressure one?', '["The density alone.", "The rheology, because it changes the slip velocity and the annulus loss together.", "The gel strength, which holds cuttings up during a connection and is the property this model computes.", "The filtration rate, which controls the filter cake and therefore the effective hole diameter."]'::jsonb, 1, 'The gel strength is a real hole cleaning property and it is not in this model. The density also affects both, through buoyancy.'),
  ('hydraulics', 'intermediate', 'final', null, 40, 'Where does the equivalent circulating density profile start, and why?', '["At the mud weight at surface, because there is no annulus above surface.", "At the fracture gradient.", "At the pump pressure converted to a density, since that is the pressure the system is operating at.", "At the bottom hole pressure, and it falls upward as the friction contribution is subtracted."]'::jsonb, 0, 'It grows downward as the friction accumulates, which is why its maximum is usually at total depth.'),
  ('hydraulics', 'intermediate', 'final', null, 41, 'What does this tier certify?', '["Computing a pump pressure.", "Designing a flow rate that satisfies the cleaning, the pump and the formation simultaneously on any well.", "Predicting whether a hole will pack off, from the cuttings concentration and the transport ratio together.", "Saying what the rock feels while circulating and how well the annulus is carrying."]'::jsonb, 3, 'Designing the flow rate is the application. Predicting a pack-off needs a mechanism the model does not have.'),
  ('hydraulics', 'intermediate', 'final', null, 42, 'A well''s cuttings concentration reaches four percent. What are the two consequences?', '["The transport ratio falls below 0.5.", "The pump pressure rises, since the denser annulus needs more pressure to push it and the pump supplies it.", "The annulus''s bulk density is noticeably up, and the risk of bridging around the assembly grows.", "The rate of penetration falls, because the cuttings are recut before they can leave the bottom of the hole."]'::jsonb, 2, 'The pump pressure does rise slightly, through the annulus term. The bridging risk is what makes four percent a threshold rather than a number.');
