-- ============================================================================
-- DC23 - ReservoirCalc Pro EXPERT (advanced tier) goes deep.
--
-- Flips (reservoircalc, advanced) onto the DC1 deep path by inserting its ACTIVE
-- academy_course_structures row, generated from the repo manifest
-- src/content/courses/reservoircalc/advanced/manifest.json (emitted by a
-- generator, not hand-typed), and seeding the six module quiz banks plus the
-- final exam. Answer keys live only here and in the table.
--
-- COMPLETES THE RESERVOIRCALC PRO LADDER at all three tiers, the sixth app to
-- finish after petrophysics, welldata, wellcorrelation, seismolord and mapping.
--
-- Every numeric item traces to the reservoircalc teaching oracle and reproduces
-- the live NG7 Expert capstone answer key: the constant porosity is replaced by a
-- grid populated from the six well values with the population engine and the
-- volumetrics rerun at the 1560 m contact, giving trend porosity at prospect P-1
-- 0.20714187889686578, mean over the oil nodes 0.20936760570720417, pore volume
-- 3.7558468705687864e6 m3, HCPV 2.4413004882563025e6 m3, STOIIP 12.79607650919541
-- MMstb and an uplift of 0.656868401698647 MMstb over the constant booking. The
-- same pipeline src/lib/reservoircalcTeaching.js drives and propertyLab.test.js
-- pins.
--
-- Tier note: the Associate tier (DC9) owns the chain and forward-quoted this
-- tier's headline; the Professional tier (DC22) owns the partition, which this
-- tier deliberately sets aside so that the property model is the only change.
-- This tier owns what is inside the headline. populate('trend') is a LEAST
-- SQUARES PLANE (0.24107144716926077 - 2.043684820796242e-5 x - 7.691319622844493e-7
-- y), so it honours NO well: it misses four of the six by more than 8 pct of the
-- measured value, worst 0.019309143835140874 at Ekene-3, and the residuals sum to
-- zero because the model carries an intercept. Three defensible means exist and
-- differ: the arithmetic well mean 0.20666666666666667, the node mean over the 169
-- oil cells 0.20936760570720417 (graded), and the volume weighted mean
-- 0.21082226429530276 which is pore over net and the only one the booking can use.
-- The geometry is untouched (169 cells, 22.26903564453125e6 m3 gross and
-- 17.81522878109259e6 m3 net are identical to the constant run) and the chain
-- diverges only at the pore step, so the whole model delivers one ratio,
-- 1.0541113057690301. THE DECOMPOSITION is the centrepiece: booking at the
-- arithmetic well mean gives 12.543847985822008 MMstb, so 0.404639878325245 of the
-- headline uplift is only a better constant and just 0.252228523373402 is spatial.
-- The sign is positive because the modelled porosity correlates with oil column at
-- +0.46242377439477966 over the oil cells.
--
-- Bank standard: measured on the length RANK of the correct option and checked for
-- cyclic key sequences, answer-index skew and within-pool near-duplicates before
-- seeding. Across the 132 questions the correct option is longest in 23 pct and
-- shortest in 24 pct.
--
-- Enrollment grandfathering: enforced_from defaults to now() on first insert; the
-- ON CONFLICT update deliberately leaves enforced_from unchanged on re-seeds.
--
-- Ladder note: an ADVANCED enrollment needs an unrevoked PROFESSIONAL
-- certification on the SAME app, so the dry-run probes back-stop a reservoircalc
-- professional cert in-transaction, and probes confirm BOTH tiers below
-- (reservoircalc beginner and reservoircalc intermediate) are left undisturbed at
-- 132 questions each.
--
-- NO DDL. Data only.
-- ============================================================================

insert into public.academy_course_structures
    (app_slug, tier, structure, content_version)
values ('reservoircalc', 'advanced', '{"modules":[{"key":"m01-from-a-constant-to-a-grid","title":"From a Constant to a Grid","lesson_keys":["l01-what-this-tier-adds","l02-the-engine-was-always-ready","l03-the-six-well-porosities","l04-the-property-panel-map"]},{"key":"m02-the-trend-plane","title":"The Trend Plane","lesson_keys":["l01-three-ways-to-fill-a-grid","l02-what-a-least-squares-plane-is","l03-the-ekene-plane","l04-the-model-honours-no-well","l05-outside-the-wells"]},{"key":"m03-three-means","title":"Three Means","lesson_keys":["l01-an-average-is-no-longer-one-number","l02-the-arithmetic-well-mean","l03-the-node-mean-over-the-oil","l04-the-volume-weighted-mean","l05-which-mean-belongs-in-the-booking"]},{"key":"m04-what-the-model-buys","title":"What the Property Model Buys","lesson_keys":["l01-the-chain-diverges-at-the-pore-step","l02-the-uplift-is-one-ratio","l03-the-decomposition","l04-why-the-sign-is-positive","l05-the-number-in-proportion"]},{"key":"m05-the-limits-of-a-property-model","title":"The Limits of a Property Model","lesson_keys":["l01-two-properties-still-constant","l02-a-plane-is-a-strong-assumption","l03-a-method-that-honours-the-data","l04-the-well-the-map-could-not-report","l05-invented-detail"]},{"key":"m06-the-property-workflow","title":"The Property Workflow","lesson_keys":["l01-the-workflow-end-to-end","l02-quality-control","l03-the-capstone-walkthrough","l04-the-top-of-the-ladder"]}]}'::jsonb, 1)
on conflict (app_slug, tier) do update
  set structure = excluded.structure,
      content_version = excluded.content_version,
      active = true,
      updated_at = now();

delete from public.academy_quiz_questions
 where app_slug = 'reservoircalc' and tier = 'advanced';

insert into public.academy_quiz_questions
    (app_slug, tier, scope, module_key, ord, prompt, options, answer_index, explanation)
values
  ('reservoircalc', 'advanced', 'module', 'm01-from-a-constant-to-a-grid', 1, 'What single input changes between the Associate tier and the Expert tier at Ekene?', '["The porosity, which becomes a grid holding one value per node.", "The contact, which is now established separately for each compartment of the field.", "The gridding method, which is replaced by one that honours the well control exactly.", "The four properties, all of which are replaced by values fitted to the six wells."]'::jsonb, 0, 'Net to gross, water saturation and the formation volume factor remain constants, and the fault from the tier below is set aside so that the property model is the only thing that has changed.'),
  ('reservoircalc', 'advanced', 'module', 'm01-from-a-constant-to-a-grid', 2, 'Why does the volume engine need no modification to accept a porosity grid?', '["Because it rescales any scalar property into a grid before summing.", "Because it was always summing node by node and always receiving arrays.", "Because a grid and a constant give identical results for the pore volume.", "Because the property grids are converted to a single effective value first."]'::jsonb, 1, 'The Associate tier filled those arrays with the same value at every node, which is why the chain collapsed into four multiplications on the total.'),
  ('reservoircalc', 'advanced', 'module', 'm01-from-a-constant-to-a-grid', 3, 'Why does the volumetric chain stop factorising when porosity varies?', '["Because the engine switches to a different accumulation order for grids.", "Because the cell area can no longer be taken outside the summation.", "Because the sum of products is not the product of the sums unless the property is constant.", "Because the oil column and the porosity are then correlated with each other."]'::jsonb, 2, 'Pulling a constant out of a sum leaves the sum unchanged; pulling a varying quantity out changes the arithmetic. That is the whole reason three different means exist at this tier.'),
  ('reservoircalc', 'advanced', 'module', 'm01-from-a-constant-to-a-grid', 4, 'What are the six Ekene well porosities?', '["0.22, 0.19, 0.23, 0.17, 0.21 and 0.22, averaging 0.206667.", "0.20 at every well, which is the constant the tiers below were handed.", "0.22, 0.19, 0.23, 0.17, 0.21 and 0.22, averaging 0.210822 by volume.", "0.17 through 0.23 in even steps, averaging 0.20 exactly."]'::jsonb, 0, 'Their range of 0.06 is 29 percent of the mean, which is what a constant of 0.20 was averaging away. The volume weighted figure of 0.210822 is a property of the model rather than of the data.'),
  ('reservoircalc', 'advanced', 'module', 'm01-from-a-constant-to-a-grid', 5, 'Why is a well porosity not a measurement in the sense that a depth pick is?', '["Because it is read from a log rather than from a core sample.", "Because it is a petrophysical result averaged over the reservoir interval.", "Because it is quoted to two decimals rather than to the nearest metre.", "Because it changes with the fluid in the pore space at the time of logging."]'::jsonb, 1, 'It is a log response converted through a mineral model, then averaged over 25 to 36 m of reservoir and screened by a cutoff, so the variation within a well is discarded before the property model sees it.'),
  ('reservoircalc', 'advanced', 'module', 'm01-from-a-constant-to-a-grid', 6, 'What spatial pattern do the six Ekene porosities show?', '["Porosity is highest at the crest and falls in every direction from it.", "Porosity falls toward the north, with no eastward pattern.", "Porosity falls toward the east, with no clear northward pattern.", "No pattern at all, which is why a constant is used at the tiers below."]'::jsonb, 2, 'The three highest values sit at eastings of 1000, 1400 and 1900 m and the two lowest at 2200 and 2600 m. Against northing, the highest and lowest values sit within 200 m of each other.'),
  ('reservoircalc', 'advanced', 'module', 'm01-from-a-constant-to-a-grid', 7, 'How strong is the evidence for the eastward porosity trend at Ekene?', '["Strong, since five of the six wells fall on the fitted line.", "Weak, since two of the six wells are dry and cannot supply porosity.", "Strong, since the trend is confirmed by the structural dip direction.", "Weak, since it rests largely on Ekene-4 being both furthest east and lowest."]'::jsonb, 3, 'Two of the six values could be swapped by their own measurement uncertainty. All six wells supply porosity, including the two that are dry at the capstone contact.'),
  ('reservoircalc', 'advanced', 'module', 'm01-from-a-constant-to-a-grid', 8, 'How much would the field booking change if a single well were the only porosity control and it read 0.17 rather than 0.23?', '["By about 3.64 MMstb, or 30 percent of the field.", "By about 0.66 MMstb, which is what the property model is worth.", "By about 0.25 MMstb, which is the spatial part of the model.", "By nothing, since one well cannot support a property model at all."]'::jsonb, 0, 'Booking at 0.17 gives 10.318 MMstb and at 0.23 gives 13.960. Fitting a model to six values is worth about a fifth of what knowing the values at all is worth.'),
  ('reservoircalc', 'advanced', 'module', 'm01-from-a-constant-to-a-grid', 9, 'Which control does the property explorer offer?', '["The population method and the oil water contact.", "The population method, and nothing else.", "The population method and the variogram range used for kriging.", "The population method and the choice of which wells to include."]'::jsonb, 1, 'The contact stays at 1560 m, the other properties stay constant, and the fault from the tier below is not present, so the method is the only variable.'),
  ('reservoircalc', 'advanced', 'module', 'm01-from-a-constant-to-a-grid', 10, 'What do the two lines beneath each well post on the property panel show?', '["The well''s top pick and the modelled porosity at that depth.", "The well''s measured porosity and its net to gross.", "The well''s measured porosity and the porosity the model gives at that location.", "The measured porosity and the porosity averaged over the surrounding cells."]'::jsonb, 2, 'A green ring means the model reproduces the measurement to within a millionth and a red ring means it does not. Under trend every ring is red.'),
  ('reservoircalc', 'advanced', 'module', 'm01-from-a-constant-to-a-grid', 11, 'Which three chain tiles do not move when the population method is changed?', '["The cell count, gross rock volume and pore volume.", "The gross rock volume, the net volume and the pore volume.", "The cell count, the gross rock volume and the pore volume.", "The cell count, the gross rock volume and the net volume."]'::jsonb, 3, 'Porosity enters the chain after the net volume is formed, so no porosity model can reach any of those three. Seeing that hold across three very different models is the fastest way to learn where porosity enters.'),
  ('reservoircalc', 'advanced', 'module', 'm01-from-a-constant-to-a-grid', 12, 'Under the constant method, how many well rings on the panel are green?', '["None, since the constant disagrees with every individual well.", "All six, since the constant is the average of the six values.", "Four, since two of the six wells are dry at the contact.", "One, at whichever well happens to measure 0.206667."]'::jsonb, 0, 'Even the simplest possible model already disagrees with every well, and nobody finds that surprising. The trend model also disagrees with every well, which people do find surprising.'),
  ('reservoircalc', 'advanced', 'module', 'm01-from-a-constant-to-a-grid', 13, 'The trend booking is 12.796077 MMstb and the constant 0.20 booking is 12.139208. What effective porosity does the trend model imply?', '["0.206667, the arithmetic mean of the six well values.", "0.210822, since the chain is linear in porosity.", "0.209368, the mean of the model over the oil bearing cells.", "0.219745, which is what the kriged model gives."]'::jsonb, 1, 'The ratio of the bookings is 1.05411 and 0.20 times that is 0.210822. The whole property model, over all 169 cells, is equivalent to booking with that single value.'),
  ('reservoircalc', 'advanced', 'module', 'm01-from-a-constant-to-a-grid', 14, 'Which of the three claims this tier examines is true?', '["A model fitted to the well porosities reproduces them at the wells.", "The uplift measures the value of spatial modelling.", "None of them. All three are wrong in ways this tier measures.", "Once porosity varies, its average is still a single number you can quote."]'::jsonb, 2, 'The trend misses five of six wells, most of the uplift is not spatial, and there are three defensible averages of the same modelled porosity.'),
  ('reservoircalc', 'advanced', 'module', 'm01-from-a-constant-to-a-grid', 15, 'Why does this tier drop the fault from the tier below?', '["Because a property model cannot be applied to a partitioned field.", "Because the capstone books the field before the partition is applied.", "Because the fault would change the effective porosity of each block.", "So that the property model is the only thing that changes."]'::jsonb, 3, 'Partitioning and property modelling are independent, and combining them would confuse both. The engine would accept labels and a property grid together without difficulty.'),
  ('reservoircalc', 'advanced', 'module', 'm02-the-trend-plane', 1, 'What does the constant population method compute?', '["The weighted mean of the control values, written at every node.", "The value measured at the nearest well, written at every node.", "The midpoint of the range of the control values across the field.", "The value that reproduces the booking of the tier below exactly."]'::jsonb, 0, 'With equal weights that is the arithmetic mean, 0.206667 at Ekene. It promises nothing about spatial variation, which is the right promise when the wells show no pattern you believe.'),
  ('reservoircalc', 'advanced', 'module', 'm02-the-trend-plane', 2, 'What claim does a trend model make about the geology?', '["That the property is spatially correlated over a range you can estimate.", "That the property varies smoothly, in one direction, at a constant rate.", "That the property is best represented by its arithmetic mean everywhere.", "That the property returns to its measured value near each control point."]'::jsonb, 1, 'That is a strong claim and it is the thing to examine before using the method. It is right when there is a genuine regional gradient and the control is too sparse for anything more detailed.'),
  ('reservoircalc', 'advanced', 'module', 'm02-the-trend-plane', 3, 'What does the trend method not promise?', '["That the property varies at a constant rate across the field.", "That the modelled values stay within the range of the data.", "That the model reproduces the well values at the wells.", "That every well influences the value at every node."]'::jsonb, 2, 'A plane through six points that are not coplanar cannot pass through all of them, so it passes near them. That is the point most often missed.'),
  ('reservoircalc', 'advanced', 'module', 'm02-the-trend-plane', 4, 'Why is six wells not enough to justify kriging at Ekene?', '["Because six points cannot support a fitted variogram, so it has to be supplied by hand.", "Because kriging needs at least eight points before its system can be solved.", "Because kriging cannot honour data at locations that fall between grid nodes.", "Because the wells are too widely spaced for any correlation range to apply."]'::jsonb, 0, 'The kriged map''s structure then comes from a range and a model somebody chose, so it is an illustration of a method rather than a defensible model of this field.'),
  ('reservoircalc', 'advanced', 'module', 'm02-the-trend-plane', 5, 'What does the engine''s fallback ladder do when the requested method cannot run?', '["It raises an error and stops, since a silent fallback would be misleading.", "It falls back to the next simplest method and records that it did so.", "It falls back to a constant and reports the result as if the method had run.", "It retries with a wider search radius until the method succeeds."]'::jsonb, 1, 'Ask for kriging and it will fall back to a trend and then to a constant. A model that quietly degraded and produced a number anyway is the kind of thing discovered years later.'),
  ('reservoircalc', 'advanced', 'module', 'm02-the-trend-plane', 6, 'How many non collinear wells does a trend fit need at minimum?', '["Six, which is why Ekene can support one.", "Four, since a plane has three parameters plus an intercept.", "Three, since three non collinear points determine a plane.", "Two, since a plane is fitted independently in each map direction."]'::jsonb, 2, 'Three points on a line do not determine a plane, which is why the engine''s trend method throws on a degenerate configuration and falls back to a constant.'),
  ('reservoircalc', 'advanced', 'module', 'm02-the-trend-plane', 7, 'What is the algebraic form of the trend model?', '["A minimum bending surface through the control values.", "A quadratic surface fitted to the control values.", "A distance weighted average of the control values.", "A plane, v equals a plus b times x plus c times y."]'::jsonb, 3, 'There is no curvature, no local detail, and no way for one well to influence its own neighbourhood more than the field as a whole.'),
  ('reservoircalc', 'advanced', 'module', 'm02-the-trend-plane', 8, 'Why do the residuals of a least squares plane sum to zero?', '["Because the model has an intercept.", "Because the method minimises their sum rather than their squares.", "Because the residuals are computed after the model is normalised.", "Because positive and negative measurement errors cancel in any large sample."]'::jsonb, 0, 'The plane is unbiased over the wells as a set, and can still be wrong at every individual well. Being right on average is not being right anywhere.'),
  ('reservoircalc', 'advanced', 'module', 'm02-the-trend-plane', 9, 'What are the coefficients of the Ekene porosity plane?', '["An intercept of 0.206667 with gradients of 0.020437 and 0.000769 per km.", "An intercept of 0.241071 with gradients of 0.020437 and 0.000769 per km.", "An intercept of 0.210822 with a single gradient of 0.020451 per km eastward.", "An intercept of 0.20 with gradients fitted separately in each block."]'::jsonb, 1, 'Porosity falls by 0.020437 per kilometre eastward and 0.000769 per kilometre northward. The intercept is a fitting parameter at the frame origin rather than a prediction anywhere.'),
  ('reservoircalc', 'advanced', 'module', 'm02-the-trend-plane', 10, 'What does the Ekene plane say in a sentence a geologist could argue with?', '["That porosity is highest at the crest and falls down the flanks.", "That porosity improves northward at about two porosity units per kilometre.", "That porosity improves westward at about two porosity units per kilometre.", "That porosity is best described by a single value of 0.206667."]'::jsonb, 2, 'The eastward gradient is 26.6 times the northward one, so the trend is essentially east to west, about 2.2 degrees south of due west.'),
  ('reservoircalc', 'advanced', 'module', 'm02-the-trend-plane', 11, 'Why is the absence of a northward gradient the weaker half of the Ekene fit?', '["Because the frame is shorter north to south than east to west.", "Because the northward gradient was fixed at zero before fitting.", "Because only four of the six wells have a distinct northing.", "Because the extreme values sit at nearly the same northing."]'::jsonb, 3, 'Ekene-3 at 0.23 sits at a northing of 2300 m and Ekene-4 at 0.17 at 2500 m, so the data has almost no ability to see a north to south trend.'),
  ('reservoircalc', 'advanced', 'module', 'm02-the-trend-plane', 12, 'Which Ekene well does the trend plane miss by the most?', '["Ekene-3, by 0.019309.", "Ekene-1, by 0.000135, since it sits nearest the data centroid.", "Ekene-4, by 0.016013, since it is furthest from the other wells.", "Ekene-2, by 0.005226, since it lies off a grid row."]'::jsonb, 0, 'Ekene-6 is next at 0.019143. Four of the six wells are missed by more than 8 percent, and only Ekene-1 is close, by accident of sitting near the centroid.'),
  ('reservoircalc', 'advanced', 'module', 'm02-the-trend-plane', 13, 'Which argument for the residuals being acceptable is the strongest?', '["That a plane cannot pass through six points that are not coplanar.", "That a trend declines to explain detail below the resolution of six wells.", "That they are comparable in size to the uncertainty on the well porosities.", "That their mean is zero, so the model is unbiased over the well set."]'::jsonb, 1, 'If you accept the model''s claim, the residuals are exactly what it says they should be. The mechanical argument is weakest, since it justifies any misfit at all, and a zero mean is guaranteed by the method.'),
  ('reservoircalc', 'advanced', 'module', 'm02-the-trend-plane', 14, 'Which residual pattern would tell you a trend model is the wrong shape?', '["Residuals that alternate in sign and are similar in size.", "Residuals that sum to zero across the whole well set.", "Residuals that are large and one sided across a group of neighbouring wells.", "Residuals that are smallest at the well nearest the centroid."]'::jsonb, 2, 'That means there is structure the plane cannot express. At Ekene the residuals alternate in sign and the largest is only 1.2 times the next, which is what a fair fit of a modest model looks like.'),
  ('reservoircalc', 'advanced', 'module', 'm02-the-trend-plane', 15, 'Over the 169 oil bearing cells, what range of porosity does the plane use?', '["0.206667 to 0.210822, between the arithmetic and volume weighted means.", "0.17 to 0.23, matching the range of the measured values exactly.", "0.181772 to 0.232281, which is its range over the whole frame.", "0.194649 to 0.227348, never near the 0.17 at Ekene-4."]'::jsonb, 3, 'The worst rock in the field sits where there is no oil, so the bottom of the distribution is absent from the population the booking averages.'),
  ('reservoircalc', 'advanced', 'module', 'm03-three-means', 1, 'Why does the word average stop picking out one quantity once porosity varies?', '["Because each candidate averages a different population.", "Because the engine computes several averages internally and reports the largest.", "Because the modelled values are not normally distributed across the field.", "Because porosity is a ratio, and ratios cannot be averaged arithmetically."]'::jsonb, 0, 'At Ekene the three candidates differ by 2.01 percent of each other, which is comparable to what the whole property model is worth.'),
  ('reservoircalc', 'advanced', 'module', 'm03-three-means', 2, 'What are the three means at Ekene under the trend model?', '["0.20, 0.206667 and 0.210822, in increasing order.", "0.206667, 0.209368 and 0.210822.", "0.206667, 0.210822 and 0.219745, in increasing order.", "0.209368, 0.210822 and 0.219745, in increasing order."]'::jsonb, 1, 'They are the arithmetic mean of the wells, the plain mean of the model over the 169 oil cells, and the mean weighted by the rock each cell carries.'),
  ('reservoircalc', 'advanced', 'module', 'm03-three-means', 3, 'What does the arithmetic mean of the six wells estimate?', '["The porosity the booking would use if the property model were correct.", "The porosity of the field, weighted by the area each well represents.", "The porosity of the rock at the six places somebody drilled.", "The porosity of the oil bearing part of the field."]'::jsonb, 2, 'It is the right answer to a specific question: pick one of these six wells at random and what porosity should you expect. Whether it estimates anything about the field depends on whether the wells are representative.'),
  ('reservoircalc', 'advanced', 'module', 'm03-three-means', 4, 'Why are well locations not a random sample of a field?', '["Because wells are drilled where oil is expected, which usually means better rock.", "Because wells are drilled on a regular grid that is laid out before the field is mapped.", "Because appraisal wells are placed to test the edges rather than the crest.", "Because the number of wells is always too small for a sample to be random."]'::jsonb, 0, 'Appraisal drilling then pulls the other way. At Ekene the well set over samples the good rock relative to the field area and under samples it relative to the oil.'),
  ('reservoircalc', 'advanced', 'module', 'm03-three-means', 5, 'What does the step from the well mean to the node mean over the oil measure?', '["That the model disagrees with the measurements at the well locations.", "That the oil bearing cells are not a representative sample of the field.", "That the thicker cells carry better rock than the thin ones.", "That the plane extrapolates beyond the range of the measured values."]'::jsonb, 1, 'The oil sits on the structural high, which at Ekene is where the plane predicts the better rock, so the low end of the distribution is absent from the population being averaged.'),
  ('reservoircalc', 'advanced', 'module', 'm03-three-means', 6, 'Over the oil bearing cells the plane never uses a value below 0.194649. Why?', '["Because the extrapolation limit prevents lower values from being computed.", "Because the extrapolation limit stops lower values being computed.", "Because the 0.17 was measured at a well where there is no oil.", "Because the low values are averaged away."]'::jsonb, 2, 'The worst rock in the field sits in the part that holds no oil. Ekene-4 still influences the booking through the fit, since it changes the coefficients, without any cell of its own contributing.'),
  ('reservoircalc', 'advanced', 'module', 'm03-three-means', 7, 'What is the trap in the node mean over the oil?', '["It is computed from the model rather than from the measurements.", "It excludes the dry live nodes, so it overstates the field average.", "It depends on the contact, so it changes when the contact moves.", "It counts every cell equally, so it is not the average the booking used."]'::jsonb, 3, 'A cell with a 20 m column and one with a 2 m column count the same in it and contribute ten to one in the booking. Multiplying it by the net volume gives the wrong pore volume.'),
  ('reservoircalc', 'advanced', 'module', 'm03-three-means', 8, 'How much does quoting the node mean where the volume weighted mean belongs cost at Ekene?', '["About 0.088 MMstb, understated.", "About 0.657 MMstb, understated.", "About 0.404 MMstb, overstated.", "Nothing, since the two differ only in the fifth decimal."]'::jsonb, 0, 'The two means differ by 0.001455, which against a net volume of 17.815229 million cubic metres is 0.025915 million cubic metres of pore space. The error is small enough to survive any sanity check.'),
  ('reservoircalc', 'advanced', 'module', 'm03-three-means', 9, 'What is the volume weighted mean equal to?', '["The pore volume divided by the gross rock volume.", "The pore volume divided by the net volume.", "The arithmetic mean of the wells weighted by their oil columns.", "The node mean over the oil weighted by the cell area."]'::jsonb, 1, 'At Ekene that division gives 0.210822, and the hand route summing column times porosity over summed column agrees with it to the seventeenth digit.'),
  ('reservoircalc', 'advanced', 'module', 'm03-three-means', 10, 'Why is the oil column the weight in the Ekene effective porosity?', '["Because the engine sorts the cells by column before accumulating them.", "Because thicker cells are closer to the crest, where the model is most reliable.", "Because the weight is whatever the porosity is multiplying at each node.", "Because the contact makes column the only property that varies between cells."]'::jsonb, 2, 'Area and net to gross cancel out of the weighting because they are the same everywhere. If net to gross also varied, the weight would be the product of column and net to gross.'),
  ('reservoircalc', 'advanced', 'module', 'm03-three-means', 11, 'What does the gap between the node mean and the volume weighted mean measure?', '["The share of the oil that lies above the mean column.", "The variance of the modelled porosity over the oil bearing cells.", "The difference between the model and the measurements at the wells.", "The covariance of column and porosity, divided by the mean column."]'::jsonb, 3, 'At Ekene the covariance is 0.019168 and the mean column 13.176944 m, giving 0.001455. If porosity were uncorrelated with column the two means would coincide.'),
  ('reservoircalc', 'advanced', 'module', 'm03-three-means', 12, 'Which mean does the booking actually use, and why is there no choice about it?', '["The volume weighted mean, the only one reproducing the sum of products.", "The node mean, since the engine averages the grid before applying it.", "The arithmetic well mean, since it is the only one grounded in measurement.", "Whichever is quoted in the report, since the chain is linear in porosity."]'::jsonb, 0, 'The question is not which average is best but which is already implied by the arithmetic, and there is only one candidate.'),
  ('reservoircalc', 'advanced', 'module', 'm03-three-means', 13, 'What are the other two means good for, if only one belongs in the booking?', '["The well mean bounds the booking and the node mean gives its uncertainty.", "The well mean is the reference and the node mean separates the two effects.", "Neither is useful once a spatial model has been built.", "Both are needed to compute the volume weighted mean."]'::jsonb, 1, 'At Ekene the selection step is 0.002701 and the weighting step 0.001455, so selection is roughly twice weighting. Reporting all three in order shows a reader where the model''s effect came from.'),
  ('reservoircalc', 'advanced', 'module', 'm03-three-means', 14, 'Under what conditions would the three means come out in the reverse order at Ekene?', '["If the contact were deeper, so that more of the flank held oil.", "If the porosity data were more uncertain than the structural picks.", "If the oil sat on poorer rock and the thick cells carried lower porosity.", "If the property model were kriged rather than fitted as a plane."]'::jsonb, 2, 'That happens in carbonate build ups with tight cemented crestal facies, and where wells were drilled preferentially into the best rock. A reader who has learned that property models increase volumes has generalised from a common case.'),
  ('reservoircalc', 'advanced', 'module', 'm03-three-means', 15, 'Under the constant method, what do the three means read?', '["0.206667 twice, and 0.210822 for the volume weighted mean.", "0.206667, 0.209368 and 0.210822, as under the trend.", "0.20, then 0.206667 twice.", "All three read 0.206667."]'::jsonb, 3, 'Averaging a constant any way you like returns the constant, so there is nothing for the choice of population or the weighting to bite on. That collapse is why the tiers below could speak of the porosity without qualification.'),
  ('reservoircalc', 'advanced', 'module', 'm04-what-the-model-buys', 1, 'Which rows of the chain are identical between a constant booking and a property model booking?', '["Cell count, gross rock volume and net volume.", "Cell count and gross rock volume only, since net to gross is applied per node.", "Pore volume, hydrocarbon pore volume and STOIIP, which all scale together.", "None. A property model changes every row of the chain below the cell count."]'::jsonb, 0, 'Porosity enters the chain after the net volume is formed, so no porosity model can reach any of those. If somebody''s property model changed their gross rock volume, they changed something else too.'),
  ('reservoircalc', 'advanced', 'module', 'm04-what-the-model-buys', 2, 'Why do the pore volume, the hydrocarbon pore volume and the STOIIP all change by the same factor?', '["Because the engine rescales the whole chain once the pore volume is known.", "Because the steps below the pore volume are multiplications by constants.", "Because the oil saturation and the formation volume factor cancel out.", "Because the porosity grid is normalised before it reaches the chain."]'::jsonb, 1, 'Multiplying by constants preserves ratios. At Ekene all three ratios come out at 1.054111.'),
  ('reservoircalc', 'advanced', 'module', 'm04-what-the-model-buys', 3, 'What are the pore volumes under the three population methods at Ekene?', '["3.7558 for all three, since the geometry does not change.", "3.5630, 3.7558 and 3.9148 million cubic metres.", "3.6818, 3.7558 and 3.9148 million cubic metres.", "3.6818, 3.7558 and 3.7558 million cubic metres."]'::jsonb, 2, '3.563046 is the Associate booking at the handed out 0.20, which is not one of the three methods. Three quite different property models give three pore volumes on one geometry.'),
  ('reservoircalc', 'advanced', 'module', 'm04-what-the-model-buys', 4, 'What is the ratio of the trend booking to the constant 0.20 booking?', '["1.054111, which is also the ratio of the effective porosities.", "1.033333, which is the ratio of the well mean to 0.20.", "1.098726, which is what the kriged model gives.", "1.210822, which is the effective porosity itself."]'::jsonb, 0, 'The chain is linear in porosity and nothing else changed, so the ratio of the bookings has to be the ratio of the effective porosities.'),
  ('reservoircalc', 'advanced', 'module', 'm04-what-the-model-buys', 5, 'The STOIIP ratio is 1.0541113058 and the porosity ratio is 1.0541113215. Why do they differ?', '["Because the two are computed over different sets of cells.", "Because the constant is stored as a 32 bit float, so the booking used 0.20000000298.", "Because the effective porosity is rounded before the division.", "Because the trend grid holds values outside the range of the data."]'::jsonb, 1, 'It is a storage artefact fifteen thousand times smaller than a single barrel on this booking, and it is not evidence of anything about the model.'),
  ('reservoircalc', 'advanced', 'module', 'm04-what-the-model-buys', 6, 'What is the fastest available audit of a property model?', '["Check that the effective porosity lies within the range of the property grid.", "Compare the modelled porosity at each well against what the well measured.", "Form each effective porosity as pore over net and compare their ratio to the STOIIP ratio.", "Confirm that the cell count is unchanged from the constant booking."]'::jsonb, 2, 'It needs only four numbers any report should contain. If the two ratios disagree, the runs differ by more than the property model and whatever else changed is not being reported.'),
  ('reservoircalc', 'advanced', 'module', 'm04-what-the-model-buys', 7, 'Which three bookings does the Ekene decomposition use?', '["The trend grid, the kriged grid, and the volume weighted constant.", "The constant 0.20, the trend grid, and the kriged grid.", "The constant 0.206667, the node mean 0.209368, and the trend grid.", "The constant 0.20, the constant 0.206667, and the trend grid."]'::jsonb, 3, 'They give 12.139208, 12.543848 and 12.796077 MMstb, and the two steps sum to the graded uplift of 0.656868.'),
  ('reservoircalc', 'advanced', 'module', 'm04-what-the-model-buys', 8, 'How does the 0.656868 MMstb uplift decompose at Ekene?', '["0.404640 from a better constant and 0.252229 from spatial variation.", "0.252229 from a better constant and 0.404640 from spatial variation.", "0.163936 from selection and 0.492932 from weighting.", "It does not decompose, since the property model acts on every cell at once."]'::jsonb, 0, 'Nearly two thirds of what the property model appears to be worth is the correction of a constant that was too low. Only just over a third comes from the spatial modelling.'),
  ('reservoircalc', 'advanced', 'module', 'm04-what-the-model-buys', 9, 'Why does the decomposition matter more than the total uplift?', '["Because the total is not reproducible without the intermediate bookings.", "Because the two parts carry different confidence and need different work.", "Because only the spatial part is affected by the choice of method.", "Because the better constant part is the one that could have the wrong sign."]'::jsonb, 1, 'The first part rests on six measurements and one division. The second rests on a plane that misses four of six wells by more than 8 percent.'),
  ('reservoircalc', 'advanced', 'module', 'm04-what-the-model-buys', 10, 'Split further, what are the three parts of the Ekene uplift?', '["0.252229 better constant, 0.163936 selection, 0.240703 weighting.", "0.404640 better constant, 0.088293 selection, 0.163936 weighting.", "0.404640 better constant, 0.163936 selection, 0.088293 weighting.", "0.163936 better constant, 0.404640 selection, 0.088293 weighting."]'::jsonb, 2, 'Only the last two are spatial, and the weighting part, which is the one this tier works hardest to explain, is the smallest of the three.'),
  ('reservoircalc', 'advanced', 'module', 'm04-what-the-model-buys', 11, 'What is the correlation between the modelled porosity and the oil column over the 169 oil cells?', '["Minus 0.462, which is why the booking falls.", "Plus 0.925, which is near perfect.", "Zero, since the two are independent properties of the rock.", "Plus 0.462, which is moderate."]'::jsonb, 3, 'The Associate tier predicted the sign in words. This tier measures it, and the moderate value is what a positive but imperfect relationship looks like.'),
  ('reservoircalc', 'advanced', 'module', 'm04-what-the-model-buys', 12, 'Where does the positive correlation at Ekene come from?', '["Two trends pointing the same way, one in porosity and one in structure.", "A genuine physical link between porosity and the height of the oil column.", "The volume weighting, which creates the correlation it then measures.", "The contact, which removes the cells where the correlation would be negative."]'::jsonb, 0, 'The plane says porosity improves westward and the structure puts the crest in the west. Had the porosity trend pointed north, the correlation would be near zero without any change to the porosity data.'),
  ('reservoircalc', 'advanced', 'module', 'm04-what-the-model-buys', 13, 'Under what circumstances does a property model remove barrels relative to a constant?', '["When the property model extrapolates below the range of the measured values.", "When the best rock lies downdip, so the covariance of column and porosity is negative.", "When the wells over sample the poorest rock in the field.", "When the contact is shallow enough that few cells hold oil."]'::jsonb, 1, 'That is the situation in carbonate build ups with tight cemented crestal facies. What property models do is replace an unweighted assumption with a weighted one, and the field sets the direction.'),
  ('reservoircalc', 'advanced', 'module', 'm04-what-the-model-buys', 14, 'How does the Ekene property model compare with the contact sensitivity?', '["It is larger, since the contact was measured and the porosity was not.", "It is roughly the same size, so the two deserve equal attention.", "It is roughly a fifteenth the size: 0.66 MMstb against 8 to 10 MMstb per 10 m.", "They cannot be compared, since one changes the geometry and the other does not."]'::jsonb, 2, 'The contact dominates everything by an order of magnitude, which the Associate tier established and nothing since has challenged.'),
  ('reservoircalc', 'advanced', 'module', 'm04-what-the-model-buys', 15, 'Which is worth more at Ekene: choosing a population method, or using one at all?', '["Neither, since both are smaller than the fault position uncertainty.", "Using one at all, at 0.656868 MMstb against the constant 0.20.", "They are identical, since the constant method is one of the three.", "The choice of method, at 0.793817 MMstb across the three."]'::jsonb, 3, 'Constant books 12.543848, trend 12.796077 and krige 13.337665. A report that says a property model was used without saying which method has left out the larger of the two decisions.'),
  ('reservoircalc', 'advanced', 'module', 'm05-the-limits-of-a-property-model', 1, 'Which properties are still constants after this tier''s property model?', '["Net to gross, water saturation and the formation volume factor.", "Water saturation and the formation volume factor only.", "Net to gross and porosity, since porosity is fitted rather than measured.", "None. All four properties are populated from the well values."]'::jsonb, 0, 'Only the formation volume factor genuinely deserves to be one, since it is a fluid property that is close to uniform within an accumulation in pressure communication.'),
  ('reservoircalc', 'advanced', 'module', 'm05-the-limits-of-a-property-model', 2, 'Which of the constants left standing has the strongest physical reason to vary?', '["Net to gross, which falls away from the depocentre as sands split.", "Water saturation, which falls with height above the free water level.", "The formation volume factor, which varies with pressure and temperature.", "None of them, since all three are already averages over the reservoir."]'::jsonb, 1, 'Capillary equilibrium means saturation falls as buoyancy pressure rises, so a single value of 0.35 is a thickness weighted average of a curve applied uniformly to cells whose columns run from a sliver to 20.28 m.'),
  ('reservoircalc', 'advanced', 'module', 'm05-the-limits-of-a-property-model', 3, 'Which way would a saturation height model move the Ekene booking?', '["It would not move, since the constant already averages the curve.", "Down, since the thin cells near the contact would carry more water.", "Up, since the thick cells would carry higher oil saturation.", "It depends on the porosity model, since the two interact."]'::jsonb, 2, 'The correlation with column would be far stronger than porosity''s plus 0.462, because saturation is a direct function of height above the contact rather than a trend that happens to point the same way.'),
  ('reservoircalc', 'advanced', 'module', 'm05-the-limits-of-a-property-model', 4, 'If net to gross also varied, what would the weight in the effective porosity become?', '["The product of the oil column and the net to gross at each node.", "The oil column alone, since net to gross cancels out of the ratio.", "The pore volume of each cell.", "The net to gross alone, since it is applied before porosity."]'::jsonb, 0, 'The weight is whatever the property multiplies. Area and net to gross cancelled at Ekene only because they are uniform there.'),
  ('reservoircalc', 'advanced', 'module', 'm05-the-limits-of-a-property-model', 5, 'What three things does a plane claim about a property field?', '["Smooth variation, spatial correlation, and a finite range.", "Monotonic variation, in a single direction, at a constant rate.", "Exactness at the wells, smoothness between them, and boundedness.", "A maximum somewhere inside the field, with symmetric fall off."]'::jsonb, 1, 'Depositional systems produce all three sometimes and violate all three often. A channel belt has a maximum along its axis, and compaction driven porosity loss follows the structure.'),
  ('reservoircalc', 'advanced', 'module', 'm05-the-limits-of-a-property-model', 6, 'Why is three parameters on six values weaker evidence than it sounds at Ekene?', '["Because two of the six wells are dry and supply no porosity value.", "Because three of the parameters are fitted and three are assumed.", "Much of the eastward gradient rests on just two of the wells.", "Because the residuals are not independent of one another."]'::jsonb, 2, 'Ekene-2 and Ekene-4 carry the two lowest porosities and sit close together in northing, so the effective information is roughly one poorly constrained gradient plus an intercept.'),
  ('reservoircalc', 'advanced', 'module', 'm05-the-limits-of-a-property-model', 7, 'Why is a more flexible model not automatically safer with sparse control?', '["Because it requires the property values to be independent of position.", "Because it takes longer to compute over a large frame.", "Because it cannot be extrapolated beyond the control points.", "Because it fits the noise, and its residuals become zero by construction."]'::jsonb, 3, 'Kriging with a guessed variogram honours all six values exactly, so the model can no longer be tested against the data at all. The trade is between an assumption you can state and one buried in a variogram nobody chose.'),
  ('reservoircalc', 'advanced', 'module', 'm05-the-limits-of-a-property-model', 8, 'What does kriging promise that a trend does not?', '["That at a data location it returns the measured value.", "That the modelled values stay within the range of the data.", "That every well influences every node in the frame.", "That the residuals sum to zero across the control set."]'::jsonb, 0, 'The weights fall off with distance and at a well the weight on that well goes to one. A trend fits through the data rather than to it.'),
  ('reservoircalc', 'advanced', 'module', 'm05-the-limits-of-a-property-model', 9, 'At how many of the six Ekene wells does the kriged model return the measured value exactly?', '["All six, which is what the exactness property guarantees.", "Five. Ekene-2 reads 0.191177 against 0.19.", "Four, since the two dry wells are excluded from the fit.", "None, since the grid is sampled bilinearly at every well."]'::jsonb, 1, 'The failure at Ekene-2 has nothing to do with the kriging and everything to do with where that well sits relative to the grid.'),
  ('reservoircalc', 'advanced', 'module', 'm05-the-limits-of-a-property-model', 10, 'What does honouring the data cost at Ekene?', '["Nothing, since both models use the same six values.", "The kriged model books 12.543848 MMstb, below the trend.", "The kriged model books 13.337665 MMstb, above the trend.", "The kriged model changes the cell count as well as the barrels."]'::jsonb, 2, 'Kriging honours the high values that sit over the oil and the low values that sit over dry ground, while the trend smooths them together. That difference is more than the whole spatial part of the trend model.'),
  ('reservoircalc', 'advanced', 'module', 'm05-the-limits-of-a-property-model', 11, 'Why does Ekene-2 sit awkwardly on the grid?', '["It lies on the boundary column used by the fault in the tier below.", "Its easting of 2200 m falls between two columns of nodes.", "It lies outside the 800 m extrapolation limit of the other wells.", "Its northing of 1150 m falls halfway between two rows of nodes."]'::jsonb, 3, 'The frame starts at a northing of 800 m with 100 m spacing, so the rows are at 1100 and 1200 m. Every other well has both coordinates on a node.'),
  ('reservoircalc', 'advanced', 'module', 'm05-the-limits-of-a-property-model', 12, 'Why does the sampling at Ekene-2 cost the trend nothing and kriging something?', '["Bilinear interpolation of a linear function is exact.", "The trend is evaluated analytically while kriging is read from the grid.", "The trend was fitted to include Ekene-2 and the kriging was not.", "Kriging uses a coarser internal grid than the trend method."]'::jsonb, 0, 'The kriged surface bends sharply toward the data at each well, so averaging two nodes either side of Ekene-2 cuts the top off that peak and reports 0.191177 rather than 0.19.'),
  ('reservoircalc', 'advanced', 'module', 'm05-the-limits-of-a-property-model', 13, 'How did the mapping tier meet the same well?', '["It was the only well that fell outside the convex hull of the control.", "Three of the four nodes around it were dead, so no depth came back.", "Its pick was the only one the spline failed to honour.", "It was excluded from the structural grid but kept for the property model."]'::jsonb, 1, 'There a value could not be reported at all. Here the property grid is populated at every node, so a value always comes back and the failure is quieter.'),
  ('reservoircalc', 'advanced', 'module', 'm05-the-limits-of-a-property-model', 14, 'How many modelled values does the Ekene property model produce from six measurements?', '["201, one for each live node.", "169, one for each oil bearing cell.", "500 across the frame, of which 169 reach the booking.", "6, extended to the rest of the field by the constant method."]'::jsonb, 2, 'That is about 28 modelled values per measurement among the booked cells, and the model overrides four of the six measurements it was fitted to.'),
  ('reservoircalc', 'advanced', 'module', 'm05-the-limits-of-a-property-model', 15, 'What is the resolution test for a property map?', '["Compare the effective porosity against the arithmetic well mean.", "Compare the modelled range against the measured range of the data.", "Compare the cell size against the average distance between wells.", "Compare the gradient times the well spacing against the residual."]'::jsonb, 3, 'At Ekene the plane predicts about 0.020 over a kilometre and its largest residual is 0.019309, so the signal to noise ratio at the well spacing scale is about one.'),
  ('reservoircalc', 'advanced', 'module', 'm06-the-property-workflow', 1, 'Which step of the property workflow is most often skipped entirely?', '["Inspecting the residuals at the control points after fitting.", "Choosing a population method and justifying it against the data density.", "Running the volumetric chain with the property grid in place.", "Collecting the property values and recording how they were derived."]'::jsonb, 0, 'It is the step that would have told you the Ekene model misses four of six wells by more than 8 percent of the value measured there.'),
  ('reservoircalc', 'advanced', 'module', 'm06-the-property-workflow', 2, 'Why does the workflow say to look at the property values before modelling them?', '["Because the engine needs the range in order to choose a method.", "Because fitting first means the model shapes what you then see.", "Because outliers must be removed before a least squares fit is valid.", "Because the values have to be converted to a common basis first."]'::jsonb, 1, 'At Ekene, looking first gives six values from 0.17 to 0.23 with the low ones in the east, which is the pattern any model then has to justify or contradict.'),
  ('reservoircalc', 'advanced', 'module', 'm06-the-property-workflow', 3, 'Which quality control check from the tiers below has to be rewritten at this tier?', '["That the field total equals the sum of the block totals.", "That the mapped crest lies above the shallowest well pick.", "That net volume times porosity gives the pore volume.", "That every live node lies within the extrapolation limit."]'::jsonb, 2, 'With a grid that only holds for the volume weighted porosity, so the check now runs backwards: divide pore by net and confirm the result is the average being reported.'),
  ('reservoircalc', 'advanced', 'module', 'm06-the-property-workflow', 4, 'Why does an average porosity in a report become an ambiguous quantity at this tier?', '["Because there are three defensible averages and they differ.", "Because the modelled values fall outside the range of the measurements.", "Because the engine never forms an average at all.", "Because the average depends on which population method was used."]'::jsonb, 0, 'At Ekene they read 0.206667, 0.209368 and 0.210822. Saying which one is quoted is now part of quoting it.'),
  ('reservoircalc', 'advanced', 'module', 'm06-the-property-workflow', 5, 'Which check confirms that only the property model changed between two runs?', '["That the pore volume and the STOIIP change by the same factor.", "That the cell count, gross rock volume and net volume are identical.", "That the effective porosity lies inside the range of the property grid.", "That the residuals at the control points sum to zero."]'::jsonb, 1, 'Any difference in those three means the geometry moved too, so the comparison measures more than the property model and has to be redone.'),
  ('reservoircalc', 'advanced', 'module', 'm06-the-property-workflow', 6, 'A property model reports an effective porosity of 0.24 while its grid over the oil cells runs 0.18 to 0.22. What is wrong?', '["The grid range excludes the dry cells, which carry the higher values.", "The effective porosity has been computed from the gross rock volume rather than the net.", "An effective porosity cannot lie outside the range of the values being averaged.", "Nothing, since volume weighting can push an average past the data range."]'::jsonb, 2, 'It is a weighted average of the grid values over the booked cells. A value of 0.24 means the pore and net volumes come from different runs, or the frames do not match.'),
  ('reservoircalc', 'advanced', 'module', 'm06-the-property-workflow', 7, 'Why is checking a property grid''s range different from checking a constant?', '["Because the grid is stored at a different precision from the constant.", "Because a grid can contain null values where the constant cannot.", "Because the range depends on the contact as well as on the property model itself.", "Because a trend extrapolates without limit, so its extremes need checking."]'::jsonb, 3, 'At Ekene the plane reaches 0.232281 somewhere in the frame, above every measured value, which is worth noticing even though it is small and lands on dead ground.'),
  ('reservoircalc', 'advanced', 'module', 'm06-the-property-workflow', 8, 'Which check tells you how much your result depends on the model at all?', '["The decomposition, which costs two extra bookings and one subtraction.", "The geometry check, which confirms nothing else moved.", "The ratio check, which confirms the chain below the pore volume.", "The residual inspection, which measures the misfit at each control point."]'::jsonb, 0, 'At Ekene it says that 62 percent of the uplift would survive the property model being wholly discredited. The other checks verify that the arithmetic is sound rather than that it matters.'),
  ('reservoircalc', 'advanced', 'module', 'm06-the-property-workflow', 9, 'What can the property quality control checks not see?', '["That the pore volume and the net volume come from different runs.", "That the plane was fitted the wrong way, or that Sw is still constant.", "That the effective porosity lies outside the grid''s range.", "That the geometry changed between the two runs being compared."]'::jsonb, 1, 'Every check passes on a model fitted to porosity values computed with the wrong matrix density, and nothing in a porosity model''s quality control mentions water saturation.'),
  ('reservoircalc', 'advanced', 'module', 'm06-the-property-workflow', 10, 'What does the capstone ask you to set?', '["The population method to krige and the contact to 1560 m.", "The population method to trend and the contact to 1560 m.", "The population method to trend, and nothing else.", "The population method to trend and the fault to 1800 m."]'::jsonb, 2, 'The contact is fixed at 1560 m, the other three properties remain constants, and the fault from the tier below is not present.'),
  ('reservoircalc', 'advanced', 'module', 'm06-the-property-workflow', 11, 'Which six values does the Expert capstone ask for?', '["Porosity at P-1, node mean, gross rock volume, net volume, pore volume and STOIIP.", "Porosity at P-1, the volume weighted mean, pore volume, HCPV, STOIIP and the uplift.", "The three means, the pore volume, the STOIIP and the uplift.", "Porosity at P-1, node mean over the oil, pore volume, HCPV, STOIIP and the uplift."]'::jsonb, 3, 'They read 0.207142, 0.209368, 3.755847, 2.441300, 12.796077 and 0.656868. Gross rock volume and net volume are not asked for, because no property model can change them.'),
  ('reservoircalc', 'advanced', 'module', 'm06-the-property-workflow', 12, 'Which mean does the capstone ask for, and what fails if you report the other?', '["The node mean 0.209368; the volume weighted 0.210822 misses by more than the tolerance.", "The volume weighted 0.210822; the node mean 0.209368 misses by more than the tolerance.", "The arithmetic well mean 0.206667; either model mean fails.", "Either, since both lie inside the 0.001 tolerance on that field."]'::jsonb, 0, 'They differ by 0.001455 and the tolerance is 0.001, so the volume weighted value fails by half again the tolerance. Both are on the panel, so read the tile labels.'),
  ('reservoircalc', 'advanced', 'module', 'm06-the-property-workflow', 13, 'Against which baseline is the capstone''s uplift measured?', '["The well average booking of 12.543848 MMstb, which uses the measured values.", "The Associate booking of 12.139208 MMstb at a constant 0.20.", "The kriged booking of 13.337665 MMstb.", "The node mean booking of 12.707784 MMstb."]'::jsonb, 1, 'Measuring against the well average booking gives 0.252229, which is the spatial part alone and fails the tolerance by a wide margin.'),
  ('reservoircalc', 'advanced', 'module', 'm06-the-property-workflow', 14, 'Which three checks confirm a capstone submission?', '["The three means increase in order; the cell count is 169; the uplift is positive.", "Pore over gross gives 0.210822; the ratios give 1.033333; the uplift plus 12.543848 gives the STOIIP.", "Pore over net gives 0.210822; the two ratios both give 1.054111; the uplift plus 12.139208 gives the STOIIP.", "The residuals sum to zero; the plane gradient is negative; the STOIIP exceeds 12.139208."]'::jsonb, 2, 'The first also confirms that the volume weighted mean exceeds the node mean, as it must when porosity correlates positively with column.'),
  ('reservoircalc', 'advanced', 'module', 'm06-the-property-workflow', 15, 'What is the largest outstanding modelling gap after this tier?', '["The deterministic treatment, which propagates no uncertainty.", "The porosity model, which honours none of the six wells.", "The contact, which remains an assumption rather than a measurement.", "Water saturation, which is still a constant 0.35 everywhere."]'::jsonb, 3, 'It is the property with the strongest physical reason to vary and the largest likely effect, and the machinery for varying it is exactly what this tier taught.'),
  ('reservoircalc', 'advanced', 'final', null, 1, 'Which set of six values is the Ekene property model capstone answer key?', '["0.207142, 0.209368, 3.755847, 2.441300, 12.796077 and 0.656868.", "0.207142, 0.210822, 3.755847, 2.441300, 12.796077 and 0.656868.", "0.220920, 0.217119, 3.914811, 2.544627, 13.337665 and 1.198457.", "0.206667, 0.206667, 3.681814, 2.393179, 12.543848 and 0.404640."]'::jsonb, 0, 'The set with 0.210822 substitutes the volume weighted mean for the node mean, the one with 13.337665 is the kriged model, and the one with 12.543848 is the constant method.'),
  ('reservoircalc', 'advanced', 'final', null, 2, 'What is the single input that changes between the Associate booking and this tier''s?', '["The contact, which is established separately for each compartment.", "The porosity, which becomes a grid holding one value per node.", "The gridding method used for the two structural surfaces.", "All four properties, which are fitted to the six well values."]'::jsonb, 1, 'Net to gross, water saturation and the formation volume factor remain constants, and the fault from the tier below is set aside so that the property model is the only change.'),
  ('reservoircalc', 'advanced', 'final', null, 3, 'Why did the volume engine need no modification to accept a porosity grid?', '["It was always summing node by node and always receiving arrays.", "It converts any grid to an effective constant before summing.", "It reruns the chain once per distinct property value.", "It applies porosity after the summation rather than inside it."]'::jsonb, 0, 'The tiers below filled those arrays with the same value at every node, which is why the chain collapsed into four multiplications on the total.'),
  ('reservoircalc', 'advanced', 'final', null, 4, 'Why does the chain stop factorising when porosity varies?', '["Because the cell area can no longer be taken outside the sum.", "Because a sum of products is not the product of the sums.", "Because the accumulation order changes when a grid is supplied.", "Because the porosity and the oil column become correlated."]'::jsonb, 1, 'Pulling a constant out of a sum leaves it unchanged; pulling a varying quantity out changes the arithmetic. That is why three different means exist at this tier.'),
  ('reservoircalc', 'advanced', 'final', null, 5, 'What are the six Ekene well porosities and their arithmetic mean?', '["0.20 at all six, which is the constant handed out below.", "0.22, 0.19, 0.23, 0.17, 0.21, 0.22, averaging 0.210822.", "0.22, 0.19, 0.23, 0.17, 0.21, 0.22, averaging 0.206667.", "0.17 to 0.23 in even steps, averaging 0.20 exactly."]'::jsonb, 2, 'Their range of 0.06 is 29 percent of the mean. The figure 0.210822 is the volume weighted mean, which is a property of the model rather than of the data.'),
  ('reservoircalc', 'advanced', 'final', null, 6, 'What does the trend population method compute?', '["The weighted mean of the control values, at every node.", "A distance weighted average of the control values.", "A minimum bending surface through the control values.", "A least squares plane, evaluated at every node."]'::jsonb, 3, 'There is no curvature, no local detail, and no way for one well to influence its own neighbourhood more than the field as a whole.'),
  ('reservoircalc', 'advanced', 'final', null, 7, 'Which claim does a trend model make about the geology?', '["That it varies monotonically, in one direction, at a fixed rate.", "That the property is spatially correlated over an estimable range.", "That the property returns to its measured value near each well.", "That the property has a maximum somewhere inside the field."]'::jsonb, 0, 'A channel belt violates the first, a prograding shoreface the second, and compaction driven porosity loss the third.'),
  ('reservoircalc', 'advanced', 'final', null, 8, 'Why can six wells not support a fitted variogram?', '["The wells are not arranged on a regular grid.", "Too few pairs exist to estimate the decorrelation with distance.", "Two of the six are dry and so carry no porosity value.", "A variogram needs at least one well outside the convex hull."]'::jsonb, 1, 'The kriged map''s structure then comes from a range and a model somebody chose, so it is an illustration of a method rather than a defensible model of this field.'),
  ('reservoircalc', 'advanced', 'final', null, 9, 'What are the Ekene plane''s two gradients?', '["0.020451 per km eastward and zero northward.", "0.020437 per km northward and 0.000769 per km eastward.", "0.020437 per km eastward and 0.000769 per km northward.", "0.002044 per km eastward and 0.000077 per km northward."]'::jsonb, 2, 'The eastward gradient is 26.6 times the northward one, so the trend is essentially east to west, about 2.2 degrees south of due west.'),
  ('reservoircalc', 'advanced', 'final', null, 10, 'Why is the Ekene plane''s intercept of 0.241071 not a prediction?', '["It is a normalisation constant rather than a porosity.", "It is the mean of the six well values before the gradients are fitted.", "It is the value at the field crest, which no well penetrated.", "It is the value at the frame origin, outside the mapped area."]'::jsonb, 3, 'No well is near an easting and northing of zero, so quoting it as the porosity of anything would be a mistake.'),
  ('reservoircalc', 'advanced', 'final', null, 11, 'How badly does the Ekene trend miss the wells?', '["Four of six by more than 8 percent of the measured value.", "One of six, at Ekene-2, by 2.8 percent.", "None. A trend fitted to six values honours all six.", "All six by less than 1 percent, since the plane passes near them."]'::jsonb, 0, 'The largest miss is 0.019309 at Ekene-3. Only Ekene-1 is close, and that is by accident of sitting near the centroid of the data.'),
  ('reservoircalc', 'advanced', 'final', null, 12, 'Why do the residuals of a least squares plane sum to zero?', '["Because positive and negative measurement errors cancel.", "Because the model has an intercept.", "Because the residuals are normalised after fitting.", "Because the method minimises their sum rather than their squares."]'::jsonb, 1, 'The plane passes through the centroid of the data, so it is unbiased over the wells as a set and can still be wrong at every individual well.'),
  ('reservoircalc', 'advanced', 'final', null, 13, 'Which residual pattern would tell you the trend is the wrong shape?', '["Residuals that sum to zero across the well set.", "Residuals that alternate in sign and are similar in size.", "Large one sided residuals across neighbouring wells.", "Residuals largest at the well nearest the data centroid."]'::jsonb, 2, 'At Ekene the residuals alternate in sign and the largest is only 1.2 times the next, which is what a fair fit of a modest model looks like.'),
  ('reservoircalc', 'advanced', 'final', null, 14, 'Over the 169 oil bearing cells, what porosity range does the plane use?', '["0.206667 to 0.210822.", "0.17 to 0.23, matching the measured range.", "0.181772 to 0.232281, its range over the whole frame.", "0.194649 to 0.227348."]'::jsonb, 3, 'The 0.17 was measured at Ekene-4, which sits on the eastern flank where no cell holds oil, so the bottom of the distribution never reaches the booking.'),
  ('reservoircalc', 'advanced', 'final', null, 15, 'How does a well with no oil beneath it still affect the booking?', '["Through the fit, since its value moves the coefficients.", "Through the mask, since its position keeps nearby nodes live.", "It does not, since only oil bearing cells reach the chain.", "Through the contact, since it bounds where the oil can be."]'::jsonb, 0, 'Ekene-4 pulls the plane down in the east, which changes the porosity everywhere including over the oil, without contributing a single cell of its own.'),
  ('reservoircalc', 'advanced', 'final', null, 16, 'What are the three means at Ekene under the trend model?', '["0.20, 0.206667 and 0.210822.", "0.206667, 0.209368 and 0.210822.", "0.206667, 0.210822 and 0.219745.", "0.209368, 0.210822 and 0.219745."]'::jsonb, 1, 'They are the arithmetic mean of the wells, the plain mean over the 169 oil cells, and the mean weighted by the rock each cell carries.'),
  ('reservoircalc', 'advanced', 'final', null, 17, 'What does the step from the well mean to the node mean measure?', '["That the thicker cells carry better rock than the thin ones.", "That the model disagrees with the measurements at the wells.", "That the oil bearing cells are not a representative sample.", "That the plane extrapolates beyond the measured range."]'::jsonb, 2, 'The oil sits on the structural high, which is where the plane predicts the better rock, so the low end of the distribution is absent from the population being averaged.'),
  ('reservoircalc', 'advanced', 'final', null, 18, 'What does the step from the node mean to the volume weighted mean measure?', '["The share of the oil lying above the mean column.", "The variance of the modelled porosity over the oil cells.", "The misfit between the model and the measurements.", "The covariance of column and porosity over the mean column."]'::jsonb, 3, 'At Ekene the covariance is 0.019168 and the mean column 13.176944 m, giving 0.001455. If porosity were uncorrelated with column the two means would coincide.'),
  ('reservoircalc', 'advanced', 'final', null, 19, 'What is the volume weighted mean equal to?', '["The pore volume divided by the net volume.", "The pore volume divided by the gross rock volume.", "The node mean weighted by cell area.", "The well mean weighted by each well''s oil column."]'::jsonb, 0, 'At Ekene that gives 0.210822, and the hand route of summed column times porosity over summed column agrees to the seventeenth digit.'),
  ('reservoircalc', 'advanced', 'final', null, 20, 'Which mean does a booking imply, and why is there no choice about it?', '["The node mean, since the engine averages the grid before applying it.", "The volume weighted mean, which reproduces the sum of products.", "The arithmetic well mean, the only one grounded in measurement.", "Whichever the report quotes, since the chain is linear in porosity."]'::jsonb, 1, 'The question is not which average is best but which is already implied by the arithmetic, and there is only one candidate.'),
  ('reservoircalc', 'advanced', 'final', null, 21, 'What does quoting the node mean where the volume weighted mean belongs cost at Ekene?', '["About 0.404 MMstb, overstated.", "About 0.657 MMstb, understated.", "About 0.088 MMstb, understated.", "Nothing, since the two agree to four decimals."]'::jsonb, 2, 'The error is small enough to survive any sanity check and large enough to matter across a portfolio. The defence is structural: sum the products and divide afterwards.'),
  ('reservoircalc', 'advanced', 'final', null, 22, 'Which rows of the chain a property model cannot change?', '["Only the cell count, since volumes all depend on porosity.", "Cell count and gross rock volume only.", "Pore volume, HCPV and STOIIP.", "Cell count, gross rock volume and net volume."]'::jsonb, 3, 'Porosity enters after the net volume is formed. If somebody''s property model changed their gross rock volume, they changed something else at the same time.'),
  ('reservoircalc', 'advanced', 'final', null, 23, 'What is the ratio of the trend booking to the constant 0.20 booking?', '["1.054111.", "1.033333, the ratio of the well mean to 0.20.", "1.098726, which the kriged model gives.", "1.210822, the effective porosity itself."]'::jsonb, 0, 'The whole property model, over all 169 cells, delivers exactly one number to the booking, and it is recoverable from two volumes and a division.'),
  ('reservoircalc', 'advanced', 'final', null, 24, 'The STOIIP ratio and the porosity ratio agree to eight figures and not further. Why?', '["The two ratios are computed over different cell sets.", "The chain stores its constants as 32 bit floats.", "The effective porosity is rounded before the division.", "The trend grid holds values outside the range of the data."]'::jsonb, 1, 'A storage artefact fifteen thousand times smaller than a single barrel on this booking, and not evidence of anything about the model.'),
  ('reservoircalc', 'advanced', 'final', null, 25, 'How does the 0.656868 MMstb uplift decompose?', '["0.163936 from selection and 0.492932 from weighting.", "0.252229 from a better constant and 0.404640 from spatial variation.", "0.404640 from a better constant and 0.252229 from spatial variation.", "It does not decompose, since the model acts on every cell at once."]'::jsonb, 2, 'Nearly two thirds of what the property model appears to be worth is the correction of a constant that sat below the well average.'),
  ('reservoircalc', 'advanced', 'final', null, 26, 'Split into three, what are the parts of the Ekene uplift?', '["0.163936 better constant, 0.404640 selection, 0.088293 weighting.", "0.404640 better constant, 0.088293 selection, 0.163936 weighting.", "0.252229 better constant, 0.240703 selection, 0.163936 weighting.", "0.404640 better constant, 0.163936 selection, 0.088293 weighting."]'::jsonb, 3, 'Only the last two are spatial, and the weighting part, which this tier works hardest to explain, is the smallest of the three.'),
  ('reservoircalc', 'advanced', 'final', null, 27, 'Why does the decomposition matter more than the total?', '["The two parts carry different confidence and need different work.", "The total cannot be reproduced without the intermediate bookings.", "Only the spatial part depends on the choice of method.", "Only the better constant part can have the wrong sign."]'::jsonb, 0, 'The first part rests on six measurements and one division. The second rests on a plane that misses four of six wells by more than 8 percent.'),
  ('reservoircalc', 'advanced', 'final', null, 28, 'What is the correlation between the modelled porosity and the oil column at Ekene?', '["Plus 0.925.", "Plus 0.462.", "Zero.", "Minus 0.462."]'::jsonb, 1, 'Moderate and positive. The Associate tier predicted the sign in words and this tier measures it.'),
  ('reservoircalc', 'advanced', 'final', null, 29, 'Where does that correlation come from?', '["The volume weighting, which creates the correlation it measures.", "A physical link between porosity and the height of the oil column.", "Two trends pointing the same way, in porosity and structure.", "The contact, which removes the cells where it would be negative."]'::jsonb, 2, 'Had the porosity trend pointed north, the correlation would be near zero without any change to the porosity data itself, so it is not independent evidence for the geological story.'),
  ('reservoircalc', 'advanced', 'final', null, 30, 'When does a property model remove barrels relative to a constant?', '["When the contact is shallow enough that few cells hold oil.", "When the model extrapolates below the measured range.", "When the wells over sample the poorest rock.", "When the best rock lies downdip, so the covariance is negative."]'::jsonb, 3, 'A reader who has learned that property models increase volumes has generalised from a common case. What they do is replace an unweighted assumption with a weighted one.'),
  ('reservoircalc', 'advanced', 'final', null, 31, 'How does the Ekene property model compare with the contact sensitivity?', '["Roughly a fifteenth the size: 0.66 against 8 to 10 MMstb per 10 m.", "Roughly the same size, so both deserve equal attention.", "Larger, since the contact was measured and the porosity was not.", "They cannot be compared, since one changes the geometry."]'::jsonb, 0, 'The contact dominates by an order of magnitude, and pinning it is worth more than any property work the study could do.'),
  ('reservoircalc', 'advanced', 'final', null, 32, 'Which is worth more at Ekene: choosing the population method, or using one at all?', '["Using one at all, at 0.656868 MMstb.", "The choice of method, at 0.793817 MMstb across the three.", "They are identical, since the constant is one of the three.", "Neither, since both fall below the fault position uncertainty."]'::jsonb, 1, 'Constant books 12.543848, trend 12.796077 and krige 13.337665. A report that omits which method was used has left out the larger of the two decisions.'),
  ('reservoircalc', 'advanced', 'final', null, 33, 'Which constant left standing has the strongest reason to vary?', '["The formation volume factor, which varies with pressure.", "Net to gross, which falls away from the depocentre.", "Water saturation, which falls with height above the contact.", "None, since all three are already averages over the reservoir."]'::jsonb, 2, 'A single 0.35 is a thickness weighted average of a curve applied uniformly to cells whose columns run from a sliver to 20.28 m.'),
  ('reservoircalc', 'advanced', 'final', null, 34, 'If net to gross also varied, what weight would the effective porosity take?', '["The net to gross alone, since it is applied first.", "The oil column alone, since net to gross cancels.", "The pore volume of each cell.", "The product of the oil column and the net to gross at each node."]'::jsonb, 3, 'The weight is whatever the property multiplies. Area and net to gross cancelled at Ekene only because they are uniform there.'),
  ('reservoircalc', 'advanced', 'final', null, 35, 'What does kriging promise that a trend does not?', '["That at a data location it returns the measured value.", "That the modelled values stay inside the range of the data.", "That every well influences every node in the frame.", "That the residuals sum to zero across the control set."]'::jsonb, 0, 'The trade is that its residuals become zero by construction, so the model can no longer be tested against the data at all.'),
  ('reservoircalc', 'advanced', 'final', null, 36, 'At how many Ekene wells does the kriged grid return the measured value exactly?', '["All six, which the exactness property guarantees.", "Five. Ekene-2 reads 0.191177 against 0.19.", "Four, since the two dry wells are excluded.", "None, since the grid is sampled bilinearly everywhere."]'::jsonb, 1, 'The failure at Ekene-2 has nothing to do with the kriging and everything to do with where that well sits relative to the grid.'),
  ('reservoircalc', 'advanced', 'final', null, 37, 'Why does the off node sampling at Ekene-2 cost the trend nothing?', '["Ekene-2 was included in the trend fit but not in the kriging.", "The trend is evaluated analytically rather than read from the grid.", "Bilinear interpolation of a linear function is exact.", "The trend uses a finer internal grid than kriging does."]'::jsonb, 2, 'A plane has no curvature to lose, so the average of two nodes either side of the well is the plane''s value at the well. A kriged surface bends toward the data and loses its peak.'),
  ('reservoircalc', 'advanced', 'final', null, 38, 'How did the mapping tier meet Ekene-2?', '["It was excluded from the structural grid entirely.", "It was the only well outside the convex hull of the control.", "Its pick was the only one the spline failed to honour.", "Three of the four nodes around it were dead."]'::jsonb, 3, 'There a value could not be reported at all. Here the property grid is populated at every node, so a value always comes back and the failure is quieter.'),
  ('reservoircalc', 'advanced', 'final', null, 39, 'How many modelled porosity values does Ekene produce from six measurements?', '["500 across the frame, of which 169 reach the booking.", "169, one per oil bearing cell.", "201, one per live node.", "6, extended by the constant method."]'::jsonb, 0, 'About 28 modelled values per measurement among the booked cells, and the model overrides four of the six measurements it was fitted to.'),
  ('reservoircalc', 'advanced', 'final', null, 40, 'What is the resolution test for a property map?', '["Compare the modelled range against the measured range.", "Compare the gradient times the well spacing against the residual.", "Compare the cell size against the mean well spacing.", "Compare the effective porosity against the arithmetic well mean."]'::jsonb, 1, 'At Ekene the plane predicts about 0.020 over a kilometre and its largest residual is 0.019309, so its signal to noise ratio at the well spacing scale is about one.'),
  ('reservoircalc', 'advanced', 'final', null, 41, 'Which check tells you how much a result depends on the property model at all?', '["The ratio check across the three lower chain rows.", "The geometry check against the constant booking.", "The decomposition, costing two extra bookings and one subtraction.", "The residual inspection at the control points."]'::jsonb, 2, 'At Ekene it says 62 percent of the uplift would survive the property model being wholly discredited. The other checks verify the arithmetic rather than its importance.'),
  ('reservoircalc', 'advanced', 'final', null, 42, 'What did the three tiers of this course do, in order?', '["Grid a surface; validate it; combine it with a second surface.", "Pick horizons; grid them; convert them to depth.", "Book one volume; measure its uncertainty; convert it to reserves.", "Book one volume; divide it between compartments; let a property vary."]'::jsonb, 3, 'Each tier made the one below it more demanding rather than replacing it, and none of them changed the rock.');
