-- ============================================================================
-- refinery EXPERT DEEP SEED: Refinery Feasibility & Planning, advanced tier.
--
-- Six modules, 26 lessons, 132 questions (15 per module bank plus a 42
-- question final exam). The structure row is GENERATED from the tier's
-- manifest.json rather than hand typed.
--
-- What this tier owns: ACTUALS, VARIANCE AND THE INVESTMENT CASE. A plan, a
-- scheduled event and a recorded actual are one shape in three ledgers; the
-- two ledgers are matched on material and type and each gap splits into a
-- volume variance, a price variance and an unexplained term; a movement in one
-- ledger only is unmatched; each line carries its direction and its effect on
-- margin, and the headline total is on margin. The feasibility streams are
-- valued through the screening engine with revenue as revenue, no royalty,
-- capital deducted in the year it is spent and the construction-year tax loss
-- carried forward.
--
-- THE ENGINE FACT THIS TIER OWNS. A positive gap on a delivery helps the
-- margin and the same gap on a receipt hurts it; the engine signs each line
-- before it adds.
--
-- THE TRAP THE TIER IS BUILT ON. Adding the revenue gaps to the cost gaps as
-- recorded gives a number with no meaning, and throwing the construction loss
-- away taxes the first operating years.
--
-- HELD, taught as a limit and never graded: capital depreciated in the year
-- it is spent (H2). The NPV is read here as the screen's answer; the
-- Economics courses grade it. The capstone grades six numbers, each an
-- engine return: four variance figures to the whole dollar and two tax
-- figures in millions to four decimals.
-- ============================================================================

insert into public.academy_course_structures
    (app_slug, tier, structure, content_version)
values ('refinery', 'advanced', '{"modules":[{"key":"m01-one-shape-three-ledgers","title":"One Shape, Three Ledgers","lesson_keys":["l01-plan-schedule-and-actual","l02-an-event-and-its-value","l03-what-an-event-refuses","l04-the-plan-ledger"]},{"key":"m02-volume-and-price-variance","title":"Volume and Price Variance","lesson_keys":["l01-matched-on-material-and-type","l02-the-volume-variance","l03-the-price-variance","l04-money-with-no-barrels","l05-unmatched-movements"]},{"key":"m03-variance-on-margin","title":"Variance on Margin","lesson_keys":["l01-cost-lines-and-revenue-lines","l02-the-margin-effect","l03-totals-on-margin","l04-units-against-plan"]},{"key":"m04-the-investment-case","title":"The Investment Case","lesson_keys":["l01-streams-into-the-screening-engine","l02-revenue-as-revenue","l03-no-royalty-on-a-refinery","l04-capital-expensed-when-spent","l05-the-feasibility-npv"]},{"key":"m05-tax-losses-carried-forward","title":"Tax Losses Carried Forward","lesson_keys":["l01-a-construction-year-loss","l02-the-loss-pool-year-by-year","l03-the-first-taxable-year","l04-what-carrying-the-loss-is-worth"]},{"key":"m06-the-expert-reading","title":"The Expert Reading","lesson_keys":["l01-the-odioma-month-end-to-end","l02-the-odioma-expansion-end-to-end","l03-what-is-held-and-what-the-oracles-check","l04-where-this-course-hands-over"]}]}'::jsonb, 1)
on conflict (app_slug, tier) do update
  set structure = excluded.structure,
      content_version = excluded.content_version,
      active = true,
      updated_at = now();

delete from public.academy_quiz_questions
 where app_slug = 'refinery' and tier = 'advanced';

insert into public.academy_quiz_questions
    (app_slug, tier, scope, module_key, ord, prompt, options, answer_index, explanation)
values
  ('refinery', 'advanced', 'module', 'm01-one-shape-three-ledgers', 1, 'The stream model holds a plan event, a scheduled event and a recorded actual. What tells the three apart?', '["The fields: an actual event adds a cost field.", "Only the ledger each one is marked with: plan, schedule or actual.", "The sign: plan quantities positive, actuals negative.", "The grain: plan events by day, actuals by month."]'::jsonb, 1, 'A plan event, a scheduled event and a recorded actual are the same shape, marked by their ledger: plan, schedule or actual.'),
  ('refinery', 'advanced', 'module', 'm01-one-shape-three-ledgers', 2, 'makeEvent records a delivery of 100 bbl. What signedQuantity does the engine return, and is the event flagged as emitting by its nature?', '["100, since a typed quantity is never negative.", "0, since a delivery moves product inside the site.", "-100, and it is flagged as emitting.", "-100, and it is not flagged as emitting."]'::jsonb, 3, 'Direction comes from the event type. A delivery of 100 bbl signs to -100 for the site''s stock, and its emits flag reads false. Only burn, flare and vent read true.'),
  ('refinery', 'advanced', 'module', 'm01-one-shape-three-ledgers', 3, 'Which event type signs a quantity of 100 bbl to -100 while its emits-by-nature flag reads false?', '["loss", "flare", "vent", "unit_run"]'::jsonb, 0, 'A loss removes barrels, -100 for 100 bbl, and emits nothing by its nature. Flare and vent also sign to -100 but read true on the flag, and a unit_run signs to 0.'),
  ('refinery', 'advanced', 'module', 'm01-one-shape-three-ledgers', 4, 'A unit_run of 100 bbl is recorded for the ODIOMA reformer. What does makeEvent return as its signedQuantity?', '["-100, the naphtha feed it consumes.", "100, the reformate it makes.", "0, the same as a transfer or a blend.", "-100, flagged as emitting, since a unit burns fuel while it runs."]'::jsonb, 2, 'Direction comes from the event type. A transfer, a unit_run and a blend all sign a quantity of 100 bbl to 0, and none of the three is flagged as emitting by its nature.'),
  ('refinery', 'advanced', 'module', 'm01-one-shape-three-ledgers', 5, 'A clerk keys a quantity of -500 into makeEvent to reverse a delivery. What does the engine return?', '["REFUSED: \"Event quantity is unsigned; direction comes from the event type\"", "An accepted receipt of 500 bbl, since a negative delivery is read as material coming back in.", "REFUSED: \"Unknown event type \"sale\"\", the same message any bad type gets.", "An accepted delivery with its quantity stored as 500 bbl and a warning flag set."]'::jsonb, 0, 'makeEvent takes a quantity that is never negative: direction comes from the event type. A quantity of -500 is refused with the message that says so. The sale message is the refusal for an unknown event type.'),
  ('refinery', 'advanced', 'module', 'm01-one-shape-three-ledgers', 6, 'An event is sent to makeEvent marked with a ledger called forecast. What happens to it?', '["It is accepted into the plan ledger.", "It is accepted and listed as unmatched.", "It is refused with the quantity message, because a forecast quantity is unsigned.", "It is refused by name: \"Unknown ledger \"forecast\"\"."]'::jsonb, 3, 'The three ledgers are plan, schedule and actual. makeEvent refuses a ledger called forecast with a message of its own, and the message names the ledger it did not know.'),
  ('refinery', 'advanced', 'module', 'm01-one-shape-three-ledgers', 7, 'A trader wants to record an lpg sale with the event type sale. What does makeEvent do?', '["Refuses it: \"Unknown event type \"sale\"\".", "Accepts it as a delivery.", "Accepts it as revenue, signed 0.", "Accepts it as costed false."]'::jsonb, 0, 'makeEvent refuses an event type called sale with a message of its own, and the message names the type it did not know. A delivery is one of the nine event types it knows, and a delivery signs 100 bbl to -100.'),
  ('refinery', 'advanced', 'module', 'm01-one-shape-three-ledgers', 8, 'An event is recorded with no cost at all. What does it carry, and how does a variance line built from it read?', '["Cost 0, and the line reads costed true.", "It is refused, naming the missing cost.", "Cost null, and the line reads costed false.", "Cost 0, and the line reads costed false."]'::jsonb, 2, 'An event recorded with no cost carries cost null, which is different from a cost of 0, and the variance marks a line with an uncosted event as costed false. The event is recorded, so nothing is refused. Every ODIOMA variance line reads costed true.'),
  ('refinery', 'advanced', 'module', 'm01-one-shape-three-ledgers', 9, 'How many barrels of Escravos (illustrative) does the ODIOMA plan ledger receive?', '["700000.00 bbl", "600000.00 bbl", "350000.00 bbl", "400000.00 bbl"]'::jsonb, 1, 'The escravos receipt line reads 600000.00 bbl in 2 events, against 700000.00 bbl available in the configuration. Forcados (illustrative) is received at 400000.00 bbl, and 350000.00 bbl is the cargo size the plan was cascaded with.'),
  ('refinery', 'advanced', 'module', 'm01-one-shape-three-ledgers', 10, 'The plan ledger''s cdu unit_run line reads a quantity equal to which other ODIOMA plan figure?', '["The crude unit''s capacity, 1200000.00 bbl.", "The Escravos availability, 700000.00 bbl.", "The reformer''s 190000.00 bbl.", "All the crude in the plan, 1000000.00 bbl."]'::jsonb, 3, 'The cdu unit_run line and the plan''s total crude both print 1000000.00 bbl, since every barrel of crude passes through the unit with no feed. Its capacity of 1200000.00 bbl is another row of the configuration, and 700000.00 bbl is what Escravos has available.'),
  ('refinery', 'advanced', 'module', 'm01-one-shape-three-ledgers', 11, 'Read the ODIOMA reformer''s plan ledger quantity beside its capacity in the configuration. How do the two compare?', '["They are equal, 190000.00 bbl each.", "The ledger reads 163400.00 bbl against a capacity of 190000.00 bbl.", "The ledger reads 190000.00 bbl against a capacity of 1200000.00 bbl.", "The ledger reads 1000000.00 bbl, every barrel of crude, against 190000.00 bbl."]'::jsonb, 0, 'The reformer line reads 190000.00 bbl and the reformer''s capacity reads 190000.00 bbl. 163400.00 bbl is the plan''s gasoline delivery, 1200000.00 bbl the crude unit''s capacity and 1000000.00 bbl the cdu line.'),
  ('refinery', 'advanced', 'module', 'm01-one-shape-three-ledgers', 12, 'At what value per barrel does the ODIOMA plan ledger hold its gasoline deliveries?', '["104.9000, the price of the Jet A-1 the plan also delivers", "4.7763, the plan''s gross margin per barrel of crude", "100.6000, the diesel price in the product table", "110.5000, the gasoline price the plan was solved with"]'::jsonb, 3, 'The plan ledger prices every movement at the configuration''s own figure. The gasoline line reads 18055700.00 over 163400.00 bbl, 110.5000 a barrel, the gasoline price in the product table. That plan unit value is the price the volume variance later uses.'),
  ('refinery', 'advanced', 'module', 'm01-one-shape-three-ledgers', 13, 'The plan ledger shows 2 events on each crude receipt line and 5 on each product delivery line. How does the variance read those events?', '["It matches each event with the dated actual event nearest to it and prices the gap in days.", "It takes the value per barrel of the first event on each line as the line''s unit value.", "It reads only each line''s sum, the grain it matches the actuals on.", "It averages the events on a line, so a line with 5 events carries more weight than one with 2."]'::jsonb, 2, 'The plan ledger is summed from the scheduled events by material and type, and that is the grain the variance matches on. The event count shows the schedule''s shape; the variance reads the sum.'),
  ('refinery', 'advanced', 'module', 'm01-one-shape-three-ledgers', 14, 'What does the value on a unit_run line of the ODIOMA plan ledger record?', '["What the unit''s products sell for, since a unit run makes the products the plan delivers.", "The value of the crude fed to the unit, 78.9000 a barrel on the Escravos share of the run.", "Nothing, since a unit_run signs to 0 and so carries a value of 0.", "What running the unit costs, 1400000.00 for the cdu."]'::jsonb, 3, 'The cdu unit_run line reads 1000000.00 bbl and a value of 1400000.00, a value per bbl of 1.4000, the crude unit''s operating cost in the configuration.'),
  ('refinery', 'advanced', 'module', 'm01-one-shape-three-ledgers', 15, 'The ODIOMA configuration lists the Crude distillation unit with no feed stream. What does the plan make of it?', '["It is left out of the plan, because a unit with no feed has nothing to run.", "It is the crude unit and carries every barrel of crude.", "It runs the Escravos crude alone, since that is the first crude in the configuration.", "It writes no crude-unit row until a feed stream is typed against it in the configuration."]'::jsonb, 1, 'An owner decision in force names the unit with no feed as the crude unit. The plan needs no feed stream typed against it, and the ledger shows the result on the cdu unit_run line.'),
  ('refinery', 'advanced', 'module', 'm02-volume-and-price-variance', 1, 'attributeVariance lays the ODIOMA plan ledger beside the actual ledger. On what does it match a plan line to an actual line?', '["Material alone.", "Type alone.", "Material and type together.", "Material, type and the event date."]'::jsonb, 2, 'attributeVariance matches the two ledgers on material and type, so a plan line and an actual line are the same line only when both agree. Each ODIOMA line carries one material and one type, such as escravos receipt or cdu unit_run.'),
  ('refinery', 'advanced', 'module', 'm02-volume-and-price-variance', 2, 'What volume variance does the escravos receipt line read?', '["10651500.00", "955500.00", "11607000.00", "-11607000.00"]'::jsonb, 0, 'Volume variance = (actual quantity - plan quantity) x plan unit value. The escravos line moved 735000.00 bbl against a plan of 600000.00 bbl, a quantity gap of 135000.00 at 78.9000, and reads 10651500.00. 955500.00 is its price variance, 11607000.00 its total and -11607000.00 its margin effect.'),
  ('refinery', 'advanced', 'module', 'm02-volume-and-price-variance', 3, 'Which figure is the diesel delivery line''s price variance?', '["-9054000.00", "-9590800.00", "168000.00", "-536800.00"]'::jsonb, 3, 'Diesel sold at an actual unit value of 98.4000 against a plan of 100.6000 on 244000.00 bbl, and the line reads a price variance of -536800.00. -9054000.00 is its volume variance, -9590800.00 its total, and 168000.00 is the fuel_oil line''s price variance.'),
  ('refinery', 'advanced', 'module', 'm02-volume-and-price-variance', 4, 'At which unit value does the volume variance price a line''s quantity gap?', '["The actual unit value, so a dearer barrel in the month raises the volume variance.", "The plan unit value, the plan line''s value per barrel.", "The mean of the plan and actual unit values, so neither ledger dominates.", "The configuration''s capacity cost, 1.4000 a barrel on every line."]'::jsonb, 1, 'Volume variance = (actual quantity - plan quantity) x plan unit value. The actual unit value appears only in the price variance, (actual unit value - plan unit value) x actual quantity.'),
  ('refinery', 'advanced', 'module', 'm02-volume-and-price-variance', 5, 'In the price variance, (actual unit value - plan unit value) is multiplied by which quantity?', '["The plan quantity.", "The quantity gap.", "The mean of the plan and actual quantities.", "The actual quantity."]'::jsonb, 3, 'Price variance = (actual unit value - plan unit value) x actual quantity. On the escravos line the actual unit value of 80.2000 against the plan''s 78.9000 is taken on the 735000.00 bbl received, and the line reads 955500.00.'),
  ('refinery', 'advanced', 'module', 'm02-volume-and-price-variance', 6, 'No Forcados (illustrative) barrels arrived in the month. What price variance does its line read, and why?', '["0.00, because the actual quantity it is taken on is 0.00.", "-30720000.00, the whole planned purchase at 76.8000.", "212000.00, the bill that arrived with no barrels.", "-400000.00, the quantity gap on the line."]'::jsonb, 0, 'The price variance is taken on the actual quantity, and the actual quantity is 0.00, so it reads 0.00. -30720000.00 is the line''s volume variance, 212000.00 its unexplained and -400000.00 its quantity gap in bbl.'),
  ('refinery', 'advanced', 'module', 'm02-volume-and-price-variance', 7, 'Forcados (illustrative) recorded 0.00 bbl and an actual value of 212000.00. In which column of the variance line does that 212000.00 appear?', '["The price variance.", "The volume variance column.", "The unexplained column.", "No column; it is listed as unmatched."]'::jsonb, 2, 'Unexplained = total - volume - price, and it is zero unless money moved with no barrels. On the Forcados line the volume variance is -30720000.00, the price variance 0.00 and the unexplained 212000.00, the money with no barrels shown on its own.'),
  ('refinery', 'advanced', 'module', 'm02-volume-and-price-variance', 8, 'The engine defines unexplained = total - volume - price. When is that term anything but zero?', '["When the unit values differ.", "When money moved with no barrels.", "When a movement sits in one ledger and not the other.", "When an event was recorded with cost null."]'::jsonb, 1, 'Seven of the eight ODIOMA lines read 0.00 unexplained. The Forcados line reads 212000.00 because a bill arrived with 0.00 bbl. A price difference goes to the price variance, and a movement in one ledger only is listed as unmatched.'),
  ('refinery', 'advanced', 'module', 'm02-volume-and-price-variance', 9, 'The actual ledger holds an lpg delivery of 9000.00 bbl for 441000.00, and the plan sells no lpg. What does attributeVariance do with it?', '["Adds it to the gasoline delivery line, the nearest light product.", "Puts its 441000.00 into the unexplained column of a delivery line.", "Refuses the actual ledger until a plan line for lpg is typed.", "Lists it as unmatched and folds it into no variance line."]'::jsonb, 3, 'Movements in one ledger and not the other are listed as unmatched and folded into no variance line. The row shows lpg, delivery, present in actual, 9000.00 bbl and 441000.00.'),
  ('refinery', 'advanced', 'module', 'm02-volume-and-price-variance', 10, 'In the actual ledger, what does the fuel_oil delivery''s value of 12810000.00 record?', '["What the fuel oil sold for in the month.", "What the fuel oil cost the refinery to make.", "What the plan expected the fuel oil to sell for.", "What the crude behind the fuel oil cost."]'::jsonb, 0, 'A delivery''s value is what it sold for; every other event''s value is what it cost. The plan expected 18902800.00 for the fuel_oil line, and the month''s delivery of 210000.00 bbl sold for 12810000.00.'),
  ('refinery', 'advanced', 'module', 'm02-volume-and-price-variance', 11, 'Over the month, what did each barrel of Escravos (illustrative) cost, as its variance line reads the actual unit value?', '["78.9000", "76.8000", "80.2000", "0.0000"]'::jsonb, 2, 'Actual unit value = actual value / actual quantity: 58947000.00 over 735000.00 bbl reads 80.2000, against a plan unit value of 78.9000. 76.8000 is the Forcados plan unit value, and 0.0000 is what the Forcados line reads, with no barrels received.'),
  ('refinery', 'advanced', 'module', 'm02-volume-and-price-variance', 12, 'The gasoline line reads a volume variance of -5606770.00 and a price variance of 179070.00. Read as recorded, what do the two signs say?', '["More barrels sold than planned, each at a lower price than planned.", "Fewer barrels sold than planned, each at a better price than planned.", "Fewer barrels sold than planned, each at a lower price than planned.", "The line lost money on both counts, since both terms reduce margin."]'::jsonb, 1, 'Gasoline sold 112660.00 bbl against a plan of 163400.00 bbl, so the volume variance is negative. Its actual unit value of 112.0895 beats the plan''s 110.5000, so the price variance is positive.'),
  ('refinery', 'advanced', 'module', 'm02-volume-and-price-variance', 13, 'Which two product delivery lines read a negative price variance?', '["jet and diesel", "gasoline and fuel_oil", "diesel and fuel_oil", "gasoline and jet"]'::jsonb, 0, 'Jet reads -80980.00 at 104.0998 against 104.9000, and diesel -536800.00 at 98.4000 against 100.6000. Gasoline reads 179070.00 and fuel_oil 168000.00, both sold above their plan prices.'),
  ('refinery', 'advanced', 'module', 'm02-volume-and-price-variance', 14, 'What quantity gap does the reformer unit_run line read?', '["-265000.00 bbl", "131000.00 bbl", "-182900.00 bbl", "-59000.00 bbl"]'::jsonb, 3, 'Quantity gap = actual quantity - plan quantity: 131000.00 against 190000.00 bbl reads -59000.00. -265000.00 is the crude unit''s gap, 131000.00 the reformer''s actual run, and -182900.00 is the reformer''s volume variance in money.'),
  ('refinery', 'advanced', 'module', 'm02-volume-and-price-variance', 15, 'The crude unit ran 735000.00 bbl for 1080450.00. Which actual unit value does its variance line print?', '["1.4000", "1.4700", "3.2000", "3.1000"]'::jsonb, 1, 'Actual unit value = actual value / actual quantity, and the cdu line reads 1.4700 against a plan unit value of 1.4000. 3.2000 and 3.1000 are the reformer''s actual and plan unit values.'),
  ('refinery', 'advanced', 'module', 'm03-variance-on-margin', 1, 'How does a matched ODIOMA variance line get its direction of cost or revenue?', '["From the sign of the line''s total variance: positive reads revenue, negative cost.", "From whether the line''s value rose or fell against the plan.", "From its event type: a delivery is revenue, a receipt or unit_run is cost.", "From the unit value on the line: above plan reads revenue, below it reads cost."]'::jsonb, 2, 'A delivery''s value is what it sold for, so a delivery line is revenue. Every other event''s value is what it cost, so a receipt line and a unit_run line are cost. The table bears it out: escravos reads a positive total and forcados a negative one, and both are cost lines.'),
  ('refinery', 'advanced', 'module', 'm03-variance-on-margin', 2, 'The escravos receipt line reads a total variance of 11607000.00. What margin effect does the engine give it?', '["-11607000.00", "11607000.00", "-30508000.00", "-5427700.00"]'::jsonb, 0, 'marginEffect is the total with its sign set by what it did to margin: as it is on a revenue line, reversed on a cost line. Escravos is a cost line, so 11607000.00 reads -11607000.00. -30508000.00 is the Forcados total as recorded and -5427700.00 the gasoline margin effect.'),
  ('refinery', 'advanced', 'module', 'm03-variance-on-margin', 3, 'The jet delivery line reads a total variance of -3731500.00 and a margin effect of -3731500.00. Why does the sign stay the same?', '["Its price variance is negative, so the engine leaves the total alone.", "Its unexplained reads 0.00, so there is nothing to reverse on it.", "Every negative total keeps its sign when it is put on margin.", "It is a revenue line, and a revenue gap counts as it is."]'::jsonb, 3, 'The engine''s rule is "margin: a revenue gap counts as it is, a cost gap with its sign reversed". Jet is a delivery and so a revenue line. The crude unit''s total of -319550.00 is also negative, and on margin it reads 319550.00 because it is a cost line.'),
  ('refinery', 'advanced', 'module', 'm03-variance-on-margin', 4, 'Put on margin, the Forcados (illustrative) line''s total becomes which figure?', '["-30508000.00", "30508000.00", "-30720000.00", "212000.00"]'::jsonb, 1, 'The Forcados total variance is -30508000.00. It is a cost line, so the sign is reversed and the margin effect reads 30508000.00. -30720000.00 is its volume variance and 212000.00 its unexplained.'),
  ('refinery', 'advanced', 'module', 'm03-variance-on-margin', 5, 'In the totals table, the cost lines as recorded carry which volume variance?', '["-24572090.00", "-20622400.00", "-19390350.00", "212000.00"]'::jsonb, 1, 'As recorded, the cost lines add to -20622400.00 on volume and to -19390350.00 in total. -24572090.00 is the same column for the revenue lines, and 212000.00 is the cost lines'' unexplained.'),
  ('refinery', 'advanced', 'module', 'm03-variance-on-margin', 6, 'Which figure does the engine print as the month''s headline variance?', '["-44233150.00, every total added as recorded", "-19390350.00, the cost lines", "-24842800.00, the revenue lines as recorded", "-5452450.00, the total on margin"]'::jsonb, 3, 'The headline total is on margin, -5452450.00. The two rows as recorded say what happened to spending and to sales. The sum of every line''s total as recorded is printed and is not the headline.'),
  ('refinery', 'advanced', 'module', 'm03-variance-on-margin', 7, 'Adding every line''s total variance as recorded gives -44233150.00. Why is that sum not the headline?', '["It adds cost gaps and revenue gaps with no sign reversed.", "It leaves out the Forcados line.", "It counts the lpg sale twice.", "It is formed at the actual unit values, which differ from the plan unit values on each line."]'::jsonb, 0, 'The headline is on margin: a revenue gap counts as it is, a cost gap with its sign reversed. Adding every line''s total as recorded, cost and revenue together, gives -44233150.00; the margin total is -5452450.00, and the engine prints that as the headline.'),
  ('refinery', 'advanced', 'module', 'm03-variance-on-margin', 8, 'Read the headline row on margin. What price variance does it carry?', '["-3949690.00", "1020050.00", "-1290760.00", "-270710.00"]'::jsonb, 2, 'The margin row reads a volume variance of -3949690.00, a price variance of -1290760.00, an unexplained of -212000.00 and a total of -5452450.00. 1020050.00 is the cost lines'' price variance as recorded and -270710.00 the revenue lines''.'),
  ('refinery', 'advanced', 'module', 'm03-variance-on-margin', 9, 'The cost lines as recorded carry an unexplained of 212000.00. What does the headline row on margin read in that column?', '["212000.00", "0.00", "-212000.00", "-3949690.00"]'::jsonb, 2, 'A cost gap counts with its sign reversed on margin, and the only unexplained money of the month sits on a cost line, Forcados. So 212000.00 as recorded reads -212000.00 on margin: money paid out with no barrels. -3949690.00 is the margin row''s volume variance.'),
  ('refinery', 'advanced', 'module', 'm03-variance-on-margin', 10, 'The cost lines as recorded read a price variance of 1020050.00. What does its sign say?', '["The month spent less on crude and on unit runs than the plan expected it to.", "The crude and unit runs that did move cost more a barrel than planned.", "The cost lines helped the margin on price by that figure.", "Fewer barrels of crude were bought and run through the units than the plan expected."]'::jsonb, 1, 'On a cost line a positive price variance is a dearer barrel. The cost row''s total variance of -19390350.00 says the month spent less overall, and its volume variance of -20622400.00 says fewer barrels were bought and run.'),
  ('refinery', 'advanced', 'module', 'm03-variance-on-margin', 11, 'What margin variance does reconcilePeriod read across the plan and actual ledgers?', '["-5452450.00", "-235150.00", "4776300.00", "-5011450.00"]'::jsonb, 3, 'reconcilePeriod reads a plan margin of 4776300.00, an actual margin of -235150.00 and a margin variance of -5011450.00. -5452450.00 is the margin total of the matched lines.'),
  ('refinery', 'advanced', 'module', 'm03-variance-on-margin', 12, 'The margin variance less the margin total of the matched lines comes to 441000.00. What accounts for it?', '["The unmatched lpg sale, which the ledger margins count and the lines do not.", "The Forcados bill of 212000.00, counted once in each of the two totals.", "Rounding in the plan unit values, carried to four decimals on each line.", "The reformer''s price variance, taken on its actual 131000.00 bbl."]'::jsonb, 0, 'The ledger margins count every movement and the variance lines count only the matched ones. The unmatched movements, deliveries counted as revenue and the rest as cost, come to 441000.00, the lpg delivery the plan never carried.'),
  ('refinery', 'advanced', 'module', 'm03-variance-on-margin', 13, 'Which unit reads 68.95 percent of plan, and with what difference?', '["The crude unit, a difference of -59000.00", "The reformer, a difference of -59000.00", "The reformer, a difference of -265000.00", "The crude unit, a difference of -265000.00"]'::jsonb, 1, 'The reformer ran 131000.00 bbl against a plan of 190000.00 bbl, a difference of -59000.00 bbl and 68.95 percent of plan. The crude unit reads -265000.00 bbl and 73.50 percent.'),
  ('refinery', 'advanced', 'module', 'm03-variance-on-margin', 14, 'The crude unit reads 73.50 percent in the units against plan table. Against which figure is that measured?', '["Its plan throughput, 1000000.00 bbl.", "Its capacity in the configuration, 1200000.00 bbl.", "Escravos received, 735000.00 bbl.", "The cargo size, 350000.00 bbl."]'::jsonb, 0, 'Utilisation of plan reads the actual against the plan''s throughput for the unit: 735000.00 bbl against 1000000.00 bbl. The crude unit''s capacity of 1200000.00 bbl is a different base, so 73.50 percent of plan is not a statement about capacity.'),
  ('refinery', 'advanced', 'module', 'm03-variance-on-margin', 15, 'dualLedgerTotals reads the actual ledger apart. What revenue does it print for it?', '["60658650.00", "84825300.00", "80049000.00", "60423500.00"]'::jsonb, 3, 'The actual ledger reads cost 60658650.00, revenue 60423500.00 and margin -235150.00. The plan ledger reads cost 80049000.00 and revenue 84825300.00. Each margin agrees with the one reconcilePeriod reads: true.'),
  ('refinery', 'advanced', 'module', 'm04-the-investment-case', 1, 'What royaltyRate does feasibilityEconomics hand the screening engine for the ODIOMA expansion?', '["30", "0", "12", "22"]'::jsonb, 1, 'The royalty rate is 0 because a refinery buys its crude and pays no royalty, an owner decision in force. 30 is the taxRate, 12 the discountRate and 22 the projectLife in years.'),
  ('refinery', 'advanced', 'module', 'm04-the-investment-case', 2, 'Why is the royalty rate on the ODIOMA expansion 0?', '["The tax rate of 30 percent carries it.", "It is charged on the crude in opexFixed.", "TaxRoyalty has no royalty term to set.", "A refinery buys its crude and pays no royalty."]'::jsonb, 3, 'The printed reason is that a refinery buys its crude and pays no royalty. The tax rate of 30 percent is a separate input, opexFixed holds the fixed operating cost plus the crude cost, and TaxRoyalty still takes a royaltyRate, which is 0.'),
  ('refinery', 'advanced', 'module', 'm04-the-investment-case', 3, 'With the royalty rate at 0, what fiscalType does the screening engine receive, and what does the royalty column show?', '["TaxRoyalty, and the column reads 0.0000 in every year.", "No fiscalType, and the column is dropped from the cash flow.", "A tax-only type, and the column is left blank.", "TaxRoyalty, and the column carries the crude royalty from 2029."]'::jsonb, 0, 'feasibilityEconomics hands the screening engine fiscalType TaxRoyalty with royaltyRate 0, and the cash flow prints the royalty column at 0.0000 in every year from 2027 to 2048.'),
  ('refinery', 'advanced', 'module', 'm04-the-investment-case', 4, 'What does the opexFixed of 291.7664 million in the first operating year contain?', '["The fixed operating cost of 14000000.00 a year, and nothing else.", "The capital spread over 20 years.", "The fixed operating cost plus the crude cost.", "The variable cost of 4.2000 a barrel."]'::jsonb, 2, 'The screen labels it: opexFixed in the first operating year is the fixed operating cost plus the crude cost, in millions. With opexVariable of 15.7651 it makes the cash flow''s opex of 307.5315.'),
  ('refinery', 'advanced', 'module', 'm04-the-investment-case', 5, 'What price does the screening engine receive for the first operating year?', '["92.2100, the slate''s gross value", "14.0100, the gross margin per barrel", "74.0000, the crude cost a barrel", "4.2000, the variable cost a barrel"]'::jsonb, 0, 'Revenue goes in as revenue: barrels at the slate''s value. The price is the gross value per barrel of crude, 92.2100, on production of 3753600.00 bbl. 14.0100 is the gross margin per barrel on the screen.'),
  ('refinery', 'advanced', 'module', 'm04-the-investment-case', 6, 'Among the inputs printed for the screen, which lossCarryForward value appears?', '["false, the screening engine''s default for other callers", "false, so that each year is taxed on its own", "Left out, so the screening engine''s default applies", "true"]'::jsonb, 3, 'The inputs print lossCarryForward true beside royaltyRate 0 and taxRate 30. Loss carry-forward is off by default for every other caller; the refinery switches it on.'),
  ('refinery', 'advanced', 'module', 'm04-the-investment-case', 7, 'The cash flow''s opex in each operating year reads 307.5315. How is that figure formed?', '["opexFixed 291.7664 plus opexVariable 15.7651.", "The fixed cost of 14000000.00 plus 4.2000 a barrel.", "opexFixed 291.7664 plus the tax of 15.7651.", "Gross revenue 346.1195 less the tax of 38.5879."]'::jsonb, 0, 'The digest prints the sum: 291.7664 + 15.7651 = 307.5315, and the cash flow''s opex reads 307.5315. The crude cost sits inside opexFixed, so a fixed and variable cost alone would leave the crude out.'),
  ('refinery', 'advanced', 'module', 'm04-the-investment-case', 8, 'In the screening engine''s units, what capex does year 0 carry?', '["58915982.67 million", "117.8320 million", "58.9160 million", "117831965.35 million"]'::jsonb, 2, 'The screening engine works in millions of US dollars. The capital of 117831965.35 dollars is spread as 58915982.67 dollars in each construction year, which the cash flow prints as 58.9160 million in year 0 and again in year 1.'),
  ('refinery', 'advanced', 'module', 'm04-the-investment-case', 9, 'How does the expansion capital of 117831965.35 enter the streams?', '["All of it in year 0, the first construction year.", "Evenly, 58915982.67 in each of the 2 construction years.", "Evenly over the 20 operating years, as a yearly charge.", "In year 1, the year construction is finished, at 117.8320."]'::jsonb, 1, 'The capital is spread evenly over the 2 construction years, each half printed to the cent. The engine carries the unrounded halves, which sum to the capital: true.'),
  ('refinery', 'advanced', 'module', 'm04-the-investment-case', 10, 'The screening engine receives a projectLife of 22 years. What does that cover?', '["The 20 operating years plus 2 years of loss carried forward.", "The calendar years 2027 to 2048, less the construction years.", "The 12 percent discount horizon and the 30 percent tax years.", "Construction in years 0 and 1, operation from year 2 to 21."]'::jsonb, 3, 'The project life covers the construction years and the operating years together, numbered year 0 to year 21 on the cash flow, calendar 2027 to 2048 from start year 2027.'),
  ('refinery', 'advanced', 'module', 'm04-the-investment-case', 11, 'feasibilityEconomics passes no capexDepreciationYears. What does the screening engine then do with the capital?', '["It deducts it over the 20 operating years.", "It deducts the capital in the year it is spent.", "It deducts nothing until the plant is commissioned in 2029.", "It refuses the call without a schedule."]'::jsonb, 1, 'The depreciation column equals the capex column in every year: true. So 2027 and 2028 each carry a deduction of 58.9160 million with no revenue against it, and the construction years make a tax loss.'),
  ('refinery', 'advanced', 'module', 'm04-the-investment-case', 12, 'Held item H2 is taught as a limit of the screening engine. What does it say the engine lacks?', '["A royalty setting for a plant that buys its crude.", "Any way to carry a tax loss into later years.", "A capital allowance schedule starting at commissioning.", "A mid-year discounting convention for the NPV."]'::jsonb, 2, 'H2: the screening engine depreciates capital in the year it is spent and offers no capital allowance schedule starting at commissioning. Carrying the loss forward covers the refinery case, and a fuller allowance model belongs to the Economics module.'),
  ('refinery', 'advanced', 'module', 'm04-the-investment-case', 13, 'What net cash flow does the ODIOMA expansion read in 2028?', '["38.5879, the first operating year", "-58.9160, capex with nothing earned", "0.0000, no flow at all", "27.6320, the first taxed year"]'::jsonb, 1, '2028 is year 1, the second construction year: no revenue, no opex, a capex of 58.9160 and no tax, so the net cash flow reads -58.9160. 38.5879 is year 2 and 27.6320 year 5.'),
  ('refinery', 'advanced', 'module', 'm04-the-investment-case', 14, 'The screen prints its NPV of 88.6345 million at 12 percent. Which discounting convention does it state?', '["End-year: a flow in year t is discounted over t whole years.", "Start-year: year 0 undiscounted.", "Continuous, at 12 percent a day.", "Mid-year: a flow in year t is discounted at t + 0.5."]'::jsonb, 3, 'The screen prints the convention beside the figure: mid-year discounting, a flow in year t discounted at t + 0.5. The Economics courses teach and grade the NPV; this course reads it as the screen''s answer.'),
  ('refinery', 'advanced', 'module', 'm04-the-investment-case', 15, 'The expansion is re-run with start year 2031 in place of 2027. What changes?', '["Only the calendar labels on the years.", "The NPV, discounted further.", "The tax, as the pool opens in 2031.", "The capital, via the modular law."]'::jsonb, 0, 'The start year labels the years and moves no figure. With start year 2031 the first calendar year reads 2031, and the NPV and total tax read 88.6345 and 196.1780 as they do with 2027. The two agree to the last digit: true.'),
  ('refinery', 'advanced', 'module', 'm05-tax-losses-carried-forward', 1, 'What taxable income before relief does each operating year of the ODIOMA expansion read, before the pool is set against it?', '["11.5764 million", "58.9160 million", "38.5879 million", "10.9559 million"]'::jsonb, 2, 'From year 2 to year 21 the taxable income before relief reads 38.5879 million, with no capital left to deduct. 11.5764 million is the full annual tax on it, 10.9559 million the tax in year 5, and 58.9160 million the capital deducted in each construction year.'),
  ('refinery', 'advanced', 'module', 'm05-tax-losses-carried-forward', 2, 'How much sits in the pool once 2028, the second construction year, closes?', '["117.8320 million", "58.9160 million", "79.2440 million", "40.6561 million"]'::jsonb, 0, 'The pool holds both construction years'' losses: 58.9160 million at the end of year 0 and 117.8320 million at the end of year 1. 79.2440 and 40.6561 are the pool at the end of years 2 and 3.'),
  ('refinery', 'advanced', 'module', 'm05-tax-losses-carried-forward', 3, 'For a caller other than the refinery, how is the screening engine''s lossCarryForward option set?', '["On by default for every caller.", "Off by default.", "On only when a royalty is charged.", "Off only for a TaxRoyalty fiscal type."]'::jsonb, 1, 'The owner decision in force: loss carry-forward is an option of the screening engine, off by default for every other caller; the refinery switches it on. feasibilityEconomics passes lossCarryForward true.'),
  ('refinery', 'advanced', 'module', 'm05-tax-losses-carried-forward', 4, 'In years 0 and 1, what tax do the two treatments print?', '["Carried reads 0.0000; option off reads 11.5764.", "Option off prints a refund of 58.9160.", "Carried holds 58.9160 as a tax credit.", "Both read 0.0000."]'::jsonb, 3, 'Years 0 and 1 read taxable income before relief of -58.9160 million, and both tax columns read 0.0000. With the loss carried forward, the loss at year end reads 58.9160 and then 117.8320 million. The two tax columns first differ in year 2.'),
  ('refinery', 'advanced', 'module', 'm05-tax-losses-carried-forward', 5, 'Year 2, calendar 2029, reads taxable income before relief of 38.5879 million. With the loss carried forward, why is its tax 0.0000?', '["The plant makes no profit until year 5, when the first tax falls due.", "The tax rate of 30 percent is not applied until the pool is empty.", "The pool of 117.8320 million carried in covers the whole year''s income.", "Year 2 is still a construction year, so its income is not taxed."]'::jsonb, 2, 'The loss carried in to 2029 is 117.8320 million, larger than the year''s taxable income of 38.5879 million, so no income is left to tax, and the loss carried forward at year end reads 79.2440 million.'),
  ('refinery', 'advanced', 'module', 'm05-tax-losses-carried-forward', 6, 'With the loss carried forward, which is the first year with tax to pay?', '["Year 2, calendar 2029, tax 11.5764", "Year 4, calendar 2031, tax 2.0682", "Year 6, calendar 2033, tax 11.5764", "Year 5, calendar 2032, tax 10.9559"]'::jsonb, 3, 'The engine prints: first year with tax to pay, loss carried forward: year 5, tax 10.9559 MM. 2.0682 million is the pool at the end of year 4, and 11.5764 million is the full annual tax from year 6.'),
  ('refinery', 'advanced', 'module', 'm05-tax-losses-carried-forward', 7, 'Why is year 5''s tax of 10.9559 million below the 11.5764 million that year 6 pays?', '["The last 2.0682 million of the pool shelters part of year 5''s income.", "Year 5 carries a smaller taxable income than year 6 does.", "The tax rate in year 5 is lower than the 30 percent later.", "Year 5''s tax is a rounding of the 11.5764 million figure."]'::jsonb, 0, 'Year 5 opens with 2.0682 million in the pool against taxable income of 38.5879 million, the same income as year 6. The pool is emptied and the income it cannot cover is taxed at 30 percent. From year 6 nothing is left to set against income.'),
  ('refinery', 'advanced', 'module', 'm05-tax-losses-carried-forward', 8, 'With the option off, what tax does year 2, calendar 2029, pay?', '["0.0000 million", "10.9559 million", "38.5879 million", "11.5764 million"]'::jsonb, 3, 'With the option off, calculateEconomics taxes each year on its own taxable income and the construction losses are not carried, so every operating year from year 2 pays 11.5764 million. With the loss carried forward year 2 pays 0.0000.'),
  ('refinery', 'advanced', 'module', 'm05-tax-losses-carried-forward', 9, 'What rule does the engine state for the loss carried forward at year end?', '["The loss carried in less the tax paid in the year, never below zero.", "The loss carried in less taxable income, never below zero.", "The capex less the depreciation, never below zero.", "The loss carried in times the tax rate of 30 percent."]'::jsonb, 1, 'The loss carried forward = the loss carried in - taxable income, never below zero. In 2029 the loss carried in is 117.831965348 million, the taxable income 38.587936000 million and the loss carried forward 79.244029348 million.'),
  ('refinery', 'advanced', 'module', 'm05-tax-losses-carried-forward', 10, 'Subtracting two printed four-decimal pool figures can differ from a printed result in the last place. Why?', '["The engine rounds only the tax column to four decimals.", "The pool is carried in whole millions.", "Each four-decimal figure is rounded on its own.", "The tax rate is applied after the pool is rounded down."]'::jsonb, 2, 'Each four-decimal figure is rounded on its own, so the digest prints the construction years through year 6 to nine decimals for arithmetic. Each nine-decimal figure agrees with the engine''s own to within two units in the ninth decimal.'),
  ('refinery', 'advanced', 'module', 'm05-tax-losses-carried-forward', 11, 'How does the feasibility oracle check the loss pool?', '["With a dated tax-loss ledger used oldest first.", "With one undated pool, used newest loss first.", "By re-solving the plan with a small extra supply.", "With a pool that lapses after 2 years unused."]'::jsonb, 0, 'The feasibility oracle keeps annual accounts and a dated tax-loss ledger used oldest first, so the loss from 2027 is used before the loss from 2028. Re-solving with a small extra supply is how the plan oracle values a stream.'),
  ('refinery', 'advanced', 'module', 'm05-tax-losses-carried-forward', 12, 'Years 0 and 1 read taxable income before relief of -58.9160 million. Where does that figure come from?', '["The fixed operating cost, charged before the plant starts.", "The capex deducted in the year, with no revenue against it.", "The tax at 30 percent on the capital, owed in advance.", "The crude bought ahead of start-up, carried inside opex."]'::jsonb, 1, 'Taxable income before relief = gross revenue - opex - capex deducted. At nine decimals years 0 and 1 read gross revenue 0.000000000, opex 0.000000000 and capex deducted 58.915982674, so taxable income reads -58.915982674, and the tax in both years is 0.000000000.'),
  ('refinery', 'advanced', 'module', 'm05-tax-losses-carried-forward', 13, 'What total tax over the life does the engine print with the option off?', '["196.1780 million", "35.3496 million", "231.5276 million", "11.5764 million"]'::jsonb, 2, 'Total tax over the life: 196.1780 MM with the loss carried forward; 231.5276 MM with the option off; the difference 35.3496 MM.'),
  ('refinery', 'advanced', 'module', 'm05-tax-losses-carried-forward', 14, 'In which years does the whole printed difference of 35.3496 million in total tax arise?', '["Years 0 and 1, the two construction years.", "Years 2 to 5, the years the pool shelters.", "Every one of the 20 operating years alike.", "Year 21, when the unused pool is released."]'::jsonb, 1, 'The construction years pay 0.0000 under both treatments, and from year 6 both pay 11.5764 million a year. With the option off years 2 to 5 each pay 11.5764 million; with the loss carried years 2 to 4 pay 0.0000 and year 5 pays 10.9559 million.'),
  ('refinery', 'advanced', 'module', 'm05-tax-losses-carried-forward', 15, 'The screen reads 88.6345 MM with the loss carried forward and 64.8440 MM with the option off. What does the pair show?', '["Switching the option off, on the same inputs, lowers the screen''s NPV.", "The option off screens a different capital, so the two are different plants.", "The NPV is the graded figure, so the carried case wins.", "The option on moves the tax into the two construction years."]'::jsonb, 0, 'The option-off run takes the same inputs through calculateEconomics directly, and the NPV at 12 percent reads 88.6345 MM carried and 64.8440 MM with the option off. The construction years pay 0.0000 tax in both columns. The Economics courses teach and grade the NPV; this course reads it as the screen''s answer.'),
  ('refinery', 'advanced', 'module', 'm06-the-expert-reading', 1, 'What do the engines state about inventory from one period to the next?', '["One period at a time, with no inventory between periods.", "Closing stock from one month opens the next month''s plan.", "Inventory is carried into the next period at the plan unit value.", "Only crude is carried over, at the cost it was bought for."]'::jsonb, 0, 'The engines state that a plan covers one period at a time, with no inventory between periods. Nothing is carried over into the next month, at a plan unit value or at cost.'),
  ('refinery', 'advanced', 'module', 'm06-the-expert-reading', 2, 'Held item H3 concerns materialBalance. Why can that function not close a refinery tank?', '["It counts burns, flares and vents in, beside the receipts.", "It counts receipts out and deliveries in, the reverse of a refinery tank.", "A unit run moves nothing, and crude leaves its tank through the crude unit.", "It counts a unit run as a delivery out of the tank."]'::jsonb, 2, 'materialBalance counts receipts in and deliveries, burns, flares, vents and losses out, and a unit run moves nothing. A refinery''s crude leaves through the crude unit and its products arrive from units, so the function serves a tank whose movements are receipts and deliveries. This course prints no material balance.'),
  ('refinery', 'advanced', 'module', 'm06-the-expert-reading', 3, 'No unit in a configuration is left without a feed. What crude-unit row does the plan then write?', '["A crude-unit row for the first unit in the list.", "A refusal that names the missing crude unit.", "A crude-unit row with a capacity of 0.00 bbl.", "No crude-unit row."]'::jsonb, 3, 'Of the three owner decisions in force, this is the one about the plan. With no feedless unit there is no unit to carry the crude, and the plan writes no crude-unit row.'),
  ('refinery', 'advanced', 'module', 'm06-the-expert-reading', 4, 'Which golden file holds the cases that check the volume, price and unexplained split?', '["modularrefinery_cases.json, with its 8 feasibility cases", "refineryplanning_cases.json, with its 3 variance lines", "refineryplanning_cases.json, with its 1 schedule", "modularrefinery_cases.json, with its 5 scale points"]'::jsonb, 1, 'refineryplanning_cases.json holds 6 plans, 3 variance lines and 1 schedule, written by the plan oracle. modularrefinery_cases.json holds 8 feasibility cases and 5 scale points, written by the feasibility oracle.'),
  ('refinery', 'advanced', 'module', 'm06-the-expert-reading', 5, 'What is it that neither oracle checks?', '["A stream''s value.", "A schedule''s dates.", "A refusal''s wording.", "The tax-loss pool."]'::jsonb, 2, 'The plan oracle values a stream by re-solving with a small extra supply of it and dates the schedule by datetime.date, and the feasibility oracle keeps a dated tax-loss ledger. Neither checks a refusal''s wording, so every refusal sentence is the engine''s own and is quoted.'),
  ('refinery', 'advanced', 'module', 'm06-the-expert-reading', 6, 'How does the plan oracle accept a plan and value a stream?', '["Exact rational simplex with a duality certificate; a stream by re-solving with a small extra supply of it.", "Floating point simplex checked against the engine to four decimals; a stream by its price in the configuration.", "Annual accounts and a dated tax-loss ledger used oldest first; a stream by its share of the plan''s margin.", "A second run of the engine at a doubled capacity; a stream by the dual printed in the engine''s own output."]'::jsonb, 0, 'The plan oracle solves each plan in exact rational arithmetic and accepts it only with a duality certificate, and values a stream by exact re-solve. Annual accounts and a dated tax-loss ledger are the feasibility oracle''s method.'),
  ('refinery', 'advanced', 'module', 'm06-the-expert-reading', 7, 'Which of these is a limit the engines state about themselves?', '["Loss carry-forward is switched off for a refinery.", "Yields change with the crude unit''s throughput.", "The schedule models each jetty window.", "Quality is not carried through the plan."]'::jsonb, 3, 'The engines state: yields are fixed vectors; quality is not carried through the plan; one period at a time with no inventory between periods; the schedule models no tank capacity, jetty window or turnaround.'),
  ('refinery', 'advanced', 'module', 'm06-the-expert-reading', 8, 'A unit loses part of the month to a turnaround and runs below plan. How does that appear in the units against plan table?', '["As a turnaround flag on the unit''s row.", "Only as a shortfall against plan.", "As an unmatched movement in the actual ledger.", "As unexplained money on the unit_run line."]'::jsonb, 1, 'The schedule models no tank capacity, jetty window or turnaround, and the app reports the gap and does not say why it happened. A unit held down for any of those reasons shows only as a difference from plan.'),
  ('refinery', 'advanced', 'module', 'm06-the-expert-reading', 9, 'Which of these ODIOMA figures is in millions of US dollars?', '["4776300.00, the plan margin reconcilePeriod reads", "80.2000, the actual unit value on the escravos line", "10.9559, the first year''s tax with the loss carried forward", "-5452450.00, the variance lines'' total on margin"]'::jsonb, 2, 'Barrels and US dollars print to two decimals, US dollars a barrel to four, and the screening engine''s millions to four. The first year with tax to pay prints tax 10.9559 MM. 4776300.00 and -5452450.00 are US dollars, and 80.2000 is US dollars a barrel.'),
  ('refinery', 'advanced', 'module', 'm06-the-expert-reading', 10, 'What actual margin does the ODIOMA month close with, against a plan margin of 4776300.00?', '["-235150.00", "-5011450.00", "-5452450.00", "-44233150.00"]'::jsonb, 0, 'Over the month the actual ledger''s deliveries brought in less than its receipts and unit runs cost, which leaves -235150.00. The other three are variances: -5011450.00 across the ledgers, -5452450.00 on margin over the matched lines, and -44233150.00 every line''s total as recorded.'),
  ('refinery', 'advanced', 'module', 'm06-the-expert-reading', 11, 'Which two settings of the ODIOMA screen are owner decisions in force for a refinery?', '["Mid-year discounting, and a 12 percent rate.", "Firm supply, and a plant of 12000 bpd.", "A taxRate of 30, and the fiscalType TaxRoyalty.", "A royalty rate of 0, and the loss carried forward."]'::jsonb, 3, 'The owner decisions in force: no royalty on a refinery, so feasibilityEconomics passes a royalty rate of 0; and loss carry-forward, off by default for every other caller, which the refinery switches on. The third decision, the feedless unit as the crude unit, is about the plan. The other pairs are the expansion''s own inputs.'),
  ('refinery', 'advanced', 'module', 'm06-the-expert-reading', 12, 'Held item H2 deducts capital in the year it is spent. What makes that an acceptable screen for a refinery?', '["The royalty rate of 0 set for every refinery case.", "The refinery''s loss carry-forward, switched on.", "The feedless unit taken as the crude unit of the plan.", "The mid-year convention on the NPV."]'::jsonb, 1, 'The held item says carrying the loss forward covers the refinery case. The loss made in 2027 and 2028 is carried and used from 2029 to 2032, and the first tax falls in year 5. The royalty rate of 0 and the feedless unit are owner decisions on other matters.'),
  ('refinery', 'advanced', 'module', 'm06-the-expert-reading', 13, 'A learner wants to know why a stream is worth what the plan says. Which course takes that question?', '["supply, Terminals, Depots & Fuel Supply", "The Economics courses", "crude, Crude Assay & Blending", "The Professional tier of this course"]'::jsonb, 2, 'Stream values belong to the plan, and what lies behind them is taught in the crude course. This course reads each value as the plan prints it.'),
  ('refinery', 'advanced', 'module', 'm06-the-expert-reading', 14, 'What part does the NPV of 88.6345 million play in this course?', '["It is read as the feasibility screen''s answer.", "It is graded in this course, to four decimals.", "It moves with the start year, so each run is dated.", "It is the lifetime tax with the loss carried forward."]'::jsonb, 0, 'The Economics courses teach and grade the NPV; this course reads it as the feasibility screen''s answer. With start year 2031 the NPV reads 88.6345, as it does with 2027, and 196.1780 MM is the total tax over the life with the loss carried forward.'),
  ('refinery', 'advanced', 'module', 'm06-the-expert-reading', 15, 'What does the engine do to each variance line before it adds the lines into the headline total?', '["It adds every total as recorded, then signs the sum.", "It folds money with no barrels into the nearest volume variance.", "It drops the lines that read an unexplained figure.", "It signs each line''s total by what the line did to margin."]'::jsonb, 3, 'On margin the fuel_oil total of -6092800.00 counts as it is and the Forcados total of -30508000.00 reads 30508000.00. Only then are the lines added, to the headline of -5452450.00, which carries the Forcados unexplained as -212000.00.'),
  ('refinery', 'advanced', 'final', null, 1, 'Which pair does makeEvent return for a flare of 100 bbl: its signedQuantity and its emits flag?', '["-100, flagged as emitting by its nature", "-100, with the emits flag left false", "0, since a flare moves nothing out of the site", "100, flagged as emitting by its nature"]'::jsonb, 0, 'The table prints flare at -100 for 100 bbl with emits by its nature true, the same as burn and vent. A loss also reads -100, and its flag reads false.'),
  ('refinery', 'advanced', 'final', null, 2, 'A receipt of 100 bbl goes through makeEvent. What signedQuantity comes back?', '["-100", "0", "100", "-500"]'::jsonb, 2, 'A receipt is the one event type that signs 100 bbl to 100. Deliveries, burns, flares, vents and losses sign to -100; transfers, unit runs and blends to 0. A quantity typed as -500 is refused.'),
  ('refinery', 'advanced', 'final', null, 3, 'Which of these events signs a quantity of 100 bbl to 0?', '["a blend", "a loss", "a vent", "a delivery"]'::jsonb, 0, 'A blend signs to 0, as a transfer and a unit_run do. A loss, a vent and a delivery each sign 100 bbl to -100.'),
  ('refinery', 'advanced', 'final', null, 4, 'What quantity does the ODIOMA plan ledger''s jet delivery line hold?', '["160000.00 bbl", "101200.00 bbl", "163400.00 bbl", "136000.00 bbl"]'::jsonb, 3, 'The jet delivery line reads 136000.00 bbl at 104.9000. 160000.00 bbl is the Jet A-1 ceiling in the configuration, 101200.00 bbl the month''s actual jet delivery, and 163400.00 bbl the plan''s gasoline.'),
  ('refinery', 'advanced', 'final', null, 5, 'Which figure is the ODIOMA month''s planned gross margin per barrel?', '["4.7763", "14.0100", "1.4000", "3.1000"]'::jsonb, 0, 'The plan reads total crude 1000000.00 bbl, margin 4776300.00 and gross margin per barrel 4.7763. 14.0100 is the expansion screen''s figure, and 1.4000 and 3.1000 are the two units'' operating costs a barrel.'),
  ('refinery', 'advanced', 'final', null, 6, 'The reformer''s unit_run line in the plan ledger reads 589000.00 on 190000.00 bbl. Which per-barrel figure is that?', '["1.4000, the crude unit''s cost", "3.2000, the month''s actual", "3.1000, its operating cost", "4.2000, the expansion''s cost"]'::jsonb, 2, 'The reformer line reads 190000.00 bbl and 589000.00, 3.1000 a barrel, the reformer''s operating cost in the configuration. 3.2000 is the reformer''s actual unit value in the month.'),
  ('refinery', 'advanced', 'final', null, 7, 'Which cargo size was the ODIOMA plan scheduled with?', '["400000.00 bbl", "190000.00 bbl", "600000.00 bbl", "350000.00 bbl"]'::jsonb, 3, 'The plan is cascaded from 2027-03-01 over 31 days with a cargo size of 350000.00 bbl. 400000.00 bbl is the Forcados receipt in the plan and 600000.00 bbl the Escravos receipt.'),
  ('refinery', 'advanced', 'final', null, 8, 'Which ODIOMA line reads an actual unit value of 61.0000?', '["gasoline delivery", "fuel_oil delivery", "diesel delivery", "jet delivery"]'::jsonb, 1, 'The fuel_oil line reads an actual unit value of 61.0000 against a plan of 60.2000. Gasoline reads 112.0895, diesel 98.4000 and jet 104.0998.'),
  ('refinery', 'advanced', 'final', null, 9, 'What price variance does the crude unit''s line carry?', '["51450.00", "13100.00", "-371000.00", "-319550.00"]'::jsonb, 0, 'The cdu line ran at 1.4700 a barrel against the plan''s 1.4000 on 735000.00 bbl and reads a price variance of 51450.00. -371000.00 is its volume variance and -319550.00 its total; 13100.00 is the reformer''s price variance.'),
  ('refinery', 'advanced', 'final', null, 10, 'Jet A-1 sold 101200.00 bbl against a plan of 136000.00 bbl. Priced at the plan''s 104.9000, that barrel gap gives which figure?', '["-80980.00", "-3731500.00", "-3650520.00", "-34800.00"]'::jsonb, 2, 'Volume variance = (actual quantity - plan quantity) x plan unit value, and the jet line prints -3650520.00. -80980.00 is its price variance, -3731500.00 its total and -34800.00 its quantity gap in bbl.'),
  ('refinery', 'advanced', 'final', null, 11, 'What plan unit value does the Forcados (illustrative) line carry?', '["78.9000", "76.8000", "80.2000", "74.0000"]'::jsonb, 1, 'Plan unit value = plan value / plan quantity: 30720000.00 over 400000.00 bbl. 78.9000 and 80.2000 are Escravos in the plan and in the month, and 74.0000 is the expansion''s crude.'),
  ('refinery', 'advanced', 'final', null, 12, 'The escravos line''s total variance is 11607000.00. How does the engine split it?', '["955500.00 volume and 10651500.00 price", "10651500.00 volume and 955500.00 price", "11607000.00 volume and 0.00 price", "10651500.00 volume and 955500.00 unexplained"]'::jsonb, 1, 'The escravos line reads a volume variance of 10651500.00, a price variance of 955500.00 and 0.00 unexplained. The barrel gap of 135000.00 is priced at 78.9000; the price rise to 80.2000 is taken on the 735000.00 bbl that arrived.'),
  ('refinery', 'advanced', 'final', null, 13, 'Gasoline sold 112660.00 bbl against a plan of 163400.00 bbl. Which quantity gap does its line print?', '["-50740.00", "-34800.00", "-90000.00", "-104000.00"]'::jsonb, 0, 'Quantity gap = actual quantity - plan quantity, and the gasoline line prints -50740.00. -34800.00 is jet''s gap, -90000.00 diesel''s and -104000.00 fuel_oil''s.'),
  ('refinery', 'advanced', 'final', null, 14, 'The actual ledger holds a movement with no plan line to meet. Where does attributeVariance put it?', '["In the unexplained column of the nearest delivery line on the plan.", "In a new variance line of its own, priced at its actual unit value.", "In a separate unmatched list, with the ledger it came from.", "Nowhere, since it is dropped before the match is made."]'::jsonb, 2, 'The match on material and type finds no partner, so the row stands apart. ODIOMA''s lpg sale of 9000.00 bbl for 441000.00 is marked present in actual, and no volume, price or unexplained figure absorbs it.'),
  ('refinery', 'advanced', 'final', null, 15, 'The reformer is a cost line with a total variance of -169800.00. What does it read on margin?', '["-169800.00, as a negative stays", "13100.00, its price variance", "-182900.00, its volume variance", "169800.00, since less was spent"]'::jsonb, 3, 'A cost gap counts with its sign reversed on margin. The reformer ran 131000.00 bbl against 190000.00 bbl, so less was spent running it, and its margin effect reads 169800.00.'),
  ('refinery', 'advanced', 'final', null, 16, 'Diesel is a revenue line. What margin effect does it carry?', '["-9054000.00", "-536800.00", "-9590800.00", "-6092800.00"]'::jsonb, 2, 'A revenue gap counts as it is, so the diesel total of -9590800.00 is also its margin effect. -9054000.00 and -536800.00 are its volume and price variances, and -6092800.00 is the fuel_oil margin effect.'),
  ('refinery', 'advanced', 'final', null, 17, 'What total variance do the revenue lines read, added as recorded?', '["-19390350.00", "-44233150.00", "-20622400.00", "-24842800.00"]'::jsonb, 3, 'The revenue lines as recorded read -24842800.00: the month received less than the plan from products. -19390350.00 is the cost lines'' total and -20622400.00 their volume variance, and -44233150.00 is every line''s total added as recorded.'),
  ('refinery', 'advanced', 'final', null, 18, 'In which calendar year does the expansion''s capex column first read 0.0000?', '["2027", "2028", "2029", "2032"]'::jsonb, 2, 'Years 0 and 1, calendar 2027 and 2028, carry capex of 58.9160 each. Year 2, calendar 2029, is the first operating year and reads capex 0.0000 with gross revenue 346.1195. 2032 is the first year with tax to pay.'),
  ('refinery', 'advanced', 'final', null, 19, 'How many events does dualLedgerTotals count in the plan ledger?', '["9", "8", "5", "34"]'::jsonb, 3, 'dualLedgerTotals reads 34 events in the plan ledger and 9 in the actual ledger, with 0 uncosted events in each. 5 is the event count on each unit_run and delivery line of the plan ledger.'),
  ('refinery', 'advanced', 'final', null, 20, 'The plan ledger''s margin and the plan''s own margin both read 4776300.00. What does that agreement show?', '["That the month''s actual margin matched the plan''s own margin figure.", "That the ledger summed from the schedule carries the plan''s margin.", "That every one of the eight variance lines reads costed true.", "That the unmatched lpg sale is counted once."]'::jsonb, 1, 'The plan ledger is summed from the scheduled events, and reconcilePeriod reads its margin as 4776300.00 beside the plan''s own margin of 4776300.00. The actual margin reads -235150.00, and the lpg delivery is unmatched, in no variance line.'),
  ('refinery', 'advanced', 'final', null, 21, 'What annual throughput does the ODIOMA expansion screen print?', '["735000.00 bbl", "1000000.00 bbl", "1200000.00 bbl", "3753600.00 bbl"]'::jsonb, 3, 'The screen prints annual throughput of 3753600.00 bbl, the production the screening engine receives in the first operating year. The other three are figures of the ODIOMA month.'),
  ('refinery', 'advanced', 'final', null, 22, 'From which reference point is the expansion''s capital scaled by the modular law?', '["117831965.35 at 12000 bpd", "14000000.00 at 12000 bpd", "58915982.67 at 10000 bpd", "100000000.00 at 10000 bpd"]'::jsonb, 3, 'Capital is scaled by the modular law from 100000000.00 at 10000 bpd, and the 12000 bpd plant comes out at 117831965.35. 14000000.00 is the fixed operating cost a year.'),
  ('refinery', 'advanced', 'final', null, 23, 'The expansion screen prints a gross value of 92.2100 and a gross margin per barrel of 14.0100. What lies between the two?', '["The crude cost alone, at 74.0000", "The crude cost and the variable operating cost", "The fixed operating cost and the tax", "The royalty and the crude cost"]'::jsonb, 1, 'Per barrel of crude, the engine takes the crude cost and the variable operating cost off the gross value to give the gross margin. The fixed operating cost is a yearly figure in the streams, the royalty rate is 0, and tax has its own column.'),
  ('refinery', 'advanced', 'final', null, 24, 'What gross revenue does each operating year of the expansion carry, in millions?', '["307.5315", "291.7664", "346.1195", "38.5879"]'::jsonb, 2, 'Each operating year reads gross revenue 346.1195, opex 307.5315 and, before any tax, a net cash flow of 38.5879. 291.7664 is opexFixed.'),
  ('refinery', 'advanced', 'final', null, 25, 'At what discount rate and tax rate, in that order, is the expansion valued?', '["12 and 30", "30 and 12", "12 and 0", "0 and 30"]'::jsonb, 0, 'The inputs read discountRate 12 and taxRate 30, beside royaltyRate 0. The expansion is valued at a discount rate of 12 percent and a tax rate of 30 percent.'),
  ('refinery', 'advanced', 'final', null, 26, 'On a matched variance line where no barrels arrived, what actual unit value does the engine print?', '["0.0000", "The plan unit value, 76.8000", "The bill on the line, 212000.00", "null, since it cannot divide"]'::jsonb, 0, 'The engine''s rule for a matched line''s unit values gives 0 when no barrels arrived. Forcados received 0.00 bbl, prints 0.0000 beside its plan unit value of 76.8000, and carries its 212000.00 in the unexplained column.'),
  ('refinery', 'advanced', 'final', null, 27, 'The expansion is valued with start year 2031. What does the first calendar year read?', '["2027", "2029", "2031", "2033"]'::jsonb, 2, 'Year 0 takes the start year as its label. The money in every row is unchanged, which the digest confirms by printing the same NPV and total tax for both runs.'),
  ('refinery', 'advanced', 'final', null, 28, 'How much loss is left in the pool at the end of 2029?', '["117.8320 million", "79.2440 million", "40.6561 million", "2.0682 million"]'::jsonb, 1, 'The loss carried forward at the end of 2029 reads 79.2440 million. At nine decimals, 117.831965348 carried in less taxable income of 38.587936000 leaves 79.244029348. 40.6561 and 2.0682 are the pool at the end of 2030 and 2031.'),
  ('refinery', 'advanced', 'final', null, 29, 'At nine decimals, what tax does year 5 pay with the loss carried forward?', '["11.576380800 million", "2.068157348 million", "38.587936000 million", "10.955933596 million"]'::jsonb, 3, 'Year 5 reads a loss carried in of 2.068157348 million, taxable income of 38.587936000 million and tax of 10.955933596 million. Year 6 pays 11.576380800 million.'),
  ('refinery', 'advanced', 'final', null, 30, 'How is a year''s tax formed once a loss is being carried?', '["taxable income x 30 percent, less the loss carried in, once above zero", "(taxable income - the tax paid last year) x 30 percent, once above zero", "the loss carried in x 30 percent, taken off the year''s income", "(taxable income - the loss carried in) x 30 percent, once above zero"]'::jsonb, 3, 'The digest states: the tax = (taxable income - the loss carried in) x the tax rate of 30 percent once that is above zero. The loss is set against income before the rate is applied.'),
  ('refinery', 'advanced', 'final', null, 31, 'What difference in total tax over the life does carrying the loss forward make?', '["196.1780 million", "11.5764 million", "35.3496 million", "64.8440 million"]'::jsonb, 2, 'The two lifetime totals are 196.1780 carried and 231.5276 with the option off, and the engine prints the gap between them itself. 11.5764 is one full year''s tax, and 64.8440 is a screen reading of another kind.'),
  ('refinery', 'advanced', 'final', null, 32, 'How is the option-off tax column of the ODIOMA expansion produced?', '["feasibilityEconomics with lossCarryForward true and the rate at 0", "The same inputs through calculateEconomics directly, with the option off", "attributeVariance run over the plan and the actual cash flows", "reconcilePeriod read across the 22 years of the project life"]'::jsonb, 1, 'feasibilityEconomics switches lossCarryForward on. The comparison runs the same inputs through calculateEconomics directly with the option off, where each year is taxed on its own taxable income.'),
  ('refinery', 'advanced', 'final', null, 33, 'If the construction loss is not carried, which year pays the plant''s first tax?', '["2032, year 5", "2027, year 0", "2033, year 6", "2029, year 2"]'::jsonb, 3, 'With the option off, year 2, calendar 2029, pays 11.5764. With the loss carried forward, the first year with tax to pay is year 5, 2032.'),
  ('refinery', 'advanced', 'final', null, 34, 'With the loss carried forward, what net cash flow does 2032 read?', '["27.0116", "38.5879", "10.9559", "27.6320"]'::jsonb, 3, '2032 is year 5, the first year with tax to pay, a tax of 10.9559, and its net cash flow reads 27.6320. 2029 to 2031 read 38.5879 with no tax, and from 2033 each year reads 27.0116.'),
  ('refinery', 'advanced', 'final', null, 35, 'Which movements does materialBalance treat as leaving a tank?', '["Receipts and deliveries alone", "Unit runs, blends and transfers", "Deliveries, burns, flares, vents and losses", "Receipts, unit runs and blends"]'::jsonb, 2, 'Receipts are the one movement it counts in, and a unit run counts as nothing. H3 is held and taught as a limit, and this course prints no material balance.'),
  ('refinery', 'advanced', 'final', null, 36, 'What does modularrefinery_cases.json hold?', '["6 plans, 3 variance lines, 1 schedule", "8 feasibility cases, 5 scale points", "8 plans and 5 variance lines", "5 feasibility cases, 8 scale points"]'::jsonb, 1, 'oracle_modularrefinery.py writes it, keeping annual accounts and a dated tax-loss ledger used oldest first, and restating the mid-year NPV from the screening engine.'),
  ('refinery', 'advanced', 'final', null, 37, 'Held item H2 leaves a fuller capital allowance model open. Which part of the Academy owns it?', '["The Economics module", "The supply course", "The crude course", "This course''s Expert tier"]'::jsonb, 0, 'The held item names the Economics module as the owner of a fuller allowance model, and says carrying the loss forward covers the refinery case.'),
  ('refinery', 'advanced', 'final', null, 38, 'Is there a published source in the engines repository for the 0.6 and 0.9 exponents?', '["Yes, one is cited beside each exponent in the code.", "Yes, it is held in the feasibility oracle''s file.", "Yes, it is the ODIOMA vendor quotation itself.", "No; none is in the engines repository."]'::jsonb, 3, 'The held item states it: the engines repository holds none. The exponents are held, taught as a stated limit, and never graded.'),
  ('refinery', 'advanced', 'final', null, 39, 'What do the engines state about crude yields?', '["They are fixed vectors.", "They vary with the unit''s throughput.", "They carry quality through the plan.", "They are fitted afresh each period."]'::jsonb, 0, 'Each crude in the configuration carries one row of yields, naphtha to offgas, and the engine treats that row as a fixed vector. Escravos (illustrative), for one, carries a naphtha yield of 0.2100.'),
  ('refinery', 'advanced', 'final', null, 40, 'At a month-end review of ODIOMA, which figure is the month judged against?', '["The actual margin, -235150.00", "The plan margin, 4776300.00", "The crude unit capacity, 1200000.00 bbl", "The screen''s NPV, 88.6345 million"]'::jsonb, 1, 'The plan''s margin of 4776300.00 and its gross margin per barrel of 4.7763 are what the month is read against. The actual margin of -235150.00 is what the month did.'),
  ('refinery', 'advanced', 'final', null, 41, 'In every year of the expansion, what does the screening engine''s depreciation column equal?', '["The capex column of the same year", "One twentieth of the capital a year", "Zero until commissioning in 2029", "The loss carried forward at year end"]'::jsonb, 0, 'Under held item H2 capital is depreciated in the year it is spent, and the screen confirms the two columns match year by year: 58.9160 in years 0 and 1, then 0.0000 from year 2.'),
  ('refinery', 'advanced', 'final', null, 42, 'What does attributeVariance do with money that moved with no barrels?', '["It folds it into the line''s volume variance.", "It shows it in its own column, the unexplained.", "It spreads it over the line''s price variance.", "It drops it from every total on margin."]'::jsonb, 1, 'The engine keeps it in the unexplained column: 212000.00 on the Forcados line as recorded, and -212000.00 in the headline row on margin. The volume and price variances take none of it: the Forcados line reads -30720000.00 and 0.00 on those two.');
