-- ============================================================================
-- PD5 EXPERT DEEP SEED: Gas Well Performance, advanced tier.
--
-- Six modules, 26 lessons, 132 questions (15 per module bank plus a 42
-- question final exam). The structure row is GENERATED from the tier's
-- manifest.json rather than hand typed.
--
-- What this tier owns: WHAT THE DESIGN HIDES OR WHAT BREAKS IT. Five of its
-- six graded fields are quantities the design report never prints, and the
-- sixth is the one place the engine and its own oracle disagree.
--
-- CHOSEN ONCE, USED EVERYWHERE. recommendCorrelation takes ONE argument, a
-- wellhead pressure, and switches at a 1000 psia limit. The capstone wellhead
-- is 999.62 psia, so the well is recommended the UNADJUSTED equation by four
-- tenths of a psi, and that recommendation is then applied at a shoe sitting
-- at 2.26 times the limit. The adjustment is exactly 1.2 on every critical
-- rate, so the arithmetic is trivial and the consequence is not: on this well
-- it is the difference between a 2.750 in workover string and a 2.323 in one.
-- The reason string also calls whatever pressure it is handed a "wellhead",
-- and it PRINTS THE THRESHOLD IT JUST CLEARED, because the message is
-- formatted with Math.round: at 999.62 psia it reads "At 1000 psia wellhead".
--
-- A SIZING RETURNS ONE ANSWER AND DISCARDS THE REST. `largestUnloaded` is the
-- first row that clears, and the rejected rows are the rest of the object. On
-- this well the rejected 2.922 in candidate misses by 2.99 percent. A pick
-- that clears in its second decimal and a pick that clears twice over are the
-- SAME FIELD, and only the rows say which one you are holding. The function
-- gained an `ok` key at engines 5733550 for exactly this reason: a null
-- `largestUnloaded` had been carrying two different meanings with one value.
--
-- THE ONE SEAM THE GATE ITSELF RECORDS, AND IT IS GRADED HERE. The slug
-- hydrostatic term carries the platform's ROUNDED 0.433 psi/ft per unit of
-- specific gravity where the oracle uses rho g exactly, 0.4335275. On the
-- capstone slug that is 78.232275 psi against 78.327582, 0.1218 percent apart
-- and 1,162 TIMES the graded tolerance. It is the only graded value in this
-- course a learner can reach with a hand calculation, and doing it by hand
-- with the textbook gradient FAILS. The gate loosens exactly that one
-- assertion to 5e-3 relative and pins the constant.
--
-- TWO FAILS-OPEN, BOTH RECORDED RATHER THAN FIXED BECAUSE plungerLift FEEDS A
-- LIVE SUITE APPLICATION.
--
--   THE GAS REQUIREMENT FALLS AS THE WELL GETS WEAKER, which is the wrong
--   direction. The cycle gas is evaluated between the casing pressure and the
--   pressure still needed at the top of the rise, so when the casing cannot
--   reach the requirement the average runs BACKWARDS and the number keeps
--   coming. The same well at 745, 288 and 96 psia of casing needs 9,306.7,
--   5,362.8 and 3,705.9 scf/bbl, and at BOTH 288 and 96 psia the gas test
--   TURNS TRUE on a well whose casing cannot move the plunger at all.
--
--   AND THE LONGEST LIFTABLE SLUG CLAMPS TO ZERO INSTEAD OF REFUSING. The same
--   well at 96 psia reports 0 ft, which reads as "the longest slug is nothing"
--   when the truth is that the plunger will not move at all. A refusal wearing
--   a number is worse than an error, because it is quotable.
--
-- WHAT NOBODY CHECKS, AND THE TIER ENDS ON IT. A day of cycling this plunger
-- delivers 18.796 bbl/d against the 373.8 bbl/d the well makes, a factor of
-- 19.9. Every pressure and gas test in the screen can pass on an installation
-- that cannot carry the well's liquid, because nothing in the screen ever
-- compares the cycle's DELIVERY to the well's PRODUCTION. `feasible` is a
-- statement about a plunger, not about a well, and the two read alike.
-- ============================================================================

insert into public.academy_course_structures
    (app_slug, tier, structure, content_version)
values ('gaswell', 'advanced', '{"modules":[{"key":"m01-chosen-once-used-everywhere","title":"Chosen Once, Used Everywhere","lesson_keys":["l01-chosen-at-the-wellhead","l02-used-at-the-shoe","l03-what-twenty-percent-is-worth","l04-a-threshold-cleared-by-nothing","l05-what-choosing-per-station-changes"]},{"key":"m02-the-candidate-that-was-discarded","title":"The Candidate That Was Discarded","lesson_keys":["l01-a-sizing-returns-one-answer","l02-the-rejected-string","l03-reading-a-rejection","l04-what-a-pick-hides"]},{"key":"m03-the-gradient-constant","title":"The Gradient Constant","lesson_keys":["l01-a-rounded-constant","l02-what-the-rounding-is-worth","l03-the-same-seam-elsewhere","l04-which-conventions-travel"]},{"key":"m04-a-requirement-that-falls","title":"A Requirement That Falls","lesson_keys":["l01-gas-against-casing-pressure","l02-the-wrong-direction","l03-a-flag-that-flips-the-wrong-way","l04-the-clamp-at-zero","l05-what-feasible-still-catches"]},{"key":"m05-what-nobody-checks","title":"What Nobody Checks","lesson_keys":["l01-liquid-capacity","l02-the-cycle-against-the-well","l03-two-molecular-weights-of-air","l04-a-sizing-at-any-station","l05-what-a-screen-cannot-tell-you"]},{"key":"m06-the-expert-reading","title":"The Expert Reading","lesson_keys":["l01-the-story-so-far","l02-working-the-capstone","l03-onward"]}]}'::jsonb, 1)
on conflict (app_slug, tier) do update
  set structure = excluded.structure,
      content_version = excluded.content_version,
      active = true,
      updated_at = now();

delete from public.academy_quiz_questions
 where app_slug = 'gaswell' and tier = 'advanced';

insert into public.academy_quiz_questions
    (app_slug, tier, scope, module_key, ord, prompt, options, answer_index, explanation)
values
  ('gaswell', 'advanced', 'module', 'm01-chosen-once-used-everywhere', 1, 'recommendCorrelation returns a name and a reason. What decides the name?', '["The pressure together with the depth it was read at, so a shoe reading and a gauge reading are treated differently.", "One pressure, compared strictly against 1000.0 psia.", "The gas density and the interfacial tension at the station, since the droplet balance is what the two names disagree about.", "The critical rate against the supplied gas rate, which is the ratio a loading verdict already computes at that station."]'::jsonb, 1, 'Below the limit it returns coleman and at 1000.0 psia and above turner, and LOADING_ADJUSTMENT then supplies 1.000000 or 1.200000.'),
  ('gaswell', 'advanced', 'module', 'm01-chosen-once-used-everywhere', 2, 'EBOCHA-5 reads 880.0 psia at the gauge and 1500.0 psia at the shoe. What does that pair establish?', '["One well on one day produces both names, because the two pressures sit on opposite sides of the limit.", "The well is transitional, so the function returns an adjustment blended between 1.000000 and 1.200000 by the pressure ratio of 1.70454545.", "The deeper reading is out of range, since the function accepts wellhead pressures only and refuses anything below the hanger.", "Nothing, since the name that comes back is a property of the well rather than a property of one pressure."]'::jsonb, 0, 'The ratio between them is 1.70454545, and the returned object records no pressure at all.'),
  ('gaswell', 'advanced', 'module', 'm01-chosen-once-used-everywhere', 3, 'A caller reads coleman at 880.0 psia and then runs the whole EBOCHA-5 profile under turner. What does the engine do about it?', '["It raises the unknown correlation error, which is the guard that keeps a profile and its recommendation in step.", "It refuses the profile, since loadingProfile checks the correlation it is handed against the recommendation for the first station of the traverse.", "It returns the profile with a warning on every station whose own recommendation differs from the correlation actually used.", "Nothing at all, because the function returns guidance rather than a decision."]'::jsonb, 3, 'The name is advisory, and no returned field anywhere records which pressure produced it.'),
  ('gaswell', 'advanced', 'module', 'm01-chosen-once-used-everywhere', 4, 'Asked at each of the six EBOCHA-5 stations in turn, what does the recommendation return?', '["coleman at every station, because the function was handed the wellhead pressure once and a traverse does not change its answer.", "turner at every station, since the shoe at 1500.0 psia is above the Coleman limit.", "coleman at 880.0 psia and at 978.0 psia, then turner at 1090.0, 1218.0, 1350.0 and 1500.0 psia.", "coleman down to 4500.0 ft, then turner at 6000.0 ft and 7500.0 ft."]'::jsonb, 2, 'The switch lands between 978.0 psia and 1090.0 psia, so four of the six stations would choose the other name.'),
  ('gaswell', 'advanced', 'module', 'm01-chosen-once-used-everywhere', 5, 'Scored under both names at the same rate, where do the six EBOCHA-5 verdicts disagree?', '["At 0.0, 1500.0, 3000.0 and 4500.0 ft, the four stations Coleman reads healthy and Turner reads loading.", "At 6000.0 ft and 7500.0 ft, where the pressures are highest and the adjustment bites hardest.", "Nowhere, since both names control at 7500.0 ft and both call the well loaded.", "At 4500.0 ft alone, whose Coleman ratio of 1.0340528848 sits closest to one."]'::jsonb, 0, 'They agree about the shoe, which loads under both, and part company over the top four stations an operator uses to call the well healthy.'),
  ('gaswell', 'advanced', 'module', 'm01-chosen-once-used-everywhere', 6, 'EBOCHA-5 is loaded under both names. What actually separates the two verdicts?', '["The controlling station, which moves from 7500.0 ft under Coleman up to 6000.0 ft under Turner as more stations cross.", "The margin, -3.80478145 percent under Coleman against -19.83731788 percent under Turner.", "The loaded flag, which reads true under Turner and false under Coleman.", "The critical velocity at the shoe, 6.1224977520 ft/s under both names."]'::jsonb, 1, 'Both control at 7500.0 ft and both read loaded, so the honest reading is that the shoe loads by somewhere between those two figures.'),
  ('gaswell', 'advanced', 'module', 'm01-chosen-once-used-everywhere', 7, 'At 1200.0 psia, 600.0 degR and z 0.9, how far apart are the Turner and Coleman terminal droplet velocities?', '["It is the gap between 7.5969218402 ft/s and 6.3307682001 ft/s, because the adjustment is applied inside the droplet balance rather than after it.", "It cannot be stated, since Coleman publishes no terminal velocity and only the adjusted 7.5969218402 ft/s is defined at that station.", "It is 1.200000, because the two names were fitted to different drag data.", "0.0000e+0 ft/s, since both are 6.3307682001 ft/s on the shared droplet constant of 1.5935346111."]'::jsonb, 3, 'The critical velocities do differ, 7.5969218402 ft/s against 6.3307682001 ft/s, and the whole of that is LOADING_ADJUSTMENT.'),
  ('gaswell', 'advanced', 'module', 'm01-chosen-once-used-everywhere', 8, 'Published row 5 sits at 2500.0 psia and 540.0 degR. What are the two critical rates there?', '["2496.154595078 Mscf/d under Coleman against 2080.128829231 Mscf/d under Turner, since Coleman is the adjusted one.", "The same rate under both, since the rate constant of 3054.38693878 Mscf/d absorbs the adjustment.", "2080.128829231 Mscf/d under Coleman against 2496.154595078 Mscf/d under Turner, a difference of 416.025765846 Mscf/d.", "2080.128829231 Mscf/d under both, the twenty percent showing in velocity alone."]'::jsonb, 2, 'Rate is linear in velocity at a fixed station and area, so a well making exactly the Coleman rate there reads 0.8333333333 under Turner.'),
  ('gaswell', 'advanced', 'module', 'm01-chosen-once-used-everywhere', 9, 'The name is worth 644.522679360 Mscf/d at the EBOCHA-5 controlling station. What should that be read against?', '["The whole spread of critical rate down the hole, 2671.123287413 to 3222.613396799 Mscf/d under Coleman.", "The gas rate of 3100.0 Mscf/d, which the difference is about a fifth of, so the name is worth about a fifth of the well.", "The station increment of 116.116224791 Mscf/d between 6000.0 ft and 7500.0 ft, the only comparison a traverse supports.", "Nothing, since a difference in Mscf/d is a tolerance quoted at the end of a study."]'::jsonb, 0, 'The name moves the answer by more than the entire traverse does, which is why it is a factor rather than a tolerance.'),
  ('gaswell', 'advanced', 'module', 'm01-chosen-once-used-everywhere', 10, 'A well at 999.88 psia once printed a reason naming 1000 psia. What was wrong with that sentence?', '["The branch had fired the wrong way, returning coleman on a pressure sitting at the limit, and the sentence reported that faithfully.", "The branch fires strictly below the limit, so it named a pressure that would have returned turner.", "Nothing was wrong, since 999.88 psia does round to 1000 and the reason is guidance rather than a returned value.", "The pressure was outside the range the function accepts."]'::jsonb, 1, 'Only the display was wrong, and a reader cannot tell a display artefact from a branch that fired the wrong way.'),
  ('gaswell', 'advanced', 'module', 'm01-chosen-once-used-everywhere', 11, 'The reason now carries one decimal. How much of the collision is left?', '["None of it, because a pressure and its limit can no longer render as the same string once a decimal place is carried.", "All of it, since the printed value is still a rounding and a rounding returns something for any input it is handed.", "Anything inside 0.05 psi of the limit still renders as the limit, so 999.96 psia prints 1000.0 while coleman comes back.", "It is 0.9600 psi wide, the distance from 999.04 psia to the limit, which is the closest case the change was tested against."]'::jsonb, 2, 'The collision narrows by ten rather than closing, and 999.96 psia sits 0.0400 psi from the limit.'),
  ('gaswell', 'advanced', 'module', 'm01-chosen-once-used-everywhere', 12, 'The message fix replaced a rounding with fixed-decimal formatting. What did that break?', '["It moved the branch, since formatting to one decimal carries 999.96 psia onto the turner side of the comparison.", "It removed the station from the sentence, which then had to be handed back as a caller argument in a second change.", "Nothing, because a change that touches only a message cannot change what a function computes.", "It turned a quiet nonsense reading into a crash, because the formatter throws where the rounding returned something."]'::jsonb, 3, 'A formatting change is safe only where the values reaching the formatter were already checked, and a guard had to be added before the format.'),
  ('gaswell', 'advanced', 'module', 'm01-chosen-once-used-everywhere', 13, 'At 1500.00 psia the sentence can say wellhead or can name a 7,500 ft shoe. What decides which?', '["The caller, since the station is an argument handed in rather than something the function works out.", "The pressure, because a reading above the Coleman limit can only have come from a deep station and the function says so.", "The name returned, with turner printing a shoe label and coleman printing a wellhead label.", "The traverse, which loadingProfile passes down so every recommendation carries the depth of its own station."]'::jsonb, 0, 'It hardcoded the word wellhead for whatever station it was handed, which matters because a name chosen at 880.0 psia prices a droplet at 1500.0 psia.'),
  ('gaswell', 'advanced', 'module', 'm01-chosen-once-used-everywhere', 14, 'Choosing per station rather than once at the gauge moves the shallowest loading station on EBOCHA-5 where?', '["From 6000.0 ft to 7500.0 ft, with turner applied at the deepest station only.", "From 6000.0 ft to 3000.0 ft, since the top two stations keep coleman and the bottom four take turner.", "Nowhere, since the controlling station is 7500.0 ft under both names.", "From 6000.0 ft to 1500.0 ft, the shallowest station still recommending coleman."]'::jsonb, 1, 'The recommendation is coleman at 880.0 psia and 978.0 psia and turner from 1090.0 psia down, so two stations read one way and four the other.'),
  ('gaswell', 'advanced', 'module', 'm01-chosen-once-used-everywhere', 15, 'What does a mixed profile put between 1500.0 ft and 3000.0 ft that a single-correlation profile does not?', '["A crossing, since the ratio passes through one between those two stations as soon as the correlation changes.", "A rise of 108.952764374 Mscf/d, which is in line with the increments on either side of it.", "A step, from a Coleman critical rate of 2771.653428599 Mscf/d to a Turner critical rate of 3456.727431568 Mscf/d.", "Nothing visible, because the critical rate rises down the hole under either name and the ratio falls 0.0423035811 there in both cases."]'::jsonb, 2, 'Nothing physical changes at 1000.0 psia, so a discontinuity there invites a reader to look for a mechanism at that depth.'),
  ('gaswell', 'advanced', 'module', 'm02-the-candidate-that-was-discarded', 1, 'sizeTubingForRate returns rows, largestUnloaded and ok. What is largestUnloaded?', '["A separate optimisation over the candidate list, which weighs each diameter''s ratio against the workover cost of running it.", "The diameter whose ratio sits furthest above one.", "One line out of rows, namely the first row walking largest diameter first whose ratio reaches one.", "The smallest diameter that unloads the well at the supplied rate."]'::jsonb, 2, 'It is 3.476 in at 1.0022156322 on the EBOCHA-5 list, and every row below the pick was scored and rejected for being smaller.'),
  ('gaswell', 'advanced', 'module', 'm02-the-candidate-that-was-discarded', 2, 'The Coleman pick reads 1.0022156322 and the next candidate down reads 1.2865006128. Why does that matter to a reader of largestUnloaded alone?', '["largestUnloaded is the same field in both cases, so a pick with no margin in it is reported exactly like a comfortable one.", "It does not, since the ratio is on the row and comes back with the pick.", "Because the function warns when a pick clears in its fourth decimal.", "Because 1.0022156322 sits inside the twenty percent the two names differ by."]'::jsonb, 0, 'A pick that barely reaches one is a workover recommendation with no margin in it, and only the row says so.'),
  ('gaswell', 'advanced', 'module', 'm02-the-candidate-that-was-discarded', 3, 'Size the EBOCHA-5 candidate list for 40.0 Mscf/d. What comes back?', '["1.610 in, the smallest candidate, since a narrower string always carries more velocity.", "largestUnloaded is null at a best ratio of 0.0502326405, so the function names no winner rather than returning the least bad candidate.", "An error on every row, because that rate leaves the actual velocity outside the balance.", "The current 3.548 in string, which the list falls back to when nothing clears."]'::jsonb, 1, 'It also refuses to invent a candidate below 1.610 in, so the list it was given is the list it answers from.'),
  ('gaswell', 'advanced', 'module', 'm02-the-candidate-that-was-discarded', 4, 'The critical velocity is 6.1224977520 ft/s on all nine Coleman rows. What follows from that?', '["It follows that the list was scored at one rate, and the critical velocity would differ per candidate at any other.", "It follows that the correlation was held fixed, and the velocity would move down the list under the other name.", "It follows that the droplet constant was recomputed nine times.", "Any comparison between candidates is a comparison of areas dressed up as a comparison of ratios."]'::jsonb, 3, 'The actual velocity climbs from 4.7325778044 ft/s on 3.958 in to 28.6020782357 ft/s on 1.610 in while the number it must beat never moves.'),
  ('gaswell', 'advanced', 'module', 'm02-the-candidate-that-was-discarded', 5, 'Run the same nine candidates at the same station under Turner. Which single candidate changes its verdict?', '["3.476 in, the pick under Coleman at a ratio of 1.0022156322 and a rejection under Turner at 0.8351796935.", "3.548 in, the current string, whose own rejection at 0.9619521855 is nearest the line.", "3.068 in, which moves from a rejection under Coleman to the pick under Turner.", "Every candidate, since each ratio is divided by 1.200000 in the crossing."]'::jsonb, 0, 'The ratio it loses is 0.1670359387, which is 16.666667 percent of it, and every other row keeps its answer under both names.'),
  ('gaswell', 'advanced', 'module', 'm02-the-candidate-that-was-discarded', 6, 'Under Turner every candidate ratio on the list is lower than under Coleman. Where does the adjustment land?', '["In the numerator, because Turner raises the actual velocity a string produces by 1.200000.", "On both sides at once, which preserves the ordering and leaves the ratios unchanged.", "In the denominator, on the critical rate.", "On the flow area, which the adjustment scales before a critical rate is formed at all."]'::jsonb, 2, 'That is the twenty percent appearing as a fall rather than a rise, and 3.476 in loses 16.666667 percent of its ratio in the crossing.'),
  ('gaswell', 'advanced', 'module', 'm02-the-candidate-that-was-discarded', 7, '3.548 in is rejected at 0.9619521855 at the controlling station. What else is that number?', '["A hypothetical, since the sizing scores 3.548 in as a candidate rather than as the tubing in the hole.", "The well''s own loading ratio at the shoe, since the profile and the sizing run one calculation.", "A different quantity that happens to agree, the profile using a traverse pressure and the sizing a candidate area.", "The margin the well has left, reported separately as -3.80478145 percent."]'::jsonb, 1, 'A sizing at the controlling station therefore contains the loading verdict, and a rejection matching the current string says the well is loading now.'),
  ('gaswell', 'advanced', 'module', 'm02-the-candidate-that-was-discarded', 8, 'Do the four Coleman rejections rank the candidates by anything about this well?', '["Yes, they rank by how far each candidate sits from the critical velocity of 6.1224977520 ft/s at that station.", "Yes, they rank by the critical rate each one carries.", "No, they rank by the adjustment, reversing under Turner.", "No, they rank by area, an ordering fixed before any of the physics runs."]'::jsonb, 3, 'The ordering survives the crossing, since Turner divides all four by the same factor: 0.6441512920, 0.6893654772, 0.7214334210 and 0.8016268212.'),
  ('gaswell', 'advanced', 'module', 'm02-the-candidate-that-was-discarded', 9, 'A candidate is rejected by the sizing. What does its row say about why?', '["It names the constraint in the ok field, which reads false on a rejected row and true on the row that becomes the pick.", "It carries a loaded flag and a warning list, so a reader can see whether the rejection was on velocity or on area.", "Only the ratio, with no field for the binding constraint and no rate that would have made it pass.", "It records the station its pressure came from."]'::jsonb, 2, 'A rejection also says nothing about erosional velocity or pressure drop, so a candidate that unloads is not thereby one you should run.'),
  ('gaswell', 'advanced', 'module', 'm02-the-candidate-that-was-discarded', 10, 'Two of the four station-and-correlation runs on EBOCHA-5 return 3.476 in. How does that happen?', '["Because 3.476 in is the current string, and the function returns the tubing already in the hole whenever it clears.", "From opposite errors, the controlling station under Coleman and the wellhead under Turner.", "Because the station and the correlation move the pick the same way.", "Because the candidate list is too coarse to separate them."]'::jsonb, 1, 'The shoe under Coleman picks it at 1.0022156322 and the wellhead under Turner picks it at 1.0076140183.'),
  ('gaswell', 'advanced', 'module', 'm02-the-candidate-that-was-discarded', 11, 'Change the correlation and a reviewer sees it in the return value. Change the station and nobody does. Why?', '["Every row names its correlation and its adjustment, while the object as a whole names no depth at all.", "Because a wrong correlation moves the pick further than a wrong station does.", "Because the station reaches the row through its pressure and temperature fields.", "Because ok reads false on a run taken away from the controlling station."]'::jsonb, 0, 'Pressure and temperature survive only inside the density they produced, so the wrong run is not optimistic in any visible way, it is unmarked.'),
  ('gaswell', 'advanced', 'module', 'm02-the-candidate-that-was-discarded', 12, 'Sized at the wellhead under Coleman the list returns 3.740 in against a current string of 3.548 in. What does the study then report?', '["That no workover is needed, while the well loads over the bottom 40.0000 percent of its tubing.", "That the current string is one size too large, which is the same conclusion the controlling station reaches.", "That the sizing could not be evaluated, a pick above the current string being the signal for a wrong station.", "That a workover to 3.740 in would raise the actual velocity."]'::jsonb, 0, 'The current string reads 1.1605604334 at the wellhead and 0.9619521855 at the controlling station, and nothing in the return marks the difference.'),
  ('gaswell', 'advanced', 'module', 'm02-the-candidate-that-was-discarded', 13, 'The controlling point of a profile already carries pPsia 1500.0, tempR 653.67, z 0.9142643742, idIn 3.548 and depthFt 7500.0. What does the sizing do with it?', '["It reads the controlling point directly, which is why the profile and the sizing agree at 0.9619521855 on the current string.", "It compares the idIn against the list and marks the current string.", "It uses depthFt to label each row it returns.", "Nothing, unless a caller hands it over, since the function refuses to guess a station and refuses to warn about one."]'::jsonb, 3, 'It also will not compare its pick to the string already in the well, since 3.548 in reaches it only as another candidate.'),
  ('gaswell', 'advanced', 'module', 'm02-the-candidate-that-was-discarded', 14, 'What has to be printed beside a recommended tubing size for a reader to see the recommendation was contingent?', '["The ratio of the pick, which shows how much of the threshold the recommendation had in hand.", "The full candidate list with every ratio, which already carries the correlation on each row.", "The correlation and the pressure it was chosen at.", "The adjustment of 1.0000 or 1.2000, the whole of the difference between the two names."]'::jsonb, 2, 'The name is recoverable from the rows, and the pressure that chose the name is recorded nowhere at all.'),
  ('gaswell', 'advanced', 'module', 'm02-the-candidate-that-was-discarded', 15, 'The list puts 1.610 in at a ratio of 4.6716355635. Is that the best candidate?', '["Yes, since the objective is the ratio and that is the largest one the list produces.", "No, only the one with the most area taken out.", "No, since a ratio that far above one is outside the range the correlation was fitted on.", "No, since the walk stops largest first and never reaches it, so it was rejected."]'::jsonb, 1, 'Nothing on a row prices pressure drop or erosional velocity, and the pick of 3.476 in clears at 1.0022156322 with far more area left.'),
  ('gaswell', 'advanced', 'module', 'm03-the-gradient-constant', 1, 'What is 0.4335275040010 psi/ft per unit SG built from?', '["A fit to fresh water density over the temperature range a plunger well sees.", "62.4 lbm/ft3 divided by 144, the field-unit route to the same gradient.", "A calibration of the balance against the oracle''s 88.4396108162 psi.", "One thousand kilograms per cubic metre times g, carried through 0.3048 m per ft and then 6894.757293168 Pa per psi."]'::jsonb, 3, 'The chain runs 9806.650000 Pa/m then 2989.066920 Pa/ft, with no sample, no temperature and no salinity anywhere in it.'),
  ('gaswell', 'advanced', 'module', 'm03-the-gradient-constant', 2, 'How big is the gap between the shipped 0.4330000000000 and the exact value?', '["It cannot be stated as one figure, because the gradient depends on the specific gravity of the liquid the slug is made of.", "0.0005275040010 psi/ft per unit SG, which is 0.1216771707 percent of the exact value.", "0.4333333333333 psi/ft per unit SG less the shipped value.", "0.0005275040010 psi/ft per unit SG, shrinking as the slug lengthens."]'::jsonb, 1, 'Exact over rounded is 1.0012182540439, a fixed percentage that never cancels and never grows relative to what it sits on.'),
  ('gaswell', 'advanced', 'module', 'm03-the-gradient-constant', 3, 'Across a slug sweep from 120.0 ft to 480.0 ft at 1.06 SG, which column never moves?', '["The cost stated in percent, which reads 0.1216771707 on all seven rows.", "The cost in psi, which is a property of the constant rather than of the slug it sits on.", "The exact gradient answer, pinned at 0.4335275040010 psi/ft per unit SG.", "The ratio of the two answers, tending toward one."]'::jsonb, 0, 'The cost grows with the slug, 0.0670985089 psi at 120.0 ft against 0.2683940357 psi at 480.0 ft, because it is length times gravity times a fixed increment.'),
  ('gaswell', 'advanced', 'module', 'm03-the-gradient-constant', 4, 'Why is a cost quoted in psi a statement about one well and a cost in percent a statement about the engine?', '["The psi carries the whole balance, since the lift pressure is a sum of five terms and one is hydrostatic.", "The percent is the same on every well and the psi is rounded to the precision of its own case.", "The psi divides back to the slug that produced it.", "The psi is measured and the percent is derived, so only the percent can be checked."]'::jsonb, 2, 'Divide 0.2012955268 psi by the fixed fraction and by 1.06 and the 360.0 ft slug comes back out of it.'),
  ('gaswell', 'advanced', 'module', 'm03-the-gradient-constant', 5, 'The rounding is 0.1216771707 percent. What is that a percentage of?', '["Every quantity the plunger module returns, since the constant enters at the door.", "The hydrostatic head alone, and not of the lift pressure, the gas per cycle or the maximum slug length.", "The required lift pressure, where it shows as 0.04763796 percent.", "The slug length, which the constant multiplies first."]'::jsonb, 1, 'On the published case it is 0.04763796 percent of the lift pressure, because the hydrostatic term is only one term of five.'),
  ('gaswell', 'advanced', 'module', 'm03-the-gradient-constant', 6, 'Which of the five terms of the published required lift pressure carries the rounded gradient?', '["The slug hydrostatic and the gas column of 16.2440440692 psi, both being pressures built from a density.", "The slug hydrostatic and the plunger weight of 1.2821115429 psi.", "All five, since the sum of 225.8581556122 psia is formed afterwards.", "The slug hydrostatic of 88.3320000000 psi, and none of the other four."]'::jsonb, 3, 'A line pressure of 120.0000000000 psi, the plunger weight, the gas column and a friction term of 0.0000000000 psi carry none of it.'),
  ('gaswell', 'advanced', 'module', 'm03-the-gradient-constant', 7, 'The ESP defence of 0.433 is that both ends of every comparison are built from it. Why does that not license the constant here?', '["The 225.8581556122 psia is compared against a casing of 600.0 psia, which came from a gauge.", "Because plungerLift rounds to 0.433 where the other route carries 0.4333333333333, so the two biases differ in size.", "Because a plunger slug is longer than an ESP stage, so the absolute cost in psi stops being negligible.", "Because the constant enters the balance twice and the two do not cancel."]'::jsonb, 0, 'Nothing cancels when only one side holds the bias, and it survives into the verdict at 0.1076454958 psi.'),
  ('gaswell', 'advanced', 'module', 'm03-the-gradient-constant', 8, 'The gate pins PSI_PER_FT_SG to 0.433 exactly and loosens the slug assertion to a relative tolerance of 5e-3. What does that combination do?', '["It records the disagreement as a defect, which is what a loosened assertion is for.", "It removes the disagreement, the pin and the loosening cancelling each other.", "It protects the constant from change with the same suite that already knows the constant is wrong.", "It leaves the constant free to change within 5e-3 of the oracle."]'::jsonb, 2, 'The tolerance is 4.109234 times the disagreement it covers, and a test asserting a constant equals its current value is one a correction has to break.'),
  ('gaswell', 'advanced', 'module', 'm03-the-gradient-constant', 9, 'The published golden carries 88.4396108162 psi for a 200.0 ft slug of 1.02 SG liquid. What does the shipped engine return?', '["88.4396108162 psi, since the gate would fail otherwise and the gate passes today.", "88.3320000000 psi, lower by 0.1076108162 psi.", "88.3320000000 psi, which the oracle also returns once its SI answer is converted.", "No hydrostatic at all, the engine reporting only the summed lift pressure."]'::jsonb, 1, 'The golden publishes a number the shipped engine cannot produce, and the disagreement is accommodated rather than hidden.'),
  ('gaswell', 'advanced', 'module', 'm03-the-gradient-constant', 10, 'How many values stand for one water gradient in this codebase, and which has a derivation behind it?', '["Three, and only 0.4335275040010 psi/ft per unit SG is derived rather than rounded.", "Two, the shipped constant and the exact conversion, 62.4 over 144 being the same number written differently.", "Three, and 0.4333333333333 psi/ft per unit SG is the derived one.", "One, since espDesign reads its gradient from plungerLift."]'::jsonb, 0, '62.4 lbm/ft3 over 144 gives 0.4333333333333, the shipped constant is 0.4330000000000, and only the pascal route has no rounding in it.'),
  ('gaswell', 'advanced', 'module', 'm03-the-gradient-constant', 11, 'What does changing PSI_PER_FT_SG in plungerLift alone accomplish?', '["It fixes the domain, since espDesign reads the same constant and inherits the correction.", "It breaks the gate, which pins the constant, and that is the whole of the cost.", "It removes the seam entirely.", "It leaves three values in circulation and only moves where they sit."]'::jsonb, 3, 'The same rounded 0.433 sits in espDesign beside an exact 62.4 over 144, so a decision about a constant in three places is a decision about one place.'),
  ('gaswell', 'advanced', 'module', 'm03-the-gradient-constant', 12, 'gasWellLoading carries 28.9647 for the molecular weight of air and gasProperties carries 28.9625. How far apart are the densities they give at 2500.0 psia and 620.0 degR?', '["0.002200 lbm/ft3, the difference in the weights carried straight through.", "Nothing, since both use the same R of 10.7316 and the same z.", "5.970042e-4 lbm/ft3 apart, which is a fraction of 7.595452e-5 of the density itself.", "75.9603 lbm/ft3, the parts per million read as a density."]'::jsonb, 2, 'One route gives 7.8600213238 lbm/ft3 and the other 7.8594243196 lbm/ft3, against an oracle value of 7.8600381043 lbm/ft3.'),
  ('gaswell', 'advanced', 'module', 'm03-the-gradient-constant', 13, 'Both molecular weights are invisible inside their own module. Where does the cost appear?', '["At the seam, where a density from one module feeds a velocity in the other.", "At the door, where one module takes degR and the other degF, which is where the conversion loses precision.", "In the oracle comparison, which only one route can match.", "Nowhere, since 75.9603 parts per million is below reporting precision."]'::jsonb, 0, 'Each side is correct by its own arithmetic, so the symptom when the seam opens is two right answers parting at the fifth decimal.'),
  ('gaswell', 'advanced', 'module', 'm03-the-gradient-constant', 14, 'A user compares this engine''s lift pressure against one built on an exact gradient. What can the return value tell them?', '["The gradient used, which appears beside the slug hydrostatic in the returned lift breakdown.", "Nothing about the gradient, since no field names it and no warning says it is rounded.", "That the difference is 0.04763796 percent, which the module reports as the tolerance on its own answer.", "That one used a different constant, since the friction term would differ."]'::jsonb, 1, 'A convention absent from a return value is enforced by the reader, and nothing in either module declares its own.'),
  ('gaswell', 'advanced', 'module', 'm03-the-gradient-constant', 15, 'One station is 620.0000 degR or 160.3300 degF depending on which module it enters. What is wrong with that?', '["The conversion is only approximate, so a station handed to one module and then the other comes back changed.", "degF cannot carry a real-gas density, so gasProperties returns 0.0545793356 psi/ft instead.", "Nothing arithmetically, and it is still two conventions.", "It puts the two modules on different absolute scales, so one station gives two z values."]'::jsonb, 2, 'gasProperties.toRankine hands back 620.0000 degR exactly, and each module is right while neither knows the other exists.'),
  ('gaswell', 'advanced', 'module', 'm04-a-requirement-that-falls', 1, 'The OGUTA-2 required lift pressure of 248.1897322873 psia is a sum of five terms. Which of them moves when the casing is walked from 900.0 psia down to 90.0 psia?', '["The gas column term of 28.0007131786 psi, which follows the casing pressure down.", "The slug hydrostatic of 73.4368000000 psi, because a lower casing pressure lets the 160.0 ft slug settle and lengthen before the rise begins.", "Not one of them, because the requirement is a static force balance the casing never enters.", "The plunger weight term of 1.7522191087 psi, a pressure that scales with the casing."]'::jsonb, 2, 'The requirement holds at 248.1897322873 psia across the whole sweep, so only the casing end of the expansion moves and the required ratio falls with it.'),
  ('gaswell', 'advanced', 'module', 'm04-a-requirement-that-falls', 2, 'How does gasPerCycleScf turn a casing pressure of 720.0 psia and a requirement of 248.1897322873 psia into 8854.756635640 scf?', '["It averages the two ends at 484.09486614 psia and expands the cycle volume at that one mean pressure.", "It integrates the real gas law down the tubing, so the z at each depth enters.", "It works from the casing pressure alone, the gas actually vented in behind the plunger.", "It works from the difference of 471.8102677127 psi, the pressure left to do the work."]'::jsonb, 0, 'The mean of the two ends is the whole of the model, which is why a number still comes back after the casing falls under the requirement.'),
  ('gaswell', 'advanced', 'module', 'm04-a-requirement-that-falls', 3, 'The screen refuses a zero plunger weight, a zero slug, a zero tubing diameter and a zero average temperature by name. Which condition is not on that list?', '["A slug longer than the tubing, which the module accepts and silently truncates to the tubing length before it averages the two ends.", "A zero line pressure, which would leave the top of the expansion meaningless and is caught by the same guard that catches the zero slug.", "A casing pressure below the line pressure of 145.0000000000 psi.", "Whether the casing stands above the pressure the cycle has to reach."]'::jsonb, 3, 'The expansion direction is never established, so the averaging happens either way and 8854.756635640 scf comes back either way.'),
  ('gaswell', 'advanced', 'module', 'm04-a-requirement-that-falls', 4, 'Between 900.0 psia and 90.0 psia of casing the OGUTA-2 required gas-liquid ratio falls by 7999.00100588 scf/bbl. What share of the starting value is that?', '["90.000000 percent, in step with the casing pressure, which falls from 900.0 psia to 90.0 psia over the same sweep.", "70.545832 percent.", "It cannot be stated as a share, because everything below 285.0 psia is an artefact and the two ends are not the same quantity.", "A little over half of it, since the requirement is linear in the casing pressure and only half of the balance moves with it."]'::jsonb, 1, 'It runs from 11338.72941173 scf/bbl to 3339.72840586 scf/bbl, which is not the tenfold fall the casing itself made.'),
  ('gaswell', 'advanced', 'module', 'm04-a-requirement-that-falls', 5, 'Which part of the OGUTA-2 casing sweep is defensible physics rather than an artefact?', '["None of it, since a requirement that falls as a well weakens is wrong at every point on the column and no part of it can be quoted.", "Only the single row at 900.0 psia, the one casing pressure on the sweep where the expansion still has real headroom to work with.", "The rows from 900.0 psia down to 285.0 psia.", "The rows below the crossing, where the small average of the two ends is what a dying well can actually be expected to deliver."]'::jsonb, 2, 'Less casing pressure genuinely means less gas expanded per cycle, and the average runs 574.09486614 psia at 900.0 psia against 266.59486614 psia at 285.0 psia.'),
  ('gaswell', 'advanced', 'module', 'm04-a-requirement-that-falls', 6, 'Which pair of adjacent rows on the OGUTA-2 sweep straddles the point where the expansion stops running the right way?', '["285.0 psia and 240.0 psia.", "400.0 psia and 320.0 psia, the pair across which glrOk changes and the only place anything in the returned object moves at all.", "180.0 psia and 130.0 psia, the pair across which the longest slug the balance can lift stops being a solution and is clamped.", "900.0 psia and 720.0 psia, since the requirement stands above what the well makes across that whole span of casing pressure."]'::jsonb, 0, 'Casing less requirement is 36.81026771 psi at 285.0 psia and -8.18973229 psi at 240.0 psia, and the ratio column crosses with no break in slope.'),
  ('gaswell', 'advanced', 'module', 'm04-a-requirement-that-falls', 7, 'At which casing pressure does glrOk on OGUTA-2 first read true, and is that row an artefact?', '["240.0 psia, and it is an artefact, since that is the first row on the sweep where casing minus requirement turns negative.", "320.0 psia, and it is not, because the casing still clears the requirement by 71.81026771 psi.", "90.0 psia, and it is an artefact, because the flag only turns true once the requirement has fallen the full 70.545832 percent.", "320.0 psia, and it is an artefact, since the flag is tracking an average."]'::jsonb, 1, 'The required ratio there has genuinely dropped under the 5900.0 scf/bbl the well makes, and feasible reads true on a living well.'),
  ('gaswell', 'advanced', 'module', 'm04-a-requirement-that-falls', 8, 'The insufficientGas warning fires on OGUTA-2 at 720.0 psia of casing and is gone at 90.0 psia. What changed?', '["The well recovered the gas-liquid ratio the cycle asks for.", "The warning was suppressed by slowCycle, which takes precedence in the returned list once a cycle can no longer complete a trip.", "pressureOk turned false, and the module drops its gas warnings once the pressure check has already failed on the same case.", "The requirement fell under the 5900.0 scf/bbl the well makes."]'::jsonb, 3, 'It went from 9561.17363265 scf/bbl to 3339.72840586 scf/bbl, and the warning fires on the requirement rather than on the verdict.'),
  ('gaswell', 'advanced', 'module', 'm04-a-requirement-that-falls', 9, 'On OGUTA-2 feasible reads false at 900.0 psia of casing and false again at 90.0 psia. Why?', '["The required gas-liquid ratio stands above the 5900.0 scf/bbl the well makes at both ends of the sweep and at every row between them.", "feasible carries a third check on the liquid a cycle brings up, and that check fails here.", "pressureOk picked up what glrOk dropped, since feasible is the conjunction of those two flags.", "The casing lies outside the band the screen accepts at both ends of the sweep."]'::jsonb, 2, 'At 900.0 psia pressureOk is true and glrOk false, at 90.0 psia the reverse, and nothing ships a wrong verdict today by arithmetic rather than by design.'),
  ('gaswell', 'advanced', 'module', 'm04-a-requirement-that-falls', 10, 'What single number makes the OGUTA-2 verdict at 720.0 psia of casing reproducible for a reader?', '["The average expansion pressure of 484.09486614 psia, the one quantity that is built from the casing and the requirement together.", "The margin of 471.8102677127 psi between the casing and the required lift pressure.", "The required gas-liquid ratio of 9561.17363265 scf/bbl, which the insufficientGas warning already quotes in full beside the verdict.", "The gas per cycle of 8854.756635640 scf, which carries both ends inside it."]'::jsonb, 1, 'The sign of casing minus required lift decides whether the gas number is worth reading, and an average of the two ends destroys that sign.'),
  ('gaswell', 'advanced', 'module', 'm04-a-requirement-that-falls', 11, 'maxSlugLengthFt returns 0.00000000 ft for OGUTA-2 at 130.0 psia of casing. What is that zero?', '["A clamp on a balance with no solution, since with no slug at all the well is short by 45.3101604102 psi.", "The longest slug this well can lift, which is nothing at all.", "The unclamped -99.47404299 ft rounded up to the reporting floor.", "The value returned for any casing under the line pressure of 145.0000000000 psi."]'::jsonb, 0, 'Zero is a refusal wearing a number, and the shortfall in psi is the answer worth quoting in its place.'),
  ('gaswell', 'advanced', 'module', 'm04-a-requirement-that-falls', 12, 'At 4000.0 psia of casing maxSlugLengthFt on OGUTA-2 returns 8200.00000000 ft. What is that?', '["The longest slug the balance can lift at that casing pressure, which happens on this well to coincide with the tubing depth exactly.", "A refusal, since the function returns the tubing length when no solution exists.", "The depth at which the required lift pressure would come to 4000.0 psia.", "The tubing depth, since the unclamped solution of 8396.73393481 ft was longer than the hole."]'::jsonb, 3, 'That is a depth rather than a computed maximum, and a caller checking the return against the tubing gets equality rather than a signal.'),
  ('gaswell', 'advanced', 'module', 'm04-a-requirement-that-falls', 13, 'maxSlugLengthFt returns NaN when the net cost of a foot of slug is not positive. What does that say about the two clamps in the same function?', '["NaN is simply the third clamp, so all three ends of the range are in fact handled by the function in one consistent way.", "The NaN is the defect and the clamps are the correct behaviour.", "The author already decided what refusal looks like and then did not use it at either end.", "The cases differ in kind, since a light liquid is an input error."]'::jsonb, 2, 'One refusal and two clamps sit in one function for one kind of question, which is why the clamp is not a matter of principle.'),
  ('gaswell', 'advanced', 'module', 'm04-a-requirement-that-falls', 14, 'A foot of slug on OGUTA-2 costs 0.455497324232 psi net. What has been netted out of it?', '["The plunger weight term of 1.7522191087 psi, spread over the 160.0 ft slug.", "A gas column of 0.003482675768 psi/ft, from a gas density of 0.5015053107 lbm/ft3 at line pressure.", "The friction on the tubing wall, carried here at 0.0000000000 psi.", "The casing pressure standing behind the plunger through the rise."]'::jsonb, 1, 'It is 0.433 times the 1.060 liquid gravity less that gas column, and the plunger weight is a fixed term rather than a cost per foot.'),
  ('gaswell', 'advanced', 'module', 'm04-a-requirement-that-falls', 15, 'pressureOk on OGUTA-2 is a static comparison. What does that leave out?', '["Velocity, gas slippage past the plunger, fallback of the slug during the rise, and friction unless it is handed in.", "The line pressure of 145.0000000000 psi, which reaches the gas expansion only and never the force balance.", "The slug hydrostatic of 73.4368000000 psi, which is a moving term computed during the rise itself.", "The plunger weight, which is held as a mass rather than as a pressure and cannot enter a static sum."]'::jsonb, 0, 'The balance is a sum of pressures at one instant, so nothing about the trip up the hole reaches it and the 471.8102677127 psi margin is a standing figure.'),
  ('gaswell', 'advanced', 'module', 'm05-what-nobody-checks', 1, 'screenPlungerLift returns liquidPerDayBbl. What is it compared against?', '["Nothing, since feasible is built from pressureOk and glrOk and nothing else.", "The well liquid make, which the screen forms from the gas rate and the gas-liquid ratio it was already handed.", "The liquid per cycle of 0.9261160790 bbl, a timing consistency check.", "The rule of thumb ratio, the one liquid check the screen makes."]'::jsonb, 0, 'On OGUTA-2 the cycle carries 14.83375148 bbl/d against a well liquid make of 194.91525424 bbl/d, and neither flag knows it.'),
  ('gaswell', 'advanced', 'module', 'm05-what-nobody-checks', 2, 'OGUTA-2 makes 1150.0 Mscf/d at 5900.0 scf/bbl. How does its liquid make stand against the cycle?', '["1150.0 Mscf/d against 141.82807355 Mscf/d, the comparison being on gas.", "5900.0 scf/bbl against a required 9561.17363265 scf/bbl.", "194.91525424 bbl/d against 14.83375148 bbl/d, which is a shortfall of 180.08150275 bbl/d.", "0.9261160790 bbl a trip against 16.01716223 trips a day."]'::jsonb, 2, 'The well makes 13.13998380 times what the cycle carries, and the ingredients of that ratio are both returned keys.'),
  ('gaswell', 'advanced', 'module', 'm05-what-nobody-checks', 3, 'Had the gas cleared on OGUTA-2, what would feasible have read?', '["false still, because feasible carries a liquid check the gas flag was masking.", "true, with 180.08150275 bbl/d of liquid a day going nowhere.", "true, and correctly so, since a plunger clearing the balance and the ratio keeps a well unloaded.", "Unchanged, pressureOk being the binding flag."]'::jsonb, 1, 'feasible is pressureOk and glrOk, and on this well pressureOk is true while glrOk is false.'),
  ('gaswell', 'advanced', 'module', 'm05-what-nobody-checks', 4, 'Is the missing liquid comparison an artefact of a teaching well?', '["Yes, since OGUTA-2 was designed with a slug small enough to make the gap visible.", "It cannot be told, the published case carrying no well gas-liquid ratio and no gas rate.", "No, but the published case closes the gap at 20.58236937 trips a day.", "No, the published case at a derived 4500.0 scf/bbl and 700.0 Mscf/d carries 23.82707902 bbl/d against a well make of 155.55555556 bbl/d."]'::jsonb, 3, 'The well makes 6.52851973 times what the cycle carries there, and the screen still reports pressureOk true, glrOk false and feasible false.'),
  ('gaswell', 'advanced', 'module', 'm05-what-nobody-checks', 5, 'The OGUTA-2 cycle is 89.90356589 min. How much of it is open to an operator?', '["The 30.0 min of afterflow and the 40.0 min of shut-in.", "All of it, since the rise and the fall follow from the slug and the casing pressure.", "The rise of 10.93333333 min, moved by changing the casing behind the plunger.", "None of it, every term being computed from the well and the slug."]'::jsonb, 0, 'The rise and the fall are set by velocities the module states as typical inputs, 750.0 ft/min up and 1000.0 ft/min and 172.0 ft/min down.'),
  ('gaswell', 'advanced', 'module', 'm05-what-nobody-checks', 6, 'Remove the afterflow on OGUTA-2 and take the shut-in to zero. What does the cycle then carry?', '["194.91525424 bbl/d, which is where the sweep is heading.", "22.26256708 bbl/d, the fastest the module will cycle.", "67.00342849 bbl/d on a trip every 19.90356589 min, which is still 2.90903404 times short of the well.", "67.00342849 bbl/d, which closes the gap as the trips rise."]'::jsonb, 2, 'The ratio falls from 8.75529105 to 2.90903404 across the whole sweep and never reaches one, so the gap is a slug size and a well.'),
  ('gaswell', 'advanced', 'module', 'm05-what-nobody-checks', 7, 'Give OGUTA-2 a 1500.0 min shut-in. What does the screen say?', '["It raises slowCycle and drops insufficientGas, a cycle that slow having ample gas per trip to work with.", "It refuses the case, 1549.90356589 min being outside the typical bands.", "It raises a liquid warning, the one place liquidPerDayBbl reaches a flag.", "It raises slowCycle on 0.92909006 trips a day, and it counts trips rather than barrels."]'::jsonb, 3, 'insufficientGas is still there because the gas check and the timing check are independent, and no warning anywhere counts barrels.'),
  ('gaswell', 'advanced', 'module', 'm05-what-nobody-checks', 8, 'Why is the liquid shortfall on OGUTA-2 easy to promise away in a design review?', '["The screen reports the shortfall as a warning a reviewer can waive against a schedule and revisit later.", "The cycle time is the field-adjustable thing and the sweep obediently improves when it is shortened.", "The sweep reaches a ratio of one before the shut-in runs out, so the last few minutes look like a detail.", "The trips per day rise faster than the liquid per trip falls."]'::jsonb, 1, 'Reading only the direction of the movement, and not the value it stops at, is how a gap of 180.08150275 bbl/d gets talked away.'),
  ('gaswell', 'advanced', 'module', 'm05-what-nobody-checks', 9, 'The two air molecular weights move the density at 2500.0 psia and 620.0 degR by a fraction of 7.595452e-5. What do they move the Turner critical velocity by?', '["7.595452e-5, since rate and velocity are linear in one another at a fixed station and area.", "Half of it exactly.", "4.050320e-5, from 5.2642800885 ft/s to 5.2644933087 ft/s.", "Nothing, the two modules sharing no velocity route."]'::jsonb, 2, 'The ratio between the two fractions is 0.53325597 rather than one half, since the density also enters the buoyancy inside the density difference.'),
  ('gaswell', 'advanced', 'module', 'm05-what-nobody-checks', 10, 'Hand criticalVelocity an unknown correlation and hand turnerFluid an unknown fluid id. What happens?', '["The correlation is refused with ok false and an error naming turner and coleman, and the fluid falls back to water.", "Both are refused, which is why the module returns ok on every call.", "Both fall back, the correlation to turner and the fluid to water.", "The correlation falls back to turner and the fluid is refused."]'::jsonb, 0, 'Two policies for one kind of mistake inside one module is the module saying it never decided, and the costs are not comparable either.'),
  ('gaswell', 'advanced', 'module', 'm05-what-nobody-checks', 11, 'What is an unknown fluid id read silently as water worth?', '["Nothing measurable, since the Turner properties are labelled starting points rather than correlations.", "A factor of 1.200000, the same size as the correlation adjustment, which is why the two are confused.", "A fixed factor at every station.", "A factor of 1.4626530609 on the terminal velocity at 1000.0 psia and 620.0 degR."]'::jsonb, 3, 'That ratio belongs to that station and does not carry to another, while an unknown correlation caught by a refusal costs nothing at all.'),
  ('gaswell', 'advanced', 'module', 'm05-what-nobody-checks', 12, 'sizeTubingForRate is handed wellhead conditions on a well loading at the shoe. What does its ok key read?', '["false, ok being the flag that marks a run whose inputs did not come from the controlling station.", "true, the sizing asked for having been answerable.", "true, but with the station recorded on every row so a reviewer can see the conditions used.", "It is not returned on that call, ok appearing only when largestUnloaded is null."]'::jsonb, 1, 'The boolean is honest about the question it covers and silent about the one nobody asked, and it returns 3.740 in against a current string of 3.548 in.'),
  ('gaswell', 'advanced', 'module', 'm05-what-nobody-checks', 13, 'On EBOCHA-5, how much tubing does the choice of station buy under each correlation?', '["0.264 in under Coleman and 0.408 in under Turner.", "0.264 in under both, since the same nine candidates are scored and only the threshold moves.", "Nothing at all.", "0.408 in under Coleman, 0.264 in under Turner."]'::jsonb, 0, 'The wellhead picks 3.740 in and 3.476 in where the controlling station picks 3.476 in and 3.068 in.'),
  ('gaswell', 'advanced', 'module', 'm05-what-nobody-checks', 14, 'On OGUTA-2 the 400 scf per bbl per 1000 ft rule asks 3280.00000000 scf/bbl. What does the balance ask?', '["5900.0 scf/bbl, the ratio the well itself makes, which is what the flag compares the rule against.", "4710.35929989 scf/bbl, which is 1.96264971 times the rule and the figure the screen carries here.", "9561.17363265 scf/bbl, so the physics is 2.91499196 times as demanding.", "3280.00000000 scf/bbl, the rule setting the requirement."]'::jsonb, 2, 'Which side of the two a well sits on is reported through ruleOfThumbAgrees, which reads false here and decides nothing.'),
  ('gaswell', 'advanced', 'module', 'm05-what-nobody-checks', 15, 'Put 40.0 psi of friction into the published plunger case. What does the required lift pressure do?', '["It rises by more than that, friction also lengthening the rise and raising the gas expanded.", "It rises to 265.8581556122 psia, exactly 40.0000000000 psi more.", "It does not move, friction being measured rather than modelled and shipped at 0.0000000000 psi.", "It rises by a fraction of it set by the rise velocity of 750.0 ft/min."]'::jsonb, 1, 'Friction is linear, additive and an input, which makes it the easiest term in the static balance to check by hand.'),
  ('gaswell', 'advanced', 'module', 'm06-the-expert-reading', 1, 'What does this tier ask of every returned number?', '["Whether it matches the golden, whether the gate covers it, and how many decimals it carries.", "Where it was read, which constant it rests on, and whether the function that produced it had a way to refuse.", "Whether it is measured, whether it repeats, and whether the oracle agrees to ten figures.", "Which module produced it, which version shipped it, and whether a warning came with it."]'::jsonb, 1, 'Most of the findings here are visible from the returned object alone, once a returned value and a computed answer stop being the same thing.'),
  ('gaswell', 'advanced', 'module', 'm06-the-expert-reading', 2, 'A number that two modules in one domain disagree about. What kind of number is it?', '["A measurement, since two independent routes agreeing to 75.9603 parts per million is a check rather than a seam.", "An artefact of the station it was read at.", "A defect, which a cross-module assertion would catch.", "A convention, like 28.9647 against 28.9625 for the molecular weight of air."]'::jsonb, 3, 'Neither of those two values changes a decision and both change a number, which is exactly the test that separates a convention from a measurement.'),
  ('gaswell', 'advanced', 'module', 'm06-the-expert-reading', 3, 'On a plunger, what comes before reading the required gas-liquid ratio?', '["Read glrOk first, since the flag already carries the sign of that subtraction inside it.", "Check maxSlugLengthFt, which refuses whenever the balance has no solution left.", "Subtract the required lift pressure from the casing and look at the sign.", "Compare the requirement to the rule of thumb."]'::jsonb, 2, 'If the sign is negative the gas number is an artefact of an average and the flag is meaningless, and nothing in the returned object will say so.'),
  ('gaswell', 'advanced', 'module', 'm06-the-expert-reading', 4, 'At 999.96 psia, which do you take, the correlation field or the sentence?', '["The field, because the sentence rounds.", "The sentence, which prints the pressure to one decimal and is therefore the more precise of the two.", "Either, since the reason is generated from the same comparison that sets the name.", "The sentence, since the field carries no station and the reason can name one."]'::jsonb, 0, 'The reason prints 1000.0 and the limit prints 1000.0 while the branch still returns coleman, and one decimal narrowed that collision rather than closing it.'),
  ('gaswell', 'advanced', 'module', 'm06-the-expert-reading', 5, 'maxSlugLengthFt comes back at zero or at the tubing depth exactly. What do you quote in its place?', '["The clamped value with its bound named, since zero and the tubing depth are both legitimate slug lengths to report.", "The shortfall in psi, since a clamp is not an answer.", "The unclamped solution.", "The casing pressure that produced it."]'::jsonb, 1, 'At 130.0 psia of casing on OGUTA-2 the return is 0.00000000 ft while the balance with no slug at all is still short by 45.3101604102 psi.'),
  ('gaswell', 'advanced', 'module', 'm06-the-expert-reading', 6, 'What does a loading verdict actually establish?', '["A critical velocity, a critical rate and one ratio that decides, at the station and the supplied rate.", "What the well will make next month once the liquid is off the bottom.", "Whether a velocity string or a plunger is the cheaper remedy here.", "The inflow the well can deliver against the new tubing."]'::jsonb, 0, 'The gas rate is an input, so a verdict is a verdict at a rate somebody supplied rather than a prediction of what the well does next.'),
  ('gaswell', 'advanced', 'module', 'm06-the-expert-reading', 7, 'How can a gas well load without any of its droplets falling?', '["Through coalescence, which the balance handles by raising the critical Weber number of 30.0000.", "Through a droplet population, which the model averages over rather than resolving row by row.", "Through slippage past the plunger.", "Liquid also travels as a film on the tubing wall, which this model never sees."]'::jsonb, 3, 'It carries one droplet at its terminal velocity on a drag coefficient of 0.4400 for a rigid sphere, and models neither break-up in transit nor film flow.'),
  ('gaswell', 'advanced', 'module', 'm06-the-expert-reading', 8, 'Why does a velocity string work at all?', '["A narrower string lowers the gas density at the station and so lowers the critical velocity a droplet needs.", "It raises the gas rate the well delivers.", "Tubing enters the calculation only through the flow area.", "It cuts the pressure at the shoe."]'::jsonb, 2, 'That is why the pick moves by 0.264 in when the station moves on EBOCHA-5, while nothing about the fluids or the station moves with it.'),
  ('gaswell', 'advanced', 'module', 'm06-the-expert-reading', 9, 'What does the sizing do when nothing on the shelf can carry the rate?', '["It returns the smallest candidate on the list, with the loaded flag set true.", "It returns largestUnloaded as null rather than the least bad candidate, in a form a caller can act on.", "It returns ok false, which is the refusal the function keeps for this case.", "It extends the list downward until something clears."]'::jsonb, 1, 'At 40.0 Mscf/d on the EBOCHA-5 list the best ratio anywhere is 0.0502326405, and no candidate below 1.610 in is invented.'),
  ('gaswell', 'advanced', 'module', 'm06-the-expert-reading', 10, 'Which step done out of order leaves every later number defensible on its own and the conclusion wrong?', '["Choosing the correlation, since the rows record the name and a reviewer can rerun the list.", "Reading the slug length, which announces itself by clamping at 0.00000000 ft.", "Checking the liquid.", "Fixing the station, because nothing downstream records a depth."]'::jsonb, 3, 'sizeTubingForRate records the correlation on every row and the depth on none, while the controlling point already carries pPsia, tempR, z, idIn and depthFt together.'),
  ('gaswell', 'advanced', 'module', 'm06-the-expert-reading', 11, 'Which unit does the loading module ask temperature in?', '["degR, where gasProperties takes degF.", "degF, which is why the EBOCHA-5 traverse carries 194.00 degF at its shoe.", "degR in the profile and degF in the sizing, which is the seam the two share.", "Either, since toRankine converts whatever it is handed."]'::jsonb, 0, 'One station is 620.0000 degR or 160.3300 degF depending on which door it enters, and each module is right by itself.'),
  ('gaswell', 'advanced', 'module', 'm06-the-expert-reading', 12, 'The required gas-liquid ratio on OGUTA-2 falls 70.545832 percent as the casing is walked down. How much of that fall is real?', '["All of it, since the average of the two ends is well defined at every casing pressure on the sweep.", "None of it, the requirement being fixed.", "The part above the crossing, where less casing pressure genuinely expands less gas.", "Only the last row, at 90.0 psia."]'::jsonb, 2, 'It runs from 11338.72941173 scf/bbl to 3339.72840586 scf/bbl, and nothing in the return marks where the expansion stopped running the right way.'),
  ('gaswell', 'advanced', 'module', 'm06-the-expert-reading', 13, 'What is feasible built from?', '["pressureOk, glrOk and the liquid comparison, which the screen holds both halves of.", "pressureOk and glrOk and nothing else, so the liquid a cycle carries reaches no flag at all.", "pressureOk and the rule of thumb, which is the screening rule the module ships.", "The warnings list, which feasible summarises."]'::jsonb, 1, 'On OGUTA-2 a cycle carries 14.83375148 bbl/d against a well that makes 194.91525424 bbl/d, which is 13.13998380 times as much.'),
  ('gaswell', 'advanced', 'module', 'm06-the-expert-reading', 14, 'What does the working order ask you to write down before any gas number?', '["The casing less the lift pressure, and that it is positive.", "The required gas-liquid ratio, which the insufficientGas warning already quotes in full.", "The gas per cycle in scf, which carries both ends of the expansion inside it.", "The rule of thumb ratio."]'::jsonb, 0, 'The sign of that subtraction decides whether the gas number is worth reading, and an average of the two ends destroys the sign.'),
  ('gaswell', 'advanced', 'module', 'm06-the-expert-reading', 15, 'What does this tier leave a reader able to sort?', '["Correlations, remedies and the wells each of the two is suited to.", "Published cases, teaching wells and the goldens that check them.", "Measurements, conventions and artefacts.", "Errors, warnings and the silent returns that sit between the two."]'::jsonb, 2, 'Read the station before the number, and report the margin beside every verdict.'),
  ('gaswell', 'advanced', 'final', null, 1, 'Between which adjacent pair of pressures does the whole correlation decision sit?', '["999.88 psia and 999.96 psia, the pair that straddles the rounding.", "1000.00 psia and 1000.04 psia, the first two on the turner side.", "999.96 psia and 1000.00 psia, since the comparison against the limit is strict.", "980.00 psia and 999.04 psia, where the print first collides."]'::jsonb, 2, 'Everything on one side of that step is treated identically, and 999.96 psia returns coleman while 1000.00 psia returns turner.'),
  ('gaswell', 'advanced', 'final', null, 2, 'In what order does the sizing return its rows?', '["Largest diameter first, so the pick is the first row that reaches one.", "By ratio ascending, so the pick is the last row that fails and the first that clears the threshold.", "Smallest first, so the larger rows are never scored.", "In whatever order the caller supplied them."]'::jsonb, 0, 'The EBOCHA-5 list runs 3.958 down to 1.610 in, and the coleman pick is 3.476 in at 1.0022156322.'),
  ('gaswell', 'advanced', 'final', null, 3, 'The gauge at 880.0 psia selects coleman and the sizing at the shoe is then run under it. What is that chain worth in tubing?', '["Nothing, since the sizing records the correlation on every row and a reviewer can simply rerun it.", "0.264 in, the distance from 3.740 in to 3.476 in, which is the price of the station rather than the name.", "Two candidates, coleman rejecting four and turner five.", "One candidate along the list, 3.476 in where turner would have picked 3.068 in."]'::jsonb, 3, 'The name is chosen 7500.0 ft above the station it is applied at, and 3.476 in reads 1.0022156322 under one and 0.8351796935 under the other.'),
  ('gaswell', 'advanced', 'final', null, 4, '1000.0 kg/m3 times g gives 9806.650000 Pa/m. What comes next in the chain?', '["0.4335275040010 psi/ft per unit SG, a pascal per metre being already a pressure per length.", "2989.066920 Pa/ft.", "2989.066920 Pa/ft, reached by dividing by 6894.757293168 Pa per psi.", "0.4333333333333 psi/ft per unit SG, the same conversion in field units."]'::jsonb, 1, 'The step from Pa/m to Pa/ft is 0.3048 m per ft, and only the last step divides by 6894.757293168 Pa per psi.'),
  ('gaswell', 'advanced', 'final', null, 5, 'At 720.0 psia of casing the OGUTA-2 maximum slug is 1195.81347818 ft. What does the balance read at exactly that length?', '["720.0000000000 psia against a casing of 720.0 psia, a residual of -1.1369e-13 psi.", "248.1897322873 psia, the required lift pressure, which the maximum slug is defined to reach exactly.", "The line pressure of 145.0 psia.", "It cannot be evaluated, since 1195.81347818 ft is a clamp."]'::jsonb, 0, 'The solve is exact where the clamp does not bite, and that maximum slug holds 6.92163806 bbl.'),
  ('gaswell', 'advanced', 'final', null, 6, 'What does a ratio of well liquid make to cycle capacity above one mean?', '["The plunger is undersized for the tubing, which a slug length check would have caught.", "The cycle is too slow, which is exactly what the slowCycle warning is raised for.", "The liquid level rises whatever the flags say.", "The gas ratio is under requirement."]'::jsonb, 2, 'On OGUTA-2 it is 13.13998380, and a plunger that clears every check the screen performs can still be the wrong remedy.'),
  ('gaswell', 'advanced', 'final', null, 7, 'Every number in a deliquification study is one of three things. Which three?', '["A golden, an engine value or a derived sweep point on published inputs.", "A measurement, a convention or an artefact.", "An input, a returned field or a warning raised beside the two.", "A published case, a teaching well or a capstone condition."]'::jsonb, 1, 'A number two modules disagree about is a convention, and a number that changes with the depth the gauge sat at is an artefact.'),
  ('gaswell', 'advanced', 'final', null, 8, 'Which EBOCHA-5 station carries the largest difference in Mscf/d between the two names?', '["0.0 ft, at 534.224657483 Mscf/d, which is where the two verdicts actually disagree.", "4500.0 ft, at 599.582486631 Mscf/d, the deepest station the verdicts still differ over.", "7500.0 ft, at 644.522679360 Mscf/d.", "All six equally."]'::jsonb, 2, 'The difference tracks the critical rate, which rises down the hole, so it is largest where the well controls.'),
  ('gaswell', 'advanced', 'final', null, 9, 'Between the 3.548 in row and the 3.476 in row under coleman, which fields move?', '["The critical velocity and the ratio, a narrower string raising what a droplet needs.", "The gas density and the actual velocity, both of which follow the string.", "Only the ratio, the critical rate belonging to the station alone.", "The actual velocity and the critical rate."]'::jsonb, 3, 'The critical velocity is 6.1224977520 ft/s on both rows, and 5.8895500931 ft/s against 6.1360629550 ft/s is the whole of the difference.'),
  ('gaswell', 'advanced', 'final', null, 10, 'A study sizes EBOCHA-5 at the wellhead and takes its correlation from the same gauge. Which of the two errors shows in the return value?', '["Both, since a row carries rhoGasLbFt3 and the pressure is recoverable from it.", "The correlation, which every row names beside its adjustment, while the station appears on no row at all.", "Neither, rows carrying only diameters, ratios and flags.", "The station, through a criticalVelocityFtS field stamped with its depth."]'::jsonb, 1, 'Two sizings run at two stations on one well are indistinguishable from their return values, and the wrong one comes back with ok true.'),
  ('gaswell', 'advanced', 'final', null, 11, 'On the published case the cost on the slug is 0.1076108162 psi and on the lift pressure 0.1076454958 psi. Why are the two so close?', '["The lift pressure is dominated by the slug hydrostatic, which is 88.3320000000 psi of it.", "Rounding makes the two indistinguishable here.", "The gas column carries an offsetting error.", "The other four terms of the balance carry no error from this constant at all."]'::jsonb, 3, 'The percentage falls from 0.1216771707 to 0.04763796 while the absolute cost barely moves, because only one term of five is affected.'),
  ('gaswell', 'advanced', 'final', null, 12, 'On the published plunger case at a derived well ratio of 4500.0 scf/bbl, between which two casing pressures does pressureOk turn false?', '["600.0 psia and 480.0 psia, where glrOk turns true and the verdict changes.", "240.0 psia and 200.0 psia.", "300.0 psia and 240.0 psia, where the required ratio drops under 2657.06559995 scf/bbl.", "150.0 psia and below."]'::jsonb, 1, 'The required lift pressure is 225.85815561 psia throughout, so the casing crosses it between those two rows and the shape is not a teaching-well artefact.'),
  ('gaswell', 'advanced', 'final', null, 13, 'What does the plunger screen actually establish?', '["Whether a plunger keeps the well unloaded at the rate the well is currently making.", "Which of the four remedies is cheapest on this particular well, which is what a screen is for.", "Whether one slug at one casing pressure clears one balance and one ratio.", "Whether the liquid the well makes can actually be carried away by the installation."]'::jsonb, 2, 'It is a genuine filter and it is cheap, and it cannot tell you what the well makes next month or whether the liquid keeps up.'),
  ('gaswell', 'advanced', 'final', null, 14, 'What does the working order put first, and why?', '["The station, because no function downstream records a depth and every later number stays defensible on its own.", "The correlation, because it is worth twenty percent of every critical rate.", "The liquid, because nothing else in the screen checks it.", "The units, because degR and degF both reach these modules."]'::jsonb, 0, 'The controlling point already carries pPsia, tempR, z, idIn and depthFt together, so keeping them together costs nothing and losing them costs a tubing size.'),
  ('gaswell', 'advanced', 'final', null, 15, 'A mixed profile on EBOCHA-5 shows a discontinuity between two stations. What is it a property of?', '["The well, since a change of flow regime at that depth is what carries the pressure past the limit.", "The traverse spacing of 1500.0 ft.", "Where a pressure threshold happened to land inside the traverse.", "The droplet balance, which switches regime there."]'::jsonb, 2, 'Nothing physical changes at 1000.0 psia, so a step between 2771.653428599 Mscf/d and 3456.727431568 Mscf/d invites a reader to look for a mechanism.'),
  ('gaswell', 'advanced', 'final', null, 16, 'Under turner the four coleman rejections read 0.6441512920, 0.6893654772, 0.7214334210 and 0.8016268212. What changed?', '["The ordering, the adjustment falling hardest on the largest area.", "Only the distance from the threshold, since the correlation divides all four of them by the same factor.", "The binding constraint, which moves from area to velocity.", "The actual velocities, scaled along with the critical ones."]'::jsonb, 1, 'The actual velocities did not move at all, because the rate and the areas are unchanged between the two runs.'),
  ('gaswell', 'advanced', 'final', null, 17, 'The rounded gradient costs 0.1216771707 percent of a slug hydrostatic. Where does that land in the OGUTA-2 casing sweep?', '["On the slug hydrostatic of 73.4368000000 psi, which the casing never moves.", "On the required gas-liquid ratio, which falls 70.545832 percent across the sweep and carries the same fixed percentage.", "On the crossing, which the rounding shifts by that percentage of the casing pressure.", "Nowhere, the slug being fixed at 160.0 ft."]'::jsonb, 0, 'The requirement of 248.1897322873 psia is a static balance the casing never enters, so the gradient error sits in one term and stays there.'),
  ('gaswell', 'advanced', 'final', null, 18, 'How much of the gradient rounding does the maximum slug length inherit?', '["The same 0.1216771707 percent, the constant multiplying the slug length directly.", "None, since maxSlugLengthFt solves the balance rather than evaluating it.", "0.04763796 percent, the share the required lift pressure carries.", "A different share, found only by running both gradients through."]'::jsonb, 3, 'Each quantity inherits a share depending on how much of it the hydrostatic term is, and a tenth of a percent is the error on the head alone.'),
  ('gaswell', 'advanced', 'final', null, 19, 'Below the crossing the gas number is an average of two ends in the wrong order. What is the flag built on it worth?', '["The same as above the crossing, since an average of two ends is well defined either way.", "A warning, raised by insufficientGas.", "Nothing, and nothing in the returned object marks the boundary.", "It is conservative, overstating the gas."]'::jsonb, 2, 'Every step of the fall is in the flattering direction, and the missing guard is one line refusing the gas number when the casing is at or below the requirement.'),
  ('gaswell', 'advanced', 'final', null, 20, 'A loading verdict says a well is loading at 3100.0 Mscf/d. What does it not say?', '["What the critical rate is, computed only at the controlling station.", "Which correlation produced it, no returned field naming one.", "Whether the traverse is physical, which the profile solves for.", "What the well will do next, since the gas rate is an input and no inflow relation exists in these modules."]'::jsonb, 3, 'The traverse is passed in station by station with its own pressure, temperature and compressibility, and nothing here invents a gradient.'),
  ('gaswell', 'advanced', 'final', null, 21, 'A function returns zero. What does this tier teach you to ask about it?', '["Whether the gate covers it and whether the golden publishes the same zero.", "Whether it is an answer or a clamp wearing a number.", "Whether it is small enough to ignore against the other terms of the balance.", "Whether it carries units."]'::jsonb, 1, 'At 130.0 psia of casing on OGUTA-2 the zero hides a balance that is short by 45.3101604102 psi with no slug at all.'),
  ('gaswell', 'advanced', 'final', null, 22, 'What does the object returned by recommendCorrelation contain?', '["A name and a reason.", "A name, a reason and the pressure, so a caller can check the branch.", "A name, an adjustment of 1.000000 or 1.200000, and the limit compared against.", "A name and a confidence, graded by distance from the limit."]'::jsonb, 0, 'It reports only a rendering of the pressure, so a caller who needs the exact value keeps the one it passed in.'),
  ('gaswell', 'advanced', 'final', null, 23, 'Which two rows of a nine-candidate sizing are worth arguing about?', '["The largest and the smallest, which bound what the shelf of sizes can do.", "The pick and the current string, since only those two are real tubing in a hole.", "Every rejection.", "The pick and the rejection immediately above it."]'::jsonb, 3, 'The rejections rank by area, an ordering fixed before the physics runs, so what carries information is where the threshold falls inside it.'),
  ('gaswell', 'advanced', 'final', null, 24, 'gasWellLoading and gasProperties disagree by 75.9603 parts per million on the molecular weight of air. What is the same shape in the plunger module?', '["A rule of thumb constant of 400.0 scf per bbl per 1000 ft carried beside a computed requirement.", "Nothing, plungerLift touching no molecular weight.", "A gradient of 0.4330000000000 against an exact 0.4335275040010.", "A friction term shipped at 0.0000000000 psi."]'::jsonb, 2, 'Two modules in one domain carrying a rounded 0.433 is one adjudication, and the constant is 0.1216771707 percent off the exact conversion.'),
  ('gaswell', 'advanced', 'final', null, 25, 'Why is a test that asserts a constant equals its current value a problem?', '["A correction has to be allowed to break it.", "It duplicates the golden, which publishes 88.4396108162 psi for the same case.", "It cannot fail, so it adds nothing and costs nothing to keep.", "It conflicts with the loosened slug assertion beside it."]'::jsonb, 0, 'The gate pins PSI_PER_FT_SG to 0.433 while loosening the answer built on it to 5e-3, which is 4.109234 times the disagreement.'),
  ('gaswell', 'advanced', 'final', null, 26, 'Walk OGUTA-2 to a casing of 900.0 psia and the longest liftable slug comes back as 1590.98594226 ft. Did the clamp bite?', '["Yes, at the available pressure of 724.68983959 psi, which is where the upper clamp fires.", "No, and the return equals the unclamped solution exactly.", "It cannot be told from the return value, which is exactly the point of the finding.", "Yes, at the tubing depth of 8200.0 ft."]'::jsonb, 1, 'The clamp bites only at 0.00000000 ft and at the tubing depth of 8200.00000000 ft, and everything between them is a solution.'),
  ('gaswell', 'advanced', 'final', null, 27, 'An unknown correlation costs nothing and an unknown fluid id costs a factor of 1.4626530609. Why?', '["One is caught by the gate and the other by no golden.", "One changes an adjustment and the other a density.", "One of the two is refused outright and the other is silently read as water instead.", "One is checked at the door, the other at use."]'::jsonb, 2, 'criticalVelocity returns ok false with an error naming turner and coleman, and turnerFluid falls back rather than refusing.'),
  ('gaswell', 'advanced', 'final', null, 28, 'Where does a loading verdict hand over to something else?', '["At the traverse, which loadingProfile solves for multiphase flow before scoring.", "At the correlation choice.", "At the flow area.", "At the inflow, which none of these modules contains."]'::jsonb, 3, 'The gas rate is an input, so every verdict is a verdict at a rate somebody supplied.'),
  ('gaswell', 'advanced', 'final', null, 29, 'The same EBOCHA-5 traverse reports -3.80478145 percent under one name. What does it report under the other?', '["-3.80478145 percent still, the margin being taken at the shoe.", "-19.83731788 percent, at the same controlling station of 7500.0 ft under both names.", "16.05604334 percent, the wellhead margin instead.", "-19.83731788 percent, controlling at 6000.0 ft."]'::jsonb, 1, 'The honest reading is that the shoe loads by somewhere between those two figures, and the choice cannot turn a loading shoe into a healthy one.'),
  ('gaswell', 'advanced', 'final', null, 30, 'What does the sizing charge a candidate for being narrow?', '["A friction penalty returned on each row beside its ratio and its loaded flag.", "A share of the supplied gas rate.", "A penalty in the ok field.", "Nothing, there being no pressure drop calculation in it at all."]'::jsonb, 3, 'That is why the objective lands on the boundary at 1.0022156322: the constraint is hard and nothing is priced beyond it.'),
  ('gaswell', 'advanced', 'final', null, 31, 'A sizing row carries a correlation and no station. A plunger return carries no gradient. What do the two omissions share?', '["An assumption that changes the answer is absent from the object reporting it.", "Both are display defects, fixed by printing more decimals in a reason string.", "Both are caught by the gate, which pins the constant and checks the station.", "Neither costs anything."]'::jsonb, 0, 'A convention absent from a return value is enforced by the reader, whether it is a depth or a 0.4335275040010 psi/ft per unit SG.'),
  ('gaswell', 'advanced', 'final', null, 32, 'gasProperties.gasGradient returns 0.0545793356 psi/ft at 2500.0 psia and 620.0 degR. How does that relate to a density?', '["It is the density times the gas gravity of 0.65, which is how a gradient carries composition.", "It is the density over 144.", "It is an independent correlation, which is why it disagrees with 7.8600213238 lbm/ft3.", "It is the density divided by the gas constant R of 10.7316."]'::jsonb, 1, 'Times 144 it gives 7.8594243196 lbm/ft3, and the 0.002200 lbm/lbmol of air is the only thing that differs between the two routes.'),
  ('gaswell', 'advanced', 'final', null, 33, 'A caller checks maxSlugLengthFt against the tubing length to detect a clamp. What does that catch?', '["Both clamps, zero and the tubing depth being the two ends of one range.", "Neither, since the function returns NaN whenever it clamps at either end.", "Only the upper clamp, at 8200.00000000 ft, and not the zero.", "Only the lower clamp."]'::jsonb, 2, 'Equality with the depth is what the caller gets rather than a signal, and at 130.0 psia the zero hides a shortfall of 45.3101604102 psi.'),
  ('gaswell', 'advanced', 'final', null, 34, 'What makes the missing liquid comparison a decision rather than an oversight?', '["It is documented in the module header as a stated limit, which an oversight would not be.", "The rule of thumb already checks liquid.", "The warnings list has room for it.", "Both ingredients are already returned, so only the ratio is absent."]'::jsonb, 3, 'A cycle carrying 0.9261160790 bbl is a correct answer about a cycle and 194.91525424 bbl/d is a correct answer about a well.'),
  ('gaswell', 'advanced', 'final', null, 35, 'Can loadingProfile vary its correlation with depth?', '["No, it takes one correlation for the whole traverse and has no argument for a per-station list.", "Yes, it calls the recommendation at each station and uses it.", "Yes, if each traverse station carries its own name.", "No, and it refuses a traverse that straddles the limit."]'::jsonb, 0, 'A mixed profile is assembled by hand and defended by hand, and the engine refuses an unknown correlation and an empty traverse but not this.'),
  ('gaswell', 'advanced', 'final', null, 36, 'Why is one candidate landing on the boundary the normal case rather than a contrivance?', '["The teaching well was tuned until one of them did, which is what a teaching well exists to do.", "The list is a shelf of standard sizes, so one usually falls near the threshold.", "The threshold of one is arbitrary.", "Candidates are spaced by area."]'::jsonb, 1, 'Every other row keeps its answer under both names, clearing one comfortably or missing by a wide margin.'),
  ('gaswell', 'advanced', 'final', null, 37, '0.4330000000000 psi/ft per unit SG, and a coleman recommendation taken at 880.0 psia. Which is which?', '["Both are conventions, neither of the two being measured on the well.", "The gradient is the artefact and the name is the convention.", "Both are artefacts, a gate pinning one and a gauge the other.", "The gradient is the convention, the name the artefact."]'::jsonb, 3, 'A number two modules disagree about is a convention, and a name that would have been turner at 1500.0 psia is an artefact of a station.'),
  ('gaswell', 'advanced', 'final', null, 38, 'What in the codebase checks that two modules in one domain agree on a constant?', '["The gate, which pins the gradient and would therefore catch any second value of it anywhere.", "The oracle, which publishes 7.8600381043 lbm/ft3 and so fixes one of the two routes.", "Nothing, there being no shared constants module and no cross-module assertion.", "The domain header."]'::jsonb, 2, 'Each module is right by its own arithmetic, so the seam opens without an error message anywhere.'),
  ('gaswell', 'advanced', 'final', null, 39, 'Which of the plunger cycle terms does the module compute?', '["The rise at 750.0 ft/min, worked out from the casing pressure behind the plunger.", "None of them.", "The fall, at 1000.0 ft/min in gas and 172.0 ft/min in liquid.", "The afterflow and the shut-in, from the trips a day required."]'::jsonb, 1, 'They are operating inputs with stated typical bands, neither computed nor optimised, which is why the whole saving on OGUTA-2 is 30.0 min and 40.0 min.'),
  ('gaswell', 'advanced', 'final', null, 40, 'The sizing refuses to name a winner at 40.0 Mscf/d and accepts wellhead conditions on a loading well without a word. What separates the two?', '["The first is a documented limit and the second is a defect the gate is meant to catch.", "One question was asked of it and the other was not.", "One returns ok false and the other ok true, the flag doing the job it was written for.", "The rate is validated and the pressure is not."]'::jsonb, 1, 'largestUnloaded null once meant both no candidate and no answer, which is why ok is there, and a wrong station still returns ok true.'),
  ('gaswell', 'advanced', 'final', null, 41, 'OGUTA-2 at 320.0 psia of casing reads pressureOk true, glrOk true and feasible true. What does the screen still not know?', '["That the cycle carries 14.83375148 bbl/d against a well making 194.91525424 bbl/d.", "That the required 5611.04967913 scf/bbl came from an average taken across the crossing.", "That a casing of 320.0 psia is below the line pressure the cycle has to vent against.", "That maxSlugLengthFt at that casing pressure was clamped, returning 317.65244688 ft instead."]'::jsonb, 0, 'feasible is built from a pressure flag and a gas flag, and the liquid comparison is in neither of them.'),
  ('gaswell', 'advanced', 'final', null, 42, 'EBOCHA-5 is sized four ways. Which single pair of choices returns a pick larger than the string already in the hole?', '["The wellhead under coleman, returning 3.740 in against 3.548 in.", "The controlling station under coleman, returning 3.476 in and so recommending no change at all.", "The wellhead under turner, returning 3.476 in and reporting the current string adequate.", "None of the four."]'::jsonb, 0, 'The other three picks sit below 3.548 in, and the well loads over the bottom 40.0000 percent of its tubing while that one answer comes back.');
