-- ============================================================================
-- refinery ASSOCIATE DEEP SEED: Refinery Feasibility & Planning, beginner tier.
--
-- Six modules, 26 lessons, 132 questions (15 per module bank plus a 42
-- question final exam). The structure row is GENERATED from the tier's
-- manifest.json rather than hand typed.
--
-- What this tier owns: THE MODULAR SCREEN. A blank money or size box is
-- refused by name and a utilisation outside 0 to 1 is refused; capital is
-- scaled from a vendor quotation on the stick-built and modular laws, which
-- agree at the reference size; the product slate is valued per barrel of
-- crude with the loss carried as a yield of no value; annual throughput is
-- capacity times on-stream days times utilisation, and the gross margin per
-- barrel is the slate value less crude and variable operating cost; supply
-- scenarios move the utilisation and the crude premium; the licensing
-- tracker names the next stage and flags one ticked out of order.
--
-- THE ENGINE FACT THIS TIER OWNS. The economy of scale is an exponent, and the
-- exponent is an input: the screen shows both laws side by side.
--
-- THE TRAP THE TIER IS BUILT ON. The scenario changes two things at once, the
-- run rate and the crude price, and a reader who applies one of them misses
-- the margin.
--
-- HELD, taught as a limit and never graded: the exponents 0.6 and 0.9 are
-- defaults a vendor's figures replace (H1). The capstone grades six numbers,
-- each an engine return: two capital costs and a first-year revenue to the
-- whole dollar, an annual throughput to the whole barrel, and a slate value
-- and a gross margin to the cent.
-- ============================================================================

insert into public.academy_course_structures
    (app_slug, tier, structure, content_version)
values ('refinery', 'beginner', '{"modules":[{"key":"m01-what-a-feasibility-screen-computes","title":"What a Feasibility Screen Computes","lesson_keys":["l01-two-apps-and-one-barrel","l02-a-screen-before-a-study","l03-a-blank-box-is-refused","l04-illustrative-prices-and-what-they-give"]},{"key":"m02-capital-and-the-scaling-law","title":"Capital and the Scaling Law","lesson_keys":["l01-cost-from-a-reference-point","l02-six-tenths-and-nine-tenths","l03-the-crossover-at-the-reference-size","l04-cost-per-barrel-of-capacity","l05-the-exponents-are-held"]},{"key":"m03-the-product-slate","title":"The Product Slate","lesson_keys":["l01-three-configurations","l02-value-per-barrel-of-crude","l03-the-loss-is-carried","l04-an-unpriced-product-is-named","l05-yields-that-do-not-close"]},{"key":"m04-throughput-and-the-gross-margin","title":"Throughput and the Gross Margin","lesson_keys":["l01-nameplate-days-and-utilisation","l02-utilisation-is-a-fraction","l03-the-gross-margin-per-barrel","l04-the-annual-streams","l05-capital-in-the-construction-years"]},{"key":"m05-crude-supply-and-licensing","title":"Crude Supply and Licensing","lesson_keys":["l01-three-supply-scenarios","l02-the-premium-and-the-run-rate","l03-the-licensing-sequence","l04-licences-out-of-order"]},{"key":"m06-the-associate-reading","title":"The Associate Reading","lesson_keys":["l01-the-okordia-screen-end-to-end","l02-okordia-under-three-supplies","l03-what-the-next-tier-changes"]}]}'::jsonb, 1)
on conflict (app_slug, tier) do update
  set structure = excluded.structure,
      content_version = excluded.content_version,
      active = true,
      updated_at = now();

delete from public.academy_quiz_questions
 where app_slug = 'refinery' and tier = 'beginner';

insert into public.academy_quiz_questions
    (app_slug, tier, scope, module_key, ord, prompt, options, answer_index, explanation)
values
  ('refinery', 'beginner', 'module', 'm01-what-a-feasibility-screen-computes', 1, 'Two Suite apps call the refinery modules. Which app reaches the screening engine, and through which function does it get there?', '["The Refinery Planning Studio, through its cascadeToSchedule function.", "The Modular Refinery Feasibility Studio, through the scaleCapex function.", "The Modular Refinery Feasibility Studio, through feasibilityEconomics.", "The Refinery Planning Studio, through the plan, schedule and actual ledgers."]'::jsonb, 2, 'modularRefinery hands its annual streams to the screening engine through feasibilityEconomics. The Refinery Planning Studio runs refineryPlanning over lib/lp/simplex and streamModel, and neither of those reaches the screening engine in this tier.'),
  ('refinery', 'beginner', 'module', 'm01-what-a-feasibility-screen-computes', 2, 'Some exports read the machine clock when an argument is left out. Which pairing of function and missing argument does the digest print?', '["feasibilityEconomics reads the year when startYear is left out.", "cascadeToSchedule reads the year whenever startYear is left out of the call.", "feasibilityEconomics reads the date when periodStart is left out.", "scaleCapex reads the clock when no exponent is passed to it at all."]'::jsonb, 0, 'cascadeToSchedule reads the clock when periodStart is missing, and feasibilityEconomics and calculateEconomics read the year when startYear is missing. The course passes both every time, with start year 2027 for every valuation.'),
  ('refinery', 'beginner', 'module', 'm01-what-a-feasibility-screen-computes', 3, 'The digest counts each module''s exports. Which count belongs to modularRefinery?', '["3 exported functions and 0 exported lists and constants.", "7 exported functions and 4 exported lists and constants, as measured.", "6 exported functions and 1 exported list or constant, as counted.", "6 exported functions and 4 exported lists and constants."]'::jsonb, 3, 'modularRefinery counts 6 and 4. refineryPlanning counts 3 and 0, streamModel 7 and 4, and the screening engine 6 and 1.'),
  ('refinery', 'beginner', 'module', 'm01-what-a-feasibility-screen-computes', 4, 'streamModel.LEDGER names the three ledgers the later tiers read one barrel on. Which three are they?', '["optimal, infeasible and unbounded", "plan, schedule and actual", "receipt, delivery and transfer", "firm, tight and disrupted"]'::jsonb, 1, 'LEDGER holds plan, schedule and actual. firm, tight and disrupted are modularRefinery.SUPPLY_SCENARIOS, the three futures for crude arriving at the gate, and the other two options are not ledgers at all.'),
  ('refinery', 'beginner', 'module', 'm01-what-a-feasibility-screen-computes', 5, 'feasibilityStreams is run on OKORDIA with the crude cost box left blank. What does the engine return?', '["An answer that reads the blank as a crude cost of zero and prints a higher margin.", "REFUSED: \"Missing crude cost. Enter 0 where the value really is zero.\"", "An answer at the firm scenario''s crude cost with premium of 76.0000 a barrel.", "An answer with the crude cost column of the annual streams left out entirely."]'::jsonb, 1, 'A money box left blank is refused by name, and the sentence says how to state zero on purpose: type 0. A blank says the value is unknown, and a typed 0 says it is known and nothing.'),
  ('refinery', 'beginner', 'module', 'm01-what-a-feasibility-screen-computes', 6, 'On OKORDIA, the capacity and the fixed operating cost are both left blank. What comes back?', '["A refusal naming capacity alone, so the fixed operating cost surfaces as its own refusal on the next run.", "A refusal naming capacity, with the blank fixed operating cost read as 0.00 so the year still builds.", "An answer with null capital from scaleCapex and streams that carry no capex or fixed opex at all.", "A single refusal that names both the capacity and the fixed operating cost, together in one sentence"]'::jsonb, 3, 'When two boxes are blank the refusal names both in one sentence: "Missing capacity, fixed operating cost. Enter 0 where the value really is zero." Both are fixed together, and the second is not discovered on the next run.'),
  ('refinery', 'beginner', 'module', 'm01-what-a-feasibility-screen-computes', 7, 'A user types 90 into the utilisation box, meaning 90 percent. What does the engine return?', '["REFUSED: \"Utilisation is a fraction between 0 and 1 (0.9 for 90 percent).\"", "An answer that reads 90 as 0.9 and runs the plant at that fraction of nameplate.", "An answer running 90 times nameplate on each of the 330 on-stream days.", "REFUSED: \"On-stream days must be between 1 and 366.\""]'::jsonb, 0, 'Utilisation is read as a fraction, and 90 lies outside 0 to 1, so the engine refuses it and gives the example 0.9 for 90 percent. It never guesses what was meant.'),
  ('refinery', 'beginner', 'module', 'm01-what-a-feasibility-screen-computes', 8, 'Utilisation typed as 0 and on-stream days typed as 0 are each tried on OKORDIA. How does the engine treat the two?', '["Both are refused, each with the range the engine accepts for that input.", "Both are answered, and each prints an annual throughput of 0.00 bbl.", "Utilisation 0 is answered with 0.00 bbl; on-stream days 0 is refused with its range.", "On-stream days 0 is answered with 0.00 bbl; utilisation 0 is refused with its range."]'::jsonb, 2, 'A utilisation of 0 is inside 0 to 1, so the engine answers: annual throughput 0.00 bbl. On-stream days must be between 1 and 366, so a typed 0 is refused.'),
  ('refinery', 'beginner', 'module', 'm01-what-a-feasibility-screen-computes', 9, 'scaleCapex is given a capacity of 0. What does it return for the cost and the cost per bpd?', '["0.00 for the cost and 0.00 per bpd", "REFUSED: \"Missing capacity, fixed operating cost. Enter 0 where the value really is zero.\"", "the reference cost of 64000000.00, unscaled, and 12800.00 per bpd", "null for the cost and null for the cost per bpd"]'::jsonb, 3, 'scaleCapex returns null for the cost and for the per bpd figure when the capacity is 0, the reference cost is blank or the reference capacity is blank. That is no cost at all, a different answer from a zero cost of 0.00. The refusal in the options is feasibilityStreams'' sentence for a blank capacity and fixed operating cost.'),
  ('refinery', 'beginner', 'module', 'm01-what-a-feasibility-screen-computes', 10, 'feasibilityEconomics is called with the tax rate left blank. What does it return?', '["A valuation that reads the blank tax rate as 0 and values the project untaxed.", "REFUSED: \"A discount rate and a tax rate are needed to value the project.\"", "REFUSED: \"Missing capital cost. Enter 0 where the value really is zero.\"", "A valuation run at the engine''s stated default tax rate for a refinery."]'::jsonb, 1, 'A tax rate left out, a tax rate left blank and a discount rate typed as null all draw the same sentence: a discount rate and a tax rate are needed to value the project.'),
  ('refinery', 'beginner', 'module', 'm01-what-a-feasibility-screen-computes', 11, 'Streams that were refused for a blank crude cost are handed to feasibilityEconomics. What does the valuation return?', '["The streams'' own refusal, word for word, with the crude cost box still named", "REFUSED: \"A discount rate and a tax rate are needed to value the project.\"", "A valuation in which the crude cost column is read as 0.00 in every year.", "A valuation of the other columns, with the crude cost named as unpriced."]'::jsonb, 0, 'feasibilityEconomics refuses streams that carry a refusal, and the refusal travels forward with its words intact, so the reader of the valuation sees the same box named.'),
  ('refinery', 'beginner', 'module', 'm01-what-a-feasibility-screen-computes', 12, 'OKORDIA''s inputs include a fixed operating cost of 7500000.00 a year. Where does that figure enter the screen?', '["As a fourth term subtracted in the gross margin per barrel of 4.5900.", "As one of the three inputs multiplied into the throughput of 1518000.00 bbl.", "In neither the throughput nor the margin; it is a yearly line in the streams.", "As part of the capital of 64000000.00 spread over the construction years."]'::jsonb, 2, 'Annual throughput is capacity times on-stream days times utilisation, and the gross margin per barrel is gross value less crude cost less variable operating cost. The fixed cost appears as fixed opex of 7500000.00 in each producing year.'),
  ('refinery', 'beginner', 'module', 'm01-what-a-feasibility-screen-computes', 13, 'OKORDIA prices diesel at 101.0000 and gasoline at 104.0000 a barrel. What does the course say these prices are?', '["Market quotations for a stated date the screen was calibrated on.", "The real prices of the crude grades whose names appear on the Studio panel.", "Illustrative figures on invented records, set in US dollars.", "Averages of published prices the Studio refreshes itself."]'::jsonb, 2, 'The digest''s case line says all three records are invented and every price and cost in it is illustrative, in US dollars. None is a market quotation for any date, and a crude grade name is a label on invented yields and prices.'),
  ('refinery', 'beginner', 'module', 'm01-what-a-feasibility-screen-computes', 14, 'All three configurations are valued against one OKORDIA price table, and give 76.9400, 83.7900 and 90.6300. What differs between them to give three values?', '["The fixed yield row each configuration carries", "Their crude cost of 76.0000 a barrel", "The supply scenario each configuration is run under, firm or tight", "The capital each plant is quoted at"]'::jsonb, 0, 'The price table is shared and the crude cost is 76.0000 whichever plant is picked. The gross value is yields times prices, so the yield row is what moves 76.9400 to 83.7900 to 90.6300.'),
  ('refinery', 'beginner', 'module', 'm01-what-a-feasibility-screen-computes', 15, 'A screen refuses with "Missing crude cost. Enter 0 where the value really is zero." The user types 0 to clear it. What has the screen now been asked to value?', '["The firm case at 76.0000 a barrel", "A plant whose crude is free", "A plant with its crude cost left unknown", "The last crude cost typed into that box"]'::jsonb, 1, 'A typed 0 is a statement that the value is known and nothing. Typing it to clear a refusal makes the screen answer for free crude, which is why the sentence asks for 0 only where the value really is zero.'),
  ('refinery', 'beginner', 'module', 'm02-capital-and-the-scaling-law', 1, 'OKORDIA''s quotation is 64000000.00 for a 5000 bpd plant. Why does each scaling law return exactly 64000000.00 at 5000 bpd?', '["The engine snaps both laws to the quotation by tolerance.", "The capacity ratio is 1 there, and 1 raised to any exponent is 1.", "Both exponents are reset to 1 at the reference size.", "The stick-built figure is copied across into the modular column there."]'::jsonb, 1, 'scaleCapex computes cost = reference cost x (capacity / reference capacity) ^ exponent. At 5000 bpd the bracket is 1, so both laws return the quotation itself, and the ratio column reads 1.0000.'),
  ('refinery', 'beginner', 'module', 'm02-capital-and-the-scaling-law', 2, 'scaleCapex is called at 20000 bpd with no exponent passed. What does it return?', '["A cost of 147033389.44, reporting exponent 0.6 as the stick-built default", "null for the cost, because an exponent is a required input to the law", "A cost of 128000000.00 with an exponent of 1", "A cost of 222860944.20, reporting exponent 0.9"]'::jsonb, 3, 'scaleCapex defaults to the modular exponent when none is passed. 147033389.44 is the stick-built law at 20000 bpd, and 128000000.00 is the exponent of 1 figure at 10000 bpd.'),
  ('refinery', 'beginner', 'module', 'm02-capital-and-the-scaling-law', 3, 'Read the 10000 bpd row of scaleComparison. What cost does the stick-built law print there?', '["97005860.26", "119428222.92", "64000000.00", "42224253.14"]'::jsonb, 0, 'At 10000 bpd the stick-built law (0.6) prints 97005860.26 and the modular law (0.9) prints 119428222.92. 64000000.00 is the quotation itself at 5000 bpd, and 42224253.14 is the stick-built law at 2500 bpd.'),
  ('refinery', 'beginner', 'module', 'm02-capital-and-the-scaling-law', 4, 'What do the ratio and the modular cheaper flag read at 2500 bpd?', '["A ratio of 1.2311, and modular cheaper false", "A ratio of 0.6170, modular cheaper true", "A ratio of 0.8123, and modular cheaper true", "A ratio of 0.8123, and modular cheaper false, since both laws equal"]'::jsonb, 2, 'The ratio is the modular cost over the stick-built cost. At 2500 bpd it reads 0.8123 and modular cheaper reads true. 0.6170 is the 1000 bpd row and 1.2311 the 10000 bpd row.'),
  ('refinery', 'beginner', 'module', 'm02-capital-and-the-scaling-law', 5, 'At 5000 bpd the modular cheaper flag reads false. What does the table say about the two laws at that size?', '["Neither is cheaper: the two laws equal flag reads true.", "The stick-built law is cheaper there, since modular cheaper reads false.", "The modular law is dearer there by its ratio of 1.0000.", "Both flags read false, so the comparison is undecided."]'::jsonb, 0, 'At the reference size both laws return 64000000.00, the ratio reads 1.0000 and the two laws equal flag reads true. Reading modular cheaper false as a win for stick-built is the mistake the lesson names.'),
  ('refinery', 'beginner', 'module', 'm02-capital-and-the-scaling-law', 6, 'At 30000 bpd, which law gives the lower capital, and what does it print?', '["The modular law, at 321008180.00", "The stick-built law, at 187529987.30", "The modular law, at 187529987.30, with its per bpd of 6251.00", "The stick-built law, at 321008180.00, with its per bpd of 10700.27"]'::jsonb, 1, 'Above the reference size modular cheaper reads false. At 30000 bpd the stick-built law (0.6) prints 187529987.30 against the modular law''s 321008180.00, a ratio of 1.7118.'),
  ('refinery', 'beginner', 'module', 'm02-capital-and-the-scaling-law', 7, 'Scaled with an exponent of 1 to 10000 bpd, the quotation gives 128000000.00 and 12800.00 per bpd. Why does the per bpd figure equal the reference row''s?', '["The engine holds per bpd fixed at its reference value on every law.", "Doubling capacity doubles the exponent, cancelling the capacity ratio.", "The per bpd column is copied from the 5000 bpd row when the ratio is blank.", "An exponent of 1 puts cost in proportion to capacity, so each bpd costs what it did at 5000 bpd."]'::jsonb, 3, 'Cost in proportion to capacity means every barrel a day costs 12800.00, the reference row''s figure, whatever the size. Both real laws print per bpd figures that change with capacity.'),
  ('refinery', 'beginner', 'module', 'm02-capital-and-the-scaling-law', 8, 'Down the scaleComparison table, what does the screen check about capital per bpd and total capital as capacity rises?', '["Per bpd falls under stick-built only; modular per bpd holds at 12800.00.", "Per bpd rises at every step and total rises at every step, under both laws.", "Per bpd falls at every step and total rises at every step, true under both laws.", "Total rises under the modular law only, and per bpd goes unchecked."]'::jsonb, 2, 'The digest prints: capital per bpd falls at every step as capacity rises, modular true, stick-built true; total capital rises at every step, modular true, stick-built true. The plant costs more and each bpd of it costs less.'),
  ('refinery', 'beginner', 'module', 'm02-capital-and-the-scaling-law', 9, 'Read the modular cheaper flags in scaleComparison. Which exponent gives the lower capital above the reference size of 5000 bpd, and which below it?', '["0.6 above it, and 0.9 below it", "0.9 above it, and 0.6 below it", "0.6 above it and below it alike", "0.9 at every size from 1000 to 30000"]'::jsonb, 0, 'Modular cheaper reads true at 1000 and 2500 bpd, where the modular law (0.9) gives the lower cost, and false at 10000, 20000 and 30000 bpd, where the stick-built law (0.6) does. At 5000 bpd the two laws equal flag reads true.'),
  ('refinery', 'beginner', 'module', 'm02-capital-and-the-scaling-law', 10, 'What capital per bpd do the two laws print at 2500 bpd?', '["16889.70 on the modular law, 13718.70 on the stick-built", "15035.12 modular, 24366.77 stick-built", "12800.00 on both laws, the quotation''s own figure", "13718.70 on the modular law, 16889.70 on the stick-built"]'::jsonb, 3, 'The 2500 bpd row prints 13718.70 per bpd on the modular law and 16889.70 on the stick-built law. 15035.12 and 24366.77 are the 1000 bpd row, and 12800.00 is the 5000 bpd row, where both laws return the quotation.'),
  ('refinery', 'beginner', 'module', 'm02-capital-and-the-scaling-law', 11, 'What does the course hold about the exponents 0.6 and 0.9 as held item H1?', '["They are published industry constants that the engine cites.", "They are defaults for a vendor''s own figures to replace.", "They are fixed in the engine and cannot be overridden by a user.", "They are graded values the capstone asks a learner to compute with."]'::jsonb, 1, 'H1 says the scaling exponents 0.6 and 0.9 are defaults for a vendor''s own figures to replace, and no published source for them is in the engines repository. The engine names them as overridable parameters.'),
  ('refinery', 'beginner', 'module', 'm02-capital-and-the-scaling-law', 12, 'Held item H1 names something the engines repository does not hold for the exponents 0.6 and 0.9. What is it?', '["A way to override them on a call", "A default for a call that passes no exponent", "A published source for either exponent", "A stick-built law to set beside the modular"]'::jsonb, 2, 'The held item says no published source for the two exponents is in the engines repository. The other three options are in the engine: the exponents are named, overridable parameters; scaleCapex falls back on 0.9 when none is passed; and scaleComparison prints the stick-built law beside the modular at every size.'),
  ('refinery', 'beginner', 'module', 'm02-capital-and-the-scaling-law', 13, 'At 10000 bpd the modular law prints 11942.82 per bpd and the stick-built law 9700.59. What is the gap between them?', '["The gap between two exponents applied to one quotation", "An economy of scale measured across two real plants", "The gap between nameplate and annual throughput", "A second vendor quotation set against the first"]'::jsonb, 0, 'Both figures come from the one 64000000.00 quotation for 5000 bpd. The gap is the gap between 0.9 and 0.6, and that gap is an assumption.'),
  ('refinery', 'beginner', 'module', 'm02-capital-and-the-scaling-law', 14, 'OKORDIA''s screen prints a capital per bpd of 12800.00. What is that a cost per?', '["Barrel of crude refined over a whole year", "Barrel of product sold in the first year", "Barrel a day of capacity at nameplate", "Barrel of throughput at the plant''s utilisation on each on-stream day"]'::jsonb, 2, 'Capacity is what the plant was built for and throughput is what it does. Capital per bpd divides by capacity, 5000 bpd, and leaves the throughput out.'),
  ('refinery', 'beginner', 'module', 'm02-capital-and-the-scaling-law', 15, 'At which capacity does scaleComparison print a ratio of 1.5157?', '["10000 bpd", "20000 bpd", "30000 bpd", "2500 bpd"]'::jsonb, 1, 'The ratio reads 0.6170 at 1000 bpd, 0.8123 at 2500, 1.0000 at 5000, 1.2311 at 10000, 1.5157 at 20000 and 1.7118 at 30000 bpd.'),
  ('refinery', 'beginner', 'module', 'm03-the-product-slate', 1, 'Which two units does a hydroskimming plant carry on top of crude distillation?', '["A fluid catalytic cracker and a hydrotreater", "A naphtha reformer and a catalytic cracker", "A diesel hydrotreater alone, since the naphtha is sold as it comes", "A naphtha reformer and a diesel hydrotreater"]'::jsonb, 3, 'Topping is crude distillation alone. Hydroskimming adds a naphtha reformer and a diesel hydrotreater, and conversion adds a fluid catalytic cracker to those.'),
  ('refinery', 'beginner', 'module', 'm03-the-product-slate', 2, 'The hydroskimming yield row prints a dash under naphtha. What does the dash mean for its slate?', '["The naphtha yield is unknown, so it is named as unpriced.", "The plant makes none, so the slate carries no naphtha row.", "Naphtha is made and valued at zero, like the loss.", "The naphtha yield is folded into the loss column of 0.0200."]'::jsonb, 1, 'A dash means the configuration makes none of that product. Topping sells naphtha at a yield of 0.1800 and no gasoline; hydroskimming and conversion sell gasoline and no naphtha, because the reformer takes it.'),
  ('refinery', 'beginner', 'module', 'm03-the-product-slate', 3, 'Read the fuelOil column of the yield table. What is the conversion plant''s fuelOil yield?', '["0.3000", "0.3400", "0.1400", "0.3300"]'::jsonb, 2, 'The fuelOil column reads 0.3400 for topping, 0.3000 for hydroskimming and 0.1400 for conversion. 0.3300 is conversion''s diesel yield.'),
  ('refinery', 'beginner', 'module', 'm03-the-product-slate', 4, 'In the topping slate, diesel carries a yield of 0.3000 at a price of 101.0000. What value per barrel of crude does its row print?', '["30.3000", "32.3200", "33.3300", "101.0000"]'::jsonb, 0, 'productSlate values each product at its yield times its price, per barrel of crude. 32.3200 and 33.3300 are diesel''s rows in the hydroskimming and conversion slates, and 101.0000 is the price, a figure per barrel of diesel.'),
  ('refinery', 'beginner', 'module', 'm03-the-product-slate', 5, 'Which gross value per barrel of crude does the conversion slate print at OKORDIA''s prices?', '["83.7900", "76.9400", "90.6300", "81.1900"]'::jsonb, 2, 'Topping prints 76.9400, hydroskimming 83.7900 and conversion 90.6300. 81.1900 is the hydroskimming row typed with yields that total 0.9700.'),
  ('refinery', 'beginner', 'module', 'm03-the-product-slate', 6, 'How does productSlate treat the loss of 0.0200 that every configuration carries?', '["As a yield with no value, so the row closes and nothing is added for it", "As a cost line, subtracted from the gross margin per barrel", "It is dropped from the row, and the other yields are scaled up", "As a yield valued at the crude cost of 76.0000 a barrel"]'::jsonb, 0, 'The loss sits in the yield row beside the products, so yields total 1.0000 and yields close true. It has no price, so nothing is added to the gross value for it.'),
  ('refinery', 'beginner', 'module', 'm03-the-product-slate', 7, 'The gross margin per barrel has no separate term for the loss. Where does the loss reach the margin?', '["In the variable operating cost on each barrel", "As a fourth term the margin subtracts after the variable cost", "Nowhere, since the loss is dropped once the yields are summed", "Inside the gross value, as a yield that adds nothing"]'::jsonb, 3, 'productSlate carries the loss as a yield with no value, so it sits in the yield row and adds nothing to the gross value per barrel of crude. The gross margin per barrel is gross value less crude cost less variable operating cost, so the loss reaches the margin through the gross value and has no term of its own.'),
  ('refinery', 'beginner', 'module', 'm03-the-product-slate', 8, 'Topping is valued with the naphtha price left blank. What does productSlate return?', '["A refusal naming naphtha, as a blank money box on the inputs is refused", "Gross value 63.6200; unpriced: naphtha", "Gross value 76.9400; naphtha valued at its last typed price", "Gross value 63.6200; unpriced: none, since the row still closes"]'::jsonb, 1, 'A blank product price is answered, with the product named on the unpriced list and adding nothing. In the full slate naphtha''s row carries 13.3200 a barrel of crude.'),
  ('refinery', 'beginner', 'module', 'm03-the-product-slate', 9, 'Topping is valued with the naphtha price left blank and prints a gross value of 63.6200. What on the slate says a product is missing from that figure?', '["The unpriced list, which names naphtha", "A refusal beside the figure", "A gross value printed as null in its place", "Nothing; 63.6200 is the whole value"]'::jsonb, 0, 'The engine prints gross value 63.6200; unpriced: naphtha. The unpriced product is named and adds nothing to the value. The figure is in the same unit and at the same precision as the full topping slate''s 76.9400, so only the list shows that naphtha is missing.'),
  ('refinery', 'beginner', 'module', 'm03-the-product-slate', 10, 'The hydroskimming yields are typed so they total 0.9700. What does productSlate do with the row?', '["Scales every yield up so the row totals 1.0000, and prints 83.7900.", "Values it as typed, prints 81.1900 and sets yields close to false.", "Refuses the row by name until the yields total 1.0000 again.", "Adds the missing fraction to the loss and sets yields close to true."]'::jsonb, 1, 'The engine reports the gap and does not normalise the yields. Normalising would spread the missing fraction across every product, a guess nobody made.'),
  ('refinery', 'beginner', 'module', 'm03-the-product-slate', 11, 'Compare OKORDIA''s hydroskimming row with the typed row that totals 0.9700. Which typed yields differ?', '["lpg, kerosene and the loss row", "gasoline, kerosene and diesel", "diesel, fuelOil and the loss", "gasoline, diesel and fuelOil"]'::jsonb, 3, 'The typed row reads gasoline 0.1900, diesel 0.3100 and fuelOil 0.2900 against 0.2000, 0.3200 and 0.3000. lpg 0.0300, kerosene 0.1300 and the loss 0.0200 are unchanged.'),
  ('refinery', 'beginner', 'module', 'm03-the-product-slate', 12, 'Which three check lines does the engine print under each slate?', '["gross value, gross margin, unpriced list", "yields total, the loss, and the capital per bpd", "yields total, yields close, and the unpriced list", "yields close, the loss, and the ratio flag"]'::jsonb, 2, 'On all three configurations at OKORDIA''s prices they read yields total 1.0000, yields close true, unpriced: none. Between them they say whether the gross value describes a complete, fully priced barrel.'),
  ('refinery', 'beginner', 'module', 'm03-the-product-slate', 13, 'The yield table carries three rows: topping, hydroskimming and conversion. What does each row describe?', '["What one plant''s units make of the same crude", "One of three crudes run through one plant", "One crude''s assay at three cut points", "Three supply scenarios for the same plant and crude"]'::jsonb, 0, 'They are three plants running one crude. OKORDIA''s crude costs 76.0000 a barrel whichever configuration is picked, and the yields describe what the units make of it.'),
  ('refinery', 'beginner', 'module', 'm03-the-product-slate', 14, 'In the hydroskimming slate, which product brings in the most per barrel of crude?', '["gasoline, the highest priced product, at 20.8000", "diesel, at 32.3200", "fuelOil, 16.5000", "kerosene, at 12.6100 on a price of 97.0000"]'::jsonb, 1, 'The value column reads lpg 1.5600, gasoline 20.8000, kerosene 12.6100, diesel 32.3200 and fuelOil 16.5000. Gasoline has the highest price at 104.0000, but diesel''s larger yield of 0.3200 gives the larger value.'),
  ('refinery', 'beginner', 'module', 'm03-the-product-slate', 15, 'Topping''s fuelOil row reads 18.7000 a barrel of crude and conversion''s 7.7000. What does the pair show?', '["Conversion sells fuel oil at a lower price than topping does.", "Topping runs more crude through the plant each year.", "Conversion puts fewer of its barrels into fuel oil.", "Conversion carries a larger loss inside its fuelOil value."]'::jsonb, 2, 'Both slates price fuel oil at 55.0000. The value moves with the yield: 0.3400 for topping and 0.1400 for conversion, where the cracker turns heavy material into lighter products.'),
  ('refinery', 'beginner', 'module', 'm04-throughput-and-the-gross-margin', 1, 'OKORDIA is run at a utilisation of 1, with its 5000 bpd and its 330 on-stream days unchanged. What annual throughput does the screen print?', '["1518000.00 bbl, the firm supply figure", "1530000.00 bbl, as with every term left out", "1650000.00 bbl", "5000 bpd over all 366 possible days"]'::jsonb, 2, 'At utilisation 1 the plant runs at nameplate on every on-stream day and the engine prints 1650000.00 bbl. The firm supply case, 1518000.00 bbl, shares the capacity and the on-stream days and differs in utilisation alone. 1530000.00 bbl belongs to the engine''s defaults.'),
  ('refinery', 'beginner', 'module', 'm04-throughput-and-the-gross-margin', 2, 'OKORDIA is screened with its on-stream days box left blank. What annual throughput comes back?', '["1530000.00 bbl, the figure the engine''s defaults give", "REFUSED: \"On-stream days must be between 1 and 366.\"", "1518000.00 bbl, as the blank keeps OKORDIA''s 330 days", "0.00 bbl, since a blank day count runs no days at all"]'::jsonb, 0, 'A schedule term left blank or left out reads as the engine''s stated default for that term. With on-stream days blank the plant prints 1530000.00 bbl, as it does with every schedule term left out. OKORDIA''s own inputs give 1518000.00 bbl, so check that each term is typed before reading the throughput.'),
  ('refinery', 'beginner', 'module', 'm04-throughput-and-the-gross-margin', 3, 'Utilisation is tried on OKORDIA as 90, as -0.1, as 0 and left blank. Which entry returns an annual throughput of 0.00 bbl?', '["-0.1, read as a plant that is shut", "The blank, read as nothing typed", "90, clipped to the top of its range", "0, which lies inside the range"]'::jsonb, 3, '90 and -0.1 lie outside 0 to 1 and are refused with the example 0.9 for 90 percent. A blank utilisation reads as the engine''s stated default and gives 1530000.00 bbl. A typed 0 is inside the range, so the engine answers it: annual throughput 0.00 bbl.'),
  ('refinery', 'beginner', 'module', 'm04-throughput-and-the-gross-margin', 4, 'OKORDIA''s annual throughput of 1518000.00 bbl is built from three inputs. Which of these is not one of them?', '["The capacity of 5000 bpd at nameplate", "The variable cost of 3.2000 a barrel", "The 330 on-stream days in a year", "The firm supply utilisation of 0.9200"]'::jsonb, 1, 'The engine prints annual throughput = capacity x on-stream days x utilisation: 1518000.00 bbl. The variable operating cost of 3.2000 a barrel enters the gross margin per barrel and the variable opex column.'),
  ('refinery', 'beginner', 'module', 'm04-throughput-and-the-gross-margin', 5, 'OKORDIA''s gross margin per barrel reads 4.5900. Which figures does the engine take it from?', '["Gross value 83.7900, less crude 79.0000, less variable cost 3.2000", "Gross value 83.7900, less crude 76.0000, less variable cost 3.2000", "Gross value 83.7900, less crude 76.0000, less fixed cost 7500000.00", "Revenue 127193220.00, less crude cost 115368000.00 and fixed opex"]'::jsonb, 1, 'The engine states gross margin per barrel = gross value - crude cost - variable operating cost, all per barrel of crude. 79.0000 is the crude cost under tight supply, and the fixed cost is a yearly line in the streams.'),
  ('refinery', 'beginner', 'module', 'm04-throughput-and-the-gross-margin', 6, 'Years 0 and 1 of OKORDIA''s streams each carry capex of 32000000.00. What rule gives that figure?', '["The stick-built law''s share of the capital in each year", "The capital less a year of fixed opex of 7500000.00", "A vendor quotation made for each construction year", "The capital spread evenly over the 2 construction years"]'::jsonb, 3, 'The engine spreads the capital evenly over the construction years: capital / construction years. With 2 construction years, years 0 and 1 carry 32000000.00 each; with three they carry 21333333.33 each. The capital itself is 64000000.00, the modular law at the reference point.'),
  ('refinery', 'beginner', 'module', 'm04-throughput-and-the-gross-margin', 7, 'The crude cost is raised on the panel and nothing else is touched. Which columns of the streams move?', '["The crude cost column, while revenue stays still", "Revenue and crude cost together, with crude run", "The fixed opex column, which follows the crude price", "Crude cost and capex, since capital buys the crude"]'::jsonb, 0, 'Revenue is crude run times gross value, and the crude price is in neither. A change in capacity moves crude run, revenue and crude cost together; the fixed opex column moves only when the fixed operating cost itself changes.'),
  ('refinery', 'beginner', 'module', 'm04-throughput-and-the-gross-margin', 8, 'Read year 1 of OKORDIA''s streams. What does it carry?', '["Producing true, crude run 1518000.00 bbl, no capex", "Producing false, fixed opex 7500000.00, no capex", "Producing false, crude run 0.00 bbl, capex 32000000.00", "Producing true, capex 32000000.00, half the run"]'::jsonb, 2, 'Year 1 is OKORDIA''s second construction year: producing false, crude run 0.00 bbl and capex 32000000.00. Fixed opex starts in the first producing year: year 1 0.00, year 2 7500000.00.'),
  ('refinery', 'beginner', 'module', 'm04-throughput-and-the-gross-margin', 9, 'With OKORDIA''s 2 construction years and 20 operating years, which are the first and the last producing years?', '["Year 1 first, and year 20 the last", "Year 2 first, and year 22 last", "Year 0 first, and year 21 last", "Year 2 first, and year 21 the last"]'::jsonb, 3, 'Years 0 and 1 carry the capital and nothing else. The first producing year is year 2 and the last is year 21, and the streams hold 22 years because they start at year 0.'),
  ('refinery', 'beginner', 'module', 'm04-throughput-and-the-gross-margin', 10, 'How does the screen build the revenue of 127193220.00 in a producing year?', '["Crude run 1518000.00 x crude cost 76.0000", "Crude run 1518000.00 x gross value 83.7900", "Capacity 5000 x 330 days x the value 83.7900", "Crude run 1518000.00 x gross margin 4.5900"]'::jsonb, 1, 'The engine prints revenue = crude run x gross value per barrel: 1518000.00 x 83.7900 = 127193220.00. Crude run times the crude cost of 76.0000 is the crude cost column, 115368000.00.'),
  ('refinery', 'beginner', 'module', 'm04-throughput-and-the-gross-margin', 11, 'The screen prints 22 years in OKORDIA''s streams. Which inputs give that count?', '["2 construction years plus 20 operating years", "20 operating years plus years 0 and 21 at either end", "The last year, 21, plus the first producing year", "22 producing years after the build is finished"]'::jsonb, 0, 'Years in the streams are the construction years plus the operating years. The same rule gives 20 years with no construction period and 23 with three construction years.'),
  ('refinery', 'beginner', 'module', 'm04-throughput-and-the-gross-margin', 12, 'OKORDIA is laid out with three construction years. What capex does each of them print, and what does the screen check?', '["21333333.33 in each year, with the rounding cent put into the last", "32000000.00 in the first two years and nothing at all in the third", "21333333.33 each, and the unrounded thirds sum to the capital: true", "64000000.00 in year 0, with the later construction years left at 0.00"]'::jsonb, 2, 'The screen prints capital / construction years = 64000000.00 / 3. Each year is printed to the cent, and the engine carries the unrounded thirds, which sum to the capital: true. Nothing of the 64000000.00 is lost to rounding.'),
  ('refinery', 'beginner', 'module', 'm04-throughput-and-the-gross-margin', 13, 'OKORDIA is laid out with no construction period at all. What does year 0 carry?', '["Capex 64000000.00 and a crude run of 0.00 bbl", "Capex 32000000.00 and a crude run of 1518000.00 bbl", "Capex 64000000.00 and a crude run of 1518000.00 bbl", "No capex, as the capital moves into the first operating year"]'::jsonb, 2, 'With no construction period the capital is spent in year 0, the first operating year, and the plant also runs that year: year 0 capex 64000000.00, year 0 crude run 1518000.00 bbl, and 20 years in the streams.'),
  ('refinery', 'beginner', 'module', 'm04-throughput-and-the-gross-margin', 14, 'The construction years on the panel go from 2 to 3. Which of these changes?', '["The first producing year, from year 2 to year 3", "The capital, which grows with the longer build", "The gross margin per barrel of 4.5900", "The annual throughput of 1518000.00 bbl"]'::jsonb, 0, 'The capital typed into the screen is 64000000.00 in every case. Construction changes when the plant earns, and the streams grow from 22 years to 23. It does not change what a barrel earns or how many barrels a year are run.'),
  ('refinery', 'beginner', 'module', 'm04-throughput-and-the-gross-margin', 15, 'The screen checks that every producing year carries the same figures as year 2, and prints true. What does that tell a reader about the streams?', '["Yields are re-checked for age each year.", "They carry no ramp up, price path or turnaround year.", "Year 2 is an average of the producing years.", "Only years 0 to 3 and year 21 are passed on for valuation."]'::jsonb, 1, 'The streams are one producing year repeated, from year 2 to year 21. That keeps the valuation traceable, and it means no ramp up after start, no price path, no change in yields with age and no turnaround year.'),
  ('refinery', 'beginner', 'module', 'm05-crude-supply-and-licensing', 1, 'Which utilisation and crude premium does the tight supply scenario carry?', '["Utilisation 0.5000 and a premium of 6.0000 a barrel", "Utilisation 0.7500 and a premium of 3.0000 a barrel", "Utilisation 0.9200 and a premium of 0.0000", "Utilisation 0.7500 and a premium of 6.0000 a barrel"]'::jsonb, 1, 'SUPPLY_SCENARIOS prints firm at 0.9200 and 0.0000, tight at 0.7500 and 3.0000, and disrupted at 0.5000 and 6.0000. Each scenario sets both inputs together.'),
  ('refinery', 'beginner', 'module', 'm05-crude-supply-and-licensing', 2, 'Which scenario carries the note "Cargoes are available but contested: the plant runs below nameplate and pays up for barrels."?', '["Disrupted supply, as its second sentence", "Firm supply, on a contract under strain", "None; it is a note from the licensing tracker", "Tight supply, at a utilisation of 0.7500"]'::jsonb, 3, 'The tight note describes both of its changes at once: fewer barrels run, and more paid for each. Firm''s note is about a term contract that is honoured, and disrupted''s says interruptions are routine.'),
  ('refinery', 'beginner', 'module', 'm05-crude-supply-and-licensing', 3, 'What probability does the engine attach to the disrupted scenario?', '["None; the scenarios are named futures only", "0.5000, the share of the years that are disrupted", "An equal weight with firm and tight, for averaging", "One set by the premium of 6.0000 a barrel"]'::jsonb, 0, 'The scenarios carry no probability. A probability would invite a weighted answer describing a plant that never exists, part firm and part disrupted every year, so the screen keeps the three apart and a reader sees each whole.'),
  ('refinery', 'beginner', 'module', 'm05-crude-supply-and-licensing', 4, 'Tight supply is picked for OKORDIA, whose own utilisation is 0.9200. Which inputs change?', '["Utilisation to 0.7500, with the crude cost kept at 76.0000", "The crude cost to 79.0000, with utilisation kept at 0.9200", "Utilisation to 0.7500 and the crude cost from 76.0000 to 79.0000", "The gross value from 83.7900 and the crude cost to 79.0000"]'::jsonb, 2, 'A scenario''s utilisation replaces the plant''s, and its premium is added to the crude cost before the streams are built. Tight supply does both in one move. The gross value comes from the slate and is 83.7900 under every scenario.'),
  ('refinery', 'beginner', 'module', 'm05-crude-supply-and-licensing', 5, 'What annual throughput does OKORDIA print under disrupted supply, and which input sets it?', '["825000.00 bbl, set by a utilisation of 0.5000", "1237500.00 bbl, set by a utilisation of 0.7500", "825000.00 bbl, set by the premium of 6.0000", "1518000.00 bbl, as supply moves only the price"]'::jsonb, 0, 'Annual throughput is capacity times on-stream days times utilisation, and the premium is not in that formula. The throughput column reads 1518000.00, 1237500.00 and 825000.00 bbl as utilisation reads 0.9200, 0.7500 and 0.5000.'),
  ('refinery', 'beginner', 'module', 'm05-crude-supply-and-licensing', 6, 'In OKORDIA''s scenario table, which column is set by the premium alone, whatever the utilisation?', '["The annual throughput in barrels", "The first operating year revenue", "The gross margin, in dollars a barrel", "The first year''s crude cost in dollars"]'::jsonb, 2, 'The margin is gross value less crude cost less variable operating cost, and the premium goes into the crude cost; utilisation is not in it. So the margin reads 4.5900, 1.5900 and -1.4100 as the crude cost reads 76.0000, 79.0000 and 82.0000. Both annual money columns move with the barrels too.'),
  ('refinery', 'beginner', 'module', 'm05-crude-supply-and-licensing', 7, 'A reader models tight supply by cutting the run to 1237500.00 bbl and keeping the firm margin of 4.5900. What have they got wrong?', '["The run, which the tight row prints as 825000.00 bbl", "Nothing, since the premium moves the revenue alone", "The gross value, printed as 79.0000", "The margin, which the tight row prints as 1.5900"]'::jsonb, 3, 'The scenario is one choice that sets two inputs. The run of 1237500.00 bbl is right, and the margin is not: the premium raises the crude cost to 79.0000 and the engine prints 1.5900. 825000.00 bbl is the disrupted run.'),
  ('refinery', 'beginner', 'module', 'm05-crude-supply-and-licensing', 8, 'Hydroskimming under disrupted supply prints a gross margin per barrel of -1.4100. What does that sign say about running more barrels?', '["More barrels would spread the fixed cost and cure the loss.", "Each barrel run loses money before any fixed cost is paid.", "The plant breaks even once it runs past 825000.00 bbl a year.", "The loss sits in the fixed cost, so the barrels themselves pay."]'::jsonb, 1, 'A negative margin per barrel is a different kind of answer from a small one. Each barrel costs more to buy and process than its products sell for, so running more would lose more. The disrupted note says this is where most of these projects are actually decided.'),
  ('refinery', 'beginner', 'module', 'm05-crude-supply-and-licensing', 9, 'Which first operating year revenue and crude cost does OKORDIA print under disrupted supply?', '["103690125.00 and 97762500.00", "69126750.00 and 67650000.00", "69126750.00 and 115368000.00", "127193220.00 and 115368000.00"]'::jsonb, 1, 'The disrupted row reads revenue 69126750.00 and crude cost 67650000.00. 103690125.00 and 97762500.00 are the tight row, and 127193220.00 and 115368000.00 the firm row. Both money columns move with the scenario.'),
  ('refinery', 'beginner', 'module', 'm05-crude-supply-and-licensing', 10, 'What is the second stage in LICENSING_STAGES, and what is its id?', '["Licence to Construct, id ltc", "Licence to Operate, with id lto", "Licence to Establish, id lte", "Licence to Construct, id lto"]'::jsonb, 0, 'The stages run 1 lte Licence to Establish, 2 ltc Licence to Construct and 3 lto Licence to Operate, in that order.'),
  ('refinery', 'beginner', 'module', 'm05-crude-supply-and-licensing', 11, 'In which stage''s typical evidence does the feasibility study sit?', '["Licence to Construct, beside the detailed engineering design", "Licence to Operate, beside the pre-startup safety review", "In none of the three; the tracker leaves the study out", "Licence to Establish, beside site title and evidence of funding"]'::jsonb, 3, 'The first stage asks whether the project is real: a feasibility study, site title or lease, evidence of funding and environmental impact assessment scoping. This tier''s screen is the kind of study that goes into that application.'),
  ('refinery', 'beginner', 'module', 'm05-crude-supply-and-licensing', 12, 'A team has ticked all three stages in the tracker. What has that shown?', '["That the regulator has approved each of the three licences", "That each stage''s typical evidence has been filed in full", "What the team has ticked, as the regulator''s current requirements govern", "That the project may begin its producing years at once"]'::jsonb, 2, 'The tracker is a process aid. It records which stages are complete and names the next, and it does not know the regulator''s forms, fees or timelines. Whether the regulator agrees is answered by the regulator.'),
  ('refinery', 'beginner', 'module', 'm05-crude-supply-and-licensing', 13, 'A project has ticked ltc alone. What does the tracker return?', '["Count 1, next Licence to Establish, out of order true", "Count 1, next Licence to Operate, out of order false", "Count 1, next Licence to Construct, out of order false", "Count 0, next Licence to Establish, out of order true"]'::jsonb, 0, 'The next stage is the first stage in sequence that is not complete, and lte is still open, so the tracker sends the project back to it and flags the tick as out of order. lte alone gives count 1, next Licence to Construct, out of order false.'),
  ('refinery', 'beginner', 'module', 'm05-crude-supply-and-licensing', 14, 'Which column of the tracker''s return reads the same for lte ticked alone and for ltc ticked alone?', '["The next stage named", "The out of order flag", "None; all three differ", "The complete count"]'::jsonb, 3, 'Both rows carry a complete count of 1. The next stage reads Licence to Construct against Licence to Establish, and out of order reads false against true, which is why a count reported alone misleads.'),
  ('refinery', 'beginner', 'module', 'm05-crude-supply-and-licensing', 15, 'All three stages, lte, ltc and lto, are ticked. What does the tracker name as the next stage?', '["lto, the last stage ticked", "null, with nothing left to name", "Licence to Establish, as the cycle begins again", "Licence to Operate, flagged out of order true"]'::jsonb, 1, 'With all three complete the count is 3, the next stage is null and out of order reads false. There is no stage left, and the tracker says so with no stage at all.'),
  ('refinery', 'beginner', 'module', 'm06-the-associate-reading', 1, 'In the nine-row table, which configuration keeps a positive gross margin per barrel under disrupted supply?', '["Hydroskimming alone, at 1.5900", "Conversion and hydroskimming, both above zero", "None; every configuration is negative under disruption", "Conversion alone, at 5.4300"]'::jsonb, 3, 'Under disrupted supply topping reads -8.2600, hydroskimming -1.4100 and conversion 5.4300. 1.5900 is hydroskimming under tight supply.'),
  ('refinery', 'beginner', 'module', 'm06-the-associate-reading', 2, 'Read down the three hydroskimming rows of the nine-row table. Which figure stays the same from firm to disrupted?', '["The annual throughput, 1518000.00 bbl", "The gross value per barrel, 83.7900", "The gross margin per barrel, 4.5900", "The first year revenue, 127193220.00"]'::jsonb, 1, 'The slate does not depend on supply, so the gross value holds at 83.7900 on all three rows. The throughput moves with the scenario''s utilisation and the margin with its premium.'),
  ('refinery', 'beginner', 'module', 'm06-the-associate-reading', 3, 'Hold the scenario at tight and compare topping, hydroskimming and conversion. What is common to all three rows?', '["A throughput of 1237500.00 bbl", "A gross value per barrel of 76.9400", "A gross margin per barrel of 1.5900", "A first year revenue of 103690125.00"]'::jsonb, 0, 'The configuration does not change how many barrels are run, so every tight row runs 1237500.00 bbl. What moves across configurations is the gross value, and with it the margin and the revenue.'),
  ('refinery', 'beginner', 'module', 'm06-the-associate-reading', 4, 'Topping under firm supply shows a first operating year revenue of 116794920.00. What does its row say about the plant?', '["It earns 4.5900 on every barrel before the fixed cost.", "Its large revenue carries it past its fixed operating cost.", "It loses money on every barrel, at a margin of -2.2600.", "It loses money only when supply turns tight or disrupted."]'::jsonb, 2, 'Revenue counts what the products sell for. A revenue of any size on a negative margin is a loss on every barrel run, with the fixed operating cost and the capital still to pay. 4.5900 is hydroskimming under firm supply.'),
  ('refinery', 'beginner', 'module', 'm06-the-associate-reading', 5, 'Which configuration''s margin changes sign with the supply scenario?', '["Topping: negative on firm, positive on both tight and disrupted supply", "Conversion: positive on firm, negative on tight and disrupted", "Hydroskimming: positive on firm and tight, negative on disrupted", "All three: each positive on firm and negative on disrupted"]'::jsonb, 2, 'Hydroskimming reads 4.5900, 1.5900 and -1.4100. Topping is negative on all three scenarios and conversion positive on all three, so hydroskimming is the one whose reading depends on supply.'),
  ('refinery', 'beginner', 'module', 'm06-the-associate-reading', 6, 'Which row of the nine-row table prints a first operating year revenue of 63475500.00?', '["Topping under disrupted supply", "Topping under tight supply", "Hydroskimming under disrupted supply", "Conversion under disrupted supply"]'::jsonb, 0, 'Topping under disrupted supply prints 63475500.00. Topping under tight supply prints 95213250.00, hydroskimming under disrupted supply 69126750.00 and conversion under disrupted supply 74769750.00.'),
  ('refinery', 'beginner', 'module', 'm06-the-associate-reading', 7, 'In the OKORDIA chain, which step takes 5000 bpd, 330 on-stream days and a utilisation of 0.9200?', '["Capital, returning 64000000.00 at 12800.00 per bpd", "Margin, returning 4.5900 a barrel of crude", "Streams, returning 22 years with revenue from year 2", "Throughput, returning 1518000.00 bbl a year"]'::jsonb, 3, 'Throughput is capacity times on-stream days times utilisation. Capital takes the quotation and the law, the margin takes the gross value and two costs, and the streams take the construction and operating years.'),
  ('refinery', 'beginner', 'module', 'm06-the-associate-reading', 8, 'Why does the choice of exponent not change OKORDIA''s capital of 64000000.00?', '["The modular exponent is fixed in the engine and cannot be changed.", "It is screened at the reference size, where both laws give the quotation.", "Its capital is spread over 2 construction years, cancelling the exponent.", "The capital per bpd of 12800.00 is set before any exponent applies."]'::jsonb, 1, 'OKORDIA is screened at 5000 bpd, the size of the quotation, so the capital is the quotation itself on either law. At any other size the exponent would matter, and the exponents are defaults that a vendor''s figures replace.'),
  ('refinery', 'beginner', 'module', 'm06-the-associate-reading', 9, 'The crude cost in OKORDIA''s streams looks wrong. Where does the lesson send you to check?', '["The crude price, the premium and the throughput", "The slate and the throughput, as with revenue", "The quotation, the capacity and the exponent", "The fixed cost and the count of construction years"]'::jsonb, 0, 'Every step feeds the next, so a surprising figure has its cause at one step. Revenue sends you to the slate and the throughput; capex to the quotation, the capacity, the exponent and the construction years.'),
  ('refinery', 'beginner', 'module', 'm06-the-associate-reading', 10, 'Under firm supply, which configuration earns the most per barrel of crude, and at what gross margin?', '["Hydroskimming, at 4.5900", "Conversion, at 8.4300", "Topping, at -2.2600", "Conversion, at 11.4300"]'::jsonb, 3, 'The three firm rows read topping -2.2600, hydroskimming 4.5900 and conversion 11.4300. 8.4300 is conversion under tight supply.'),
  ('refinery', 'beginner', 'module', 'm06-the-associate-reading', 11, 'Hydroskimming under tight supply prints a gross margin per barrel of 1.5900. What first operating year revenue does the same row print?', '["127193220.00", "103690125.00", "69126750.00", "112154625.00"]'::jsonb, 1, 'Read the hydroskimming tight row: gross margin 1.5900 beside 103690125.00. The firm and disrupted hydroskimming rows carry 127193220.00 and 69126750.00, and 112154625.00 sits on the conversion tight row.'),
  ('refinery', 'beginner', 'module', 'm06-the-associate-reading', 12, 'In the Professional tier, what does every barrel of crude the plant buys pass through?', '["The naphtha reformer, which takes crude as its feed", "The supply scenario, which then sets its utilisation", "The crude unit, whose capacity and cost join the answer", "The licensing tracker, before any unit may run it"]'::jsonb, 2, 'In the plan every barrel of crude passes through the crude unit, and the crude unit''s own capacity and cost become part of the answer. Yields become streams that other units take as feed.'),
  ('refinery', 'beginner', 'module', 'm06-the-associate-reading', 13, 'Which course teaches how the plan finds each stream''s marginal value?', '["The crude course, which owns linear programming", "The Professional tier of this course, in its own lessons", "The Economics courses, beside the valuation", "The supply course, with terminals and landed cost"]'::jsonb, 0, 'The plan prices one more barrel of each stream arriving from outside. How it finds those values is linear programming, and the crude course teaches it; this course reads the plan''s answers.'),
  ('refinery', 'beginner', 'module', 'm06-the-associate-reading', 14, 'In the OKORDIA chain the capital step returns 64000000.00 and 12800.00 per bpd. What does it use?', '["The hydroskimming yields and OKORDIA''s prices", "5000 bpd, 330 on-stream days and a utilisation of 0.9200", "The 2 construction years and the 20 operating years", "The 64000000.00 quotation for 5000 bpd and the modular law"]'::jsonb, 3, 'The screen prints capital (modular law at the reference point): 64000000.00; capital per bpd 12800.00, from the vendor quotation of 64000000.00 for a 5000 bpd plant. The yields and prices give the slate, the capacity, days and utilisation give the throughput, and the construction and operating years lay out the streams.'),
  ('refinery', 'beginner', 'module', 'm06-the-associate-reading', 15, 'In the chain''s streams step, what does each producing year from year 2 carry?', '["Crude run 1518000.00 bbl, revenue 127193220.00, capex 32000000.00", "Crude run 1518000.00 bbl, revenue 127193220.00, crude cost 115368000.00", "Crude run 1650000.00 bbl, revenue 127193220.00, crude cost 115368000.00", "Crude run 1518000.00 bbl, revenue 116794920.00, crude cost 115368000.00"]'::jsonb, 1, 'From year 2 the plant produces a crude run of 1518000.00 bbl, revenue of 127193220.00, crude cost of 115368000.00, fixed opex of 7500000.00 and variable opex of 4857600.00. Capex of 32000000.00 sits in the two construction years, 1650000.00 bbl is nameplate on every on-stream day, and 116794920.00 is topping''s revenue.'),
  ('refinery', 'beginner', 'final', null, 1, 'Which module in the counts table exports 7 functions and 4 lists and constants?', '["modularRefinery", "refineryPlanning", "streamModel", "the screening engine"]'::jsonb, 2, 'The counts are measured from the modules themselves, and the row reading 7 and 4 is streamModel, the module whose LEDGER names the plan, schedule and actual ledgers of the later tiers.'),
  ('refinery', 'beginner', 'final', null, 2, 'Which four lists does modularRefinery export, each naming a thing chosen on the screen?', '["SCALING_EXPONENT, CONFIGURATIONS, SUPPLY_SCENARIOS and LICENSING_STAGES", "SCALING_EXPONENT, CONFIGURATIONS, SUPPLY_SCENARIOS and streamModel.LEDGER", "CONFIGURATIONS, SUPPLY_SCENARIOS, LICENSING_STAGES and one price table", "LEDGER, CONFIGURATIONS, LICENSING_STAGES and the three prices of crude"]'::jsonb, 0, 'Capital comes from the exponents, the slate from the configurations, the run rate and crude price from the supply scenarios, and the paperwork from the licensing stages. LEDGER belongs to streamModel and names the ledgers of the later tiers.'),
  ('refinery', 'beginner', 'final', null, 3, 'On-stream days is typed as 400. What does the engine return?', '["An answer with the days capped at 366, the top of the range", "REFUSED: \"Utilisation is a fraction between 0 and 1 (0.9 for 90 percent).\"", "An answer at 400 days, read as a run of more than one year", "REFUSED: \"On-stream days must be between 1 and 366.\""]'::jsonb, 3, 'On-stream days have a range and the refusal states it. The engine does not cap a figure outside the range or read it as something else.'),
  ('refinery', 'beginner', 'final', null, 4, 'The variable operating cost box is left blank on OKORDIA. What comes back?', '["An answer with the variable cost read as 0.0000 a barrel of crude, the blank taken as zero", "A refusal that names the variable operating cost and asks for a typed 0", "An answer at a stated default of 3.2000 a barrel, the figure OKORDIA types", "REFUSED: \"Missing crude cost. Enter 0 where the value really is zero.\""]'::jsonb, 1, 'The engine prints "Missing variable operating cost. Enter 0 where the value really is zero." It takes no default for a money box and never reads the blank as zero.'),
  ('refinery', 'beginner', 'final', null, 5, 'Which calls to feasibilityEconomics draw the sentence "A discount rate and a tax rate are needed to value the project."?', '["Tax rate left out, and any streams already refused for a blank crude cost", "A discount rate of null only, with a blank tax rate read as zero", "Any call whose streams carry a capital cost of 64000000.00", "Tax rate left out, tax rate left blank, and a discount rate of null"]'::jsonb, 3, 'All three rate cases draw the one sentence. Streams refused for a blank crude cost come back with their own refusal, word for word, and the box is still named.'),
  ('refinery', 'beginner', 'final', null, 6, 'Which export reads the machine clock when periodStart is left out of the call?', '["cascadeToSchedule", "feasibilityEconomics", "calculateEconomics", "scaleCapex, in modularRefinery"]'::jsonb, 0, 'periodStart is the schedule''s own argument, and cascadeToSchedule is the export that falls back on the machine clock without it. The two valuation exports fall back on the clock for the year instead.'),
  ('refinery', 'beginner', 'final', null, 7, 'What start year does the course pass to every valuation?', '["The current year from the machine clock", "Year 2, the first producing year", "2027, on every call", "None, as a valuation needs no year"]'::jsonb, 2, 'Every valuation is passed start year 2027, so a figure read in this course does not move with the day it is read.'),
  ('refinery', 'beginner', 'final', null, 8, 'A 1000 bpd plant is scaled from OKORDIA''s quotation. Which costs does scaleComparison print for it?', '["24366770.42 modular and 15035122.47 stick-built", "15035122.47 modular and 24366770.42 stick-built", "34296750.80 modular and 42224253.14 stick-built", "15035122.47 on both laws, as at the quotation size"]'::jsonb, 1, 'At 1000 bpd the modular law (0.9) prints 15035122.47 and the stick-built law (0.6) 24366770.42, so modular cheaper reads true. 34296750.80 and 42224253.14 are the 2500 bpd row.'),
  ('refinery', 'beginner', 'final', null, 9, 'What capital per bpd does the stick-built law print at 20000 bpd?', '["7351.67", "11143.05", "9700.59", "12800.00"]'::jsonb, 0, 'At 20000 bpd the stick-built law prints 7351.67 per bpd and the modular law 11143.05. 9700.59 is the stick-built law at 10000 bpd, and 12800.00 is the reference row.'),
  ('refinery', 'beginner', 'final', null, 10, 'The ratio at 20000 bpd reads 1.5157. What does it state?', '["The stick-built cost is that multiple of the modular cost.", "The modular plant is cheaper there by that fraction.", "The modular cost is that multiple of the stick-built cost.", "The two laws agree to within that figure at that size."]'::jsonb, 2, 'The ratio is the modular cost over the stick-built cost. Above 1.0000 the modular plant is the dearer, and modular cheaper reads false on that row.'),
  ('refinery', 'beginner', 'final', null, 11, 'Which of these capital figures did a vendor actually quote?', '["222860944.20 for 20000 bpd", "128000000.00 for 10000 bpd", "187529987.30 for 30000 bpd", "64000000.00 for 5000 bpd"]'::jsonb, 3, 'OKORDIA''s reference point is one quotation, 64000000.00 for 5000 bpd. Every other figure is that quotation carried through an exponent. Nobody quoted them, and a vendor''s answer at another size would replace the scaled figure.'),
  ('refinery', 'beginner', 'final', null, 12, 'SCALING_EXPONENT holds two named entries. Which?', '["STICK_BUILT at 0.9, MODULAR at 0.6", "STICK_BUILT at 0.6, MODULAR at 0.9", "MODULAR 0.9 and a PROPORTIONAL 1", "MODULAR 0.6 and a PROPORTIONAL 1"]'::jsonb, 1, 'The stick-built exponent is 0.6, the strong economy of scale, and the modular exponent is 0.9, the weak one. An exponent of 1 is a comparison the lesson runs and is not an entry in the list.'),
  ('refinery', 'beginner', 'final', null, 13, 'Scaled to 10000 bpd with an exponent of 1, what does OKORDIA''s quotation become?', '["119428222.92", "128000000.00", "97005860.26", "64000000.00"]'::jsonb, 1, 'An exponent of 1 is cost in proportion to capacity. At 10000 bpd the modular law prints 119428222.92 and the stick-built law 97005860.26, so one plant from one quotation gets three costs from three exponents.'),
  ('refinery', 'beginner', 'final', null, 14, 'In the conversion slate, what is gasoline worth per barrel of crude?', '["20.8000", "104.0000", "33.3300", "35.3600"]'::jsonb, 3, 'Conversion yields gasoline at 0.3400, priced at 104.0000, so its row prints 35.3600. 20.8000 is gasoline in the hydroskimming slate and 33.3300 is conversion''s diesel.'),
  ('refinery', 'beginner', 'final', null, 15, 'Which configuration yields kerosene at 0.1400?', '["Topping, with crude distillation alone", "Hydroskimming, with its naphtha reformer added", "Conversion, with its cracker added", "All three, as kerosene is a crude cut"]'::jsonb, 0, 'Kerosene reads 0.1400 for topping, 0.1300 for hydroskimming and 0.1200 for conversion.'),
  ('refinery', 'beginner', 'final', null, 16, 'Which configuration carries a fluid catalytic cracker?', '["Hydroskimming, in place of its diesel hydrotreater", "Topping, beside its crude distillation unit", "Conversion, on top of the reformer and hydrotreater", "None; the cracker belongs to the next tier''s monthly plan"]'::jsonb, 2, 'The fluid catalytic cracker is what makes a plant conversion. It cracks heavy material into lighter products and sits beside the reformer and hydrotreater that hydroskimming already has.'),
  ('refinery', 'beginner', 'final', null, 17, 'What lpg yield does the conversion row carry?', '["0.0500", "0.0300", "0.0200", "0.3400"]'::jsonb, 0, 'lpg reads 0.0200 for topping, 0.0300 for hydroskimming and 0.0500 for conversion. 0.0200 is also the loss on every row, and 0.3400 is conversion''s gasoline.'),
  ('refinery', 'beginner', 'final', null, 18, '16.5000 a barrel of crude: which product earns that on OKORDIA''s hydroskimming plant?', '["diesel", "gasoline", "kerosene", "fuelOil"]'::jsonb, 3, 'fuelOil yields 0.3000 at 55.0000, which prints 16.5000. Diesel prints 32.3200, gasoline 20.8000 and kerosene 12.6100 in the same slate.'),
  ('refinery', 'beginner', 'final', null, 19, 'Which of these entries does the engine answer with a figure?', '["A crude cost left blank on the OKORDIA screen''s inputs", "A naphtha price left blank on the topping slate", "On-stream days typed as 0 for the plant", "A tax rate left blank on the valuation call"]'::jsonb, 1, 'A blank product price is answered: gross value 63.6200, with naphtha named on the unpriced list. The other three are refused, which makes a forgotten price the quiet one to check for.'),
  ('refinery', 'beginner', 'final', null, 20, 'Which of these rows makes productSlate print yields close false?', '["Topping at OKORDIA''s own prices, naphtha included", "Any row carrying a loss yield of 0.0200 in its slate", "Hydroskimming typed with yields that total 0.9700", "Conversion at OKORDIA''s own prices"]'::jsonb, 2, 'The typed hydroskimming row totals 0.9700 and prints yields close false, valued as typed at 81.1900. The topping and conversion slates at OKORDIA''s prices print yields total 1.0000 and yields close true, and the loss of 0.0200 is part of each of those closing rows.'),
  ('refinery', 'beginner', 'final', null, 21, 'Which multiplication gives OKORDIA''s yearly variable opex of 4857600.00?', '["1518000.00 bbl at 76.0000 a barrel", "1650000.00 bbl at 3.2000 a barrel", "5000 bpd at 3.2000 over 330 days", "1518000.00 bbl at 3.2000 a barrel"]'::jsonb, 3, 'Variable opex = crude run x variable operating cost. The crude run is the annual throughput, which carries the utilisation of 0.9200 as well as the on-stream days. 1518000.00 x 76.0000 is the crude cost column.'),
  ('refinery', 'beginner', 'final', null, 22, 'In which year does OKORDIA''s fixed opex of 7500000.00 first appear in the streams?', '["Year 0, beside the first capex", "Year 2, when production starts", "Year 1, as building finishes", "Year 3, after a year of running"]'::jsonb, 1, 'The fixed operating cost is paid in the years the plant runs, so the streams print 0.00 for it in year 1 and 7500000.00 in year 2.'),
  ('refinery', 'beginner', 'final', null, 23, 'OKORDIA is built over three construction years. Which is its first producing year, and how many years do the streams hold?', '["Year 3, and 23 years", "Year 3, and 22 years", "Year 2, and 23 years", "Year 2, and 22 years"]'::jsonb, 0, 'Years in the streams are the construction years plus the operating years, 3 and 20. With two construction years the first producing year is year 2 and the streams hold 22.'),
  ('refinery', 'beginner', 'final', null, 24, 'The streams table prints years 0 to 3 and year 21 only. How does a reader know what the unprinted middle years carry?', '["They are interpolated between the printed year 3 and year 21 rows.", "They are left for the valuation engine to fill in later.", "They carry the engine''s defaults, 1530000.00 bbl a year.", "The screen checks each producing year against year 2 and prints true."]'::jsonb, 3, 'Every producing year carries the same figures as year 2: true. The streams are one year repeated from year 2 to year 21, and a hidden row holds nothing the printed rows do not.'),
  ('refinery', 'beginner', 'final', null, 25, 'A reader quotes 1518000.00 bbl as OKORDIA''s size. What have they read?', '["The nameplate, 5000 bpd, run over a full calendar year", "The capacity of the plant in barrels a day", "A year''s crude run, after 330 days at 0.9200", "The crude run at a utilisation of 1"]'::jsonb, 2, 'Capacity is 5000 bpd of nameplate. 1518000.00 bbl is the annual throughput, capacity times 330 on-stream days times a utilisation of 0.9200. At utilisation 1 the run would read 1650000.00 bbl.'),
  ('refinery', 'beginner', 'final', null, 26, 'A reviewer wants more barrels a year from OKORDIA with its margin per barrel left untouched. Which single entry does that?', '["Tight supply picked in place of firm supply", "A utilisation of 1 in place of 0.9200", "A crude cost set higher than its 76.0000", "Conversion in place of hydroskimming"]'::jsonb, 1, 'Utilisation sits in the throughput and not in the margin, so a utilisation of 1 gives 1650000.00 bbl at the same 4.5900. Tight supply lowers the run and the margin together, the crude cost moves only the margin, and conversion moves the gross value.'),
  ('refinery', 'beginner', 'final', null, 27, '"Half the nameplate and a hard premium": which utilisation and premium does the engine pair with those words?', '["0.7500 and 3.0000", "0.5000 and 3.0000", "0.5000 and 6.0000", "0.9200 and 6.0000"]'::jsonb, 2, 'The words belong to the disrupted note, and disrupted supply carries a utilisation of 0.5000 and a crude premium of 6.0000. Tight carries 0.7500 and 3.0000.'),
  ('refinery', 'beginner', 'final', null, 28, 'OKORDIA buys its crude under tight supply. How much does the first operating year''s crude bill come to?', '["97762500.00", "103690125.00", "115368000.00", "67650000.00"]'::jsonb, 0, 'The tight row reads a crude cost of 97762500.00 beside a revenue of 103690125.00. 115368000.00 is the firm crude cost and 67650000.00 the disrupted one.'),
  ('refinery', 'beginner', 'final', null, 29, 'Stages lte and ltc are complete, in that order. What does the tracker report?', '["A complete count of 2 with Licence to Construct named next, in order", "A complete count of 2 with no stage named next, as two is enough", "A complete count of 3 with Licence to Operate named next, in order", "A complete count of 2 with Licence to Operate named next, in order"]'::jsonb, 3, 'The next stage is the first in sequence not complete, which after lte and ltc is Licence to Operate, and out of order reads false. Only with all three complete does the next stage read null.'),
  ('refinery', 'beginner', 'final', null, 30, 'No licensing stage has been ticked. What does the tracker name as the next stage?', '["Licence to Operate, the last in line", "Licence to Establish, with a count of 0", "null, as there is nothing yet to count", "Licence to Construct, with a count of 1"]'::jsonb, 1, 'Before anything is ticked the tracker counts 0 and points at the first stage in sequence, Licence to Establish, with out of order false.'),
  ('refinery', 'beginner', 'final', null, 31, 'Which stage lists a construction HSE plan and financing close among its typical evidence?', '["The first, Licence to Establish", "The third, Licence to Operate", "None of the three stages", "The second, Licence to Construct"]'::jsonb, 3, 'The Licence to Construct asks whether the project can be built: detailed engineering design, approved environmental impact assessment, construction HSE plan and financing close.'),
  ('refinery', 'beginner', 'final', null, 32, 'Which scenario''s note reads "A term contract that is honoured, at the market price.", and what premium does it add?', '["Tight supply, adding 3.0000", "Firm supply, adding 3.0000", "Firm supply, adding 0.0000", "Disrupted, adding 6.0000"]'::jsonb, 2, 'Firm supply carries a utilisation of 0.9200 and a premium of 0.0000, so OKORDIA''s crude stays at 76.0000 a barrel under it.'),
  ('refinery', 'beginner', 'final', null, 33, 'OKORDIA types its own utilisation of 0.9200, and disrupted supply is then picked. What utilisation does the screen run?', '["0.5000, the scenario''s own", "0.9200, the plant''s own figure", "0.7500, the tight scenario''s", "0.9200 in the first year only"]'::jsonb, 0, 'A scenario''s utilisation replaces the plant''s, whatever was typed. Disrupted supply runs OKORDIA at 0.5000 and 825000.00 bbl a year.'),
  ('refinery', 'beginner', 'final', null, 34, 'What first operating year revenue does the nine-row table print for conversion under firm supply?', '["127193220.00", "137576340.00", "116794920.00", "112154625.00"]'::jsonb, 1, 'Conversion under firm supply prints 137576340.00. 127193220.00 is hydroskimming and 116794920.00 topping under firm supply, and 112154625.00 is conversion under tight supply.'),
  ('refinery', 'beginner', 'final', null, 35, 'What gross margin per barrel does topping print under disrupted supply?', '["-8.2600", "-5.2600", "-2.2600", "-1.4100"]'::jsonb, 0, 'Topping''s rows read -2.2600, -5.2600 and -8.2600 as supply goes from firm to tight to disrupted, negative on every one. -1.4100 is the hydroskimming disrupted row.'),
  ('refinery', 'beginner', 'final', null, 36, 'A margin of 8.4300 a barrel of crude: which configuration and supply give it?', '["Conversion under disrupted supply", "Hydroskimming under firm supply", "Conversion under tight supply", "Conversion under firm supply"]'::jsonb, 2, 'Conversion reads 11.4300 on firm, 8.4300 on tight and 5.4300 on disrupted. Hydroskimming on firm reads 4.5900.'),
  ('refinery', 'beginner', 'final', null, 37, 'Under disrupted supply, what crude cost with premium does OKORDIA''s scenario table print?', '["79.0000", "76.0000", "6.0000", "82.0000"]'::jsonb, 3, 'The premium is added to the crude cost before the streams are built: 76.0000 on firm, 79.0000 on tight and 82.0000 on disrupted. 6.0000 is the disrupted premium itself.'),
  ('refinery', 'beginner', 'final', null, 38, 'What does the Professional tier put on a barrel for the first time in this course?', '["A price, taken from OKORDIA''s illustrative product price table", "A calendar date, from a schedule cascaded from the month''s plan", "A licence stage, from the tracker in the Feasibility Studio", "A yield, from one fixed row for each of the configurations"]'::jsonb, 1, 'The Professional tier cascades the month''s plan into a schedule of cargoes, unit runs and lifts across the period. That is the first time this course dates a barrel.'),
  ('refinery', 'beginner', 'final', null, 39, 'Which module does the Professional tier move to?', '["modularRefinery, over the screening engine", "screening, through feasibilityEconomics", "refineryPlanning, over lib/lp/simplex", "streamModel, over the licensing tracker"]'::jsonb, 2, 'The Associate tier lives almost entirely in modularRefinery. The Professional tier moves to the Refinery Planning Studio and refineryPlanning, which runs over lib/lp/simplex and streamModel.'),
  ('refinery', 'beginner', 'final', null, 40, 'Which change moves OKORDIA''s gross margin per barrel?', '["Going from 2 to 3 construction years", "Picking tight supply in place of firm", "Changing the scaling exponent", "Typing a utilisation of 1"]'::jsonb, 1, 'The margin is gross value less crude cost less variable operating cost. Tight supply adds a premium to the crude cost and the margin reads 1.5900. Construction years move when the plant earns, the exponent enters scaleCapex (and at OKORDIA''s 5000 bpd both laws print 64000000.00), and utilisation moves the throughput.'),
  ('refinery', 'beginner', 'final', null, 41, 'Which function hands OKORDIA''s annual streams on to the screening engine?', '["feasibilityStreams", "scaleComparison", "feasibilityEconomics", "cascadeToSchedule"]'::jsonb, 2, 'feasibilityStreams builds the streams and feasibilityEconomics hands them to the screening engine. scaleComparison prints the two capital laws, and cascadeToSchedule belongs to refineryPlanning.'),
  ('refinery', 'beginner', 'final', null, 42, 'Which of these outputs does the scaling exponent change?', '["The gross value per barrel of the slate", "The annual throughput of the plant", "The first producing year of the streams", "Capital at sizes other than 5000 bpd"]'::jsonb, 3, 'The exponent changes the capital and nothing else, and at the reference size of 5000 bpd not even that, since both laws return the quotation there.');
