-- ============================================================================
-- DR5 EXPERT DEEP SEED: Geomechanics, advanced tier.
--
-- Six modules, 26 lessons, 132 questions. The structure row is GENERATED from
-- the tier's manifest.json rather than hand typed.
--
-- What this tier owns: the mud weight window walked along a whole trajectory,
-- 30 m of measured depth at a time, with the profile interpolated onto each
-- station's true vertical depth. 99 rows on the slant well and 92 on the
-- horizontal one, both checked against the published oracle.
--
-- THE FIRST FINDING. The tightest point is at TOTAL DEPTH on the slant well
-- and at the KICK-OFF POINT on the horizontal one, 1020 m into a 2800 m hole,
-- with the hole barely 5.333333333333236 degrees off vertical. The collapse
-- gradient falls all the way through that interval as the rock strengthens,
-- and the deviation below the kick-off WIDENS the window rather than narrowing
-- it, so the minimum sits where the two trends cross. The hardest place to
-- drill that well is nowhere near the reservoir, and a study that evaluated
-- total depth on both wells would have got one of them right by accident.
--
-- THE SECOND FINDING, WHICH REORDERS EVERYTHING ELSE. The slant well is PORE
-- PRESSURE bound at its tightest point, by 773.5521036358621 kg/m3. The
-- horizontal well is COLLAPSE bound at its, by 333.0134212003486. Which bound
-- binds decides the remedy, the uncertainty, the failure mode AND which
-- parameters matter: sweeping the friction angle from 20 to 40 degrees moves
-- the slant well's window by EXACTLY ZERO at every digit, because neither of
-- its two bounds contains a friction angle, while it moves the horizontal
-- well's by 216.4400735919205 kg/m3.
--
-- THE THIRD FINDING. The Poisson ratio dominates every other sensitivity.
-- Sweeping it from 0.20 to 0.35, which is this course's OWN sandstone-to-shale
-- seed range, moves the slant well's window by 956.2616032453875 kg/m3 and the
-- horizontal well's by 1153.222084676116. The next largest are the SHmax
-- azimuth at 366.7313503391106 on the slant well and the tensile strength at
-- 496.6885864429339 on the horizontal one. So the parameter with the largest
-- influence is the one usually taken from a lithology table, and on this
-- evidence a dipole shear sonic beats core and an extended leak-off test as
-- the first thing to buy. That contradicts the conventional wish list, and the
-- general lesson is that the ranking should be COMPUTED rather than assumed.
--
-- FIVE THINGS TAUGHT IN m05 AND CERTIFIED NOWHERE: inelastic and anisotropic
-- rock behaviour, time-dependent effects, chemical effects, thermal stress,
-- and natural fractures and bedding.
-- 20260830_dr5_geomech_go_live.sql asserts that no graded field key names one.
--
-- Answer keys live only here and in academy_quiz_questions, which has no
-- client SELECT policy.
-- ============================================================================

insert into public.academy_course_structures
    (app_slug, tier, structure, content_version)
values ('geomech', 'advanced', '{"modules":[{"key":"m01-the-window-along-a-well","title":"The Window Along a Well","lesson_keys":["l01-one-depth-is-not-a-well","l02-the-walk","l03-interpolating-onto-the-trajectory","l04-the-tightest-point","l05-two-wells-two-answers"]},{"key":"m02-which-bound-binds","title":"Which Bound Binds","lesson_keys":["l01-collapse-or-pore-pressure","l02-the-slant-well-is-pore-pressure-bound","l03-the-horizontal-well-is-collapse-bound","l04-different-bounds-different-remedies","l05-when-the-window-closes"]},{"key":"m03-sensitivity","title":"Sensitivity","lesson_keys":["l01-the-shmax-azimuth","l02-the-poisson-ratio","l03-the-friction-angle-twice","l04-what-to-calibrate-first"]},{"key":"m04-using-it-in-a-well-plan","title":"Using It in a Well Plan","lesson_keys":["l01-what-the-driller-gets","l02-against-the-kick-tolerance","l03-against-the-circulating-density","l04-what-goes-in-the-programme"]},{"key":"m05-the-edges-of-the-model","title":"The Edges of the Model","lesson_keys":["l01-linear-elastic-and-isotropic","l02-no-time-and-no-chemistry","l03-no-thermal-stress","l04-no-natural-fractures-or-bedding","l05-what-this-course-will-not-certify"]},{"key":"m06-the-expert-reading","title":"The Expert Reading","lesson_keys":["l01-the-story-so-far","l02-working-the-capstone","l03-onward"]}]}'::jsonb, 1)
on conflict (app_slug, tier) do update
  set structure = excluded.structure,
      content_version = excluded.content_version,
      active = true,
      updated_at = now();

delete from public.academy_quiz_questions
 where app_slug = 'geomech' and tier = 'advanced';

insert into public.academy_quiz_questions
    (app_slug, tier, scope, module_key, ord, prompt, options, answer_index, explanation)
values
  ('geomech', 'advanced', 'module', 'm01-the-window-along-a-well', 1, 'Why is a stability answer at one depth not yet an answer?', '["Because one depth cannot be measured accurately.", "Because the failure criteria are only valid over an interval rather than at a point, so a single depth is meaningless.", "Because a well is drilled through many depths at many attitudes, and the programme has to work at all of them.", "Because the profile is sampled at fifty metre spacing, so no single depth is represented directly in the model."]'::jsonb, 2, 'It is a complete answer to a question nobody asks.'),
  ('geomech', 'advanced', 'module', 'm01-the-window-along-a-well', 2, 'What three things vary along a well?', '["The rock, the hole''s attitude, and which of the two dominates the answer.", "The mud weight, the flow rate and the hole size.", "The overburden, the pore pressure and the strength, all three of which are functions of true vertical depth alone.", "The inclination, the azimuth and the dogleg severity, which together define the trajectory the walk steps along."]'::jsonb, 0, 'Going deeper usually strengthens the rock and usually adds inclination, and those pull in opposite directions.'),
  ('geomech', 'advanced', 'module', 'm01-the-window-along-a-well', 3, 'What does the walk step in, and why?', '["True vertical depth, because the profile is indexed by it.", "Measured depth, because the trajectory is defined in it and a lateral covers a lot of it at no vertical depth.", "Inclination, so that each step represents an equal change in the hole''s attitude regardless of how much hole it covers.", "Survey stations, so that no interpolation of the trajectory is needed at any point along the walk."]'::jsonb, 1, 'Stepping vertically would put one point on a 1500 m lateral, which is where a horizontal well spends most of its length.'),
  ('geomech', 'advanced', 'module', 'm01-the-window-along-a-well', 4, 'What does the walk do at each step?', '["Interpolates between the two neighbouring survey stations.", "Evaluates the closed-form vertical solution and applies a correction factor for the inclination at that measured depth.", "Compares the mud weight against the pore pressure and the fracture gradient, both taken from the profile directly.", "Reads the attitude and vertical depth from the survey, interpolates the profile onto it, runs the full stability calculation."]'::jsonb, 3, 'Five profile quantities interpolated, one stability run, one row recorded.'),
  ('geomech', 'advanced', 'module', 'm01-the-window-along-a-well', 5, 'Why does the walk skip the shallowest depths on both wells?', '["Because the profile begins at 50 m of true vertical depth and the walk refuses to extrapolate above it.", "Because the survey has no stations there.", "Because the collapse criterion cannot be evaluated where the pore pressure is hydrostatic and the rock is unconsolidated.", "Because the conductor is already set at that depth, so there is no open hole to evaluate stability in."]'::jsonb, 0, 'Extrapolating a stress model above its shallowest sample is exactly the problem the Associate tier warned about.'),
  ('geomech', 'advanced', 'module', 'm01-the-window-along-a-well', 6, 'What interpolation does the walk use, and why that one?', '["Cubic spline, for smoothness.", "Nearest neighbour, because the profile samples are close enough together that the difference is below the model uncertainty.", "Linear, because the profile is already a discretisation and a higher order would invent structure it does not support.", "Logarithmic in depth, which matches the way the stresses grow and therefore introduces the least error."]'::jsonb, 2, 'It also stays obviously reversible: a reader can check any interpolated value with two samples and a fraction.'),
  ('geomech', 'advanced', 'module', 'm01-the-window-along-a-well', 7, 'Where is the linear interpolation least safe in this profile?', '["In the middle of the section, where the samples are sparsest.", "Across the pore pressure corner at 1500 m, and through the fast strength rise at the bottom.", "At the top, where the stresses are clamped and therefore no longer vary smoothly between one sample and the next.", "Nowhere, since all five quantities in the profile are linear functions of depth by construction of the fixture."]'::jsonb, 1, 'Interpolating across a corner rounds it off, and interpolating across a steep curve understates the curvature.'),
  ('geomech', 'advanced', 'module', 'm01-the-window-along-a-well', 8, 'How is the tightest point defined?', '["The row with the highest collapse gradient.", "The deepest row, since the pore pressure is highest there and the fracture gradient is lowest in absolute terms.", "The row where the collapse gradient and the fracture gradient are closest together, regardless of the pore pressure.", "The row where the fracture gradient less the larger of the collapse gradient and the pore pressure is smallest."]'::jsonb, 3, 'Measuring from the collapse gradient where the pore pressure is above it would include weights that take a kick.'),
  ('geomech', 'advanced', 'module', 'm01-the-window-along-a-well', 9, 'Where is the slant well tightest, and what is notable about it?', '["At total depth, which is also its deepest point.", "At the kick-off point, a third of the way down.", "At the casing shoe, where the fracture gradient is lowest and the exposed open hole is at its longest for the section.", "In the middle of the build, where the inclination is changing fastest and the hole is turning across the stress field."]'::jsonb, 0, 'That is the shape people expect, and it is only one of the two answers this course produces.'),
  ('geomech', 'advanced', 'module', 'm01-the-window-along-a-well', 10, 'Where is the horizontal well tightest?', '["At total depth, in the lateral.", "At the landing point, where the inclination reaches ninety degrees and the hole stops gaining vertical depth altogether.", "At the kick-off point, barely a third of the way down a 2800 m hole.", "At the casing shoe, which is the shallowest point the walk evaluates on that well."]'::jsonb, 2, 'The hardest place to drill that well is nowhere near the reservoir.'),
  ('geomech', 'advanced', 'module', 'm01-the-window-along-a-well', 11, 'Why is the tightest point on that well where it is?', '["The rock is weakest exactly there.", "The collapse gradient falls all the way through, and the deviation below the kick-off widens the window rather than narrowing it.", "The pore pressure ramp begins at that depth, which pushes the lower bound up sharply over a short interval of hole.", "The survey has its largest dogleg there, which the model treats as an additional stress concentration at the wall."]'::jsonb, 1, 'The minimum is where the falling collapse trend and the trajectory effect cross.'),
  ('geomech', 'advanced', 'module', 'm01-the-window-along-a-well', 12, 'What is the window width comparison between the two wells at their tightest points?', '["The slant well''s is about twice as wide.", "They are within a few kilograms per cubic metre of each other, which is a coincidence of the fixture rather than a result.", "The horizontal well''s is narrower, which is the expected result for a well with a long lateral section.", "The horizontal well''s is about 31 percent wider, so on that measure it is the easier well."]'::jsonb, 3, 'Four differences, all consequential: where, why, how wide, and which lever.'),
  ('geomech', 'advanced', 'module', 'm01-the-window-along-a-well', 13, 'What does the slant well''s answer say about its problem?', '["It is weak rock, and the remedy is a heavier mud.", "It is the trajectory, and the remedy is to reduce the inclination in the lower part of the section before total depth.", "It is the pore pressure ramp, and the remedy is a casing point.", "It is the fracture gradient, and the remedy is a wellbore strengthening treatment applied while drilling ahead."]'::jsonb, 2, 'The window narrows steadily to total depth because the pore pressure rises while the fracture gradient falls slowly.'),
  ('geomech', 'advanced', 'module', 'm01-the-window-along-a-well', 14, 'And for the lateral well, what is the underlying difficulty?', '["Weak shallow rock, and the remedy is a mud weight that clears the collapse gradient there.", "An overpressured reservoir section.", "An unfavourable landing azimuth, which puts the lateral along the maximum horizontal stress and narrows the window there.", "A dogleg in the build that the survey does not resolve, which produces a local stress concentration at the wall."]'::jsonb, 0, 'Not a casing point at 1020 m: a mud weight, and a comfortably achievable one.'),
  ('geomech', 'advanced', 'module', 'm01-the-window-along-a-well', 15, 'What is the lesson for a study, from this pair?', '["Always evaluate total depth first.", "Do not assume the reservoir section is the hard part.", "Always walk the trajectory in true vertical depth, since that is the axis the mechanical earth model is indexed by.", "Prefer horizontal wells, since this pair shows them to have the wider window at the tightest point of the trajectory."]'::jsonb, 1, 'A study that evaluated total depth on both would have got one of them right by accident.'),
  ('geomech', 'advanced', 'module', 'm02-which-bound-binds', 1, 'The two candidates for the lower bound differ in kind. How?', '["One is a pressure and the other a mud weight.", "One is a property of the rock''s fluid; the other of its strength, the stress field and the hole''s attitude.", "One is measured directly by a formation tester and the other is computed, so the two carry different levels of confidence.", "One applies while circulating and the other while static, which is why the larger of the two has to be used throughout."]'::jsonb, 1, 'The pore pressure does not care about the hole. The collapse pressure cares about almost everything.'),
  ('geomech', 'advanced', 'module', 'm02-which-bound-binds', 2, 'What does that mean for the remedies?', '["Both give the same single lever.", "Pore pressure gives several levers including the trajectory, while collapse can only be addressed by raising the mud weight.", "Neither can be addressed by mud weight alone, since both are properties of the formation rather than of the wellbore.", "Pore pressure gives one lever; collapse gives several."]'::jsonb, 3, 'Mud weight, and also trajectory, open hole time, hole cleaning and mud chemistry.'),
  ('geomech', 'advanced', 'module', 'm02-which-bound-binds', 3, 'How firm is each of the two numbers?', '["A pore-pressure-bound window is a firmer number than a collapse-bound one of the same width.", "Both carry the same uncertainty.", "A collapse-bound window is firmer, because the collapse gradient is computed from the model rather than taken from upstream.", "The uncertainty depends only on the width of the window rather than on which of the two bounds produced it."]'::jsonb, 0, 'The collapse bound carries the whole model''s uncertainty. The pore pressure bound carries the pore pressure''s.'),
  ('geomech', 'advanced', 'module', 'm02-which-bound-binds', 4, 'What does it mean for the consequence of being too light?', '["The same outcome in both cases.", "A kick in both cases, since a collapse-bound section is also underbalanced whenever the mud falls below the lower bound.", "A kick, detected in minutes, against cavings and possible stuck pipe, detected over hours to days.", "Lost circulation in the collapse-bound case, because the failed material packs off the annulus and raises the pressure."]'::jsonb, 2, 'The slower failure is the more expensive one to fix.'),
  ('geomech', 'advanced', 'module', 'm02-which-bound-binds', 5, 'At its tightest point, the slant well''s pore pressure exceeds its collapse gradient by how much?', '["By about 20 kg per cubic metre.", "By more than 700 kg per cubic metre. It is not close.", "By nothing. The two are equal there, which is what makes that depth the tightest point on the whole trajectory.", "The collapse gradient is the larger of the two there, by a margin of a few hundred kilograms per cubic metre."]'::jsonb, 1, 'The collapse gradient there is below the density of water, so the criterion is not a practical constraint at all.'),
  ('geomech', 'advanced', 'module', 'm02-which-bound-binds', 6, 'Why is the slant well''s collapse gradient so low at total depth?', '["Because the hole is nearly vertical there.", "Because the pore pressure is high, which reduces the effective stresses at the wall and therefore the risk of shear failure.", "Because the inclination of forty degrees puts the hole close to the minimum horizontal stress direction at that depth.", "Because the rock there is strong: the strength interpolates to well over 100 MPa."]'::jsonb, 3, 'A rock that strong tolerates almost any hoop stress the stress field can produce.'),
  ('geomech', 'advanced', 'module', 'm02-which-bound-binds', 7, 'What is closing the slant well''s window, if not the collapse gradient?', '["The pore pressure rising and the fracture gradient falling, at the same time.", "The collapse gradient rising with depth.", "The inclination increasing through the build, which narrows the window by putting the overburden into the cross section.", "The strength falling with depth, which raises the collapse gradient faster than the fracture gradient rises."]'::jsonb, 0, 'It narrows from both sides at once over the last 150 m of hole.'),
  ('geomech', 'advanced', 'module', 'm02-which-bound-binds', 8, 'At the horizontal well''s tightest point, which bound binds and by how much?', '["Pore pressure, by a similar margin.", "Neither. The two are within a few kilograms per cubic metre of each other, which is what makes the point tightest.", "Collapse, by more than 300 kg per cubic metre over the pore pressure.", "Collapse, by less than 10 kg per cubic metre, which is why the answer is sensitive to the tolerated breakout width."]'::jsonb, 2, 'A mud at the pore pressure plus a trip margin would be safe against a kick and produce a hole full of cavings.'),
  ('geomech', 'advanced', 'module', 'm02-which-bound-binds', 9, 'Account for that high shear failure pressure at 1020 m.', '["Because the hole is fully horizontal there.", "Because the rock is weak: the strength there is less than a fifth of the value at the slant well''s tightest point.", "Because the pore pressure is on the ramp at that depth, which raises the lower bound and narrows the window from below.", "Because the stress azimuth is unfavourable there, which puts the hole across the maximum horizontal stress direction."]'::jsonb, 1, 'A weak rock cannot carry the hoop stress concentration, so it needs the mud to hold it up.'),
  ('geomech', 'advanced', 'module', 'm02-which-bound-binds', 10, 'What is the failure mode nobody sees coming on a well drilled by pore pressure alone?', '["A kick in the reservoir section.", "Lost circulation at the shoe, caused by a mud weight chosen to clear the collapse gradient in the section below it.", "A stuck pipe event in the lateral, where the hole cleaning is worst and the cuttings bed forms most readily.", "A collapse-bound shallow section, drilled at a mud weight that is safe against a kick and far too light for stability."]'::jsonb, 3, 'The mud weight in that section is set by stability, not by well control.'),
  ('geomech', 'advanced', 'module', 'm02-which-bound-binds', 11, 'Besides mud weight, what levers does a collapse-bound section offer?', '["None. Mud weight is the only lever.", "Hole size and bit selection, both of which change the stress concentration at the wall and therefore the collapse pressure.", "Trajectory, open hole time and mud chemistry, of which the last two are outside this model entirely.", "Casing depth, which is the only remedy the model can quantify for a section limited by wellbore stability."]'::jsonb, 2, 'Drilling the section faster genuinely helps, and the model cannot show it because it has no time in it.'),
  ('geomech', 'advanced', 'module', 'm02-which-bound-binds', 12, 'What are the two failure modes when the two bounds are treated the same?', '["Over-conservatism that closes a window unnecessarily, and complacency that produces a hole full of cavings.", "Only over-conservatism.", "Only complacency, since a collapse gradient at zero breakout width can never be too high to be usable in practice.", "Neither, because the operational safety factor applied to the mud weight absorbs the difference between them."]'::jsonb, 0, 'Stating the assumption is what avoids both: what breakout width was tolerated, and what the number would be at another.'),
  ('geomech', 'advanced', 'module', 'm02-which-bound-binds', 13, 'What should a programme write for each section?', '["A single recommended mud weight.", "The lower bound, which candidate produced it, the upper bound, and the tolerated breakout width if collapse binds.", "The window width and the tightest depth, from which a reader can reconstruct both bounds if they know the pore pressure.", "The collapse gradient, the fracture gradient and the pore pressure, leaving the reader to take the maximum themselves."]'::jsonb, 1, 'Four items instead of two, and the reader can act on the one that is actually constraining them.'),
  ('geomech', 'advanced', 'module', 'm02-which-bound-binds', 14, 'What does it mean when the window closes?', '["The section is fully cased.", "The collapse gradient and the fracture gradient coincide, which is a marginal condition rather than an impossible one.", "The model has failed to converge, which happens when the scan and the bisection disagree on the collapse pressure.", "No mud weight both holds the hole up and keeps it from splitting."]'::jsonb, 3, 'The engine records the shallowest such depth and returns a warning naming it.'),
  ('geomech', 'advanced', 'module', 'm02-which-bound-binds', 15, 'What should be checked before believing a computed window closure?', '["Nothing. A closure is a hard result.", "The step size of the walk, since a closure that appears at only one row may be an artefact of the thirty metre spacing.", "The breakout width assumed, the upper bound used, and whether the stresses at that depth are clamped.", "The survey accuracy, since an error in the inclination at that station would change the wall loading substantially."]'::jsonb, 2, 'A closure inside a region the model has already flagged as inconsistent is a symptom rather than a prediction.'),
  ('geomech', 'advanced', 'module', 'm03-sensitivity', 1, 'Where does the SHmax azimuth come from on a normal well?', '["Breakout orientations on image logs, tensile fractures, a regional stress map, or a guess.", "A dipole shear sonic log.", "A leak-off test, which measures the minimum horizontal stress and therefore fixes the direction of the maximum one.", "The survey, since the maximum horizontal stress is by convention aligned with the regional structural dip."]'::jsonb, 0, 'It is one of the least well constrained inputs, and how much that matters depends on the well.'),
  ('geomech', 'advanced', 'module', 'm03-sensitivity', 2, 'Rotating the stress azimuth moves the slant well''s window by how much?', '["By less than one percent.", "By a factor of three, which is comparable with the effect of sweeping the Poisson ratio across its plausible range.", "By about 35 percent of its smallest value.", "Not at all, since the slant well is pore pressure bound and the pore pressure has no directional dependence."]'::jsonb, 2, 'From a parameter that was never measured, on a well whose tightest point is deviated.'),
  ('geomech', 'advanced', 'module', 'm03-sensitivity', 3, 'And how much does it move the horizontal well''s window?', '["By a similar 35 percent throughout.", "Almost nothing at five of the six azimuths, and it jumps once.", "By more than the slant well, because a horizontal hole is maximally exposed to the horizontal stress directions.", "By nothing at all at any azimuth, since the tightest point on that well is where the hole is effectively vertical."]'::jsonb, 1, 'At one azimuth the tightest point moves several hundred metres deeper and the width drops.'),
  ('geomech', 'advanced', 'module', 'm03-sensitivity', 4, 'Why is the horizontal well insensitive to the stress azimuth at most azimuths?', '["Because its window is wider to start with.", "Because the stress difference between the two horizontal stresses is small at that depth, so the direction barely matters.", "Because the collapse criterion, which binds there, does not contain the stress azimuth as a parameter at all.", "Because its tightest point is nearly vertical, and a nearly vertical hole does not care about the azimuth."]'::jsonb, 3, 'The sensitivity to the azimuth depends on how deviated the well is where its window is tightest.'),
  ('geomech', 'advanced', 'module', 'm03-sensitivity', 5, 'What is the practical rule from that?', '["Always measure the stress azimuth.", "Always assume the worst azimuth, since the cost of a conservative mud programme is lower than the cost of a stuck string.", "If the tightest point is deviated and the azimuth is a guess, quote the range rather than a value.", "Never sweep the azimuth, since the result depends on the trajectory and therefore cannot be generalised between wells."]'::jsonb, 2, 'It is a more honest deliverable and it tells the reader what to buy.'),
  ('geomech', 'advanced', 'module', 'm03-sensitivity', 6, 'Sweeping the Poisson ratio from 0.20 to 0.35 does what to the windows?', '["Nearly triples them on both wells.", "Changes them by a few percent.", "Widens the slant well''s and narrows the horizontal well''s, because the two are bound by different criteria.", "Leaves them unchanged, since the Poisson ratio affects both bounds equally and therefore cancels out of the width."]'::jsonb, 0, 'That range is this course''s own sandstone-to-shale seed span, and the difference between assuming one and the other.'),
  ('geomech', 'advanced', 'module', 'm03-sensitivity', 7, 'Why does a higher Poisson ratio widen the window?', '["It lowers the collapse gradient directly.", "It reduces the axial stress at the wall through the Poisson correction, which moves the least wall stress further from tension.", "It raises the frictional bounds, which allows the horizontal stress estimate to grow without being clamped.", "A higher k0 gives higher horizontal stresses, which gives a higher fracture gradient."]'::jsonb, 3, 'At 0.20 k0 is 0.25 and at 0.35 it is about 0.538, so the horizontal stresses more than double.'),
  ('geomech', 'advanced', 'module', 'm03-sensitivity', 8, 'Why is the Poisson ratio sensitivity the important finding?', '["Because it is the easiest to measure.", "Because it is usually the least carefully determined input in the whole model.", "Because it appears in both the stress model and the wall stress calculation, which is why its effect compounds through them.", "Because it is the only input that is a pure number rather than a physical quantity with units attached to it."]'::jsonb, 1, 'The parameter with the largest influence is the one with the least evidence behind it.'),
  ('geomech', 'advanced', 'module', 'm03-sensitivity', 9, 'Now sweep the internal friction from 20 to 40 degrees on the deep well. What happens?', '["Exactly zero, at every digit, across the whole sweep.", "By about 18 percent, as on the other well.", "By a small amount that grows with the angle, since the frictional ratio accelerates as the friction angle rises.", "By an amount that cannot be determined, because the tightest point moves as the friction angle changes."]'::jsonb, 0, 'Not approximately. Identically.'),
  ('geomech', 'advanced', 'module', 'm03-sensitivity', 10, 'Why is it exactly zero?', '["Because the friction angle is clamped there.", "Because the collapse gradient at that depth is below the density of water, so any change to it is numerically negligible.", "Because that well''s tightest point is pore pressure bound, and neither of its two bounds contains a friction angle.", "Because the frictional bounds on the horizontal stresses are not active at that depth, so the second use of it also cancels."]'::jsonb, 2, 'The pore pressure has no friction angle in it, and the tensile criterion has none either.'),
  ('geomech', 'advanced', 'module', 'm03-sensitivity', 11, 'State the general rule that follows.', '["Every parameter matters equally.", "The sensitivity of a window to any parameter is proportional to the width of the window at the point being evaluated.", "Parameters that appear in both the stress model and the wall calculation always dominate those that appear in only one.", "Which bound binds determines which parameters matter."]'::jsonb, 3, 'It tells you not to spend money measuring a friction angle in a pore-pressure-bound section, and to spend it in a collapse-bound one.'),
  ('geomech', 'advanced', 'module', 'm03-sensitivity', 12, 'Why does the friction angle''s SECOND job not show on the slant well either?', '["Because the second job affects only shallow depths.", "Because no depth near its tightest point is clamped, so widening or narrowing the frictional bounds changes nothing.", "Because the frictional bounds use a fault friction angle, which the engine takes as a separate input from the rock one.", "Because the bounds are applied to the effective stresses and the window is computed from the total ones."]'::jsonb, 1, 'On a profile with more clamping the friction angle would move the fracture gradient too, and the two effects would not separate.'),
  ('geomech', 'advanced', 'module', 'm03-sensitivity', 13, 'What does the ranking of sensitivities say to buy first?', '["A dipole shear sonic, because it gives the Poisson ratio at log resolution over the whole well.", "Core, for a triaxial test suite.", "An extended leak-off test at each shoe, which measures the minimum horizontal stress directly and anchors the fracture end.", "An image log, which gives the stress azimuth from breakout orientations and calibrates the collapse gradient at the same time."]'::jsonb, 0, 'The conventional wish list starts with core and a leak-off test, and on this fixture the shear log beats both.'),
  ('geomech', 'advanced', 'module', 'm03-sensitivity', 14, 'What is the general lesson about that ranking?', '["Core is always the right first purchase.", "The ranking is a property of the model rather than of the well, so one sweep serves for every well the model is applied to.", "It should be computed for the well in hand rather than assumed from the conventional list.", "The ranking depends on the depth, so a separate sweep is needed for every section of every well being planned."]'::jsonb, 2, 'The conclusion here is fixture-specific, and the method is not.'),
  ('geomech', 'advanced', 'module', 'm03-sensitivity', 15, 'What does a sensitivity study cost?', '["Several days of computing time.", "A few dozen runs of a calculation that takes seconds, which makes it the cheapest thing in a geomechanics study.", "About as much as the base case, since each parameter requires the whole trajectory to be walked again from the top.", "Nothing, because the engine computes the sensitivities automatically alongside the base case at no additional cost."]'::jsonb, 1, 'It is the cheapest thing in the study and it is skipped more often than anything else.'),
  ('geomech', 'advanced', 'module', 'm04-using-it-in-a-well-plan', 1, 'What does the four-curve chart plot?', '["Just the lower and upper bounds.", "Pore pressure, collapse, fracture initiation and the planned mud weight, against measured depth.", "The three principal stresses and the pore pressure, from which the reader derives the two bounds as needed for each section.", "The equivalent circulating density, the surge and swab pressures, and the static mud weight over the whole trajectory."]'::jsonb, 1, 'The plan has to sit above the higher of the first two and below the third, at every depth in the section.'),
  ('geomech', 'advanced', 'module', 'm04-using-it-in-a-well-plan', 2, 'Why four curves rather than two?', '["Because two curves would be hard to read.", "Because the pore pressure and the collapse gradient cross at some depth in every well, and the crossing has to be shown.", "Because the fracture gradient needs both a static and a circulating version, which are drawn as separate curves.", "Because reading which lower-bound candidate is doing the work is the difference between knowing what to do and guessing."]'::jsonb, 3, 'The panel plots the lower bound as a heavy line and the two candidates underneath it for exactly that reason.'),
  ('geomech', 'advanced', 'module', 'm04-using-it-in-a-well-plan', 3, 'Which row of the per-section table is usually missing from a real report?', '["The tolerated breakout width the collapse number assumes.", "The tightest measured depth.", "The window width, which most reports give as a range rather than as a single value at the tightest point.", "The breakout angle, which is rarely computed because it requires the full theta sweep to be retained."]'::jsonb, 0, 'A collapse gradient with no stated breakout width is an unlabelled number, and this engine''s is at zero width.'),
  ('geomech', 'advanced', 'module', 'm04-using-it-in-a-well-plan', 4, 'What should NOT go into the deliverable?', '["The clamp count and the quality score.", "The sensitivity band, since a reader who sees a range may take the optimistic end of it rather than the base case.", "Ten decimal places, a single number where a band belongs, or a curve above the last calibration depth.", "The breakout angle, which is in the borehole frame and will be misread as a compass bearing by most readers."]'::jsonb, 2, 'Each of the three claims something the model cannot support.'),
  ('geomech', 'advanced', 'module', 'm04-using-it-in-a-well-plan', 5, 'What does the driller do with the chart?', '["Uses the lower bound as the mud weight.", "Picks a mud weight, usually near the middle, biased toward the bound that is less well known.", "Averages the two bounds and adds a safety factor of ten percent, which is the standard practice in most operating companies.", "Reads off the fracture gradient and sets the mud weight just below it, to maximise the margin against a kick."]'::jsonb, 1, 'Then watches the hole: cavings mean too light and losses mean too heavy, and both are calibration data.'),
  ('geomech', 'advanced', 'module', 'm04-using-it-in-a-well-plan', 6, 'Where do this course and the well control course meet?', '["They do not meet at all.", "At the kill mud weight, which both courses compute from the pore pressure using the same true vertical depth.", "At the fracture gradient, which this course computes and the well control course measures with a leak-off test.", "At the casing point, and the shoe goes at the shallower of the two answers."]'::jsonb, 3, 'Both use the same fracture gradient to answer different questions.'),
  ('geomech', 'advanced', 'module', 'm04-using-it-in-a-well-plan', 7, 'Why can the two casing point answers disagree?', '["Because one is limited in the open hole and the other at the shoe, which is much shallower.", "Because they use different fracture gradients.", "Because the well control calculation is done at the planning stage and the geomechanics one is updated as the well is drilled.", "Because the two use different definitions of the pore pressure, one static and one at the equivalent circulating density."]'::jsonb, 0, 'A shallow shoe can run out of kick tolerance while the open hole below it still has a comfortable window.'),
  ('geomech', 'advanced', 'module', 'm04-using-it-in-a-well-plan', 8, 'Which usually binds on a well with a rising pore pressure ramp?', '["Usually the geomechanics window.", "Neither. The two converge on the same depth whenever the pore pressure ramp is the dominant control on both calculations.", "Usually the kick tolerance, because the mud weight rises against a fixed shoe fracture gradient.", "It depends on the hole size, since a larger hole has a lower kick tolerance for the same shoe fracture gradient."]'::jsonb, 2, 'On a well with weak shallow rock it is usually the geomechanics window instead, because collapse is the problem.'),
  ('geomech', 'advanced', 'module', 'm04-using-it-in-a-well-plan', 9, 'This course''s window is static. What has to fit inside it?', '["Only the static mud weight.", "The static mud weight, plus the circulating uplift, plus the surge, and minus the swab.", "The static mud weight and the equivalent circulating density, both of which are computed by the hydraulics course directly.", "The kill mud weight and the trip margin, both of which are set by the well control calculation rather than by this one."]'::jsonb, 1, 'Four numbers in one window, and this course computes none of the transient three.'),
  ('geomech', 'advanced', 'module', 'm04-using-it-in-a-well-plan', 10, 'What does the equivalent circulating density do to the usable window?', '["Eats into it from the top, because the formation feels the circulating pressure rather than the static one.", "Widens it from below.", "Leaves it unchanged, since the fracture gradient is a static property of the rock and does not depend on the flow rate.", "Eats into it from the bottom, because the extra pressure at the wall reduces the risk of collapse and raises the lower bound."]'::jsonb, 0, 'Quoting the window without that caveat invites planning a mud weight right at the fracture gradient.'),
  ('geomech', 'advanced', 'module', 'm04-using-it-in-a-well-plan', 11, 'And the swab?', '["Adds to the pressure, like surge.", "Affects only the annulus above the bit, so it has no bearing on the mud window at the bottom of the hole.", "Cancels against the circulating uplift, since one is a pumping effect and the other happens with the pumps off.", "Subtracts from the bottom hole pressure and takes the well toward the lower bound."]'::jsonb, 3, 'Which is why the well control course carries a trip margin, and why this course says what that margin costs.'),
  ('geomech', 'advanced', 'module', 'm04-using-it-in-a-well-plan', 12, 'The trip margin is a well control decision. What does this course add?', '["That it should always be applied.", "That it should be computed from the swab pressure, which the hydraulics course calculates for the planned trip speed.", "That it moves the mud weight up toward the fracture gradient and takes room out of the window.", "That it is unnecessary in a collapse-bound section, where the mud weight is already well above the pore pressure."]'::jsonb, 2, 'Two courses pushing the same number in opposite directions, and the well plan has to hold both.'),
  ('geomech', 'advanced', 'module', 'm04-using-it-in-a-well-plan', 13, 'What does this course hand to the well planner?', '["A single recommended trajectory.", "The window as a function of inclination and azimuth at the critical depths.", "The tightest point on the planned trajectory, from which the planner can infer whether an alternative would be better.", "The collapse and fracture gradients along the planned trajectory only, since evaluating alternatives is a separate study."]'::jsonb, 1, 'So the trajectory decision can be made on evidence rather than on drilling convenience alone.'),
  ('geomech', 'advanced', 'module', 'm04-using-it-in-a-well-plan', 14, 'What does the next well get from this one?', '["The calibration: where breakouts formed and how wide, where returns were lost, and where the hole gave trouble.", "A copy of the same model.", "A revised set of lithology seeds, updated from any core taken during the drilling of the first well in the sequence.", "The final mud weights actually used, which become the recommended programme for the offset well without further analysis."]'::jsonb, 0, 'Feed those back, adjust the model to have predicted them, and the next well starts from a calibrated model.'),
  ('geomech', 'advanced', 'module', 'm04-using-it-in-a-well-plan', 15, 'If the programme has room for one thing, what is it?', '["The per-section table.", "The sensitivity band on the Poisson ratio, which is the largest single uncertainty in the whole of the calculation.", "The quality score and the clamp count, which tell the reader how much of the profile to distrust before reading anything.", "The four-curve chart with the plan on it and the tightest point marked."]'::jsonb, 3, 'Everything else is support for reading that chart.'),
  ('geomech', 'advanced', 'module', 'm05-the-edges-of-the-model', 1, 'What does linear elasticity buy the model?', '["A single modulus and Poisson ratio describe the rock, and superposition makes the Kirsch solution valid.", "A closed form for the deviated case.", "A guarantee that the answer is conservative, since a real rock deforms plastically and therefore redistributes stress away.", "Independence from the loading path, which means the answer does not depend on the history of the section being drilled."]'::jsonb, 0, 'Superposition only works in a linear system, which is why the wall stress formulas can be added together at all.'),
  ('geomech', 'advanced', 'module', 'm05-the-edges-of-the-model', 2, 'Where does linear elasticity fail worst?', '["In the far field, away from the hole.", "In strong rock at depth, where the stresses are largest and the elastic strains therefore furthest from being small.", "Near the hole wall at high stress, where the rock is close to failure and softens and dilates.", "At shallow depth, where the effective stresses are low and the rock has not yet been compacted by burial."]'::jsonb, 2, 'That redistribution is why a real breakout stabilises at a finite width instead of running away.'),
  ('geomech', 'advanced', 'module', 'm05-the-edges-of-the-model', 3, 'Which common sedimentary rock is most anisotropic?', '["Clean sandstone.", "Shale.", "Limestone, whose depositional fabric gives it strongly direction-dependent elastic properties at the wellbore scale.", "Salt, whose crystalline structure produces the largest elastic contrast of any of the common lithologies."]'::jsonb, 1, 'Ratios of 1.3 to 2 between the along-bedding and across-bedding properties are ordinary.'),
  ('geomech', 'advanced', 'module', 'm05-the-edges-of-the-model', 4, 'Which geometry makes anisotropy matter most?', '["A vertical hole through sandstone.", "A horizontal hole through limestone, where the bedding is parallel to the axis and the loading is uniform around the wall.", "A vertical hole through salt, where the isotropy assumption is exactly correct and no correction is needed at all.", "A deviated hole through shale, where the hole is at an angle to the bedding."]'::jsonb, 3, 'Which is exactly the situation that gives the most trouble in the field.'),
  ('geomech', 'advanced', 'module', 'm05-the-edges-of-the-model', 5, 'Why is the model isotropic anyway?', '["Because a transversely isotropic model needs five elastic constants and four cannot be got from a standard log suite.", "Because the difference is negligible.", "Because anisotropic Kirsch solutions do not exist in closed form, so the wall stresses could not be evaluated at all.", "Because the frictional bounds are derived under an isotropy assumption, and relaxing it would invalidate them."]'::jsonb, 0, 'The model uses what a well has. That is a legitimate reason and it is not the same as the assumption being harmless.'),
  ('geomech', 'advanced', 'module', 'm05-the-edges-of-the-model', 6, 'Name the three time-dependent effects the model omits.', '["Gas migration, gelling and settling.", "Thermal diffusion, chemical diffusion and mechanical fatigue, all three of which act over the life of the open hole.", "Pore pressure diffusion into the near-wall rock, creep, and accumulating damage.", "Filter cake build-up, mud invasion and formation damage, which together change the near-wall permeability over time."]'::jsonb, 2, 'All three make a hole worse the longer it is open, and none is in the model.'),
  ('geomech', 'advanced', 'module', 'm05-the-edges-of-the-model', 7, 'What is the strongest single predictor of trouble in a shale section?', '["The mud weight used.", "Open hole time.", "The inclination of the hole through the section, which determines how the bedding planes are loaded by the wall stresses.", "The unconfined compressive strength of the shale, which sets the collapse gradient and therefore the required mud weight."]'::jsonb, 1, 'It is why drilling a difficult section fast and casing it promptly works, and the model cannot show it.'),
  ('geomech', 'advanced', 'module', 'm05-the-edges-of-the-model', 8, 'Why does an oil-based mud help in reactive shale?', '["It is denser than a water-based mud.", "It lubricates the wall, which reduces the mechanical damage caused by the drill string contacting the low side of the hole.", "It is more compressible, so the pressure fluctuations from tripping and connections are damped before they reach the wall.", "It presents a low water activity and a membrane that limits transport."]'::jsonb, 3, 'A chemical solution to a problem that looks mechanical, and a model with no chemistry cannot represent it.'),
  ('geomech', 'advanced', 'module', 'm05-the-edges-of-the-model', 9, 'What does cooling the wall do to the hoop stress?', '["Reduces it, because prevented thermal contraction is a tensile stress.", "Raises it, because the rock contracts.", "Leaves it unchanged, since thermal effects act on the pore fluid rather than on the grain framework of the rock.", "Reduces it only above the neutral point, where the mud is warmer than the surrounding rock rather than cooler."]'::jsonb, 0, 'It helps against collapse and hurts against fracture, so the net effect depends on which bound is binding.'),
  ('geomech', 'advanced', 'module', 'm05-the-edges-of-the-model', 10, 'Where does thermal stress matter most?', '["Shallow wells with short exposures.", "Wells drilled with oil-based mud, whose thermal conductivity differs enough from water-based mud to change the wall temperature.", "Deep hot wells, long circulating times, and injection wells over the life of a waterflood.", "Horizontal wells, where the long lateral gives the mud time to reach thermal equilibrium with the surrounding formation."]'::jsonb, 2, 'It is why injection fracture gradients fall over the life of a waterflood, which is a well documented effect.'),
  ('geomech', 'advanced', 'module', 'm05-the-edges-of-the-model', 11, 'What surprising loss behaviour does thermal stress explain?', '["Losses starting the moment the pumps come on.", "Losses starting after hours of trouble-free circulation with nothing else having changed.", "Losses that stop when the pumps are shut down, which is the signature of an equivalent circulating density problem.", "Losses that only occur while tripping, which is the signature of a surge pressure exceeding the fracture gradient."]'::jsonb, 1, 'The cooling penetrates further into the rock the longer it goes on, and the effective fracture gradient falls with it.'),
  ('geomech', 'advanced', 'module', 'm05-the-edges-of-the-model', 12, 'What does a natural fracture do to the fracture initiation criterion?', '["Raises the initiation pressure.", "Leaves it unchanged, since the criterion concerns the intact rock at the wall and a fracture is a far-field feature.", "Makes it conservative, because a fractured rock has a lower effective tensile strength than the intact value assumed.", "Makes it irrelevant: the hole only has to open a plane that already exists."]'::jsonb, 3, 'That opening pressure is roughly the normal stress across the fracture, which can be well below the intact value.'),
  ('geomech', 'advanced', 'module', 'm05-the-edges-of-the-model', 13, 'What is the practical upper bound in a naturally fractured formation?', '["A measured leak-off, a loss history, or the minimum horizontal stress.", "The computed fracture initiation pressure.", "The overburden gradient, since a fracture cannot propagate against a stress larger than the vertical one in a normal regime.", "The pore pressure plus the tensile strength of the intact rock, which is when the first fracture would begin to open."]'::jsonb, 0, 'Using the minimum horizontal stress is a cheap and defensible conservatism in fractured ground.'),
  ('geomech', 'advanced', 'module', 'm05-the-edges-of-the-model', 14, 'How does a weak bedding plane change the collapse problem?', '["It makes no difference to collapse.", "It raises the collapse pressure uniformly, by an amount proportional to the difference between the two strengths.", "The hole can fail by slip on the planes rather than by shear through intact rock.", "It moves the breakout to the bedding orientation, but the pressure at which it forms is unchanged from the intact case."]'::jsonb, 2, 'The pressure required to prevent that depends on the angle between the hole and the planes, and it is a different calculation.'),
  ('geomech', 'advanced', 'module', 'm05-the-edges-of-the-model', 15, 'Which five things does the course teach and refuse to certify?', '["The two failure criteria and the three checks.", "Inelastic and anisotropic behaviour, time, chemistry, thermal stress, and natural fractures and bedding.", "The overburden, the pore pressure, the stress azimuth, the Poisson ratio and the friction angle, all of which are estimated.", "Anything involving a deviated well, since the closed forms apply only to a vertical hole and the rest is unverified."]'::jsonb, 1, 'The go-live migration refuses to run if any graded field key names one of them.'),
  ('geomech', 'advanced', 'module', 'm06-the-expert-reading', 1, 'Give the Expert tier in one claim.', '["The mud window is a property of the trajectory.", "The tightest point on a well is not reliably at total depth, and on one of the two wells here it is at the kick-off point.", "Which bound binds decides which parameter matters, and that reorders the whole list of what to measure.", "The Poisson ratio moves the answer more than any other input, and it usually comes from a lithology seed table."]'::jsonb, 2, 'The other statements are true and are consequences of it. That one is what the tier discovered.'),
  ('geomech', 'advanced', 'module', 'm06-the-expert-reading', 2, 'How many walks does the Expert capstone need, and how many fields from each?', '["Two walks, three fields each.", "One walk, six fields.", "Two walks with four fields from the deep well and two from the lateral, matching where each of the bounds binds.", "Six separate runs, one per field, since each field is evaluated at a different depth along the two trajectories."]'::jsonb, 0, 'Nothing here is computed by hand: this tier is about reading a walk correctly.'),
  ('geomech', 'advanced', 'module', 'm06-the-expert-reading', 3, 'What is the first trap in the Expert capstone?', '["The units are pascals rather than mud weight.", "The two wells have to be walked in the same run, since the engine caches the interpolated profile between the two of them.", "The capstone uses a different profile from the lessons, so the stresses have to be recomputed before the walk can start.", "The tightest point moves at the capstone parameters, so the lesson''s depth is the wrong row."]'::jsonb, 3, 'Reading the published tightest depth off the lessons will give you the wrong three numbers.'),
  ('geomech', 'advanced', 'module', 'm06-the-expert-reading', 4, 'Two of the graded fields ask for the collapse gradient. What is the trap there?', '["It is asked for in pascals.", "It is asked for specifically, not as the lower bound, so on the pore-pressure-bound well it is well below the floor.", "It has to be evaluated at zero breakout width, which the engine reports by default but which a real study would relax.", "It is the same number on both wells, since the collapse criterion depends on the rock rather than on the trajectory."]'::jsonb, 1, 'The collapse gradient is still the answer even where it is not the binding bound.'),
  ('geomech', 'advanced', 'module', 'm06-the-expert-reading', 5, 'The window width is measured from what?', '["The lower bound, which is the larger of the collapse gradient and the pore pressure.", "The collapse gradient, always.", "The pore pressure, since a window that included weights below it would be unusable regardless of the stability answer.", "The midpoint between the collapse gradient and the pore pressure, which is the conservative reading of an uncertain floor."]'::jsonb, 0, 'That is why the sum check closes on one well and not on the other.'),
  ('geomech', 'advanced', 'module', 'm06-the-expert-reading', 6, 'On which well does the sum of the collapse field and the width equal the fracture field?', '["Both wells, since it is an identity.", "Neither, because the width is computed at the tightest row and the two gradients are read at the same row separately.", "The collapse-bound one, because there the collapse gradient IS the lower bound.", "The pore-pressure-bound one, since the pore pressure cancels out of the difference between the two bounds."]'::jsonb, 2, 'One of the two sums closes and the other does not, and you should be able to say which before running anything.'),
  ('geomech', 'advanced', 'module', 'm06-the-expert-reading', 7, 'What should the capstone windows be, relative to the published ones?', '["Wider on both wells.", "Narrower on the deep well and wider on the lateral, because the two are bound by different criteria and respond differently.", "The same, since the window width depends on the geometry rather than on the elastic parameters of the rock.", "Narrower on both wells, because the capstone Poisson ratio is lower."]'::jsonb, 3, 'Module 3 says a lower Poisson ratio gives lower horizontal stresses and therefore a narrower window. Check that they are.'),
  ('geomech', 'advanced', 'module', 'm06-the-expert-reading', 8, 'What did module 1 establish about the tightest point?', '["It is always at total depth.", "It is at total depth on one well and at the kick-off point on the other.", "It is always in the build, because that is where the trajectory turns across the stress field while the rock is still weak.", "It cannot be located without a finer step than thirty metres, which is the resolution the walk currently uses."]'::jsonb, 1, 'The rock trend and the trajectory trend pull in opposite directions, and the minimum is where they cross.'),
  ('geomech', 'advanced', 'module', 'm06-the-expert-reading', 9, 'What did module 2 establish about the two wells?', '["One is pore pressure bound at its tightest point and the other is collapse bound.", "Both are pore pressure bound.", "Both are collapse bound, which is why the friction angle sensitivity is the same on the two of them at their tightest points.", "Neither is clearly bound by one candidate, since the two are within a few kilograms per cubic metre on both wells."]'::jsonb, 0, 'And their remedies, their uncertainties and their failure modes all differ accordingly.'),
  ('geomech', 'advanced', 'module', 'm06-the-expert-reading', 10, 'What did module 3 establish about the Poisson ratio?', '["It has almost no effect on the window.", "It affects only the fracture gradient, so its influence is confined to the upper bound and leaves the floor untouched.", "It moves the answer two and a half to five times further than anything else, and it usually comes from a table.", "It matters only on the collapse-bound well, since it enters the failure criterion through the axial stress correction."]'::jsonb, 2, 'The parameter with the largest influence is the one with the least evidence behind it.'),
  ('geomech', 'advanced', 'module', 'm06-the-expert-reading', 11, 'Recall what the fourth module said about how the answer is handed on.', '["That the deliverable is a single mud weight.", "That the window is static, so the circulating uplift, the surge and the swab all have to fit inside it.", "That the casing point from this course always governs over the one from the kick tolerance calculation in well control.", "That the four-curve chart should show only the lower and upper bounds, to avoid overloading the reader with detail."]'::jsonb, 1, 'This course computes none of the three transient corrections, and the drilling engineer owns them.'),
  ('geomech', 'advanced', 'module', 'm06-the-expert-reading', 12, 'What did module 5 establish about natural fractures?', '["That they raise the fracture gradient.", "That they can be represented in the model by lowering the tensile strength to zero at the affected depths.", "That they matter only in carbonates, where the fracture density is high enough to control the loss behaviour.", "That a hole meeting one does not have to split intact rock, so the computed fracture gradient is an over-estimate."]'::jsonb, 3, 'The opening pressure is roughly the normal stress across the fracture, which is often below the minimum horizontal stress.'),
  ('geomech', 'advanced', 'module', 'm06-the-expert-reading', 13, 'Which habit does the tier name about the trajectory?', '["Walk the whole thing, because the tightest point is not reliably at total depth.", "Evaluate the reservoir depth first.", "Step the walk in true vertical depth, since the mechanical earth model is indexed by it and interpolation is then unnecessary.", "Use a thirty metre step, which is fine enough to locate the tightest point and coarse enough to keep the run time reasonable."]'::jsonb, 0, 'On one of the two wells here it is at the kick-off point, nearly 2000 m from the bottom.'),
  ('geomech', 'advanced', 'module', 'm06-the-expert-reading', 14, 'Which habit does it name about precision?', '["Quote to three decimal places throughout.", "Round every gradient to the nearest ten kilograms per cubic metre, which is the resolution mud weight is controlled to.", "Run the sensitivity before quoting one.", "Quote pressures rather than gradients, since the conversion to gradient introduces a rounding at the last step."]'::jsonb, 2, 'The Poisson ratio alone moves these windows by more than a thousand kilograms per cubic metre.'),
  ('geomech', 'advanced', 'module', 'm06-the-expert-reading', 15, 'What does this course hand to well control, and what comes back?', '["Nothing goes either way.", "It sends the fracture gradient and the pore pressure, and gets back the transient corrections and the trip margin.", "It sends the mud window and receives the kill mud weight, which becomes the lower bound for the section below the shoe.", "It sends the casing point and receives the kick tolerance, which is then used to set the mud weight for the section."]'::jsonb, 1, 'Two courses pushing the same number in opposite directions, and the well plan has to hold both.'),
  ('geomech', 'advanced', 'final', null, 1, 'A study evaluates the reservoir depth and stops. What has it missed?', '["That the tightest point can be anywhere on the trajectory, and on one well here it is at the kick-off.", "Nothing, if the reservoir is the deepest point.", "The pore pressure ramp, which begins above the reservoir and therefore has to be evaluated separately from the target depth.", "The equivalent circulating density, which is largest at the bottom of the hole and therefore governs the upper bound there."]'::jsonb, 0, 'The rock trend and the trajectory trend pull in opposite directions and cross somewhere.'),
  ('geomech', 'advanced', 'final', null, 2, 'Why does the walk step in measured depth rather than true vertical depth?', '["Because the survey is recorded that way.", "Because the profile is indexed by measured depth, so no interpolation is needed at any of the steps along the walk.", "Because a lateral covers a lot of measured depth at no vertical depth at all.", "Because the stability calculation is a function of measured depth through the inclination, which changes with hole length."]'::jsonb, 2, 'Stepping vertically would put one point on a 1500 m lateral.'),
  ('geomech', 'advanced', 'final', null, 3, 'Describe one iteration of the trajectory loop, from survey to recorded row.', '["Interpolates between the neighbouring rows.", "Reads attitude and vertical depth from the survey, interpolates the profile, runs the full stability calculation.", "Applies a correction factor to the vertical closed-form solution based on the inclination at that measured depth.", "Compares the planned mud weight against the pore pressure and the fracture gradient taken directly from the profile."]'::jsonb, 1, 'Five quantities interpolated, one stability run, one row recorded.'),
  ('geomech', 'advanced', 'final', null, 4, 'Why does the walk refuse to evaluate above 50 m of true vertical depth?', '["Because the survey has no stations there.", "Because the conductor is set at that depth, so there is no open hole in which stability could be evaluated at all.", "Because the collapse criterion cannot be applied to unconsolidated sediment, which is what occupies the top of the hole.", "Because the profile starts there and extrapolating a stress model upward is exactly what the Associate tier warned about."]'::jsonb, 3, 'Both wells start their walk at the first grid step below the top of the profile.'),
  ('geomech', 'advanced', 'final', null, 5, 'Straight lines between profile samples: name the two places that hurts here.', '["Across the pore pressure corner at 1500 m, and through the fast strength rise at the bottom.", "Nowhere. All five quantities are linear.", "At the top, where the stresses are clamped and no longer vary smoothly between one profile sample and the next.", "In the middle of the section, where the fifty metre sample spacing is largest relative to the rate of change."]'::jsonb, 0, 'Interpolating across a corner rounds it off and interpolating across a steep curve understates the curvature.'),
  ('geomech', 'advanced', 'final', null, 6, 'Of the ninety-odd rows a walk produces, which one is the design case, and by what test?', '["The row with the highest collapse gradient.", "The deepest row, since both the pore pressure and the effective stress reach their extremes at total depth on any well.", "The row where the fracture gradient less the LARGER of the collapse gradient and the pore pressure is smallest.", "The row where the collapse and fracture gradients are closest, regardless of where the pore pressure sits."]'::jsonb, 2, 'Measuring from the smaller candidate would include mud weights that take a kick.'),
  ('geomech', 'advanced', 'final', null, 7, 'One of the two wells is tightest at total depth. What is the other''s answer?', '["Also at total depth, in the lateral.", "At the kick-off point, a third of the way down a 2800 m hole.", "At the landing point, where the inclination reaches ninety degrees and the hole stops gaining vertical depth entirely.", "At the casing shoe, which is the shallowest depth the walk evaluates on that particular trajectory."]'::jsonb, 1, 'The hardest place to drill that well is nowhere near the reservoir.'),
  ('geomech', 'advanced', 'final', null, 8, 'Account for a minimum sitting where the hole first leaves vertical.', '["The rock is weakest exactly there.", "The pore pressure ramp begins there, which pushes the lower bound up sharply over a short interval of the hole.", "The dogleg at the kick-off produces a local stress concentration that the model treats as an additional load.", "The collapse gradient falls all the way through and the deviation below the kick-off widens the window."]'::jsonb, 3, 'The minimum is where the falling collapse trend and the trajectory effect cross.'),
  ('geomech', 'advanced', 'final', null, 9, 'Contrast a shear failure floor with a fluid influx floor as kinds of number.', '["One is a property of the rock''s fluid, the other of its strength, the stress field and the hole''s attitude.", "One is a pressure and the other a mud weight.", "One is measured directly by a formation tester and the other computed, so the two carry different confidence levels.", "One applies when static and the other when circulating, which is why the larger must be used at all times."]'::jsonb, 0, 'The pore pressure does not care about the hole. The collapse pressure cares about almost everything.'),
  ('geomech', 'advanced', 'final', null, 10, 'How does that change the remedies available?', '["Both give only mud weight.", "Pore pressure gives several, including the casing depth and the trip margin, while collapse gives only the mud weight.", "Pore pressure gives one lever; collapse gives several including the trajectory and the open hole time.", "Neither can be addressed by mud weight, since both are formation properties rather than wellbore ones."]'::jsonb, 2, 'Two of the collapse levers are outside the model entirely: open hole time and mud chemistry.'),
  ('geomech', 'advanced', 'final', null, 11, 'How does it change the uncertainty?', '["Both carry identical uncertainty.", "A pore-pressure-bound window is a firmer number than a collapse-bound one of the same width.", "A collapse-bound window is firmer, because the collapse gradient comes from the model rather than from an upstream study.", "The uncertainty depends on the width alone, rather than on which of the two candidates produced the lower bound."]'::jsonb, 1, 'The collapse bound carries the whole model''s uncertainty; the pore pressure bound carries the pore pressure''s.'),
  ('geomech', 'advanced', 'final', null, 12, 'And the consequence of being too light?', '["The same outcome either way.", "A kick in both cases, since a collapse-bound section is also underbalanced whenever the mud is below the lower bound.", "Lost circulation in the collapse case, because the failed material packs off the annulus and raises the pressure.", "A kick detected in minutes, against cavings and possible stuck pipe detected over hours to days."]'::jsonb, 3, 'The slower failure is the more expensive one to fix.'),
  ('geomech', 'advanced', 'final', null, 13, 'At the deep well''s tightest point, why is the collapse gradient below the density of water?', '["Because the rock there is strong: the strength interpolates to well over 100 MPa.", "Because the hole is nearly vertical there.", "Because the pore pressure is high, which reduces the effective stresses at the wall and therefore the shear failure risk.", "Because the inclination puts the hole close to the minimum horizontal stress direction at that depth."]'::jsonb, 0, 'A rock that strong tolerates almost any hoop stress the stress field can produce.'),
  ('geomech', 'advanced', 'final', null, 14, 'What is closing that well''s window instead?', '["The collapse gradient rising with depth.", "The inclination increasing through the build, which puts the overburden into the cross section and narrows the window.", "The pore pressure rising and the fracture gradient falling at the same time.", "The strength falling with depth, which raises the collapse gradient faster than the fracture gradient rises."]'::jsonb, 2, 'It narrows from both sides at once over the last 150 m of hole.'),
  ('geomech', 'advanced', 'final', null, 15, 'At the lateral well''s tightest point, what would a pore-pressure-only mud programme produce?', '["A perfectly stable hole.", "A hole full of cavings, because the collapse gradient is more than 300 kg per cubic metre above the pore pressure.", "A kick, because the collapse gradient is below the pore pressure and the mud would therefore be underbalanced.", "Lost circulation, because the mud weight needed to clear the pore pressure would exceed the fracture gradient there."]'::jsonb, 1, 'That is the failure mode nobody sees coming on a well drilled by pore pressure alone.'),
  ('geomech', 'advanced', 'final', null, 16, 'What is the general rule about which parameters matter?', '["Every parameter matters equally.", "The parameters that appear in both the stress model and the wall stress calculation always dominate the ones that do not.", "The sensitivity to any parameter is proportional to the window width at the point being evaluated.", "Which bound binds decides which parameters matter."]'::jsonb, 3, 'It tells you not to measure a friction angle in a pore-pressure-bound section, and to measure it in a collapse-bound one.'),
  ('geomech', 'advanced', 'final', null, 17, 'Turn the stress field right round and watch the forty degree well. What is the spread?', '["About 35 percent of its smallest value.", "Less than one percent.", "By a factor of three, which is comparable with the effect of sweeping the Poisson ratio over its plausible range.", "Not at all, since that well is pore pressure bound and the pore pressure has no directional dependence."]'::jsonb, 0, 'From a parameter that was never measured, on a well whose tightest point is deviated.'),
  ('geomech', 'advanced', 'final', null, 18, 'The lateral barely responds to the same rotation. Account for that.', '["Because its window is wider to start with.", "Because the horizontal stress difference is small at that depth, so the direction of the larger one barely matters.", "Because its tightest point is nearly vertical, and a nearly vertical hole does not care about the azimuth.", "Because the collapse criterion, which binds there, contains no stress azimuth as a parameter."]'::jsonb, 2, 'The sensitivity depends on how deviated the well is where its window is tightest.'),
  ('geomech', 'advanced', 'final', null, 19, 'Run the sandstone-to-shale seed span through the model. What is the effect?', '["Changes it by a few percent.", "Nearly triples the window on both wells.", "Widens one and narrows the other, because the two wells are bound by different criteria at their tightest points.", "Leaves it unchanged, since the ratio affects both bounds equally and therefore cancels out of the difference."]'::jsonb, 1, 'That is this course''s own sandstone-to-shale seed span.'),
  ('geomech', 'advanced', 'final', null, 20, 'Trace the mechanism by which a stiffer lateral response opens the mud weight range.', '["It lowers the collapse gradient directly.", "It reduces the axial stress at the wall through the Poisson correction, moving the least wall stress further from tension.", "It raises the frictional bounds, which lets the horizontal stress estimate grow without being clamped.", "A higher k0 gives higher horizontal stresses, which gives a higher fracture gradient."]'::jsonb, 3, 'At 0.20 k0 is 0.25 and at 0.35 it is about 0.538, so the horizontal stresses more than double.'),
  ('geomech', 'advanced', 'final', null, 21, 'Of all the sweeps, why does that one deserve the most attention?', '["Because the Poisson ratio is usually the least carefully determined input in the whole model.", "Because it is the easiest input to measure.", "Because it enters both the stress model and the wall calculation, which is why its effect compounds through them.", "Because it is dimensionless, so an error in it cannot be caught by a units check anywhere in the workflow."]'::jsonb, 0, 'The parameter with the largest influence is the one with the least evidence behind it.'),
  ('geomech', 'advanced', 'final', null, 22, 'Sweeping the friction angle on the deep well gives what?', '["About 18 percent, as on the other well.", "A small change that grows with the angle, since the frictional ratio accelerates as the friction angle rises.", "Exactly zero change, at every digit.", "An indeterminate change, because the tightest point moves as the friction angle is varied through the sweep."]'::jsonb, 2, 'Not approximately. Identically.'),
  ('geomech', 'advanced', 'final', null, 23, 'Explain how a sweep can produce no change whatsoever rather than a small one.', '["Because the friction angle is clamped there.", "Because that well''s tightest point is pore pressure bound, and neither of its bounds contains a friction angle.", "Because the collapse gradient there is below the density of water, so any change to it is numerically negligible.", "Because the frictional bounds are not active at that depth, so the stress model use of it also drops out."]'::jsonb, 1, 'The pore pressure has no friction angle in it, and the tensile criterion has none either.'),
  ('geomech', 'advanced', 'final', null, 24, 'On this evidence, what should be bought first?', '["Core, for a triaxial test suite.", "An extended leak-off test at each shoe, which measures the minimum horizontal stress directly and anchors the fracture end.", "An image log, which gives the stress azimuth and calibrates the collapse gradient against observed breakouts.", "A dipole shear sonic, for the Poisson ratio at log resolution."]'::jsonb, 3, 'The conventional wish list starts with core and a leak-off test, and on this fixture the shear log beats both.'),
  ('geomech', 'advanced', 'final', null, 25, 'Should the order of what to buy be carried from this well to the next one?', '["It should be computed for the well in hand rather than assumed from the conventional list.", "Core is always the right first purchase.", "The ranking is a property of the model, so one sweep serves for every well the model is subsequently applied to.", "The ranking changes with depth, so a separate sweep is needed for every section of every well being planned."]'::jsonb, 0, 'The conclusion here is fixture-specific and the method is not.'),
  ('geomech', 'advanced', 'final', null, 26, 'Describe the single page a drilling engineer actually works from.', '["The two bounds and the plan only.", "The three principal stresses and the pore pressure, from which the two bounds can be reconstructed by the reader.", "Pore pressure, collapse, fracture initiation and the planned mud weight against measured depth.", "The static mud weight, the circulating density, the surge and the swab, all over the whole trajectory."]'::jsonb, 2, 'Four curves because reading which lower-bound candidate is doing the work changes what you can do about it.'),
  ('geomech', 'advanced', 'final', null, 27, 'One line is nearly always absent from a real stability summary. Which?', '["The tightest measured depth.", "The tolerated breakout width the collapse number assumes.", "The window width, which most reports give as a range rather than as a value at the single tightest point.", "The breakout angle, which is rarely retained because it requires the full theta sweep to be kept in memory."]'::jsonb, 1, 'A collapse gradient with no stated width is unlabelled, and this engine''s is at zero width.'),
  ('geomech', 'advanced', 'final', null, 28, 'Name three things that would overstate what the model can support.', '["The clamp count and the quality score.", "The sensitivity band, since a reader who sees a range may quietly take the optimistic end of it as the answer.", "The breakout angle, which is in the borehole frame and will be misread as a compass bearing by most readers.", "Ten decimal places, a single number where a band belongs, or a curve above the last calibration depth."]'::jsonb, 3, 'Each of the three claims something the model cannot support.'),
  ('geomech', 'advanced', 'final', null, 29, 'Two drilling courses converge on one shoe depth. Where exactly?', '["At the casing point, with the shoe going at the shallower of their two answers.", "They do not meet at all.", "At the kill mud weight, which both compute from the pore pressure using the same true vertical depth at the bit.", "At the fracture gradient, which this course computes and the well control course measures with a leak-off test."]'::jsonb, 0, 'Both use the same fracture gradient to answer different questions.'),
  ('geomech', 'advanced', 'final', null, 30, 'Those two shoe depth calculations can differ. Explain the mechanism.', '["Because they use different fracture gradients.", "Because one is computed at the planning stage and the other is updated with measurements as the well is drilled.", "Because one is limited in the open hole and the other at the shoe, which is much shallower.", "Because one uses the static pore pressure and the other uses the equivalent circulating density at the same depth."]'::jsonb, 2, 'A shallow shoe can run out of kick tolerance while the open hole below still has a comfortable window.'),
  ('geomech', 'advanced', 'final', null, 31, 'Everything a hole actually experiences has to sit in one range. List it.', '["Only the static mud weight.", "The static mud weight, plus the circulating uplift, plus the surge, and minus the swab.", "The static mud weight and the equivalent circulating density, both of which the hydraulics course computes directly.", "The kill mud weight and the trip margin, both of which the well control calculation supplies for the section."]'::jsonb, 1, 'Four numbers in one window, and this course computes none of the transient three.'),
  ('geomech', 'advanced', 'final', null, 32, 'Weigh the elastic assumption: what does it enable, and where does it break down?', '["Nothing useful; it fails everywhere.", "A closed form for the deviated case, and it fails only in salt and in the most plastic of the shales encountered.", "Independence from the loading path, and it fails in a depleted reservoir where the stress path is not the burial path.", "Superposition, which makes the Kirsch solution valid, and it fails near the wall where the rock softens and dilates."]'::jsonb, 3, 'That near-wall redistribution is why a real breakout stabilises at a finite width instead of running away.'),
  ('geomech', 'advanced', 'final', null, 33, 'Which rock is most anisotropic, and which geometry makes that matter most?', '["Shale, and a deviated hole through it at an angle to the bedding.", "Salt, and a vertical hole through it.", "Limestone, and a horizontal hole in which the bedding runs parallel to the axis over the whole of the lateral section.", "Sandstone, and a vertical hole, since the grain fabric is aligned with the depositional direction in a clean sand."]'::jsonb, 0, 'Which is exactly the situation that gives the most trouble in the field.'),
  ('geomech', 'advanced', 'final', null, 34, 'Given the size of that error in shale, defend the direction-independent treatment.', '["Because the difference is negligible.", "Because no closed-form anisotropic Kirsch solution exists, so the wall stresses could not be evaluated at all.", "Because a transversely isotropic model needs five elastic constants and four are not on a standard log suite.", "Because the frictional bounds are derived assuming isotropy, and relaxing it would invalidate the clamping."]'::jsonb, 2, 'The model uses what a well has, which is a legitimate reason and not the same as the assumption being harmless.'),
  ('geomech', 'advanced', 'final', null, 35, 'One variable predicts shale trouble better than any other. Which, and why is it absent here?', '["The mud weight used.", "Open hole time.", "The inclination through the section, which determines how the bedding planes are loaded by the wall stresses.", "The unconfined compressive strength, which sets the collapse gradient and therefore the required mud weight."]'::jsonb, 1, 'It is why drilling fast and casing promptly works, and the model has no clock in it at all.'),
  ('geomech', 'advanced', 'final', null, 36, 'Account for the success of a non-aqueous system in a swelling formation.', '["It is denser than water-based mud.", "It lubricates the wall and reduces the mechanical damage from the string contacting the low side of the hole.", "It is more compressible, so pressure fluctuations from connections are damped before they reach the wall.", "It presents a low water activity and a membrane that limits transport."]'::jsonb, 3, 'A chemical solution to a problem that looks mechanical, and this model has no chemistry.'),
  ('geomech', 'advanced', 'final', null, 37, 'Cooling the wall does what to the two bounds?', '["Helps against collapse and hurts against fracture, because it reduces the hoop stress.", "Helps against both.", "Hurts against both, since a cooler rock is more brittle and therefore fails at a lower stress in either mode.", "Leaves both unchanged, since thermal effects act on the pore fluid rather than on the grain framework."]'::jsonb, 0, 'Prevented thermal contraction is a tensile stress, and it is why injection fracture gradients fall over time.'),
  ('geomech', 'advanced', 'final', null, 38, 'Returns disappear after six hours of steady circulation. What mechanism fits?', '["Losses starting the moment the pumps come on.", "Losses that stop when the pumps are shut down, which is the signature of an equivalent circulating density problem.", "Losses starting after hours of trouble-free circulation with nothing else having changed.", "Losses that only happen while tripping, which is the signature of a surge exceeding the fracture gradient."]'::jsonb, 2, 'The cooling penetrates further the longer it goes on, and the effective fracture gradient falls with it.'),
  ('geomech', 'advanced', 'final', null, 39, 'A hole meets a natural fracture. What happens to the upper bound?', '["Nothing. The intact criterion still applies.", "It collapses to roughly the normal stress across the fracture, which can be well below the intact value.", "It rises, because a fractured rock relieves the hoop stress concentration and therefore resists tensile failure better.", "It becomes indeterminate, because the fracture opening pressure depends on the aperture, which is never measured."]'::jsonb, 1, 'The hole does not have to split anything: it only has to open a plane that already exists.'),
  ('geomech', 'advanced', 'final', null, 40, 'In a formation full of existing planes, what number should cap the mud weight?', '["The computed fracture initiation pressure.", "The overburden gradient, since a fracture cannot propagate against a stress larger than the vertical in a normal regime.", "The pore pressure plus the intact tensile strength, which is when the first natural fracture would begin to open.", "A measured leak-off, a loss history, or the minimum horizontal stress."]'::jsonb, 3, 'Using the minimum horizontal stress is a cheap and defensible conservatism.'),
  ('geomech', 'advanced', 'final', null, 41, 'List the topics that appear in the lessons and in no graded field.', '["Inelastic and anisotropic behaviour, time, chemistry, thermal stress, and natural fractures and bedding.", "The two failure criteria and the three checks.", "The overburden, the pore pressure, the stress azimuth, the Poisson ratio and the friction angle, all of them estimated.", "Anything involving a deviated well, since the closed forms hold only for a vertical hole and the rest is unverified."]'::jsonb, 0, 'The go-live migration refuses to run if any graded field key names one of them.'),
  ('geomech', 'advanced', 'final', null, 42, 'Reduce the whole Expert tier to one claim.', '["The mud window is a property of the trajectory.", "The tightest point is not reliably at total depth, and on one of the two wells here it sits at the kick-off point.", "Which bound binds decides which parameter matters, and that reorders the whole list of what to measure.", "The Poisson ratio moves the answer more than any other input, and it usually comes from a lithology seed table."]'::jsonb, 2, 'The others are true and are consequences of it. That one is what the tier discovered.');
