import sys; sys.path.insert(0, '/root/dc-wavekit')
from bankkit import emit, finish
Q=[]
def q(k,p,c,ds,e): Q.append((k,p,c,ds,e))

# D1 Associate final exam, 42 questions, seven drawn from each module's
# lessons and asked from a different angle than the module banks.
# Sources: digest sections 1 to 16 and 32. Every figure is printed there.

# m01, what data quality means
q(3, "You receive a log whose gamma ray reads fully complete and yet fails the definitional range check at the same bottom entries. What does that pattern usually mean?",
 "The file's placeholder, such as -999.25, was left in place: completeness counts it present and the range check sees a value below the limit.",
 ["The gamma ray tool saturated at the bottom of the hole and wrote its largest reading there.",
  "The index skipped samples at the bottom, so the range check compared values against the wrong depths.",
  "The range check ran before completeness, and the engine flags whatever an earlier check did not."],
 "A channel that reads complete and fails its range check at the same entries is what a sentinel left in place looks like. On EKENE-7 the four -999.25 values at entries 236 to 239 read completeness 1.000000 and 4 range failures. The practical habit is to run the two checks side by side before converting anything; neither check depends on the other's order, and the index plays no part in a range check."),

q(0, "A shut-in day is recorded with an oil rate of 0. Why does it matter that the engine counts that zero as a present value?",
 "Because a zero rate while shut in is the correct record, and counting zeros as missing would make every shut-in day look like a lost reading.",
 ["Because the rate check flags every zero as a rate while shut in, and it needs the zero present in the column to do so.",
  "Because a zero is the engine's own marker for a missing rate, and the completeness check counts it as missing in every column it reads.",
  "Because zero is the definitional minimum of a rate, so a zero rate has to be present in the column to be flagged as falling below it."],
 "Missing is null, undefined or NaN, and a zero is present. EKENE-3's day 60 is shut in with 0.000000 oil: the rate check counts it among the 87 days checked and does not flag it, since a zero rate while shut in is correct. The rate minimum of 0 is inclusive, so a zero is inside it, and a zero is never the engine's marker for anything."),

q(0, "Where does a result from the engine record the convention the check used, such as a tolerance or where its limits came from?",
 "In its `basis` block, which every result carries beside its figures.",
 ["In the `reason` of its first flag, which states the rule and its settings once for the whole call.",
  "Nowhere in the result: the caller keeps the settings, and the engine returns only counts and flags.",
  "In the `field` of the result, which names the setting that most affected the figures."],
 "Every result carries a `basis` block naming its convention; the caller range check's basis reads \"limits supplied by the caller\", for example. A reason describes one flag, and `field` belongs only to a refusal, where it names the input refused."),

q(3, "A flag carries its figure twice: as a numeric field such as `value` or `drop`, and inside the `reason` sentence. Which should you reason with?",
 "The numeric field, quoted at six decimals, with the reason kept as the engine's own sentence for a person to read.",
 ["The reason, since it prints the figure exactly as the engine computed it, with every digit it has.",
  "Either, since the field and the reason always print a figure the same way.",
  "The reason, since the field is rounded to six decimals before it is returned."],
 "The flag's numeric fields are what a lesson reasons with, at six decimals: the day 70 `drop` is 7496.700000. The reason prints each figure as the shortest decimal that reads back to its field, written for a person scanning a list, so the two can look different: the day 70 reason prints 1338506.2 where the `previous` field is quoted as 1338506.200000."),

q(2, "A production engineer asks the engine to hand back EKENE-3's sheet with the bad days corrected. What will it give?",
 "A set of flags with their rules and reasons on the sheet as delivered; it does not fill, repair or delete a value.",
 ["A corrected sheet, with each negative rate set to zero and each missing day filled in from its present neighbours.",
  "A corrected sheet for the flagged days only, with a basis note listing every value it changed.",
  "A refusal, since a sheet carrying planted defects has to be cleaned before any check will run on it."],
 "The engine does not fill, repair or delete a value, and it does not decide whether a flagged value is wrong; each fix is a decision for a person reading the flag. It runs every Associate check on the sheet with its defects in place and refuses only inputs it cannot answer, such as an empty series or an unlisted unit."),

q(2, "Which dimension does the engine assign to `coverage`?",
 "Completeness, since coverage asks how much of an interval the present samples span.",
 ["Validity, since coverage tests each step between samples against a stated maxStep limit.",
  "Consistency, since coverage compares each channel with the shared depth index it hangs on.",
  "Uniqueness, since coverage refuses an index holding a repeated depth."],
 "The function table files both `completeness` and `coverage` under completeness: one counts present values over n, the other measures the fraction of a depth or time interval spanned by steps no longer than maxStep. The refusal of a repeated or backward index is a precondition of the calculation, and a step test against a limit is what the index check does under validity."),

q(1, "Under which dimension does the engine file `waterCutCheck` and `phaseSumCheck`?",
 "Consistency, since each compares figures on the sheet that should agree with one another.",
 ["Validity, since each tests a value against a limit fixed by the definition of the quantity.",
  "Completeness, since each skips days with a missing part and so measures what is there.",
  "Plausibility, since each flags a day that stands apart from the others on the sheet."],
 "The engine files the cumulative, water cut, phase sum and frozen run checks under consistency: channels that should agree, checked against one another. Skipping days with a missing term is a rule of the check, and plausibility is the Professional tier's dimension."),

# m02, is it there
q(1, "EKENE-7's neutron reads a `nullFraction` of 0.012500. What completeness does the same call report?",
 "0.987500, since the two figures describe the same count of 240 from opposite sides.",
 ["0.012500, since completeness and the null fraction are two names for one figure.",
  "0.950000, since the neutron shares the density's pad lift across entries 80 to 91 of the log.",
  "0.965217, the fraction of the interval the neutron spans at a half-foot maxStep."],
 "The two figures always add to one: 3 lost samples give a null fraction of 0.012500, so the present share is 0.987500. The density reads 0.950000 because of its own pad lift, which the neutron does not share, and 0.965217 comes from the coverage call, which divides feet by feet."),

q(2, "EKENE-3's cumulative oil column reads a completeness of 0.988889. What lies behind that figure?",
 "One missing day in 90, day 69, the lost reading just before the day 70 keying error.",
 ["The keying error on day 70, which completeness counts as a missing value once the cumulative falls.",
  "The three days of the oil meter outage, days 31 to 33, carried into the cumulative column.",
  "Eleven days on which the cumulative repeats its previous value, which completeness counts as missing."],
 "The cumulative oil column has 1 missing of 90, a single gap run at day 69, for 0.988889. A falling or repeated value is present, and a present value is judged by other checks. The oil outage leaves the cumulative column complete on those days."),

q(0, "At a half-foot maxStep, EKENE-7's neutron has four holes in the interval 8400 to 8515 ft. Where do they come from?",
 "Three straddle its three single missing samples, and the fourth is the index skip at 8474.500000 to 8475.500000 ft.",
 ["All four straddle missing neutron samples, one of them a fourth neutron sample lost at the depth where the index skips a row.",
  "Two come from its missing samples and two from the density's pad lift, which the neutron shares.",
  "Each is a step equal to maxStep, which coverage counts as uncovered whenever the step is exactly half a foot long."],
 "Each single missing sample leaves a step between its present neighbours longer than half a foot, which a half-foot maxStep calls a hole, and the index skip after entry 149 makes the fourth. A step equal to maxStep covers. The neutron has only 3 missing samples, and the density's gap is the density's own."),

q(2, "Over the stated interval of the log, the gamma ray, its placeholders already nulled, is run through coverage with a one-foot maxStep. What comes back?",
 "Coverage 1.000000 with 115.000000 ft covered and no holes, since the step across the index skip is now within maxStep.",
 ["Coverage 0.991304 with 114.000000 ft covered, since a skipped index sample stays a hole at any maxStep the caller states.",
  "Coverage 0.983333, the same as its completeness once the four sentinels at the bottom are converted to null.",
  "A refusal, since a maxStep longer than the logging step would hide the skipped sample."],
 "At a one-foot maxStep the step from 8474.500000 to 8475.500000 ft covers, so the gamma ray reads 1.000000 and 115.000000 ft. 0.991304 is the half-foot reading. The converted sentinels sit at entries 236 to 239, below the interval's end, and the engine refuses no maxStep for being generous."),

q(0, "How should a caller choose the `maxStep` for a coverage figure going into a report?",
 "From the question: the logging step if every sample matters, something longer if a single dropout does no harm, and state it beside the figure.",
 ["Leave it to the engine, which sets maxStep to the median step of the index when none is passed.",
  "Always use the logging step, since any longer maxStep makes coverage a meaningless figure.",
  "Always use twice the logging step, which the engine treats as the standard allowance for dropouts."],
 "maxStep is the caller's statement of the longest step that still counts as data. There is no single right value: half a foot tells the truth about a file logged at that step, and one foot tells you a single gap can be bridged. A coverage figure quoted without its maxStep cannot be checked or compared."),

q(1, "Why do missing values lower coverage at all, when coverage measures depth and not samples?",
 "Because a missing sample lengthens the step between the present samples on either side of it, and a long enough step is a hole.",
 ["Because coverage subtracts half a step for each missing sample from the covered length.",
  "Because coverage multiplies the covered length by the channel's completeness before it reports.",
  "Because the index loses a row at every missing value, so the depths around it move apart."],
 "Coverage walks from one present sample to the next, and missing values matter only because they lengthen that step. The index keeps its rows at a null; that is why a null can be counted by completeness while a skipped index row cannot. Coverage never uses the completeness figure."),

q(3, "EKENE-3's water cut column is missing 5 days. How many gap runs does `completeness` report, and where do they start?",
 "Three: day 31 for 3 days, day 47 for 1, and day 60 for 1.",
 ["One: a single run of 5 days, since completeness joins the missing days of one column into one flag.",
  "Two: day 31 for 3 days, and one run holding days 47 and 60, the two days the rate check flags.",
  "Five: one flag for each missing day, since a water cut is checked day by day."],
 "A gap run is a maximal stretch of consecutive missing values: days 31 to 33, then day 47 alone, then day 60 alone, so 3 runs. The first coincides with the oil outage, day 47 with the negative allocation entry and day 60 with a shut-in day. Days 47 and 60 are not consecutive, and a run of one is still a run."),

# m03, is it valid
q(3, "A temperature channel in degF carries a value of exactly -459.670000. What does the range check do?",
 "It passes, since the degF minimum of -459.670000 is not marked excluded and a value on it is inside.",
 ["It fails, since no reading can reach absolute zero and the minimum is exclusive.",
  "It is refused, since temperatures must be checked in K and the engine converts nothing from degF itself.",
  "It passes only in K, where the minimum is 0, so the caller must convert the value to K before checking it."],
 "The degF limit has a minimum of -459.670000, and the minimum excluded column reads no, so the bound itself is allowed; the engine fires strictly beyond it. degF is one of the three temperature units the engine lists, and it never converts one unit to another."),

q(1, "The engine's limit table holds 16 channel and unit pairs. How does it reach 16 from its 10 channels?",
 "Some channels are listed in more than one unit, such as sonic in us/ft and us/m and temperature in degC, degF and K.",
 ["Each channel carries a lower and an upper limit, and six of them carry both as separate rows.",
  "Six pairs are caller plausibility ranges the engine ships beside its definitional limits.",
  "The rate and cumulative channels are each listed once per phase, oil, water and gas."],
 "The table has 16 channel and unit pairs across 10 channels because sonic, caliper, absolutePressure and temperature each appear in more than one unit; rate and cumulative are listed once each, in any unit. The engine ships no plausibility ranges, and limits are columns of a row."),

q(0, "A channel whose true values are small fractions is written in percent while the call still names v/v, and every percent value it carries is at or below one. What does the fraction limit report?",
 "Nothing: each value sits inside [0, 1], so the percent slip passes without a flag.",
 ["An above-maximum flag on each value, since the engine checks the unit label against the size.",
  "A refusal naming `unit`, since percent is not a unit the fraction channel lists.",
  "A below-minimum flag on each value, since a percent is read against a minimum of 1."],
 "The fraction check catches a percent value only when it is larger than one. A value at or below one sits inside the definitional range and passes, and v/v is a listed unit, so nothing is refused. The engine checks values against limits and cannot see how a number was meant; the fraction channel's range is 0 to 1."),

q(2, "Which EKENE-7 channel fails the definitional range check at exactly one entry, and why?",
 "The resistivity, at entry 120, where a zero meets an exclusive minimum.",
 ["The neutron, at entry 150, the first of the samples written in percent.",
  "The gamma ray, at entry 236, the first sentinel below the minimum.",
  "The density, at entry 80, the first sample of the pad lift."],
 "RT fails once, at entry 120, with the engine's reason \"value 0 is below the minimum 0 (the minimum itself is not allowed)\". The neutron fails 10 entries, 150 to 159, the gamma ray 4, entries 236 to 239, and the density 0: its missing samples are not checked against a limit."),

q(1, "With its sentinels converted to null, EKENE-7's gamma ray is checked against a caller range of 0 to 150 gAPI. Why does it report 236 checked?",
 "The four converted samples are missing, and a missing value is never checked against a limit.",
 ["The four sentinels fall outside the caller range and are removed before the count.",
  "The caller range excludes the bottom four samples, which lie below the logged interval of the channel.",
  "Four samples read above 150 gAPI and are counted as failed and left out of the checked count."],
 "240 samples less the 4 converted to null leaves 236 present values, and the check reports 236 checked and 0 failed. Failed values are still counted as checked, and nothing is removed; the basis reads \"limits supplied by the caller\"."),

q(1, "EKENE-3's day 59 ran 18.500000 hours with a positive oil rate. What does the rate check make of the rate's size for a partial day?",
 "It flags nothing: the day is not shut in, and the engine carries no rule for whether a rate suits the hours flowed.",
 ["It flags the rate as rate-while-shut-in, since fewer than 24.000000 hours on marks the day as a shut-in day.",
  "It scales the rate up to 24.000000 hours and flags the day if the scaled figure exceeds either of its neighbours' rates.",
  "It refuses the call, since hoursOn must be 0 or 24.000000 for the shut-in rule to apply."],
 "Only a status of 'shut-in' or zero hours makes a day shut in, so day 59 is not, and a positive rate on it is allowed. Whether the rate is plausible for 18.500000 hours of flow is a different question, and the engine has no rule for it. It scales nothing and refuses no partial day."),

q(3, "The same EKENE-3 oil column is checked once with the status column and once with the hours on column instead. How do the two runs compare?",
 "Both fail 2 days, since either column is enough to reveal the rate carried onto the shut-in day.",
 ["Status fails 2 days and hours on fails 1, since an hours on column alone cannot mark any day as shut in.",
  "Status fails 1 day and hours on fails 2, since the status column never names day 61.",
  "Both fail 3 days, since each column adds its own flag to the negative rate on day 47."],
 "The course's table reads 2 failed with rates and status, 2 with rates and hours on, and 2 with both. Day 61 is 'shut-in' in the status column and has 0.000000 hours on, and either marks it shut in. With rates alone the count is 1, the negative rate."),

# m04, the depth and time index
q(0, "Why does the engine take the median of the steps as the expected step, when it could take their mean?",
 "The median returns the step the tool was set to, while one long step would pull a mean to a figure matching no step in the file.",
 ["The median needs fewer steps than the mean, so it works on short indexes where a mean cannot.",
  "The mean would include the backward steps, while the median excludes them by construction.",
  "The median and the mean agree on any regular log, and the median is simply faster."],
 "Almost every EKENE-7 step is 0.500000 ft and one is longer; the median ignores the long one and returns 0.500000, while a mean would drift toward the long step and leave every regular step a little away from it. Backward steps are left out because only steps in the stated direction count, which applies whatever statistic is taken."),

q(1, "Between splice entries 9 and 10 the depth jumps from 8523.500000 to 8524.500000 ft. What does that jump mean for the record?",
 "A depth was skipped: the forward step is longer than the expected 0.500000 ft, so one row between them was never logged.",
 ["A repeated depth: 8524.500000 ft appears earlier in the splice, and the step rule reports the repeat.",
  "A lost entry: entry 10 has no depth, and the step to entry 11 is measured across it.",
  "A reversal: the index steps back from entry 9 and then forward again at entry 10."],
 "Entry 9 is at 8523.500000 ft and entry 10 at 8524.500000 ft, a forward step longer than the expected 0.500000 ft, so one depth was never logged. The lost entry is entry 12, the reversal is at entry 5, and 8524.500000 ft appears only once on the splice."),

q(3, "On the splice you replace the null at entry 12 with the depth that correctly fills the gap between entries 11 and 13. Which flags disappear together?",
 "The missing-index flag at entry 12 and the irregular step at entry 13, since the lost row showed up as both.",
 ["The missing-index flag at entry 12 alone, since the step to entry 13 was never measured across a null.",
  "Every irregular step on the splice, since the lost entry had set the expected step for the whole of the index.",
  "The irregular steps at entries 6 and 13, since both were measured from an entry that was not present."],
 "The step after a lost entry is measured from the last present entry, so entry 12's loss showed up twice: once as missing and once as the long step from entry 11 to entry 13. Filling it removes both. Entry 6 follows the reversal at entry 5, which is present, and the expected step is the median of the forward steps, which one entry does not set."),

q(2, "The log's own depth column, all of it, goes through the index check. How many repeated depths and backward steps turn up, and is it monotonic?",
 "0 duplicates, 0 reversals and monotonic true: the two duplicates belong to the separate splice index.",
 ["2 duplicates, 1 reversal and monotonic false, since the full log index includes the splice.",
  "0 duplicates, 1 reversal and monotonic false, since the skipped sample after entry 149 steps back onto an earlier depth.",
  "1 duplicate, 0 reversals and monotonic true, since the skipped sample leaves one depth repeated."],
 "The full log index reads 0 duplicates, 0 reversals, 1 irregular step and monotonic true. The skipped sample is a step forward that is too long, which is an irregular step. The splice is a separate 15-entry index where two runs meet."),

q(0, "On the splice you delete the second 8523.000000 ft, the depth at entry 8. Which duplicate is still flagged?",
 "The one at the old entry 5, whose 8521.500000 ft repeats entry 3, a match two rows back.",
 ["None, because the only repeated depth on the splice was the pair of rows at 8523.000000 ft.",
  "The one at entry 7, which now repeats a depth later in the index.",
  "The one at entry 9, which moves up one row after the deletion and repeats its new neighbour."],
 "A duplicate is a value equal to any earlier value. Entry 5 at 8521.500000 ft repeats entry 3, and a neighbour-only check would have missed it; deleting entry 8 does not touch it. Only earlier values count, and no remaining depth repeats its neighbour."),

q(2, "When is it worth passing `expectedStep` to `indexCheck` yourself?",
 "When the index is short, when most of it is irregular, or when the logging step is known from the header.",
 ["Only when the index is decreasing, since the engine infers a step for increasing indexes alone and refuses the rest.",
  "Only when duplicates are present, since a stated step is what lets the engine find them.",
  "Always, since the inferred step is the mean of the steps and is pulled by every long one."],
 "The engine infers the median of the steps in the stated direction, which works when most steps are regular. A short or mostly irregular index gives a poor median, and a header can state the step directly. The declared-decreasing index infers 0.500000 on its own, and duplicates do not depend on the step at all."),

q(3, "A caller sets a step tolerance of 0.6 on a half-foot splice to quiet its flags. What would that setting hide in a real file?",
 "Skipped samples: with the step test that loose, a depth never logged no longer shows as an irregular step.",
 ["Repeated depths, since a tolerance wider than the step lets two equal depths pass as a single regular step.",
  "The reversal at entry 5, since a backward step of half a foot then sits inside the tolerance on the step size.",
  "The lost entry at entry 12, since its null depth is then read as a step that sits inside the loosened tolerance."],
 "A tolerance loosens the step test only. At 0.6 the splice reads 0 irregular steps, and the skipped depth at entry 10 is no longer visible, while both duplicates, the reversal and the missing entry are still flagged. A tolerance is a statement about what size of error you accept, and it should come from the tool and the question."),

# m05, does it agree with itself
q(0, "Why does a cumulative check carry a tolerance at all, when a cumulative can never fall?",
 "So the small corrections meters and allocation systems make, which can nudge a cumulative down, are read as noise up to a stated size.",
 ["So the check can ignore the missing days, which would otherwise count as falls to zero.",
  "So the check can accept a keying error of a few thousand barrels as ordinary meter drift.",
  "So a rise of more than the tolerance is flagged as well, catching gains that are too large."],
 "A tolerance exists because small corrections are real; the dataset tables use 0, which accepts no fall at all. A tolerance wide enough to swallow a keying error hides it: at 8000 bbl the day 70 drop of 7496.700000 bbl is not flagged. Missing days are skipped by the last-present-value rule, and a rise is never flagged."),

q(3, "Suppose EKENE-3's water cut column held water over oil, the water-oil ratio, in place of the cut. What will `waterCutCheck` report?",
 "A mismatch day after day, since the engine's cut is water / (oil + water); the fix is a relabelled column.",
 ["Nothing, since the engine accepts any of the three water cut definitions when the rates agree.",
  "An out-of-range flag on every day, since a water-oil ratio is always above 1.",
  "A refusal naming `waterCut`, since the column does not hold a liquid-basis cut."],
 "The engine checks a liquid-basis cut only. On day 10 the computed cut is 0.183105 and the water-oil ratio 0.224147, so a ratio in the column disagrees every day. A ratio is below 1 whenever water is less than oil, as on day 10, so the out-of-range rule would not catch it; the engine refuses only when neither a cut nor both rates are given."),

q(1, "On day 10 of EKENE-3 the engine computes a water cut of 0.183105. What is 0.816895 on the same day?",
 "The oil cut, oil / (oil + water), which is the complement of the liquid-basis water cut.",
 ["The water-oil ratio, water / oil, which the engine checks beside the water cut on each day.",
  "The reported water cut on day 10, which disagrees with the computed value in the fourth decimal.",
  "The allowed difference for day 10's phase sum at the default relative tolerance on the total."],
 "0.816895 is derived as oil over liquid, the oil cut; with the water cut it makes up the whole liquid. The water-oil ratio on day 10 is 0.224147. The engine checks only the liquid-basis water cut, and a phase sum's allowance is 0.005 of that day's gross total."),

q(2, "Why does the engine scale its default phase sum allowance by the gross total?",
 "Because a relative allowance grows with the day's total, giving a high-rate day a proportionally wider allowance than a low-rate day.",
 ["Because the total is the most accurate figure on the sheet, so errors are always in the parts.",
  "Because an allowance on the parts would flag every day on which a part was zero.",
  "Because a fixed number of barrels is refused by the engine as a tolerance."],
 "The default allowance is 0.005 of the TOTAL: on day 40 that is 8.870000 and on day 41 8.991000. The absolute tolerance is there for a floor of barrels and defaults to 0; 50 bbl/d is an allowed stated setting. Days 31 to 33 carry no total and are not checked at all. The engine makes no claim about which figure is more accurate."),

q(3, "EKENE-7's sonic holds 83.200000 us/ft from entry 175 to entry 183. Why does `frozenRuns` treat that as a sign of trouble in a log?",
 "Because the rock changes every half foot, nine identical readings in a row suggest the tool stopped responding.",
 ["Because 83.200000 us/ft falls outside the definitional limit for a slowness recorded in us/ft on the logging run that recorded it.",
  "Because the nine readings are missing values, which the frozen-run check counts as a run of missing samples.",
  "Because any repeated reading in a log is a defect in itself, whatever the length of the run it belongs to."],
 "The run of 9 is present, valid and in range; its only sign is that the value does not move, where the rock under a logging tool changes every sample. The slowness is positive, so it is inside its limit, and a run must reach minRun, 5 by default, before it is flagged."),

q(2, "A frozen gas meter also drops one reading in the middle of its stuck stretch. How does `frozenRuns` see it?",
 "As two shorter runs, since a missing value ends a run, and either may fall under minRun and go unflagged.",
 ["As one run across the gap, since the check compares each present value with the first value of the run it joins.",
  "As one run with the missing day counted in it, since a held meter records nothing new on that day anyway.",
  "As a refusal, since frozenRuns needs a complete series and a gap inside the stuck stretch stops the call."],
 "A missing value ends a run, so a frozen meter that also drops a reading shows as two shorter runs, and both may fall under minRun. The first-value rule decides which present values join a run; it does not bridge a gap. frozenRuns refuses a minRun below 2 and does not refuse a series with a gap."),

q(0, "For a channel that is steady by nature, such as a shut-in pressure, what should a caller do about the frozen-run defaults?",
 "Set minRun and the tolerance from what the channel should do, since long equal runs there are the truth.",
 ["Keep minRun 5 and tolerance 0 as they are, since the defaults were chosen to suit every channel in every well.",
  "Lower minRun to 1, so that every repeated value in the channel is flagged on its own and read by a person.",
  "Raise the tolerance until the flags stop, since a channel that is steady by nature has no frozen runs to find."],
 "The defaults, minRun 5 and tolerance 0, are Petrolord choices, and both may be wrong for a channel whose long equal runs are real. The engine refuses minRun below 2, since a run of one is every value. A tolerance raised until the flags stop hides the fault the check exists for."),

# m06, names and one dataset end to end
q(1, "Which steps of the stated normalisation turn \"Ekene 3\" into EKENE3?",
 "Upper case turns Ekene into EKENE, and keeping only A to Z and 0 to 9 removes the space inside the name.",
 ["Trim removes the space inside the name, and then NFKD raises each lower-case letter of Ekene to its capital.",
  "Stripping leading zeros removes the space, which the engine reads as a zero written before the digit 3 in the name.",
  "Nothing: Ekene 3 matches EKENE3 as written, which makes the pair exact."],
 "Upper case makes \"Ekene\" and \"EKENE\" the same, and the letter filter drops spaces and hyphens inside a name; trim acts only at the ends. NFKD decomposes accented letters and changes no case. The raw strings differ, so the pair is reported as normalised."),

q(2, "EKENE-1 and EKENE-10 normalise to EKENE1 and EKENE10, one edit apart. What does the engine report for the pair with the defaults?",
 "No pair at all, since 1 and 10 are different digits, and the digit rule keeps two real wells apart.",
 ["A near pair, since one added digit is a single Levenshtein edit, within the default maxDistance of 1.",
  "A normalised pair, since stripping leading zeros turns 10 into 1.",
  "An exact pair, since both names share the stem EKENE-1 as written."],
 "The normalised forms are 1 edit apart but carry 1 and 10, so the digit rule fails and they are not near; the course's table reads false for the pair. Leading zeros are stripped only at the front of a digit group, so 10 stays 10. The raw strings differ, so nothing is exact."),

q(0, "What happens to the pairs reported on a list when `maxDistance` is raised above its default of 1?",
 "The near rule reaches further, so the list to review can grow as names that are merely similar get paired.",
 ["The engine reports fewer pairs, since a larger distance merges near pairs into the normalised class above them.",
  "Nothing can change, since the digit rule alone decides every near pair and the distance is never consulted.",
  "The engine refuses, since maxDistance must stay at 1 for well names."],
 "The default of 1 catches one dropped, added or replaced character; a larger value reaches further and can pair names that are merely similar, and it never removes a pair. The digit rule still applies, but among names with matching digits a wider distance admits more. Classes are decided by the rule each pair meets, and maxDistance is a caller setting."),

q(3, "With the settings of the one-dataset table, put EKENE-3's flags in date order. Which comes first on the sheet?",
 "The water cut written in percent on days 20 to 24.",
 ["The oil meter outage on days 31 to 33, which empties the oil and gross columns.",
  "The truck load booked into the gross total on day 40, the first phase sum failure.",
  "The negative allocation entry on day 47, the first rate the rate check flags."],
 "In date order: days 20 to 24 carry the percent water cut, days 31 to 33 the oil outage, day 40 the truck load, day 47 the negative allocation entry, day 55 the copied water cut, day 61 the carried-forward rate, day 70 the keyed cumulative and days 74 to 81 the stuck gas meter."),

q(3, "On the one-dataset table for EKENE-7's log, what do `indexCheck` on the depth index and `frozenRuns` on the sonic report?",
 "indexCheck 1 entry failed and 1 flag; frozenRuns 9 entries failed and 1 flag.",
 ["indexCheck 2 entries failed and 2 flags; frozenRuns 9 entries failed and 9 flags, one for each held reading.",
  "indexCheck 1 entry failed and 1 flag; frozenRuns 1 entry failed and 1 flag, the first reading of the stuck run.",
  "indexCheck 0 entries failed, since the log index is monotonic; frozenRuns 9 entries failed and 1 flag."],
 "The index check finds the one irregular step after entry 149, 1 entry and 1 flag. frozenRuns faults the 9 entries of the stuck sonic and returns 1 flag for the run. A monotonic index can still carry an irregular step, and a run is one flag however long it is."),

q(1, "At the end of this tier, what is the answer to whether EKENE-3's sheet is fit to use?",
 "The tables of checks with their settings stated, and a note on what the owner of the file must decide about each flag.",
 ["A single pass or fail for the whole sheet, taken from the weakest of the six checks in the tables and stated once.",
  "The sheet with every flagged value removed, so that only the data fit to use remain in the file handed back to the owner.",
  "A list of the values that stand apart from the rest, ranked by how far each one sits."],
 "The tier's answer is the pair of tables with their settings and a note on what the owner must decide, since every flag is a question and a count without its setting cannot be reproduced. The engine removes nothing and gives no single verdict, and which values stand apart is the next tier's question."),

q(2, "`duplicateIdentifiers` reports EKENE-7, EKENE 7 and ÉKENE-7 as normalised pairs. Which spelling does it keep as the master record?",
 "The choice is left open: it reports the pairs with their class and reason, and choosing the master spelling is for whoever owns the well list.",
 ["The first spelling in the list, EKENE-7, which the engine keeps and marks the others as copies.",
  "The normalised form, EKENE7, which the engine writes back over all three entries.",
  "The spelling that appears in the most databases, which the engine counts across the three lists."],
 "The check does not merge names or pick a preferred spelling; it reports pairs with their class and reason, for example \"EKENE-7\" and \"EKENE 7\" are the same after normalisation (EKENE7). Which spelling becomes the master record is the owner's decision, and the engine keeps no count of databases."),

emit(Q, '/root/dai-wip-dataqc/banks/d1b_exam.json', expect_n=42)
finish()
