// The gsa capstone case files, generated by tools/course-waves/gsa/gen_course.py
// from the engine's own inputs (gsa_capstone.mjs --inputs). Only the capstone card
// imports this module: no panel preloads a case, and the graded answers are not
// stored anywhere in the app.
import ozubu_case from './ozubu_case.json?raw';
import ifeyi_case from './ifeyi_case.json?raw';
import nwaka_case from './nwaka_case.json?raw';

export const GSA_CASE_FILES = {
  beginner: [
    { name: 'ozubu_case.json', text: ozubu_case },
  ],
  intermediate: [
    { name: 'ifeyi_case.json', text: ifeyi_case },
  ],
  advanced: [
    { name: 'nwaka_case.json', text: nwaka_case },
  ],
};
