// The prms capstone case files, generated by tools/course-waves/prms/gen_course.py
// from the engine's own inputs (prms_capstone.mjs --inputs). Only the capstone card
// imports this module: no panel preloads a case, and the graded answers are not
// stored anywhere in the app.
import abagana_case from './abagana_case.json?raw';
import awkuzu_case from './awkuzu_case.json?raw';
import isuofia_case from './isuofia_case.json?raw';

export const PRMS_CASE_FILES = {
  beginner: [
    { name: 'abagana_case.json', text: abagana_case },
  ],
  intermediate: [
    { name: 'awkuzu_case.json', text: awkuzu_case },
  ],
  advanced: [
    { name: 'isuofia_case.json', text: isuofia_case },
  ],
};
